DPC++ Runtime: sycl::_V1 Namespace Reference
sycl::_V1 Namespace Reference
Namespaces
access
detail
ext
ext
half_precision
info
native
opencl
property
property
usm
Classes
struct mode_tag_t
struct mode_target_tag_t
struct remove_decoration
struct remove_decoration< const T >
struct remove_decoration< T * >
struct remove_decoration< const T * >
struct remove_decoration< T & >
struct remove_decoration< const T & >
class accessor
class local_accessor_base
Local accessor.
class accessor< DataT, Dimensions, AccessMode, access::target::local, IsPlaceholder >
class host_accessor
class accessor< DataT, Dimensions, AccessMode, access::target::host_image, IsPlaceholder >
Host image accessor.
class unsampled_image_accessor
class host_unsampled_image_accessor
class sampled_image_accessor
class host_sampled_image_accessor
class vec
class sycl::vec ///////////////////////// Provides a cross-patform vector class template that works efficiently on SYCL devices as well as in host C++ code.
class multi_ptr
class atomic_ref
class backend_traits
class range
Defines the iteration domain of either a single work-group in a parallel dispatch, or the overall Dimensions of the dispatch.
class buffer
Defines a shared array that can be used by kernels in queues.
class context
The context class represents a SYCL context on which kernel functions may be executed.
class id
A unique identifier of an item in an index space.
class marray
Provides a cross-platform math array class template that works on SYCL devices as well as in host C++ code.
class item
Identifies an instance of the function object executing at each point in a range.
class group
class nd_item
Identifies an instance of the function object executing at each point in an nd_range.
class h_item
Identifies an instance of a group::parallel_for_work_item function object executing at each point in a local range passed to a parallel_for_work_item call or to the corresponding parallel_for_work_group call.
struct is_device_copyable
is_device_copyable is a user specializable class template to indicate that a type T is device copyable, which means that SYCL implementation may copy objects of the type T between host and device or between two devices.
struct is_device_copyable< std::array< T, 0 > >
struct is_device_copyable< std::array< T, N > >
struct is_device_copyable< std::optional< T > >
struct is_device_copyable< std::pair< T1, T2 > >
struct is_device_copyable< std::tuple< Ts... > >
struct is_device_copyable< std::variant< Ts... > >
struct is_device_copyable< T[N]>
struct is_group
class device
The SYCL device class encapsulates a single SYCL device on which kernels may be executed.
class device_event
Encapsulates a single SYCL device event which is available only within SYCL kernel functions and can be used to wait for asynchronous operations within a kernel function to complete.
class accelerator_selector
The default selector chooses the first available SYCL device.
class event
An event object can be used to synchronize memory transfers, enqueues of kernels and signaling barriers.
class exception
class exception_list
A list of asynchronous exceptions.
struct is_property< ext::codeplay::experimental::property::promote_private >
struct is_property< ext::codeplay::experimental::property::promote_local >
struct is_property< ext::codeplay::experimental::property::no_barriers >
struct is_property< ext::codeplay::experimental::property::force_fusion >
struct is_property< ext::codeplay::experimental::property::queue::enable_fusion >
struct is_property_of< ext::codeplay::experimental::property::promote_private, buffer< T, Dimensions, AllocatorT, void > >
struct is_property_of< ext::codeplay::experimental::property::promote_local, buffer< T, Dimensions, AllocatorT, void > >
struct is_property_of< ext::codeplay::experimental::property::promote_private, accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT > >
struct is_property_of< ext::codeplay::experimental::property::promote_local, accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder, PropertyListT > >
struct is_property_of< ext::codeplay::experimental::property::queue::enable_fusion, queue >
struct is_property< ext::oneapi::property::usm::device_read_only >
struct is_property< ext::intel::experimental::property::usm::buffer_location >
struct is_group< ext::oneapi::experimental::ballot_group< ParentGroup > >
struct is_group< ext::oneapi::experimental::fixed_size_group< PartitionSize, ParentGroup > >
struct is_property< ext::oneapi::experimental::property::graph::no_cycle_check >
struct is_property< ext::oneapi::experimental::property::node::depends_on >
struct is_property_of< ext::oneapi::experimental::property::graph::no_cycle_check, ext::oneapi::experimental::command_graph< ext::oneapi::experimental::graph_state::modifiable > >
struct is_property_of< ext::oneapi::experimental::property::node::depends_on, ext::oneapi::experimental::node >
struct is_group< ext::oneapi::experimental::opportunistic_group >
struct is_group< ext::oneapi::experimental::tangle_group< ParentGroup > >
class nd_range
Defines the iteration domain of both the work-groups and the overall dispatch.
struct is_device_copyable< ext::oneapi::experimental::properties< PropertiesT > >
struct logical_and
struct logical_and< void >
struct logical_or
struct logical_or< void >
struct minimum
struct minimum< void >
struct maximum
struct maximum< void >
class handler
Command group handler class.
class image
Defines a shared image data.
class unsampled_image
class sampled_image
class interop_handle
class kernel_bundle
The kernel_bundle class represents collection of device images in a particular state.
class kernel
Provides an abstraction of a SYCL kernel.
class kernel_id
Objects of the class identify kernel is some kernel_bundle related APIs.
class device_image
Objects of the class represents an instance of an image in a specific state.
struct has_known_identity
struct known_identity
struct is_device_copyable< sycl::marray< T, N > >
class local_accessor
class platform
Encapsulates a SYCL platform on which kernels may be executed.
class image_accessor
struct is_property< ext::oneapi::property::no_offset >
struct is_property< ext::oneapi::property::no_alias >
struct is_property< ext::intel::property::buffer_location >
struct is_property_of< property::noinit, T >
struct is_property_of< property::no_init, T >
struct is_property_of< ext::oneapi::property::no_offset, T >
struct is_property_of< ext::oneapi::property::no_alias, T >
struct is_property_of< ext::intel::property::buffer_location, T >
struct is_property_of< property::buffer::use_host_ptr, buffer< T, Dimensions, AllocatorT, void > >
struct is_property_of< property::buffer::use_mutex, buffer< T, Dimensions, AllocatorT, void > >
struct is_property_of< property::buffer::detail::buffer_location, buffer< T, Dimensions, AllocatorT, void > >
struct is_property_of< property::buffer::context_bound, buffer< T, Dimensions, AllocatorT, void > >
struct is_property_of< property::buffer::mem_channel, buffer< T, Dimensions, AllocatorT, void > >
struct is_property_of< ext::oneapi::property::buffer::use_pinned_host_memory, buffer< T, Dimensions, AllocatorT, void > >
struct is_property_of< property::context::cuda::use_primary_context, context >
struct is_property_of< ext::oneapi::cuda::property::context::use_primary_context, context >
struct is_property_of< property::image::use_host_ptr, image< Dimensions, AllocatorT > >
struct is_property_of< property::image::use_mutex, image< Dimensions, AllocatorT > >
struct is_property_of< property::image::context_bound, image< Dimensions, AllocatorT > >
struct is_property_of< property::image::use_host_ptr, sampled_image< Dimensions, AllocatorT > >
struct is_property_of< property::image::use_mutex, sampled_image< Dimensions, AllocatorT > >
struct is_property_of< property::image::context_bound, sampled_image< Dimensions, AllocatorT > >
struct is_property_of< property::image::use_host_ptr, unsampled_image< Dimensions, AllocatorT > >
struct is_property_of< property::image::use_mutex, unsampled_image< Dimensions, AllocatorT > >
struct is_property_of< property::image::context_bound, unsampled_image< Dimensions, AllocatorT > >
struct is_property
struct is_property_of
class property_list
Objects of the property_list class are containers for the SYCL properties.
class queue
Encapsulates a single SYCL queue which schedules kernels on a SYCL device.
class reducer
Class that is used to represent objects that are passed to user's lambda functions and representing users' reduction variable.
struct is_device_copyable< detail::ReducerElement< T, BinaryOperation, IsOptional > >
class reducer< T, BinaryOperation, Dims, Extent, IdentityContainerT, View, std::enable_if_t< Dims==0 &&Extent==1 &&View==false &&!detail::IsKnownIdentityOp< T, BinaryOperation >::value > >
Specialization of the generic class 'reducer'.
class reducer< T, BinaryOperation, Dims, Extent, IdentityContainerT, View, std::enable_if_t< Dims==0 &&Extent==1 &&View==false &&detail::IsKnownIdentityOp< T, BinaryOperation >::value > >
Specialization of the generic class 'reducer'.
class reducer< T, BinaryOperation, Dims, Extent, IdentityContainerT, View, std::enable_if_t< Dims==0 &&View==true > >
Component of 'reducer' class for array reductions, representing a single element of the span (as returned by the subscript operator).
class reducer< T, BinaryOperation, Dims, Extent, IdentityContainerT, View, std::enable_if_t< Dims==1 &&View==false &&!detail::IsKnownIdentityOp< T, BinaryOperation >::value > >
Specialization of 'reducer' class for array reductions exposing the subscript operator.
class reducer< T, BinaryOperation, Dims, Extent, IdentityContainerT, View, std::enable_if_t< Dims==1 &&View==false &&detail::IsKnownIdentityOp< T, BinaryOperation >::value > >
Specialization of 'reducer' class for array reductions accepting a span in cases where the identity value is known.
struct image_sampler
class __precision_manipulator__
class __width_manipulator__
struct sub_group
class span
struct __is_span_impl
struct __is_span_impl< span< _Tp, _Extent > >
struct __is_span
struct __is_std_array_impl
struct __is_std_array_impl< std::array< _Tp, _Sz > >
struct __is_std_array
struct __is_span_compatible_container
struct __is_span_compatible_container< _Tp, _ElementType, std::void_t< typename std::enable_if<!__is_span< _Tp >::value, std::nullptr_t >::type, typename std::enable_if<!__is_std_array< _Tp >::value, std::nullptr_t >::type, typename std::enable_if<!std::is_array_v< _Tp >, std::nullptr_t >::type, decltype(data(std::declval< _Tp >())), decltype(size(std::declval< _Tp >())), typename std::enable_if< std::is_convertible_v< std::remove_pointer_t< decltype(data(std::declval< _Tp & >()))>(*)[], _ElementType(*)[]>, std::nullptr_t >::type > >
class span< _Tp, dynamic_extent >
class usm_allocator
struct elem
Typedefs
using access_mode = access::mode
template<typename T >
using remove_decoration_t = typename remove_decoration< T >::type
using instead = std::uint8_t
using __SYCL2020_DEPRECATED = signed char
using half = sycl::detail::half_impl::half
using async_handler = std::function< void(sycl::exception_list)>
template<backend Backend, typename SyclType >
using backend_input_t = typename backend_traits< Backend >::template input_type< SyclType >
template<backend Backend, typename SyclType >
using backend_return_t = typename backend_traits< Backend >::template return_type< SyclType >
template<typename DataT >
using buffer_allocator = detail::sycl_memory_object_allocator< DataT >
template<backend B>
using errc_for = typename backend_traits< B >::errc
template<typename T = void>
using plus = std::plus< T >
template<typename T = void>
using multiplies = std::multiplies< T >
template<typename T = void>
using bit_and = std::bit_and< T >
template<typename T = void>
using bit_or = std::bit_or< T >
template<typename T = void>
using bit_xor = std::bit_xor< T >
using byte = unsigned char
using image_allocator = detail::aligned_allocator< byte >
using value_type = const void
using pointer = std::conditional_t< is_decorated, decorated_type *, std::add_pointer_t< value_type > >
using difference_type = std::ptrdiff_t
template<class name , class dataT , int32_t min_capacity = 0>
using pipe = ext::intel::pipe< name, dataT, min_capacity >
template<typename ElementType , access::decorated IsDecorated = access::decorated::legacy>
using generic_ptr = multi_ptr< ElementType, access::address_space::generic_space, IsDecorated >
template<typename ElementType , access::decorated IsDecorated = access::decorated::legacy>
using global_ptr = multi_ptr< ElementType, access::address_space::global_space, IsDecorated >
template<typename ElementType , access::decorated IsDecorated = access::decorated::legacy>
using local_ptr = multi_ptr< ElementType, access::address_space::local_space, IsDecorated >
template<typename ElementType >
using constant_ptr = multi_ptr< ElementType, access::address_space::constant_space, access::decorated::legacy >
template<typename ElementType , access::decorated IsDecorated = access::decorated::legacy>
using private_ptr = multi_ptr< ElementType, access::address_space::private_space, IsDecorated >
template<typename ElementType >
using raw_global_ptr = multi_ptr< ElementType, access::address_space::global_space, access::decorated::no >
template<typename ElementType >
using raw_local_ptr = multi_ptr< ElementType, access::address_space::local_space, access::decorated::no >
template<typename ElementType >
using raw_private_ptr = multi_ptr< ElementType, access::address_space::private_space, access::decorated::no >
template<typename ElementType >
using decorated_global_ptr = multi_ptr< ElementType, access::address_space::global_space, access::decorated::yes >
template<typename ElementType >
using decorated_local_ptr = multi_ptr< ElementType, access::address_space::local_space, access::decorated::yes >
template<typename ElementType >
using decorated_private_ptr = multi_ptr< ElementType, access::address_space::private_space, access::decorated::yes >
template<typename T >
using vec_data = detail::vec_helper< T >
template<typename T >
using vec_data_t = typename detail::vec_helper< T >::RetType
using ContextImplPtr = std::shared_ptr< sycl::detail::context_impl >
using alloc = sycl::usm::alloc
Enumerations
enum class image_target : unsigned int { device = 0 , host_task = 1 }
enum class backend : char {
__SYCL2020_DEPRECATED =("'host' backend is no longer supported") = 0 , opencl = 1 , ext_oneapi_level_zero = 2 , ext_oneapi_cuda = 3 ,
all = 4 , __SYCL_DEPRECATED , ext_oneapi_hip = 6 , ext_oneapi_native_cpu = 7
}
enum class errc : unsigned int {
success = 0 , runtime = 1 , kernel = 2 , accessor = 3 ,
nd_range = 4 , event = 5 , kernel_argument = 6 , build = 7 ,
invalid = 8 , memory_allocation = 9 , platform = 10 , profiling = 11 ,
feature_not_supported = 12 , kernel_not_supported = 13 , backend_mismatch = 14
}
enum class image_channel_order : unsigned int {
a = 0 , r = 1 , rx = 2 , rg = 3 ,
rgx = 4 , ra = 5 , rgb = 6 , rgbx = 7 ,
rgba = 8 , argb = 9 , bgra = 10 , intensity = 11 ,
luminance = 12 , abgr = 13 , ext_oneapi_srgba = 14
}
enum class image_channel_type : unsigned int {
snorm_int8 = 0 , snorm_int16 = 1 , unorm_int8 = 2 , unorm_int16 = 3 ,
unorm_short_565 = 4 , unorm_short_555 = 5 , unorm_int_101010 = 6 , signed_int8 = 7 ,
signed_int16 = 8 , signed_int32 = 9 , unsigned_int8 = 10 , unsigned_int16 = 11 ,
unsigned_int32 = 12 , fp16 = 13 , fp32 = 14
}
enum class image_format : unsigned int {
r8g8b8a8_unorm = 0 , r16g16b16a16_unorm = 1 , r8g8b8a8_sint = 2 , r16g16b16a16_sint = 3 ,
r32b32g32a32_sint = 4 , r8g8b8a8_uint = 5 , r16g16b16a16_uint = 6 , r32b32g32a32_uint = 7 ,
r16b16g16a16_sfloat = 8 , r32g32b32a32_sfloat = 9 , b8g8r8a8_unorm = 10
}
enum class bundle_state : char { input = 0 , object = 1 , executable = 2 , ext_oneapi_source = 3 }
enum class memory_order : int {
relaxed = 0 , acquire = 1 , __consume_unsupported , release = 3 ,
acq_rel = 4 , seq_cst = 5
}
enum class memory_scope : int {
work_item = 0 , sub_group = 1 , work_group = 2 , device = 3 ,
system = 4
}
enum class addressing_mode : unsigned int {
mirrored_repeat = PI_SAMPLER_ADDRESSING_MODE_MIRRORED_REPEAT , repeat = PI_SAMPLER_ADDRESSING_MODE_REPEAT , clamp_to_edge = PI_SAMPLER_ADDRESSING_MODE_CLAMP_TO_EDGE , clamp = PI_SAMPLER_ADDRESSING_MODE_CLAMP ,
none = PI_SAMPLER_ADDRESSING_MODE_NONE
}
enum class filtering_mode : unsigned int { nearest = PI_SAMPLER_FILTER_MODE_NEAREST , linear = PI_SAMPLER_FILTER_MODE_LINEAR }
enum class coordinate_normalization_mode : unsigned int { normalized = 1 , unnormalized = 0 }
enum class stream_manipulator {
dec = 0 , hex = 1 , oct = 2 , noshowbase = 3 ,
showbase = 4 , noshowpos = 5 , showpos = 6 , endl = 7 ,
flush = 8 , fixed = 9 , scientific = 10 , hexfloat = 11 ,
defaultfloat = 12
}
Functions
template<typename DataT , int Dimensions, typename AllocatorT >
class __SYCL_EBO __SYCL_SPECIAL_CLASS __SYCL_TYPE(accessor) accessor accessor (buffer< DataT, Dimensions, AllocatorT >) -> accessor< DataT, Dimensions, access::mode::read_write, target::device, access::placeholder::true_t >
Buffer accessor.
template<typename DataT , int Dimensions, typename AllocatorT , typename... PropsT>
accessor (buffer< DataT, Dimensions, AllocatorT >, const ext::oneapi::accessor_property_list< PropsT... > &) -> accessor< DataT, Dimensions, access::mode::read_write, target::device, access::placeholder::true_t, ext::oneapi::accessor_property_list< PropsT... >>
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 >
accessor (buffer< DataT, Dimensions, AllocatorT >, Type1) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type1, Type1 >(), detail::deduceAccessTarget< Type1, Type1 >(target::device), access::placeholder::true_t >
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename... PropsT>
accessor (buffer< DataT, Dimensions, AllocatorT >, Type1, const ext::oneapi::accessor_property_list< PropsT... > &) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type1, Type1 >(), detail::deduceAccessTarget< Type1, Type1 >(target::device), access::placeholder::true_t, ext::oneapi::accessor_property_list< PropsT... >>
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 >
accessor (buffer< DataT, Dimensions, AllocatorT >, Type1, Type2) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type1, Type2 >(), detail::deduceAccessTarget< Type1, Type2 >(target::device), access::placeholder::true_t >
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename... PropsT>
accessor (buffer< DataT, Dimensions, AllocatorT >, Type1, Type2, const ext::oneapi::accessor_property_list< PropsT... > &) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type1, Type2 >(), detail::deduceAccessTarget< Type1, Type2 >(target::device), access::placeholder::true_t, ext::oneapi::accessor_property_list< PropsT... >>
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 >
accessor (buffer< DataT, Dimensions, AllocatorT >, Type1, Type2, Type3) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type2, Type3 >(), detail::deduceAccessTarget< Type2, Type3 >(target::device), access::placeholder::true_t >
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 , typename... PropsT>
accessor (buffer< DataT, Dimensions, AllocatorT >, Type1, Type2, Type3, const ext::oneapi::accessor_property_list< PropsT... > &) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type2, Type3 >(), detail::deduceAccessTarget< Type2, Type3 >(target::device), access::placeholder::true_t, ext::oneapi::accessor_property_list< PropsT... >>
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 , typename Type4 >
accessor (buffer< DataT, Dimensions, AllocatorT >, Type1, Type2, Type3, Type4) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type3, Type4 >(), detail::deduceAccessTarget< Type3, Type4 >(target::device), access::placeholder::true_t >
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 , typename Type4 , typename... PropsT>
accessor (buffer< DataT, Dimensions, AllocatorT >, Type1, Type2, Type3, Type4, const ext::oneapi::accessor_property_list< PropsT... > &) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type3, Type4 >(), detail::deduceAccessTarget< Type3, Type4 >(target::device), access::placeholder::true_t, ext::oneapi::accessor_property_list< PropsT... >>
template<typename DataT , int Dimensions, typename AllocatorT >
accessor (buffer< DataT, Dimensions, AllocatorT >, handler &) -> accessor< DataT, Dimensions, access::mode::read_write, target::device, access::placeholder::false_t >
template<typename DataT , int Dimensions, typename AllocatorT , typename... PropsT>
accessor (buffer< DataT, Dimensions, AllocatorT >, handler &, const ext::oneapi::accessor_property_list< PropsT... > &) -> accessor< DataT, Dimensions, access::mode::read_write, target::device, access::placeholder::false_t, ext::oneapi::accessor_property_list< PropsT... >>
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 >
accessor (buffer< DataT, Dimensions, AllocatorT >, handler &, Type1) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type1, Type1 >(), detail::deduceAccessTarget< Type1, Type1 >(target::device), access::placeholder::false_t >
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename... PropsT>
accessor (buffer< DataT, Dimensions, AllocatorT >, handler &, Type1, const ext::oneapi::accessor_property_list< PropsT... > &) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type1, Type1 >(), detail::deduceAccessTarget< Type1, Type1 >(target::device), access::placeholder::false_t, ext::oneapi::accessor_property_list< PropsT... >>
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 >
accessor (buffer< DataT, Dimensions, AllocatorT >, handler &, Type1, Type2) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type1, Type2 >(), detail::deduceAccessTarget< Type1, Type2 >(target::device), access::placeholder::false_t >
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename... PropsT>
accessor (buffer< DataT, Dimensions, AllocatorT >, handler &, Type1, Type2, const ext::oneapi::accessor_property_list< PropsT... > &) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type1, Type2 >(), detail::deduceAccessTarget< Type1, Type2 >(target::device), access::placeholder::false_t, ext::oneapi::accessor_property_list< PropsT... >>
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 >
accessor (buffer< DataT, Dimensions, AllocatorT >, handler &, Type1, Type2, Type3) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type2, Type3 >(), detail::deduceAccessTarget< Type2, Type3 >(target::device), access::placeholder::false_t >
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 , typename... PropsT>
accessor (buffer< DataT, Dimensions, AllocatorT >, handler &, Type1, Type2, Type3, const ext::oneapi::accessor_property_list< PropsT... > &) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type2, Type3 >(), detail::deduceAccessTarget< Type2, Type3 >(target::device), access::placeholder::false_t, ext::oneapi::accessor_property_list< PropsT... >>
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 , typename Type4 >
accessor (buffer< DataT, Dimensions, AllocatorT >, handler &, Type1, Type2, Type3, Type4) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type3, Type4 >(), detail::deduceAccessTarget< Type3, Type4 >(target::device), access::placeholder::false_t >
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 , typename Type4 , typename... PropsT>
accessor (buffer< DataT, Dimensions, AllocatorT >, handler &, Type1, Type2, Type3, Type4, const ext::oneapi::accessor_property_list< PropsT... > &) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type3, Type4 >(), detail::deduceAccessTarget< Type3, Type4 >(target::device), access::placeholder::false_t, ext::oneapi::accessor_property_list< PropsT... >>
template<typename DataT , int Dimensions, typename AllocatorT >
host_accessor (buffer< DataT, Dimensions, AllocatorT >) -> host_accessor< DataT, Dimensions, access::mode::read_write >
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 >
host_accessor (buffer< DataT, Dimensions, AllocatorT >, Type1) -> host_accessor< DataT, Dimensions, detail::deduceAccessMode< Type1, Type1 >()>
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 >
host_accessor (buffer< DataT, Dimensions, AllocatorT >, Type1, Type2) -> host_accessor< DataT, Dimensions, detail::deduceAccessMode< Type1, Type2 >()>
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 >
host_accessor (buffer< DataT, Dimensions, AllocatorT >, Type1, Type2, Type3) -> host_accessor< DataT, Dimensions, detail::deduceAccessMode< Type2, Type3 >()>
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 , typename Type4 >
host_accessor (buffer< DataT, Dimensions, AllocatorT >, Type1, Type2, Type3, Type4) -> host_accessor< DataT, Dimensions, detail::deduceAccessMode< Type3, Type4 >()>
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 , typename Type4 , typename Type5 >
host_accessor (buffer< DataT, Dimensions, AllocatorT >, Type1, Type2, Type3, Type4, Type5) -> host_accessor< DataT, Dimensions, detail::deduceAccessMode< Type4, Type5 >()>
template<typename DataT , int Dimensions, access::mode AccessMode, access::placeholder IsPlaceholder>
class __SYCL_EBO __SYCL_SPECIAL_CLASS __SYCL_TYPE (accessor) accessor< DataT
Image accessors.
enum __SYCL_TYPE (aspect) aspect
template<typename T , access::address_space addressSpace = access::address_space::global_space>
class __SYCL2020_DEPRECATED ("sycl::atomic is deprecated since SYCL 2020") atomic
template<typename T , access::address_space addressSpace>
void atomic_store (atomic< T, addressSpace > Object, T Operand, memory_order MemoryOrder=memory_order::relaxed)
template<typename T , access::address_space addressSpace>
T atomic_load (atomic< T, addressSpace > Object, memory_order MemoryOrder=memory_order::relaxed)
template<typename T , access::address_space addressSpace>
T atomic_exchange (atomic< T, addressSpace > Object, T Operand, memory_order MemoryOrder=memory_order::relaxed)
template<typename T , access::address_space addressSpace>
bool atomic_compare_exchange_strong (atomic< T, addressSpace > Object, T &Expected, T Desired, memory_order SuccessOrder=memory_order::relaxed, memory_order FailOrder=memory_order::relaxed)
template<typename T , access::address_space addressSpace>
T atomic_fetch_add (atomic< T, addressSpace > Object, T Operand, memory_order MemoryOrder=memory_order::relaxed)
template<typename T , access::address_space addressSpace>
T atomic_fetch_sub (atomic< T, addressSpace > Object, T Operand, memory_order MemoryOrder=memory_order::relaxed)
template<typename T , access::address_space addressSpace>
T atomic_fetch_and (atomic< T, addressSpace > Object, T Operand, memory_order MemoryOrder=memory_order::relaxed)
template<typename T , access::address_space addressSpace>
T atomic_fetch_or (atomic< T, addressSpace > Object, T Operand, memory_order MemoryOrder=memory_order::relaxed)
template<typename T , access::address_space addressSpace>
T atomic_fetch_xor (atomic< T, addressSpace > Object, T Operand, memory_order MemoryOrder=memory_order::relaxed)
template<typename T , access::address_space addressSpace>
T atomic_fetch_min (atomic< T, addressSpace > Object, T Operand, memory_order MemoryOrder=memory_order::relaxed)
template<typename T , access::address_space addressSpace>
T atomic_fetch_max (atomic< T, addressSpace > Object, T Operand, memory_order MemoryOrder=memory_order::relaxed)
void atomic_fence (memory_order order, memory_scope scope)
template<backend BackendName, class SyclObjectT >
auto get_native (const SyclObjectT &Obj) -> backend_return_t< BackendName, SyclObjectT >
template<backend BackendName>
auto get_native (const queue &Obj) -> backend_return_t< BackendName, queue >
template<backend BackendName, bundle_state State>
auto get_native (const kernel_bundle< State > &Obj) -> backend_return_t< BackendName, kernel_bundle< State >>
template<backend BackendName, typename DataT , int Dimensions, typename AllocatorT >
auto get_native (const buffer< DataT, Dimensions, AllocatorT > &Obj) -> backend_return_t< BackendName, buffer< DataT, Dimensions, AllocatorT >>
template<backend BackendName, typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder>
auto get_native (const accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder > &Obj) -> typename detail::interop< BackendName, accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder >>::type=delete
template<backend Backend>
std::enable_if_t< detail::InteropFeatureSupportMap< Backend >::MakePlatform==true, platform > make_platform (const typename backend_traits< Backend >::template input_type< platform > &BackendObject)
template<backend Backend>
std::enable_if_t< detail::InteropFeatureSupportMap< Backend >::MakeDevice==true, device > make_device (const typename backend_traits< Backend >::template input_type< device > &BackendObject)
template<backend Backend>
std::enable_if_t< detail::InteropFeatureSupportMap< Backend >::MakeContext==true, context > make_context (const typename backend_traits< Backend >::template input_type< context > &BackendObject, const async_handler &Handler={})
template<backend Backend>
std::enable_if_t< detail::InteropFeatureSupportMap< Backend >::MakeQueue==true, queue > make_queue (const typename backend_traits< Backend >::template input_type< queue > &BackendObject, const context &TargetContext, const async_handler Handler={})
template<backend Backend>
std::enable_if_t< detail::InteropFeatureSupportMap< Backend >::MakeEvent==true, event > make_event (const typename backend_traits< Backend >::template input_type< event > &BackendObject, const context &TargetContext)
template<backend Backend>
std::enable_if_t< detail::InteropFeatureSupportMap< Backend >::MakeEvent==true, event > make_event (const typename backend_traits< Backend >::template input_type< event > &BackendObject, const context &TargetContext, bool KeepOwnership)
template<backend Backend, typename T , int Dimensions = 1, typename AllocatorT = buffer_allocator<std::remove_const_t<T>>>
std::enable_if_t< detail::InteropFeatureSupportMap< Backend >::MakeBuffer==true &&Backend !=backend::ext_oneapi_level_zero, buffer< T, Dimensions, AllocatorT > > make_buffer (const typename backend_traits< Backend >::template input_type< buffer< T, Dimensions, AllocatorT >> &BackendObject, const context &TargetContext, event AvailableEvent={})
template<backend Backend, int Dimensions = 1, typename AllocatorT = image_allocator>
std::enable_if_t< detail::InteropFeatureSupportMap< Backend >::MakeImage==true &&Backend !=backend::ext_oneapi_level_zero, image< Dimensions, AllocatorT > > make_image (const typename backend_traits< Backend >::template input_type< image< Dimensions, AllocatorT >> &BackendObject, const context &TargetContext, event AvailableEvent={})
template<backend Backend>
kernel make_kernel (const typename backend_traits< Backend >::template input_type< kernel > &BackendObject, const context &TargetContext)
template<backend Backend, bundle_state State>
std::enable_if_t< detail::InteropFeatureSupportMap< Backend >::MakeKernelBundle==true, kernel_bundle< State > > make_kernel_bundle (const typename backend_traits< Backend >::template input_type< kernel_bundle< State >> &BackendObject, const context &TargetContext)
std::ostream & operator<< (std::ostream &Out, backend be)
template<typename To , typename From >
std::enable_if_t< sizeof(To)==sizeof(From) &&std::is_trivially_copyable< From >::value &&std::is_trivially_copyable< To >::value, To > bit_cast (const From &from) noexcept
template<int SZ>
ESIMD_NODEBUG ESIMD_INLINE sycl::ext::intel::esimd::simd< float, SZ > cos (sycl::ext::intel::esimd::simd< float, SZ > x) __NOEXC
template<int SZ>
ESIMD_NODEBUG ESIMD_INLINE sycl::ext::intel::esimd::simd< float, SZ > sin (sycl::ext::intel::esimd::simd< float, SZ > x) __NOEXC
template<int SZ>
ESIMD_NODEBUG ESIMD_INLINE sycl::ext::intel::esimd::simd< float, SZ > exp (sycl::ext::intel::esimd::simd< float, SZ > x) __NOEXC
template<int SZ>
ESIMD_NODEBUG ESIMD_INLINE sycl::ext::intel::esimd::simd< float, SZ > log (sycl::ext::intel::esimd::simd< float, SZ > x) __NOEXC
template<backend Backend, class SyclT >
auto get_native (const SyclT &Obj) -> backend_return_t< Backend, SyclT >
float ceil (float)
double ceil (double)
float floor (float)
double floor (double)
float rint (float)
double rint (double)
float trunc (float)
double trunc (double)
class __SYCL2020_DEPRECATED ("Use SYCL 2020 callable device selectors instead.") device_selector
The SYCL 1.2.1 device_selector class provides ability to choose the best SYCL device based on heuristics specified by the user.
class __SYCL2020_DEPRECATED("Host device is no longer supported.") host_selector int default_selector_v (const device &dev)
Selects SYCL host device.
int gpu_selector_v (const device &dev)
int cpu_selector_v (const device &dev)
int accelerator_selector_v (const device &dev)
detail::DSelectorInvocableType aspect_selector (const std::vector< aspect > &RequireList, const std::vector< aspect > &DenyList={})
template<typename... AspectListT>
detail::DSelectorInvocableType aspect_selector (AspectListT... AspectList)
template<aspect... AspectList>
detail::DSelectorInvocableType aspect_selector ()
std::error_code make_error_code (sycl::errc E) noexcept
Constructs an error code using e and sycl_category()
const std::error_category & sycl_category () noexcept
template<>
backend_return_t< backend::ext_oneapi_hip, device > get_native< backend::ext_oneapi_hip, device > (const device &Obj)
template<>
device make_device< backend::ext_oneapi_hip > (const backend_input_t< backend::ext_oneapi_hip, device > &BackendObject)
template<>
context make_context< backend::ext_oneapi_level_zero > (const backend_input_t< backend::ext_oneapi_level_zero, context > &BackendObject, const async_handler &Handler)
template<>
queue make_queue< backend::ext_oneapi_level_zero > (const backend_input_t< backend::ext_oneapi_level_zero, queue > &BackendObject, const context &TargetContext, const async_handler Handler)
template<>
auto get_native< backend::ext_oneapi_level_zero, queue > (const queue &Obj) -> backend_return_t< backend::ext_oneapi_level_zero, queue >
template<>
event make_event< backend::ext_oneapi_level_zero > (const backend_input_t< backend::ext_oneapi_level_zero, event > &BackendObject, const context &TargetContext)
template<>
kernel_bundle< bundle_state::executable > make_kernel_bundle< backend::ext_oneapi_level_zero, bundle_state::executable > (const backend_input_t< backend::ext_oneapi_level_zero, kernel_bundle< bundle_state::executable >> &BackendObject, const context &TargetContext)
template<>
kernel make_kernel< backend::ext_oneapi_level_zero > (const backend_input_t< backend::ext_oneapi_level_zero, kernel > &BackendObject, const context &TargetContext)
template<backend Backend, typename T , int Dimensions = 1, typename AllocatorT = buffer_allocator<std::remove_const_t<T>>>
std::enable_if_t< Backend==backend::ext_oneapi_level_zero, buffer< T, Dimensions, AllocatorT > > make_buffer (const backend_input_t< backend::ext_oneapi_level_zero, buffer< T, Dimensions, AllocatorT >> &BackendObject, const context &TargetContext, event AvailableEvent)
template<backend Backend, typename T , int Dimensions = 1, typename AllocatorT = buffer_allocator<std::remove_const_t<T>>>
std::enable_if_t< Backend==backend::ext_oneapi_level_zero, buffer< T, Dimensions, AllocatorT > > make_buffer (const backend_input_t< backend::ext_oneapi_level_zero, buffer< T, Dimensions, AllocatorT >> &BackendObject, const context &TargetContext)
template<backend Backend, int Dimensions = 1, typename AllocatorT = image_allocator>
std::enable_if_t< Backend==backend::ext_oneapi_level_zero, image< Dimensions, AllocatorT > > make_image (const backend_input_t< Backend, image< Dimensions, AllocatorT >> &BackendObject, const context &TargetContext, event AvailableEvent)
namespace __SYCL2020_DEPRECATED ("use 'ext::oneapi::level_zero' instead") level_zero
template<>
auto get_native< backend::ext_oneapi_cuda, context > (const context &C) -> backend_return_t< backend::ext_oneapi_cuda, context >
template<>
backend_return_t< backend::ext_oneapi_cuda, context > interop_handle::get_native_context< backend::ext_oneapi_cuda > () const
template<>
device make_device< backend::ext_oneapi_cuda > (const backend_input_t< backend::ext_oneapi_cuda, device > &BackendObject)
template<>
event make_event< backend::ext_oneapi_cuda > (const backend_input_t< backend::ext_oneapi_cuda, event > &BackendObject, const context &TargetContext)
template<>
queue make_queue< backend::ext_oneapi_cuda > (const backend_input_t< backend::ext_oneapi_cuda, queue > &BackendObject, const context &TargetContext, const async_handler Handler)
template<int dimensions>
void group_barrier (ext::oneapi::experimental::root_group< dimensions > G, memory_scope FenceScope=decltype(G)::fence_scope)
template<typename T , int Dimensions = 1>
class __SYCL_TYPE (private_memory) private_memory
template<int Dimensions = 1>
class __SYCL_TYPE (group) group
Encapsulates all functionality required to represent a particular work-group within a parallel execution.
template<typename Group , typename T , class BinaryOperation >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&(detail::is_scalar_arithmetic< T >::value||(detail::is_complex< T >::value &&detail::is_multiplies< T, BinaryOperation >::value)) &&detail::is_native_op< T, BinaryOperation >::value), T > reduce_over_group (Group g, T x, BinaryOperation binary_op)
template<typename Group , typename T , class BinaryOperation >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&detail::is_complex< T >::value &&detail::is_native_op< T, sycl::plus< T >>::value &&detail::is_plus< T, BinaryOperation >::value), T > reduce_over_group (Group g, T x, BinaryOperation)
template<typename Group , typename T , class BinaryOperation >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&detail::is_vector_arithmetic_or_complex< T >::value &&detail::is_native_op< T, BinaryOperation >::value), T > reduce_over_group (Group g, T x, BinaryOperation binary_op)
template<typename Group , typename V , typename T , class BinaryOperation >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&(detail::is_scalar_arithmetic< V >::value||detail::is_complex< V >::value) &&(detail::is_scalar_arithmetic< T >::value||detail::is_complex< T >::value) &&detail::is_native_op< T, BinaryOperation >::value &&detail::is_plus_or_multiplies_if_complex< T, BinaryOperation >::value &&std::is_convertible_v< V, T >), T > reduce_over_group (Group g, V x, T init, BinaryOperation binary_op)
template<typename Group , typename V , typename T , class BinaryOperation >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&detail::is_vector_arithmetic_or_complex< V >::value &&detail::is_vector_arithmetic_or_complex< T >::value &&detail::is_native_op< V, BinaryOperation >::value &&detail::is_native_op< T, BinaryOperation >::value), T > reduce_over_group (Group g, V x, T init, BinaryOperation binary_op)
template<typename Group , typename Ptr , typename T , class BinaryOperation >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&detail::is_pointer_v< Ptr > &&detail::is_arithmetic_or_complex< typename detail::remove_pointer< Ptr >::type >::value &&detail::is_arithmetic_or_complex< T >::value &&detail::is_plus_or_multiplies_if_complex< T, BinaryOperation >::value &&detail::is_native_op< T, BinaryOperation >::value), T > joint_reduce (Group g, Ptr first, Ptr last, T init, BinaryOperation binary_op)
template<typename Group , typename Ptr , class BinaryOperation >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&detail::is_pointer_v< Ptr > &&detail::is_arithmetic_or_complex< typename detail::remove_pointer< Ptr >::type >::value &&detail::is_plus_or_multiplies_if_complex< typename detail::remove_pointer< Ptr >::type, BinaryOperation >::value), typename detail::remove_pointer< Ptr >::type > joint_reduce (Group g, Ptr first, Ptr last, BinaryOperation binary_op)
template<typename Group >
std::enable_if_t< is_group_v< std::decay_t< Group > >, bool > any_of_group (Group g, bool pred)
template<typename Group , typename T , class Predicate >
std::enable_if_t< is_group_v< Group >, bool > any_of_group (Group g, T x, Predicate pred)
template<typename Group , typename Ptr , class Predicate >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&detail::is_pointer_v< Ptr >), bool > joint_any_of (Group g, Ptr first, Ptr last, Predicate pred)
template<typename Group >
std::enable_if_t< is_group_v< std::decay_t< Group > >, bool > all_of_group (Group g, bool pred)
template<typename Group , typename T , class Predicate >
std::enable_if_t< is_group_v< std::decay_t< Group > >, bool > all_of_group (Group g, T x, Predicate pred)
template<typename Group , typename Ptr , class Predicate >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&detail::is_pointer_v< Ptr >), bool > joint_all_of (Group g, Ptr first, Ptr last, Predicate pred)
template<typename Group >
std::enable_if_t< is_group_v< std::decay_t< Group > >, bool > none_of_group (Group g, bool pred)
template<typename Group , typename T , class Predicate >
std::enable_if_t< is_group_v< std::decay_t< Group > >, bool > none_of_group (Group g, T x, Predicate pred)
template<typename Group , typename Ptr , class Predicate >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&detail::is_pointer_v< Ptr >), bool > joint_none_of (Group g, Ptr first, Ptr last, Predicate pred)
template<typename Group , typename T >
std::enable_if_t<((std::is_same_v< std::decay_t< Group >, sub_group >||sycl::ext::oneapi::experimental::is_user_constructed_group_v< std::decay_t< Group >>) &&(std::is_trivially_copyable_v< T >||detail::is_vec< T >::value)), T > shift_group_left (Group g, T x, typename Group::linear_id_type delta=1)
template<typename Group , typename T >
std::enable_if_t<((std::is_same_v< std::decay_t< Group >, sub_group >||sycl::ext::oneapi::experimental::is_user_constructed_group_v< std::decay_t< Group >>) &&(std::is_trivially_copyable_v< T >||detail::is_vec< T >::value)), T > shift_group_right (Group g, T x, typename Group::linear_id_type delta=1)
template<typename Group , typename T >
std::enable_if_t<((std::is_same_v< std::decay_t< Group >, sub_group >||sycl::ext::oneapi::experimental::is_user_constructed_group_v< std::decay_t< Group >>) &&(std::is_trivially_copyable_v< T >||detail::is_vec< T >::value)), T > permute_group_by_xor (Group g, T x, typename Group::linear_id_type mask)
template<typename Group , typename T >
std::enable_if_t<((std::is_same_v< std::decay_t< Group >, sub_group >||sycl::ext::oneapi::experimental::is_user_constructed_group_v< std::decay_t< Group >>) &&(std::is_trivially_copyable_v< T >||detail::is_vec< T >::value)), T > select_from_group (Group g, T x, typename Group::id_type local_id)
template<typename Group , typename T >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&(std::is_trivially_copyable_v< T >||detail::is_vec< T >::value)), T > group_broadcast (Group g, T x, typename Group::id_type local_id)
template<typename Group , typename T >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&(std::is_trivially_copyable_v< T >||detail::is_vec< T >::value)), T > group_broadcast (Group g, T x, typename Group::linear_id_type linear_local_id)
template<typename Group , typename T >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&(std::is_trivially_copyable_v< T >||detail::is_vec< T >::value)), T > group_broadcast (Group g, T x)
template<typename Group , typename T , class BinaryOperation >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&(detail::is_scalar_arithmetic< T >::value||(detail::is_complex< T >::value &&detail::is_multiplies< T, BinaryOperation >::value)) &&detail::is_native_op< T, BinaryOperation >::value), T > exclusive_scan_over_group (Group g, T x, BinaryOperation binary_op)
template<typename Group , typename T , class BinaryOperation >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&detail::is_complex< T >::value &&detail::is_native_op< T, sycl::plus< T >>::value &&detail::is_plus< T, BinaryOperation >::value), T > exclusive_scan_over_group (Group g, T x, BinaryOperation)
template<typename Group , typename T , class BinaryOperation >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&detail::is_vector_arithmetic_or_complex< T >::value &&detail::is_native_op< T, BinaryOperation >::value), T > exclusive_scan_over_group (Group g, T x, BinaryOperation binary_op)
template<typename Group , typename V , typename T , class BinaryOperation >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&detail::is_vector_arithmetic_or_complex< V >::value &&detail::is_vector_arithmetic_or_complex< T >::value &&detail::is_native_op< V, BinaryOperation >::value &&detail::is_native_op< T, BinaryOperation >::value), T > exclusive_scan_over_group (Group g, V x, T init, BinaryOperation binary_op)
template<typename Group , typename V , typename T , class BinaryOperation >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&(detail::is_scalar_arithmetic< V >::value||detail::is_complex< V >::value) &&(detail::is_scalar_arithmetic< T >::value||detail::is_complex< T >::value) &&detail::is_native_op< T, BinaryOperation >::value &&detail::is_plus_or_multiplies_if_complex< T, BinaryOperation >::value &&std::is_convertible_v< V, T >), T > exclusive_scan_over_group (Group g, V x, T init, BinaryOperation binary_op)
template<typename Group , typename InPtr , typename OutPtr , typename T , class BinaryOperation >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&detail::is_pointer_v< InPtr > &&detail::is_pointer_v< OutPtr > &&detail::is_arithmetic_or_complex< typename detail::remove_pointer< InPtr >::type >::value &&detail::is_arithmetic_or_complex< typename detail::remove_pointer< OutPtr >::type >::value &&detail::is_arithmetic_or_complex< T >::value &&detail::is_native_op< T, BinaryOperation >::value &&detail::is_plus_or_multiplies_if_complex< T, BinaryOperation >::value), OutPtr > joint_exclusive_scan (Group g, InPtr first, InPtr last, OutPtr result, T init, BinaryOperation binary_op)
template<typename Group , typename InPtr , typename OutPtr , class BinaryOperation >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&detail::is_pointer_v< InPtr > &&detail::is_pointer_v< OutPtr > &&detail::is_arithmetic_or_complex< typename detail::remove_pointer< InPtr >::type >::value &&detail::is_arithmetic_or_complex< typename detail::remove_pointer< OutPtr >::type >::value &&detail::is_native_op< typename detail::remove_pointer< OutPtr >::type, BinaryOperation >::value &&detail::is_plus_or_multiplies_if_complex< typename detail::remove_pointer< OutPtr >::type, BinaryOperation >::value), OutPtr > joint_exclusive_scan (Group g, InPtr first, InPtr last, OutPtr result, BinaryOperation binary_op)
template<typename Group , typename T , class BinaryOperation >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&detail::is_vector_arithmetic_or_complex< T >::value &&detail::is_native_op< T, BinaryOperation >::value), T > inclusive_scan_over_group (Group g, T x, BinaryOperation binary_op)
template<typename Group , typename T , class BinaryOperation >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&(detail::is_scalar_arithmetic< T >::value||(detail::is_complex< T >::value &&detail::is_multiplies< T, BinaryOperation >::value)) &&detail::is_native_op< T, BinaryOperation >::value), T > inclusive_scan_over_group (Group g, T x, BinaryOperation binary_op)
template<typename Group , typename T , class BinaryOperation >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&detail::is_complex< T >::value &&detail::is_native_op< T, sycl::plus< T >>::value &&detail::is_plus< T, BinaryOperation >::value), T > inclusive_scan_over_group (Group g, T x, BinaryOperation)
template<typename Group , typename V , class BinaryOperation , typename T >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&(detail::is_scalar_arithmetic< V >::value||detail::is_complex< V >::value) &&(detail::is_scalar_arithmetic< T >::value||detail::is_complex< T >::value) &&detail::is_native_op< T, BinaryOperation >::value &&detail::is_plus_or_multiplies_if_complex< T, BinaryOperation >::value &&std::is_convertible_v< V, T >), T > inclusive_scan_over_group (Group g, V x, BinaryOperation binary_op, T init)
template<typename Group , typename V , class BinaryOperation , typename T >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&detail::is_vector_arithmetic_or_complex< V >::value &&detail::is_vector_arithmetic_or_complex< T >::value &&detail::is_native_op< V, BinaryOperation >::value &&detail::is_native_op< T, BinaryOperation >::value), T > inclusive_scan_over_group (Group g, V x, BinaryOperation binary_op, T init)
template<typename Group , typename InPtr , typename OutPtr , class BinaryOperation , typename T >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&detail::is_pointer_v< InPtr > &&detail::is_pointer_v< OutPtr > &&detail::is_arithmetic_or_complex< typename detail::remove_pointer< InPtr >::type >::value &&detail::is_arithmetic_or_complex< typename detail::remove_pointer< OutPtr >::type >::value &&detail::is_arithmetic_or_complex< T >::value &&detail::is_native_op< T, BinaryOperation >::value &&detail::is_plus_or_multiplies_if_complex< T, BinaryOperation >::value), OutPtr > joint_inclusive_scan (Group g, InPtr first, InPtr last, OutPtr result, BinaryOperation binary_op, T init)
template<typename Group , typename InPtr , typename OutPtr , class BinaryOperation >
std::enable_if_t<(is_group_v< std::decay_t< Group >> &&detail::is_pointer_v< InPtr > &&detail::is_pointer_v< OutPtr > &&detail::is_arithmetic_or_complex< typename detail::remove_pointer< InPtr >::type >::value &&detail::is_native_op< typename detail::remove_pointer< OutPtr >::type, BinaryOperation >::value &&detail::is_plus_or_multiplies_if_complex< typename detail::remove_pointer< OutPtr >::type, BinaryOperation >::value), OutPtr > joint_inclusive_scan (Group g, InPtr first, InPtr last, OutPtr result, BinaryOperation binary_op)
template<typename Group >
std::enable_if_t< is_group_v< Group > > group_barrier (Group G, memory_scope FenceScope=Group::fence_scope)
template<backend Backend, int D, typename A >
std::enable_if_t< Backend==backend::ext_oneapi_level_zero, image< D, A > > make_image (const backend_input_t< Backend, image< D, A >> &BackendObject, const context &TargetContext, event AvailableEvent={})
template<typename KernelName >
kernel_id get_kernel_id ()
template<bundle_state State>
kernel_bundle (kernel_bundle< State > &&) -> kernel_bundle< State >
std::vector< kernel_id > get_kernel_ids ()
template<bundle_state State>
kernel_bundle< State > get_kernel_bundle (const context &Ctx, const std::vector< device > &Devs)
A kernel bundle in state State which contains all of the kernels in the application which are compatible with at least one of the devices in Devs.
template<bundle_state State>
kernel_bundle< State > get_kernel_bundle (const context &Ctx)
template<bundle_state State>
kernel_bundle< State > get_kernel_bundle (const context &Ctx, const std::vector< device > &Devs, const std::vector< kernel_id > &KernelIDs)
template<bundle_state State>
kernel_bundle< State > get_kernel_bundle (const context &Ctx, const std::vector< kernel_id > &KernelIDs)
template<typename KernelName , bundle_state State>
kernel_bundle< State > get_kernel_bundle (const context &Ctx)
template<typename KernelName , bundle_state State>
kernel_bundle< State > get_kernel_bundle (const context &Ctx, const std::vector< device > &Devs)
template<bundle_state State, typename SelectorT >
kernel_bundle< State > get_kernel_bundle (const context &Ctx, const std::vector< device > &Devs, SelectorT Selector)
A kernel bundle in state State which contains all of the device images for which the selector returns true.
template<bundle_state State, typename SelectorT >
kernel_bundle< State > get_kernel_bundle (const context &Ctx, SelectorT Selector)
template<bundle_state State>
bool has_kernel_bundle (const context &Ctx, const std::vector< device > &Devs)
template<bundle_state State>
bool has_kernel_bundle (const context &Ctx, const std::vector< device > &Devs, const std::vector< kernel_id > &KernelIDs)
template<bundle_state State>
bool has_kernel_bundle (const context &Ctx)
template<bundle_state State>
bool has_kernel_bundle (const context &Ctx, const std::vector< kernel_id > &KernelIDs)
template<typename KernelName , bundle_state State>
bool has_kernel_bundle (const context &Ctx)
template<typename KernelName , bundle_state State>
bool has_kernel_bundle (const context &Ctx, const std::vector< device > &Devs)
bool is_compatible (const std::vector< kernel_id > &KernelIDs, const device &Dev)
template<typename KernelName >
bool is_compatible (const device &Dev)
template<sycl::bundle_state State>
sycl::kernel_bundle< State > join (const std::vector< sycl::kernel_bundle< State >> &Bundles)
kernel_bundle< bundle_state::object > compile (const kernel_bundle< bundle_state::input > &InputBundle, const std::vector< device > &Devs, const property_list &PropList={})
kernel_bundle< bundle_state::object > compile (const kernel_bundle< bundle_state::input > &InputBundle, const property_list &PropList={})
kernel_bundle< bundle_state::executable > link (const std::vector< kernel_bundle< bundle_state::object >> &ObjectBundles, const std::vector< device > &Devs, const property_list &PropList={})
kernel_bundle< bundle_state::executable > link (const kernel_bundle< bundle_state::object > &ObjectBundle, const property_list &PropList={})
kernel_bundle< bundle_state::executable > link (const std::vector< kernel_bundle< bundle_state::object >> &ObjectBundles, const property_list &PropList={})
kernel_bundle< bundle_state::executable > link (const kernel_bundle< bundle_state::object > &ObjectBundle, const std::vector< device > &Devs, const property_list &PropList={})
kernel_bundle< bundle_state::executable > build (const kernel_bundle< bundle_state::input > &InputBundle, const std::vector< device > &Devs, const property_list &PropList={})
kernel_bundle< bundle_state::executable > build (const kernel_bundle< bundle_state::input > &InputBundle, const property_list &PropList={})
class __SYCL_TYPE (kernel_handler) kernel_handler
Reading the value of a specialization constant.
template<typename ElementType , access::address_space Space, access::decorated DecorateAddress = access::decorated::legacy>
class __SYCL_TYPE (multi_ptr) multi_ptr
Provides constructors for address space qualified and non address space qualified pointers to allow interoperability between plain C++ and OpenCL C.
template<access::address_space Space, access::decorated DecorateAddress>
class __SYCL_TYPE (multi_ptr) multi_ptr< const void
Specialization of multi_ptr for const void.
multi_ptr ()
multi_ptr (const multi_ptr &)=default
multi_ptr (multi_ptr &&)=default
multi_ptr (typename multi_ptr< const void, Space, access::decorated::yes >::pointer ptr)
multi_ptr (std::nullptr_t)
template<typename ElementType , int Dimensions, access::mode Mode, access::placeholder isPlaceholder, typename PropertyListT , access::address_space RelaySpace = Space, typename = typename std::enable_if_t< RelaySpace == Space && (Space == access::address_space::global_space || Space == access::address_space::generic_space || Space == access::address_space::ext_intel_global_device_space)>>
multi_ptr (accessor< ElementType, Dimensions, Mode, target::device, isPlaceholder, PropertyListT > Accessor)
template<typename ElementType , int Dimensions, access::mode Mode, access::placeholder isPlaceholder, typename PropertyListT , access::address_space RelaySpace = Space, typename = typename std::enable_if_t< RelaySpace == Space && Space == access::address_space::local_space>>
__SYCL2020_DEPRECATED ("multi_ptr construction using target::local specialized " "accessor is deprecated since SYCL 2020") multi_ptr(accessor< ElementType
PropertyListT int access::address_space multi_ptr & operator= (multi_ptr &&)=default
multi_ptr & operator= (std::nullptr_t)
pointer get () const
__SYCL2020_DEPRECATED ("Conversion to pointer type is deprecated since SYCL " "2020. Please use get() instead.") operator pointer() const
template<typename ElementType , typename = typename std::enable_if_t<std::is_const_v<ElementType>>>
operator multi_ptr< ElementType, Space, DecorateAddress > () const
template<access::address_space GlobalSpace = access::address_space::global_space, access::address_space RelaySpace = Space, typename = typename std::enable_if_t< RelaySpace == Space && GlobalSpace == access::address_space::global_space && (Space == access::address_space::ext_intel_global_device_space || Space == access::address_space::ext_intel_global_host_space)>>
operator multi_ptr< const void, GlobalSpace, DecorateAddress > () const
template<typename ElementType >
operator multi_ptr< ElementType, Space, DecorateAddress > () const
template<access::address_space GlobalSpace = access::address_space::global_space, access::address_space RelaySpace = Space, typename = typename std::enable_if_t< RelaySpace == Space && GlobalSpace == access::address_space::global_space && (Space == access::address_space::ext_intel_global_device_space || Space == access::address_space::ext_intel_global_host_space)>>
operator multi_ptr< void, GlobalSpace, DecorateAddress > () const
template<typename DataT , int Dimensions>
class __SYCL_EBO __SYCL_SPECIAL_CLASS __SYCL_TYPE (local_accessor) local_accessor
template<typename T , typename AllocatorT , typename BinaryOperation >
auto reduction (buffer< T, 1, AllocatorT > Var, handler &CGH, BinaryOperation Combiner, const property_list &PropList={})
Constructs a reduction object using the given buffer Var, handler CGH, reduction operation Combiner, and optional reduction properties.
template<typename T , typename BinaryOperation >
auto reduction (T *Var, BinaryOperation Combiner, const property_list &PropList={})
Constructs a reduction object using the reduction variable referenced by the given USM pointer Var, handler CGH, reduction operation Combiner, and optional reduction properties.
template<typename T , typename AllocatorT , typename BinaryOperation >
auto reduction (buffer< T, 1, AllocatorT > Var, handler &CGH, const T &Identity, BinaryOperation Combiner, const property_list &PropList={})
Constructs a reduction object using the given buffer Var, handler CGH, reduction identity value Identity, reduction operation Combiner, and optional reduction properties.
template<typename T , typename BinaryOperation >
auto reduction (T *Var, const T &Identity, BinaryOperation Combiner, const property_list &PropList={})
Constructs a reduction object using the reduction variable referenced by the given USM pointer Var, reduction identity value Identity, binary operation Combiner, and optional reduction properties.
template<typename T , size_t Extent, typename BinaryOperation , typename = std::enable_if_t<Extent != dynamic_extent>>
auto reduction (span< T, Extent > Span, BinaryOperation Combiner, const property_list &PropList={})
Constructs a reduction object using the reduction variable referenced by the given sycl::span Span, reduction operation Combiner, and optional reduction properties.
template<typename T , size_t Extent, typename BinaryOperation , typename = std::enable_if_t<Extent != dynamic_extent>>
auto reduction (span< T, Extent > Span, const T &Identity, BinaryOperation Combiner, const property_list &PropList={})
Constructs a reduction object using the reduction variable referenced by the given sycl::span Span, reduction identity value Identity, reduction operation Combiner, and optional reduction properties.
class __SYCL_SPECIAL_CLASS __SYCL_TYPE (sampler) sampler
Encapsulates a configuration for sampling an image accessor.
template<typename T >
class __SYCL_TYPE (specialization_id) specialization_id
Declaring a specialization constant.
__precision_manipulator__ setprecision (int Precision)
__width_manipulator__ setw (int Width)
template<typename T >
class __SYCL_SPECIAL_CLASS __SYCL_TYPE(stream) stream std::enable_if_t< std::is_same_v< T, std::byte >, const stream & > operator<< (const stream &, const T &)
A buffered output stream that allows outputting the values of built-in, vector and SYCL types to the console.
const stream & operator<< (const stream &Out, const char C)
const stream & operator<< (const stream &Out, const char *Str)
const stream & operator<< (const stream &Out, const bool &RHS)
template<typename ValueType >
std::enable_if_t< std::is_integral_v< ValueType >, const stream & > operator<< (const stream &Out, const ValueType &RHS)
const stream & operator<< (const stream &Out, const float &RHS)
const stream & operator<< (const stream &Out, const double &RHS)
const stream & operator<< (const stream &Out, const half &RHS)
const stream & operator<< (const stream &Out, const ext::oneapi::bfloat16 &RHS)
template<typename ElementType , access::address_space Space, access::decorated IsDecorated>
const stream & operator<< (const stream &Out, const multi_ptr< ElementType, Space, IsDecorated > &RHS)
template<typename T >
const stream & operator<< (const stream &Out, const T *RHS)
const stream & operator<< (const stream &Out, const __precision_manipulator__ &RHS)
const stream & operator<< (const stream &Out, const __width_manipulator__ &RHS)
const stream & operator<< (const stream &Out, const stream_manipulator RHS)
template<typename T , int VectorLength>
const stream & operator<< (const stream &Out, const vec< T, VectorLength > &RHS)
template<int Dimensions>
const stream & operator<< (const stream &Out, const id< Dimensions > &RHS)
template<int Dimensions>
const stream & operator<< (const stream &Out, const range< Dimensions > &RHS)
template<int Dimensions>
const stream & operator<< (const stream &Out, const item< Dimensions > &RHS)
template<int Dimensions>
const stream & operator<< (const stream &Out, const nd_range< Dimensions > &RHS)
template<int Dimensions>
const stream & operator<< (const stream &Out, const nd_item< Dimensions > &RHS)
template<int Dimensions>
const stream & operator<< (const stream &Out, const group< Dimensions > &RHS)
template<int Dimensions>
const stream & operator<< (const stream &Out, const h_item< Dimensions > &RHS)
template<typename T , typename RT = detail::EnableIfSwizzleVec<T>>
const stream & operator<< (const stream &Out, const T &RHS)
template<class _Tp , size_t _Extent>
_SYCL_SPAN_INLINE_VISIBILITY auto as_bytes (span< _Tp, _Extent > __s) noexcept -> decltype(__s.__as_bytes())
template<class _Tp , size_t _Extent>
_SYCL_SPAN_INLINE_VISIBILITY auto as_writable_bytes (span< _Tp, _Extent > __s) noexcept -> std::enable_if_t<!std::is_const_v< _Tp >, decltype(__s.__as_writable_bytes())>
template<class _Tp , size_t _Sz>
span (_Tp(&)[_Sz]) -> span< _Tp, _Sz >
template<class _Tp , size_t _Sz>
span (std::array< _Tp, _Sz > &) -> span< _Tp, _Sz >
template<class _Tp , size_t _Sz>
span (const std::array< _Tp, _Sz > &) -> span< const _Tp, _Sz >
template<class _Container >
span (_Container &) -> span< typename _Container::value_type >
template<class _Container >
span (const _Container &) -> span< const typename _Container::value_type >
usm::alloc get_pointer_type (const void *ptr, const context &ctxt)
Query the allocation type from a USM pointer.
device get_pointer_device (const void *ptr, const context &ctxt)
Queries the device against which the pointer was allocated Throws an invalid_object_error if ptr is a host allocation.
void * malloc_device (size_t size, const device &dev, const context &ctxt, const detail::code_location &CodeLoc=detail::code_location::current())
void * malloc_device (size_t size, const device &dev, const context &ctxt, const property_list &propList, const detail::code_location &CodeLoc=detail::code_location::current())
void * malloc_device (size_t size, const queue &q, const detail::code_location &CodeLoc=detail::code_location::current())
void * malloc_device (size_t size, const queue &q, const property_list &propList, const detail::code_location &CodeLoc=detail::code_location::current())
void * aligned_alloc_device (size_t alignment, size_t size, const device &dev, const context &ctxt, const detail::code_location &CodeLoc=detail::code_location::current())
void * aligned_alloc_device (size_t alignment, size_t size, const device &dev, const context &ctxt, const property_list &propList, const detail::code_location &CodeLoc=detail::code_location::current())
void * aligned_alloc_device (size_t alignment, size_t size, const queue &q, const detail::code_location &CodeLoc=detail::code_location::current())
void * aligned_alloc_device (size_t alignment, size_t size, const queue &q, const property_list &propList, const detail::code_location &CodeLoc=detail::code_location::current())
void free (void *ptr, const context &ctxt, const detail::code_location &CodeLoc=detail::code_location::current())
void free (void *ptr, const queue &q, const detail::code_location &CodeLoc=detail::code_location::current())
void * malloc_host (size_t size, const context &ctxt, const detail::code_location &CodeLoc=detail::code_location::current())
void * malloc_host (size_t size, const context &ctxt, const property_list &propList, const detail::code_location &CodeLoc=detail::code_location::current())
void * malloc_host (size_t size, const queue &q, const detail::code_location &CodeLoc=detail::code_location::current())
void * malloc_host (size_t size, const queue &q, const property_list &propList, const detail::code_location &CodeLoc=detail::code_location::current())
void * malloc_shared (size_t size, const device &dev, const context &ctxt, const detail::code_location &CodeLoc=detail::code_location::current())
void * malloc_shared (size_t size, const device &dev, const context &ctxt, const property_list &propList, const detail::code_location &CodeLoc=detail::code_location::current())
void * malloc_shared (size_t size, const queue &q, const detail::code_location &CodeLoc=detail::code_location::current())
void * malloc_shared (size_t size, const queue &q, const property_list &propList, const detail::code_location &CodeLoc=detail::code_location::current())
void * aligned_alloc_host (size_t alignment, size_t size, const context &ctxt, const detail::code_location &CodeLoc=detail::code_location::current())
void * aligned_alloc_host (size_t alignment, size_t size, const context &ctxt, const property_list &propList, const detail::code_location &CodeLoc=detail::code_location::current())
void * aligned_alloc_host (size_t alignment, size_t size, const queue &q, const detail::code_location &CodeLoc=detail::code_location::current())
void * aligned_alloc_host (size_t alignment, size_t size, const queue &q, const property_list &propList, const detail::code_location &CodeLoc=detail::code_location::current())
void * aligned_alloc_shared (size_t alignment, size_t size, const device &dev, const context &ctxt, const detail::code_location &CodeLoc=detail::code_location::current())
void * aligned_alloc_shared (size_t alignment, size_t size, const device &dev, const context &ctxt, const property_list &propList, const detail::code_location &CodeLoc=detail::code_location::current())
void * aligned_alloc_shared (size_t alignment, size_t size, const queue &q, const detail::code_location &CodeLoc=detail::code_location::current())
void * aligned_alloc_shared (size_t alignment, size_t size, const queue &q, const property_list &propList, const detail::code_location &CodeLoc=detail::code_location::current())
void * malloc (size_t size, const device &dev, const context &ctxt, usm::alloc kind, const detail::code_location &CodeLoc=detail::code_location::current())
void * malloc (size_t size, const device &dev, const context &ctxt, usm::alloc kind, const property_list &propList, const detail::code_location &CodeLoc=detail::code_location::current())
void * malloc (size_t size, const queue &q, usm::alloc kind, const detail::code_location &CodeLoc=detail::code_location::current())
void * malloc (size_t size, const queue &q, usm::alloc kind, const property_list &propList, const detail::code_location &CodeLoc=detail::code_location::current())
void * aligned_alloc (size_t alignment, size_t size, const device &dev, const context &ctxt, usm::alloc kind, const detail::code_location &CodeLoc=detail::code_location::current())
void * aligned_alloc (size_t alignment, size_t size, const device &dev, const context &ctxt, usm::alloc kind, const property_list &propList, const detail::code_location &CodeLoc=detail::code_location::current())
void * aligned_alloc (size_t alignment, size_t size, const queue &q, usm::alloc kind, const detail::code_location &CodeLoc=detail::code_location::current())
void * aligned_alloc (size_t alignment, size_t size, const queue &q, usm::alloc kind, const property_list &propList, const detail::code_location &CodeLoc=detail::code_location::current())
size_t is_not_power_of_two (size_t Alignment)
BUILTIN_COMMON (ONE_ARG, degrees, [](auto x) -> decltype(x) { return(180/M_PI) *x;}) BUILTIN_COMMON(ONE_ARG
BUILTIN_COMMON (ONE_ARG, sign, [](auto x) -> decltype(x) { using T=decltype(x);if(std::isnan(x)) return T(0.0);if(x > 0) return T(1.0);if(x< 0) return T(-1.0);return x;}) BUILTIN_COMMON(THREE_ARGS
BUILTIN_COMMON (TWO_ARGS, step, [](auto x, auto y) -> decltype(x) { return y< x ? 0.0 :1.0;}) BUILTIN_COMMON(THREE_ARGS
BUILTIN_COMMON (TWO_ARGS, max, [](auto x, auto y) -> decltype(x) { return(x< y ? y :x);}) BUILTIN_COMMON(TWO_ARGS
template<typename T >
static T cross_host_impl (T p0, T p1)
template<typename T0 , typename T1 >
static auto dot_host_impl (T0 x, T1 y)
template<typename T >
static auto length_host_impl (T x)
template<typename T >
static auto fast_length_host_impl (T x)
template<typename T0 , typename T1 >
static auto distance_host_impl (T0 x, T1 y)
template<typename T0 , typename T1 >
static auto fast_distance_host_impl (T0 x, T1 y)
template<typename T >
static auto normalize_host_impl (T x)
template<typename T >
static auto fast_normalize_host_impl (T x)
BUILTIN_GENINT (ONE_ARG, abs, [](auto x) -> decltype(x) { if constexpr(std::is_signed_v< decltype(x)>) { return std::abs(x);} else { return x;} }) BUILTIN_GENINT_SU(TWO_ARGS
return std::max(x, y) - std BUILTIN_GENINT_SU (TWO_ARGS, add_sat, [](auto x, auto y) -> decltype(x) { using T=decltype(x);if constexpr(std::is_signed_v< T >) { if(x > 0 &&y > 0) return(x<(std::numeric_limits< T >::max() - y) ?(x+y) :std::numeric_limits< T >::max());if(x< 0 &&y< 0) return(x >(std::numeric_limits< T >::min() - y) ?(x+y) :std::numeric_limits< T >::min());return x+y;} else { return(x<(std::numeric_limits< T >::max() - y) ? x+y :std::numeric_limits< T >::max());} }) BUILTIN_GENINT_SU(TWO_ARGS
return (x >> one)+(y >> one)+((y &x) &one)
BUILTIN_GENINT_SU (TWO_ARGS, rhadd, [](auto x, auto y) -> decltype(x) { const decltype(x) one=1;return(x >> one)+(y >> one)+((y|x) &one);}) BUILTIN_GENINT_SU(THREE_ARGS
BUILTIN_GENINT_SU (THREE_ARGS, mad_sat, [](auto a, auto b, auto c) -> decltype(a) { using T=decltype(a);if constexpr(std::is_signed_v< T >) { if constexpr(sizeof(T)==8) { bool neg_prod=(a< 0) ^(b< 0);T mulhi=__s_long_mul_hi(a, b);if(!neg_prod &&mulhi !=0) return std::numeric_limits< T >::max();if(neg_prod &&mulhi !=-1) return std::numeric_limits< T >::min();return sycl::add_sat(T(a *b), c);} else { using UPT=sycl::detail::make_larger_t< T >;UPT mul=UPT(a) *UPT(b);UPT res=mul+UPT(c);const UPT max=std::numeric_limits< T >::max();const UPT min=std::numeric_limits< T >::min();res=std::min(std::max(res, min), max);return T(res);} } else { if constexpr(sizeof(T)==8) { T mulhi=__u_long_mul_hi(a, b);if(mulhi !=0) return std::numeric_limits< T >::max();return sycl::add_sat(T(a *b), c);} else { using UPT=sycl::detail::make_larger_t< T >;UPT mul=UPT(a) *UPT(b);const UPT min=std::numeric_limits< T >::min();const UPT max=std::numeric_limits< T >::max();mul=std::min(std::max(mul, min), max);return sycl::add_sat(T(mul), c);} } }) BUILTIN_GENINT_SU(TWO_ARGS
constexpr if (sizeof(T)==8)
return (mul >>(sizeof(T) *8))
BUILTIN_GENINT_SU (TWO_ARGS, sub_sat, [](auto x, auto y) -> decltype(x) { using T=decltype(x);if constexpr(std::is_signed_v< T >) { using UT=std::make_unsigned_t< T >;T result=UT(x) - UT(y);if(((x< 0) ^(y< 0)) &&((x< 0) ^(result< 0))) result=result< 0 ? std::numeric_limits< T >::max() :std::numeric_limits< T >::min();return result;} else { return(y<(x - std::numeric_limits< T >::min())) ?(x - y) :std::numeric_limits< T >::min();} }) BUILTIN_GENINT_SU(TWO_ARGS
BUILTIN_GENINT_SU (TWO_ARGS, min, [](auto x, auto y) -> decltype(x) { return y< x ? y :x;}) BUILTIN_GENINT_SU(THREE_ARGS
template<typename T >
static constexpr T __clz_impl (T x, T m, T n=0)
template<typename T >
static constexpr T __clz (T x)
template<typename T >
static constexpr T __ctz_impl (T x, T m, T n=0)
template<typename T >
static constexpr T __ctz (T x)
BUILTIN_GENINT (TWO_ARGS, rotate, [](auto x, auto n) -> decltype(x) { using T=decltype(x);using UT=std::make_unsigned_t< T >;constexpr UT size=sizeof(x) *8;UT xu=UT(x);UT nu=UT(n) &(size - 1);return(xu<< nu)|(xu >>(size - nu));}) template< typename T > static inline const expr T __popcount_impl(T x
BUILTIN_GENF_CUSTOM (ONE_ARG, acospi, [](auto x) -> decltype(x) { return std::acos(x)/M_PI;}) BUILTIN_GENF_CUSTOM(ONE_ARG
BUILTIN_GENF_CUSTOM (ONE_ARG, atanpi, [](auto x) -> decltype(x) { return std::atan(x)/M_PI;}) BUILTIN_GENF_CUSTOM(TWO_ARGS
BUILTIN_GENF_CUSTOM (ONE_ARG, cospi, [](auto x) -> decltype(x) { return std::sin(M_PI *(0.5 - x));}) BUILTIN_GENF_CUSTOM(ONE_ARG
BUILTIN_GENF_CUSTOM (THREE_ARGS, mad, [](auto x, auto y, auto z) -> decltype(x) { return(x *y)+z;}) BUILTIN_GENF_CUSTOM(TWO_ARGS
if (std::fabs(y) > std::fabs(x)) return y
BUILTIN_GENF_CUSTOM (TWO_ARGS, minmag, [](auto x, auto y) -> decltype(x) { if(std::fabs(x)< std::fabs(y)) return x;if(std::fabs(y)< std::fabs(x)) return y;return std::fmin(x, y);}) BUILTIN_GENF_CUSTOM(TWO_ARGS
return(x >=T(0)) ? T(std BUILTIN_GENF_CUSTOM (ONE_ARG, rsqrt, [](auto x) -> decltype(x) { return decltype(x){1.0}/std::sqrt(x);}) BUILTIN_GENF_CUSTOM(ONE_ARG
BUILTIN_GENF_CUSTOM (ONE_ARG, tanpi, [](auto x) -> decltype(x) { double y=x - std::floor(x);return 1.0/std::tan((0.5 - y) *M_PI);}) BUILTIN_GENF_CUSTOM(TWO_ARGS
template<typename T >
static auto process_arg_for_macos (T x)
REL_BUILTIN_CUSTOM (TWO_ARGS, isequal,([](auto x, auto y) { return x==y;})) REL_BUILTIN_CUSTOM(TWO_ARGS
REL_BUILTIN_CUSTOM (TWO_ARGS, isgreater,([](auto x, auto y) { return x > y;})) REL_BUILTIN_CUSTOM(TWO_ARGS
REL_BUILTIN_CUSTOM (TWO_ARGS, isless,([](auto x, auto y) { return x< y;})) REL_BUILTIN_CUSTOM(TWO_ARGS
REL_BUILTIN_CUSTOM (TWO_ARGS, islessgreater,([](auto x, auto y) { return x< y||x > y;})) REL_BUILTIN_CUSTOM(TWO_ARGS
namespace __SYCL2020_DEPRECATED ("use 'ext::oneapi' instead") ONEAPI
namespace __SYCL2020_DEPRECATED ("use 'ext::intel::experimental' instead") INTEL
void * malloc (size_t Size, const device &Dev, const context &Ctxt, alloc Kind, const property_list &PropList, const detail::code_location &CodeLoc)
void * malloc (size_t Size, const device &Dev, const context &Ctxt, alloc Kind, const detail::code_location &CodeLoc)
void * malloc (size_t Size, const queue &Q, alloc Kind, const detail::code_location &CodeLoc)
void * malloc (size_t Size, const queue &Q, alloc Kind, const property_list &PropList, const detail::code_location &CodeLoc)
void * aligned_alloc (size_t Alignment, size_t Size, const device &Dev, const context &Ctxt, alloc Kind, const detail::code_location &CodeLoc)
void * aligned_alloc (size_t Alignment, size_t Size, const device &Dev, const context &Ctxt, alloc Kind, const property_list &PropList, const detail::code_location &CodeLoc)
void * aligned_alloc (size_t Alignment, size_t Size, const queue &Q, alloc Kind, const detail::code_location &CodeLoc)
void * aligned_alloc (size_t Alignment, size_t Size, const queue &Q, alloc Kind, const property_list &PropList, const detail::code_location &CodeLoc)
static void prepare_for_usm_device_copy (const void *Ptr, size_t Size, const context &Ctxt)
static void release_from_usm_device_copy (const void *Ptr, const context &Ctxt)
template std::vector< device > device::create_sub_devices< info::partition_property::partition_equally > (size_t ComputeUnits) const
template std::vector< device > device::create_sub_devices< info::partition_property::partition_by_counts > (const std::vector< size_t > &Counts) const
template std::vector< device > device::create_sub_devices< info::partition_property::partition_by_affinity_domain > (info::partition_affinity_domain AffinityDomain) const
template std::vector< device > device::create_sub_devices< info::partition_property::ext_intel_partition_by_cslice > () const
template<>
device device::get_info_impl< info::device::parent_device > () const
template<>
std::vector< sycl::aspect > device::get_info_impl< info::device::aspects > () const
template<>
bool device::get_info_impl< info::device::image_support > () const
static void traceDeviceSelector (const std::string &DeviceType)
default_selector_v Devices of different kinds are prioritized in the following order:
static void addArgsForGlobalAccessor (detail::Requirement *AccImpl, size_t Index, size_t &IndexShift, int Size, bool IsKernelCreatedFromSource, size_t GlobalSize, std::vector< detail::ArgDesc > &Args, bool isESIMD)
static bool checkContextSupports (const std::shared_ptr< detail::context_impl > &ContextImpl, sycl::detail::pi::PiContextInfo InfoQuery)
template uint32_t kernel::get_info< info::kernel_device_specific::max_sub_group_size > (const device &, const sycl::range< 3 > &) const
template ext::oneapi::experimental::info::kernel_queue_specific::max_num_work_group_sync::return_type kernel::ext_oneapi_get_info< ext::oneapi::experimental::info::kernel_queue_specific::max_num_work_group_sync > (const queue &Queue) const
static event getBarrierEventForInorderQueueHelper (const detail::QueueImplPtr QueueImpl)
static size_t CheckMaxStatementSize (const size_t &MaxStatementSize)
Variables
constexpr mode_tag_t< access_mode::read > read_only {}
constexpr mode_tag_t< access_mode::read_write > read_write {}
constexpr mode_tag_t< access_mode::write > write_only {}
constexpr mode_target_tag_t< access_mode::read, target::constant_buffer > read_constant {}
constexpr mode_target_tag_t< access_mode::read, target::host_task > read_only_host_task
constexpr mode_target_tag_t< access_mode::read_write, target::host_task > read_write_host_task
constexpr mode_target_tag_t< access_mode::write, target::host_task > write_only_host_task
class __SYCL_EBO __SYCL_SPECIAL_CLASS Dimensions
class __SYCL_EBO __SYCL_SPECIAL_CLASS AccessMode
class __SYCL_EBO __SYCL_SPECIAL_CLASS IsPlaceholder
template<typename T >
constexpr bool is_device_copyable_v = is_device_copyable<T>::value
template<class T >
constexpr bool is_group_v = is_group<T>::value
template<typename BinaryOperation , typename AccumulatorT >
constexpr bool has_known_identity_v
template<typename BinaryOperation , typename AccumulatorT >
constexpr AccumulatorT known_identity_v
constexpr auto memory_scope_work_item = memory_scope::work_item
constexpr auto memory_scope_sub_group = memory_scope::sub_group
constexpr auto memory_scope_work_group = memory_scope::work_group
constexpr auto memory_scope_device = memory_scope::device
constexpr auto memory_scope_system = memory_scope::system
constexpr auto memory_order_relaxed = memory_order::relaxed
constexpr auto memory_order_acquire = memory_order::acquire
constexpr auto memory_order_release = memory_order::release
constexpr auto memory_order_acq_rel = memory_order::acq_rel
constexpr auto memory_order_seq_cst = memory_order::seq_cst
static constexpr bool is_decorated
static constexpr access::address_space address_space = Space
Mode
isPlaceholder
PropertyListT Accessor
PropertyListT int access::address_space RelaySpace = Space
constexpr property::no_init no_init
constexpr property::noinit noinit
template<typename propertyT >
constexpr bool is_property_v = is_property<propertyT>::value
template<typename propertyT , typename syclObjectT >
constexpr bool is_property_of_v
constexpr stream_manipulator dec = stream_manipulator::dec
constexpr stream_manipulator hex = stream_manipulator::hex
constexpr stream_manipulator oct = stream_manipulator::oct
constexpr stream_manipulator noshowbase = stream_manipulator::noshowbase
constexpr stream_manipulator showbase = stream_manipulator::showbase
constexpr stream_manipulator noshowpos = stream_manipulator::noshowpos
constexpr stream_manipulator showpos = stream_manipulator::showpos
constexpr stream_manipulator endl = stream_manipulator::endl
constexpr stream_manipulator flush = stream_manipulator::flush
constexpr stream_manipulator fixed = stream_manipulator::fixed
constexpr stream_manipulator scientific = stream_manipulator::scientific
constexpr stream_manipulator hexfloat = stream_manipulator::hexfloat
constexpr stream_manipulator defaultfloat = stream_manipulator::defaultfloat
constexpr size_t dynamic_extent = SIZE_MAX
radians
autodecltype(x) x { return (M_PI / 180) * x
mix
auto auto y { return (y < x ? y : x)
auto auto autodecltype(x) z
smoothstep
auto t = sycl::clamp((z - x) / (y - x), T{0}, T{1})
min
abs_diff
return std::max(x, y) - std hadd
mad_hi
mul_hi
auto a
auto autodecltype(a) b
else
UPT a_s = a
UPT b_s = b
UPT mul = a_s * b_s
max
clamp
asinpi
atan2pi
exp10
maxmag
powr
return(x >=T(0)) ? T(std sinpi
nextafter
isnotequal
isgreaterequal
islessequal
isordered
constexpr size_t MaxNumAdditionalArgs = 13
static constexpr size_t MAX_STATEMENT_SIZE
Typedef Documentation
__SYCL2020_DEPRECATED
namespace sycl::_V1::__SYCL2020_DEPRECATED
Definition at line 94 of file aliases.hpp.
access_mode
using sycl::_V1::access_mode = typedef access::mode
Definition at line 72 of file access.hpp.
alloc
using sycl::_V1::alloc = typedef sycl::usm::alloc
Definition at line 35 of file usm_impl.cpp.
async_handler
using sycl::_V1::async_handler = typedef std::function<void(sycl::exception_list)>
Definition at line 19 of file async_handler.hpp.
backend_input_t
template<backend Backend, typename SyclType > using sycl::_V1::backend_input_t = typedef typename backend_traits<Backend>::template input_type<SYCLObjectT>
Definition at line 82 of file backend.hpp.
backend_return_t
template<backend Backend, typename SyclType > using sycl::_V1::backend_return_t = typedef typename backend_traits<Backend>::template return_type<SYCLObjectT>
Definition at line 86 of file backend.hpp.
bit_and
template<typename T = void> using sycl::_V1::bit_and = typedef std::bit_and<T>
Definition at line 20 of file functional.hpp.
bit_or
template<typename T = void> using sycl::_V1::bit_or = typedef std::bit_or<T>
Definition at line 21 of file functional.hpp.
bit_xor
template<typename T = void> using sycl::_V1::bit_xor = typedef std::bit_xor<T>
Definition at line 22 of file functional.hpp.
buffer_allocator
template<typename DataT > using sycl::_V1::buffer_allocator = typedef detail::sycl_memory_object_allocator<DataT>
Definition at line 53 of file buffer.hpp.
byte
typedef unsigned char sycl::_V1::byte
Definition at line 107 of file image.hpp.
constant_ptr
template<typename ElementType > using sycl::_V1::constant_ptr = typedef multi_ptr<ElementType, access::address_space::constant_space, access::decorated::legacy>
Definition at line 37 of file pointers.hpp.
ContextImplPtr
using sycl::_V1::ContextImplPtr = typedef std::shared_ptr<sycl::detail::context_impl>
Definition at line 22 of file helpers.cpp.
decorated_global_ptr
template<typename ElementType > using sycl::_V1::decorated_global_ptr = typedef multi_ptr<ElementType, access::address_space::global_space, access::decorated::yes>
Definition at line 68 of file pointers.hpp.
decorated_local_ptr
template<typename ElementType > using sycl::_V1::decorated_local_ptr = typedef multi_ptr<ElementType, access::address_space::local_space, access::decorated::yes>
Definition at line 73 of file pointers.hpp.
decorated_private_ptr
template<typename ElementType > using sycl::_V1::decorated_private_ptr = typedef multi_ptr<ElementType, access::address_space::private_space, access::decorated::yes>
Definition at line 78 of file pointers.hpp.
difference_type
typedef std::ptrdiff_t sycl::_V1::difference_type
Definition at line 460 of file multi_ptr.hpp.
errc_for
template<backend B> using sycl::_V1::errc_for = typedef typename backend_traits<B>::errc
Definition at line 53 of file exception.hpp.
generic_ptr
template<typename ElementType , access::decorated IsDecorated = access::decorated::legacy> using sycl::_V1::generic_ptr = typedef multi_ptr<ElementType, access::address_space::generic_space, IsDecorated>
Definition at line 23 of file pointers.hpp.
global_ptr
template<typename ElementType , access::decorated IsDecorated = access::decorated::legacy> using sycl::_V1::global_ptr = typedef multi_ptr<ElementType, access::address_space::global_space, IsDecorated>
Definition at line 28 of file pointers.hpp.
half
typedef detail::half_impl::half sycl::_V1::half
Definition at line 101 of file aliases.hpp.
image_allocator
using sycl::_V1::image_allocator = typedef detail::aligned_allocator<byte>
Definition at line 109 of file image.hpp.
instead
typedef double sycl::_V1::instead
Definition at line 93 of file aliases.hpp.
local_ptr
template<typename ElementType , access::decorated IsDecorated = access::decorated::legacy> using sycl::_V1::local_ptr = typedef multi_ptr<ElementType, access::address_space::local_space, IsDecorated>
Definition at line 33 of file pointers.hpp.
multiplies
template<typename T = void> using sycl::_V1::multiplies = typedef std::multiplies<T>
Definition at line 19 of file functional.hpp.
pipe
template<class name , class dataT , int32_t min_capacity = 0> using sycl::_V1::pipe = typedef ext::intel::pipe<name, dataT, min_capacity>
Definition at line 18 of file pipes.hpp.
plus
template<typename T = void> using sycl::_V1::plus = typedef std::plus<T>
Definition at line 18 of file functional.hpp.
pointer
typedef std::conditional_t< is_decorated, decorated_type *, std::add_pointer_t< value_type > > sycl::_V1::pointer
Definition at line 458 of file multi_ptr.hpp.
private_ptr
template<typename ElementType , access::decorated IsDecorated = access::decorated::legacy> using sycl::_V1::private_ptr = typedef multi_ptr<ElementType, access::address_space::private_space, IsDecorated>
Definition at line 43 of file pointers.hpp.
raw_global_ptr
template<typename ElementType > using sycl::_V1::raw_global_ptr = typedef multi_ptr<ElementType, access::address_space::global_space, access::decorated::no>
Definition at line 51 of file pointers.hpp.
raw_local_ptr
template<typename ElementType > using sycl::_V1::raw_local_ptr = typedef multi_ptr<ElementType, access::address_space::local_space, access::decorated::no>
Definition at line 56 of file pointers.hpp.
raw_private_ptr
template<typename ElementType > using sycl::_V1::raw_private_ptr = typedef multi_ptr<ElementType, access::address_space::private_space, access::decorated::no>
Definition at line 60 of file pointers.hpp.
remove_decoration_t
template<typename T > using sycl::_V1::remove_decoration_t = typedef typename remove_decoration<T>::type
Definition at line 325 of file access.hpp.
value_type
typedef void sycl::_V1::value_type
Definition at line 457 of file multi_ptr.hpp.
vec_data
template<typename T > using sycl::_V1::vec_data = typedef detail::vec_helper<T>
Definition at line 351 of file vector.hpp.
vec_data_t
template<typename T > using sycl::_V1::vec_data_t = typedef typename detail::vec_helper<T>::RetType
Definition at line 354 of file vector.hpp.
Enumeration Type Documentation
addressing_mode
enum sycl::_V1::addressing_mode : unsigned int strong
Enumerator
mirrored_repeat
repeat
clamp_to_edge
clamp
none
Definition at line 24 of file sampler.hpp.
backend
enum sycl::_V1::backend : char strong
Enumerator
__SYCL2020_DEPRECATED
opencl
ext_oneapi_level_zero
ext_oneapi_cuda
all
__SYCL_DEPRECATED
ext_oneapi_hip
ext_oneapi_native_cpu
Definition at line 18 of file backend_types.hpp.
bundle_state
enum sycl::_V1::bundle_state : char strong
Enumerator
input
object
executable
ext_oneapi_source
Definition at line 14 of file kernel_bundle_enums.hpp.
coordinate_normalization_mode
enum sycl::_V1::coordinate_normalization_mode : unsigned int strong
Enumerator
normalized
unnormalized
Definition at line 37 of file sampler.hpp.
errc
enum sycl::_V1::errc : unsigned int strong
Enumerator
success
runtime
kernel
accessor
nd_range
event
kernel_argument
build
invalid
memory_allocation
platform
profiling
feature_not_supported
kernel_not_supported
backend_mismatch
Definition at line 35 of file exception.hpp.
filtering_mode
enum sycl::_V1::filtering_mode : unsigned int strong
Enumerator
nearest
linear
Definition at line 32 of file sampler.hpp.
image_channel_order
enum sycl::_V1::image_channel_order : unsigned int strong
Enumerator
a
r
rx
rg
rgx
ra
rgb
rgbx
rgba
argb
bgra
intensity
luminance
abgr
ext_oneapi_srgba
Definition at line 56 of file image.hpp.
image_channel_type
enum sycl::_V1::image_channel_type : unsigned int strong
Enumerator
snorm_int8
snorm_int16
unorm_int8
unorm_int16
unorm_short_565
unorm_short_555
unorm_int_101010
signed_int8
signed_int16
signed_int32
unsigned_int8
unsigned_int16
unsigned_int32
fp16
fp32
Definition at line 74 of file image.hpp.
image_format
enum sycl::_V1::image_format : unsigned int strong
Enumerator
r8g8b8a8_unorm
r16g16b16a16_unorm
r8g8b8a8_sint
r16g16b16a16_sint
r32b32g32a32_sint
r8g8b8a8_uint
r16g16b16a16_uint
r32b32g32a32_uint
r16b16g16a16_sfloat
r32g32b32a32_sfloat
b8g8r8a8_unorm
Definition at line 93 of file image.hpp.
image_target
enum sycl::_V1::image_target : unsigned int strong
Enumerator
device
host_task
Definition at line 74 of file access.hpp.
memory_order
enum sycl::_V1::memory_order : int strong
Enumerator
relaxed
acquire
__consume_unsupported
release
acq_rel
seq_cst
Definition at line 19 of file memory_enums.hpp.
memory_scope
enum sycl::_V1::memory_scope : int strong
Enumerator
work_item
sub_group
work_group
device
system
Definition at line 29 of file memory_enums.hpp.
stream_manipulator
enum sycl::_V1::stream_manipulator strong
Enumerator
dec
hex
oct
noshowbase
showbase
noshowpos
showpos
endl
flush
fixed
scientific
hexfloat
defaultfloat
Definition at line 768 of file stream.hpp.
Function Documentation
__clz()
template<typename T > static constexpr T sycl::_V1::__clz (T x) inline static constexpr
Definition at line 225 of file integer_functions.cpp.
__clz_impl()
template<typename T > static constexpr T sycl::_V1::__clz_impl (T x, T m, T n = 0) inline static constexpr
Definition at line 222 of file integer_functions.cpp.
__ctz()
template<typename T > static constexpr T sycl::_V1::__ctz (T x) inline static constexpr
Definition at line 236 of file integer_functions.cpp.
__ctz_impl()
template<typename T > static constexpr T sycl::_V1::__ctz_impl (T x, T m, T n = 0) inline static constexpr
Definition at line 232 of file integer_functions.cpp.
__SYCL2020_DEPRECATED() [1/6]
sycl::_V1::__SYCL2020_DEPRECATED ("Conversion to pointer type is deprecated since SYCL " "2020. Please use get() instead.") const
Definition at line 547 of file multi_ptr.hpp.
__SYCL2020_DEPRECATED() [2/6]
template<typename ElementType , int Dimensions, access::mode Mode, access::placeholder isPlaceholder, typename PropertyListT , access::address_space RelaySpace = Space, typename = typename std::enable_if_t< RelaySpace == Space && Space == access::address_space::local_space>> sycl::_V1::__SYCL2020_DEPRECATED ("multi_ptr construction using target::local specialized " "accessor is deprecated since SYCL 2020")
__SYCL2020_DEPRECATED() [3/6]
template<typename T , access::address_space addressSpace = access::address_space::global_space> class sycl::_V1::__SYCL2020_DEPRECATED ("sycl::atomic is deprecated since SYCL 2020")
Definition at line 82 of file atomic.hpp.
__SYCL2020_DEPRECATED() [4/6]
namespace sycl::_V1::__SYCL2020_DEPRECATED ("use 'ext::intel::experimental' instead")
Definition at line 1 of file online_compiler.cpp.
__SYCL2020_DEPRECATED() [5/6]
namespace sycl::_V1::__SYCL2020_DEPRECATED ("use 'ext::oneapi' instead")
Definition at line 1 of file filter_selector_impl.cpp.
__SYCL2020_DEPRECATED() [6/6]
namespace sycl::_V1::__SYCL2020_DEPRECATED ("use 'ext::oneapi::level_zero' instead")
Definition at line 241 of file level_zero.hpp.
__SYCL_TYPE() [1/4]
enum sycl::_V1::__SYCL_TYPE (aspect) strong
Definition at line 1 of file aspects.hpp.
__SYCL_TYPE() [2/4]
template<typename DataT , int Dimensions> class __SYCL_EBO __SYCL_SPECIAL_CLASS sycl::_V1::__SYCL_TYPE (local_accessor)
__SYCL_TYPE() [3/4]
template<access::address_space Space, access::decorated DecorateAddress> class sycl::_V1::__SYCL_TYPE (multi_ptr) const
Specialization of multi_ptr for const void.
__SYCL_TYPE() [4/4]
template<typename T , int Dimensions = 1> class sycl::_V1::__SYCL_TYPE (private_memory)
Definition at line 1 of file group.hpp.
accelerator_selector_v()
int sycl::_V1::accelerator_selector_v (const device & dev)
Definition at line 235 of file device_selector.cpp.
Referenced by sycl::_V1::accelerator_selector::operator()(), and sycl::_V1::detail::select_device().
accessor() [1/19]
template<typename DataT , int Dimensions, typename AllocatorT , typename... PropsT> sycl::_V1::accessor (buffer< DataT, Dimensions, AllocatorT > , const ext::oneapi::accessor_property_list< PropsT... > &) -> accessor< DataT, Dimensions, access::mode::read_write, target::device, access::placeholder::true_t, ext::oneapi::accessor_property_list< PropsT... >>
accessor() [2/19]
template<typename DataT , int Dimensions, typename AllocatorT > sycl::_V1::accessor (buffer< DataT, Dimensions, AllocatorT > , handler &) -> accessor< DataT, Dimensions, access::mode::read_write, target::device, access::placeholder::false_t >
accessor() [3/19]
template<typename DataT , int Dimensions, typename AllocatorT , typename... PropsT> sycl::_V1::accessor (buffer< DataT, Dimensions, AllocatorT > , handler & , const ext::oneapi::accessor_property_list< PropsT... > &) -> accessor< DataT, Dimensions, access::mode::read_write, target::device, access::placeholder::false_t, ext::oneapi::accessor_property_list< PropsT... >>
accessor() [4/19]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 > sycl::_V1::accessor (buffer< DataT, Dimensions, AllocatorT > , handler & , Type1) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type1, Type1 >(), detail::deduceAccessTarget< Type1, Type1 >(target::device), access::placeholder::false_t >
accessor() [5/19]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename... PropsT> sycl::_V1::accessor (buffer< DataT, Dimensions, AllocatorT > , handler & , Type1 , const ext::oneapi::accessor_property_list< PropsT... > &) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type1, Type1 >(), detail::deduceAccessTarget< Type1, Type1 >(target::device), access::placeholder::false_t, ext::oneapi::accessor_property_list< PropsT... >>
accessor() [6/19]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 > sycl::_V1::accessor (buffer< DataT, Dimensions, AllocatorT > , handler & , Type1 , Type2) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type1, Type2 >(), detail::deduceAccessTarget< Type1, Type2 >(target::device), access::placeholder::false_t >
accessor() [7/19]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename... PropsT> sycl::_V1::accessor (buffer< DataT, Dimensions, AllocatorT > , handler & , Type1 , Type2 , const ext::oneapi::accessor_property_list< PropsT... > &) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type1, Type2 >(), detail::deduceAccessTarget< Type1, Type2 >(target::device), access::placeholder::false_t, ext::oneapi::accessor_property_list< PropsT... >>
accessor() [8/19]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 > sycl::_V1::accessor (buffer< DataT, Dimensions, AllocatorT > , handler & , Type1 , Type2 , Type3) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type2, Type3 >(), detail::deduceAccessTarget< Type2, Type3 >(target::device), access::placeholder::false_t >
accessor() [9/19]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 , typename... PropsT> sycl::_V1::accessor (buffer< DataT, Dimensions, AllocatorT > , handler & , Type1 , Type2 , Type3 , const ext::oneapi::accessor_property_list< PropsT... > &) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type2, Type3 >(), detail::deduceAccessTarget< Type2, Type3 >(target::device), access::placeholder::false_t, ext::oneapi::accessor_property_list< PropsT... >>
accessor() [10/19]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 , typename Type4 > sycl::_V1::accessor (buffer< DataT, Dimensions, AllocatorT > , handler & , Type1 , Type2 , Type3 , Type4) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type3, Type4 >(), detail::deduceAccessTarget< Type3, Type4 >(target::device), access::placeholder::false_t >
accessor() [11/19]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 , typename Type4 , typename... PropsT> sycl::_V1::accessor (buffer< DataT, Dimensions, AllocatorT > , handler & , Type1 , Type2 , Type3 , Type4 , const ext::oneapi::accessor_property_list< PropsT... > &) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type3, Type4 >(), detail::deduceAccessTarget< Type3, Type4 >(target::device), access::placeholder::false_t, ext::oneapi::accessor_property_list< PropsT... >>
accessor() [12/19]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 > sycl::_V1::accessor (buffer< DataT, Dimensions, AllocatorT > , Type1) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type1, Type1 >(), detail::deduceAccessTarget< Type1, Type1 >(target::device), access::placeholder::true_t >
accessor() [13/19]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename... PropsT> sycl::_V1::accessor (buffer< DataT, Dimensions, AllocatorT > , Type1 , const ext::oneapi::accessor_property_list< PropsT... > &) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type1, Type1 >(), detail::deduceAccessTarget< Type1, Type1 >(target::device), access::placeholder::true_t, ext::oneapi::accessor_property_list< PropsT... >>
accessor() [14/19]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 > sycl::_V1::accessor (buffer< DataT, Dimensions, AllocatorT > , Type1 , Type2) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type1, Type2 >(), detail::deduceAccessTarget< Type1, Type2 >(target::device), access::placeholder::true_t >
accessor() [15/19]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename... PropsT> sycl::_V1::accessor (buffer< DataT, Dimensions, AllocatorT > , Type1 , Type2 , const ext::oneapi::accessor_property_list< PropsT... > &) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type1, Type2 >(), detail::deduceAccessTarget< Type1, Type2 >(target::device), access::placeholder::true_t, ext::oneapi::accessor_property_list< PropsT... >>
accessor() [16/19]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 > sycl::_V1::accessor (buffer< DataT, Dimensions, AllocatorT > , Type1 , Type2 , Type3) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type2, Type3 >(), detail::deduceAccessTarget< Type2, Type3 >(target::device), access::placeholder::true_t >
accessor() [17/19]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 , typename... PropsT> sycl::_V1::accessor (buffer< DataT, Dimensions, AllocatorT > , Type1 , Type2 , Type3 , const ext::oneapi::accessor_property_list< PropsT... > &) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type2, Type3 >(), detail::deduceAccessTarget< Type2, Type3 >(target::device), access::placeholder::true_t, ext::oneapi::accessor_property_list< PropsT... >>
accessor() [18/19]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 , typename Type4 > sycl::_V1::accessor (buffer< DataT, Dimensions, AllocatorT > , Type1 , Type2 , Type3 , Type4) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type3, Type4 >(), detail::deduceAccessTarget< Type3, Type4 >(target::device), access::placeholder::true_t >
accessor() [19/19]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 , typename Type4 , typename... PropsT> sycl::_V1::accessor (buffer< DataT, Dimensions, AllocatorT > , Type1 , Type2 , Type3 , Type4 , const ext::oneapi::accessor_property_list< PropsT... > &) -> accessor< DataT, Dimensions, detail::deduceAccessMode< Type3, Type4 >(), detail::deduceAccessTarget< Type3, Type4 >(target::device), access::placeholder::true_t, ext::oneapi::accessor_property_list< PropsT... >>
addArgsForGlobalAccessor()
static void sycl::_V1::addArgsForGlobalAccessor (detail::Requirement * AccImpl, size_t Index, size_t & IndexShift, int Size, bool IsKernelCreatedFromSource, size_t GlobalSize, std::vector< detail::ArgDesc > & Args, bool isESIMD) static
Definition at line 655 of file handler.cpp.
aligned_alloc() [1/8]
void* sycl::_V1::aligned_alloc (size_t Alignment, size_t Size, const device & Dev, const context & Ctxt, alloc Kind, const detail::code_location & CodeLoc)
Definition at line 527 of file usm_impl.cpp.
aligned_alloc() [2/8]
void* sycl::_V1::aligned_alloc (size_t Alignment, size_t Size, const device & Dev, const context & Ctxt, alloc Kind, const property_list & PropList, const detail::code_location & CodeLoc)
Definition at line 538 of file usm_impl.cpp.
aligned_alloc() [3/8]
void* sycl::_V1::aligned_alloc (size_t alignment, size_t size, const device & dev, const context & ctxt, usm::alloc kind, const detail::code_location & CodeLoc = detail::code_location::current())
Referenced by sycl::_V1::detail::OSUtil::alignedAlloc(), and sycl::_V1::usm_allocator< T, AllocKind, Alignment >::allocate().
aligned_alloc() [4/8]
void* sycl::_V1::aligned_alloc (size_t alignment, size_t size, const device & dev, const context & ctxt, usm::alloc kind, const property_list & propList = {}, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 310 of file usm.hpp.
aligned_alloc() [5/8]
void* sycl::_V1::aligned_alloc (size_t Alignment, size_t Size, const queue & Q, alloc Kind, const detail::code_location & CodeLoc)
Definition at line 549 of file usm_impl.cpp.
aligned_alloc() [6/8]
void* sycl::_V1::aligned_alloc (size_t Alignment, size_t Size, const queue & Q, alloc Kind, const property_list & PropList, const detail::code_location & CodeLoc)
Definition at line 559 of file usm_impl.cpp.
aligned_alloc() [7/8]
void* sycl::_V1::aligned_alloc (size_t alignment, size_t size, const queue & q, usm::alloc kind, const detail::code_location & CodeLoc = detail::code_location::current())
aligned_alloc() [8/8]
void* sycl::_V1::aligned_alloc (size_t alignment, size_t size, const queue & q, usm::alloc kind, const property_list & propList = {}, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 323 of file usm.hpp.
aligned_alloc_device() [1/4]
void * sycl::_V1::aligned_alloc_device (size_t alignment, size_t size, const device & dev, const context & ctxt, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 345 of file usm_impl.cpp.
aligned_alloc_device() [2/4]
void * sycl::_V1::aligned_alloc_device (size_t alignment, size_t size, const device & dev, const context & ctxt, const property_list & propList = {}, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 185 of file usm.hpp.
aligned_alloc_device() [3/4]
void * sycl::_V1::aligned_alloc_device (size_t alignment, size_t size, const queue & q, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 359 of file usm_impl.cpp.
aligned_alloc_device() [4/4]
void * sycl::_V1::aligned_alloc_device (size_t alignment, size_t size, const queue & q, const property_list & propList = {}, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 198 of file usm.hpp.
aligned_alloc_host() [1/4]
void * sycl::_V1::aligned_alloc_host (size_t alignment, size_t size, const context & ctxt, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 433 of file usm_impl.cpp.
aligned_alloc_host() [2/4]
void * sycl::_V1::aligned_alloc_host (size_t alignment, size_t size, const context & ctxt, const property_list & propList = {}, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 242 of file usm.hpp.
aligned_alloc_host() [3/4]
void * sycl::_V1::aligned_alloc_host (size_t alignment, size_t size, const queue & q, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 446 of file usm_impl.cpp.
aligned_alloc_host() [4/4]
void * sycl::_V1::aligned_alloc_host (size_t alignment, size_t size, const queue & q, const property_list & propList = {}, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 255 of file usm.hpp.
aligned_alloc_shared() [1/4]
void * sycl::_V1::aligned_alloc_shared (size_t alignment, size_t size, const device & dev, const context & ctxt, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 459 of file usm_impl.cpp.
aligned_alloc_shared() [2/4]
void * sycl::_V1::aligned_alloc_shared (size_t alignment, size_t size, const device & dev, const context & ctxt, const property_list & propList = {}, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 267 of file usm.hpp.
aligned_alloc_shared() [3/4]
void * sycl::_V1::aligned_alloc_shared (size_t alignment, size_t size, const queue & q, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 473 of file usm_impl.cpp.
aligned_alloc_shared() [4/4]
void * sycl::_V1::aligned_alloc_shared (size_t alignment, size_t size, const queue & q, const property_list & propList = {}, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 280 of file usm.hpp.
all_of_group() [1/2]
template<typename Group > std::enable_if_t<is_group_v<std::decay_t<Group> >, bool> sycl::_V1::all_of_group (Group g, bool pred)
Definition at line 435 of file group_algorithm.hpp.
all_of_group() [2/2]
template<typename Group , typename T , class Predicate > std::enable_if_t<is_group_v<std::decay_t<Group> >, bool> sycl::_V1::all_of_group (Group g, T x, Predicate pred)
Definition at line 454 of file group_algorithm.hpp.
any_of_group() [1/2]
template<typename Group > std::enable_if_t<is_group_v<std::decay_t<Group> >, bool> sycl::_V1::any_of_group (Group g, bool pred)
Definition at line 389 of file group_algorithm.hpp.
any_of_group() [2/2]
template<typename Group , typename T , class Predicate > std::enable_if_t<is_group_v<Group>, bool> sycl::_V1::any_of_group (Group g, T x, Predicate pred)
Definition at line 407 of file group_algorithm.hpp.
as_bytes()
template<class _Tp , size_t _Extent> _SYCL_SPAN_INLINE_VISIBILITY auto sycl::_V1::as_bytes (span< _Tp, _Extent > __s) -> decltype(__s.__as_bytes()) noexcept
Definition at line 606 of file sycl_span.hpp.
as_writable_bytes()
template<class _Tp , size_t _Extent> _SYCL_SPAN_INLINE_VISIBILITY auto sycl::_V1::as_writable_bytes (span< _Tp, _Extent > __s) -> std::enable_if_t<!std::is_const_v<_Tp>, decltype(__s.__as_writable_bytes())> noexcept
Definition at line 613 of file sycl_span.hpp.
aspect_selector() [1/3]
template<aspect... AspectList> detail::DSelectorInvocableType sycl::_V1::aspect_selector ()
Definition at line 169 of file device_selector.hpp.
aspect_selector() [2/3]
template<typename... AspectListT> detail::DSelectorInvocableType sycl::_V1::aspect_selector (AspectListT... AspectList)
Definition at line 159 of file device_selector.hpp.
aspect_selector() [3/3]
detail::DSelectorInvocableType sycl::_V1::aspect_selector (const std::vector< aspect > & RequireList, const std::vector< aspect > & DenyList = {})
Definition at line 255 of file device_selector.cpp.
atomic_compare_exchange_strong()
template<typename T , access::address_space addressSpace> bool sycl::_V1::atomic_compare_exchange_strong (atomic< T, addressSpace > Object, T & Expected, T Desired, memory_order SuccessOrder = memory_order::relaxed, memory_order FailOrder = memory_order::relaxed)
Definition at line 354 of file atomic.hpp.
atomic_exchange()
template<typename T , access::address_space addressSpace> T sycl::_V1::atomic_exchange (atomic< T, addressSpace > Object, T Operand, memory_order MemoryOrder = memory_order::relaxed)
Definition at line 348 of file atomic.hpp.
atomic_fence()
void sycl::_V1::atomic_fence (memory_order order, memory_scope scope) inline
Definition at line 22 of file atomic_fence.hpp.
atomic_fetch_add()
template<typename T , access::address_space addressSpace> T sycl::_V1::atomic_fetch_add (atomic< T, addressSpace > Object, T Operand, memory_order MemoryOrder = memory_order::relaxed)
Definition at line 363 of file atomic.hpp.
atomic_fetch_and()
template<typename T , access::address_space addressSpace> T sycl::_V1::atomic_fetch_and (atomic< T, addressSpace > Object, T Operand, memory_order MemoryOrder = memory_order::relaxed)
Definition at line 375 of file atomic.hpp.
atomic_fetch_max()
template<typename T , access::address_space addressSpace> T sycl::_V1::atomic_fetch_max (atomic< T, addressSpace > Object, T Operand, memory_order MemoryOrder = memory_order::relaxed)
Definition at line 399 of file atomic.hpp.
atomic_fetch_min()
template<typename T , access::address_space addressSpace> T sycl::_V1::atomic_fetch_min (atomic< T, addressSpace > Object, T Operand, memory_order MemoryOrder = memory_order::relaxed)
Definition at line 393 of file atomic.hpp.
atomic_fetch_or()
template<typename T , access::address_space addressSpace> T sycl::_V1::atomic_fetch_or (atomic< T, addressSpace > Object, T Operand, memory_order MemoryOrder = memory_order::relaxed)
Definition at line 381 of file atomic.hpp.
atomic_fetch_sub()
template<typename T , access::address_space addressSpace> T sycl::_V1::atomic_fetch_sub (atomic< T, addressSpace > Object, T Operand, memory_order MemoryOrder = memory_order::relaxed)
Definition at line 369 of file atomic.hpp.
atomic_fetch_xor()
template<typename T , access::address_space addressSpace> T sycl::_V1::atomic_fetch_xor (atomic< T, addressSpace > Object, T Operand, memory_order MemoryOrder = memory_order::relaxed)
Definition at line 387 of file atomic.hpp.
atomic_load()
template<typename T , access::address_space addressSpace> T sycl::_V1::atomic_load (atomic< T, addressSpace > Object, memory_order MemoryOrder = memory_order::relaxed)
Definition at line 342 of file atomic.hpp.
atomic_store()
template<typename T , access::address_space addressSpace> void sycl::_V1::atomic_store (atomic< T, addressSpace > Object, T Operand, memory_order MemoryOrder = memory_order::relaxed)
Definition at line 336 of file atomic.hpp.
bit_cast()
template<typename To , typename From > std::enable_if_t<sizeof(To) == sizeof(From) && std::is_trivially_copyable<From>::value && std::is_trivially_copyable<To>::value, To> sycl::_V1::bit_cast (const From & from) noexcept
Definition at line 52 of file bit_cast.hpp.
build() [1/2]
kernel_bundle<bundle_state::executable> sycl::_V1::build (const kernel_bundle< bundle_state::input > & InputBundle, const property_list & PropList = {}) inline
Definition at line 810 of file kernel_bundle.hpp.
build() [2/2]
kernel_bundle<bundle_state::executable> sycl::_V1::build (const kernel_bundle< bundle_state::input > & InputBundle, const std::vector< device > & Devs, const property_list & PropList = {}) inline
Returns
a new kernel_bundle which contains device images that are translated into one ore more new device images of state bundle_state::executable. The new bundle represents all of the kernels in InputBundle that are compatible with at least one of the devices in Devs.
Definition at line 799 of file kernel_bundle.hpp.
Referenced by sycl::_V1::detail::ProgramManager::bringSYCLDeviceImagesToState(), and sycl::_V1::detail::ProgramManager::build().
BUILTIN_COMMON() [1/4]
sycl::_V1::BUILTIN_COMMON (ONE_ARG , degrees , [] (auto x) -> decltype(x) { return(180/M_PI) *x;})
BUILTIN_COMMON() [2/4]
sycl::_V1::BUILTIN_COMMON (ONE_ARG , sign , [] (auto x) -> decltype(x) { using T=decltype(x);if(std::isnan(x)) return T(0.0);if(x > 0) return T(1.0);if(x< 0) return T(-1.0);return x;})
BUILTIN_COMMON() [3/4]
sycl::_V1::BUILTIN_COMMON (TWO_ARGS , max , [] (auto x, auto y) -> decltype(x) { return(x< y ? y :x);})
BUILTIN_COMMON() [4/4]
sycl::_V1::BUILTIN_COMMON (TWO_ARGS , step , [] (auto x, auto y) -> decltype(x) { return y< x ? 0.0 :1.0;})
BUILTIN_GENF_CUSTOM() [1/7]
sycl::_V1::BUILTIN_GENF_CUSTOM (ONE_ARG , acospi , [] (auto x) -> decltype(x) { return std::acos(x)/M_PI;})
BUILTIN_GENF_CUSTOM() [2/7]
sycl::_V1::BUILTIN_GENF_CUSTOM (ONE_ARG , atanpi , [] (auto x) -> decltype(x) { return std::atan(x)/M_PI;})
BUILTIN_GENF_CUSTOM() [3/7]
sycl::_V1::BUILTIN_GENF_CUSTOM (ONE_ARG , cospi , [] (auto x) -> decltype(x) { return std::sin(M_PI *(0.5 - x));})
BUILTIN_GENF_CUSTOM() [4/7]
return (x >= T(0)) ? T(std sycl::_V1::BUILTIN_GENF_CUSTOM (ONE_ARG , rsqrt , [] (auto x) -> decltype(x) { return decltype(x){1.0}/std::sqrt(x);})
BUILTIN_GENF_CUSTOM() [5/7]
sycl::_V1::BUILTIN_GENF_CUSTOM (ONE_ARG , tanpi , [] (auto x) -> decltype(x) { double y=x - std::floor(x);return 1.0/std::tan((0.5 - y) *M_PI);})
BUILTIN_GENF_CUSTOM() [6/7]
sycl::_V1::BUILTIN_GENF_CUSTOM (THREE_ARGS , mad , [] (auto x, auto y, auto z) -> decltype(x) { return(x *y)+z;})
BUILTIN_GENF_CUSTOM() [7/7]
sycl::_V1::BUILTIN_GENF_CUSTOM (TWO_ARGS , minmag , [] (auto x, auto y) -> decltype(x) { if(std::fabs(x)< std::fabs(y)) return x;if(std::fabs(y)< std::fabs(x)) return y;return std::fmin(x, y);})
BUILTIN_GENINT() [1/2]
sycl::_V1::BUILTIN_GENINT (ONE_ARG , abs , [] (auto x) -> decltype(x) { if constexpr(std::is_signed_v< decltype(x)>) { return std::abs(x);} else { return x;} })
BUILTIN_GENINT() [2/2]
sycl::_V1::BUILTIN_GENINT (TWO_ARGS , rotate , [] (auto x, auto n) -> decltype(x) { using T=decltype(x);using UT=std::make_unsigned_t< T >;constexpr UT size=sizeof(x) *8;UT xu=UT(x);UT nu=UT(n) &(size - 1);return(xu<< nu)|(xu >>(size - nu));}) const
BUILTIN_GENINT_SU() [1/5]
sycl::_V1::BUILTIN_GENINT_SU (THREE_ARGS , mad_sat , [] (auto a, auto b, auto c) -> decltype(a) { using T=decltype(a);if constexpr(std::is_signed_v< T >) { if constexpr(sizeof(T)==8) { bool neg_prod=(a< 0) ^(b< 0);T mulhi=__s_long_mul_hi(a, b);if(!neg_prod &&mulhi !=0) return std::numeric_limits< T >::max();if(neg_prod &&mulhi !=-1) return std::numeric_limits< T >::min();return sycl::add_sat(T(a *b), c);} else { using UPT=sycl::detail::make_larger_t< T >;UPT mul=UPT(a) *UPT(b);UPT res=mul+UPT(c);const UPT max=std::numeric_limits< T >::max();const UPT min=std::numeric_limits< T >::min();res=std::min(std::max(res, min), max);return T(res);} } else { if constexpr(sizeof(T)==8) { T mulhi=__u_long_mul_hi(a, b);if(mulhi !=0) return std::numeric_limits< T >::max();return sycl::add_sat(T(a *b), c);} else { using UPT=sycl::detail::make_larger_t< T >;UPT mul=UPT(a) *UPT(b);const UPT min=std::numeric_limits< T >::min();const UPT max=std::numeric_limits< T >::max();mul=std::min(std::max(mul, min), max);return sycl::add_sat(T(mul), c);} } })
BUILTIN_GENINT_SU() [2/5]
return std::max (x, y) - std sycl::_V1::BUILTIN_GENINT_SU (TWO_ARGS , add_sat , [] (auto x, auto y) -> decltype(x) { using T=decltype(x);if constexpr(std::is_signed_v< T >) { if(x > 0 &&y > 0) return(x<(std::numeric_limits< T >::max() - y) ?(x+y) :std::numeric_limits< T >::max());if(x< 0 &&y< 0) return(x >(std::numeric_limits< T >::min() - y) ?(x+y) :std::numeric_limits< T >::min());return x+y;} else { return(x<(std::numeric_limits< T >::max() - y) ? x+y :std::numeric_limits< T >::max());} })
BUILTIN_GENINT_SU() [3/5]
sycl::_V1::BUILTIN_GENINT_SU (TWO_ARGS , min , [] (auto x, auto y) -> decltype(x) { return y< x ? y :x;})
BUILTIN_GENINT_SU() [4/5]
sycl::_V1::BUILTIN_GENINT_SU (TWO_ARGS , rhadd , [] (auto x, auto y) -> decltype(x) { const decltype(x) one=1;return(x >> one)+(y >> one)+((y|x) &one);})
BUILTIN_GENINT_SU() [5/5]
sycl::_V1::BUILTIN_GENINT_SU (TWO_ARGS , sub_sat , [] (auto x, auto y) -> decltype(x) { using T=decltype(x);if constexpr(std::is_signed_v< T >) { using UT=std::make_unsigned_t< T >;T result=UT(x) - UT(y);if(((x< 0) ^(y< 0)) &&((x< 0) ^(result< 0))) result=result< 0 ? std::numeric_limits< T >::max() :std::numeric_limits< T >::min();return result;} else { return(y<(x - std::numeric_limits< T >::min())) ?(x - y) :std::numeric_limits< T >::min();} })
ceil() [1/2]
double sycl::_V1::ceil (double) inline
ceil() [2/2]
float sycl::_V1::ceil (float) inline
checkContextSupports()
static bool sycl::_V1::checkContextSupports (const std::shared_ptr< detail::context_impl > & ContextImpl, sycl::detail::pi::PiContextInfo InfoQuery) static
Definition at line 1468 of file handler.cpp.
CheckMaxStatementSize()
static size_t sycl::_V1::CheckMaxStatementSize (const size_t & MaxStatementSize) static
Definition at line 27 of file stream.cpp.
compile() [1/2]
kernel_bundle<bundle_state::object> sycl::_V1::compile (const kernel_bundle< bundle_state::input > & InputBundle, const property_list & PropList = {}) inline
Definition at line 728 of file kernel_bundle.hpp.
compile() [2/2]
kernel_bundle<bundle_state::object> sycl::_V1::compile (const kernel_bundle< bundle_state::input > & InputBundle, const std::vector< device > & Devs, const property_list & PropList = {}) inline
Returns
a new kernel_bundle which contains the device images from InputBundle that are translated into one or more new device images of state bundle_state::object. The new bundle represents all of the kernels in InputBundles that are compatible with at least one of the devices in Devs.
Definition at line 717 of file kernel_bundle.hpp.
Referenced by sycl::_V1::detail::ProgramManager::bringSYCLDeviceImagesToState(), and sycl::_V1::detail::kernel_bundle_impl::kernel_bundle_impl().
cos()
template<int SZ> ESIMD_NODEBUG ESIMD_INLINE sycl::ext::intel::esimd::simd<float, SZ> sycl::_V1::cos (sycl::ext::intel::esimd::simd< float, SZ > x)
Definition at line 26 of file builtins_esimd.hpp.
cpu_selector_v()
int sycl::_V1::cpu_selector_v (const device & dev)
Definition at line 224 of file device_selector.cpp.
Referenced by sycl::_V1::detail::select_device().
cross_host_impl()
template<typename T > static T sycl::_V1::cross_host_impl (T p0, T p1) inline static
Definition at line 17 of file geometric_functions.cpp.
device::create_sub_devices< info::partition_property::ext_intel_partition_by_cslice >()
template std::vector<device> sycl::_V1::device::create_sub_devices< info::partition_property::ext_intel_partition_by_cslice > () const
device::create_sub_devices< info::partition_property::partition_by_affinity_domain >()
template std::vector<device> sycl::_V1::device::create_sub_devices< info::partition_property::partition_by_affinity_domain > (info::partition_affinity_domain AffinityDomain) const
device::create_sub_devices< info::partition_property::partition_by_counts >()
template std::vector<device> sycl::_V1::device::create_sub_devices< info::partition_property::partition_by_counts > (const std::vector< size_t > & Counts) const
device::create_sub_devices< info::partition_property::partition_equally >()
template std::vector<device> sycl::_V1::device::create_sub_devices< info::partition_property::partition_equally > (size_t ComputeUnits) const
device::get_info_impl< info::device::aspects >()
template<> std::vector<sycl::aspect> sycl::_V1::device::get_info_impl< info::device::aspects > () const
Definition at line 136 of file device.cpp.
device::get_info_impl< info::device::image_support >()
template<> bool sycl::_V1::device::get_info_impl< info::device::image_support > () const
Definition at line 176 of file device.cpp.
device::get_info_impl< info::device::parent_device >()
template<> device sycl::_V1::device::get_info_impl< info::device::parent_device > () const
Definition at line 136 of file device.cpp.
distance_host_impl()
template<typename T0 , typename T1 > static auto sycl::_V1::distance_host_impl (T0 x, T1 y) inline static
Definition at line 62 of file geometric_functions.cpp.
dot_host_impl()
template<typename T0 , typename T1 > static auto sycl::_V1::dot_host_impl (T0 x, T1 y) inline static
Definition at line 27 of file geometric_functions.cpp.
exclusive_scan_over_group() [1/5]
template<typename Group , typename T , class BinaryOperation > std::enable_if_t<(is_group_v<std::decay_t<Group>> && (detail::is_scalar_arithmetic<T>::value || (detail::is_complex<T>::value && detail::is_multiplies<T, BinaryOperation>::value)) && detail::is_native_op<T, BinaryOperation>::value), T> sycl::_V1::exclusive_scan_over_group (Group g, T x, BinaryOperation binary_op)
Definition at line 682 of file group_algorithm.hpp.
exclusive_scan_over_group() [2/5]
template<typename Group , typename T , class BinaryOperation > std::enable_if_t<(is_group_v<std::decay_t<Group>> && detail::is_vector_arithmetic_or_complex<T>::value && detail::is_native_op<T, BinaryOperation>::value), T> sycl::_V1::exclusive_scan_over_group (Group g, T x, BinaryOperation binary_op)
Definition at line 755 of file group_algorithm.hpp.
exclusive_scan_over_group() [3/5]
template<typename Group , typename T , class BinaryOperation > std::enable_if_t<(is_group_v<std::decay_t<Group>> && detail::is_complex<T>::value && detail::is_native_op<T, sycl::plus<T>>::value && detail::is_plus<T, BinaryOperation>::value), T> sycl::_V1::exclusive_scan_over_group (Group g, T x, BinaryOperation)
Definition at line 736 of file group_algorithm.hpp.
exclusive_scan_over_group() [4/5]
template<typename Group , typename V , typename T , class BinaryOperation > std::enable_if_t<(is_group_v<std::decay_t<Group>> && detail::is_vector_arithmetic_or_complex<V>::value && detail::is_vector_arithmetic_or_complex<T>::value && detail::is_native_op<V, BinaryOperation>::value && detail::is_native_op<T, BinaryOperation>::value), T> sycl::_V1::exclusive_scan_over_group (Group g, V x, T init, BinaryOperation binary_op)
Definition at line 776 of file group_algorithm.hpp.
exclusive_scan_over_group() [5/5]
template<typename Group , typename V , typename T , class BinaryOperation > std::enable_if_t< (is_group_v<std::decay_t<Group>> && (detail::is_scalar_arithmetic<V>::value || detail::is_complex<V>::value) && (detail::is_scalar_arithmetic<T>::value || detail::is_complex<T>::value) && detail::is_native_op<T, BinaryOperation>::value && detail::is_plus_or_multiplies_if_complex<T, BinaryOperation>::value && std::is_convertible_v<V, T>), T> sycl::_V1::exclusive_scan_over_group (Group g, V x, T init, BinaryOperation binary_op)
Definition at line 797 of file group_algorithm.hpp.
exp()
template<int SZ> ESIMD_NODEBUG ESIMD_INLINE sycl::ext::intel::esimd::simd<float, SZ> sycl::_V1::exp (sycl::ext::intel::esimd::simd< float, SZ > x)
Definition at line 48 of file builtins_esimd.hpp.
fast_distance_host_impl()
template<typename T0 , typename T1 > static auto sycl::_V1::fast_distance_host_impl (T0 x, T1 y) inline static
Definition at line 68 of file geometric_functions.cpp.
fast_length_host_impl()
template<typename T > static auto sycl::_V1::fast_length_host_impl (T x) inline static
Definition at line 56 of file geometric_functions.cpp.
fast_normalize_host_impl()
template<typename T > static auto sycl::_V1::fast_normalize_host_impl (T x) inline static
Definition at line 81 of file geometric_functions.cpp.
floor() [1/2]
double sycl::_V1::floor (double) inline
floor() [2/2]
float sycl::_V1::floor (float) inline
free() [1/2]
void sycl::_V1::free (void * ptr, const context & ctxt, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 374 of file usm_impl.cpp.
Referenced by sycl::_V1::detail::OSUtil::alignedFree(), sycl::_V1::usm_allocator< T, AllocKind, Alignment >::deallocate(), and sycl::_V1::detail::reduction_impl_algo< T, BinaryOperation, Dims, Extent, ExplicitIdentity, RedOutVar >::getGroupsCounterAccDiscrete().
free() [2/2]
void sycl::_V1::free (void * ptr, const queue & q, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 379 of file usm_impl.cpp.
get()
pointer_t sycl::_V1::get () const
Definition at line 544 of file multi_ptr.hpp.
Referenced by sycl::_V1::detail::usm::alignedAlloc(), sycl::_V1::detail::usm::free(), sycl::_V1::ext::intel::experimental::fpga_datapath< T >::operator const T &(), sycl::_V1::ext::intel::experimental::fpga_mem< T, ext::oneapi::experimental::detail::properties_t< Props... > >::operator const T &(), sycl::_V1::ext::intel::experimental::fpga_datapath< T >::operator T&(), sycl::_V1::ext::intel::experimental::fpga_mem< T, ext::oneapi::experimental::detail::properties_t< Props... > >::operator T&(), sycl::_V1::ext::oneapi::sub_group_mask::operator[](), and sycl::_V1::ext::intel::experimental::task_sequence< f, oneapi::experimental::detail::properties_t< Props... > >::~task_sequence().
get_kernel_bundle() [1/8]
template<bundle_state State> kernel_bundle<State> sycl::_V1::get_kernel_bundle (const context & Ctx)
Definition at line 500 of file kernel_bundle.hpp.
get_kernel_bundle() [2/8]
template<typename KernelName , bundle_state State> kernel_bundle<State> sycl::_V1::get_kernel_bundle (const context & Ctx)
Definition at line 540 of file kernel_bundle.hpp.
get_kernel_bundle() [3/8]
template<bundle_state State> kernel_bundle<State> sycl::_V1::get_kernel_bundle (const context & Ctx, const std::vector< device > & Devs)
A kernel bundle in state State which contains all of the kernels in the application which are compatible with at least one of the devices in Devs.
This does not include any device built-in kernels. The bundles set of associated devices is Devs.
Definition at line 489 of file kernel_bundle.hpp.
get_kernel_bundle() [4/8]
template<typename KernelName , bundle_state State> kernel_bundle<State> sycl::_V1::get_kernel_bundle (const context & Ctx, const std::vector< device > & Devs)
Definition at line 546 of file kernel_bundle.hpp.
get_kernel_bundle() [5/8]
template<bundle_state State> kernel_bundle<State> sycl::_V1::get_kernel_bundle (const context & Ctx, const std::vector< device > & Devs, const std::vector< kernel_id > & KernelIDs)
Returns
a kernel bundle in state State which contains all of the device images that are compatible with at least one of the devices in Devs, further filtered to contain only those device images that contain kernels with the given identifiers. These identifiers may represent kernels that are defined in the application, device built-in kernels, or a mixture of the two. Since the device images may group many kernels together, the returned bundle may contain additional kernels beyond those that are requested in KernelIDs. The bundles set of associated devices is Devs.
Definition at line 524 of file kernel_bundle.hpp.
get_kernel_bundle() [6/8]
template<bundle_state State, typename SelectorT > kernel_bundle<State> sycl::_V1::get_kernel_bundle (const context & Ctx, const std::vector< device > & Devs, SelectorT Selector)
A kernel bundle in state State which contains all of the device images for which the selector returns true.
Definition at line 582 of file kernel_bundle.hpp.
get_kernel_bundle() [7/8]
template<bundle_state State> kernel_bundle<State> sycl::_V1::get_kernel_bundle (const context & Ctx, const std::vector< kernel_id > & KernelIDs)
Definition at line 535 of file kernel_bundle.hpp.
get_kernel_bundle() [8/8]
template<bundle_state State, typename SelectorT > kernel_bundle<State> sycl::_V1::get_kernel_bundle (const context & Ctx, SelectorT Selector)
Definition at line 600 of file kernel_bundle.hpp.
get_kernel_id()
template<typename KernelName > kernel_id sycl::_V1::get_kernel_id ()
Returns
the kernel_id associated with the KernelName
Definition at line 457 of file kernel_bundle.hpp.
get_kernel_ids()
std::vector< kernel_id > sycl::_V1::get_kernel_ids ()
Returns
a vector with all kernel_id's defined in the application
Definition at line 301 of file kernel_bundle.cpp.
get_native() [1/6]
template<backend BackendName, typename DataT , int Dimensions, access::mode AccessMode, access::target AccessTarget, access::placeholder IsPlaceholder> auto sycl::_V1::get_native (const accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder > & Obj) -> typename detail::interop< BackendName, accessor< DataT, Dimensions, AccessMode, AccessTarget, IsPlaceholder >>::type=delete delete
get_native() [2/6]
template<backend BackendName, typename DataT , int Dimensions, typename AllocatorT > auto sycl::_V1::get_native (const buffer< DataT, Dimensions, AllocatorT > & Obj) -> backend_return_t<BackendName, buffer<DataT, Dimensions, AllocatorT>>
Definition at line 179 of file backend.hpp.
get_native() [3/6]
template<backend BackendName, bundle_state State> auto sycl::_V1::get_native (const kernel_bundle< State > & Obj) -> backend_return_t< BackendName, kernel_bundle< State >>
Definition at line 168 of file backend.hpp.
get_native() [4/6]
template<backend BackendName> auto sycl::_V1::get_native (const queue & Obj) -> backend_return_t<BackendName, queue>
Definition at line 147 of file backend.hpp.
get_native() [5/6]
template<backend BackendName, class SyclObjectT > auto sycl::_V1::get_native (const SyclObjectT & Obj) -> backend_return_t< BackendName, SyclObjectT >
Definition at line 136 of file backend.hpp.
get_native() [6/6]
template<backend Backend, class SyclT > auto sycl::_V1::get_native (const SyclT & Obj) -> backend_return_t< Backend, SyclT >
get_native< backend::ext_oneapi_cuda, context >()
template<> auto sycl::_V1::get_native< backend::ext_oneapi_cuda, context > (const context & C) -> backend_return_t<backend::ext_oneapi_cuda, context> inline
Definition at line 38 of file cuda.hpp.
get_native< backend::ext_oneapi_hip, device >()
template<> backend_return_t<backend::ext_oneapi_hip, device> sycl::_V1::get_native< backend::ext_oneapi_hip, device > (const device & Obj) inline
Definition at line 1 of file hip.hpp.
get_native< backend::ext_oneapi_level_zero, queue >()
template<> auto sycl::_V1::get_native< backend::ext_oneapi_level_zero, queue > (const queue & Obj) -> backend_return_t<backend::ext_oneapi_level_zero, queue> inline
Definition at line 152 of file level_zero.hpp.
get_pointer_device()
device sycl::_V1::get_pointer_device (const void * Ptr, const context & Ctxt)
Queries the device against which the pointer was allocated Throws an invalid_object_error if ptr is a host allocation.
Queries the device against which the pointer was allocated.
Parameters
ptr is the USM pointer to query
ctxt is the sycl context the ptr was allocated in
Ptr is the USM pointer to query
Ctxt is the sycl context the ptr was allocated in
Definition at line 626 of file usm_impl.cpp.
get_pointer_type()
alloc sycl::_V1::get_pointer_type (const void * Ptr, const context & Ctxt)
Query the allocation type from a USM pointer.
Query the allocation type from a USM pointer Returns alloc::host for all pointers in a host context.
Parameters
ptr is the USM pointer to query
ctxt is the sycl context the ptr was allocated in
Ptr is the USM pointer to query
Ctxt is the sycl context the ptr was allocated in
Definition at line 575 of file usm_impl.cpp.
Referenced by sycl::_V1::handler::ext_oneapi_copy(), sycl::_V1::handler::ext_oneapi_copy2d(), sycl::_V1::handler::ext_oneapi_fill2d(), sycl::_V1::handler::ext_oneapi_memcpy2d(), and sycl::_V1::handler::ext_oneapi_memset2d().
getBarrierEventForInorderQueueHelper()
static event sycl::_V1::getBarrierEventForInorderQueueHelper (const detail::QueueImplPtr QueueImpl) static
Definition at line 209 of file queue.cpp.
Referenced by sycl::_V1::queue::ext_oneapi_submit_barrier().
gpu_selector_v()
int sycl::_V1::gpu_selector_v (const device & dev)
Definition at line 209 of file device_selector.cpp.
Referenced by sycl::_V1::detail::select_device().
group_barrier() [1/2]
template<int dimensions> void sycl::_V1::group_barrier (ext::oneapi::experimental::root_group< dimensions > G, memory_scope FenceScope = decltype(G)::fence_scope)
Definition at line 102 of file root_group.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::joint_reduce(), and sycl::_V1::ext::oneapi::experimental::detail::reduce_over_group_impl().
group_barrier() [2/2]
template<typename Group > std::enable_if_t<is_group_v<Group> > sycl::_V1::group_barrier (Group G, memory_scope FenceScope = Group::fence_scope)
Definition at line 24 of file group_barrier.hpp.
group_broadcast() [1/3]
template<typename Group , typename T > std::enable_if_t<(is_group_v<std::decay_t<Group>> && (std::is_trivially_copyable_v<T> || detail::is_vec<T>::value)), T> sycl::_V1::group_broadcast (Group g, T x)
Definition at line 660 of file group_algorithm.hpp.
group_broadcast() [2/3]
template<typename Group , typename T > std::enable_if_t<(is_group_v<std::decay_t<Group>> && (std::is_trivially_copyable_v<T> || detail::is_vec<T>::value)), T> sycl::_V1::group_broadcast (Group g, T x, typename Group::id_type local_id)
Definition at line 617 of file group_algorithm.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::detail::reduce_over_group_impl().
group_broadcast() [3/3]
template<typename Group , typename T > std::enable_if_t<(is_group_v<std::decay_t<Group>> && (std::is_trivially_copyable_v<T> || detail::is_vec<T>::value)), T> sycl::_V1::group_broadcast (Group g, T x, typename Group::linear_id_type linear_local_id)
Definition at line 641 of file group_algorithm.hpp.
has_kernel_bundle() [1/6]
template<bundle_state State> bool sycl::_V1::has_kernel_bundle (const context & Ctx)
Definition at line 641 of file kernel_bundle.hpp.
has_kernel_bundle() [2/6]
template<typename KernelName , bundle_state State> bool sycl::_V1::has_kernel_bundle (const context & Ctx)
Definition at line 652 of file kernel_bundle.hpp.
has_kernel_bundle() [3/6]
template<bundle_state State> bool sycl::_V1::has_kernel_bundle (const context & Ctx, const std::vector< device > & Devs)
Returns
true if the following is true: The application defines at least one kernel that is compatible with at least one of the devices in Devs, and that kernel can be represented in a device image of state State.
If State is bundle_state::input, all devices in Devs have aspect::online_compiler.
If State is bundle_state::object, all devices in Devs have aspect::online_linker.
Definition at line 631 of file kernel_bundle.hpp.
has_kernel_bundle() [4/6]
template<typename KernelName , bundle_state State> bool sycl::_V1::has_kernel_bundle (const context & Ctx, const std::vector< device > & Devs)
Definition at line 657 of file kernel_bundle.hpp.
has_kernel_bundle() [5/6]
template<bundle_state State> bool sycl::_V1::has_kernel_bundle (const context & Ctx, const std::vector< device > & Devs, const std::vector< kernel_id > & KernelIDs)
Definition at line 636 of file kernel_bundle.hpp.
has_kernel_bundle() [6/6]
template<bundle_state State> bool sycl::_V1::has_kernel_bundle (const context & Ctx, const std::vector< kernel_id > & KernelIDs)
Definition at line 646 of file kernel_bundle.hpp.
host_accessor() [1/6]
template<typename DataT , int Dimensions, typename AllocatorT > sycl::_V1::host_accessor (buffer< DataT, Dimensions, AllocatorT >) -> host_accessor< DataT, Dimensions, access::mode::read_write >
host_accessor() [2/6]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 > sycl::_V1::host_accessor (buffer< DataT, Dimensions, AllocatorT > , Type1) -> host_accessor< DataT, Dimensions, detail::deduceAccessMode< Type1, Type1 >()>
host_accessor() [3/6]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 > sycl::_V1::host_accessor (buffer< DataT, Dimensions, AllocatorT > , Type1 , Type2) -> host_accessor< DataT, Dimensions, detail::deduceAccessMode< Type1, Type2 >()>
host_accessor() [4/6]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 > sycl::_V1::host_accessor (buffer< DataT, Dimensions, AllocatorT > , Type1 , Type2 , Type3) -> host_accessor< DataT, Dimensions, detail::deduceAccessMode< Type2, Type3 >()>
host_accessor() [5/6]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 , typename Type4 > sycl::_V1::host_accessor (buffer< DataT, Dimensions, AllocatorT > , Type1 , Type2 , Type3 , Type4) -> host_accessor< DataT, Dimensions, detail::deduceAccessMode< Type3, Type4 >()>
host_accessor() [6/6]
template<typename DataT , int Dimensions, typename AllocatorT , typename Type1 , typename Type2 , typename Type3 , typename Type4 , typename Type5 > sycl::_V1::host_accessor (buffer< DataT, Dimensions, AllocatorT > , Type1 , Type2 , Type3 , Type4 , Type5) -> host_accessor< DataT, Dimensions, detail::deduceAccessMode< Type4, Type5 >()>
if() [1/2]
constexpr sycl::_V1::if (sizeof(T) = = 8) constexpr
Definition at line 181 of file integer_functions.cpp.
Referenced by sycl::_V1::detail::HostKernel< KernelType, KernelArgType, Dims >::call(), and sycl::_V1::detail::Scheduler::GraphBuilder::completeFusion().
if() [2/2]
sycl::_V1::if (std::fabs(y) , std::fabs(x))
inclusive_scan_over_group() [1/5]
template<typename Group , typename T , class BinaryOperation > std::enable_if_t<(is_group_v<std::decay_t<Group>> && detail::is_vector_arithmetic_or_complex<T>::value && detail::is_native_op<T, BinaryOperation>::value), T> sycl::_V1::inclusive_scan_over_group (Group g, T x, BinaryOperation binary_op)
Definition at line 904 of file group_algorithm.hpp.
inclusive_scan_over_group() [2/5]
template<typename Group , typename T , class BinaryOperation > std::enable_if_t<(is_group_v<std::decay_t<Group>> && (detail::is_scalar_arithmetic<T>::value || (detail::is_complex<T>::value && detail::is_multiplies<T, BinaryOperation>::value)) && detail::is_native_op<T, BinaryOperation>::value), T> sycl::_V1::inclusive_scan_over_group (Group g, T x, BinaryOperation binary_op)
Definition at line 923 of file group_algorithm.hpp.
inclusive_scan_over_group() [3/5]
template<typename Group , typename T , class BinaryOperation > std::enable_if_t<(is_group_v<std::decay_t<Group>> && detail::is_complex<T>::value && detail::is_native_op<T, sycl::plus<T>>::value && detail::is_plus<T, BinaryOperation>::value), T> sycl::_V1::inclusive_scan_over_group (Group g, T x, BinaryOperation)
Definition at line 950 of file group_algorithm.hpp.
inclusive_scan_over_group() [4/5]
template<typename Group , typename V , class BinaryOperation , typename T > std::enable_if_t< (is_group_v<std::decay_t<Group>> && (detail::is_scalar_arithmetic<V>::value || detail::is_complex<V>::value) && (detail::is_scalar_arithmetic<T>::value || detail::is_complex<T>::value) && detail::is_native_op<T, BinaryOperation>::value && detail::is_plus_or_multiplies_if_complex<T, BinaryOperation>::value && std::is_convertible_v<V, T>), T> sycl::_V1::inclusive_scan_over_group (Group g, V x, BinaryOperation binary_op, T init)
Definition at line 975 of file group_algorithm.hpp.
inclusive_scan_over_group() [5/5]
template<typename Group , typename V , class BinaryOperation , typename T > std::enable_if_t<(is_group_v<std::decay_t<Group>> && detail::is_vector_arithmetic_or_complex<V>::value && detail::is_vector_arithmetic_or_complex<T>::value && detail::is_native_op<V, BinaryOperation>::value && detail::is_native_op<T, BinaryOperation>::value), T> sycl::_V1::inclusive_scan_over_group (Group g, V x, BinaryOperation binary_op, T init)
Definition at line 998 of file group_algorithm.hpp.
interop_handle::get_native_context< backend::ext_oneapi_cuda >()
template<> backend_return_t<backend::ext_oneapi_cuda, context> sycl::_V1::interop_handle::get_native_context< backend::ext_oneapi_cuda > () const inline
Definition at line 38 of file cuda.hpp.
is_compatible() [1/2]
template<typename KernelName > bool sycl::_V1::is_compatible (const device & Dev)
Definition at line 670 of file kernel_bundle.hpp.
is_compatible() [2/2]
bool sycl::_V1::is_compatible (const std::vector< kernel_id > & KernelIDs, const device & Dev)
Returns
true if all of the kernels identified by KernelIDs are compatible with the device Dev.
Definition at line 305 of file kernel_bundle.cpp.
is_not_power_of_two()
size_t sycl::_V1::is_not_power_of_two (size_t Alignment) inline
Definition at line 160 of file usm.hpp.
join()
template<sycl::bundle_state State> sycl::kernel_bundle<State> sycl::_V1::join (const std::vector< sycl::kernel_bundle< State >> & Bundles)
Returns
a new kernel bundle that represents the union of all the device images in the input bundles with duplicates removed.
Definition at line 689 of file kernel_bundle.hpp.
joint_all_of()
template<typename Group , typename Ptr , class Predicate > std::enable_if_t<(is_group_v<std::decay_t<Group>> && detail::is_pointer_v<Ptr>), bool> sycl::_V1::joint_all_of (Group g, Ptr first, Ptr last, Predicate pred)
Definition at line 462 of file group_algorithm.hpp.
joint_any_of()
template<typename Group , typename Ptr , class Predicate > std::enable_if_t<(is_group_v<std::decay_t<Group>> && detail::is_pointer_v<Ptr>), bool> sycl::_V1::joint_any_of (Group g, Ptr first, Ptr last, Predicate pred)
Definition at line 416 of file group_algorithm.hpp.
joint_exclusive_scan() [1/2]
template<typename Group , typename InPtr , typename OutPtr , class BinaryOperation > std::enable_if_t< (is_group_v<std::decay_t<Group>> && detail::is_pointer_v<InPtr> && detail::is_pointer_v<OutPtr> && detail::is_arithmetic_or_complex< typename detail::remove_pointer<InPtr>::type>::value && detail::is_arithmetic_or_complex< typename detail::remove_pointer<OutPtr>::type>::value && detail::is_native_op<typename detail::remove_pointer<OutPtr>::type, BinaryOperation>::value && detail::is_plus_or_multiplies_if_complex< typename detail::remove_pointer<OutPtr>::type, BinaryOperation>::value), OutPtr> sycl::_V1::joint_exclusive_scan (Group g, InPtr first, InPtr last, OutPtr result, BinaryOperation binary_op)
Definition at line 885 of file group_algorithm.hpp.
joint_exclusive_scan() [2/2]
template<typename Group , typename InPtr , typename OutPtr , typename T , class BinaryOperation > std::enable_if_t< (is_group_v<std::decay_t<Group>> && detail::is_pointer_v<InPtr> && detail::is_pointer_v<OutPtr> && detail::is_arithmetic_or_complex< typename detail::remove_pointer<InPtr>::type>::value && detail::is_arithmetic_or_complex< typename detail::remove_pointer<OutPtr>::type>::value && detail::is_arithmetic_or_complex<T>::value && detail::is_native_op<T, BinaryOperation>::value && detail::is_plus_or_multiplies_if_complex<T, BinaryOperation>::value), OutPtr> sycl::_V1::joint_exclusive_scan (Group g, InPtr first, InPtr last, OutPtr result, T init, BinaryOperation binary_op)
Definition at line 833 of file group_algorithm.hpp.
joint_inclusive_scan() [1/2]
template<typename Group , typename InPtr , typename OutPtr , class BinaryOperation > std::enable_if_t< (is_group_v<std::decay_t<Group>> && detail::is_pointer_v<InPtr> && detail::is_pointer_v<OutPtr> && detail::is_arithmetic_or_complex< typename detail::remove_pointer<InPtr>::type>::value && detail::is_native_op<typename detail::remove_pointer<OutPtr>::type, BinaryOperation>::value && detail::is_plus_or_multiplies_if_complex< typename detail::remove_pointer<OutPtr>::type, BinaryOperation>::value), OutPtr> sycl::_V1::joint_inclusive_scan (Group g, InPtr first, InPtr last, OutPtr result, BinaryOperation binary_op)
Definition at line 1073 of file group_algorithm.hpp.
joint_inclusive_scan() [2/2]
template<typename Group , typename InPtr , typename OutPtr , class BinaryOperation , typename T > std::enable_if_t< (is_group_v<std::decay_t<Group>> && detail::is_pointer_v<InPtr> && detail::is_pointer_v<OutPtr> && detail::is_arithmetic_or_complex< typename detail::remove_pointer<InPtr>::type>::value && detail::is_arithmetic_or_complex< typename detail::remove_pointer<OutPtr>::type>::value && detail::is_arithmetic_or_complex<T>::value && detail::is_native_op<T, BinaryOperation>::value && detail::is_plus_or_multiplies_if_complex<T, BinaryOperation>::value), OutPtr> sycl::_V1::joint_inclusive_scan (Group g, InPtr first, InPtr last, OutPtr result, BinaryOperation binary_op, T init)
Definition at line 1024 of file group_algorithm.hpp.
joint_none_of()
template<typename Group , typename Ptr , class Predicate > std::enable_if_t<(is_group_v<std::decay_t<Group>> && detail::is_pointer_v<Ptr>), bool> sycl::_V1::joint_none_of (Group g, Ptr first, Ptr last, Predicate pred)
Definition at line 508 of file group_algorithm.hpp.
joint_reduce() [1/2]
template<typename Group , typename Ptr , class BinaryOperation > std::enable_if_t< (is_group_v<std::decay_t<Group>> && detail::is_pointer_v<Ptr> && detail::is_arithmetic_or_complex< typename detail::remove_pointer<Ptr>::type>::value && detail::is_plus_or_multiplies_if_complex< typename detail::remove_pointer<Ptr>::type, BinaryOperation>::value), typename detail::remove_pointer<Ptr>::type> sycl::_V1::joint_reduce (Group g, Ptr first, Ptr last, BinaryOperation binary_op)
Definition at line 371 of file group_algorithm.hpp.
joint_reduce() [2/2]
template<typename Group , typename Ptr , typename T , class BinaryOperation > std::enable_if_t< (is_group_v<std::decay_t<Group>> && detail::is_pointer_v<Ptr> && detail::is_arithmetic_or_complex< typename detail::remove_pointer<Ptr>::type>::value && detail::is_arithmetic_or_complex<T>::value && detail::is_plus_or_multiplies_if_complex<T, BinaryOperation>::value && detail::is_native_op<T, BinaryOperation>::value), T> sycl::_V1::joint_reduce (Group g, Ptr first, Ptr last, T init, BinaryOperation binary_op)
Definition at line 344 of file group_algorithm.hpp.
kernel::ext_oneapi_get_info< ext::oneapi::experimental::info::kernel_queue_specific::max_num_work_group_sync >()
template ext::oneapi::experimental::info:: kernel_queue_specific::max_num_work_group_sync::return_type sycl::_V1::kernel::ext_oneapi_get_info< ext::oneapi::experimental::info::kernel_queue_specific::max_num_work_group_sync > (const queue & Queue) const
kernel::get_info< info::kernel_device_specific::max_sub_group_size >()
template uint32_t sycl::_V1::kernel::get_info< info::kernel_device_specific::max_sub_group_size > (const device & , const sycl::range< 3 > &) const
kernel_bundle()
template<bundle_state State> sycl::_V1::kernel_bundle (kernel_bundle< State > &&) -> kernel_bundle< State >
length_host_impl()
template<typename T > static auto sycl::_V1::length_host_impl (T x) inline static
Definition at line 46 of file geometric_functions.cpp.
link() [1/4]
kernel_bundle<bundle_state::executable> sycl::_V1::link (const kernel_bundle< bundle_state::object > & ObjectBundle, const property_list & PropList = {}) inline
Definition at line 763 of file kernel_bundle.hpp.
link() [2/4]
kernel_bundle<bundle_state::executable> sycl::_V1::link (const kernel_bundle< bundle_state::object > & ObjectBundle, const std::vector< device > & Devs, const property_list & PropList = {}) inline
Definition at line 778 of file kernel_bundle.hpp.
link() [3/4]
kernel_bundle<bundle_state::executable> sycl::_V1::link (const std::vector< kernel_bundle< bundle_state::object >> & ObjectBundles, const property_list & PropList = {}) inline
Definition at line 770 of file kernel_bundle.hpp.
link() [4/4]
kernel_bundle<bundle_state::executable> sycl::_V1::link (const std::vector< kernel_bundle< bundle_state::object >> & ObjectBundles, const std::vector< device > & Devs, const property_list & PropList = {}) inline
Returns
a new kernel_bundle which contains the device images from the ObjectBundles that are translated into one or more new device images of state bundle_state::executable The new bundle represents all of the kernels in ObjectBundles that are compatible with at least one of the devices in Devs.
Definition at line 752 of file kernel_bundle.hpp.
Referenced by sycl::_V1::detail::ProgramManager::bringSYCLDeviceImagesToState().
log()
template<int SZ> ESIMD_NODEBUG ESIMD_INLINE sycl::ext::intel::esimd::simd<float, SZ> sycl::_V1::log (sycl::ext::intel::esimd::simd< float, SZ > x)
Definition at line 59 of file builtins_esimd.hpp.
make_buffer() [1/3]
template<backend Backend, typename T , int Dimensions = 1, typename AllocatorT = buffer_allocator<std::remove_const_t<T>>> std::enable_if_t<Backend == backend::ext_oneapi_level_zero, buffer<T, Dimensions, AllocatorT> > sycl::_V1::make_buffer (const backend_input_t< backend::ext_oneapi_level_zero, buffer< T, Dimensions, AllocatorT >> & BackendObject, const context & TargetContext)
Definition at line 226 of file level_zero.hpp.
make_buffer() [2/3]
template<backend Backend, typename T , int Dimensions = 1, typename AllocatorT = buffer_allocator<std::remove_const_t<T>>> std::enable_if_t<Backend == backend::ext_oneapi_level_zero, buffer<T, Dimensions, AllocatorT> > sycl::_V1::make_buffer (const backend_input_t< backend::ext_oneapi_level_zero, buffer< T, Dimensions, AllocatorT >> & BackendObject, const context & TargetContext, event AvailableEvent)
Definition at line 211 of file level_zero.hpp.
make_buffer() [3/3]
template<backend Backend, typename T , int Dimensions = 1, typename AllocatorT = buffer_allocator<std::remove_const_t<T>>> std::enable_if_t<detail::InteropFeatureSupportMap<Backend>::MakeBuffer == true && Backend != backend::ext_oneapi_level_zero, buffer<T, Dimensions, AllocatorT> > sycl::_V1::make_buffer (const typename backend_traits< Backend >::template input_type< buffer< T, Dimensions, AllocatorT >> & BackendObject, const context & TargetContext, event AvailableEvent = {})
Definition at line 371 of file backend.hpp.
make_context()
template<backend Backend> std::enable_if_t<detail::InteropFeatureSupportMap<Backend>::MakeContext == true, context> sycl::_V1::make_context (const typename backend_traits< Backend >::template input_type< context > & BackendObject, const async_handler & Handler = {})
Definition at line 322 of file backend.hpp.
make_context< backend::ext_oneapi_level_zero >()
template<> context sycl::_V1::make_context< backend::ext_oneapi_level_zero > (const backend_input_t< backend::ext_oneapi_level_zero, context > & BackendObject, const async_handler & Handler) inline
Definition at line 117 of file level_zero.hpp.
make_device()
template<backend Backend> std::enable_if_t<detail::InteropFeatureSupportMap<Backend>::MakeDevice == true, device> sycl::_V1::make_device (const typename backend_traits< Backend >::template input_type< device > & BackendObject)
Definition at line 313 of file backend.hpp.
make_device< backend::ext_oneapi_cuda >()
template<> device sycl::_V1::make_device< backend::ext_oneapi_cuda > (const backend_input_t< backend::ext_oneapi_cuda, device > & BackendObject) inline
Definition at line 66 of file cuda.hpp.
make_device< backend::ext_oneapi_hip >()
template<> device sycl::_V1::make_device< backend::ext_oneapi_hip > (const backend_input_t< backend::ext_oneapi_hip, device > & BackendObject) inline
Definition at line 32 of file hip.hpp.
make_error_code()
std::error_code sycl::_V1::make_error_code (sycl::errc E) noexcept
Constructs an error code using e and sycl_category()
Definition at line 93 of file exception.cpp.
Referenced by sycl::_V1::sub_group::__SYCL_DEPRECATED(), sycl::_V1::ext::oneapi::experimental::detail::graph_impl::add(), sycl::_V1::ext::intel::experimental::task_sequence< f, oneapi::experimental::detail::properties_t< Props... > >::async(), sycl::_V1::detail::kernel_bundle_impl::build_from_source(), sycl::_V1::detail::checkDevSupportDeviceRequirements(), sycl::_V1::detail::checkDevSupportJointMatrix(), sycl::_V1::detail::checkDevSupportJointMatrixMad(), sycl::_V1::ext::oneapi::experimental::detail::checkOclocLibrary(), sycl::_V1::detail::event_impl::checkProfilingPreconditions(), sycl::_V1::detail::ProgramManager::compile(), sycl::_V1::detail::ConvertFToS(), sycl::_V1::detail::queue_impl::createPiQueueProperties(), sycl::_V1::handler::depends_on(), sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::enqueue(), sycl::_V1::queue::ext_oneapi_get_graph(), sycl::_V1::detail::kernel_bundle_impl::ext_oneapi_get_kernel(), sycl::_V1::queue::ext_oneapi_get_last_event(), sycl::_V1::queue::ext_oneapi_set_external_event(), sycl::_V1::detail::for_each(), sycl::_V1::ext::intel::experimental::task_sequence< f, oneapi::experimental::detail::properties_t< Props... > >::get(), sycl::_V1::detail::get_device_info_impl< ext::oneapi::experimental::architecture, ext::oneapi::experimental::info::device::architecture >::get(), sycl::_V1::detail::get_device_info_impl< sycl::device, ext::oneapi::experimental::info::device::composite_device >::get(), sycl::_V1::sub_group::get_group_id(), sycl::_V1::sub_group::get_group_linear_id(), sycl::_V1::sub_group::get_group_range(), sycl::_V1::detail::kernel_bundle_impl::get_kernel(), sycl::_V1::sub_group::get_local_id(), sycl::_V1::sub_group::get_local_linear_id(), sycl::_V1::sub_group::get_local_range(), sycl::_V1::sub_group::get_max_local_range(), sycl::_V1::event::get_profiling_info(), sycl::_V1::handler::get_specialization_constant(), sycl::_V1::detail::getPiImageCopyFlags(), sycl::_V1::detail::context_impl::getProgramForDevImgs(), sycl::_V1::detail::ProgramManager::getSYCLDeviceImages(), sycl::_V1::detail::ProgramManager::getSYCLDeviceImagesWithCompatibleState(), sycl::_V1::detail::event_impl::getWaitList(), sycl::_V1::detail::enqueue_kernel_launch::handleInvalidWorkGroupSize(), sycl::_V1::ext::oneapi::experimental::detail::InvokeOclocQuery(), sycl::_V1::detail::kernel_bundle_impl::kernel_bundle_impl(), sycl::_V1::detail::ProgramManager::link(), sycl::_V1::sub_group::load(), sycl::_V1::ext::oneapi::experimental::detail::loadOclocLibrary(), sycl::_V1::detail::make_queue(), sycl::_V1::ext::oneapi::experimental::detail::graph_impl::makeEdge(), sycl::_V1::queue::memcpy(), sycl::_V1::handler::memcpy(), sycl::_V1::ext::oneapi::experimental::detail::OpenCLC_Supports_Extension(), sycl::_V1::ext::oneapi::experimental::detail::OpenCLC_to_SPIRV(), sycl::_V1::detail::queue_impl::queue_impl(), sycl::_V1::detail::readConfig(), sycl::_V1::detail::reduction_impl< T, BinaryOperation, Dims, Extent, ExplicitIdentity, RedOutVar >::reduction_impl(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_multiple_kernels >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::basic >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::multi >::run(), sycl::_V1::detail::handler_impl::setStateExplicitKernelBundle(), sycl::_V1::detail::handler_impl::setStateSpecConstSet(), sycl::_V1::detail::event_impl::setSubmissionTime(), sycl::_V1::sub_group::shuffle(), sycl::_V1::sub_group::shuffle_down(), sycl::_V1::sub_group::shuffle_up(), sycl::_V1::sub_group::shuffle_xor(), sycl::_V1::sub_group::store(), sycl::_V1::detail::queue_impl::submit_impl(), sycl::_V1::ext::intel::experimental::task_sequence< f, oneapi::experimental::detail::properties_t< Props... > >::task_sequence(), sycl::_V1::ext::oneapi::experimental::detail::graph_impl::throwIfGraphRecordingQueue(), sycl::_V1::ext::oneapi::experimental::detail::node_impl::updateAccessor(), sycl::_V1::handler::use_kernel_bundle(), sycl::_V1::detail::queue_impl::wait(), sycl::_V1::detail::event_impl::wait(), and sycl::_V1::detail::event_impl::waitInternal().
make_event() [1/2]
template<backend Backend> std::enable_if_t<detail::InteropFeatureSupportMap<Backend>::MakeEvent == true, event> sycl::_V1::make_event (const typename backend_traits< Backend >::template input_type< event > & BackendObject, const context & TargetContext)
Definition at line 346 of file backend.hpp.
make_event() [2/2]
template<backend Backend> std::enable_if_t<detail::InteropFeatureSupportMap<Backend>::MakeEvent == true, event> sycl::_V1::make_event (const typename backend_traits< Backend >::template input_type< event > & BackendObject, const context & TargetContext, bool KeepOwnership)
Definition at line 356 of file backend.hpp.
make_event< backend::ext_oneapi_cuda >()
template<> event sycl::_V1::make_event< backend::ext_oneapi_cuda > (const backend_input_t< backend::ext_oneapi_cuda, event > & BackendObject, const context & TargetContext) inline
Definition at line 81 of file cuda.hpp.
make_event< backend::ext_oneapi_level_zero >()
template<> event sycl::_V1::make_event< backend::ext_oneapi_level_zero > (const backend_input_t< backend::ext_oneapi_level_zero, event > & BackendObject, const context & TargetContext) inline
Definition at line 166 of file level_zero.hpp.
make_image() [1/3]
template<backend Backend, int D, typename A > std::enable_if_t<Backend == backend::ext_oneapi_level_zero, image<D, A> > sycl::_V1::make_image (const backend_input_t< Backend, image< D, A >> & BackendObject, const context & TargetContext, event AvailableEvent = {})
make_image() [2/3]
template<backend Backend, int Dimensions = 1, typename AllocatorT = image_allocator> std::enable_if_t<Backend == backend::ext_oneapi_level_zero, image<Dimensions, AllocatorT> > sycl::_V1::make_image (const backend_input_t< Backend, image< Dimensions, AllocatorT >> & BackendObject, const context & TargetContext, event AvailableEvent)
Definition at line 241 of file level_zero.hpp.
make_image() [3/3]
template<backend Backend, int Dimensions = 1, typename AllocatorT = image_allocator> std::enable_if_t<detail::InteropFeatureSupportMap<Backend>::MakeImage == true && Backend != backend::ext_oneapi_level_zero, image<Dimensions, AllocatorT> > sycl::_V1::make_image (const typename backend_traits< Backend >::template input_type< image< Dimensions, AllocatorT >> & BackendObject, const context & TargetContext, event AvailableEvent = {})
Definition at line 384 of file backend.hpp.
make_kernel()
template<backend Backend> kernel sycl::_V1::make_kernel (const typename backend_traits< Backend >::template input_type< kernel > & BackendObject, const context & TargetContext)
Definition at line 394 of file backend.hpp.
make_kernel< backend::ext_oneapi_level_zero >()
template<> kernel sycl::_V1::make_kernel< backend::ext_oneapi_level_zero > (const backend_input_t< backend::ext_oneapi_level_zero, kernel > & BackendObject, const context & TargetContext) inline
Definition at line 195 of file level_zero.hpp.
make_kernel_bundle()
template<backend Backend, bundle_state State> std::enable_if_t<detail::InteropFeatureSupportMap<Backend>::MakeKernelBundle == true, kernel_bundle<State> > sycl::_V1::make_kernel_bundle (const typename backend_traits< Backend >::template input_type< kernel_bundle< State >> & BackendObject, const context & TargetContext)
Definition at line 405 of file backend.hpp.
make_kernel_bundle< backend::ext_oneapi_level_zero, bundle_state::executable >()
template<> kernel_bundle<bundle_state::executable> sycl::_V1::make_kernel_bundle< backend::ext_oneapi_level_zero, bundle_state::executable > (const backend_input_t< backend::ext_oneapi_level_zero, kernel_bundle< bundle_state::executable >> & BackendObject, const context & TargetContext) inline
Definition at line 166 of file level_zero.hpp.
make_platform()
template<backend Backend> std::enable_if_t< detail::InteropFeatureSupportMap<Backend>::MakePlatform == true, platform> sycl::_V1::make_platform (const typename backend_traits< Backend >::template input_type< platform > & BackendObject)
Definition at line 303 of file backend.hpp.
make_queue()
template<backend Backend> std::enable_if_t<detail::InteropFeatureSupportMap<Backend>::MakeQueue == true, queue> sycl::_V1::make_queue (const typename backend_traits< Backend >::template input_type< queue > & BackendObject, const context & TargetContext, const async_handler Handler = {})
Definition at line 333 of file backend.hpp.
make_queue< backend::ext_oneapi_cuda >()
template<> queue sycl::_V1::make_queue< backend::ext_oneapi_cuda > (const backend_input_t< backend::ext_oneapi_cuda, queue > & BackendObject, const context & TargetContext, const async_handler Handler) inline
Definition at line 91 of file cuda.hpp.
make_queue< backend::ext_oneapi_level_zero >()
template<> queue sycl::_V1::make_queue< backend::ext_oneapi_level_zero > (const backend_input_t< backend::ext_oneapi_level_zero, queue > & BackendObject, const context & TargetContext, const async_handler Handler) inline
Definition at line 130 of file level_zero.hpp.
malloc() [1/8]
void* sycl::_V1::malloc (size_t Size, const device & Dev, const context & Ctxt, alloc Kind, const detail::code_location & CodeLoc)
Definition at line 499 of file usm_impl.cpp.
malloc() [2/8]
void* sycl::_V1::malloc (size_t Size, const device & Dev, const context & Ctxt, alloc Kind, const property_list & PropList, const detail::code_location & CodeLoc)
Definition at line 490 of file usm_impl.cpp.
malloc() [3/8]
void* sycl::_V1::malloc (size_t size, const device & dev, const context & ctxt, usm::alloc kind, const detail::code_location & CodeLoc = detail::code_location::current())
malloc() [4/8]
void* sycl::_V1::malloc (size_t size, const device & dev, const context & ctxt, usm::alloc kind, const property_list & propList = {}, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 292 of file usm.hpp.
malloc() [5/8]
void* sycl::_V1::malloc (size_t Size, const queue & Q, alloc Kind, const detail::code_location & CodeLoc)
Definition at line 508 of file usm_impl.cpp.
malloc() [6/8]
void* sycl::_V1::malloc (size_t Size, const queue & Q, alloc Kind, const property_list & PropList, const detail::code_location & CodeLoc)
Definition at line 517 of file usm_impl.cpp.
malloc() [7/8]
void* sycl::_V1::malloc (size_t size, const queue & q, usm::alloc kind, const detail::code_location & CodeLoc = detail::code_location::current())
malloc() [8/8]
void* sycl::_V1::malloc (size_t size, const queue & q, usm::alloc kind, const property_list & propList = {}, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 301 of file usm.hpp.
malloc_device() [1/4]
void * sycl::_V1::malloc_device (size_t size, const device & dev, const context & ctxt, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 320 of file usm_impl.cpp.
malloc_device() [2/4]
void * sycl::_V1::malloc_device (size_t size, const device & dev, const context & ctxt, const property_list & propList = {}, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 168 of file usm.hpp.
malloc_device() [3/4]
void * sycl::_V1::malloc_device (size_t size, const queue & q, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 333 of file usm_impl.cpp.
malloc_device() [4/4]
void * sycl::_V1::malloc_device (size_t size, const queue & q, const property_list & propList = {}, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 177 of file usm.hpp.
malloc_host() [1/4]
void * sycl::_V1::malloc_host (size_t size, const context & ctxt, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 383 of file usm_impl.cpp.
malloc_host() [2/4]
void * sycl::_V1::malloc_host (size_t size, const context & ctxt, const property_list & propList = {}, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 210 of file usm.hpp.
malloc_host() [3/4]
void * sycl::_V1::malloc_host (size_t size, const queue & q, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 396 of file usm_impl.cpp.
malloc_host() [4/4]
void * sycl::_V1::malloc_host (size_t size, const queue & q, const property_list & propList = {}, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 218 of file usm.hpp.
malloc_shared() [1/4]
void * sycl::_V1::malloc_shared (size_t size, const device & dev, const context & ctxt, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 408 of file usm_impl.cpp.
malloc_shared() [2/4]
void * sycl::_V1::malloc_shared (size_t size, const device & dev, const context & ctxt, const property_list & propList = {}, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 225 of file usm.hpp.
malloc_shared() [3/4]
void * sycl::_V1::malloc_shared (size_t size, const queue & q, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 421 of file usm_impl.cpp.
malloc_shared() [4/4]
void * sycl::_V1::malloc_shared (size_t size, const queue & q, const property_list & propList = {}, const detail::code_location & CodeLoc = detail::code_location::current())
Definition at line 234 of file usm.hpp.
multi_ptr() [1/6]
sycl::_V1::multi_ptr ()
Definition at line 468 of file multi_ptr.hpp.
multi_ptr() [2/6]
template<typename ElementType , int Dimensions, access::mode Mode, access::placeholder isPlaceholder, typename PropertyListT , access::address_space RelaySpace = Space, typename = typename std::enable_if_t< RelaySpace == Space && (Space == access::address_space::global_space || Space == access::address_space::generic_space || Space == access::address_space::ext_intel_global_device_space)>> sycl::_V1::multi_ptr (accessor< ElementType, Dimensions, Mode, target::device, isPlaceholder, PropertyListT > Accessor)
Definition at line 487 of file multi_ptr.hpp.
multi_ptr() [3/6]
sycl::_V1::multi_ptr (const multi_ptr &) default
multi_ptr() [4/6]
sycl::_V1::multi_ptr (multi_ptr &&) default
multi_ptr() [5/6]
sycl::_V1::multi_ptr (std::nullptr_t)
Definition at line 474 of file multi_ptr.hpp.
multi_ptr() [6/6]
sycl::_V1::multi_ptr (typename multi_ptr< const void, Space, access::decorated::yes >::pointer ptr) explicit
Definition at line 471 of file multi_ptr.hpp.
none_of_group() [1/2]
template<typename Group > std::enable_if_t<is_group_v<std::decay_t<Group> >, bool> sycl::_V1::none_of_group (Group g, bool pred)
Definition at line 481 of file group_algorithm.hpp.
none_of_group() [2/2]
template<typename Group , typename T , class Predicate > std::enable_if_t<is_group_v<std::decay_t<Group> >, bool> sycl::_V1::none_of_group (Group g, T x, Predicate pred)
Definition at line 500 of file group_algorithm.hpp.
normalize_host_impl()
template<typename T > static auto sycl::_V1::normalize_host_impl (T x) inline static
Definition at line 73 of file geometric_functions.cpp.
operator multi_ptr< const void, GlobalSpace, DecorateAddress >()
template<access::address_space GlobalSpace = access::address_space::global_space, access::address_space RelaySpace = Space, typename = typename std::enable_if_t< RelaySpace == Space && GlobalSpace == access::address_space::global_space && (Space == access::address_space::ext_intel_global_device_space || Space == access::address_space::ext_intel_global_host_space)>> sycl::_V1::operator multi_ptr< const void, GlobalSpace, DecorateAddress > () const explicit
Definition at line 581 of file multi_ptr.hpp.
operator multi_ptr< ElementType, Space, DecorateAddress >() [1/2]
template<typename ElementType , typename = typename std::enable_if_t<std::is_const_v<ElementType>>> sycl::_V1::operator multi_ptr< ElementType, Space, DecorateAddress > () const explicit
Definition at line 554 of file multi_ptr.hpp.
operator multi_ptr< ElementType, Space, DecorateAddress >() [2/2]
template<typename ElementType > sycl::_V1::operator multi_ptr< ElementType, Space, DecorateAddress > () const explicit
Definition at line 704 of file multi_ptr.hpp.
operator multi_ptr< void, GlobalSpace, DecorateAddress >()
template<access::address_space GlobalSpace = access::address_space::global_space, access::address_space RelaySpace = Space, typename = typename std::enable_if_t< RelaySpace == Space && GlobalSpace == access::address_space::global_space && (Space == access::address_space::ext_intel_global_device_space || Space == access::address_space::ext_intel_global_host_space)>> sycl::_V1::operator multi_ptr< void, GlobalSpace, DecorateAddress > () const explicit
Definition at line 730 of file multi_ptr.hpp.
operator<<() [1/23]
const stream& sycl::_V1::operator<< (const stream & Out, const __precision_manipulator__ & RHS) inline
Definition at line 1214 of file stream.hpp.
operator<<() [2/23]
const stream& sycl::_V1::operator<< (const stream & Out, const __width_manipulator__ & RHS) inline
Definition at line 1220 of file stream.hpp.
operator<<() [3/23]
const stream& sycl::_V1::operator<< (const stream & Out, const bool & RHS) inline
Definition at line 1146 of file stream.hpp.
operator<<() [4/23]
const stream& sycl::_V1::operator<< (const stream & Out, const char * Str) inline
Definition at line 1135 of file stream.hpp.
operator<<() [5/23]
const stream& sycl::_V1::operator<< (const stream & Out, const char C) inline
Definition at line 1129 of file stream.hpp.
operator<<() [6/23]
const stream& sycl::_V1::operator<< (const stream & Out, const double & RHS) inline
Definition at line 1169 of file stream.hpp.
operator<<() [7/23]
const stream& sycl::_V1::operator<< (const stream & Out, const ext::oneapi::bfloat16 & RHS) inline
Definition at line 1183 of file stream.hpp.
operator<<() [8/23]
const stream& sycl::_V1::operator<< (const stream & Out, const float & RHS) inline
Definition at line 1162 of file stream.hpp.
operator<<() [9/23]
template<int Dimensions> const stream& sycl::_V1::operator<< (const stream & Out, const group< Dimensions > & RHS) inline
Definition at line 1297 of file stream.hpp.
operator<<() [10/23]
template<int Dimensions> const stream& sycl::_V1::operator<< (const stream & Out, const h_item< Dimensions > & RHS) inline
Definition at line 1305 of file stream.hpp.
operator<<() [11/23]
const stream& sycl::_V1::operator<< (const stream & Out, const half & RHS) inline
Definition at line 1176 of file stream.hpp.
operator<<() [12/23]
template<int Dimensions> const stream& sycl::_V1::operator<< (const stream & Out, const id< Dimensions > & RHS) inline
Definition at line 1258 of file stream.hpp.
operator<<() [13/23]
template<int Dimensions> const stream& sycl::_V1::operator<< (const stream & Out, const item< Dimensions > & RHS) inline
Definition at line 1273 of file stream.hpp.
operator<<() [14/23]
template<typename ElementType , access::address_space Space, access::decorated IsDecorated> const stream& sycl::_V1::operator<< (const stream & Out, const multi_ptr< ElementType, Space, IsDecorated > & RHS) inline
Definition at line 1195 of file stream.hpp.
operator<<() [15/23]
template<int Dimensions> const stream& sycl::_V1::operator<< (const stream & Out, const nd_item< Dimensions > & RHS) inline
Definition at line 1289 of file stream.hpp.
operator<<() [16/23]
template<int Dimensions> const stream& sycl::_V1::operator<< (const stream & Out, const nd_range< Dimensions > & RHS) inline
Definition at line 1281 of file stream.hpp.
operator<<() [17/23]
template<int Dimensions> const stream& sycl::_V1::operator<< (const stream & Out, const range< Dimensions > & RHS) inline
Definition at line 1265 of file stream.hpp.
operator<<() [18/23]
const stream& sycl::_V1::operator<< (const stream & Out, const stream_manipulator RHS) inline
Definition at line 1226 of file stream.hpp.
operator<<() [19/23]
template<typename T , typename RT = detail::EnableIfSwizzleVec<T>> const stream& sycl::_V1::operator<< (const stream & Out, const T & RHS) inline
Definition at line 1313 of file stream.hpp.
operator<<() [20/23]
template<typename T > const stream& sycl::_V1::operator<< (const stream & Out, const T * RHS)
Definition at line 1203 of file stream.hpp.
operator<<() [21/23]
template<typename ValueType > std::enable_if_t<std::is_integral_v<ValueType>, const stream &> sycl::_V1::operator<< (const stream & Out, const ValueType & RHS) inline
Definition at line 1146 of file stream.hpp.
operator<<() [22/23]
template<typename T , int VectorLength> const stream& sycl::_V1::operator<< (const stream & Out, const vec< T, VectorLength > & RHS)
Definition at line 1248 of file stream.hpp.
operator<<() [23/23]
std::ostream& sycl::_V1::operator<< (std::ostream & Out, backend be) inline
Definition at line 39 of file backend_types.hpp.
operator=() [1/2]
multi_ptr & sycl::_V1::operator= (multi_ptr &&) default
Initial value:
= typename std::enable_if_t<
                RelaySpace == Space &&
                (Space == access::address_space::local_space ||
                 Space == access::address_space::generic_space)>>
  multi_ptr(local_accessor<ElementType, Dimensions> Accessor)
      : multi_ptr(Accessor.template get_multi_ptr<DecorateAddress>()
                      .get_decorated()) {}
  template <
      typename ElementType, int dimensions, typename PropertyListT,
      access::address_space _Space = Space,
      typename = typename std::enable_if_t<
          _Space == Space && Space == access::address_space::constant_space>>
  __SYCL2020_DEPRECATED(
      "multi_ptr construction using target::constant_buffer specialized "
      "accessor is deprecated since SYCL 2020")
  multi_ptr(accessor<ElementType, dimensions, access_mode::read,
                     target::constant_buffer, access::placeholder::false_t,
                     PropertyListT>
                Accessor)
      : multi_ptr(Accessor.template get_multi_ptr<DecorateAddress>()
                      .get_decorated()) {}
  multi_ptr &operator=(const multi_ptr &) = default
operator=() [2/2]
multi_ptr & sycl::_V1::operator= (std::nullptr_t)
Definition at line 539 of file multi_ptr.hpp.
permute_group_by_xor()
template<typename Group , typename T > std::enable_if_t<((std::is_same_v<std::decay_t<Group>, sub_group> || sycl::ext::oneapi::experimental::is_user_constructed_group_v< std::decay_t<Group>>) && (std::is_trivially_copyable_v<T> || detail::is_vec<T>::value)), T> sycl::_V1::permute_group_by_xor (Group g, T x, typename Group::linear_id_type mask)
Definition at line 575 of file group_algorithm.hpp.
prepare_for_usm_device_copy()
static void sycl::_V1::prepare_for_usm_device_copy (const void * Ptr, size_t Size, const context & Ctxt) static
Definition at line 670 of file usm_impl.cpp.
Referenced by sycl::_V1::ext::oneapi::experimental::prepare_for_device_copy().
process_arg_for_macos()
template<typename T > static auto sycl::_V1::process_arg_for_macos (T x) static
Definition at line 19 of file relational_functions.cpp.
reduce_over_group() [1/5]
template<typename Group , typename T , class BinaryOperation > std::enable_if_t<(is_group_v<std::decay_t<Group>> && (detail::is_scalar_arithmetic<T>::value || (detail::is_complex<T>::value && detail::is_multiplies<T, BinaryOperation>::value)) && detail::is_native_op<T, BinaryOperation>::value), T> sycl::_V1::reduce_over_group (Group g, T x, BinaryOperation binary_op)
Definition at line 218 of file group_algorithm.hpp.
Referenced by sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_last_wg_detection >::run(), sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_atomic_cross_wg >::run(), and sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_multiple_kernels >::run().
reduce_over_group() [2/5]
template<typename Group , typename T , class BinaryOperation > std::enable_if_t<(is_group_v<std::decay_t<Group>> && detail::is_vector_arithmetic_or_complex<T>::value && detail::is_native_op<T, BinaryOperation>::value), T> sycl::_V1::reduce_over_group (Group g, T x, BinaryOperation binary_op)
Definition at line 270 of file group_algorithm.hpp.
reduce_over_group() [3/5]
template<typename Group , typename T , class BinaryOperation > std::enable_if_t<(is_group_v<std::decay_t<Group>> && detail::is_complex<T>::value && detail::is_native_op<T, sycl::plus<T>>::value && detail::is_plus<T, BinaryOperation>::value), T> sycl::_V1::reduce_over_group (Group g, T x, BinaryOperation)
Definition at line 251 of file group_algorithm.hpp.
reduce_over_group() [4/5]
template<typename Group , typename V , typename T , class BinaryOperation > std::enable_if_t< (is_group_v<std::decay_t<Group>> && (detail::is_scalar_arithmetic<V>::value || detail::is_complex<V>::value) && (detail::is_scalar_arithmetic<T>::value || detail::is_complex<T>::value) && detail::is_native_op<T, BinaryOperation>::value && detail::is_plus_or_multiplies_if_complex<T, BinaryOperation>::value && std::is_convertible_v<V, T>), T> sycl::_V1::reduce_over_group (Group g, V x, T init, BinaryOperation binary_op)
Definition at line 294 of file group_algorithm.hpp.
reduce_over_group() [5/5]
template<typename Group , typename V , typename T , class BinaryOperation > std::enable_if_t<(is_group_v<std::decay_t<Group>> && detail::is_vector_arithmetic_or_complex<V>::value && detail::is_vector_arithmetic_or_complex<T>::value && detail::is_native_op<V, BinaryOperation>::value && detail::is_native_op<T, BinaryOperation>::value), T> sycl::_V1::reduce_over_group (Group g, V x, T init, BinaryOperation binary_op)
Definition at line 314 of file group_algorithm.hpp.
reduction() [1/6]
template<typename T , typename AllocatorT , typename BinaryOperation > auto sycl::_V1::reduction (buffer< T, 1, AllocatorT > Var, handler & CGH, BinaryOperation Combiner, const property_list & PropList = {})
Constructs a reduction object using the given buffer Var, handler CGH, reduction operation Combiner, and optional reduction properties.
The reduction algorithm may be less efficient if the specified binary operation does not have a known identity.
Definition at line 2837 of file reduction.hpp.
reduction() [2/6]
template<typename T , typename AllocatorT , typename BinaryOperation > auto sycl::_V1::reduction (buffer< T, 1, AllocatorT > Var, handler & CGH, const T & Identity, BinaryOperation Combiner, const property_list & PropList = {})
Constructs a reduction object using the given buffer Var, handler CGH, reduction identity value Identity, reduction operation Combiner, and optional reduction properties.
Definition at line 2864 of file reduction.hpp.
reduction() [3/6]
template<typename T , size_t Extent, typename BinaryOperation , typename = std::enable_if_t<Extent != dynamic_extent>> auto sycl::_V1::reduction (span< T, Extent > Span, BinaryOperation Combiner, const property_list & PropList = {})
Constructs a reduction object using the reduction variable referenced by the given sycl::span Span, reduction operation Combiner, and optional reduction properties.
The reduction algorithm may be less efficient if the specified binary operation does not have a known identity.
Definition at line 2892 of file reduction.hpp.
reduction() [4/6]
template<typename T , size_t Extent, typename BinaryOperation , typename = std::enable_if_t<Extent != dynamic_extent>> auto sycl::_V1::reduction (span< T, Extent > Span, const T & Identity, BinaryOperation Combiner, const property_list & PropList = {})
Constructs a reduction object using the reduction variable referenced by the given sycl::span Span, reduction identity value Identity, reduction operation Combiner, and optional reduction properties.
Definition at line 2905 of file reduction.hpp.
reduction() [5/6]
template<typename T , typename BinaryOperation > auto sycl::_V1::reduction (T * Var, BinaryOperation Combiner, const property_list & PropList = {})
Constructs a reduction object using the reduction variable referenced by the given USM pointer Var, handler CGH, reduction operation Combiner, and optional reduction properties.
The reduction algorithm may be less efficient if the specified binary operation does not have a known identity.
Definition at line 2852 of file reduction.hpp.
reduction() [6/6]
template<typename T , typename BinaryOperation > auto sycl::_V1::reduction (T * Var, const T & Identity, BinaryOperation Combiner, const property_list & PropList = {})
Constructs a reduction object using the reduction variable referenced by the given USM pointer Var, reduction identity value Identity, binary operation Combiner, and optional reduction properties.
Definition at line 2877 of file reduction.hpp.
REL_BUILTIN_CUSTOM() [1/4]
sycl::_V1::REL_BUILTIN_CUSTOM (TWO_ARGS , isequal , ([](auto x, auto y) { return x==y;}))
REL_BUILTIN_CUSTOM() [2/4]
sycl::_V1::REL_BUILTIN_CUSTOM (TWO_ARGS , isgreater , ([](auto x, auto y) { return x > y;}))
REL_BUILTIN_CUSTOM() [3/4]
sycl::_V1::REL_BUILTIN_CUSTOM (TWO_ARGS , isless , ([](auto x, auto y) { return x< y;}))
REL_BUILTIN_CUSTOM() [4/4]
sycl::_V1::REL_BUILTIN_CUSTOM (TWO_ARGS , islessgreater , ([](auto x, auto y) { return x< y||x > y;}))
release_from_usm_device_copy()
static void sycl::_V1::release_from_usm_device_copy (const void * Ptr, const context & Ctxt) static
Definition at line 679 of file usm_impl.cpp.
Referenced by sycl::_V1::ext::oneapi::experimental::release_from_device_copy().
return() [1/2]
sycl::_V1::return (mul >> sizeof(T) *8)
return() [2/2]
sycl::_V1::return (x >> one) &
rint() [1/2]
double sycl::_V1::rint (double) inline
rint() [2/2]
float sycl::_V1::rint (float) inline
select_from_group()
template<typename Group , typename T > std::enable_if_t<((std::is_same_v<std::decay_t<Group>, sub_group> || sycl::ext::oneapi::experimental::is_user_constructed_group_v< std::decay_t<Group>>) && (std::is_trivially_copyable_v<T> || detail::is_vec<T>::value)), T> sycl::_V1::select_from_group (Group g, T x, typename Group::id_type local_id)
Definition at line 597 of file group_algorithm.hpp.
setprecision()
__precision_manipulator__ sycl::_V1::setprecision (int Precision) inline
Definition at line 836 of file stream.hpp.
setw()
__width_manipulator__ sycl::_V1::setw (int Width) inline
Definition at line 840 of file stream.hpp.
shift_group_left()
template<typename Group , typename T > std::enable_if_t<((std::is_same_v<std::decay_t<Group>, sub_group> || sycl::ext::oneapi::experimental::is_user_constructed_group_v< std::decay_t<Group>>) && (std::is_trivially_copyable_v<T> || detail::is_vec<T>::value)), T> sycl::_V1::shift_group_left (Group g, T x, typename Group::linear_id_type delta = 1)
Definition at line 531 of file group_algorithm.hpp.
shift_group_right()
template<typename Group , typename T > std::enable_if_t<((std::is_same_v<std::decay_t<Group>, sub_group> || sycl::ext::oneapi::experimental::is_user_constructed_group_v< std::decay_t<Group>>) && (std::is_trivially_copyable_v<T> || detail::is_vec<T>::value)), T> sycl::_V1::shift_group_right (Group g, T x, typename Group::linear_id_type delta = 1)
Definition at line 553 of file group_algorithm.hpp.
sin()
template<int SZ> ESIMD_NODEBUG ESIMD_INLINE sycl::ext::intel::esimd::simd<float, SZ> sycl::_V1::sin (sycl::ext::intel::esimd::simd< float, SZ > x)
Definition at line 37 of file builtins_esimd.hpp.
span() [1/5]
template<class _Container > sycl::_V1::span (_Container &) -> span< typename _Container::value_type >
span() [2/5]
template<class _Tp , size_t _Sz> sycl::_V1::span (_Tp(&) [_Sz]) -> span< _Tp, _Sz >
span() [3/5]
template<class _Container > sycl::_V1::span (const _Container &) -> span< const typename _Container::value_type >
span() [4/5]
template<class _Tp , size_t _Sz> sycl::_V1::span (const std::array< _Tp, _Sz > &) -> span< const _Tp, _Sz >
span() [5/5]
template<class _Tp , size_t _Sz> sycl::_V1::span (std::array< _Tp, _Sz > &) -> span< _Tp, _Sz >
sycl_category()
const std::error_category & sycl::_V1::sycl_category () noexcept
Definition at line 88 of file exception.cpp.
traceDeviceSelector()
static void sycl::_V1::traceDeviceSelector (const std::string & DeviceType) static
default_selector_v Devices of different kinds are prioritized in the following order:
GPU
CPU
Host
Accelerator
Definition at line 169 of file device_selector.cpp.
trunc() [1/2]
double sycl::_V1::trunc (double) inline
trunc() [2/2]
float sycl::_V1::trunc (float) inline
Variable Documentation
a
auto sycl::_V1::a
Definition at line 179 of file integer_functions.cpp.
a_s
UPT sycl::_V1::a_s = a
Definition at line 188 of file integer_functions.cpp.
abs_diff
sycl::_V1::abs_diff
Definition at line 92 of file integer_functions.cpp.
AccessMode
class __SYCL_EBO __SYCL_SPECIAL_CLASS sycl::_V1::AccessMode
Definition at line 577 of file accessor_image.hpp.
Referenced by sycl::_V1::detail::AccessorBaseHost::AccessorBaseHost(), sycl::_V1::detail::Scheduler::GraphBuilder::addNodeToLeaves(), sycl::_V1::handler::copy(), sycl::_V1::image< Dimensions, AllocatorT >::get_access(), sycl::_V1::detail::UnsampledImageAccessorBaseHost::UnsampledImageAccessorBaseHost(), sycl::_V1::detail::SYCLMemObjT::updateHostMemory(), and sycl::_V1::detail::Scheduler::GraphBuilder::updateLeaves().
Accessor
PropertyListT sycl::_V1::Accessor
Definition at line 506 of file multi_ptr.hpp.
address_space
static constexpr access::address_space sycl::_V1::address_space = Space static constexpr
Definition at line 455 of file multi_ptr.hpp.
asinpi
sycl::_V1::asinpi
Definition at line 41 of file math_functions.cpp.
atan2pi
sycl::_V1::atan2pi
Definition at line 48 of file math_functions.cpp.
b
auto autodecltype(a) sycl::_V1::b
Initial value:
{
  using T = decltype(a)
Definition at line 179 of file integer_functions.cpp.
Referenced by std::hash< sycl::buffer< T, dimensions, AllocatorT > >::operator()().
b_s
UPT sycl::_V1::b_s = b
Definition at line 189 of file integer_functions.cpp.
clamp
sycl::_V1::clamp
Definition at line 218 of file integer_functions.cpp.
dec
constexpr stream_manipulator sycl::_V1::dec = stream_manipulator::dec constexpr
Definition at line 784 of file stream.hpp.
defaultfloat
constexpr stream_manipulator sycl::_V1::defaultfloat = stream_manipulator::defaultfloat constexpr
Definition at line 808 of file stream.hpp.
Dimensions
PropertyListT int sycl::_V1::Dimensions
Definition at line 577 of file accessor_image.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::auto_range(), sycl::_V1::image< Dimensions, AllocatorT >::get_access(), sycl::_V1::nd_item< Dimensions >::get_global_linear_id(), sycl::_V1::nd_item< Dimensions >::get_group_linear_id(), sycl::_V1::ext::oneapi::experimental::root_group< Dimensions >::get_group_range(), sycl::_V1::nd_item< Dimensions >::get_local_linear_id(), sycl::_V1::detail::image_common< Dimensions, AllocatorT >::get_pitch(), sycl::_V1::image< Dimensions, AllocatorT >::get_pitch(), sycl::_V1::detail::getImageType(), sycl::_V1::detail::getOffsetForId(), sycl::_V1::detail::image_plain::image_plain(), sycl::_V1::detail::prepTermPositions(), sycl::_V1::range< Dimensions >::size(), sycl::_V1::detail::__image_array_slice__< DataT, Dimensions, AccessMode, IsPlaceholder >::size(), sycl::_V1::detail::SYCLMemObjT::SYCLMemObjT(), sycl::_V1::ext::oneapi::experimental::detail::node_impl::updateNDRange(), and sycl::_V1::ext::oneapi::experimental::detail::node_impl::updateRange().
dynamic_extent
constexpr size_t sycl::_V1::dynamic_extent = SIZE_MAX inline constexpr
Definition at line 152 of file sycl_span.hpp.
Referenced by sycl::_V1::span< _Tp, dynamic_extent >::subspan(), and sycl::_V1::span< _Tp, _Extent >::subspan().
else
sycl::_V1::else
Initial value:
{
    using UPT = sycl::detail::make_larger_t<T>
Definition at line 186 of file integer_functions.cpp.
endl
constexpr stream_manipulator sycl::_V1::endl = stream_manipulator::endl constexpr
Definition at line 798 of file stream.hpp.
exp10
sycl::_V1::exp10
Definition at line 63 of file math_functions.cpp.
fixed
constexpr stream_manipulator sycl::_V1::fixed = stream_manipulator::fixed constexpr
Definition at line 802 of file stream.hpp.
flush
constexpr stream_manipulator sycl::_V1::flush = stream_manipulator::flush constexpr
Definition at line 800 of file stream.hpp.
hadd
return std::max (x, y) - std sycl::_V1::hadd
Definition at line 119 of file integer_functions.cpp.
has_known_identity_v
template<typename BinaryOperation , typename AccumulatorT > constexpr bool sycl::_V1::has_known_identity_v inline constexpr
Initial value:
=
    sycl::has_known_identity<BinaryOperation, AccumulatorT>::value
Definition at line 405 of file known_identity.hpp.
hex
constexpr stream_manipulator sycl::_V1::hex = stream_manipulator::hex constexpr
Definition at line 786 of file stream.hpp.
hexfloat
constexpr stream_manipulator sycl::_V1::hexfloat = stream_manipulator::hexfloat constexpr
Definition at line 806 of file stream.hpp.
is_decorated
static constexpr bool sycl::_V1::is_decorated static constexpr
Initial value:
=
      DecorateAddress == access::decorated::yes
Definition at line 453 of file multi_ptr.hpp.
is_device_copyable_v
template<typename T > constexpr bool sycl::_V1::is_device_copyable_v = is_device_copyable<T>::value inline constexpr
Definition at line 82 of file is_device_copyable.hpp.
is_group_v
template<class T > constexpr bool sycl::_V1::is_group_v = is_group<T>::value inline constexpr
Definition at line 109 of file type_traits.hpp.
is_property_of_v
template<typename propertyT , typename syclObjectT > constexpr bool sycl::_V1::is_property_of_v inline constexpr
Initial value:
=
    is_property_of<propertyT, syclObjectT>::value
Definition at line 32 of file property_traits.hpp.
is_property_v
template<typename propertyT > constexpr bool sycl::_V1::is_property_v = is_property<propertyT>::value inline constexpr
Definition at line 29 of file property_traits.hpp.
isgreaterequal
sycl::_V1::isgreaterequal
Definition at line 60 of file relational_functions.cpp.
islessequal
sycl::_V1::islessequal
Definition at line 63 of file relational_functions.cpp.
isnotequal
sycl::_V1::isnotequal
Definition at line 57 of file relational_functions.cpp.
isordered
sycl::_V1::isordered
Definition at line 72 of file relational_functions.cpp.
IsPlaceholder
class __SYCL_EBO __SYCL_SPECIAL_CLASS sycl::_V1::IsPlaceholder
Definition at line 577 of file accessor_image.hpp.
isPlaceholder
sycl::_V1::isPlaceholder
Definition at line 505 of file multi_ptr.hpp.
known_identity_v
template<typename BinaryOperation , typename AccumulatorT > constexpr AccumulatorT sycl::_V1::known_identity_v inline constexpr
Initial value:
=
    sycl::known_identity<BinaryOperation, AccumulatorT>::value
Definition at line 415 of file known_identity.hpp.
mad_hi
sycl::_V1::mad_hi
Definition at line 129 of file integer_functions.cpp.
max
sycl::_V1::max
Definition at line 212 of file integer_functions.cpp.
MAX_STATEMENT_SIZE
constexpr size_t sycl::_V1::MAX_STATEMENT_SIZE static constexpr
Initial value:
=
    (1 << (CHAR_BIT * detail::FLUSH_BUF_OFFSET_SIZE)) - 1
Definition at line 20 of file stream.cpp.
maxmag
sycl::_V1::maxmag
Definition at line 83 of file math_functions.cpp.
MaxNumAdditionalArgs
constexpr size_t sycl::_V1::MaxNumAdditionalArgs = 13 inline constexpr
Definition at line 836 of file handler.cpp.
memory_order_acq_rel
constexpr auto sycl::_V1::memory_order_acq_rel = memory_order::acq_rel inline constexpr
Definition at line 46 of file memory_enums.hpp.
Referenced by sycl::_V1::detail::getStdMemoryOrder().
memory_order_acquire
constexpr auto sycl::_V1::memory_order_acquire = memory_order::acquire inline constexpr
Definition at line 44 of file memory_enums.hpp.
Referenced by sycl::_V1::detail::getStdMemoryOrder().
memory_order_relaxed
constexpr auto sycl::_V1::memory_order_relaxed = memory_order::relaxed inline constexpr
Definition at line 43 of file memory_enums.hpp.
Referenced by sycl::_V1::detail::getStdMemoryOrder().
memory_order_release
constexpr auto sycl::_V1::memory_order_release = memory_order::release inline constexpr
Definition at line 45 of file memory_enums.hpp.
Referenced by sycl::_V1::detail::getStdMemoryOrder().
memory_order_seq_cst
constexpr auto sycl::_V1::memory_order_seq_cst = memory_order::seq_cst inline constexpr
Definition at line 47 of file memory_enums.hpp.
Referenced by sycl::_V1::detail::getStdMemoryOrder().
memory_scope_device
constexpr auto sycl::_V1::memory_scope_device = memory_scope::device inline constexpr
Definition at line 40 of file memory_enums.hpp.
memory_scope_sub_group
constexpr auto sycl::_V1::memory_scope_sub_group = memory_scope::sub_group inline constexpr
Definition at line 38 of file memory_enums.hpp.
memory_scope_system
constexpr auto sycl::_V1::memory_scope_system = memory_scope::system inline constexpr
Definition at line 41 of file memory_enums.hpp.
memory_scope_work_group
constexpr auto sycl::_V1::memory_scope_work_group = memory_scope::work_group inline constexpr
Definition at line 39 of file memory_enums.hpp.
memory_scope_work_item
constexpr auto sycl::_V1::memory_scope_work_item = memory_scope::work_item inline constexpr
Definition at line 37 of file memory_enums.hpp.
min
sycl::_V1::min
Definition at line 63 of file common_functions.cpp.
mix
sycl::_V1::mix
Definition at line 47 of file common_functions.cpp.
Mode
sycl::_V1::Mode
Definition at line 504 of file multi_ptr.hpp.
Referenced by sycl::_V1::detail::accessModeToString(), sycl::_V1::detail::XPTIRegistry::bufferAccessorNotification(), sycl::_V1::detail::constructorNotification(), sycl::_V1::buffer< T, dimensions, AllocatorT, __Enabled >::get_access(), sycl::_V1::detail::XPTIRegistry::unsampledImageAccessorNotification(), sycl::_V1::detail::unsampledImageConstructorNotification(), and sycl::_V1::detail::XPTIRegistry::unsampledImageHostAccessorNotification().
mul
UPT sycl::_V1::mul = a_s * b_s
Definition at line 190 of file integer_functions.cpp.
mul_hi
sycl::_V1::mul_hi
Definition at line 179 of file integer_functions.cpp.
nextafter
sycl::_V1::nextafter
Definition at line 124 of file math_functions.cpp.
no_init
constexpr property::no_init sycl::_V1::no_init inline constexpr
Definition at line 33 of file accessor_properties.hpp.
noinit
constexpr property::noinit sycl::_V1::noinit inline constexpr
Definition at line 36 of file accessor_properties.hpp.
noshowbase
constexpr stream_manipulator sycl::_V1::noshowbase = stream_manipulator::noshowbase constexpr
Definition at line 790 of file stream.hpp.
noshowpos
constexpr stream_manipulator sycl::_V1::noshowpos = stream_manipulator::noshowpos constexpr
Definition at line 794 of file stream.hpp.
oct
constexpr stream_manipulator sycl::_V1::oct = stream_manipulator::oct constexpr
Definition at line 788 of file stream.hpp.
powr
sycl::_V1::powr
Definition at line 98 of file math_functions.cpp.
radians
sycl::_V1::radians
Definition at line 32 of file common_functions.cpp.
read_constant
constexpr mode_target_tag_t<access_mode::read, target::constant_buffer> sycl::_V1::read_constant {} inline constexpr
Definition at line 88 of file access.hpp.
read_only
constexpr mode_tag_t<access_mode::read> sycl::_V1::read_only {} inline constexpr
Definition at line 84 of file access.hpp.
read_only_host_task
constexpr mode_target_tag_t<access_mode::read, target::host_task> sycl::_V1::read_only_host_task inline constexpr
Definition at line 90 of file access.hpp.
read_write
constexpr mode_tag_t<access_mode::read_write> sycl::_V1::read_write {} inline constexpr
Definition at line 85 of file access.hpp.
read_write_host_task
constexpr mode_target_tag_t<access_mode::read_write, target::host_task> sycl::_V1::read_write_host_task inline constexpr
Definition at line 92 of file access.hpp.
RelaySpace
PropertyListT int access::address_space sycl::_V1::RelaySpace = Space
Definition at line 511 of file multi_ptr.hpp.
scientific
constexpr stream_manipulator sycl::_V1::scientific = stream_manipulator::scientific constexpr
Definition at line 804 of file stream.hpp.
showbase
constexpr stream_manipulator sycl::_V1::showbase = stream_manipulator::showbase constexpr
Definition at line 792 of file stream.hpp.
showpos
constexpr stream_manipulator sycl::_V1::showpos = stream_manipulator::showpos constexpr
Definition at line 796 of file stream.hpp.
sinpi
return (x >= T(0)) ? T(std sycl::_V1::sinpi
Definition at line 110 of file math_functions.cpp.
smoothstep
sycl::_V1::smoothstep
Definition at line 54 of file common_functions.cpp.
t
return t *t ** sycl::_V1::t = sycl::clamp((z - x) / (y - x), T{0}, T{1})
Definition at line 57 of file common_functions.cpp.
Referenced by sycl::_V1::detail::force_type(), sycl::_V1::ext::intel::fpga_reg(), sycl::_V1::ext::oneapi::experimental::annotated_ref< T, detail::properties_t< Props... > >::operator++(), and sycl::_V1::ext::oneapi::experimental::annotated_ref< T, detail::properties_t< Props... > >::operator--().
write_only
constexpr mode_tag_t<access_mode::write> sycl::_V1::write_only {} inline constexpr
Definition at line 86 of file access.hpp.
write_only_host_task
constexpr mode_target_tag_t<access_mode::write, target::host_task> sycl::_V1::write_only_host_task inline constexpr
Definition at line 94 of file access.hpp.
x
auto sycl::_V1::x { return (M_PI / 180) * x
Definition at line 33 of file common_functions.cpp.
Referenced by sycl::_V1::detail::multiply_with_overflow_check(), sycl::_V1::sub_group::shuffle(), sycl::_V1::sub_group::shuffle_down(), sycl::_V1::sub_group::shuffle_up(), sycl::_V1::sub_group::shuffle_xor(), and sycl::_V1::sub_group::store().
y
auto auto sycl::_V1::y { return (y < x ? y : x)
Definition at line 47 of file common_functions.cpp.
Referenced by sycl::_V1::detail::multiply_with_overflow_check().
z
auto auto autodecltype(x) sycl::_V1::z
Initial value:
{
  return x + (y - x) * z
Definition at line 47 of file common_functions.cpp.