DPC++ Runtime: sycl::_V1::ext::intel::math Namespace Reference
sycl::_V1::ext::intel::math Namespace Reference
Functions
template<typename To = int, typename From = float>
To float2int_rd (From x)
template<typename To = int, typename From = float>
To float2int_rn (From x)
template<typename To = int, typename From = float>
To float2int_ru (From x)
template<typename To = int, typename From = float>
To float2int_rz (From x)
template<typename To = unsigned int, typename From = float>
To float2uint_rd (From x)
template<typename To = unsigned int, typename From = float>
To float2uint_rn (From x)
template<typename To = unsigned int, typename From = float>
To float2uint_ru (From x)
template<typename To = unsigned int, typename From = float>
To float2uint_rz (From x)
template<typename To = long long, typename From = float>
To float2ll_rd (From x)
template<typename To = long long, typename From = float>
To float2ll_rn (From x)
template<typename To = long long, typename From = float>
To float2ll_ru (From x)
template<typename To = long long, typename From = float>
To float2ll_rz (From x)
template<typename To = unsigned long long, typename From = float>
To float2ull_rd (From x)
template<typename To = unsigned long long, typename From = float>
To float2ull_rn (From x)
template<typename To = unsigned long long, typename From = float>
To float2ull_ru (From x)
template<typename To = unsigned long long, typename From = float>
To float2ull_rz (From x)
template<typename To = float, typename From = long long>
To ll2float_rd (From x)
template<typename To = float, typename From = long long>
To ll2float_rn (From x)
template<typename To = float, typename From = long long>
To ll2float_ru (From x)
template<typename To = float, typename From = long long>
To ll2float_rz (From x)
template<typename To = float, typename From = unsigned long long>
To ull2float_rd (From x)
template<typename To = float, typename From = unsigned long long>
To ull2float_rn (From x)
template<typename To = float, typename From = unsigned long long>
To ull2float_ru (From x)
template<typename To = float, typename From = unsigned long long>
To ull2float_rz (From x)
template<typename To = float, typename From = int>
To int2float_rd (From x)
template<typename To = float, typename From = int>
To int2float_rn (From x)
template<typename To = float, typename From = int>
To int2float_ru (From x)
template<typename To = float, typename From = int>
To int2float_rz (From x)
template<typename To = float, typename From = unsigned int>
To uint2float_rd (From x)
template<typename To = float, typename From = unsigned int>
To uint2float_rn (From x)
template<typename To = float, typename From = unsigned int>
To uint2float_ru (From x)
template<typename To = float, typename From = unsigned int>
To uint2float_rz (From x)
template<typename To = int, typename From = float>
To float_as_int (From x)
template<typename To = unsigned int, typename From = float>
To float_as_uint (From x)
template<typename To = float, typename From = int>
To int_as_float (From x)
template<typename To = float, typename From = unsigned int>
To uint_as_float (From x)
template<typename To = float, typename From = double>
To double2float_rd (From x)
template<typename To = float, typename From = double>
To double2float_rn (From x)
template<typename To = float, typename From = double>
To double2float_ru (From x)
template<typename To = float, typename From = double>
To double2float_rz (From x)
template<typename To = int, typename From = double>
To double2hiint (From x)
template<typename To = int, typename From = double>
To double2loint (From x)
template<typename To = int, typename From = double>
To double2int_rd (From x)
template<typename To = int, typename From = double>
To double2int_rn (From x)
template<typename To = int, typename From = double>
To double2int_ru (From x)
template<typename To = int, typename From = double>
To double2int_rz (From x)
template<typename To = long long, typename From = double>
To double2ll_rd (From x)
template<typename To = long long, typename From = double>
To double2ll_rn (From x)
template<typename To = long long, typename From = double>
To double2ll_ru (From x)
template<typename To = long long, typename From = double>
To double2ll_rz (From x)
template<typename To = unsigned int, typename From = double>
To double2uint_rd (From x)
template<typename To = unsigned int, typename From = double>
To double2uint_rn (From x)
template<typename To = unsigned int, typename From = double>
To double2uint_ru (From x)
template<typename To = unsigned int, typename From = double>
To double2uint_rz (From x)
template<typename To = unsigned long long, typename From = double>
To double2ull_rd (From x)
template<typename To = unsigned long long, typename From = double>
To double2ull_rn (From x)
template<typename To = unsigned long long, typename From = double>
To double2ull_ru (From x)
template<typename To = unsigned long long, typename From = double>
To double2ull_rz (From x)
template<typename To = long long, typename From = double>
To double_as_longlong (From x)
template<typename To = double, typename From = long long>
To longlong_as_double (From x)
template<typename To = double, typename From = int>
To hiloint2double (From x, From y)
template<typename To = double, typename From = int>
To int2double_rn (From x)
template<typename To = double, typename From = unsigned int>
To uint2double_rn (From x)
template<typename To = double, typename From = long long>
To ll2double_rd (From x)
template<typename To = double, typename From = long long>
To ll2double_rn (From x)
template<typename To = double, typename From = long long>
To ll2double_ru (From x)
template<typename To = double, typename From = long long>
To ll2double_rz (From x)
template<typename To = double, typename From = unsigned long long>
To ull2double_rd (From x)
template<typename To = double, typename From = unsigned long long>
To ull2double_rn (From x)
template<typename To = double, typename From = unsigned long long>
To ull2double_ru (From x)
template<typename To = double, typename From = unsigned long long>
To ull2double_rz (From x)
template<typename To = float, typename From = sycl::half>
To half2float (From x)
template<typename To = sycl::half, typename From = float>
To float2half_rn (From x)
template<typename To = sycl::half, typename From = float>
To float2half_rd (From x)
template<typename To = sycl::half, typename From = float>
To float2half_ru (From x)
template<typename To = sycl::half, typename From = float>
To float2half_rz (From x)
template<typename To = sycl::half, typename From = double>
To double2half (From x)
template<typename To = int, typename From = sycl::half>
To half2int_rn (From x)
template<typename To = int, typename From = sycl::half>
To half2int_rd (From x)
template<typename To = int, typename From = sycl::half>
To half2int_ru (From x)
template<typename To = int, typename From = sycl::half>
To half2int_rz (From x)
template<typename To = long long, typename From = sycl::half>
To half2ll_rn (From x)
template<typename To = long long, typename From = sycl::half>
To half2ll_rd (From x)
template<typename To = long long, typename From = sycl::half>
To half2ll_ru (From x)
template<typename To = long long, typename From = sycl::half>
To half2ll_rz (From x)
template<typename To = short, typename From = sycl::half>
To half2short_rn (From x)
template<typename To = short, typename From = sycl::half>
To half2short_rd (From x)
template<typename To = short, typename From = sycl::half>
To half2short_ru (From x)
template<typename To = short, typename From = sycl::half>
To half2short_rz (From x)
template<typename To = unsigned short, typename From = sycl::half>
To half2ushort_rn (From x)
template<typename To = unsigned short, typename From = sycl::half>
To half2ushort_rd (From x)
template<typename To = unsigned short, typename From = sycl::half>
To half2ushort_ru (From x)
template<typename To = unsigned short, typename From = sycl::half>
To half2ushort_rz (From x)
template<typename To = unsigned int, typename From = sycl::half>
To half2uint_rn (From x)
template<typename To = unsigned int, typename From = sycl::half>
To half2uint_rd (From x)
template<typename To = unsigned int, typename From = sycl::half>
To half2uint_ru (From x)
template<typename To = unsigned int, typename From = sycl::half>
To half2uint_rz (From x)
template<typename To = unsigned long long, typename From = sycl::half>
To half2ull_rn (From x)
template<typename To = unsigned long long, typename From = sycl::half>
To half2ull_rd (From x)
template<typename To = unsigned long long, typename From = sycl::half>
To half2ull_ru (From x)
template<typename To = unsigned long long, typename From = sycl::half>
To half2ull_rz (From x)
template<typename To = sycl::half, typename From = int>
To int2half_rn (From x)
template<typename To = sycl::half, typename From = int>
To int2half_rd (From x)
template<typename To = sycl::half, typename From = int>
To int2half_ru (From x)
template<typename To = sycl::half, typename From = int>
To int2half_rz (From x)
template<typename To = sycl::half, typename From = short>
To short2half_rn (From x)
template<typename To = sycl::half, typename From = short>
To short2half_rd (From x)
template<typename To = sycl::half, typename From = short>
To short2half_ru (From x)
template<typename To = sycl::half, typename From = short>
To short2half_rz (From x)
template<typename To = sycl::half, typename From = long long>
To ll2half_rn (From x)
template<typename To = sycl::half, typename From = long long>
To ll2half_rd (From x)
template<typename To = sycl::half, typename From = long long>
To ll2half_ru (From x)
template<typename To = sycl::half, typename From = long long>
To ll2half_rz (From x)
template<typename To = sycl::half, typename From = unsigned short>
To ushort2half_rn (From x)
template<typename To = sycl::half, typename From = unsigned short>
To ushort2half_rd (From x)
template<typename To = sycl::half, typename From = unsigned short>
To ushort2half_ru (From x)
template<typename To = sycl::half, typename From = unsigned short>
To ushort2half_rz (From x)
template<typename To = sycl::half, typename From = unsigned int>
To uint2half_rn (From x)
template<typename To = sycl::half, typename From = unsigned int>
To uint2half_rd (From x)
template<typename To = sycl::half, typename From = unsigned int>
To uint2half_ru (From x)
template<typename To = sycl::half, typename From = unsigned int>
To uint2half_rz (From x)
template<typename To = sycl::half, typename From = unsigned long long>
To ull2half_rn (From x)
template<typename To = sycl::half, typename From = unsigned long long>
To ull2half_rd (From x)
template<typename To = sycl::half, typename From = unsigned long long>
To ull2half_ru (From x)
template<typename To = sycl::half, typename From = unsigned long long>
To ull2half_rz (From x)
template<typename To = unsigned short, typename From = sycl::ext::oneapi::bfloat16>
To bfloat16_as_ushort (From x)
template<typename To = short, typename From = sycl::ext::oneapi::bfloat16>
To bfloat16_as_short (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned short>
To ushort_as_bfloat16 (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = short>
To short_as_bfloat16 (From x)
template<typename To = float, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162float (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = float>
To float2bfloat16 (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = float>
To float2bfloat16_rd (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = float>
To float2bfloat16_rn (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = float>
To float2bfloat16_ru (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = float>
To float2bfloat16_rz (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned short>
To ushort2bfloat16_rd (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned short>
To ushort2bfloat16_rn (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned short>
To ushort2bfloat16_ru (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned short>
To ushort2bfloat16_rz (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned int>
To uint2bfloat16_rd (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned int>
To uint2bfloat16_rn (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned int>
To uint2bfloat16_ru (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned int>
To uint2bfloat16_rz (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned long long>
To ull2bfloat16_rd (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned long long>
To ull2bfloat16_rn (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned long long>
To ull2bfloat16_ru (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned long long>
To ull2bfloat16_rz (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = short>
To short2bfloat16_rd (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = short>
To short2bfloat16_rn (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = short>
To short2bfloat16_ru (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = short>
To short2bfloat16_rz (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = int>
To int2bfloat16_rd (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = int>
To int2bfloat16_rn (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = int>
To int2bfloat16_ru (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = int>
To int2bfloat16_rz (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = long long>
To ll2bfloat16_rd (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = long long>
To ll2bfloat16_rn (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = long long>
To ll2bfloat16_ru (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = long long>
To ll2bfloat16_rz (From x)
template<typename To = sycl::ext::oneapi::bfloat16, typename From = double>
To double2bfloat16 (From x)
template<typename To = unsigned int, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162uint_rd (From x)
template<typename To = unsigned int, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162uint_rn (From x)
template<typename To = unsigned int, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162uint_ru (From x)
template<typename To = unsigned int, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162uint_rz (From x)
template<typename To = int, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162int_rd (From x)
template<typename To = int, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162int_rn (From x)
template<typename To = int, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162int_ru (From x)
template<typename To = int, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162int_rz (From x)
template<typename To = unsigned short, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162ushort_rd (From x)
template<typename To = unsigned short, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162ushort_rn (From x)
template<typename To = unsigned short, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162ushort_ru (From x)
template<typename To = unsigned short, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162ushort_rz (From x)
template<typename To = short, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162short_rd (From x)
template<typename To = short, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162short_rn (From x)
template<typename To = short, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162short_ru (From x)
template<typename To = short, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162short_rz (From x)
template<typename To = long long, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162ll_rd (From x)
template<typename To = long long, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162ll_rn (From x)
template<typename To = long long, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162ll_ru (From x)
template<typename To = long long, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162ll_rz (From x)
template<typename To = unsigned long long, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162ull_rd (From x)
template<typename To = unsigned long long, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162ull_rn (From x)
template<typename To = unsigned long long, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162ull_ru (From x)
template<typename To = unsigned long long, typename From = sycl::ext::oneapi::bfloat16>
To bfloat162ull_rz (From x)
sycl::half hadd (sycl::half x, sycl::half y)
sycl::half hadd_sat (sycl::half x, sycl::half y)
sycl::half hfma (sycl::half x, sycl::half y, sycl::half z)
sycl::half hfma_sat (sycl::half x, sycl::half y, sycl::half z)
sycl::half hmul (sycl::half x, sycl::half y)
sycl::half hmul_sat (sycl::half x, sycl::half y)
sycl::half hneg (sycl::half x)
sycl::half hsub (sycl::half x, sycl::half y)
sycl::half hsub_sat (sycl::half x, sycl::half y)
sycl::half hdiv (sycl::half x, sycl::half y)
bool heq (sycl::half x, sycl::half y)
bool hequ (sycl::half x, sycl::half y)
bool hge (sycl::half x, sycl::half y)
bool hgeu (sycl::half x, sycl::half y)
bool hgt (sycl::half x, sycl::half y)
bool hgtu (sycl::half x, sycl::half y)
bool hle (sycl::half x, sycl::half y)
bool hleu (sycl::half x, sycl::half y)
bool hlt (sycl::half x, sycl::half y)
bool hltu (sycl::half x, sycl::half y)
bool hne (sycl::half x, sycl::half y)
bool hneu (sycl::half x, sycl::half y)
bool hisinf (sycl::half x)
bool hisnan (sycl::half y)
sycl::half2 hadd2 (sycl::half2 x, sycl::half2 y)
sycl::half2 hadd2_sat (sycl::half2 x, sycl::half2 y)
sycl::half2 hfma2 (sycl::half2 x, sycl::half2 y, sycl::half2 z)
sycl::half2 hfma2_sat (sycl::half2 x, sycl::half2 y, sycl::half2 z)
sycl::half2 hmul2 (sycl::half2 x, sycl::half2 y)
sycl::half2 hmul2_sat (sycl::half2 x, sycl::half2 y)
sycl::half2 h2div (sycl::half2 x, sycl::half2 y)
sycl::half2 hneg2 (sycl::half2 x)
sycl::half2 hsub2 (sycl::half2 x, sycl::half2 y)
sycl::half2 hsub2_sat (sycl::half2 x, sycl::half2 y)
bool hbeq2 (sycl::half2 x, sycl::half2 y)
bool hbequ2 (sycl::half2 x, sycl::half2 y)
bool hbge2 (sycl::half2 x, sycl::half2 y)
bool hbgeu2 (sycl::half2 x, sycl::half2 y)
bool hbgt2 (sycl::half2 x, sycl::half2 y)
bool hbgtu2 (sycl::half2 x, sycl::half2 y)
bool hble2 (sycl::half2 x, sycl::half2 y)
bool hbleu2 (sycl::half2 x, sycl::half2 y)
bool hblt2 (sycl::half2 x, sycl::half2 y)
bool hbltu2 (sycl::half2 x, sycl::half2 y)
bool hbne2 (sycl::half2 x, sycl::half2 y)
bool hbneu2 (sycl::half2 x, sycl::half2 y)
sycl::half2 heq2 (sycl::half2 x, sycl::half2 y)
sycl::half2 hequ2 (sycl::half2 x, sycl::half2 y)
sycl::half2 hge2 (sycl::half2 x, sycl::half2 y)
sycl::half2 hgeu2 (sycl::half2 x, sycl::half2 y)
sycl::half2 hgt2 (sycl::half2 x, sycl::half2 y)
sycl::half2 hgtu2 (sycl::half2 x, sycl::half2 y)
sycl::half2 hle2 (sycl::half2 x, sycl::half2 y)
sycl::half2 hleu2 (sycl::half2 x, sycl::half2 y)
sycl::half2 hlt2 (sycl::half2 x, sycl::half2 y)
sycl::half2 hltu2 (sycl::half2 x, sycl::half2 y)
sycl::half2 hisnan2 (sycl::half2 x)
sycl::half2 hne2 (sycl::half2 x, sycl::half2 y)
sycl::half2 hneu2 (sycl::half2 x, sycl::half2 y)
sycl::half hmax (sycl::half x, sycl::half y)
sycl::half hmax_nan (sycl::half x, sycl::half y)
sycl::half2 hmax2 (sycl::half2 x, sycl::half2 y)
sycl::half2 hmax2_nan (sycl::half2 x, sycl::half2 y)
sycl::half hmin (sycl::half x, sycl::half y)
sycl::half hmin_nan (sycl::half x, sycl::half y)
sycl::half2 hmin2 (sycl::half2 x, sycl::half2 y)
sycl::half2 hmin2_nan (sycl::half2 x, sycl::half2 y)
sycl::half2 hcmadd (sycl::half2 x, sycl::half2 y, sycl::half2 z)
sycl::half hfma_relu (sycl::half x, sycl::half y, sycl::half z)
sycl::half2 hfma2_relu (sycl::half2 x, sycl::half2 y, sycl::half2 z)
sycl::half habs (sycl::half x)
sycl::half2 habs2 (sycl::half2 x)
template<typename Tp = unsigned>
unsigned brev (Tp x)
template<typename Tp = unsigned long long>
unsigned long long brevll (Tp x)
template<typename Tp = unsigned>
unsigned byte_perm (Tp x, Tp y, Tp z)
template<typename Tp = int>
int max (Tp x, Tp y)
template<typename Tp = int>
int min (Tp x, Tp y)
template<typename Tp = unsigned>
unsigned umax (Tp x, Tp y)
template<typename Tp = unsigned>
unsigned umin (Tp x, Tp y)
template<typename Tp = long long>
long long llmax (Tp x, Tp y)
template<typename Tp = long long>
long long llmin (Tp x, Tp y)
template<typename Tp = unsigned long long>
unsigned long long ullmax (Tp x, Tp y)
template<typename Tp = unsigned long long>
unsigned long long ullmin (Tp x, Tp y)
template<typename Tp = int>
int clz (Tp x)
template<typename Tp = long long>
int clzll (Tp x)
template<typename Tp = int>
int ffs (Tp x)
template<typename Tp = long long>
int ffsll (Tp x)
template<typename Tp = int>
int hadd (Tp x, Tp y)
template<typename Tp = int>
int rhadd (Tp x, Tp y)
template<typename Tp = unsigned>
unsigned urhadd (Tp x, Tp y)
template<typename Tp = int>
int mul24 (Tp x, Tp y)
template<typename Tp = unsigned>
unsigned umul24 (Tp x, Tp y)
template<typename Tp = int>
int mulhi (Tp x, Tp y)
template<typename Tp = unsigned>
unsigned umulhi (Tp x, Tp y)
template<typename Tp = long long>
long long mul64hi (Tp x, Tp y)
template<typename Tp = unsigned long long>
unsigned long long umul64hi (Tp x, Tp y)
template<typename Tp = unsigned>
int popc (Tp x)
template<typename Tp = unsigned long long>
int popcll (Tp x)
template<typename Tp1 = int, typename Tp2 = unsigned>
unsigned sad (Tp1 x, Tp1 y, Tp2 z)
template<typename Tp = unsigned>
unsigned usad (Tp x, Tp y, Tp z)
template<typename Tp = unsigned>
unsigned uhadd (Tp x, Tp y)
template<typename Tp = float>
Tp fadd_rd (Tp x, Tp y)
template<typename Tp = float>
Tp fadd_rn (Tp x, Tp y)
template<typename Tp = float>
Tp fadd_ru (Tp x, Tp y)
template<typename Tp = float>
Tp fadd_rz (Tp x, Tp y)
template<typename Tp = float>
Tp fsub_rd (Tp x, Tp y)
template<typename Tp = float>
Tp fsub_rn (Tp x, Tp y)
template<typename Tp = float>
Tp fsub_ru (Tp x, Tp y)
template<typename Tp = float>
Tp fsub_rz (Tp x, Tp y)
template<typename Tp = float>
Tp fmul_rd (Tp x, Tp y)
template<typename Tp = float>
Tp fmul_rn (Tp x, Tp y)
template<typename Tp = float>
Tp fmul_ru (Tp x, Tp y)
template<typename Tp = float>
Tp fmul_rz (Tp x, Tp y)
template<typename Tp = float>
Tp fdiv_rd (Tp x, Tp y)
template<typename Tp = float>
Tp fdiv_rn (Tp x, Tp y)
template<typename Tp = float>
Tp fdiv_ru (Tp x, Tp y)
template<typename Tp = float>
Tp fdiv_rz (Tp x, Tp y)
template<typename Tp = float>
Tp frcp_rd (Tp x)
template<typename Tp = float>
Tp frcp_rn (Tp x)
template<typename Tp = float>
Tp frcp_ru (Tp x)
template<typename Tp = float>
Tp frcp_rz (Tp x)
template<typename Tp = float>
Tp fmaf_rd (Tp x, Tp y, Tp z)
template<typename Tp = float>
Tp fmaf_rn (Tp x, Tp y, Tp z)
template<typename Tp = float>
Tp fmaf_ru (Tp x, Tp y, Tp z)
template<typename Tp = float>
Tp fmaf_rz (Tp x, Tp y, Tp z)
template<typename Tp = float>
Tp fsqrt_rd (Tp x)
template<typename Tp = float>
Tp fsqrt_rn (Tp x)
template<typename Tp = float>
Tp fsqrt_ru (Tp x)
template<typename Tp = float>
Tp fsqrt_rz (Tp x)
template<typename Tp = double>
Tp dadd_rd (Tp x, Tp y)
template<typename Tp = double>
Tp dadd_rn (Tp x, Tp y)
template<typename Tp = double>
Tp dadd_ru (Tp x, Tp y)
template<typename Tp = double>
Tp dadd_rz (Tp x, Tp y)
template<typename Tp = double>
Tp dsub_rd (Tp x, Tp y)
template<typename Tp = double>
Tp dsub_rn (Tp x, Tp y)
template<typename Tp = double>
Tp dsub_ru (Tp x, Tp y)
template<typename Tp = double>
Tp dsub_rz (Tp x, Tp y)
template<typename Tp = double>
Tp dmul_rd (Tp x, Tp y)
template<typename Tp = double>
Tp dmul_rn (Tp x, Tp y)
template<typename Tp = double>
Tp dmul_ru (Tp x, Tp y)
template<typename Tp = double>
Tp dmul_rz (Tp x, Tp y)
template<typename Tp = double>
Tp ddiv_rd (Tp x, Tp y)
template<typename Tp = double>
Tp ddiv_rn (Tp x, Tp y)
template<typename Tp = double>
Tp ddiv_ru (Tp x, Tp y)
template<typename Tp = double>
Tp ddiv_rz (Tp x, Tp y)
template<typename Tp = double>
Tp drcp_rd (Tp x)
template<typename Tp = double>
Tp drcp_rn (Tp x)
template<typename Tp = double>
Tp drcp_ru (Tp x)
template<typename Tp = double>
Tp drcp_rz (Tp x)
template<typename Tp = double>
Tp fma_rd (Tp x, Tp y, Tp z)
template<typename Tp = double>
Tp fma_rn (Tp x, Tp y, Tp z)
template<typename Tp = double>
Tp fma_ru (Tp x, Tp y, Tp z)
template<typename Tp = double>
Tp fma_rz (Tp x, Tp y, Tp z)
template<typename Tp = double>
Tp dsqrt_rd (Tp x)
template<typename Tp = double>
Tp dsqrt_rn (Tp x)
template<typename Tp = double>
Tp dsqrt_ru (Tp x)
template<typename Tp = double>
Tp dsqrt_rz (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vabs2 (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vabs4 (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vneg2 (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vneg4 (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vnegss2 (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vnegss4 (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vabsdiffs2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vabsdiffs4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vabsdiffu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vabsdiffu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vabsss2 (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vabsss4 (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vadd2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vadd4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vaddss2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vaddss4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vaddus2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vaddus4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsub2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsub4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsubss2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsubss4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsubus2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsubus4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vhaddu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vhaddu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vavgs2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vavgs4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vavgu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vavgu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vcmpeq2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vcmpeq4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vcmpges2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vcmpges4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vcmpgeu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vcmpgeu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vcmpgts2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vcmpgts4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vcmpgtu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vcmpgtu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vcmples2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vcmples4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vcmpleu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vcmpleu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vcmplts2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vcmplts4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vcmpltu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vcmpltu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vcmpne2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vcmpne4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vmaxs2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vmaxs4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vmaxu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vmaxu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vmins2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vmins4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vminu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vminu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vseteq2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vseteq4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsetne2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsetne4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsetges2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsetges4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsetgeu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsetgeu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsetgts2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsetgts4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsetgtu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsetgtu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsetles2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsetles4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsetleu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsetleu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsetlts2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsetlts4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsetltu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsetltu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsads2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsads4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsadu2 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vsadu4 (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > viaddmax_s16x2 (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > viaddmax_s16x2_relu (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, int >, int > viaddmax_s32 (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, int >, int > viaddmax_s32_relu (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > viaddmax_u16x2 (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > viaddmax_u32 (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > viaddmin_s16x2 (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > viaddmin_s16x2_relu (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, int >, int > viaddmin_s32 (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, int >, int > viaddmin_s32_relu (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > viaddmin_u16x2 (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > viaddmin_u32 (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vibmax_s16x2 (Tp x, Tp y, bool *p_hi, bool *p_lo)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, int >, int > vibmax_s32 (Tp x, Tp y, bool *p)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vibmax_u16x2 (Tp x, Tp y, bool *p_hi, bool *p_lo)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vibmax_u32 (Tp x, Tp y, bool *p)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vibmin_s16x2 (Tp x, Tp y, bool *p_hi, bool *p_lo)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, int >, int > vibmin_s32 (Tp x, Tp y, bool *p)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vibmin_u16x2 (Tp x, Tp y, bool *p_hi, bool *p_lo)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vibmin_u32 (Tp x, Tp y, bool *p)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vimax3_s16x2 (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vimin3_s16x2 (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vimax3_s16x2_relu (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vimin3_s16x2_relu (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, int >, int > vimax3_s32 (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, int >, int > vimin3_s32 (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, int >, int > vimax3_s32_relu (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, int >, int > vimin3_s32_relu (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vimax3_u16x2 (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vimin3_u16x2 (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vimax3_u32 (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vimin3_u32 (Tp x, Tp y, Tp z)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, int >, int > vimax_s32_relu (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vimax_s16x2_relu (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, int >, int > vimin_s32_relu (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, unsigned int >, unsigned int > vimin_s16x2_relu (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, float >, float > saturate (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, float >, float > copysign (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, double >, double > copysign (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half >, sycl::half > copysign (Tp x, Tp y)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, float >, float > ceil (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, double >, double > ceil (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half >, sycl::half > ceil (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half2 >, sycl::half2 > ceil (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, float >, float > floor (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, double >, double > floor (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half >, sycl::half > floor (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half2 >, sycl::half2 > floor (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, float >, float > inv (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, double >, double > inv (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half >, sycl::half > inv (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half2 >, sycl::half2 > inv (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, float >, float > rint (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, double >, double > rint (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half >, sycl::half > rint (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half2 >, sycl::half2 > rint (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, float >, float > sqrt (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, double >, double > sqrt (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half >, sycl::half > sqrt (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half2 >, sycl::half2 > sqrt (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, float >, float > rsqrt (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, double >, double > rsqrt (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half >, sycl::half > rsqrt (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half2 >, sycl::half2 > rsqrt (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, float >, float > trunc (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, double >, double > trunc (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half >, sycl::half > trunc (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, sycl::half2 >, sycl::half2 > trunc (Tp x)
template<typename Tp >
std::enable_if_t< std::is_same_v< Tp, double >, double > rcp64h (Tp x)
Function Documentation
bfloat162float()
template<typename To = float, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162float (From x)
Definition at line 846 of file imf_fp_conversions.hpp.
References __imf_bfloat162float().
bfloat162int_rd()
template<typename To = int, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162int_rd (From x)
Definition at line 1050 of file imf_fp_conversions.hpp.
References __imf_bfloat162int_rd().
bfloat162int_rn()
template<typename To = int, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162int_rn (From x)
Definition at line 1055 of file imf_fp_conversions.hpp.
References __imf_bfloat162int_rn().
bfloat162int_ru()
template<typename To = int, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162int_ru (From x)
Definition at line 1060 of file imf_fp_conversions.hpp.
References __imf_bfloat162int_ru().
bfloat162int_rz()
template<typename To = int, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162int_rz (From x)
Definition at line 1065 of file imf_fp_conversions.hpp.
References __imf_bfloat162int_rz().
bfloat162ll_rd()
template<typename To = long long, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162ll_rd (From x)
Definition at line 1114 of file imf_fp_conversions.hpp.
References __imf_bfloat162ll_rd().
bfloat162ll_rn()
template<typename To = long long, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162ll_rn (From x)
Definition at line 1119 of file imf_fp_conversions.hpp.
References __imf_bfloat162ll_rn().
bfloat162ll_ru()
template<typename To = long long, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162ll_ru (From x)
Definition at line 1124 of file imf_fp_conversions.hpp.
References __imf_bfloat162ll_ru().
bfloat162ll_rz()
template<typename To = long long, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162ll_rz (From x)
Definition at line 1129 of file imf_fp_conversions.hpp.
References __imf_bfloat162ll_rz().
bfloat162short_rd()
template<typename To = short, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162short_rd (From x)
Definition at line 1094 of file imf_fp_conversions.hpp.
References __imf_bfloat162short_rd().
bfloat162short_rn()
template<typename To = short, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162short_rn (From x)
Definition at line 1099 of file imf_fp_conversions.hpp.
References __imf_bfloat162short_rn().
bfloat162short_ru()
template<typename To = short, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162short_ru (From x)
Definition at line 1104 of file imf_fp_conversions.hpp.
References __imf_bfloat162short_ru().
bfloat162short_rz()
template<typename To = short, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162short_rz (From x)
Definition at line 1109 of file imf_fp_conversions.hpp.
References __imf_bfloat162short_rz().
bfloat162uint_rd()
template<typename To = unsigned int, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162uint_rd (From x)
Definition at line 1027 of file imf_fp_conversions.hpp.
References __imf_bfloat162uint_rd().
bfloat162uint_rn()
template<typename To = unsigned int, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162uint_rn (From x)
Definition at line 1033 of file imf_fp_conversions.hpp.
References __imf_bfloat162uint_rn().
bfloat162uint_ru()
template<typename To = unsigned int, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162uint_ru (From x)
Definition at line 1039 of file imf_fp_conversions.hpp.
References __imf_bfloat162uint_ru().
bfloat162uint_rz()
template<typename To = unsigned int, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162uint_rz (From x)
Definition at line 1045 of file imf_fp_conversions.hpp.
References __imf_bfloat162uint_rz().
bfloat162ull_rd()
template<typename To = unsigned long long, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162ull_rd (From x)
Definition at line 1135 of file imf_fp_conversions.hpp.
References __imf_bfloat162ull_rd().
bfloat162ull_rn()
template<typename To = unsigned long long, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162ull_rn (From x)
Definition at line 1141 of file imf_fp_conversions.hpp.
References __imf_bfloat162ull_rn().
bfloat162ull_ru()
template<typename To = unsigned long long, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162ull_ru (From x)
Definition at line 1147 of file imf_fp_conversions.hpp.
References __imf_bfloat162ull_ru().
bfloat162ull_rz()
template<typename To = unsigned long long, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162ull_rz (From x)
Definition at line 1153 of file imf_fp_conversions.hpp.
References __imf_bfloat162ull_rz().
bfloat162ushort_rd()
template<typename To = unsigned short, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162ushort_rd (From x)
Definition at line 1071 of file imf_fp_conversions.hpp.
References __imf_bfloat162ushort_rd().
bfloat162ushort_rn()
template<typename To = unsigned short, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162ushort_rn (From x)
Definition at line 1077 of file imf_fp_conversions.hpp.
References __imf_bfloat162ushort_rn().
bfloat162ushort_ru()
template<typename To = unsigned short, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162ushort_ru (From x)
Definition at line 1083 of file imf_fp_conversions.hpp.
References __imf_bfloat162ushort_ru().
bfloat162ushort_rz()
template<typename To = unsigned short, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat162ushort_rz (From x)
Definition at line 1089 of file imf_fp_conversions.hpp.
References __imf_bfloat162ushort_rz().
bfloat16_as_short()
template<typename To = short, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat16_as_short (From x)
Definition at line 828 of file imf_fp_conversions.hpp.
References __imf_bfloat16_as_short().
bfloat16_as_ushort()
template<typename To = unsigned short, typename From = sycl::ext::oneapi::bfloat16> To sycl::_V1::ext::intel::math::bfloat16_as_ushort (From x)
Definition at line 823 of file imf_fp_conversions.hpp.
References __imf_bfloat16_as_ushort().
brev()
template<typename Tp = unsigned> unsigned sycl::_V1::ext::intel::math::brev (Tp x)
Definition at line 49 of file imf_integer_utils.hpp.
References __imf_brev().
brevll()
template<typename Tp = unsigned long long> unsigned long long sycl::_V1::ext::intel::math::brevll (Tp x)
Definition at line 51 of file imf_integer_utils.hpp.
References __imf_brevll().
byte_perm()
template<typename Tp = unsigned> unsigned sycl::_V1::ext::intel::math::byte_perm (Tp x, Tp y, Tp z)
Definition at line 55 of file imf_integer_utils.hpp.
References __imf_byte_perm().
ceil() [1/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, float>, float> sycl::_V1::ext::intel::math::ceil (Tp x)
Definition at line 95 of file math.hpp.
References __imf_ceilf().
Referenced by ceil().
ceil() [2/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, double>, double> sycl::_V1::ext::intel::math::ceil (Tp x)
Definition at line 100 of file math.hpp.
References __imf_ceil().
ceil() [3/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, sycl::half>, sycl::half> sycl::_V1::ext::intel::math::ceil (Tp x)
Definition at line 105 of file math.hpp.
References __imf_ceilf16().
ceil() [4/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, sycl::half2>, sycl::half2> sycl::_V1::ext::intel::math::ceil (Tp x)
Definition at line 111 of file math.hpp.
References ceil().
clz()
template<typename Tp = int> int sycl::_V1::ext::intel::math::clz (Tp x)
Definition at line 89 of file imf_integer_utils.hpp.
References __imf_clz().
clzll()
template<typename Tp = long long> int sycl::_V1::ext::intel::math::clzll (Tp x)
Definition at line 91 of file imf_integer_utils.hpp.
References __imf_clzll().
copysign() [1/3]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, float>, float> sycl::_V1::ext::intel::math::copysign (Tp x, Tp y)
Definition at line 77 of file math.hpp.
References __imf_copysignf().
Referenced by sycl::_V1::ext::oneapi::experimental::acosh(), sycl::_V1::ext::oneapi::experimental::asinh(), sycl::_V1::ext::oneapi::experimental::atanh(), sycl::_V1::ext::oneapi::experimental::exp(), sycl::_V1::ext::oneapi::experimental::proj(), sycl::_V1::ext::oneapi::experimental::sqrt(), and sycl::_V1::ext::oneapi::experimental::tanh().
copysign() [2/3]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, double>, double> sycl::_V1::ext::intel::math::copysign (Tp x, Tp y)
Definition at line 82 of file math.hpp.
References __imf_copysign().
copysign() [3/3]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, sycl::half>, sycl::half> sycl::_V1::ext::intel::math::copysign (Tp x, Tp y)
Definition at line 87 of file math.hpp.
References __imf_copysignf16().
dadd_rd()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::dadd_rd (Tp x, Tp y)
Definition at line 173 of file imf_rounding_math.hpp.
References __imf_dadd_rd().
dadd_rn()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::dadd_rn (Tp x, Tp y)
Definition at line 177 of file imf_rounding_math.hpp.
References __imf_dadd_rn().
dadd_ru()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::dadd_ru (Tp x, Tp y)
Definition at line 181 of file imf_rounding_math.hpp.
References __imf_dadd_ru().
dadd_rz()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::dadd_rz (Tp x, Tp y)
Definition at line 185 of file imf_rounding_math.hpp.
References __imf_dadd_rz().
ddiv_rd()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::ddiv_rd (Tp x, Tp y)
Definition at line 221 of file imf_rounding_math.hpp.
References __imf_ddiv_rd().
ddiv_rn()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::ddiv_rn (Tp x, Tp y)
Definition at line 225 of file imf_rounding_math.hpp.
References __imf_ddiv_rn().
ddiv_ru()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::ddiv_ru (Tp x, Tp y)
Definition at line 229 of file imf_rounding_math.hpp.
References __imf_ddiv_ru().
ddiv_rz()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::ddiv_rz (Tp x, Tp y)
Definition at line 233 of file imf_rounding_math.hpp.
References __imf_ddiv_rz().
dmul_rd()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::dmul_rd (Tp x, Tp y)
Definition at line 205 of file imf_rounding_math.hpp.
References __imf_dmul_rd().
dmul_rn()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::dmul_rn (Tp x, Tp y)
Definition at line 209 of file imf_rounding_math.hpp.
References __imf_dmul_rn().
dmul_ru()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::dmul_ru (Tp x, Tp y)
Definition at line 213 of file imf_rounding_math.hpp.
References __imf_dmul_ru().
dmul_rz()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::dmul_rz (Tp x, Tp y)
Definition at line 217 of file imf_rounding_math.hpp.
References __imf_dmul_rz().
double2bfloat16()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = double> To sycl::_V1::ext::intel::math::double2bfloat16 (From x)
Definition at line 1021 of file imf_fp_conversions.hpp.
References __imf_double2bfloat16().
double2float_rd()
template<typename To = float, typename From = double> To sycl::_V1::ext::intel::math::double2float_rd (From x)
Definition at line 384 of file imf_fp_conversions.hpp.
References __imf_double2float_rd().
double2float_rn()
template<typename To = float, typename From = double> To sycl::_V1::ext::intel::math::double2float_rn (From x)
Definition at line 389 of file imf_fp_conversions.hpp.
References __imf_double2float_rn().
double2float_ru()
template<typename To = float, typename From = double> To sycl::_V1::ext::intel::math::double2float_ru (From x)
Definition at line 394 of file imf_fp_conversions.hpp.
References __imf_double2float_ru().
double2float_rz()
template<typename To = float, typename From = double> To sycl::_V1::ext::intel::math::double2float_rz (From x)
Definition at line 399 of file imf_fp_conversions.hpp.
References __imf_double2float_rz().
double2half()
template<typename To = sycl::half, typename From = double> To sycl::_V1::ext::intel::math::double2half (From x)
Definition at line 577 of file imf_fp_conversions.hpp.
References __imf_double2half().
double2hiint()
template<typename To = int, typename From = double> To sycl::_V1::ext::intel::math::double2hiint (From x)
Definition at line 403 of file imf_fp_conversions.hpp.
References __imf_double2hiint().
double2int_rd()
template<typename To = int, typename From = double> To sycl::_V1::ext::intel::math::double2int_rd (From x)
Definition at line 411 of file imf_fp_conversions.hpp.
References __imf_double2int_rd().
double2int_rn()
template<typename To = int, typename From = double> To sycl::_V1::ext::intel::math::double2int_rn (From x)
Definition at line 415 of file imf_fp_conversions.hpp.
References __imf_double2int_rn().
double2int_ru()
template<typename To = int, typename From = double> To sycl::_V1::ext::intel::math::double2int_ru (From x)
Definition at line 419 of file imf_fp_conversions.hpp.
References __imf_double2int_ru().
double2int_rz()
template<typename To = int, typename From = double> To sycl::_V1::ext::intel::math::double2int_rz (From x)
Definition at line 423 of file imf_fp_conversions.hpp.
References __imf_double2int_rz().
double2ll_rd()
template<typename To = long long, typename From = double> To sycl::_V1::ext::intel::math::double2ll_rd (From x)
Definition at line 428 of file imf_fp_conversions.hpp.
References __imf_double2ll_rd().
double2ll_rn()
template<typename To = long long, typename From = double> To sycl::_V1::ext::intel::math::double2ll_rn (From x)
Definition at line 433 of file imf_fp_conversions.hpp.
References __imf_double2ll_rn().
double2ll_ru()
template<typename To = long long, typename From = double> To sycl::_V1::ext::intel::math::double2ll_ru (From x)
Definition at line 438 of file imf_fp_conversions.hpp.
References __imf_double2ll_ru().
double2ll_rz()
template<typename To = long long, typename From = double> To sycl::_V1::ext::intel::math::double2ll_rz (From x)
Definition at line 443 of file imf_fp_conversions.hpp.
References __imf_double2ll_rz().
double2loint()
template<typename To = int, typename From = double> To sycl::_V1::ext::intel::math::double2loint (From x)
Definition at line 407 of file imf_fp_conversions.hpp.
References __imf_double2loint().
double2uint_rd()
template<typename To = unsigned int, typename From = double> To sycl::_V1::ext::intel::math::double2uint_rd (From x)
Definition at line 448 of file imf_fp_conversions.hpp.
References __imf_double2uint_rd().
double2uint_rn()
template<typename To = unsigned int, typename From = double> To sycl::_V1::ext::intel::math::double2uint_rn (From x)
Definition at line 453 of file imf_fp_conversions.hpp.
References __imf_double2uint_rn().
double2uint_ru()
template<typename To = unsigned int, typename From = double> To sycl::_V1::ext::intel::math::double2uint_ru (From x)
Definition at line 458 of file imf_fp_conversions.hpp.
References __imf_double2uint_ru().
double2uint_rz()
template<typename To = unsigned int, typename From = double> To sycl::_V1::ext::intel::math::double2uint_rz (From x)
Definition at line 463 of file imf_fp_conversions.hpp.
References __imf_double2uint_rz().
double2ull_rd()
template<typename To = unsigned long long, typename From = double> To sycl::_V1::ext::intel::math::double2ull_rd (From x)
Definition at line 468 of file imf_fp_conversions.hpp.
References __imf_double2ull_rd().
double2ull_rn()
template<typename To = unsigned long long, typename From = double> To sycl::_V1::ext::intel::math::double2ull_rn (From x)
Definition at line 473 of file imf_fp_conversions.hpp.
References __imf_double2ull_rn().
double2ull_ru()
template<typename To = unsigned long long, typename From = double> To sycl::_V1::ext::intel::math::double2ull_ru (From x)
Definition at line 478 of file imf_fp_conversions.hpp.
References __imf_double2ull_ru().
double2ull_rz()
template<typename To = unsigned long long, typename From = double> To sycl::_V1::ext::intel::math::double2ull_rz (From x)
Definition at line 483 of file imf_fp_conversions.hpp.
References __imf_double2ull_rz().
double_as_longlong()
template<typename To = long long, typename From = double> To sycl::_V1::ext::intel::math::double_as_longlong (From x)
Definition at line 488 of file imf_fp_conversions.hpp.
References __imf_double_as_longlong().
drcp_rd()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::drcp_rd (Tp x)
Definition at line 237 of file imf_rounding_math.hpp.
References __imf_drcp_rd().
drcp_rn()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::drcp_rn (Tp x)
Definition at line 239 of file imf_rounding_math.hpp.
References __imf_drcp_rn().
drcp_ru()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::drcp_ru (Tp x)
Definition at line 241 of file imf_rounding_math.hpp.
References __imf_drcp_ru().
drcp_rz()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::drcp_rz (Tp x)
Definition at line 243 of file imf_rounding_math.hpp.
References __imf_drcp_rz().
dsqrt_rd()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::dsqrt_rd (Tp x)
Definition at line 261 of file imf_rounding_math.hpp.
References __imf_sqrt_rd().
dsqrt_rn()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::dsqrt_rn (Tp x)
Definition at line 263 of file imf_rounding_math.hpp.
References __imf_sqrt_rn().
dsqrt_ru()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::dsqrt_ru (Tp x)
Definition at line 265 of file imf_rounding_math.hpp.
References __imf_sqrt_ru().
dsqrt_rz()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::dsqrt_rz (Tp x)
Definition at line 267 of file imf_rounding_math.hpp.
References __imf_sqrt_rz().
dsub_rd()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::dsub_rd (Tp x, Tp y)
Definition at line 189 of file imf_rounding_math.hpp.
References __imf_dsub_rd().
dsub_rn()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::dsub_rn (Tp x, Tp y)
Definition at line 193 of file imf_rounding_math.hpp.
References __imf_dsub_rn().
dsub_ru()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::dsub_ru (Tp x, Tp y)
Definition at line 197 of file imf_rounding_math.hpp.
References __imf_dsub_ru().
dsub_rz()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::dsub_rz (Tp x, Tp y)
Definition at line 201 of file imf_rounding_math.hpp.
References __imf_dsub_rz().
fadd_rd()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fadd_rd (Tp x, Tp y)
Definition at line 77 of file imf_rounding_math.hpp.
References __imf_fadd_rd().
fadd_rn()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fadd_rn (Tp x, Tp y)
Definition at line 81 of file imf_rounding_math.hpp.
References __imf_fadd_rn().
fadd_ru()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fadd_ru (Tp x, Tp y)
Definition at line 85 of file imf_rounding_math.hpp.
References __imf_fadd_ru().
fadd_rz()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fadd_rz (Tp x, Tp y)
Definition at line 89 of file imf_rounding_math.hpp.
References __imf_fadd_rz().
fdiv_rd()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fdiv_rd (Tp x, Tp y)
Definition at line 125 of file imf_rounding_math.hpp.
References __imf_fdiv_rd().
fdiv_rn()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fdiv_rn (Tp x, Tp y)
Definition at line 129 of file imf_rounding_math.hpp.
References __imf_fdiv_rn().
fdiv_ru()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fdiv_ru (Tp x, Tp y)
Definition at line 133 of file imf_rounding_math.hpp.
References __imf_fdiv_ru().
fdiv_rz()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fdiv_rz (Tp x, Tp y)
Definition at line 137 of file imf_rounding_math.hpp.
References __imf_fdiv_rz().
ffs()
template<typename Tp = int> int sycl::_V1::ext::intel::math::ffs (Tp x)
Definition at line 93 of file imf_integer_utils.hpp.
References __imf_ffs().
ffsll()
template<typename Tp = long long> int sycl::_V1::ext::intel::math::ffsll (Tp x)
Definition at line 95 of file imf_integer_utils.hpp.
References __imf_ffsll().
float2bfloat16()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = float> To sycl::_V1::ext::intel::math::float2bfloat16 (From x)
Definition at line 851 of file imf_fp_conversions.hpp.
References __imf_float2bfloat16_rn().
float2bfloat16_rd()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = float> To sycl::_V1::ext::intel::math::float2bfloat16_rd (From x)
Definition at line 857 of file imf_fp_conversions.hpp.
References __imf_float2bfloat16_rd().
float2bfloat16_rn()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = float> To sycl::_V1::ext::intel::math::float2bfloat16_rn (From x)
Definition at line 863 of file imf_fp_conversions.hpp.
References __imf_float2bfloat16_rn().
float2bfloat16_ru()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = float> To sycl::_V1::ext::intel::math::float2bfloat16_ru (From x)
Definition at line 869 of file imf_fp_conversions.hpp.
References __imf_float2bfloat16_ru().
float2bfloat16_rz()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = float> To sycl::_V1::ext::intel::math::float2bfloat16_rz (From x)
Definition at line 875 of file imf_fp_conversions.hpp.
References __imf_float2bfloat16_rz().
float2half_rd()
template<typename To = sycl::half, typename From = float> To sycl::_V1::ext::intel::math::float2half_rd (From x)
Definition at line 562 of file imf_fp_conversions.hpp.
References __imf_float2half_rd().
float2half_rn()
template<typename To = sycl::half, typename From = float> To sycl::_V1::ext::intel::math::float2half_rn (From x)
Definition at line 557 of file imf_fp_conversions.hpp.
References __imf_float2half_rn().
float2half_ru()
template<typename To = sycl::half, typename From = float> To sycl::_V1::ext::intel::math::float2half_ru (From x)
Definition at line 567 of file imf_fp_conversions.hpp.
References __imf_float2half_ru().
float2half_rz()
template<typename To = sycl::half, typename From = float> To sycl::_V1::ext::intel::math::float2half_rz (From x)
Definition at line 572 of file imf_fp_conversions.hpp.
References __imf_float2half_rz().
float2int_rd()
template<typename To = int, typename From = float> To sycl::_V1::ext::intel::math::float2int_rd (From x)
Definition at line 213 of file imf_fp_conversions.hpp.
References __imf_float2int_rd().
float2int_rn()
template<typename To = int, typename From = float> To sycl::_V1::ext::intel::math::float2int_rn (From x)
Definition at line 217 of file imf_fp_conversions.hpp.
References __imf_float2int_rn().
float2int_ru()
template<typename To = int, typename From = float> To sycl::_V1::ext::intel::math::float2int_ru (From x)
Definition at line 221 of file imf_fp_conversions.hpp.
References __imf_float2int_ru().
float2int_rz()
template<typename To = int, typename From = float> To sycl::_V1::ext::intel::math::float2int_rz (From x)
Definition at line 225 of file imf_fp_conversions.hpp.
References __imf_float2int_rz().
float2ll_rd()
template<typename To = long long, typename From = float> To sycl::_V1::ext::intel::math::float2ll_rd (From x)
Definition at line 250 of file imf_fp_conversions.hpp.
References __imf_float2ll_rd().
float2ll_rn()
template<typename To = long long, typename From = float> To sycl::_V1::ext::intel::math::float2ll_rn (From x)
Definition at line 255 of file imf_fp_conversions.hpp.
References __imf_float2ll_rn().
float2ll_ru()
template<typename To = long long, typename From = float> To sycl::_V1::ext::intel::math::float2ll_ru (From x)
Definition at line 260 of file imf_fp_conversions.hpp.
References __imf_float2ll_ru().
float2ll_rz()
template<typename To = long long, typename From = float> To sycl::_V1::ext::intel::math::float2ll_rz (From x)
Definition at line 265 of file imf_fp_conversions.hpp.
References __imf_float2ll_rz().
float2uint_rd()
template<typename To = unsigned int, typename From = float> To sycl::_V1::ext::intel::math::float2uint_rd (From x)
Definition at line 230 of file imf_fp_conversions.hpp.
References __imf_float2uint_rd().
float2uint_rn()
template<typename To = unsigned int, typename From = float> To sycl::_V1::ext::intel::math::float2uint_rn (From x)
Definition at line 235 of file imf_fp_conversions.hpp.
References __imf_float2uint_rn().
float2uint_ru()
template<typename To = unsigned int, typename From = float> To sycl::_V1::ext::intel::math::float2uint_ru (From x)
Definition at line 240 of file imf_fp_conversions.hpp.
References __imf_float2uint_ru().
float2uint_rz()
template<typename To = unsigned int, typename From = float> To sycl::_V1::ext::intel::math::float2uint_rz (From x)
Definition at line 245 of file imf_fp_conversions.hpp.
References __imf_float2uint_rz().
float2ull_rd()
template<typename To = unsigned long long, typename From = float> To sycl::_V1::ext::intel::math::float2ull_rd (From x)
Definition at line 270 of file imf_fp_conversions.hpp.
References __imf_float2ull_rd().
float2ull_rn()
template<typename To = unsigned long long, typename From = float> To sycl::_V1::ext::intel::math::float2ull_rn (From x)
Definition at line 275 of file imf_fp_conversions.hpp.
References __imf_float2ull_rn().
float2ull_ru()
template<typename To = unsigned long long, typename From = float> To sycl::_V1::ext::intel::math::float2ull_ru (From x)
Definition at line 280 of file imf_fp_conversions.hpp.
References __imf_float2ull_ru().
float2ull_rz()
template<typename To = unsigned long long, typename From = float> To sycl::_V1::ext::intel::math::float2ull_rz (From x)
Definition at line 285 of file imf_fp_conversions.hpp.
References __imf_float2ull_rz().
float_as_int()
template<typename To = int, typename From = float> To sycl::_V1::ext::intel::math::float_as_int (From x)
Definition at line 365 of file imf_fp_conversions.hpp.
References __imf_float_as_int().
float_as_uint()
template<typename To = unsigned int, typename From = float> To sycl::_V1::ext::intel::math::float_as_uint (From x)
Definition at line 370 of file imf_fp_conversions.hpp.
References __imf_float_as_uint().
floor() [1/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, float>, float> sycl::_V1::ext::intel::math::floor (Tp x)
Definition at line 116 of file math.hpp.
References __imf_floorf().
Referenced by floor().
floor() [2/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, double>, double> sycl::_V1::ext::intel::math::floor (Tp x)
Definition at line 121 of file math.hpp.
References __imf_floor().
floor() [3/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, sycl::half>, sycl::half> sycl::_V1::ext::intel::math::floor (Tp x)
Definition at line 126 of file math.hpp.
References __imf_floorf16().
floor() [4/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, sycl::half2>, sycl::half2> sycl::_V1::ext::intel::math::floor (Tp x)
Definition at line 132 of file math.hpp.
References floor().
fma_rd()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::fma_rd (Tp x, Tp y, Tp z)
Definition at line 245 of file imf_rounding_math.hpp.
References __imf_fma_rd().
fma_rn()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::fma_rn (Tp x, Tp y, Tp z)
Definition at line 249 of file imf_rounding_math.hpp.
References __imf_fma_rn().
fma_ru()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::fma_ru (Tp x, Tp y, Tp z)
Definition at line 253 of file imf_rounding_math.hpp.
References __imf_fma_ru().
fma_rz()
template<typename Tp = double> Tp sycl::_V1::ext::intel::math::fma_rz (Tp x, Tp y, Tp z)
Definition at line 257 of file imf_rounding_math.hpp.
References __imf_fma_rz().
fmaf_rd()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fmaf_rd (Tp x, Tp y, Tp z)
Definition at line 149 of file imf_rounding_math.hpp.
References __imf_fmaf_rd().
fmaf_rn()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fmaf_rn (Tp x, Tp y, Tp z)
Definition at line 153 of file imf_rounding_math.hpp.
References __imf_fmaf_rn().
fmaf_ru()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fmaf_ru (Tp x, Tp y, Tp z)
Definition at line 157 of file imf_rounding_math.hpp.
References __imf_fmaf_ru().
fmaf_rz()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fmaf_rz (Tp x, Tp y, Tp z)
Definition at line 161 of file imf_rounding_math.hpp.
References __imf_fmaf_rz().
fmul_rd()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fmul_rd (Tp x, Tp y)
Definition at line 109 of file imf_rounding_math.hpp.
References __imf_fmul_rd().
fmul_rn()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fmul_rn (Tp x, Tp y)
Definition at line 113 of file imf_rounding_math.hpp.
References __imf_fmul_rn().
fmul_ru()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fmul_ru (Tp x, Tp y)
Definition at line 117 of file imf_rounding_math.hpp.
References __imf_fmul_ru().
fmul_rz()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fmul_rz (Tp x, Tp y)
Definition at line 121 of file imf_rounding_math.hpp.
References __imf_fmul_rz().
frcp_rd()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::frcp_rd (Tp x)
Definition at line 141 of file imf_rounding_math.hpp.
References __imf_frcp_rd().
frcp_rn()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::frcp_rn (Tp x)
Definition at line 143 of file imf_rounding_math.hpp.
References __imf_frcp_rn().
frcp_ru()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::frcp_ru (Tp x)
Definition at line 145 of file imf_rounding_math.hpp.
References __imf_frcp_ru().
frcp_rz()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::frcp_rz (Tp x)
Definition at line 147 of file imf_rounding_math.hpp.
References __imf_frcp_rz().
fsqrt_rd()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fsqrt_rd (Tp x)
Definition at line 165 of file imf_rounding_math.hpp.
References __imf_sqrtf_rd().
fsqrt_rn()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fsqrt_rn (Tp x)
Definition at line 167 of file imf_rounding_math.hpp.
References __imf_sqrtf_rn().
fsqrt_ru()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fsqrt_ru (Tp x)
Definition at line 169 of file imf_rounding_math.hpp.
References __imf_sqrtf_ru().
fsqrt_rz()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fsqrt_rz (Tp x)
Definition at line 171 of file imf_rounding_math.hpp.
References __imf_sqrtf_rz().
fsub_rd()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fsub_rd (Tp x, Tp y)
Definition at line 93 of file imf_rounding_math.hpp.
References __imf_fsub_rd().
fsub_rn()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fsub_rn (Tp x, Tp y)
Definition at line 97 of file imf_rounding_math.hpp.
References __imf_fsub_rn().
fsub_ru()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fsub_ru (Tp x, Tp y)
Definition at line 101 of file imf_rounding_math.hpp.
References __imf_fsub_ru().
fsub_rz()
template<typename Tp = float> Tp sycl::_V1::ext::intel::math::fsub_rz (Tp x, Tp y)
Definition at line 105 of file imf_rounding_math.hpp.
References __imf_fsub_rz().
h2div()
sycl::half2 sycl::_V1::ext::intel::math::h2div (sycl::half2 x, sycl::half2 y)
Definition at line 130 of file imf_half_trivial.hpp.
habs()
sycl::half sycl::_V1::ext::intel::math::habs (sycl::half x)
Definition at line 312 of file imf_half_trivial.hpp.
References sycl::_V1::ext::oneapi::fabs().
habs2()
sycl::half2 sycl::_V1::ext::intel::math::habs2 (sycl::half2 x)
Definition at line 314 of file imf_half_trivial.hpp.
References sycl::_V1::ext::oneapi::fabs().
hadd() [1/2]
sycl::half sycl::_V1::ext::intel::math::hadd (sycl::half x, sycl::half y)
Definition at line 19 of file imf_half_trivial.hpp.
hadd() [2/2]
template<typename Tp = int> int sycl::_V1::ext::intel::math::hadd (Tp x, Tp y)
Definition at line 97 of file imf_integer_utils.hpp.
References __imf_hadd().
hadd2()
sycl::half2 sycl::_V1::ext::intel::math::hadd2 (sycl::half2 x, sycl::half2 y)
Definition at line 109 of file imf_half_trivial.hpp.
hadd2_sat()
sycl::half2 sycl::_V1::ext::intel::math::hadd2_sat (sycl::half2 x, sycl::half2 y)
Definition at line 111 of file imf_half_trivial.hpp.
hadd_sat()
sycl::half sycl::_V1::ext::intel::math::hadd_sat (sycl::half x, sycl::half y)
Definition at line 21 of file imf_half_trivial.hpp.
half2float()
template<typename To = float, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2float (From x)
Definition at line 552 of file imf_fp_conversions.hpp.
References __imf_half2float().
half2int_rd()
template<typename To = int, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2int_rd (From x)
Definition at line 587 of file imf_fp_conversions.hpp.
References __imf_half2int_rd().
half2int_rn()
template<typename To = int, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2int_rn (From x)
Definition at line 582 of file imf_fp_conversions.hpp.
References __imf_half2int_rn().
half2int_ru()
template<typename To = int, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2int_ru (From x)
Definition at line 592 of file imf_fp_conversions.hpp.
References __imf_half2int_ru().
half2int_rz()
template<typename To = int, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2int_rz (From x)
Definition at line 597 of file imf_fp_conversions.hpp.
References __imf_half2int_rz().
half2ll_rd()
template<typename To = long long, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2ll_rd (From x)
Definition at line 607 of file imf_fp_conversions.hpp.
References __imf_half2ll_rd().
half2ll_rn()
template<typename To = long long, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2ll_rn (From x)
Definition at line 602 of file imf_fp_conversions.hpp.
References __imf_half2ll_rn().
half2ll_ru()
template<typename To = long long, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2ll_ru (From x)
Definition at line 612 of file imf_fp_conversions.hpp.
References __imf_half2ll_ru().
half2ll_rz()
template<typename To = long long, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2ll_rz (From x)
Definition at line 617 of file imf_fp_conversions.hpp.
References __imf_half2ll_rz().
half2short_rd()
template<typename To = short, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2short_rd (From x)
Definition at line 627 of file imf_fp_conversions.hpp.
References __imf_half2short_rd().
half2short_rn()
template<typename To = short, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2short_rn (From x)
Definition at line 622 of file imf_fp_conversions.hpp.
References __imf_half2short_rn().
half2short_ru()
template<typename To = short, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2short_ru (From x)
Definition at line 632 of file imf_fp_conversions.hpp.
References __imf_half2short_ru().
half2short_rz()
template<typename To = short, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2short_rz (From x)
Definition at line 637 of file imf_fp_conversions.hpp.
References __imf_half2short_rz().
half2uint_rd()
template<typename To = unsigned int, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2uint_rd (From x)
Definition at line 667 of file imf_fp_conversions.hpp.
References __imf_half2uint_rd().
half2uint_rn()
template<typename To = unsigned int, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2uint_rn (From x)
Definition at line 662 of file imf_fp_conversions.hpp.
References __imf_half2uint_rn().
half2uint_ru()
template<typename To = unsigned int, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2uint_ru (From x)
Definition at line 672 of file imf_fp_conversions.hpp.
References __imf_half2uint_ru().
half2uint_rz()
template<typename To = unsigned int, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2uint_rz (From x)
Definition at line 677 of file imf_fp_conversions.hpp.
References __imf_half2uint_rz().
half2ull_rd()
template<typename To = unsigned long long, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2ull_rd (From x)
Definition at line 687 of file imf_fp_conversions.hpp.
References __imf_half2ull_rd().
half2ull_rn()
template<typename To = unsigned long long, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2ull_rn (From x)
Definition at line 682 of file imf_fp_conversions.hpp.
References __imf_half2ull_rn().
half2ull_ru()
template<typename To = unsigned long long, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2ull_ru (From x)
Definition at line 692 of file imf_fp_conversions.hpp.
References __imf_half2ull_ru().
half2ull_rz()
template<typename To = unsigned long long, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2ull_rz (From x)
Definition at line 697 of file imf_fp_conversions.hpp.
References __imf_half2ull_rz().
half2ushort_rd()
template<typename To = unsigned short, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2ushort_rd (From x)
Definition at line 647 of file imf_fp_conversions.hpp.
References __imf_half2ushort_rd().
half2ushort_rn()
template<typename To = unsigned short, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2ushort_rn (From x)
Definition at line 642 of file imf_fp_conversions.hpp.
References __imf_half2ushort_rn().
half2ushort_ru()
template<typename To = unsigned short, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2ushort_ru (From x)
Definition at line 652 of file imf_fp_conversions.hpp.
References __imf_half2ushort_ru().
half2ushort_rz()
template<typename To = unsigned short, typename From = sycl::half> To sycl::_V1::ext::intel::math::half2ushort_rz (From x)
Definition at line 657 of file imf_fp_conversions.hpp.
References __imf_half2ushort_rz().
hbeq2()
bool sycl::_V1::ext::intel::math::hbeq2 (sycl::half2 x, sycl::half2 y)
Definition at line 140 of file imf_half_trivial.hpp.
References heq().
hbequ2()
bool sycl::_V1::ext::intel::math::hbequ2 (sycl::half2 x, sycl::half2 y)
Definition at line 144 of file imf_half_trivial.hpp.
References hequ().
hbge2()
bool sycl::_V1::ext::intel::math::hbge2 (sycl::half2 x, sycl::half2 y)
Definition at line 148 of file imf_half_trivial.hpp.
References hge().
hbgeu2()
bool sycl::_V1::ext::intel::math::hbgeu2 (sycl::half2 x, sycl::half2 y)
Definition at line 152 of file imf_half_trivial.hpp.
References hgeu().
hbgt2()
bool sycl::_V1::ext::intel::math::hbgt2 (sycl::half2 x, sycl::half2 y)
Definition at line 156 of file imf_half_trivial.hpp.
References hgt().
hbgtu2()
bool sycl::_V1::ext::intel::math::hbgtu2 (sycl::half2 x, sycl::half2 y)
Definition at line 160 of file imf_half_trivial.hpp.
References hgtu().
hble2()
bool sycl::_V1::ext::intel::math::hble2 (sycl::half2 x, sycl::half2 y)
Definition at line 164 of file imf_half_trivial.hpp.
References hle().
hbleu2()
bool sycl::_V1::ext::intel::math::hbleu2 (sycl::half2 x, sycl::half2 y)
Definition at line 168 of file imf_half_trivial.hpp.
References hleu().
hblt2()
bool sycl::_V1::ext::intel::math::hblt2 (sycl::half2 x, sycl::half2 y)
Definition at line 172 of file imf_half_trivial.hpp.
References hlt().
hbltu2()
bool sycl::_V1::ext::intel::math::hbltu2 (sycl::half2 x, sycl::half2 y)
Definition at line 176 of file imf_half_trivial.hpp.
References hltu().
hbne2()
bool sycl::_V1::ext::intel::math::hbne2 (sycl::half2 x, sycl::half2 y)
Definition at line 180 of file imf_half_trivial.hpp.
References hne().
hbneu2()
bool sycl::_V1::ext::intel::math::hbneu2 (sycl::half2 x, sycl::half2 y)
Definition at line 184 of file imf_half_trivial.hpp.
References hneu().
hcmadd()
sycl::half2 sycl::_V1::ext::intel::math::hcmadd (sycl::half2 x, sycl::half2 y, sycl::half2 z)
Definition at line 287 of file imf_half_trivial.hpp.
hdiv()
sycl::half sycl::_V1::ext::intel::math::hdiv (sycl::half x, sycl::half y)
Definition at line 47 of file imf_half_trivial.hpp.
heq()
bool sycl::_V1::ext::intel::math::heq (sycl::half x, sycl::half y)
Definition at line 49 of file imf_half_trivial.hpp.
Referenced by hbeq2(), and heq2().
heq2()
sycl::half2 sycl::_V1::ext::intel::math::heq2 (sycl::half2 x, sycl::half2 y)
Definition at line 188 of file imf_half_trivial.hpp.
References heq().
hequ()
bool sycl::_V1::ext::intel::math::hequ (sycl::half x, sycl::half y)
Definition at line 51 of file imf_half_trivial.hpp.
References sycl::_V1::ext::oneapi::experimental::isnan().
Referenced by hbequ2(), and hequ2().
hequ2()
sycl::half2 sycl::_V1::ext::intel::math::hequ2 (sycl::half2 x, sycl::half2 y)
Definition at line 193 of file imf_half_trivial.hpp.
References hequ().
hfma()
sycl::half sycl::_V1::ext::intel::math::hfma (sycl::half x, sycl::half y, sycl::half z)
Definition at line 25 of file imf_half_trivial.hpp.
hfma2()
sycl::half2 sycl::_V1::ext::intel::math::hfma2 (sycl::half2 x, sycl::half2 y, sycl::half2 z)
Definition at line 115 of file imf_half_trivial.hpp.
hfma2_relu()
sycl::half2 sycl::_V1::ext::intel::math::hfma2_relu (sycl::half2 x, sycl::half2 y, sycl::half2 z)
Definition at line 303 of file imf_half_trivial.hpp.
References hisnan(), and sycl::_V1::r.
hfma2_sat()
sycl::half2 sycl::_V1::ext::intel::math::hfma2_sat (sycl::half2 x, sycl::half2 y, sycl::half2 z)
Definition at line 119 of file imf_half_trivial.hpp.
hfma_relu()
sycl::half sycl::_V1::ext::intel::math::hfma_relu (sycl::half x, sycl::half y, sycl::half z)
Definition at line 292 of file imf_half_trivial.hpp.
References hisnan(), and sycl::_V1::r.
hfma_sat()
sycl::half sycl::_V1::ext::intel::math::hfma_sat (sycl::half x, sycl::half y, sycl::half z)
Definition at line 29 of file imf_half_trivial.hpp.
hge()
bool sycl::_V1::ext::intel::math::hge (sycl::half x, sycl::half y)
Definition at line 58 of file imf_half_trivial.hpp.
Referenced by hbge2(), and hge2().
hge2()
sycl::half2 sycl::_V1::ext::intel::math::hge2 (sycl::half2 x, sycl::half2 y)
Definition at line 198 of file imf_half_trivial.hpp.
References hge().
hgeu()
bool sycl::_V1::ext::intel::math::hgeu (sycl::half x, sycl::half y)
Definition at line 60 of file imf_half_trivial.hpp.
References sycl::_V1::ext::oneapi::experimental::isnan().
Referenced by hbgeu2(), and hgeu2().
hgeu2()
sycl::half2 sycl::_V1::ext::intel::math::hgeu2 (sycl::half2 x, sycl::half2 y)
Definition at line 203 of file imf_half_trivial.hpp.
References hgeu().
hgt()
bool sycl::_V1::ext::intel::math::hgt (sycl::half x, sycl::half y)
Definition at line 67 of file imf_half_trivial.hpp.
Referenced by hbgt2(), and hgt2().
hgt2()
sycl::half2 sycl::_V1::ext::intel::math::hgt2 (sycl::half2 x, sycl::half2 y)
Definition at line 208 of file imf_half_trivial.hpp.
References hgt().
hgtu()
bool sycl::_V1::ext::intel::math::hgtu (sycl::half x, sycl::half y)
Definition at line 69 of file imf_half_trivial.hpp.
References sycl::_V1::ext::oneapi::experimental::isnan().
Referenced by hbgtu2(), and hgtu2().
hgtu2()
sycl::half2 sycl::_V1::ext::intel::math::hgtu2 (sycl::half2 x, sycl::half2 y)
Definition at line 213 of file imf_half_trivial.hpp.
References hgtu().
hiloint2double()
template<typename To = double, typename From = int> To sycl::_V1::ext::intel::math::hiloint2double (From x, From y)
Definition at line 498 of file imf_fp_conversions.hpp.
References __imf_hiloint2double().
hisinf()
bool sycl::_V1::ext::intel::math::hisinf (sycl::half x)
Definition at line 106 of file imf_half_trivial.hpp.
hisnan()
bool sycl::_V1::ext::intel::math::hisnan (sycl::half y)
Definition at line 107 of file imf_half_trivial.hpp.
References sycl::_V1::ext::oneapi::experimental::isnan().
Referenced by hfma2_relu(), hfma_relu(), hisnan2(), hmax_nan(), and hmin_nan().
hisnan2()
sycl::half2 sycl::_V1::ext::intel::math::hisnan2 (sycl::half2 x)
Definition at line 238 of file imf_half_trivial.hpp.
References hisnan().
hle()
bool sycl::_V1::ext::intel::math::hle (sycl::half x, sycl::half y)
Definition at line 76 of file imf_half_trivial.hpp.
Referenced by hble2(), and hle2().
hle2()
sycl::half2 sycl::_V1::ext::intel::math::hle2 (sycl::half2 x, sycl::half2 y)
Definition at line 218 of file imf_half_trivial.hpp.
References hle().
hleu()
bool sycl::_V1::ext::intel::math::hleu (sycl::half x, sycl::half y)
Definition at line 78 of file imf_half_trivial.hpp.
References sycl::_V1::ext::oneapi::experimental::isnan().
Referenced by hbleu2(), and hleu2().
hleu2()
sycl::half2 sycl::_V1::ext::intel::math::hleu2 (sycl::half2 x, sycl::half2 y)
Definition at line 223 of file imf_half_trivial.hpp.
References hleu().
hlt()
bool sycl::_V1::ext::intel::math::hlt (sycl::half x, sycl::half y)
Definition at line 85 of file imf_half_trivial.hpp.
Referenced by hblt2(), and hlt2().
hlt2()
sycl::half2 sycl::_V1::ext::intel::math::hlt2 (sycl::half2 x, sycl::half2 y)
Definition at line 228 of file imf_half_trivial.hpp.
References hlt().
hltu()
bool sycl::_V1::ext::intel::math::hltu (sycl::half x, sycl::half y)
Definition at line 87 of file imf_half_trivial.hpp.
References sycl::_V1::ext::oneapi::experimental::isnan().
Referenced by hbltu2(), and hltu2().
hltu2()
sycl::half2 sycl::_V1::ext::intel::math::hltu2 (sycl::half2 x, sycl::half2 y)
Definition at line 233 of file imf_half_trivial.hpp.
References hltu().
hmax()
sycl::half sycl::_V1::ext::intel::math::hmax (sycl::half x, sycl::half y)
Definition at line 253 of file imf_half_trivial.hpp.
Referenced by hmax2().
hmax2()
sycl::half2 sycl::_V1::ext::intel::math::hmax2 (sycl::half2 x, sycl::half2 y)
Definition at line 262 of file imf_half_trivial.hpp.
References hmax().
hmax2_nan()
sycl::half2 sycl::_V1::ext::intel::math::hmax2_nan (sycl::half2 x, sycl::half2 y)
Definition at line 266 of file imf_half_trivial.hpp.
References hmax_nan().
hmax_nan()
sycl::half sycl::_V1::ext::intel::math::hmax_nan (sycl::half x, sycl::half y)
Definition at line 255 of file imf_half_trivial.hpp.
References hisnan().
Referenced by hmax2_nan().
hmin()
sycl::half sycl::_V1::ext::intel::math::hmin (sycl::half x, sycl::half y)
Definition at line 270 of file imf_half_trivial.hpp.
Referenced by hmin2().
hmin2()
sycl::half2 sycl::_V1::ext::intel::math::hmin2 (sycl::half2 x, sycl::half2 y)
Definition at line 279 of file imf_half_trivial.hpp.
References hmin().
hmin2_nan()
sycl::half2 sycl::_V1::ext::intel::math::hmin2_nan (sycl::half2 x, sycl::half2 y)
Definition at line 283 of file imf_half_trivial.hpp.
References hmin_nan().
hmin_nan()
sycl::half sycl::_V1::ext::intel::math::hmin_nan (sycl::half x, sycl::half y)
Definition at line 272 of file imf_half_trivial.hpp.
References hisnan().
Referenced by hmin2_nan().
hmul()
sycl::half sycl::_V1::ext::intel::math::hmul (sycl::half x, sycl::half y)
Definition at line 33 of file imf_half_trivial.hpp.
hmul2()
sycl::half2 sycl::_V1::ext::intel::math::hmul2 (sycl::half2 x, sycl::half2 y)
Definition at line 124 of file imf_half_trivial.hpp.
hmul2_sat()
sycl::half2 sycl::_V1::ext::intel::math::hmul2_sat (sycl::half2 x, sycl::half2 y)
Definition at line 126 of file imf_half_trivial.hpp.
hmul_sat()
sycl::half sycl::_V1::ext::intel::math::hmul_sat (sycl::half x, sycl::half y)
Definition at line 35 of file imf_half_trivial.hpp.
hne()
bool sycl::_V1::ext::intel::math::hne (sycl::half x, sycl::half y)
Definition at line 93 of file imf_half_trivial.hpp.
References sycl::_V1::ext::oneapi::experimental::isnan().
Referenced by hbne2(), and hne2().
hne2()
sycl::half2 sycl::_V1::ext::intel::math::hne2 (sycl::half2 x, sycl::half2 y)
Definition at line 243 of file imf_half_trivial.hpp.
References hne().
hneg()
sycl::half sycl::_V1::ext::intel::math::hneg (sycl::half x)
Definition at line 39 of file imf_half_trivial.hpp.
hneg2()
sycl::half2 sycl::_V1::ext::intel::math::hneg2 (sycl::half2 x)
Definition at line 132 of file imf_half_trivial.hpp.
hneu()
bool sycl::_V1::ext::intel::math::hneu (sycl::half x, sycl::half y)
Definition at line 99 of file imf_half_trivial.hpp.
References sycl::_V1::ext::oneapi::experimental::isnan().
Referenced by hbneu2(), and hneu2().
hneu2()
sycl::half2 sycl::_V1::ext::intel::math::hneu2 (sycl::half2 x, sycl::half2 y)
Definition at line 248 of file imf_half_trivial.hpp.
References hneu().
hsub()
sycl::half sycl::_V1::ext::intel::math::hsub (sycl::half x, sycl::half y)
Definition at line 41 of file imf_half_trivial.hpp.
hsub2()
sycl::half2 sycl::_V1::ext::intel::math::hsub2 (sycl::half2 x, sycl::half2 y)
Definition at line 134 of file imf_half_trivial.hpp.
hsub2_sat()
sycl::half2 sycl::_V1::ext::intel::math::hsub2_sat (sycl::half2 x, sycl::half2 y)
Definition at line 136 of file imf_half_trivial.hpp.
hsub_sat()
sycl::half sycl::_V1::ext::intel::math::hsub_sat (sycl::half x, sycl::half y)
Definition at line 43 of file imf_half_trivial.hpp.
int2bfloat16_rd()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = int> To sycl::_V1::ext::intel::math::int2bfloat16_rd (From x)
Definition at line 981 of file imf_fp_conversions.hpp.
References __imf_int2bfloat16_rd().
int2bfloat16_rn()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = int> To sycl::_V1::ext::intel::math::int2bfloat16_rn (From x)
Definition at line 986 of file imf_fp_conversions.hpp.
References __imf_int2bfloat16_rn().
int2bfloat16_ru()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = int> To sycl::_V1::ext::intel::math::int2bfloat16_ru (From x)
Definition at line 991 of file imf_fp_conversions.hpp.
References __imf_int2bfloat16_ru().
int2bfloat16_rz()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = int> To sycl::_V1::ext::intel::math::int2bfloat16_rz (From x)
Definition at line 996 of file imf_fp_conversions.hpp.
References __imf_int2bfloat16_rz().
int2double_rn()
template<typename To = double, typename From = int> To sycl::_V1::ext::intel::math::int2double_rn (From x)
Definition at line 502 of file imf_fp_conversions.hpp.
References __imf_int2double_rn().
int2float_rd()
template<typename To = float, typename From = int> To sycl::_V1::ext::intel::math::int2float_rd (From x)
Definition at line 329 of file imf_fp_conversions.hpp.
References __imf_int2float_rd().
int2float_rn()
template<typename To = float, typename From = int> To sycl::_V1::ext::intel::math::int2float_rn (From x)
Definition at line 333 of file imf_fp_conversions.hpp.
References __imf_int2float_rn().
int2float_ru()
template<typename To = float, typename From = int> To sycl::_V1::ext::intel::math::int2float_ru (From x)
Definition at line 337 of file imf_fp_conversions.hpp.
References __imf_int2float_ru().
int2float_rz()
template<typename To = float, typename From = int> To sycl::_V1::ext::intel::math::int2float_rz (From x)
Definition at line 341 of file imf_fp_conversions.hpp.
References __imf_int2float_rz().
int2half_rd()
template<typename To = sycl::half, typename From = int> To sycl::_V1::ext::intel::math::int2half_rd (From x)
Definition at line 707 of file imf_fp_conversions.hpp.
References __imf_int2half_rd().
int2half_rn()
template<typename To = sycl::half, typename From = int> To sycl::_V1::ext::intel::math::int2half_rn (From x)
Definition at line 702 of file imf_fp_conversions.hpp.
References __imf_int2half_rn().
int2half_ru()
template<typename To = sycl::half, typename From = int> To sycl::_V1::ext::intel::math::int2half_ru (From x)
Definition at line 712 of file imf_fp_conversions.hpp.
References __imf_int2half_ru().
int2half_rz()
template<typename To = sycl::half, typename From = int> To sycl::_V1::ext::intel::math::int2half_rz (From x)
Definition at line 717 of file imf_fp_conversions.hpp.
References __imf_int2half_rz().
int_as_float()
template<typename To = float, typename From = int> To sycl::_V1::ext::intel::math::int_as_float (From x)
Definition at line 374 of file imf_fp_conversions.hpp.
References __imf_int_as_float().
inv() [1/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, float>, float> sycl::_V1::ext::intel::math::inv (Tp x)
Definition at line 137 of file math.hpp.
References __imf_invf().
Referenced by inv().
inv() [2/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, double>, double> sycl::_V1::ext::intel::math::inv (Tp x)
Definition at line 142 of file math.hpp.
References __imf_inv().
inv() [3/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, sycl::half>, sycl::half> sycl::_V1::ext::intel::math::inv (Tp x)
Definition at line 147 of file math.hpp.
References __imf_invf16().
inv() [4/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, sycl::half2>, sycl::half2> sycl::_V1::ext::intel::math::inv (Tp x)
Definition at line 153 of file math.hpp.
References inv().
ll2bfloat16_rd()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = long long> To sycl::_V1::ext::intel::math::ll2bfloat16_rd (From x)
Definition at line 1001 of file imf_fp_conversions.hpp.
References __imf_ll2bfloat16_rd().
ll2bfloat16_rn()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = long long> To sycl::_V1::ext::intel::math::ll2bfloat16_rn (From x)
Definition at line 1006 of file imf_fp_conversions.hpp.
References __imf_ll2bfloat16_rn().
ll2bfloat16_ru()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = long long> To sycl::_V1::ext::intel::math::ll2bfloat16_ru (From x)
Definition at line 1011 of file imf_fp_conversions.hpp.
References __imf_ll2bfloat16_ru().
ll2bfloat16_rz()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = long long> To sycl::_V1::ext::intel::math::ll2bfloat16_rz (From x)
Definition at line 1016 of file imf_fp_conversions.hpp.
References __imf_ll2bfloat16_rz().
ll2double_rd()
template<typename To = double, typename From = long long> To sycl::_V1::ext::intel::math::ll2double_rd (From x)
Definition at line 512 of file imf_fp_conversions.hpp.
References __imf_ll2double_rd().
ll2double_rn()
template<typename To = double, typename From = long long> To sycl::_V1::ext::intel::math::ll2double_rn (From x)
Definition at line 517 of file imf_fp_conversions.hpp.
References __imf_ll2double_rn().
ll2double_ru()
template<typename To = double, typename From = long long> To sycl::_V1::ext::intel::math::ll2double_ru (From x)
Definition at line 522 of file imf_fp_conversions.hpp.
References __imf_ll2double_ru().
ll2double_rz()
template<typename To = double, typename From = long long> To sycl::_V1::ext::intel::math::ll2double_rz (From x)
Definition at line 527 of file imf_fp_conversions.hpp.
References __imf_ll2double_rz().
ll2float_rd()
template<typename To = float, typename From = long long> To sycl::_V1::ext::intel::math::ll2float_rd (From x)
Definition at line 290 of file imf_fp_conversions.hpp.
References __imf_ll2float_rd().
ll2float_rn()
template<typename To = float, typename From = long long> To sycl::_V1::ext::intel::math::ll2float_rn (From x)
Definition at line 295 of file imf_fp_conversions.hpp.
References __imf_ll2float_rn().
ll2float_ru()
template<typename To = float, typename From = long long> To sycl::_V1::ext::intel::math::ll2float_ru (From x)
Definition at line 300 of file imf_fp_conversions.hpp.
References __imf_ll2float_ru().
ll2float_rz()
template<typename To = float, typename From = long long> To sycl::_V1::ext::intel::math::ll2float_rz (From x)
Definition at line 305 of file imf_fp_conversions.hpp.
References __imf_ll2float_rz().
ll2half_rd()
template<typename To = sycl::half, typename From = long long> To sycl::_V1::ext::intel::math::ll2half_rd (From x)
Definition at line 747 of file imf_fp_conversions.hpp.
References __imf_ll2half_rd().
ll2half_rn()
template<typename To = sycl::half, typename From = long long> To sycl::_V1::ext::intel::math::ll2half_rn (From x)
Definition at line 742 of file imf_fp_conversions.hpp.
References __imf_ll2half_rn().
ll2half_ru()
template<typename To = sycl::half, typename From = long long> To sycl::_V1::ext::intel::math::ll2half_ru (From x)
Definition at line 752 of file imf_fp_conversions.hpp.
References __imf_ll2half_ru().
ll2half_rz()
template<typename To = sycl::half, typename From = long long> To sycl::_V1::ext::intel::math::ll2half_rz (From x)
Definition at line 757 of file imf_fp_conversions.hpp.
References __imf_ll2half_rz().
llmax()
template<typename Tp = long long> long long sycl::_V1::ext::intel::math::llmax (Tp x, Tp y)
Definition at line 71 of file imf_integer_utils.hpp.
References __imf_llmax().
llmin()
template<typename Tp = long long> long long sycl::_V1::ext::intel::math::llmin (Tp x, Tp y)
Definition at line 75 of file imf_integer_utils.hpp.
References __imf_llmin().
longlong_as_double()
template<typename To = double, typename From = long long> To sycl::_V1::ext::intel::math::longlong_as_double (From x)
Definition at line 493 of file imf_fp_conversions.hpp.
References __imf_longlong_as_double().
max()
template<typename Tp = int> int sycl::_V1::ext::intel::math::max (Tp x, Tp y)
Definition at line 59 of file imf_integer_utils.hpp.
References __imf_max().
min()
template<typename Tp = int> int sycl::_V1::ext::intel::math::min (Tp x, Tp y)
Definition at line 61 of file imf_integer_utils.hpp.
References __imf_min().
mul24()
template<typename Tp = int> int sycl::_V1::ext::intel::math::mul24 (Tp x, Tp y)
Definition at line 105 of file imf_integer_utils.hpp.
References __imf_mul24().
mul64hi()
template<typename Tp = long long> long long sycl::_V1::ext::intel::math::mul64hi (Tp x, Tp y)
Definition at line 117 of file imf_integer_utils.hpp.
References __imf_mul64hi().
mulhi()
template<typename Tp = int> int sycl::_V1::ext::intel::math::mulhi (Tp x, Tp y)
Definition at line 111 of file imf_integer_utils.hpp.
References __imf_mulhi().
popc()
template<typename Tp = unsigned> int sycl::_V1::ext::intel::math::popc (Tp x)
Definition at line 126 of file imf_integer_utils.hpp.
References __imf_popc().
popcll()
template<typename Tp = unsigned long long> int sycl::_V1::ext::intel::math::popcll (Tp x)
Definition at line 128 of file imf_integer_utils.hpp.
References __imf_popcll().
rcp64h()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, double>, double> sycl::_V1::ext::intel::math::rcp64h (Tp x)
Definition at line 242 of file math.hpp.
References __imf_rcp64h().
rhadd()
template<typename Tp = int> int sycl::_V1::ext::intel::math::rhadd (Tp x, Tp y)
Definition at line 99 of file imf_integer_utils.hpp.
References __imf_rhadd().
Referenced by syclcompat::rhadd::operator()().
rint() [1/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, float>, float> sycl::_V1::ext::intel::math::rint (Tp x)
Definition at line 158 of file math.hpp.
References __imf_rintf().
Referenced by rint().
rint() [2/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, double>, double> sycl::_V1::ext::intel::math::rint (Tp x)
Definition at line 163 of file math.hpp.
References __imf_rint().
rint() [3/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, sycl::half>, sycl::half> sycl::_V1::ext::intel::math::rint (Tp x)
Definition at line 168 of file math.hpp.
References __imf_rintf16().
rint() [4/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, sycl::half2>, sycl::half2> sycl::_V1::ext::intel::math::rint (Tp x)
Definition at line 174 of file math.hpp.
References rint().
rsqrt() [1/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, float>, float> sycl::_V1::ext::intel::math::rsqrt (Tp x)
Definition at line 200 of file math.hpp.
References __imf_rsqrtf().
Referenced by rsqrt().
rsqrt() [2/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, double>, double> sycl::_V1::ext::intel::math::rsqrt (Tp x)
Definition at line 205 of file math.hpp.
References __imf_rsqrt().
rsqrt() [3/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, sycl::half>, sycl::half> sycl::_V1::ext::intel::math::rsqrt (Tp x)
Definition at line 210 of file math.hpp.
References __imf_rsqrtf16().
rsqrt() [4/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, sycl::half2>, sycl::half2> sycl::_V1::ext::intel::math::rsqrt (Tp x)
Definition at line 216 of file math.hpp.
References rsqrt().
sad()
template<typename Tp1 = int, typename Tp2 = unsigned> unsigned sycl::_V1::ext::intel::math::sad (Tp1 x, Tp1 y, Tp2 z)
Definition at line 133 of file imf_integer_utils.hpp.
References __imf_sad().
saturate()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, float>, float> sycl::_V1::ext::intel::math::saturate (Tp x)
Definition at line 72 of file math.hpp.
References __imf_saturatef().
short2bfloat16_rd()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = short> To sycl::_V1::ext::intel::math::short2bfloat16_rd (From x)
Definition at line 957 of file imf_fp_conversions.hpp.
References __imf_short2bfloat16_rd().
short2bfloat16_rn()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = short> To sycl::_V1::ext::intel::math::short2bfloat16_rn (From x)
Definition at line 963 of file imf_fp_conversions.hpp.
References __imf_short2bfloat16_rn().
short2bfloat16_ru()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = short> To sycl::_V1::ext::intel::math::short2bfloat16_ru (From x)
Definition at line 969 of file imf_fp_conversions.hpp.
References __imf_short2bfloat16_ru().
short2bfloat16_rz()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = short> To sycl::_V1::ext::intel::math::short2bfloat16_rz (From x)
Definition at line 975 of file imf_fp_conversions.hpp.
References __imf_short2bfloat16_rz().
short2half_rd()
template<typename To = sycl::half, typename From = short> To sycl::_V1::ext::intel::math::short2half_rd (From x)
Definition at line 727 of file imf_fp_conversions.hpp.
References __imf_short2half_rd().
short2half_rn()
template<typename To = sycl::half, typename From = short> To sycl::_V1::ext::intel::math::short2half_rn (From x)
Definition at line 722 of file imf_fp_conversions.hpp.
References __imf_short2half_rn().
short2half_ru()
template<typename To = sycl::half, typename From = short> To sycl::_V1::ext::intel::math::short2half_ru (From x)
Definition at line 732 of file imf_fp_conversions.hpp.
References __imf_short2half_ru().
short2half_rz()
template<typename To = sycl::half, typename From = short> To sycl::_V1::ext::intel::math::short2half_rz (From x)
Definition at line 737 of file imf_fp_conversions.hpp.
References __imf_short2half_rz().
short_as_bfloat16()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = short> To sycl::_V1::ext::intel::math::short_as_bfloat16 (From x)
Definition at line 840 of file imf_fp_conversions.hpp.
References __imf_short_as_bfloat16().
sqrt() [1/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, float>, float> sycl::_V1::ext::intel::math::sqrt (Tp x)
Definition at line 179 of file math.hpp.
References __imf_sqrtf().
Referenced by sqrt().
sqrt() [2/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, double>, double> sycl::_V1::ext::intel::math::sqrt (Tp x)
Definition at line 184 of file math.hpp.
References __imf_sqrt().
sqrt() [3/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, sycl::half>, sycl::half> sycl::_V1::ext::intel::math::sqrt (Tp x)
Definition at line 189 of file math.hpp.
References __imf_sqrtf16().
sqrt() [4/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, sycl::half2>, sycl::half2> sycl::_V1::ext::intel::math::sqrt (Tp x)
Definition at line 195 of file math.hpp.
References sqrt().
Referenced by syclcompat::fast_length(), and syclcompat::length().
trunc() [1/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, float>, float> sycl::_V1::ext::intel::math::trunc (Tp x)
Definition at line 221 of file math.hpp.
References __imf_truncf().
Referenced by trunc().
trunc() [2/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, double>, double> sycl::_V1::ext::intel::math::trunc (Tp x)
Definition at line 226 of file math.hpp.
References __imf_trunc().
trunc() [3/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, sycl::half>, sycl::half> sycl::_V1::ext::intel::math::trunc (Tp x)
Definition at line 231 of file math.hpp.
References __imf_truncf16().
trunc() [4/4]
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, sycl::half2>, sycl::half2> sycl::_V1::ext::intel::math::trunc (Tp x)
Definition at line 237 of file math.hpp.
References trunc().
uhadd()
template<typename Tp = unsigned> unsigned sycl::_V1::ext::intel::math::uhadd (Tp x, Tp y)
Definition at line 141 of file imf_integer_utils.hpp.
References __imf_uhadd().
uint2bfloat16_rd()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned int> To sycl::_V1::ext::intel::math::uint2bfloat16_rd (From x)
Definition at line 910 of file imf_fp_conversions.hpp.
References __imf_uint2bfloat16_rd().
uint2bfloat16_rn()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned int> To sycl::_V1::ext::intel::math::uint2bfloat16_rn (From x)
Definition at line 916 of file imf_fp_conversions.hpp.
References __imf_uint2bfloat16_rn().
uint2bfloat16_ru()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned int> To sycl::_V1::ext::intel::math::uint2bfloat16_ru (From x)
Definition at line 922 of file imf_fp_conversions.hpp.
References __imf_uint2bfloat16_ru().
uint2bfloat16_rz()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned int> To sycl::_V1::ext::intel::math::uint2bfloat16_rz (From x)
Definition at line 928 of file imf_fp_conversions.hpp.
References __imf_uint2bfloat16_rz().
uint2double_rn()
template<typename To = double, typename From = unsigned int> To sycl::_V1::ext::intel::math::uint2double_rn (From x)
Definition at line 507 of file imf_fp_conversions.hpp.
References __imf_uint2double_rn().
uint2float_rd()
template<typename To = float, typename From = unsigned int> To sycl::_V1::ext::intel::math::uint2float_rd (From x)
Definition at line 346 of file imf_fp_conversions.hpp.
References __imf_uint2float_rd().
uint2float_rn()
template<typename To = float, typename From = unsigned int> To sycl::_V1::ext::intel::math::uint2float_rn (From x)
Definition at line 351 of file imf_fp_conversions.hpp.
References __imf_uint2float_rn().
uint2float_ru()
template<typename To = float, typename From = unsigned int> To sycl::_V1::ext::intel::math::uint2float_ru (From x)
Definition at line 356 of file imf_fp_conversions.hpp.
References __imf_uint2float_ru().
uint2float_rz()
template<typename To = float, typename From = unsigned int> To sycl::_V1::ext::intel::math::uint2float_rz (From x)
Definition at line 361 of file imf_fp_conversions.hpp.
References __imf_uint2float_rz().
uint2half_rd()
template<typename To = sycl::half, typename From = unsigned int> To sycl::_V1::ext::intel::math::uint2half_rd (From x)
Definition at line 787 of file imf_fp_conversions.hpp.
References __imf_uint2half_rd().
uint2half_rn()
template<typename To = sycl::half, typename From = unsigned int> To sycl::_V1::ext::intel::math::uint2half_rn (From x)
Definition at line 782 of file imf_fp_conversions.hpp.
References __imf_uint2half_rn().
uint2half_ru()
template<typename To = sycl::half, typename From = unsigned int> To sycl::_V1::ext::intel::math::uint2half_ru (From x)
Definition at line 792 of file imf_fp_conversions.hpp.
References __imf_uint2half_ru().
uint2half_rz()
template<typename To = sycl::half, typename From = unsigned int> To sycl::_V1::ext::intel::math::uint2half_rz (From x)
Definition at line 797 of file imf_fp_conversions.hpp.
References __imf_uint2half_rz().
uint_as_float()
template<typename To = float, typename From = unsigned int> To sycl::_V1::ext::intel::math::uint_as_float (From x)
Definition at line 379 of file imf_fp_conversions.hpp.
References __imf_uint_as_float().
ull2bfloat16_rd()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned long long> To sycl::_V1::ext::intel::math::ull2bfloat16_rd (From x)
Definition at line 934 of file imf_fp_conversions.hpp.
References __imf_ull2bfloat16_rd().
ull2bfloat16_rn()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned long long> To sycl::_V1::ext::intel::math::ull2bfloat16_rn (From x)
Definition at line 940 of file imf_fp_conversions.hpp.
References __imf_ull2bfloat16_rn().
ull2bfloat16_ru()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned long long> To sycl::_V1::ext::intel::math::ull2bfloat16_ru (From x)
Definition at line 946 of file imf_fp_conversions.hpp.
References __imf_ull2bfloat16_ru().
ull2bfloat16_rz()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned long long> To sycl::_V1::ext::intel::math::ull2bfloat16_rz (From x)
Definition at line 952 of file imf_fp_conversions.hpp.
References __imf_ull2bfloat16_rz().
ull2double_rd()
template<typename To = double, typename From = unsigned long long> To sycl::_V1::ext::intel::math::ull2double_rd (From x)
Definition at line 532 of file imf_fp_conversions.hpp.
References __imf_ull2double_rd().
ull2double_rn()
template<typename To = double, typename From = unsigned long long> To sycl::_V1::ext::intel::math::ull2double_rn (From x)
Definition at line 537 of file imf_fp_conversions.hpp.
References __imf_ull2double_rn().
ull2double_ru()
template<typename To = double, typename From = unsigned long long> To sycl::_V1::ext::intel::math::ull2double_ru (From x)
Definition at line 542 of file imf_fp_conversions.hpp.
References __imf_ull2double_ru().
ull2double_rz()
template<typename To = double, typename From = unsigned long long> To sycl::_V1::ext::intel::math::ull2double_rz (From x)
Definition at line 547 of file imf_fp_conversions.hpp.
References __imf_ull2double_rz().
ull2float_rd()
template<typename To = float, typename From = unsigned long long> To sycl::_V1::ext::intel::math::ull2float_rd (From x)
Definition at line 310 of file imf_fp_conversions.hpp.
References __imf_ull2float_rd().
ull2float_rn()
template<typename To = float, typename From = unsigned long long> To sycl::_V1::ext::intel::math::ull2float_rn (From x)
Definition at line 315 of file imf_fp_conversions.hpp.
References __imf_ull2float_rn().
ull2float_ru()
template<typename To = float, typename From = unsigned long long> To sycl::_V1::ext::intel::math::ull2float_ru (From x)
Definition at line 320 of file imf_fp_conversions.hpp.
References __imf_ull2float_ru().
ull2float_rz()
template<typename To = float, typename From = unsigned long long> To sycl::_V1::ext::intel::math::ull2float_rz (From x)
Definition at line 325 of file imf_fp_conversions.hpp.
References __imf_ull2float_rz().
ull2half_rd()
template<typename To = sycl::half, typename From = unsigned long long> To sycl::_V1::ext::intel::math::ull2half_rd (From x)
Definition at line 807 of file imf_fp_conversions.hpp.
References __imf_ull2half_rd().
ull2half_rn()
template<typename To = sycl::half, typename From = unsigned long long> To sycl::_V1::ext::intel::math::ull2half_rn (From x)
Definition at line 802 of file imf_fp_conversions.hpp.
References __imf_ull2half_rn().
ull2half_ru()
template<typename To = sycl::half, typename From = unsigned long long> To sycl::_V1::ext::intel::math::ull2half_ru (From x)
Definition at line 812 of file imf_fp_conversions.hpp.
References __imf_ull2half_ru().
ull2half_rz()
template<typename To = sycl::half, typename From = unsigned long long> To sycl::_V1::ext::intel::math::ull2half_rz (From x)
Definition at line 817 of file imf_fp_conversions.hpp.
References __imf_ull2half_rz().
ullmax()
template<typename Tp = unsigned long long> unsigned long long sycl::_V1::ext::intel::math::ullmax (Tp x, Tp y)
Definition at line 80 of file imf_integer_utils.hpp.
References __imf_ullmax().
ullmin()
template<typename Tp = unsigned long long> unsigned long long sycl::_V1::ext::intel::math::ullmin (Tp x, Tp y)
Definition at line 85 of file imf_integer_utils.hpp.
References __imf_ullmin().
umax()
template<typename Tp = unsigned> unsigned sycl::_V1::ext::intel::math::umax (Tp x, Tp y)
Definition at line 63 of file imf_integer_utils.hpp.
References __imf_umax().
Referenced by sycl::_V1::ext::intel::esimd::detail::check_atomic(), sycl::_V1::ext::intel::esimd::detail::get_num_args(), sycl::_V1::ext::intel::esimd::detail::to_atomic_op(), and sycl::_V1::ext::intel::esimd::detail::to_lsc_atomic_op().
umin()
template<typename Tp = unsigned> unsigned sycl::_V1::ext::intel::math::umin (Tp x, Tp y)
Definition at line 67 of file imf_integer_utils.hpp.
References __imf_umin().
Referenced by sycl::_V1::ext::intel::esimd::detail::check_atomic(), sycl::_V1::ext::intel::esimd::detail::get_num_args(), sycl::_V1::ext::intel::esimd::detail::to_atomic_op(), and sycl::_V1::ext::intel::esimd::detail::to_lsc_atomic_op().
umul24()
template<typename Tp = unsigned> unsigned sycl::_V1::ext::intel::math::umul24 (Tp x, Tp y)
Definition at line 107 of file imf_integer_utils.hpp.
References __imf_umul24().
umul64hi()
template<typename Tp = unsigned long long> unsigned long long sycl::_V1::ext::intel::math::umul64hi (Tp x, Tp y)
Definition at line 122 of file imf_integer_utils.hpp.
References __imf_umul64hi().
umulhi()
template<typename Tp = unsigned> unsigned sycl::_V1::ext::intel::math::umulhi (Tp x, Tp y)
Definition at line 113 of file imf_integer_utils.hpp.
References __imf_umulhi().
urhadd()
template<typename Tp = unsigned> unsigned sycl::_V1::ext::intel::math::urhadd (Tp x, Tp y)
Definition at line 101 of file imf_integer_utils.hpp.
References __imf_urhadd().
usad()
template<typename Tp = unsigned> unsigned sycl::_V1::ext::intel::math::usad (Tp x, Tp y, Tp z)
Definition at line 137 of file imf_integer_utils.hpp.
References __imf_usad().
ushort2bfloat16_rd()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned short> To sycl::_V1::ext::intel::math::ushort2bfloat16_rd (From x)
Definition at line 882 of file imf_fp_conversions.hpp.
References __imf_ushort2bfloat16_rd().
ushort2bfloat16_rn()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned short> To sycl::_V1::ext::intel::math::ushort2bfloat16_rn (From x)
Definition at line 889 of file imf_fp_conversions.hpp.
References __imf_ushort2bfloat16_rn().
ushort2bfloat16_ru()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned short> To sycl::_V1::ext::intel::math::ushort2bfloat16_ru (From x)
Definition at line 896 of file imf_fp_conversions.hpp.
References __imf_ushort2bfloat16_ru().
ushort2bfloat16_rz()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned short> To sycl::_V1::ext::intel::math::ushort2bfloat16_rz (From x)
Definition at line 903 of file imf_fp_conversions.hpp.
References __imf_ushort2bfloat16_rz().
ushort2half_rd()
template<typename To = sycl::half, typename From = unsigned short> To sycl::_V1::ext::intel::math::ushort2half_rd (From x)
Definition at line 767 of file imf_fp_conversions.hpp.
References __imf_ushort2half_rd().
ushort2half_rn()
template<typename To = sycl::half, typename From = unsigned short> To sycl::_V1::ext::intel::math::ushort2half_rn (From x)
Definition at line 762 of file imf_fp_conversions.hpp.
References __imf_ushort2half_rn().
ushort2half_ru()
template<typename To = sycl::half, typename From = unsigned short> To sycl::_V1::ext::intel::math::ushort2half_ru (From x)
Definition at line 772 of file imf_fp_conversions.hpp.
References __imf_ushort2half_ru().
ushort2half_rz()
template<typename To = sycl::half, typename From = unsigned short> To sycl::_V1::ext::intel::math::ushort2half_rz (From x)
Definition at line 777 of file imf_fp_conversions.hpp.
References __imf_ushort2half_rz().
ushort_as_bfloat16()
template<typename To = sycl::ext::oneapi::bfloat16, typename From = unsigned short> To sycl::_V1::ext::intel::math::ushort_as_bfloat16 (From x)
Definition at line 834 of file imf_fp_conversions.hpp.
References __imf_ushort_as_bfloat16().
vabs2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vabs2 (Tp x)
Definition at line 144 of file imf_simd.hpp.
References __imf_vabs2().
vabs4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vabs4 (Tp x)
Definition at line 149 of file imf_simd.hpp.
References __imf_vabs4().
vabsdiffs2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vabsdiffs2 (Tp x, Tp y)
Definition at line 175 of file imf_simd.hpp.
References __imf_vabsdiffs2().
vabsdiffs4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vabsdiffs4 (Tp x, Tp y)
Definition at line 181 of file imf_simd.hpp.
References __imf_vabsdiffs4().
vabsdiffu2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vabsdiffu2 (Tp x, Tp y)
Definition at line 187 of file imf_simd.hpp.
References __imf_vabsdiffu2().
vabsdiffu4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vabsdiffu4 (Tp x, Tp y)
Definition at line 193 of file imf_simd.hpp.
References __imf_vabsdiffu4().
vabsss2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vabsss2 (Tp x)
Definition at line 198 of file imf_simd.hpp.
References __imf_vabsss2().
vabsss4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vabsss4 (Tp x)
Definition at line 203 of file imf_simd.hpp.
References __imf_vabsss4().
vadd2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vadd2 (Tp x, Tp y)
Definition at line 208 of file imf_simd.hpp.
References __imf_vadd2().
vadd4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vadd4 (Tp x, Tp y)
Definition at line 214 of file imf_simd.hpp.
References __imf_vadd4().
vaddss2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vaddss2 (Tp x, Tp y)
Definition at line 220 of file imf_simd.hpp.
References __imf_vaddss2().
vaddss4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vaddss4 (Tp x, Tp y)
Definition at line 226 of file imf_simd.hpp.
References __imf_vaddss4().
vaddus2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vaddus2 (Tp x, Tp y)
Definition at line 232 of file imf_simd.hpp.
References __imf_vaddus2().
vaddus4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vaddus4 (Tp x, Tp y)
Definition at line 238 of file imf_simd.hpp.
References __imf_vaddus4().
vavgs2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vavgs2 (Tp x, Tp y)
Definition at line 292 of file imf_simd.hpp.
References __imf_vavgs2().
vavgs4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vavgs4 (Tp x, Tp y)
Definition at line 298 of file imf_simd.hpp.
References __imf_vavgs4().
vavgu2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vavgu2 (Tp x, Tp y)
Definition at line 304 of file imf_simd.hpp.
References __imf_vavgu2().
vavgu4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vavgu4 (Tp x, Tp y)
Definition at line 310 of file imf_simd.hpp.
References __imf_vavgu4().
vcmpeq2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vcmpeq2 (Tp x, Tp y)
Definition at line 316 of file imf_simd.hpp.
References __imf_vcmpeq2().
vcmpeq4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vcmpeq4 (Tp x, Tp y)
Definition at line 322 of file imf_simd.hpp.
References __imf_vcmpeq4().
vcmpges2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vcmpges2 (Tp x, Tp y)
Definition at line 329 of file imf_simd.hpp.
References __imf_vcmpges2().
vcmpges4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vcmpges4 (Tp x, Tp y)
Definition at line 335 of file imf_simd.hpp.
References __imf_vcmpges4().
vcmpgeu2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vcmpgeu2 (Tp x, Tp y)
Definition at line 341 of file imf_simd.hpp.
References __imf_vcmpgeu2().
vcmpgeu4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vcmpgeu4 (Tp x, Tp y)
Definition at line 347 of file imf_simd.hpp.
References __imf_vcmpgeu4().
vcmpgts2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vcmpgts2 (Tp x, Tp y)
Definition at line 353 of file imf_simd.hpp.
References __imf_vcmpgts2().
vcmpgts4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vcmpgts4 (Tp x, Tp y)
Definition at line 359 of file imf_simd.hpp.
References __imf_vcmpgts4().
vcmpgtu2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vcmpgtu2 (Tp x, Tp y)
Definition at line 365 of file imf_simd.hpp.
References __imf_vcmpgtu2().
vcmpgtu4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vcmpgtu4 (Tp x, Tp y)
Definition at line 371 of file imf_simd.hpp.
References __imf_vcmpgtu4().
vcmples2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vcmples2 (Tp x, Tp y)
Definition at line 377 of file imf_simd.hpp.
References __imf_vcmples2().
vcmples4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vcmples4 (Tp x, Tp y)
Definition at line 383 of file imf_simd.hpp.
References __imf_vcmples4().
vcmpleu2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vcmpleu2 (Tp x, Tp y)
Definition at line 389 of file imf_simd.hpp.
References __imf_vcmpleu2().
vcmpleu4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vcmpleu4 (Tp x, Tp y)
Definition at line 395 of file imf_simd.hpp.
References __imf_vcmpleu4().
vcmplts2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vcmplts2 (Tp x, Tp y)
Definition at line 401 of file imf_simd.hpp.
References __imf_vcmplts2().
vcmplts4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vcmplts4 (Tp x, Tp y)
Definition at line 407 of file imf_simd.hpp.
References __imf_vcmplts4().
vcmpltu2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vcmpltu2 (Tp x, Tp y)
Definition at line 413 of file imf_simd.hpp.
References __imf_vcmpltu2().
vcmpltu4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vcmpltu4 (Tp x, Tp y)
Definition at line 419 of file imf_simd.hpp.
References __imf_vcmpltu4().
vcmpne2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vcmpne2 (Tp x, Tp y)
Definition at line 424 of file imf_simd.hpp.
References __imf_vcmpne2().
vcmpne4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vcmpne4 (Tp x, Tp y)
Definition at line 430 of file imf_simd.hpp.
References __imf_vcmpne4().
vhaddu2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vhaddu2 (Tp x, Tp y)
Definition at line 280 of file imf_simd.hpp.
References __imf_vhaddu2().
vhaddu4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vhaddu4 (Tp x, Tp y)
Definition at line 286 of file imf_simd.hpp.
References __imf_vhaddu4().
viaddmax_s16x2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::viaddmax_s16x2 (Tp x, Tp y, Tp z)
Definition at line 629 of file imf_simd.hpp.
References __imf_viaddmax_s16x2().
viaddmax_s16x2_relu()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::viaddmax_s16x2_relu (Tp x, Tp y, Tp z)
Definition at line 635 of file imf_simd.hpp.
References __imf_viaddmax_s16x2_relu().
viaddmax_s32()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, int>, int> sycl::_V1::ext::intel::math::viaddmax_s32 (Tp x, Tp y, Tp z)
Definition at line 640 of file imf_simd.hpp.
References __imf_viaddmax_s32().
viaddmax_s32_relu()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, int>, int> sycl::_V1::ext::intel::math::viaddmax_s32_relu (Tp x, Tp y, Tp z)
Definition at line 645 of file imf_simd.hpp.
References __imf_viaddmax_s32_relu().
viaddmax_u16x2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::viaddmax_u16x2 (Tp x, Tp y, Tp z)
Definition at line 652 of file imf_simd.hpp.
References __imf_viaddmax_u16x2().
viaddmax_u32()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::viaddmax_u32 (Tp x, Tp y, Tp z)
Definition at line 658 of file imf_simd.hpp.
References __imf_viaddmax_u32().
viaddmin_s16x2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::viaddmin_s16x2 (Tp x, Tp y, Tp z)
Definition at line 664 of file imf_simd.hpp.
References __imf_viaddmin_s16x2().
viaddmin_s16x2_relu()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::viaddmin_s16x2_relu (Tp x, Tp y, Tp z)
Definition at line 670 of file imf_simd.hpp.
References __imf_viaddmin_s16x2_relu().
viaddmin_s32()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, int>, int> sycl::_V1::ext::intel::math::viaddmin_s32 (Tp x, Tp y, Tp z)
Definition at line 675 of file imf_simd.hpp.
References __imf_viaddmin_s32().
viaddmin_s32_relu()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, int>, int> sycl::_V1::ext::intel::math::viaddmin_s32_relu (Tp x, Tp y, Tp z)
Definition at line 680 of file imf_simd.hpp.
References __imf_viaddmin_s32_relu().
viaddmin_u16x2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::viaddmin_u16x2 (Tp x, Tp y, Tp z)
Definition at line 687 of file imf_simd.hpp.
References __imf_viaddmin_u16x2().
viaddmin_u32()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::viaddmin_u32 (Tp x, Tp y, Tp z)
Definition at line 693 of file imf_simd.hpp.
References __imf_viaddmin_u32().
vibmax_s16x2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vibmax_s16x2 (Tp x, Tp y, bool * p_hi, bool * p_lo)
Definition at line 699 of file imf_simd.hpp.
References __imf_vibmax_s16x2().
vibmax_s32()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, int>, int> sycl::_V1::ext::intel::math::vibmax_s32 (Tp x, Tp y, bool * p)
Definition at line 704 of file imf_simd.hpp.
References __imf_vibmax_s32().
vibmax_u16x2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vibmax_u16x2 (Tp x, Tp y, bool * p_hi, bool * p_lo)
Definition at line 710 of file imf_simd.hpp.
References __imf_vibmax_u16x2().
vibmax_u32()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vibmax_u32 (Tp x, Tp y, bool * p)
Definition at line 716 of file imf_simd.hpp.
References __imf_vibmax_u32().
vibmin_s16x2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vibmin_s16x2 (Tp x, Tp y, bool * p_hi, bool * p_lo)
Definition at line 722 of file imf_simd.hpp.
References __imf_vibmin_s16x2().
vibmin_s32()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, int>, int> sycl::_V1::ext::intel::math::vibmin_s32 (Tp x, Tp y, bool * p)
Definition at line 727 of file imf_simd.hpp.
References __imf_vibmin_s32().
vibmin_u16x2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vibmin_u16x2 (Tp x, Tp y, bool * p_hi, bool * p_lo)
Definition at line 733 of file imf_simd.hpp.
References __imf_vibmin_u16x2().
vibmin_u32()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vibmin_u32 (Tp x, Tp y, bool * p)
Definition at line 739 of file imf_simd.hpp.
References __imf_vibmin_u32().
vimax3_s16x2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vimax3_s16x2 (Tp x, Tp y, Tp z)
Definition at line 745 of file imf_simd.hpp.
References __imf_vimax3_s16x2().
vimax3_s16x2_relu()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vimax3_s16x2_relu (Tp x, Tp y, Tp z)
Definition at line 757 of file imf_simd.hpp.
References __imf_vimax3_s16x2_relu().
vimax3_s32()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, int>, int> sycl::_V1::ext::intel::math::vimax3_s32 (Tp x, Tp y, Tp z)
Definition at line 768 of file imf_simd.hpp.
References __imf_vimax3_s32().
vimax3_s32_relu()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, int>, int> sycl::_V1::ext::intel::math::vimax3_s32_relu (Tp x, Tp y, Tp z)
Definition at line 778 of file imf_simd.hpp.
References __imf_vimax3_s32_relu().
vimax3_u16x2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vimax3_u16x2 (Tp x, Tp y, Tp z)
Definition at line 791 of file imf_simd.hpp.
References __imf_vimax3_u16x2().
vimax3_u32()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vimax3_u32 (Tp x, Tp y, Tp z)
Definition at line 803 of file imf_simd.hpp.
References __imf_vimax3_u32().
vimax_s16x2_relu()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vimax_s16x2_relu (Tp x, Tp y)
Definition at line 820 of file imf_simd.hpp.
References __imf_vimax_s16x2_relu().
vimax_s32_relu()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, int>, int> sycl::_V1::ext::intel::math::vimax_s32_relu (Tp x, Tp y)
Definition at line 814 of file imf_simd.hpp.
References __imf_vimax_s32_relu().
vimin3_s16x2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vimin3_s16x2 (Tp x, Tp y, Tp z)
Definition at line 751 of file imf_simd.hpp.
References __imf_vimin3_s16x2().
vimin3_s16x2_relu()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vimin3_s16x2_relu (Tp x, Tp y, Tp z)
Definition at line 763 of file imf_simd.hpp.
References __imf_vimin3_s16x2_relu().
vimin3_s32()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, int>, int> sycl::_V1::ext::intel::math::vimin3_s32 (Tp x, Tp y, Tp z)
Definition at line 773 of file imf_simd.hpp.
References __imf_vimin3_s32().
vimin3_s32_relu()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, int>, int> sycl::_V1::ext::intel::math::vimin3_s32_relu (Tp x, Tp y, Tp z)
Definition at line 784 of file imf_simd.hpp.
References __imf_vimin3_s32_relu().
vimin3_u16x2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vimin3_u16x2 (Tp x, Tp y, Tp z)
Definition at line 797 of file imf_simd.hpp.
References __imf_vimin3_u16x2().
vimin3_u32()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vimin3_u32 (Tp x, Tp y, Tp z)
Definition at line 809 of file imf_simd.hpp.
References __imf_vimin3_u32().
vimin_s16x2_relu()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vimin_s16x2_relu (Tp x, Tp y)
Definition at line 831 of file imf_simd.hpp.
References __imf_vimin_s16x2_relu().
vimin_s32_relu()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, int>, int> sycl::_V1::ext::intel::math::vimin_s32_relu (Tp x, Tp y)
Definition at line 825 of file imf_simd.hpp.
References __imf_vimin_s32_relu().
vmaxs2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vmaxs2 (Tp x, Tp y)
Definition at line 436 of file imf_simd.hpp.
References __imf_vmaxs2().
vmaxs4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vmaxs4 (Tp x, Tp y)
Definition at line 442 of file imf_simd.hpp.
References __imf_vmaxs4().
vmaxu2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vmaxu2 (Tp x, Tp y)
Definition at line 448 of file imf_simd.hpp.
References __imf_vmaxu2().
vmaxu4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vmaxu4 (Tp x, Tp y)
Definition at line 454 of file imf_simd.hpp.
References __imf_vmaxu4().
vmins2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vmins2 (Tp x, Tp y)
Definition at line 460 of file imf_simd.hpp.
References __imf_vmins2().
vmins4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vmins4 (Tp x, Tp y)
Definition at line 466 of file imf_simd.hpp.
References __imf_vmins4().
vminu2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vminu2 (Tp x, Tp y)
Definition at line 472 of file imf_simd.hpp.
References __imf_vminu2().
vminu4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vminu4 (Tp x, Tp y)
Definition at line 478 of file imf_simd.hpp.
References __imf_vminu4().
vneg2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vneg2 (Tp x)
Definition at line 154 of file imf_simd.hpp.
References __imf_vneg2().
vneg4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vneg4 (Tp x)
Definition at line 159 of file imf_simd.hpp.
References __imf_vneg4().
vnegss2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vnegss2 (Tp x)
Definition at line 164 of file imf_simd.hpp.
References __imf_vnegss2().
vnegss4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vnegss4 (Tp x)
Definition at line 169 of file imf_simd.hpp.
References __imf_vnegss4().
vsads2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsads2 (Tp x, Tp y)
Definition at line 604 of file imf_simd.hpp.
References __imf_vsads2().
vsads4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsads4 (Tp x, Tp y)
Definition at line 610 of file imf_simd.hpp.
References __imf_vsads4().
vsadu2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsadu2 (Tp x, Tp y)
Definition at line 616 of file imf_simd.hpp.
References __imf_vsadu2().
vsadu4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsadu4 (Tp x, Tp y)
Definition at line 622 of file imf_simd.hpp.
References __imf_vsadu4().
vseteq2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vseteq2 (Tp x, Tp y)
Definition at line 484 of file imf_simd.hpp.
References __imf_vseteq2().
vseteq4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vseteq4 (Tp x, Tp y)
Definition at line 490 of file imf_simd.hpp.
References __imf_vseteq4().
vsetges2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsetges2 (Tp x, Tp y)
Definition at line 509 of file imf_simd.hpp.
References __imf_vsetges2().
vsetges4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsetges4 (Tp x, Tp y)
Definition at line 515 of file imf_simd.hpp.
References __imf_vsetges4().
vsetgeu2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsetgeu2 (Tp x, Tp y)
Definition at line 521 of file imf_simd.hpp.
References __imf_vsetgeu2().
vsetgeu4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsetgeu4 (Tp x, Tp y)
Definition at line 527 of file imf_simd.hpp.
References __imf_vsetgeu4().
vsetgts2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsetgts2 (Tp x, Tp y)
Definition at line 533 of file imf_simd.hpp.
References __imf_vsetgts2().
vsetgts4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsetgts4 (Tp x, Tp y)
Definition at line 539 of file imf_simd.hpp.
References __imf_vsetgts4().
vsetgtu2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsetgtu2 (Tp x, Tp y)
Definition at line 545 of file imf_simd.hpp.
References __imf_vsetgtu2().
vsetgtu4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsetgtu4 (Tp x, Tp y)
Definition at line 551 of file imf_simd.hpp.
References __imf_vsetgtu4().
vsetles2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsetles2 (Tp x, Tp y)
Definition at line 557 of file imf_simd.hpp.
References __imf_vsetles2().
vsetles4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsetles4 (Tp x, Tp y)
Definition at line 563 of file imf_simd.hpp.
References __imf_vsetles4().
vsetleu2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsetleu2 (Tp x, Tp y)
Definition at line 569 of file imf_simd.hpp.
References __imf_vsetleu2().
vsetleu4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsetleu4 (Tp x, Tp y)
Definition at line 575 of file imf_simd.hpp.
References __imf_vsetleu4().
vsetlts2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsetlts2 (Tp x, Tp y)
Definition at line 581 of file imf_simd.hpp.
References __imf_vsetlts2().
vsetlts4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsetlts4 (Tp x, Tp y)
Definition at line 587 of file imf_simd.hpp.
References __imf_vsetlts4().
vsetltu2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsetltu2 (Tp x, Tp y)
Definition at line 593 of file imf_simd.hpp.
References __imf_vsetltu2().
vsetltu4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsetltu4 (Tp x, Tp y)
Definition at line 599 of file imf_simd.hpp.
References __imf_vsetltu4().
vsetne2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsetne2 (Tp x, Tp y)
Definition at line 496 of file imf_simd.hpp.
References __imf_vsetne2().
vsetne4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsetne4 (Tp x, Tp y)
Definition at line 502 of file imf_simd.hpp.
References __imf_vsetne4().
vsub2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsub2 (Tp x, Tp y)
Definition at line 244 of file imf_simd.hpp.
References __imf_vsub2().
vsub4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsub4 (Tp x, Tp y)
Definition at line 250 of file imf_simd.hpp.
References __imf_vsub4().
vsubss2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsubss2 (Tp x, Tp y)
Definition at line 256 of file imf_simd.hpp.
References __imf_vsubss2().
vsubss4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsubss4 (Tp x, Tp y)
Definition at line 262 of file imf_simd.hpp.
References __imf_vsubss4().
vsubus2()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsubus2 (Tp x, Tp y)
Definition at line 268 of file imf_simd.hpp.
References __imf_vsubus2().
vsubus4()
template<typename Tp > std::enable_if_t<std::is_same_v<Tp, unsigned int>, unsigned int> sycl::_V1::ext::intel::math::vsubus4 (Tp x, Tp y)
Definition at line 274 of file imf_simd.hpp.
References __imf_vsubus4().