DPC++ Runtime: cl::sycl::detail::enqueue_kernel_launch Namespace Reference
cl::sycl::detail::enqueue_kernel_launch Namespace Reference
Functions
bool handleInvalidWorkGroupSize (const device_impl &DeviceImpl, pi_kernel Kernel, const NDRDescT &NDRDesc)
bool handleInvalidWorkItemSize (const device_impl &DeviceImpl, const NDRDescT &NDRDesc)
bool handleError (pi_result, const device_impl &, pi_kernel, const NDRDescT &)
Analyzes error code and arguments of piEnqueueKernelLaunch to emit user-friendly exception describing the problem.
Function Documentation
handleError()
bool cl::sycl::detail::enqueue_kernel_launch::handleError (pi_result , const device_impl & , pi_kernel , const NDRDescT &)
Analyzes error code and arguments of piEnqueueKernelLaunch to emit user-friendly exception describing the problem.
This function is expected to be called only for non-success error codes, i.e. the first argument must not be equal to PI_SUCCESS.
This function actually never returns and always throws an exception with error description.
Definition at line 271 of file enqueue_kernel.cpp.
References cl::sycl::detail::codeToString(), handleInvalidWorkGroupSize(), handleInvalidWorkItemSize(), PI_IMAGE_FORMAT_NOT_SUPPORTED, PI_INVALID_IMAGE_SIZE, PI_INVALID_KERNEL_ARGS, PI_INVALID_WORK_GROUP_SIZE, PI_INVALID_WORK_ITEM_SIZE, PI_MEM_OBJECT_ALLOCATION_FAILURE, PI_MISALIGNED_SUB_BUFFER_OFFSET, and PI_SUCCESS.
Referenced by cl::sycl::detail::enqueueImpKernel().
handleInvalidWorkGroupSize()
bool cl::sycl::detail::enqueue_kernel_launch::handleInvalidWorkGroupSize (const device_impl & DeviceImpl, pi_kernel Kernel, const NDRDescT & NDRDesc)
Definition at line 25 of file enqueue_kernel.cpp.
References cl::sycl::detail::plugin::call(), cl::sycl::detail::codeToString(), cl::sycl::platform::get_backend(), cl::sycl::detail::device_impl::get_info(), cl::sycl::detail::device_impl::get_platform(), cl::sycl::detail::device_impl::getHandleRef(), cl::sycl::detail::device_impl::getPlugin(), cl::sycl::detail::NDRDescT::GlobalSize, cl::sycl::detail::NDRDescT::LocalSize, cl::sycl::opencl, PI_DEVICE_INFO_MAX_WORK_GROUP_SIZE, PI_DEVICE_INFO_MAX_WORK_ITEM_SIZES, PI_INVALID_WORK_GROUP_SIZE, PI_KERNEL_GROUP_INFO_COMPILE_WORK_GROUP_SIZE, PI_KERNEL_GROUP_INFO_WORK_GROUP_SIZE, PI_KERNEL_INFO_PROGRAM, PI_PROGRAM_BUILD_INFO_OPTIONS, piDeviceGetInfo(), piKernelGetGroupInfo(), piKernelGetInfo(), and piProgramGetBuildInfo().
Referenced by handleError().
handleInvalidWorkItemSize()
bool cl::sycl::detail::enqueue_kernel_launch::handleInvalidWorkItemSize (const device_impl & DeviceImpl, const NDRDescT & NDRDesc)
Definition at line 249 of file enqueue_kernel.cpp.
References cl::sycl::detail::plugin::call(), cl::sycl::detail::NDRDescT::Dims, cl::sycl::detail::device_impl::getHandleRef(), cl::sycl::detail::device_impl::getPlugin(), cl::sycl::detail::NDRDescT::LocalSize, PI_DEVICE_INFO_MAX_WORK_ITEM_SIZES, PI_INVALID_WORK_ITEM_SIZE, and piDeviceGetInfo().
Referenced by handleError().