DPC++ Runtime: sycl::_V1::ext::oneapi Namespace Reference
sycl::_V1::ext::oneapi Namespace Reference
Namespaces
cuda
detail
Objects of the accessor_property_list class are containers for the SYCL properties.
experimental
level_zero
property
this_work_item
Classes
class weak_object
struct is_compile_time_property
class bfloat16
union Us
union Uu
class filter_selector
struct owner_less
struct owner_less< context >
struct owner_less< device >
struct owner_less< event >
struct owner_less< kernel >
struct owner_less< kernel_id >
struct owner_less< platform >
struct owner_less< queue >
struct owner_less< stream >
struct owner_less< device_image< State > >
struct owner_less< kernel_bundle< State > >
struct owner_less< buffer< DataT, Dimensions, AllocatorT > >
struct owner_less< unsampled_image< Dimensions, AllocatorT > >
struct owner_less< sampled_image< Dimensions, AllocatorT > >
struct owner_less< accessor< DataT, Dimensions, AccessMode, AccessTarget, isPlaceholder > >
struct owner_less< host_accessor< DataT, Dimensions, AccessMode > >
struct owner_less< local_accessor< DataT, Dimensions > >
struct owner_less< unsampled_image_accessor< DataT, Dimensions, AccessMode, AccessTarget > >
struct owner_less< host_unsampled_image_accessor< DataT, Dimensions, AccessMode > >
struct owner_less< sampled_image_accessor< DataT, Dimensions, AccessTarget > >
struct owner_less< host_sampled_image_accessor< DataT, Dimensions > >
struct sub_group_mask
class weak_object< buffer< T, Dimensions, AllocatorT > >
class weak_object< stream >
struct is_compile_time_property< ext::oneapi::property::no_offset >
struct is_compile_time_property< ext::oneapi::property::no_alias >
struct is_compile_time_property< sycl::ext::intel::property::buffer_location >
class accessor_property_list
Typedefs
template<typename T = void>
using plus = std::plus< T >
template<typename T = void>
using multiplies = std::multiplies< T >
template<typename T = void>
using bit_or = std::bit_or< T >
template<typename T = void>
using bit_xor = std::bit_xor< T >
template<typename T = void>
using bit_and = std::bit_and< T >
template<typename T = void>
using maximum = sycl::maximum< T >
template<typename T = void>
using minimum = sycl::minimum< T >
Enumerations
enum class peer_access { access_supported = 0x0 , atomics_supported = 0x1 }
Functions
template<typename T >
std::enable_if_t< detail::is_bf16_storage_type< T >::value, T > fabs (T x)
template<typename T >
std::enable_if_t< detail::is_bf16_storage_type< T >::value, T > fmin (T x, T y)
template<typename T >
std::enable_if_t< detail::is_bf16_storage_type< T >::value, T > fmax (T x, T y)
template<typename T >
std::enable_if_t< detail::is_bf16_storage_type< T >::value, T > fma (T x, T y, T z)
int32_t dot_acc (int32_t pa, int32_t pb, int32_t c)
int32_t dot_acc (uint32_t pa, uint32_t pb, int32_t c)
int32_t dot_acc (int32_t pa, uint32_t pb, int32_t c)
int32_t dot_acc (uint32_t pa, int32_t pb, int32_t c)
int32_t dot_acc (vec< int8_t, 4 > a, vec< int8_t, 4 > b, int32_t c)
int32_t dot_acc (vec< uint8_t, 4 > a, vec< uint8_t, 4 > b, int32_t c)
int32_t dot_acc (vec< uint8_t, 4 > a, vec< int8_t, 4 > b, int32_t c)
int32_t dot_acc (vec< int8_t, 4 > a, vec< uint8_t, 4 > b, int32_t c)
template<typename T , typename Group >
std::enable_if_t< std::is_trivially_destructible_v< T > &&sycl::detail::is_group< Group >::value, multi_ptr< T, access::address_space::local_space, access::decorated::legacy > > __SYCL_ALWAYS_INLINE group_local_memory_for_overwrite (Group g)
template<typename T , typename Group , typename... Args>
std::enable_if_t< std::is_trivially_destructible_v< T > &&sycl::detail::is_group< Group >::value, multi_ptr< T, access::address_space::local_space, access::decorated::legacy > > __SYCL_ALWAYS_INLINE group_local_memory (Group g, Args &&...args)
template<typename Group >
std::enable_if_t< std::is_same_v< std::decay_t< Group >, sub_group >||std::is_same_v< std::decay_t< Group >, sycl::sub_group >, sub_group_mask > group_ballot (Group g, bool predicate=true)
Variables
constexpr property::no_offset::instance no_offset
constexpr property::no_alias::instance no_alias
Typedef Documentation
bit_and
template<typename T = void> using sycl::_V1::ext::oneapi::bit_and = typedef std::bit_and<T>
Definition at line 24 of file functional.hpp.
bit_or
template<typename T = void> using sycl::_V1::ext::oneapi::bit_or = typedef std::bit_or<T>
Definition at line 22 of file functional.hpp.
bit_xor
template<typename T = void> using sycl::_V1::ext::oneapi::bit_xor = typedef std::bit_xor<T>
Definition at line 23 of file functional.hpp.
maximum
template<typename T = void> using sycl::_V1::ext::oneapi::maximum = typedef sycl::maximum<T>
Definition at line 25 of file functional.hpp.
minimum
template<typename T = void> using sycl::_V1::ext::oneapi::minimum = typedef sycl::minimum<T>
Definition at line 26 of file functional.hpp.
multiplies
template<typename T = void> using sycl::_V1::ext::oneapi::multiplies = typedef std::multiplies<T>
Definition at line 21 of file functional.hpp.
plus
template<typename T = void> using sycl::_V1::ext::oneapi::plus = typedef std::plus<T>
Definition at line 20 of file functional.hpp.
Enumeration Type Documentation
peer_access
enum sycl::_V1::ext::oneapi::peer_access strong
Enumerator
access_supported
atomics_supported
Definition at line 53 of file device.hpp.
Function Documentation
dot_acc() [1/8]
int32_t sycl::_V1::ext::oneapi::dot_acc (int32_t pa, int32_t pb, int32_t c)
Definition at line 29 of file dot_product.hpp.
dot_acc() [2/8]
int32_t sycl::_V1::ext::oneapi::dot_acc (int32_t pa, uint32_t pb, int32_t c)
Definition at line 43 of file dot_product.hpp.
dot_acc() [3/8]
int32_t sycl::_V1::ext::oneapi::dot_acc (uint32_t pa, int32_t pb, int32_t c)
Definition at line 50 of file dot_product.hpp.
dot_acc() [4/8]
int32_t sycl::_V1::ext::oneapi::dot_acc (uint32_t pa, uint32_t pb, int32_t c)
Definition at line 36 of file dot_product.hpp.
dot_acc() [5/8]
int32_t sycl::_V1::ext::oneapi::dot_acc (vec< int8_t, 4 > a, vec< int8_t, 4 > b, int32_t c)
Definition at line 57 of file dot_product.hpp.
dot_acc() [6/8]
int32_t sycl::_V1::ext::oneapi::dot_acc (vec< int8_t, 4 > a, vec< uint8_t, 4 > b, int32_t c)
Definition at line 72 of file dot_product.hpp.
dot_acc() [7/8]
int32_t sycl::_V1::ext::oneapi::dot_acc (vec< uint8_t, 4 > a, vec< int8_t, 4 > b, int32_t c)
Definition at line 67 of file dot_product.hpp.
dot_acc() [8/8]
int32_t sycl::_V1::ext::oneapi::dot_acc (vec< uint8_t, 4 > a, vec< uint8_t, 4 > b, int32_t c)
Definition at line 62 of file dot_product.hpp.
fabs()
template<typename T > std::enable_if_t<detail::is_bf16_storage_type<T>::value, T> sycl::_V1::ext::oneapi::fabs (T x)
Definition at line 47 of file bf16_storage_builtins.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::acos(), sycl::_V1::ext::oneapi::experimental::acosh(), sycl::_V1::ext::oneapi::experimental::atanh(), sycl::_V1::ext::oneapi::experimental::cosh(), sycl::_V1::detail::getPixelCoordLinearFiltMode(), sycl::_V1::detail::getPixelCoordNearestFiltMode(), sycl::_V1::ext::intel::math::habs(), sycl::_V1::ext::intel::math::habs2(), sycl::_V1::ext::oneapi::experimental::norm(), sycl::_V1::ext::oneapi::detail::wi_element< sycl::ext::oneapi::bfloat16, NumRows, NumCols, Use, Layout, Group >::operator bool(), and sycl::_V1::ext::oneapi::experimental::proj().
fma()
template<typename T > std::enable_if_t<detail::is_bf16_storage_type<T>::value, T> sycl::_V1::ext::oneapi::fma (T x, T y, T z)
Definition at line 79 of file bf16_storage_builtins.hpp.
fmax()
template<typename T > std::enable_if_t<detail::is_bf16_storage_type<T>::value, T> sycl::_V1::ext::oneapi::fmax (T x, T y)
Definition at line 68 of file bf16_storage_builtins.hpp.
Referenced by sycl::_V1::ext::intel::esimd::detail::check_atomic(), sycl::_V1::ext::intel::esimd::detail::get_num_args(), sycl::_V1::ext::intel::esimd::detail::to_atomic_op(), and sycl::_V1::ext::intel::esimd::detail::to_lsc_atomic_op().
fmin()
template<typename T > std::enable_if_t<detail::is_bf16_storage_type<T>::value, T> sycl::_V1::ext::oneapi::fmin (T x, T y)
Definition at line 57 of file bf16_storage_builtins.hpp.
Referenced by sycl::_V1::ext::intel::esimd::detail::check_atomic(), sycl::_V1::ext::intel::esimd::detail::get_num_args(), sycl::_V1::ext::intel::esimd::detail::to_atomic_op(), and sycl::_V1::ext::intel::esimd::detail::to_lsc_atomic_op().
group_ballot()
template<typename Group > std::enable_if_t< std::is_same_v< std::decay_t< Group >, sub_group >||std::is_same_v< std::decay_t< Group >, sycl::sub_group >, sub_group_mask > sycl::_V1::ext::oneapi::group_ballot (Group g, bool predicate = true)
Definition at line 341 of file sub_group_mask.hpp.
Referenced by sycl::_V1::ext::oneapi::experimental::get_ballot_group(), sycl::_V1::ext::oneapi::experimental::this_kernel::get_opportunistic_group(), and sycl::_V1::ext::oneapi::experimental::get_tangle_group().
group_local_memory()
template<typename T , typename Group , typename... Args> std::enable_if_t< std::is_trivially_destructible_v<T> && sycl::detail::is_group<Group>::value, multi_ptr<T, access::address_space::local_space, access::decorated::legacy> > __SYCL_ALWAYS_INLINE sycl::_V1::ext::oneapi::group_local_memory (Group g, Args &&... args)
Definition at line 56 of file group_local_memory.hpp.
References sycl::_V1::ext::oneapi::experimental::__attribute__(), and sycl::_V1::detail::workGroupBarrier().
group_local_memory_for_overwrite()
template<typename T , typename Group > std::enable_if_t< std::is_trivially_destructible_v<T> && sycl::detail::is_group<Group>::value, multi_ptr<T, access::address_space::local_space, access::decorated::legacy> > __SYCL_ALWAYS_INLINE sycl::_V1::ext::oneapi::group_local_memory_for_overwrite (Group g)
Definition at line 33 of file group_local_memory.hpp.
References sycl::_V1::ext::oneapi::experimental::__attribute__(), and sycl::_V1::detail::workGroupBarrier().
Variable Documentation
no_alias
constexpr property::no_alias::instance sycl::_V1::ext::oneapi::no_alias inline constexpr
Definition at line 84 of file accessor_properties.hpp.
no_offset
constexpr property::no_offset::instance sycl::_V1::ext::oneapi::no_offset inline constexpr
Definition at line 83 of file accessor_properties.hpp.