DPC++ Runtime: sycl::_V1::opencl Namespace Reference
sycl::_V1::opencl Namespace Reference
Typedefs
using cl_bool = bool
using cl_char = std::int8_t
using cl_uchar = std::uint8_t
using cl_short = std::int16_t
using cl_ushort = std::uint16_t
using cl_int = std::int32_t
using cl_uint = std::uint32_t
using cl_long = std::int64_t
using cl_ulong = std::uint64_t
using cl_half = half
using cl_float = float
using cl_double = double
Functions
platform make_platform (pi_native_handle NativeHandle)
device make_device (pi_native_handle NativeHandle)
context make_context (pi_native_handle NativeHandle)
queue make_queue (const context &Context, pi_native_handle InteropHandle)
bool has_extension (const sycl::platform &SyclPlatform, const std::string &Extension)
bool has_extension (const sycl::device &SyclDevice, const std::string &Extension)
template<typename T , typename std::enable_if_t< std::is_same_v< T, platform >> * = nullptr>
T make (typename detail::interop< backend::opencl, T >::type Interop)
template<typename T , typename std::enable_if_t< std::is_same_v< T, queue >> * = nullptr>
T make (const context &Context, typename detail::interop< backend::opencl, T >::type Interop)
Typedef Documentation
cl_bool
using sycl::_V1::opencl::cl_bool = typedef bool
Definition at line 129 of file aliases.hpp.
cl_char
using sycl::_V1::opencl::cl_char = typedef std::int8_t
Definition at line 130 of file aliases.hpp.
cl_double
using sycl::_V1::opencl::cl_double = typedef double
Definition at line 140 of file aliases.hpp.
cl_float
using sycl::_V1::opencl::cl_float = typedef float
Definition at line 139 of file aliases.hpp.
cl_half
using sycl::_V1::opencl::cl_half = typedef half
Definition at line 138 of file aliases.hpp.
cl_int
using sycl::_V1::opencl::cl_int = typedef std::int32_t
Definition at line 134 of file aliases.hpp.
cl_long
using sycl::_V1::opencl::cl_long = typedef std::int64_t
Definition at line 136 of file aliases.hpp.
cl_short
using sycl::_V1::opencl::cl_short = typedef std::int16_t
Definition at line 132 of file aliases.hpp.
cl_uchar
using sycl::_V1::opencl::cl_uchar = typedef std::uint8_t
Definition at line 131 of file aliases.hpp.
cl_uint
using sycl::_V1::opencl::cl_uint = typedef std::uint32_t
Definition at line 135 of file aliases.hpp.
cl_ulong
using sycl::_V1::opencl::cl_ulong = typedef std::uint64_t
Definition at line 137 of file aliases.hpp.
cl_ushort
using sycl::_V1::opencl::cl_ushort = typedef std::uint16_t
Definition at line 133 of file aliases.hpp.
Function Documentation
has_extension() [1/2]
bool sycl::_V1::opencl::has_extension (const sycl::device & SyclDevice, const std::string & Extension)
Definition at line 85 of file opencl.cpp.
References sycl::_V1::backend_mismatch, sycl::_V1::device::get_backend(), sycl::_V1::detail::getSyclObjImpl(), PI_DEVICE_INFO_EXTENSIONS, and piDeviceGetInfo().
has_extension() [2/2]
bool sycl::_V1::opencl::has_extension (const sycl::platform & SyclPlatform, const std::string & Extension)
Definition at line 54 of file opencl.cpp.
References sycl::_V1::backend_mismatch, sycl::_V1::platform::get_backend(), sycl::_V1::detail::getSyclObjImpl(), PI_PLATFORM_INFO_EXTENSIONS, and piPlatformGetInfo().
make() [1/2]
template<typename T , typename std::enable_if_t< std::is_same_v< T, queue >> * = nullptr> T sycl::_V1::opencl::make (const context & Context, typename detail::interop< backend::opencl, T >::type Interop)
Definition at line 71 of file opencl.hpp.
References make_queue().
make() [2/2]
template<typename T , typename std::enable_if_t< std::is_same_v< T, platform >> * = nullptr> T sycl::_V1::opencl::make (typename detail::interop< backend::opencl, T >::type Interop)
Definition at line 47 of file opencl.hpp.
References make_platform().
make_context()
context sycl::_V1::opencl::make_context (pi_native_handle NativeHandle)
Definition at line 38 of file opencl.cpp.
References sycl::_V1::detail::defaultAsyncHandler(), sycl::_V1::detail::make_context(), and sycl::_V1::opencl.
make_device()
device sycl::_V1::opencl::make_device (pi_native_handle NativeHandle)
Definition at line 32 of file opencl.cpp.
References sycl::_V1::detail::make_device(), and sycl::_V1::opencl.
make_platform()
platform sycl::_V1::opencl::make_platform (pi_native_handle NativeHandle)
Definition at line 26 of file opencl.cpp.
References sycl::_V1::detail::make_platform(), and sycl::_V1::opencl.
Referenced by make().
make_queue()
queue sycl::_V1::opencl::make_queue (const context & Context, pi_native_handle InteropHandle)
Definition at line 45 of file opencl.cpp.
References sycl::_V1::detail::getSyclObjImpl(), sycl::_V1::detail::make_queue(), and sycl::_V1::opencl.
Referenced by make().