DPC++ Runtime: sycl::_V1::detail::pi Namespace Reference
sycl::_V1::detail::pi Namespace Reference
Classes
struct PiFuncInfo
struct IsStdVector
struct IsStdVector< std::vector< T > >
struct printOut
struct printOut< PiEvent * >
struct printOut< PiMem * >
struct printOut< void * >
struct printOut< T ** >
Typedefs
using PiPlugin = ::pi_plugin
using PiResult = ::pi_result
using PiPlatform = ::pi_platform
using PiPlatformBackend = ::pi_platform_backend
using PiDevice = ::pi_device
using PiDeviceType = ::pi_device_type
using PiDeviceInfo = ::pi_device_info
using PiDeviceBinaryType = ::pi_device_binary_type
using PiContext = ::pi_context
using PiContextInfo = ::pi_context_info
using PiProgram = ::pi_program
using PiKernel = ::pi_kernel
using PiQueue = ::pi_queue
using PiQueueProperties = ::pi_queue_properties
using PiMem = ::pi_mem
using PiMemFlags = ::pi_mem_flags
using PiEvent = ::pi_event
using PiSampler = ::pi_sampler
using PiSamplerInfo = ::pi_sampler_info
using PiSamplerProperties = ::pi_sampler_properties
using PiSamplerAddressingMode = ::pi_sampler_addressing_mode
using PiSamplerFilterMode = ::pi_sampler_filter_mode
using PiMemImageFormat = ::pi_image_format
using PiMemImageDesc = ::pi_image_desc
using PiMemImageInfo = ::pi_image_info
using PiMemObjectType = ::pi_mem_type
using PiMemImageChannelOrder = ::pi_image_channel_order
using PiMemImageChannelType = ::pi_image_channel_type
using PiKernelCacheConfig = ::pi_kernel_cache_config
using PiExtSyncPoint = ::pi_ext_sync_point
using PiExtCommandBuffer = ::pi_ext_command_buffer
using PiExtCommandBufferDesc = ::pi_ext_command_buffer_desc
using PiExtCommandBufferCommand = ::pi_ext_command_buffer_command
using PiPeerAttr = ::pi_peer_attr
using PiImageHandle = ::pi_image_handle
using PiImageMemHandle = ::pi_image_mem_handle
using PiImageCopyFlags = ::pi_image_copy_flags
using PiInteropMemHandle = ::pi_interop_mem_handle
using PiInteropSemaphoreHandle = ::pi_interop_semaphore_handle
using PiImageOffset = ::pi_image_offset_struct
using PiImageRegion = ::pi_image_region_struct
Enumerations
enum TraceLevel { PI_TRACE_BASIC = 0x1 , PI_TRACE_CALLS = 0x2 , PI_TRACE_ALL = -1 }
Functions
template<class To >
To cast (std::vector< cl_event > value)
template<>
PiDevice cast (cl_device_id)=delete
bool trace (TraceLevel level)
void die (const char *Message)
void assertion (bool Condition, const char *Message=nullptr)
template<typename T >
void handleUnknownParamName (const char *functionName, T parameter)
void contextSetExtendedDeleter (const sycl::context &constext, pi_context_extended_deleter func, void *user_data)
void * loadOsLibrary (const std::string &Library)
int unloadOsLibrary (void *Library)
void * loadOsPluginLibrary (const std::string &Library)
int unloadOsPluginLibrary (void *Library)
int unloadPlugin (void *Library)
void * getOsLibraryFuncAddress (void *Library, const std::string &FunctionName)
std::string platformInfoToString (pi_platform_info info)
template<class To , class From >
To cast (From value)
std::vector< PluginPtr > & initialize ()
template<backend BE>
const PluginPtr & getPlugin ()
uint64_t emitFunctionBeginTrace (const char *FName)
Emits an XPTI trace before a PI API call is made.
void emitFunctionEndTrace (uint64_t CorrelationID, const char *FName)
Emits an XPTI trace after the PI API call has been made.
uint64_t emitFunctionWithArgsBeginTrace (uint32_t FuncID, const char *FName, unsigned char *ArgsData, pi_plugin Plugin)
Notifies XPTI subscribers about PI function calls and packs call arguments.
void emitFunctionWithArgsEndTrace (uint64_t CorrelationID, uint32_t FuncID, const char *FName, unsigned char *ArgsData, pi_result Result, pi_plugin Plugin)
Notifies XPTI subscribers about PI function call result.
PiDeviceBinaryType getBinaryImageFormat (const unsigned char *ImgData, size_t ImgSize)
Tries to determine the device binary image foramat.
template<class To , class FromE >
To cast (std::vector< FromE > Values)
static void initializePlugins (std::vector< PluginPtr > &Plugins)
std::string memFlagToString (pi_mem_flags Flag)
std::string memFlagsToString (pi_mem_flags Flags)
std::vector< std::pair< std::string, backend > > findPlugins ()
void * loadPlugin (const std::string &PluginPath)
bool bindPlugin (void *Library, const std::shared_ptr< PiPlugin > &PluginInformation)
std::vector< std::tuple< std::string, backend, void * > > loadPlugins (const std::vector< std::pair< std::string, backend >> &&PluginNames)
template const PluginPtr & getPlugin< backend::opencl > ()
template const PluginPtr & getPlugin< backend::ext_oneapi_level_zero > ()
template const PluginPtr & getPlugin< backend::ext_intel_esimd_emulator > ()
template const PluginPtr & getPlugin< backend::ext_oneapi_cuda > ()
template const PluginPtr & getPlugin< backend::ext_oneapi_hip > ()
template<typename ResT >
static ResT readELFValue (const unsigned char *Data, size_t NumBytes, bool IsBigEndian)
static bool checkELFSectionPresent (const std::string &ExpectedSectionName, const unsigned char *ImgData, size_t ImgSize)
static uint16_t getELFHeaderType (const unsigned char *ImgData, size_t ImgSize)
template<typename T >
std::enable_if<!std::is_pointer< T >::value, void >::type print (T val)
template<typename T >
std::enable_if< std::is_pointer< T >::value, void >::type print (T val)
template<>
void print (PiPlatform val)
template<>
void print (PiEvent val)
template<>
void print (PiMem val)
template<>
void print (PiEvent *val)
template<>
void print (const PiEvent *val)
template<>
void print (pi_buffer_region rgn)
template<>
void print (pi_buff_rect_region rgn)
template<>
void print (pi_buff_rect_offset off)
template<>
void print (pi_image_region rgn)
template<>
void print (pi_image_offset off)
template<>
void print (const pi_image_desc *desc)
template<>
void print (PiResult val)
template<>
void print (std::nullptr_t)
template<>
void print (char *val)
template<>
void print (const char *val)
void printArgs (void)
template<typename Arg0 , typename... Args>
void printArgs (Arg0 arg0, Args... args)
void printOuts (void)
template<typename Arg0 , typename... Args>
void printOuts (Arg0 arg0, Args... args)
static std::filesystem::path getCurrentDSODirPath ()
Variables
template<>
PiProgram cast (cl_program)=delete
std::shared_ptr< plugin > GlobalPlugin
bool XPTIInitDone = false
Typedef Documentation
PiContext
using sycl::_V1::detail::pi::PiContext = typedef ::pi_context
Definition at line 135 of file pi.hpp.
PiContextInfo
using sycl::_V1::detail::pi::PiContextInfo = typedef ::pi_context_info
Definition at line 136 of file pi.hpp.
PiDevice
using sycl::_V1::detail::pi::PiDevice = typedef ::pi_device
Definition at line 131 of file pi.hpp.
PiDeviceBinaryType
using sycl::_V1::detail::pi::PiDeviceBinaryType = typedef ::pi_device_binary_type
Definition at line 134 of file pi.hpp.
PiDeviceInfo
using sycl::_V1::detail::pi::PiDeviceInfo = typedef ::pi_device_info
Definition at line 133 of file pi.hpp.
PiDeviceType
using sycl::_V1::detail::pi::PiDeviceType = typedef ::pi_device_type
Definition at line 132 of file pi.hpp.
PiEvent
using sycl::_V1::detail::pi::PiEvent = typedef ::pi_event
Definition at line 143 of file pi.hpp.
PiExtCommandBuffer
using sycl::_V1::detail::pi::PiExtCommandBuffer = typedef ::pi_ext_command_buffer
Definition at line 157 of file pi.hpp.
PiExtCommandBufferCommand
using sycl::_V1::detail::pi::PiExtCommandBufferCommand = typedef ::pi_ext_command_buffer_command
Definition at line 159 of file pi.hpp.
PiExtCommandBufferDesc
using sycl::_V1::detail::pi::PiExtCommandBufferDesc = typedef ::pi_ext_command_buffer_desc
Definition at line 158 of file pi.hpp.
PiExtSyncPoint
using sycl::_V1::detail::pi::PiExtSyncPoint = typedef ::pi_ext_sync_point
Definition at line 156 of file pi.hpp.
PiImageCopyFlags
using sycl::_V1::detail::pi::PiImageCopyFlags = typedef ::pi_image_copy_flags
Definition at line 163 of file pi.hpp.
PiImageHandle
using sycl::_V1::detail::pi::PiImageHandle = typedef ::pi_image_handle
Definition at line 161 of file pi.hpp.
PiImageMemHandle
using sycl::_V1::detail::pi::PiImageMemHandle = typedef ::pi_image_mem_handle
Definition at line 162 of file pi.hpp.
PiImageOffset
using sycl::_V1::detail::pi::PiImageOffset = typedef ::pi_image_offset_struct
Definition at line 166 of file pi.hpp.
PiImageRegion
using sycl::_V1::detail::pi::PiImageRegion = typedef ::pi_image_region_struct
Definition at line 167 of file pi.hpp.
PiInteropMemHandle
using sycl::_V1::detail::pi::PiInteropMemHandle = typedef ::pi_interop_mem_handle
Definition at line 164 of file pi.hpp.
PiInteropSemaphoreHandle
using sycl::_V1::detail::pi::PiInteropSemaphoreHandle = typedef ::pi_interop_semaphore_handle
Definition at line 165 of file pi.hpp.
PiKernel
using sycl::_V1::detail::pi::PiKernel = typedef ::pi_kernel
Definition at line 138 of file pi.hpp.
PiKernelCacheConfig
using sycl::_V1::detail::pi::PiKernelCacheConfig = typedef ::pi_kernel_cache_config
Definition at line 155 of file pi.hpp.
PiMem
using sycl::_V1::detail::pi::PiMem = typedef ::pi_mem
Definition at line 141 of file pi.hpp.
PiMemFlags
using sycl::_V1::detail::pi::PiMemFlags = typedef ::pi_mem_flags
Definition at line 142 of file pi.hpp.
PiMemImageChannelOrder
using sycl::_V1::detail::pi::PiMemImageChannelOrder = typedef ::pi_image_channel_order
Definition at line 153 of file pi.hpp.
PiMemImageChannelType
using sycl::_V1::detail::pi::PiMemImageChannelType = typedef ::pi_image_channel_type
Definition at line 154 of file pi.hpp.
PiMemImageDesc
using sycl::_V1::detail::pi::PiMemImageDesc = typedef ::pi_image_desc
Definition at line 150 of file pi.hpp.
PiMemImageFormat
using sycl::_V1::detail::pi::PiMemImageFormat = typedef ::pi_image_format
Definition at line 149 of file pi.hpp.
PiMemImageInfo
using sycl::_V1::detail::pi::PiMemImageInfo = typedef ::pi_image_info
Definition at line 151 of file pi.hpp.
PiMemObjectType
using sycl::_V1::detail::pi::PiMemObjectType = typedef ::pi_mem_type
Definition at line 152 of file pi.hpp.
PiPeerAttr
using sycl::_V1::detail::pi::PiPeerAttr = typedef ::pi_peer_attr
Definition at line 160 of file pi.hpp.
PiPlatform
using sycl::_V1::detail::pi::PiPlatform = typedef ::pi_platform
Definition at line 129 of file pi.hpp.
PiPlatformBackend
using sycl::_V1::detail::pi::PiPlatformBackend = typedef ::pi_platform_backend
Definition at line 130 of file pi.hpp.
PiPlugin
using sycl::_V1::detail::pi::PiPlugin = typedef ::pi_plugin
Definition at line 127 of file pi.hpp.
PiProgram
using sycl::_V1::detail::pi::PiProgram = typedef ::pi_program
Definition at line 137 of file pi.hpp.
PiQueue
using sycl::_V1::detail::pi::PiQueue = typedef ::pi_queue
Definition at line 139 of file pi.hpp.
PiQueueProperties
using sycl::_V1::detail::pi::PiQueueProperties = typedef ::pi_queue_properties
Definition at line 140 of file pi.hpp.
PiResult
using sycl::_V1::detail::pi::PiResult = typedef ::pi_result
Definition at line 128 of file pi.hpp.
PiSampler
using sycl::_V1::detail::pi::PiSampler = typedef ::pi_sampler
Definition at line 144 of file pi.hpp.
PiSamplerAddressingMode
using sycl::_V1::detail::pi::PiSamplerAddressingMode = typedef ::pi_sampler_addressing_mode
Definition at line 147 of file pi.hpp.
PiSamplerFilterMode
using sycl::_V1::detail::pi::PiSamplerFilterMode = typedef ::pi_sampler_filter_mode
Definition at line 148 of file pi.hpp.
PiSamplerInfo
using sycl::_V1::detail::pi::PiSamplerInfo = typedef ::pi_sampler_info
Definition at line 145 of file pi.hpp.
PiSamplerProperties
using sycl::_V1::detail::pi::PiSamplerProperties = typedef ::pi_sampler_properties
Definition at line 146 of file pi.hpp.
Enumeration Type Documentation
TraceLevel
enum sycl::_V1::detail::pi::TraceLevel
Enumerator
PI_TRACE_BASIC
PI_TRACE_CALLS
PI_TRACE_ALL
Definition at line 57 of file pi.hpp.
Function Documentation
assertion()
void sycl::_V1::detail::pi::assertion (bool Condition, const char * Message = nullptr)
Definition at line 531 of file pi.cpp.
References die().
Referenced by cast(), and memFlagToString().
bindPlugin()
bool sycl::_V1::detail::pi::bindPlugin (void * Library, const std::shared_ptr< PiPlugin > & PluginInformation)
Definition at line 346 of file pi.cpp.
References getOsLibraryFuncAddress(), and piPluginInit().
Referenced by initializePlugins().
cast() [1/4]
template<> PiDevice sycl::_V1::detail::pi::cast (cl_device_id) inline delete
cast() [2/4]
template<class To , class From > To sycl::_V1::detail::pi::cast (From value) inline
Definition at line 278 of file pi.hpp.
References assertion().
cast() [3/4]
template<class To > To sycl::_V1::detail::pi::cast (std::vector< cl_event > value) inline
Definition at line 145 of file backend_traits_opencl.hpp.
References assertion().
cast() [4/4]
template<class To , class FromE > To sycl::_V1::detail::pi::cast (std::vector< FromE > Values)
Definition at line 291 of file pi.hpp.
checkELFSectionPresent()
static bool sycl::_V1::detail::pi::checkELFSectionPresent (const std::string & ExpectedSectionName, const unsigned char * ImgData, size_t ImgSize) static
Definition at line 553 of file pi.cpp.
Referenced by getBinaryImageFormat().
contextSetExtendedDeleter()
void sycl::_V1::detail::pi::contextSetExtendedDeleter (const sycl::context & constext, pi_context_extended_deleter func, void * user_data)
Definition at line 193 of file pi.cpp.
References sycl::_V1::detail::getSyclObjImpl(), and piextContextSetExtendedDeleter().
die()
void sycl::_V1::detail::pi::die (const char * Message)
Definition at line 526 of file pi.cpp.
References std::cerr.
Referenced by assertion(), DieUnsupported(), handleUnknownParamName(), pi2ur::pi2urImageCopyFlags(), pi2ur::pi2urImageDesc(), pi2ur::pi2urImageInfoFlags(), pi2ur::piContextGetInfo(), pi2ur::piDevicePartition(), pi2ur::piEnqueueMemImageFill(), pi2ur::piEventSetCallback(), pi2ur::piEventSetStatus(), piextEnqueueReadHostPipe(), piextEnqueueWriteHostPipe(), pi2ur::piextUSMEnqueueMemset2D(), pi2ur::piextUSMGetMemAllocInfo(), pi2ur::piKernelGetGroupInfo(), pi2ur::piKernelSetExecInfo(), pi2ur::piMemGetInfo(), pi2ur::piPlatformGetInfo(), pi2ur::piProgramGetBuildInfo(), pi2ur::piProgramGetInfo(), pi2ur::piQueueGetInfo(), platformInfoToString(), ur2piDeviceInfoValue(), pi2ur::ur2piImageFormat(), ur2piPlatformInfoValue(), ur2piProgramBuildInfoValue(), ur2piSamplerInfoValue(), and ur2piUSMAllocInfoValue().
emitFunctionBeginTrace()
uint64_t sycl::_V1::detail::pi::emitFunctionBeginTrace (const char * FName)
Emits an XPTI trace before a PI API call is made.
Parameters
FName The name of the PI API call
Returns
The correlation ID for the API call that is to be used by the emitFunctionEndTrace() call
Definition at line 82 of file pi.cpp.
Referenced by sycl::_V1::detail::plugin::call_nocheck().
emitFunctionEndTrace()
void sycl::_V1::detail::pi::emitFunctionEndTrace (uint64_t CorrelationID, const char * FName)
Emits an XPTI trace after the PI API call has been made.
Parameters
CorrelationID The correlation ID for the API call generated by the emitFunctionBeginTrace() call.
FName The name of the PI API call
Definition at line 127 of file pi.cpp.
Referenced by sycl::_V1::detail::plugin::call_nocheck().
emitFunctionWithArgsBeginTrace()
uint64_t sycl::_V1::detail::pi::emitFunctionWithArgsBeginTrace (uint32_t FuncID, const char * FName, unsigned char * ArgsData, pi_plugin Plugin)
Notifies XPTI subscribers about PI function calls and packs call arguments.
Parameters
FuncID is the API hash ID from PiApiID type trait.
FName The name of the PI API call.
ArgsData is a pointer to packed function call arguments.
Plugin is the plugin, which is used to make call.
Definition at line 143 of file pi.cpp.
References sycl::_V1::detail::tls_code_loc_t::query().
Referenced by sycl::_V1::detail::plugin::call_nocheck().
emitFunctionWithArgsEndTrace()
void sycl::_V1::detail::pi::emitFunctionWithArgsEndTrace (uint64_t CorrelationID, uint32_t FuncID, const char * FName, unsigned char * ArgsData, pi_result Result, pi_plugin Plugin)
Notifies XPTI subscribers about PI function call result.
Parameters
CorrelationID The correlation ID for the API call generated by the emitFunctionWithArgsBeginTrace() call.
FuncID is the API hash ID from PiApiID type trait.
FName The name of the PI API call.
ArgsData is a pointer to packed function call arguments.
Result is function call result value.
Plugin is the plugin, which is used to make call.
Definition at line 175 of file pi.cpp.
Referenced by sycl::_V1::detail::plugin::call_nocheck().
findPlugins()
std::vector<std::pair<std::string, backend> > sycl::_V1::detail::pi::findPlugins ()
Definition at line 286 of file pi.cpp.
References sycl::_V1::all, sycl::_V1::detail::ods_target_list::backendCompatible(), sycl::_V1::ext_oneapi_cuda, sycl::_V1::ext_oneapi_hip, sycl::_V1::ext_oneapi_level_zero, sycl::_V1::ext_oneapi_native_cpu, sycl::_V1::detail::SYCLConfig< Config >::get(), and sycl::_V1::opencl.
Referenced by initializePlugins().
getBinaryImageFormat()
sycl::detail::pi::PiDeviceBinaryType sycl::_V1::detail::pi::getBinaryImageFormat (const unsigned char * ImgData, size_t ImgSize)
Tries to determine the device binary image foramat.
Returns PI_DEVICE_BINARY_TYPE_NONE if unsuccessful.
Definition at line 626 of file pi.cpp.
References checkELFSectionPresent(), getELFHeaderType(), PI_DEVICE_BINARY_TYPE_LLVMIR_BITCODE, PI_DEVICE_BINARY_TYPE_NATIVE, PI_DEVICE_BINARY_TYPE_NONE, and PI_DEVICE_BINARY_TYPE_SPIRV.
Referenced by sycl::_V1::detail::ProgramManager::createPIProgram(), sycl::_V1::detail::DynRTDeviceBinaryImage::DynRTDeviceBinaryImage(), and sycl::_V1::detail::RTDeviceBinaryImage::init().
getCurrentDSODirPath()
static std::filesystem::path sycl::_V1::detail::pi::getCurrentDSODirPath () static
Definition at line 71 of file windows_pi.cpp.
References ExeModuleHandle, and getOSModuleHandle().
getELFHeaderType()
static uint16_t sycl::_V1::detail::pi::getELFHeaderType (const unsigned char * ImgData, size_t ImgSize) static
Definition at line 617 of file pi.cpp.
Referenced by getBinaryImageFormat().
getOsLibraryFuncAddress()
void * sycl::_V1::detail::pi::getOsLibraryFuncAddress (void * Library, const std::string & FunctionName)
Definition at line 47 of file posix_pi.cpp.
Referenced by sycl::_V1::ext::__SYCL2020_DEPRECATED(), bindPlugin(), sycl::_V1::ext::oneapi::experimental::detail::checkOclocLibrary(), and sycl::_V1::ext::oneapi::experimental::detail::SetupLibrary().
getPlugin()
template<backend BE> const PluginPtr & sycl::_V1::detail::pi::getPlugin ()
Definition at line 498 of file pi.cpp.
References initialize().
getPlugin< backend::ext_intel_esimd_emulator >()
template const PluginPtr& sycl::_V1::detail::pi::getPlugin< backend::ext_intel_esimd_emulator > ()
getPlugin< backend::ext_oneapi_cuda >()
template const PluginPtr& sycl::_V1::detail::pi::getPlugin< backend::ext_oneapi_cuda > ()
getPlugin< backend::ext_oneapi_hip >()
template const PluginPtr& sycl::_V1::detail::pi::getPlugin< backend::ext_oneapi_hip > ()
getPlugin< backend::ext_oneapi_level_zero >()
template const PluginPtr& sycl::_V1::detail::pi::getPlugin< backend::ext_oneapi_level_zero > ()
getPlugin< backend::opencl >()
template const PluginPtr& sycl::_V1::detail::pi::getPlugin< backend::opencl > ()
handleUnknownParamName()
template<typename T > void sycl::_V1::detail::pi::handleUnknownParamName (const char * functionName, T parameter)
Definition at line 112 of file pi.hpp.
References die().
initialize()
std::vector< PluginPtr > & sycl::_V1::detail::pi::initialize ()
Definition at line 372 of file pi.cpp.
References sycl::_V1::detail::GlobalHandler::getPlugins(), initializePlugins(), and sycl::_V1::detail::GlobalHandler::instance().
Referenced by sycl::_V1::detail::platform_impl::get_devices(), sycl::_V1::detail::platform_impl::get_platforms(), and getPlugin().
initializePlugins()
static void sycl::_V1::detail::pi::initializePlugins (std::vector< PluginPtr > & Plugins) static
Definition at line 393 of file pi.cpp.
References _PI_H_VERSION_STRING, _PI_SANITIZE_TYPE_ADDRESS, _PI_SANITIZE_TYPE_NONE, bindPlugin(), std::cerr, findPlugins(), sycl::_V1::detail::ProgramManager::getInstance(), sycl::_V1::detail::GlobalHandler::getXPTIRegistry(), GMajVer, GMinVer, GVerStr, sycl::_V1::detail::XPTIRegistry::initializeFrameworkOnce(), sycl::_V1::detail::XPTIRegistry::initializeStream(), sycl::_V1::detail::GlobalHandler::instance(), sycl::_V1::detail::ProgramManager::kernelUsesAsan(), loadPlugins(), PI_TRACE_ALL, PI_TRACE_BASIC, sycl::_V1::detail::SYCL_PICALL_STREAM_NAME, sycl::_V1::detail::SYCL_PIDEBUGCALL_STREAM_NAME, sycl::_V1::detail::SYCL_STREAM_NAME, trace(), and XPTIInitDone.
Referenced by initialize().
loadOsLibrary()
void * sycl::_V1::detail::pi::loadOsLibrary (const std::string & Library)
Definition at line 20 of file posix_pi.cpp.
References std::cerr, PI_TRACE_ALL, and trace().
Referenced by sycl::_V1::ext::__SYCL2020_DEPRECATED(), sycl::_V1::ext::oneapi::experimental::detail::loadOclocLibrary(), and loadOsPluginLibrary().
loadOsPluginLibrary()
void * sycl::_V1::detail::pi::loadOsPluginLibrary (const std::string & Library)
Definition at line 33 of file posix_pi.cpp.
References loadOsLibrary().
Referenced by loadPlugin(), and loadPlugins().
loadPlugin()
void* sycl::_V1::detail::pi::loadPlugin (const std::string & PluginPath)
Definition at line 332 of file pi.cpp.
References loadOsPluginLibrary().
loadPlugins()
std::vector< std::tuple< std::string, backend, void * > > sycl::_V1::detail::pi::loadPlugins (const std::vector< std::pair< std::string, backend >> && PluginNames)
Definition at line 53 of file posix_pi.cpp.
References loadOsPluginLibrary(), and sycl::_V1::detail::make_tuple().
Referenced by initializePlugins().
memFlagsToString()
std::string sycl::_V1::detail::pi::memFlagsToString (pi_mem_flags Flags)
Definition at line 248 of file pi.cpp.
References memFlagToString(), PI_MEM_FLAGS_ACCESS_RW, PI_MEM_FLAGS_HOST_PTR_COPY, and PI_MEM_FLAGS_HOST_PTR_USE.
memFlagToString()
std::string sycl::_V1::detail::pi::memFlagToString (pi_mem_flags Flag)
Definition at line 222 of file pi.cpp.
References assertion(), PI_MEM_FLAGS_ACCESS_RW, PI_MEM_FLAGS_HOST_PTR_COPY, and PI_MEM_FLAGS_HOST_PTR_USE.
Referenced by memFlagsToString().
platformInfoToString()
std::string sycl::_V1::detail::pi::platformInfoToString (pi_platform_info info)
Definition at line 203 of file pi.cpp.
References die(), PI_EXT_PLATFORM_INFO_BACKEND, PI_PLATFORM_INFO_EXTENSIONS, PI_PLATFORM_INFO_NAME, PI_PLATFORM_INFO_PROFILE, PI_PLATFORM_INFO_VENDOR, and PI_PLATFORM_INFO_VERSION.
print() [1/17]
template<> void sycl::_V1::detail::pi::print (char * val) inline
Definition at line 115 of file plugin_printers.hpp.
References std::cout.
print() [2/17]
template<> void sycl::_V1::detail::pi::print (const char * val) inline
Definition at line 119 of file plugin_printers.hpp.
References std::cout.
print() [3/17]
template<> void sycl::_V1::detail::pi::print (const pi_image_desc * desc) inline
Definition at line 92 of file plugin_printers.hpp.
References std::cout, _pi_image_desc::image_array_size, _pi_image_desc::image_depth, _pi_image_desc::image_height, _pi_image_desc::image_row_pitch, _pi_image_desc::image_slice_pitch, _pi_image_desc::image_type, _pi_image_desc::image_width, _pi_image_desc::num_mip_levels, and _pi_image_desc::num_samples.
print() [4/17]
template<> void sycl::_V1::detail::pi::print (const PiEvent * val) inline
Definition at line 57 of file plugin_printers.hpp.
References std::cout.
print() [5/17]
template<> void sycl::_V1::detail::pi::print (pi_buff_rect_offset off) inline
Definition at line 77 of file plugin_printers.hpp.
References std::cout, pi_buff_rect_offset_struct::x_bytes, pi_buff_rect_offset_struct::y_scalar, and pi_buff_rect_offset_struct::z_scalar.
print() [6/17]
template<> void sycl::_V1::detail::pi::print (pi_buff_rect_region rgn) inline
Definition at line 71 of file plugin_printers.hpp.
References std::cout, pi_buff_rect_region_struct::depth_scalar, pi_buff_rect_region_struct::height_scalar, and pi_buff_rect_region_struct::width_bytes.
print() [7/17]
template<> void sycl::_V1::detail::pi::print (pi_buffer_region rgn) inline
Definition at line 66 of file plugin_printers.hpp.
References std::cout, pi_buffer_region_struct::origin, and pi_buffer_region_struct::size.
print() [8/17]
template<> void sycl::_V1::detail::pi::print (pi_image_offset off) inline
Definition at line 87 of file plugin_printers.hpp.
References std::cout, pi_image_offset_struct::x, pi_image_offset_struct::y, and pi_image_offset_struct::z.
print() [9/17]
template<> void sycl::_V1::detail::pi::print (pi_image_region rgn) inline
Definition at line 82 of file plugin_printers.hpp.
References std::cout, pi_image_region_struct::depth, pi_image_region_struct::height, and pi_image_region_struct::width.
print() [10/17]
template<> void sycl::_V1::detail::pi::print (PiEvent * val) inline
Definition at line 48 of file plugin_printers.hpp.
References std::cout.
print() [11/17]
template<> void sycl::_V1::detail::pi::print (PiEvent val) inline
Definition at line 40 of file plugin_printers.hpp.
References std::cout.
print() [12/17]
template<> void sycl::_V1::detail::pi::print (PiMem val) inline
Definition at line 44 of file plugin_printers.hpp.
References std::cout.
print() [13/17]
template<> void sycl::_V1::detail::pi::print (PiPlatform val) inline
Definition at line 36 of file plugin_printers.hpp.
References std::cout.
print() [14/17]
template<> void sycl::_V1::detail::pi::print (PiResult val) inline
Definition at line 102 of file plugin_printers.hpp.
References std::cout.
print() [15/17]
template<> void sycl::_V1::detail::pi::print (std::nullptr_t) inline
Definition at line 111 of file plugin_printers.hpp.
References std::cout.
print() [16/17]
template<typename T > std::enable_if<!std::is_pointer<T>::value, void>::type sycl::_V1::detail::pi::print (T val) inline
Definition at line 25 of file plugin_printers.hpp.
References std::cout.
Referenced by printArgs().
print() [17/17]
template<typename T > std::enable_if<std::is_pointer<T>::value, void>::type sycl::_V1::detail::pi::print (T val) inline
Definition at line 31 of file plugin_printers.hpp.
References std::cout.
printArgs() [1/2]
template<typename Arg0 , typename... Args> void sycl::_V1::detail::pi::printArgs (Arg0 arg0, Args... args)
Definition at line 125 of file plugin_printers.hpp.
References std::cout, print(), and printArgs().
printArgs() [2/2]
void sycl::_V1::detail::pi::printArgs (void) inline
Definition at line 123 of file plugin_printers.hpp.
Referenced by sycl::_V1::detail::plugin::call_nocheck(), and printArgs().
printOuts() [1/2]
template<typename Arg0 , typename... Args> void sycl::_V1::detail::pi::printOuts (Arg0 arg0, Args... args)
Definition at line 174 of file plugin_printers.hpp.
References printOuts().
printOuts() [2/2]
void sycl::_V1::detail::pi::printOuts (void) inline
Definition at line 172 of file plugin_printers.hpp.
Referenced by sycl::_V1::detail::plugin::call_nocheck(), and printOuts().
readELFValue()
template<typename ResT > static ResT sycl::_V1::detail::pi::readELFValue (const unsigned char * Data, size_t NumBytes, bool IsBigEndian) static
Definition at line 538 of file pi.cpp.
References sycl::_V1::ext::oneapi::experimental::copy().
trace()
bool sycl::_V1::detail::pi::trace (TraceLevel level)
Definition at line 366 of file pi.cpp.
References sycl::_V1::detail::SYCLConfig< Config >::get().
Referenced by sycl::_V1::detail::plugin::call_nocheck(), initializePlugins(), sycl::_V1::detail::IsBannedPlatform(), loadOsLibrary(), and sycl::_V1::detail::traceDeviceSelection().
unloadOsLibrary()
int sycl::_V1::detail::pi::unloadOsLibrary (void * Library)
Definition at line 37 of file posix_pi.cpp.
unloadOsPluginLibrary()
int sycl::_V1::detail::pi::unloadOsPluginLibrary (void * Library)
Definition at line 39 of file posix_pi.cpp.
Referenced by unloadPlugin().
unloadPlugin()
int sycl::_V1::detail::pi::unloadPlugin (void * Library)
Definition at line 338 of file pi.cpp.
References unloadOsPluginLibrary().
Referenced by sycl::_V1::detail::plugin::unload().
Variable Documentation
cast
template<> PiDevice sycl::_V1::detail::pi::cast(cl_device_id)=delete (cl_program) inline delete
Referenced by sycl::_V1::detail::BufferInterop< backend::opencl, DataT, Dimensions, AllocatorT >::GetNativeObjs().
GlobalPlugin
std::shared_ptr< plugin > sycl::_V1::detail::pi::GlobalPlugin
Definition at line 283 of file pi.cpp.
XPTIInitDone
bool sycl::_V1::detail::pi::XPTIInitDone = false
Definition at line 78 of file pi.cpp.
Referenced by initializePlugins().