DPC++ Runtime: cl::sycl::ONEAPI Namespace Reference
cl::sycl::ONEAPI Namespace Reference
Namespaces
detail
experimental
property
Classes
class accessor_property_list
Objects of the accessor_property_list class are containers for the SYCL properties.
class atomic_accessor
class atomic_ref
class filter_selector
struct is_compile_time_property
struct is_compile_time_property< INTEL::property::buffer_location >
struct is_compile_time_property< ONEAPI::property::no_alias >
struct is_compile_time_property< ONEAPI::property::no_offset >
struct maximum
struct minimum
struct sub_group
Typedefs
using device_func_ptr_holder_t = cl_ulong
template<class FuncType >
using enable_if_is_function_pointer_t = typename std::enable_if< std::is_pointer< FuncType >::value &&std::is_function< typename std::remove_pointer< FuncType >::type >::value, int >::type
template<typename T = void>
using plus = std::plus< T >
template<typename T = void>
using multiplies = std::multiplies< T >
template<typename T = void>
using bit_or = std::bit_or< T >
template<typename T = void>
using bit_xor = std::bit_xor< T >
template<typename T = void>
using bit_and = std::bit_and< T >
template<typename T >
using EnableIfIsScalarArithmetic = cl::sycl::detail::enable_if_t< cl::sycl::detail::is_scalar_arithmetic< T >::value, T >
template<typename T >
using EnableIfIsVectorArithmetic = cl::sycl::detail::enable_if_t< cl::sycl::detail::is_vector_arithmetic< T >::value, T >
template<typename Ptr , typename T >
using EnableIfIsPointer = cl::sycl::detail::enable_if_t< cl::sycl::detail::is_pointer< Ptr >::value, T >
template<typename T >
using EnableIfIsTriviallyCopyable = cl::sycl::detail::enable_if_t< std::is_trivially_copyable< T >::value &&!cl::sycl::detail::is_vector_arithmetic< T >::value, T >
template<typename T , typename BinaryOperation >
using EnableIfIsScalarArithmeticNativeOp = cl::sycl::detail::enable_if_t< cl::sycl::detail::is_scalar_arithmetic< T >::value &&cl::sycl::detail::is_native_op< T, BinaryOperation >::value, T >
template<typename T , typename BinaryOperation >
using EnableIfIsVectorArithmeticNativeOp = cl::sycl::detail::enable_if_t< cl::sycl::detail::is_vector_arithmetic< T >::value &&cl::sycl::detail::is_native_op< T, BinaryOperation >::value, T >
template<typename T , typename BinaryOperation >
using EnableIfIsNonNativeOp = cl::sycl::detail::enable_if_t<(!cl::sycl::detail::is_scalar_arithmetic< T >::value &&!cl::sycl::detail::is_vector_arithmetic< T >::value &&std::is_trivially_copyable< T >::value)||!cl::sycl::detail::is_native_op< T, BinaryOperation >::value, T >
Enumerations
enum memory_order : int {
memory_order::relaxed, memory_order::acquire, memory_order::__consume_unsupported, memory_order::release,
memory_order::acq_rel, memory_order::seq_cst
}
enum memory_scope : int {
memory_scope::work_item, memory_scope::sub_group, memory_scope::work_group, memory_scope::device,
memory_scope::system
}
Functions
static void atomic_fence (memory_order order, memory_scope scope)
template<class FuncType , typename FuncPtrType = typename std::add_pointer<FuncType>::type, typename std::enable_if< std::is_function< FuncType >::value, int >::type = 0>
FuncPtrType to_device_func_ptr (device_func_ptr_holder_t FptrHolder)
this function performs a cast from device_func_ptr_holder_t type to the provided function pointer type.
template<class FuncType , enable_if_is_function_pointer_t< FuncType > = 0>
device_func_ptr_holder_t get_device_func_ptr (FuncType F, const char *FuncName, program &P, device &D)
this function can be used only on host side to obtain device function pointer for the specified function.
template<typename Group >
detail::enable_if_t< detail::is_generic_group< Group >::value, bool > all_of (Group, bool pred)
template<typename Group , typename T , class Predicate >
detail::enable_if_t< detail::is_generic_group< Group >::value, bool > all_of (Group g, T x, Predicate pred)
template<typename Group , typename Ptr , class Predicate >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_pointer< Ptr >::value), bool > all_of (Group g, Ptr first, Ptr last, Predicate pred)
template<typename Group >
detail::enable_if_t< detail::is_generic_group< Group >::value, bool > any_of (Group, bool pred)
template<typename Group , typename T , class Predicate >
detail::enable_if_t< detail::is_generic_group< Group >::value, bool > any_of (Group g, T x, Predicate pred)
template<typename Group , typename Ptr , class Predicate >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_pointer< Ptr >::value), bool > any_of (Group g, Ptr first, Ptr last, Predicate pred)
template<typename Group >
detail::enable_if_t< detail::is_generic_group< Group >::value, bool > none_of (Group, bool pred)
template<typename Group , typename T , class Predicate >
detail::enable_if_t< detail::is_generic_group< Group >::value, bool > none_of (Group g, T x, Predicate pred)
template<typename Group , typename Ptr , class Predicate >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_pointer< Ptr >::value), bool > none_of (Group g, Ptr first, Ptr last, Predicate pred)
template<typename Group , typename T >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&std::is_trivially_copyable< T >::value &&!detail::is_vector_arithmetic< T >::value), T > broadcast (Group, T x, typename Group::id_type local_id)
template<typename Group , typename T >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_vector_arithmetic< T >::value), T > broadcast (Group g, T x, typename Group::id_type local_id)
template<typename Group , typename T >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&std::is_trivially_copyable< T >::value &&!detail::is_vector_arithmetic< T >::value), T > broadcast (Group g, T x, typename Group::linear_id_type linear_local_id)
template<typename Group , typename T >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_vector_arithmetic< T >::value), T > broadcast (Group g, T x, typename Group::linear_id_type linear_local_id)
template<typename Group , typename T >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&std::is_trivially_copyable< T >::value &&!detail::is_vector_arithmetic< T >::value), T > broadcast (Group g, T x)
template<typename Group , typename T >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_vector_arithmetic< T >::value), T > broadcast (Group g, T x)
template<typename Group , typename T , class BinaryOperation >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_scalar_arithmetic< T >::value &&detail::is_native_op< T, BinaryOperation >::value), T > reduce (Group, T x, BinaryOperation binary_op)
template<typename Group , typename T , class BinaryOperation >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_vector_arithmetic< T >::value &&detail::is_native_op< T, BinaryOperation >::value), T > reduce (Group g, T x, BinaryOperation binary_op)
template<typename Group , typename T , class BinaryOperation >
detail::enable_if_t<(detail::is_sub_group< Group >::value &&std::is_trivially_copyable< T >::value &&(!detail::is_arithmetic< T >::value||!detail::is_native_op< T, BinaryOperation >::value)), T > reduce (Group g, T x, BinaryOperation op)
template<typename Group , typename V , typename T , class BinaryOperation >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_scalar_arithmetic< V >::value &&detail::is_scalar_arithmetic< T >::value &&detail::is_native_op< V, BinaryOperation >::value &&detail::is_native_op< T, BinaryOperation >::value), T > reduce (Group g, V x, T init, BinaryOperation binary_op)
template<typename Group , typename V , typename T , class BinaryOperation >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_vector_arithmetic< V >::value &&detail::is_vector_arithmetic< T >::value &&detail::is_native_op< V, BinaryOperation >::value &&detail::is_native_op< T, BinaryOperation >::value), T > reduce (Group g, V x, T init, BinaryOperation binary_op)
template<typename Group , typename V , typename T , class BinaryOperation >
detail::enable_if_t<(detail::is_sub_group< Group >::value &&std::is_trivially_copyable< T >::value &&std::is_trivially_copyable< V >::value &&(!detail::is_arithmetic< T >::value||!detail::is_arithmetic< V >::value||!detail::is_native_op< T, BinaryOperation >::value)), T > reduce (Group g, V x, T init, BinaryOperation op)
template<typename Group , typename Ptr , class BinaryOperation >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_pointer< Ptr >::value &&detail::is_arithmetic< typename detail::remove_pointer< Ptr >::type >::value), typename detail::remove_pointer< Ptr >::type > reduce (Group g, Ptr first, Ptr last, BinaryOperation binary_op)
template<typename Group , typename Ptr , typename T , class BinaryOperation >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_pointer< Ptr >::value &&detail::is_arithmetic< typename detail::remove_pointer< Ptr >::type >::value &&detail::is_arithmetic< T >::value &&detail::is_native_op< typename detail::remove_pointer< Ptr >::type, BinaryOperation >::value &&detail::is_native_op< T, BinaryOperation >::value), T > reduce (Group g, Ptr first, Ptr last, T init, BinaryOperation binary_op)
template<typename Group , typename T , class BinaryOperation >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_scalar_arithmetic< T >::value &&detail::is_native_op< T, BinaryOperation >::value), T > exclusive_scan (Group, T x, BinaryOperation binary_op)
template<typename Group , typename T , class BinaryOperation >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_vector_arithmetic< T >::value &&detail::is_native_op< T, BinaryOperation >::value), T > exclusive_scan (Group g, T x, BinaryOperation binary_op)
template<typename Group , typename V , typename T , class BinaryOperation >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_vector_arithmetic< V >::value &&detail::is_vector_arithmetic< T >::value &&detail::is_native_op< V, BinaryOperation >::value &&detail::is_native_op< T, BinaryOperation >::value), T > exclusive_scan (Group g, V x, T init, BinaryOperation binary_op)
template<typename Group , typename V , typename T , class BinaryOperation >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_scalar_arithmetic< V >::value &&detail::is_scalar_arithmetic< T >::value &&detail::is_native_op< V, BinaryOperation >::value &&detail::is_native_op< T, BinaryOperation >::value), T > exclusive_scan (Group g, V x, T init, BinaryOperation binary_op)
template<typename Group , typename InPtr , typename OutPtr , typename T , class BinaryOperation >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_pointer< InPtr >::value &&detail::is_pointer< OutPtr >::value &&detail::is_arithmetic< typename detail::remove_pointer< InPtr >::type >::value &&detail::is_arithmetic< T >::value &&detail::is_native_op< typename detail::remove_pointer< InPtr >::type, BinaryOperation >::value &&detail::is_native_op< T, BinaryOperation >::value), OutPtr > exclusive_scan (Group g, InPtr first, InPtr last, OutPtr result, T init, BinaryOperation binary_op)
template<typename Group , typename InPtr , typename OutPtr , class BinaryOperation >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_pointer< InPtr >::value &&detail::is_pointer< OutPtr >::value &&detail::is_arithmetic< typename detail::remove_pointer< InPtr >::type >::value &&detail::is_native_op< typename detail::remove_pointer< InPtr >::type, BinaryOperation >::value), OutPtr > exclusive_scan (Group g, InPtr first, InPtr last, OutPtr result, BinaryOperation binary_op)
template<typename Group , typename T , class BinaryOperation >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_vector_arithmetic< T >::value &&detail::is_native_op< T, BinaryOperation >::value), T > inclusive_scan (Group g, T x, BinaryOperation binary_op)
template<typename Group , typename T , class BinaryOperation >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_scalar_arithmetic< T >::value &&detail::is_native_op< T, BinaryOperation >::value), T > inclusive_scan (Group, T x, BinaryOperation binary_op)
template<typename Group , typename V , class BinaryOperation , typename T >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_scalar_arithmetic< V >::value &&detail::is_scalar_arithmetic< T >::value &&detail::is_native_op< V, BinaryOperation >::value &&detail::is_native_op< T, BinaryOperation >::value), T > inclusive_scan (Group g, V x, BinaryOperation binary_op, T init)
template<typename Group , typename V , class BinaryOperation , typename T >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_vector_arithmetic< V >::value &&detail::is_vector_arithmetic< T >::value &&detail::is_native_op< V, BinaryOperation >::value &&detail::is_native_op< T, BinaryOperation >::value), T > inclusive_scan (Group g, V x, BinaryOperation binary_op, T init)
template<typename Group , typename InPtr , typename OutPtr , class BinaryOperation , typename T >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_pointer< InPtr >::value &&detail::is_pointer< OutPtr >::value &&detail::is_arithmetic< typename detail::remove_pointer< InPtr >::type >::value &&detail::is_arithmetic< T >::value &&detail::is_native_op< typename detail::remove_pointer< InPtr >::type, BinaryOperation >::value &&detail::is_native_op< T, BinaryOperation >::value), OutPtr > inclusive_scan (Group g, InPtr first, InPtr last, OutPtr result, BinaryOperation binary_op, T init)
template<typename Group , typename InPtr , typename OutPtr , class BinaryOperation >
detail::enable_if_t<(detail::is_generic_group< Group >::value &&detail::is_pointer< InPtr >::value &&detail::is_pointer< OutPtr >::value &&detail::is_arithmetic< typename detail::remove_pointer< InPtr >::type >::value &&detail::is_native_op< typename detail::remove_pointer< InPtr >::type, BinaryOperation >::value), OutPtr > inclusive_scan (Group g, InPtr first, InPtr last, OutPtr result, BinaryOperation binary_op)
template<typename Group >
detail::enable_if_t< detail::is_generic_group< Group >::value, bool > leader (Group g)
template<typename T , class BinaryOperation , int Dims, access::mode AccMode, access::placeholder IsPH>
detail::reduction_impl< T, BinaryOperation, Dims, false, AccMode, IsPH > reduction (accessor< T, Dims, AccMode, access::target::global_buffer, IsPH > &Acc, const T &Identity, BinaryOperation BOp)
Creates and returns an object implementing the reduction functionality.
template<typename T , class BinaryOperation , int Dims, access::mode AccMode, access::placeholder IsPH>
detail::enable_if_t< detail::IsKnownIdentityOp< T, BinaryOperation >::value, detail::reduction_impl< T, BinaryOperation, Dims, false, AccMode, IsPH > > reduction (accessor< T, Dims, AccMode, access::target::global_buffer, IsPH > &Acc, BinaryOperation)
Creates and returns an object implementing the reduction functionality.
template<typename T , class BinaryOperation >
detail::reduction_impl< T, BinaryOperation, 0, true, access::mode::read_write > reduction (T *VarPtr, const T &Identity, BinaryOperation BOp)
Creates and returns an object implementing the reduction functionality.
template<typename T , class BinaryOperation >
detail::enable_if_t< detail::IsKnownIdentityOp< T, BinaryOperation >::value, detail::reduction_impl< T, BinaryOperation, 0, true, access::mode::read_write > > reduction (T *VarPtr, BinaryOperation)
Creates and returns an object implementing the reduction functionality.
sub_group this_sub_group ()
Variables
__SYCL_INLINE_CONSTEXPR memory_order memory_order_relaxed
__SYCL_INLINE_CONSTEXPR memory_order memory_order_acquire
__SYCL_INLINE_CONSTEXPR memory_order memory_order_release
__SYCL_INLINE_CONSTEXPR memory_order memory_order_acq_rel
__SYCL_INLINE_CONSTEXPR memory_order memory_order_seq_cst
__SYCL_INLINE_CONSTEXPR memory_scope memory_scope_work_item
__SYCL_INLINE_CONSTEXPR memory_scope memory_scope_sub_group
__SYCL_INLINE_CONSTEXPR memory_scope memory_scope_work_group
__SYCL_INLINE_CONSTEXPR memory_scope memory_scope_device = memory_scope::device
__SYCL_INLINE_CONSTEXPR memory_scope memory_scope_system = memory_scope::system
Typedef Documentation
bit_and
template<typename T = void> using cl::sycl::ONEAPI::bit_and = typedef std::bit_and<T>
Definition at line 59 of file functional.hpp.
bit_or
template<typename T = void> using cl::sycl::ONEAPI::bit_or = typedef std::bit_or<T>
Definition at line 57 of file functional.hpp.
bit_xor
template<typename T = void> using cl::sycl::ONEAPI::bit_xor = typedef std::bit_xor<T>
Definition at line 58 of file functional.hpp.
device_func_ptr_holder_t
using cl::sycl::ONEAPI::device_func_ptr_holder_t = typedef cl_ulong
Definition at line 34 of file function_pointer.hpp.
enable_if_is_function_pointer_t
template<class FuncType > using cl::sycl::ONEAPI::enable_if_is_function_pointer_t = typedef typename std::enable_if< std::is_pointer<FuncType>::value && std::is_function<typename std::remove_pointer<FuncType>::type>::value, int>::type
Definition at line 50 of file function_pointer.hpp.
EnableIfIsNonNativeOp
template<typename T , typename BinaryOperation > using cl::sycl::ONEAPI::EnableIfIsNonNativeOp = typedef cl::sycl::detail::enable_if_t< (!cl::sycl::detail::is_scalar_arithmetic<T>::value && !cl::sycl::detail::is_vector_arithmetic<T>::value && std::is_trivially_copyable<T>::value) || !cl::sycl::detail::is_native_op<T, BinaryOperation>::value, T>
Definition at line 191 of file group_algorithm.hpp.
EnableIfIsPointer
template<typename Ptr , typename T > using cl::sycl::ONEAPI::EnableIfIsPointer = typedef cl::sycl::detail::enable_if_t<cl::sycl::detail::is_pointer<Ptr>::value, T>
Definition at line 163 of file group_algorithm.hpp.
EnableIfIsScalarArithmetic
template<typename T > using cl::sycl::ONEAPI::EnableIfIsScalarArithmetic = typedef cl::sycl::detail::enable_if_t< cl::sycl::detail::is_scalar_arithmetic<T>::value, T>
Definition at line 155 of file group_algorithm.hpp.
EnableIfIsScalarArithmeticNativeOp
template<typename T , typename BinaryOperation > using cl::sycl::ONEAPI::EnableIfIsScalarArithmeticNativeOp = typedef cl::sycl::detail::enable_if_t< cl::sycl::detail::is_scalar_arithmetic<T>::value && cl::sycl::detail::is_native_op<T, BinaryOperation>::value, T>
Definition at line 176 of file group_algorithm.hpp.
EnableIfIsTriviallyCopyable
template<typename T > using cl::sycl::ONEAPI::EnableIfIsTriviallyCopyable = typedef cl::sycl::detail::enable_if_t< std::is_trivially_copyable<T>::value && !cl::sycl::detail::is_vector_arithmetic<T>::value, T>
Definition at line 169 of file group_algorithm.hpp.
EnableIfIsVectorArithmetic
template<typename T > using cl::sycl::ONEAPI::EnableIfIsVectorArithmetic = typedef cl::sycl::detail::enable_if_t< cl::sycl::detail::is_vector_arithmetic<T>::value, T>
Definition at line 159 of file group_algorithm.hpp.
EnableIfIsVectorArithmeticNativeOp
template<typename T , typename BinaryOperation > using cl::sycl::ONEAPI::EnableIfIsVectorArithmeticNativeOp = typedef cl::sycl::detail::enable_if_t< cl::sycl::detail::is_vector_arithmetic<T>::value && cl::sycl::detail::is_native_op<T, BinaryOperation>::value, T>
Definition at line 182 of file group_algorithm.hpp.
multiplies
template<typename T = void> using cl::sycl::ONEAPI::multiplies = typedef std::multiplies<T>
Definition at line 56 of file functional.hpp.
plus
template<typename T = void> using cl::sycl::ONEAPI::plus = typedef std::plus<T>
Definition at line 55 of file functional.hpp.
Enumeration Type Documentation
memory_order
enum cl::sycl::ONEAPI::memory_order : int strong
Enumerator
relaxed
acquire
__consume_unsupported
release
acq_rel
seq_cst
Definition at line 25 of file atomic_enums.hpp.
memory_scope
enum cl::sycl::ONEAPI::memory_scope : int strong
Enumerator
work_item
sub_group
work_group
device
system
Definition at line 44 of file atomic_enums.hpp.
Function Documentation
all_of() [1/3]
template<typename Group > detail::enable_if_t<detail::is_generic_group<Group>::value, bool> cl::sycl::ONEAPI::all_of (Group , bool pred)
Definition at line 195 of file group_algorithm.hpp.
References PI_INVALID_DEVICE.
Referenced by cl::sycl::detail::checkImageValueRange().
all_of() [2/3]
template<typename Group , typename T , class Predicate > detail::enable_if_t<detail::is_generic_group<Group>::value, bool> cl::sycl::ONEAPI::all_of (Group g, T x, Predicate pred)
Definition at line 207 of file group_algorithm.hpp.
References all_of().
all_of() [3/3]
template<typename Group , typename Ptr , class Predicate > detail::enable_if_t<(detail::is_generic_group<Group>::value && detail::is_pointer<Ptr>::value), bool> cl::sycl::ONEAPI::all_of (Group g, Ptr first, Ptr last, Predicate pred)
Definition at line 215 of file group_algorithm.hpp.
References cl::sycl::detail::for_each(), and PI_INVALID_DEVICE.
Referenced by all_of().
any_of() [1/3]
template<typename Group > detail::enable_if_t<detail::is_generic_group<Group>::value, bool> cl::sycl::ONEAPI::any_of (Group , bool pred)
Definition at line 234 of file group_algorithm.hpp.
References PI_INVALID_DEVICE.
Referenced by cl::sycl::context::context().
any_of() [2/3]
template<typename Group , typename T , class Predicate > detail::enable_if_t<detail::is_generic_group<Group>::value, bool> cl::sycl::ONEAPI::any_of (Group g, T x, Predicate pred)
Definition at line 246 of file group_algorithm.hpp.
References any_of().
any_of() [3/3]
template<typename Group , typename Ptr , class Predicate > detail::enable_if_t<(detail::is_generic_group<Group>::value && detail::is_pointer<Ptr>::value), bool> cl::sycl::ONEAPI::any_of (Group g, Ptr first, Ptr last, Predicate pred)
Definition at line 254 of file group_algorithm.hpp.
References cl::sycl::detail::for_each(), and PI_INVALID_DEVICE.
Referenced by any_of(), and none_of().
atomic_fence()
static void cl::sycl::ONEAPI::atomic_fence (memory_order order, memory_scope scope) inline static
Definition at line 26 of file atomic_fence.hpp.
References __spirv_MemoryBarrier(), and cl::sycl::detail::getStdMemoryOrder().
broadcast() [1/6]
template<typename Group , typename T > detail::enable_if_t<(detail::is_generic_group<Group>::value && std::is_trivially_copyable<T>::value && !detail::is_vector_arithmetic<T>::value), T> cl::sycl::ONEAPI::broadcast (Group , T x, typename Group::id_type local_id)
Definition at line 311 of file group_algorithm.hpp.
References PI_INVALID_DEVICE.
Referenced by cl::sycl::ONEAPI::sub_group::barrier().
broadcast() [2/6]
template<typename Group , typename T > detail::enable_if_t<(detail::is_generic_group<Group>::value && detail::is_vector_arithmetic<T>::value), T> cl::sycl::ONEAPI::broadcast (Group g, T x, typename Group::id_type local_id)
Definition at line 326 of file group_algorithm.hpp.
References broadcast(), and PI_INVALID_DEVICE.
broadcast() [3/6]
template<typename Group , typename T > detail::enable_if_t<(detail::is_generic_group<Group>::value && std::is_trivially_copyable<T>::value && !detail::is_vector_arithmetic<T>::value), T> cl::sycl::ONEAPI::broadcast (Group g, T x, typename Group::linear_id_type linear_local_id)
Definition at line 347 of file group_algorithm.hpp.
References broadcast(), cl::sycl::detail::linear_id_to_id(), and PI_INVALID_DEVICE.
broadcast() [4/6]
template<typename Group , typename T > detail::enable_if_t<(detail::is_generic_group<Group>::value && detail::is_vector_arithmetic<T>::value), T> cl::sycl::ONEAPI::broadcast (Group g, T x, typename Group::linear_id_type linear_local_id)
Definition at line 365 of file group_algorithm.hpp.
References broadcast(), and PI_INVALID_DEVICE.
broadcast() [5/6]
template<typename Group , typename T > detail::enable_if_t<(detail::is_generic_group<Group>::value && std::is_trivially_copyable<T>::value && !detail::is_vector_arithmetic<T>::value), T> cl::sycl::ONEAPI::broadcast (Group g, T x)
Definition at line 386 of file group_algorithm.hpp.
References broadcast(), and PI_INVALID_DEVICE.
broadcast() [6/6]
template<typename Group , typename T > detail::enable_if_t<(detail::is_generic_group<Group>::value && detail::is_vector_arithmetic<T>::value), T> cl::sycl::ONEAPI::broadcast (Group g, T x)
Definition at line 401 of file group_algorithm.hpp.
References PI_INVALID_DEVICE.
Referenced by broadcast(), exclusive_scan(), and inclusive_scan().
exclusive_scan() [1/6]
template<typename Group , typename T , class BinaryOperation > detail::enable_if_t<(detail::is_generic_group<Group>::value && detail::is_scalar_arithmetic<T>::value && detail::is_native_op<T, BinaryOperation>::value), T> cl::sycl::ONEAPI::exclusive_scan (Group , T x, BinaryOperation binary_op)
Definition at line 609 of file group_algorithm.hpp.
References __spv::ExclusiveScan, and PI_INVALID_DEVICE.
Referenced by cl::sycl::ONEAPI::sub_group::barrier().
exclusive_scan() [2/6]
template<typename Group , typename T , class BinaryOperation > detail::enable_if_t<(detail::is_generic_group<Group>::value && detail::is_vector_arithmetic<T>::value && detail::is_native_op<T, BinaryOperation>::value), T> cl::sycl::ONEAPI::exclusive_scan (Group g, T x, BinaryOperation binary_op)
Definition at line 630 of file group_algorithm.hpp.
References exclusive_scan().
exclusive_scan() [3/6]
template<typename Group , typename V , typename T , class BinaryOperation > detail::enable_if_t<(detail::is_generic_group<Group>::value && detail::is_vector_arithmetic<V>::value && detail::is_vector_arithmetic<T>::value && detail::is_native_op<V, BinaryOperation>::value && detail::is_native_op<T, BinaryOperation>::value), T> cl::sycl::ONEAPI::exclusive_scan (Group g, V x, T init, BinaryOperation binary_op)
Definition at line 652 of file group_algorithm.hpp.
References exclusive_scan().
exclusive_scan() [4/6]
template<typename Group , typename V , typename T , class BinaryOperation > detail::enable_if_t<(detail::is_generic_group<Group>::value && detail::is_scalar_arithmetic<V>::value && detail::is_scalar_arithmetic<T>::value && detail::is_native_op<V, BinaryOperation>::value && detail::is_native_op<T, BinaryOperation>::value), T> cl::sycl::ONEAPI::exclusive_scan (Group g, V x, T init, BinaryOperation binary_op)
Definition at line 674 of file group_algorithm.hpp.
References exclusive_scan(), cl::sycl::detail::get_local_linear_id(), and PI_INVALID_DEVICE.
exclusive_scan() [5/6]
template<typename Group , typename InPtr , typename OutPtr , typename T , class BinaryOperation > detail::enable_if_t< (detail::is_generic_group<Group>::value && detail::is_pointer<InPtr>::value && detail::is_pointer<OutPtr>::value && detail::is_arithmetic< typename detail::remove_pointer<InPtr>::type>::value && detail::is_arithmetic<T>::value && detail::is_native_op<typename detail::remove_pointer<InPtr>::type, BinaryOperation>::value && detail::is_native_op<T, BinaryOperation>::value), OutPtr> cl::sycl::ONEAPI::exclusive_scan (Group g, InPtr first, InPtr last, OutPtr result, T init, BinaryOperation binary_op)
Definition at line 710 of file group_algorithm.hpp.
References broadcast(), exclusive_scan(), cl::sycl::detail::get_local_linear_id(), cl::sycl::detail::get_local_linear_range(), and PI_INVALID_DEVICE.
exclusive_scan() [6/6]
template<typename Group , typename InPtr , typename OutPtr , class BinaryOperation > detail::enable_if_t< (detail::is_generic_group<Group>::value && detail::is_pointer<InPtr>::value && detail::is_pointer<OutPtr>::value && detail::is_arithmetic< typename detail::remove_pointer<InPtr>::type>::value && detail::is_native_op<typename detail::remove_pointer<InPtr>::type, BinaryOperation>::value), OutPtr> cl::sycl::ONEAPI::exclusive_scan (Group g, InPtr first, InPtr last, OutPtr result, BinaryOperation binary_op)
Definition at line 760 of file group_algorithm.hpp.
Referenced by exclusive_scan().
get_device_func_ptr()
template<class FuncType , enable_if_is_function_pointer_t< FuncType > = 0> device_func_ptr_holder_t cl::sycl::ONEAPI::get_device_func_ptr (FuncType F, const char * FuncName, program & P, device & D)
this function can be used only on host side to obtain device function pointer for the specified function.
Parameters
F - pointer to function to make it work for SYCL Host device
FuncName - name of the function. Please note that by default names of functions are mangled since SYCL is a C++. To avoid the need ot specifying mangled name here, use extern "C"
P - sycl::program object which will be used to extract device function pointer
D - sycl::device object which will be used to extract device function pointer
Returns
device_func_ptr_holder_t object which can be used inside a device code. This object must be converted back to a function pointer using to_device_func_ptr prior to actual usage.
Returned value is valid only within device code which was compiled for the specified program and device. Returned value invalidates whenever program is released or re-built
Definition at line 70 of file function_pointer.hpp.
References cl::sycl::program::get_state(), cl::sycl::detail::getDeviceFunctionPointerImpl(), cl::sycl::device::is_host(), and PI_INVALID_OPERATION.
inclusive_scan() [1/6]
template<typename Group , typename T , class BinaryOperation > detail::enable_if_t<(detail::is_generic_group<Group>::value && detail::is_vector_arithmetic<T>::value && detail::is_native_op<T, BinaryOperation>::value), T> cl::sycl::ONEAPI::inclusive_scan (Group g, T x, BinaryOperation binary_op)
Definition at line 780 of file group_algorithm.hpp.
References inclusive_scan().
Referenced by cl::sycl::ONEAPI::sub_group::barrier().
inclusive_scan() [2/6]
template<typename Group , typename T , class BinaryOperation > detail::enable_if_t<(detail::is_generic_group<Group>::value && detail::is_scalar_arithmetic<T>::value && detail::is_native_op<T, BinaryOperation>::value), T> cl::sycl::ONEAPI::inclusive_scan (Group , T x, BinaryOperation binary_op)
Definition at line 800 of file group_algorithm.hpp.
References __spv::InclusiveScan, and PI_INVALID_DEVICE.
inclusive_scan() [3/6]
template<typename Group , typename V , class BinaryOperation , typename T > detail::enable_if_t<(detail::is_generic_group<Group>::value && detail::is_scalar_arithmetic<V>::value && detail::is_scalar_arithmetic<T>::value && detail::is_native_op<V, BinaryOperation>::value && detail::is_native_op<T, BinaryOperation>::value), T> cl::sycl::ONEAPI::inclusive_scan (Group g, V x, BinaryOperation binary_op, T init)
Definition at line 823 of file group_algorithm.hpp.
References cl::sycl::detail::get_local_linear_id(), inclusive_scan(), and PI_INVALID_DEVICE.
inclusive_scan() [4/6]
template<typename Group , typename V , class BinaryOperation , typename T > detail::enable_if_t<(detail::is_generic_group<Group>::value && detail::is_vector_arithmetic<V>::value && detail::is_vector_arithmetic<T>::value && detail::is_native_op<V, BinaryOperation>::value && detail::is_native_op<T, BinaryOperation>::value), T> cl::sycl::ONEAPI::inclusive_scan (Group g, V x, BinaryOperation binary_op, T init)
Definition at line 848 of file group_algorithm.hpp.
References inclusive_scan().
inclusive_scan() [5/6]
template<typename Group , typename InPtr , typename OutPtr , class BinaryOperation , typename T > detail::enable_if_t< (detail::is_generic_group<Group>::value && detail::is_pointer<InPtr>::value && detail::is_pointer<OutPtr>::value && detail::is_arithmetic< typename detail::remove_pointer<InPtr>::type>::value && detail::is_arithmetic<T>::value && detail::is_native_op<typename detail::remove_pointer<InPtr>::type, BinaryOperation>::value && detail::is_native_op<T, BinaryOperation>::value), OutPtr> cl::sycl::ONEAPI::inclusive_scan (Group g, InPtr first, InPtr last, OutPtr result, BinaryOperation binary_op, T init)
Definition at line 874 of file group_algorithm.hpp.
References broadcast(), cl::sycl::detail::get_local_linear_id(), cl::sycl::detail::get_local_linear_range(), inclusive_scan(), and PI_INVALID_DEVICE.
inclusive_scan() [6/6]
template<typename Group , typename InPtr , typename OutPtr , class BinaryOperation > detail::enable_if_t< (detail::is_generic_group<Group>::value && detail::is_pointer<InPtr>::value && detail::is_pointer<OutPtr>::value && detail::is_arithmetic< typename detail::remove_pointer<InPtr>::type>::value && detail::is_native_op<typename detail::remove_pointer<InPtr>::type, BinaryOperation>::value), OutPtr> cl::sycl::ONEAPI::inclusive_scan (Group g, InPtr first, InPtr last, OutPtr result, BinaryOperation binary_op)
Definition at line 923 of file group_algorithm.hpp.
Referenced by inclusive_scan().
leader()
template<typename Group > detail::enable_if_t<detail::is_generic_group<Group>::value, bool> cl::sycl::ONEAPI::leader (Group g)
Definition at line 939 of file group_algorithm.hpp.
References cl::sycl::detail::get_local_linear_id(), and PI_INVALID_DEVICE.
none_of() [1/3]
template<typename Group > detail::enable_if_t<detail::is_generic_group<Group>::value, bool> cl::sycl::ONEAPI::none_of (Group , bool pred)
Definition at line 273 of file group_algorithm.hpp.
References PI_INVALID_DEVICE.
none_of() [2/3]
template<typename Group , typename T , class Predicate > detail::enable_if_t<detail::is_generic_group<Group>::value, bool> cl::sycl::ONEAPI::none_of (Group g, T x, Predicate pred)
Definition at line 285 of file group_algorithm.hpp.
References none_of().
none_of() [3/3]
template<typename Group , typename Ptr , class Predicate > detail::enable_if_t<(detail::is_generic_group<Group>::value && detail::is_pointer<Ptr>::value), bool> cl::sycl::ONEAPI::none_of (Group g, Ptr first, Ptr last, Predicate pred)
Definition at line 293 of file group_algorithm.hpp.
References any_of(), and PI_INVALID_DEVICE.
Referenced by none_of().
reduce() [1/8]
template<typename Group , typename T , class BinaryOperation > detail::enable_if_t<(detail::is_generic_group<Group>::value && detail::is_scalar_arithmetic<T>::value && detail::is_native_op<T, BinaryOperation>::value), T> cl::sycl::ONEAPI::reduce (Group , T x, BinaryOperation binary_op)
Definition at line 421 of file group_algorithm.hpp.
References PI_INVALID_DEVICE, and __spv::Reduce.
reduce() [2/8]
template<typename Group , typename T , class BinaryOperation > detail::enable_if_t<(detail::is_generic_group<Group>::value && detail::is_vector_arithmetic<T>::value && detail::is_native_op<T, BinaryOperation>::value), T> cl::sycl::ONEAPI::reduce (Group g, T x, BinaryOperation binary_op)
Definition at line 443 of file group_algorithm.hpp.
References reduce().
reduce() [3/8]
template<typename Group , typename T , class BinaryOperation > detail::enable_if_t<(detail::is_sub_group<Group>::value && std::is_trivially_copyable<T>::value && (!detail::is_arithmetic<T>::value || !detail::is_native_op<T, BinaryOperation>::value)), T> cl::sycl::ONEAPI::reduce (Group g, T x, BinaryOperation op)
Definition at line 464 of file group_algorithm.hpp.
reduce() [4/8]
template<typename Group , typename V , typename T , class BinaryOperation > detail::enable_if_t<(detail::is_generic_group<Group>::value && detail::is_scalar_arithmetic<V>::value && detail::is_scalar_arithmetic<T>::value && detail::is_native_op<V, BinaryOperation>::value && detail::is_native_op<T, BinaryOperation>::value), T> cl::sycl::ONEAPI::reduce (Group g, V x, T init, BinaryOperation binary_op)
Definition at line 482 of file group_algorithm.hpp.
References PI_INVALID_DEVICE, and reduce().
reduce() [5/8]
template<typename Group , typename V , typename T , class BinaryOperation > detail::enable_if_t<(detail::is_generic_group<Group>::value && detail::is_vector_arithmetic<V>::value && detail::is_vector_arithmetic<T>::value && detail::is_native_op<V, BinaryOperation>::value && detail::is_native_op<T, BinaryOperation>::value), T> cl::sycl::ONEAPI::reduce (Group g, V x, T init, BinaryOperation binary_op)
Definition at line 505 of file group_algorithm.hpp.
References PI_INVALID_DEVICE, and reduce().
reduce() [6/8]
template<typename Group , typename V , typename T , class BinaryOperation > detail::enable_if_t<(detail::is_sub_group<Group>::value && std::is_trivially_copyable<T>::value && std::is_trivially_copyable<V>::value && (!detail::is_arithmetic<T>::value || !detail::is_arithmetic<V>::value || !detail::is_native_op<T, BinaryOperation>::value)), T> cl::sycl::ONEAPI::reduce (Group g, V x, T init, BinaryOperation op)
Definition at line 534 of file group_algorithm.hpp.
reduce() [7/8]
template<typename Group , typename Ptr , class BinaryOperation > detail::enable_if_t< (detail::is_generic_group<Group>::value && detail::is_pointer<Ptr>::value && detail::is_arithmetic<typename detail::remove_pointer<Ptr>::type>::value), typename detail::remove_pointer<Ptr>::type> cl::sycl::ONEAPI::reduce (Group g, Ptr first, Ptr last, BinaryOperation binary_op)
Definition at line 550 of file group_algorithm.hpp.
References cl::sycl::detail::for_each(), PI_INVALID_DEVICE, and reduce().
reduce() [8/8]
template<typename Group , typename Ptr , typename T , class BinaryOperation > detail::enable_if_t< (detail::is_generic_group<Group>::value && detail::is_pointer<Ptr>::value && detail::is_arithmetic<typename detail::remove_pointer<Ptr>::type>::value && detail::is_arithmetic<T>::value && detail::is_native_op<typename detail::remove_pointer<Ptr>::type, BinaryOperation>::value && detail::is_native_op<T, BinaryOperation>::value), T> cl::sycl::ONEAPI::reduce (Group g, Ptr first, Ptr last, T init, BinaryOperation binary_op)
Definition at line 582 of file group_algorithm.hpp.
References cl::sycl::detail::for_each(), and PI_INVALID_DEVICE.
Referenced by reduce().
reduction() [1/4]
template<typename T , class BinaryOperation , int Dims, access::mode AccMode, access::placeholder IsPH> detail::reduction_impl<T, BinaryOperation, Dims, false, AccMode, IsPH> cl::sycl::ONEAPI::reduction (accessor< T, Dims, AccMode, access::target::global_buffer, IsPH > & Acc, const T & Identity, BinaryOperation BOp)
Creates and returns an object implementing the reduction functionality.
Accepts 3 arguments: the accessor to buffer to where the computed reduction must be stored
Parameters
Acc,identity value
Identity,and the binary operation used in the reduction.
Definition at line 1032 of file reduction.hpp.
reduction() [2/4]
template<typename T , class BinaryOperation , int Dims, access::mode AccMode, access::placeholder IsPH> detail::enable_if_t< detail::IsKnownIdentityOp<T, BinaryOperation>::value, detail::reduction_impl<T, BinaryOperation, Dims, false, AccMode, IsPH> > cl::sycl::ONEAPI::reduction (accessor< T, Dims, AccMode, access::target::global_buffer, IsPH > & Acc, BinaryOperation)
Creates and returns an object implementing the reduction functionality.
Accepts 2 arguments: the accessor to buffer to where the computed reduction must be stored
Parameters
Acc and the binary operation used in the reduction. The identity value is not passed to this version as it is statically known.
Definition at line 1048 of file reduction.hpp.
reduction() [3/4]
template<typename T , class BinaryOperation > detail::reduction_impl<T, BinaryOperation, 0, true, access::mode::read_write> cl::sycl::ONEAPI::reduction (T * VarPtr, const T & Identity, BinaryOperation BOp)
Creates and returns an object implementing the reduction functionality.
Accepts 3 arguments: the reference to the reduction variable to where the computed reduction must be stored
Parameters
VarPtr,identity value
Identity,and the binary operation used in the reduction.
Definition at line 1061 of file reduction.hpp.
reduction() [4/4]
template<typename T , class BinaryOperation > detail::enable_if_t<detail::IsKnownIdentityOp<T, BinaryOperation>::value, detail::reduction_impl<T, BinaryOperation, 0, true, access::mode::read_write> > cl::sycl::ONEAPI::reduction (T * VarPtr, BinaryOperation)
Creates and returns an object implementing the reduction functionality.
Accepts 2 arguments: the reference to the reduction variable, to where the computed reduction must be stored
Parameters
VarPtr,and the binary operation used in the reduction. The identity value is not passed to this version as it is statically known.
Definition at line 1076 of file reduction.hpp.
this_sub_group()
sub_group cl::sycl::ONEAPI::this_sub_group () inline
Definition at line 531 of file sub_group.hpp.
References PI_INVALID_DEVICE.
Referenced by cl::sycl::ONEAPI::sub_group::barrier().
to_device_func_ptr()
template<class FuncType , typename FuncPtrType = typename std::add_pointer<FuncType>::type, typename std::enable_if< std::is_function< FuncType >::value, int >::type = 0> FuncPtrType cl::sycl::ONEAPI::to_device_func_ptr (device_func_ptr_holder_t FptrHolder) inline
this function performs a cast from device_func_ptr_holder_t type to the provided function pointer type.
Definition at line 42 of file function_pointer.hpp.
Variable Documentation
memory_order_acq_rel
__SYCL_INLINE_CONSTEXPR memory_order cl::sycl::ONEAPI::memory_order_acq_rel
Initial value:
=
    memory_order::acq_rel
Definition at line 39 of file atomic_enums.hpp.
Referenced by cl::sycl::ONEAPI::detail::getStdMemoryOrder().
memory_order_acquire
__SYCL_INLINE_CONSTEXPR memory_order cl::sycl::ONEAPI::memory_order_acquire
Initial value:
=
    memory_order::acquire
Definition at line 35 of file atomic_enums.hpp.
Referenced by cl::sycl::ONEAPI::detail::getLoadOrder(), cl::sycl::ONEAPI::detail::getStdMemoryOrder(), and cl::sycl::detail::SpinLock::lock().
memory_order_relaxed
__SYCL_INLINE_CONSTEXPR memory_order cl::sycl::ONEAPI::memory_order_relaxed
Initial value:
=
    memory_order::relaxed
Definition at line 33 of file atomic_enums.hpp.
Referenced by cl::sycl::ONEAPI::detail::getLoadOrder(), cl::sycl::detail::getStdMemoryOrder(), and cl::sycl::ONEAPI::detail::getStdMemoryOrder().
memory_order_release
__SYCL_INLINE_CONSTEXPR memory_order cl::sycl::ONEAPI::memory_order_release
Initial value:
=
    memory_order::release
Definition at line 37 of file atomic_enums.hpp.
Referenced by cl::sycl::ONEAPI::detail::getStdMemoryOrder(), and cl::sycl::detail::SpinLock::unlock().
memory_order_seq_cst
__SYCL_INLINE_CONSTEXPR memory_order cl::sycl::ONEAPI::memory_order_seq_cst
Initial value:
=
    memory_order::seq_cst
Definition at line 41 of file atomic_enums.hpp.
Referenced by __spirv_MemoryBarrier(), cl::sycl::ONEAPI::detail::getLoadOrder(), and cl::sycl::ONEAPI::detail::getStdMemoryOrder().
memory_scope_device
__SYCL_INLINE_CONSTEXPR memory_scope cl::sycl::ONEAPI::memory_scope_device = memory_scope::device
Definition at line 57 of file atomic_enums.hpp.
memory_scope_sub_group
__SYCL_INLINE_CONSTEXPR memory_scope cl::sycl::ONEAPI::memory_scope_sub_group
Initial value:
=
    memory_scope::sub_group
Definition at line 53 of file atomic_enums.hpp.
memory_scope_system
__SYCL_INLINE_CONSTEXPR memory_scope cl::sycl::ONEAPI::memory_scope_system = memory_scope::system
Definition at line 58 of file atomic_enums.hpp.
memory_scope_work_group
__SYCL_INLINE_CONSTEXPR memory_scope cl::sycl::ONEAPI::memory_scope_work_group
Initial value:
=
    memory_scope::work_group
Definition at line 55 of file atomic_enums.hpp.
memory_scope_work_item
__SYCL_INLINE_CONSTEXPR memory_scope cl::sycl::ONEAPI::memory_scope_work_item
Initial value:
=
    memory_scope::work_item
Definition at line 51 of file atomic_enums.hpp.