DPC++ Runtime: cl::__ESIMD_ENS::detail Namespace Reference
cl::__ESIMD_ENS::detail Namespace Reference
DPC++ Explicit SIMD API » ESIMD core.DPC++ Explicit SIMD API » Memory access API. » | LSC memory access APIs.
Classes
class cache_hint_wrap
struct lsc_bitcast_type
struct lsc_expand_type
Enumerations
enum lsc_atomic_op : uint8_t {
lsc_atomic_op::iinc = 0x08, lsc_atomic_op::idec = 0x09, lsc_atomic_op::load = 0x0a, lsc_atomic_op::store = 0x0b,
lsc_atomic_op::iadd = 0x0c, lsc_atomic_op::isub = 0x0d, lsc_atomic_op::smin = 0x0e, lsc_atomic_op::smax = 0x0f,
lsc_atomic_op::umin = 0x10, lsc_atomic_op::umax = 0x11, lsc_atomic_op::icas = 0x12, lsc_atomic_op::fadd = 0x13,
lsc_atomic_op::fsub = 0x14, lsc_atomic_op::fmin = 0x15, lsc_atomic_op::fmax = 0x16, lsc_atomic_op::fcas = 0x17,
lsc_atomic_op::bit_and = 0x18, lsc_atomic_op::bit_or = 0x19, lsc_atomic_op::bit_xor = 0x1a
}
LSC atomic operations op codes.
enum lsc_vector_size : uint8_t {
lsc_vector_size::n1 = 1, lsc_vector_size::n2 = 2, lsc_vector_size::n3 = 3, lsc_vector_size::n4 = 4,
lsc_vector_size::n8 = 5, lsc_vector_size::n16 = 6, lsc_vector_size::n32 = 7, lsc_vector_size::n64 = 8
}
enum lsc_data_order : uint8_t { lsc_data_order::nontranspose = 1, lsc_data_order::transpose = 2 }
enum lsc_action { lsc_action::prefetch, lsc_action::load, lsc_action::store, lsc_action::atomic }
Functions
template<lsc_vector_size VS>
constexpr void check_lsc_vector_size ()
template<typename T , lsc_data_size DS>
constexpr void check_lsc_data_size ()
template<__ESIMD_NS::atomic_op Op>
constexpr void check_lsc_atomic_op ()
template<__ESIMD_NS::atomic_op Op, unsigned NumSrc>
constexpr void check_lsc_atomic ()
Check the legality of lsc xatomic call in terms of size and type.
template<__ESIMD_NS::atomic_op Op>
constexpr lsc_atomic_op to_lsc_atomic_op ()
template<lsc_vector_size VS>
constexpr uint8_t to_int ()
template<uint8_t VS>
constexpr lsc_vector_size to_lsc_vector_size ()
template<typename T , lsc_data_size DS>
constexpr lsc_data_size finalize_data_size ()
constexpr lsc_data_size expand_data_size (lsc_data_size DS)
constexpr bool are_both (cache_hint First, cache_hint Second, cache_hint Val)
template<lsc_action Action, cache_hint L1, cache_hint L3>
constexpr void check_lsc_cache_hint ()
template<typename T , int NBlocks, int Height, int Width, bool Transposed, bool Transformed>
constexpr int get_lsc_block_2d_data_size ()
template<typename T , typename T1 , int N>
ESIMD_INLINE __ESIMD_NS::simd< T, N > lsc_format_ret (__ESIMD_NS::simd< T1, N > Vals)
Enumeration Type Documentation
lsc_action
enum cl::__ESIMD_ENS::detail::lsc_action strong
Enumerator
prefetch
load
store
atomic
Definition at line 372 of file common.hpp.
lsc_atomic_op
enum cl::__ESIMD_ENS::detail::lsc_atomic_op : uint8_t strong
LSC atomic operations op codes.
Enumerator
iinc
idec
load
store
iadd
isub
smin
smax
umin
umax
icas
fadd
fsub
fmin
fmax
fcas
bit_and
bit_or
bit_xor
Definition at line 90 of file common.hpp.
lsc_data_order
enum cl::__ESIMD_ENS::detail::lsc_data_order : uint8_t strong
Enumerator
nontranspose
transpose
Definition at line 123 of file common.hpp.
lsc_vector_size
enum cl::__ESIMD_ENS::detail::lsc_vector_size : uint8_t strong
Enumerator
n1
n2
n3
n4
n8
n16
n32
n64
Definition at line 112 of file common.hpp.
Function Documentation
are_both()
constexpr bool cl::__ESIMD_ENS::detail::are_both (cache_hint First, cache_hint Second, cache_hint Val) constexpr
Definition at line 368 of file common.hpp.
Referenced by check_lsc_cache_hint().
check_lsc_atomic()
template<__ESIMD_NS::atomic_op Op, unsigned NumSrc> constexpr void cl::__ESIMD_ENS::detail::check_lsc_atomic () constexpr
Check the legality of lsc xatomic call in terms of size and type.
Definition at line 173 of file common.hpp.
References cl::sycl::detail::device_global_map::add(), cl::sycl::dec, cl::sycl::fmax(), cl::sycl::fmin(), max(), and min().
check_lsc_atomic_op()
template<__ESIMD_NS::atomic_op Op> constexpr void cl::__ESIMD_ENS::detail::check_lsc_atomic_op () constexpr
Definition at line 148 of file common.hpp.
References cl::sycl::detail::device_global_map::add(), cl::sycl::dec, cl::sycl::fmax(), cl::sycl::fmin(), max(), and min().
check_lsc_cache_hint()
template<lsc_action Action, cache_hint L1, cache_hint L3> constexpr void cl::__ESIMD_ENS::detail::check_lsc_cache_hint () constexpr
Definition at line 375 of file common.hpp.
References are_both().
check_lsc_data_size()
template<typename T , lsc_data_size DS> constexpr void cl::__ESIMD_ENS::detail::check_lsc_data_size () constexpr
Definition at line 142 of file common.hpp.
check_lsc_vector_size()
template<lsc_vector_size VS> constexpr void cl::__ESIMD_ENS::detail::check_lsc_vector_size () constexpr
Definition at line 128 of file common.hpp.
expand_data_size()
constexpr lsc_data_size cl::__ESIMD_ENS::detail::expand_data_size (lsc_data_size DS) constexpr
Definition at line 313 of file common.hpp.
Referenced by cl::__ESIMD_ENS::lsc_atomic_update(), cl::__ESIMD_ENS::lsc_gather(), cl::__ESIMD_ENS::lsc_prefetch(), cl::__ESIMD_ENS::lsc_scatter(), cl::__ESIMD_ENS::lsc_slm_atomic_update(), cl::__ESIMD_ENS::lsc_slm_gather(), and cl::__ESIMD_ENS::lsc_slm_scatter().
finalize_data_size()
template<typename T , lsc_data_size DS> constexpr lsc_data_size cl::__ESIMD_ENS::detail::finalize_data_size () constexpr
Definition at line 297 of file common.hpp.
get_lsc_block_2d_data_size()
template<typename T , int NBlocks, int Height, int Width, bool Transposed, bool Transformed> constexpr int cl::__ESIMD_ENS::detail::get_lsc_block_2d_data_size () constexpr
Definition at line 256 of file memory.hpp.
lsc_format_ret()
template<typename T , typename T1 , int N> ESIMD_INLINE __ESIMD_NS::simd<T, N> cl::__ESIMD_ENS::detail::lsc_format_ret (__ESIMD_NS::simd< T1, N > Vals)
Definition at line 266 of file memory.hpp.
to_int()
template<lsc_vector_size VS> constexpr uint8_t cl::__ESIMD_ENS::detail::to_int () constexpr
Definition at line 248 of file common.hpp.
to_lsc_atomic_op()
template<__ESIMD_NS::atomic_op Op> constexpr lsc_atomic_op cl::__ESIMD_ENS::detail::to_lsc_atomic_op () constexpr
Definition at line 202 of file common.hpp.
References cl::sycl::detail::device_global_map::add(), cl::sycl::dec, cl::sycl::fmax(), cl::sycl::fmin(), max(), and min().
to_lsc_vector_size()
template<uint8_t VS> constexpr lsc_vector_size cl::__ESIMD_ENS::detail::to_lsc_vector_size () constexpr
Definition at line 272 of file common.hpp.