DPC++ Runtime: cl::sycl::level0 Namespace Reference
cl::sycl::level0 Namespace Reference
Functions
platform make_platform (pi_native_handle NativeHandle)
device make_device (const platform &Platform, pi_native_handle NativeHandle)
program make_program (const context &Context, pi_native_handle NativeHandle)
queue make_queue (const context &Context, pi_native_handle InteropHandle)
template<typename T , typename std::enable_if< std::is_same< T, platform >::value >::type * = nullptr>
T make (typename interop< backend::level0, T >::type Interop)
template<typename T , typename std::enable_if< std::is_same< T, device >::value >::type * = nullptr>
T make (const platform &Platform, typename interop< backend::level0, T >::type Interop)
template<typename T , typename std::enable_if< std::is_same< T, program >::value >::type * = nullptr>
T make (const context &Context, typename interop< backend::level0, T >::type Interop)
Function Documentation
make() [1/3]
template<typename T , typename std::enable_if< std::is_same< T, platform >::value >::type * = nullptr> T cl::sycl::level0::make (typename interop< backend::level0, T >::type Interop)
Definition at line 51 of file level_zero.hpp.
References make_platform().
make() [2/3]
template<typename T , typename std::enable_if< std::is_same< T, device >::value >::type * = nullptr> T cl::sycl::level0::make (const platform & Platform, typename interop< backend::level0, T >::type Interop)
Definition at line 58 of file level_zero.hpp.
References make_device().
make() [3/3]
template<typename T , typename std::enable_if< std::is_same< T, program >::value >::type * = nullptr> T cl::sycl::level0::make (const context & Context, typename interop< backend::level0, T >::type Interop)
Definition at line 66 of file level_zero.hpp.
References make_program(), and make_queue().
make_device()
device cl::sycl::level0::make_device (const platform & Platform, pi_native_handle NativeHandle)
Definition at line 36 of file level_zero.cpp.
References cl::sycl::detail::getSyclObjImpl(), and piextDeviceCreateWithNativeHandle().
Referenced by make().
make_platform()
platform cl::sycl::level0::make_platform (pi_native_handle NativeHandle)
Definition at line 22 of file level_zero.cpp.
References piextPlatformCreateWithNativeHandle().
Referenced by make().
make_program()
program cl::sycl::level0::make_program (const context & Context, pi_native_handle NativeHandle)
Definition at line 51 of file level_zero.cpp.
References cl::sycl::detail::getSyclObjImpl().
Referenced by make().
make_queue()
queue cl::sycl::level0::make_queue (const context & Context, pi_native_handle InteropHandle)
Definition at line 62 of file level_zero.cpp.
References cl::sycl::detail::getSyclObjImpl(), and piextQueueCreateWithNativeHandle().
Referenced by make().