DPC++ Runtime: cl::sycl::detail::pi Namespace Reference
cl::sycl::detail::pi Namespace Reference
Classes
class ByteArray
class DeviceBinaryImage
class DeviceBinaryProperty
struct PiFuncInfo
struct printOut
struct printOut< PiEvent * >
struct printOut< PiMem * >
struct printOut< T ** >
struct printOut< void * >
Typedefs
using PiPlugin = ::pi_plugin
using PiResult = ::pi_result
using PiPlatform = ::pi_platform
using PiDevice = ::pi_device
using PiDeviceType = ::pi_device_type
using PiDeviceInfo = ::pi_device_info
using PiDeviceBinaryType = ::pi_device_binary_type
using PiContext = ::pi_context
using PiProgram = ::pi_program
using PiKernel = ::pi_kernel
using PiQueue = ::pi_queue
using PiQueueProperties = ::pi_queue_properties
using PiMem = ::pi_mem
using PiMemFlags = ::pi_mem_flags
using PiEvent = ::pi_event
using PiSampler = ::pi_sampler
using PiSamplerInfo = ::pi_sampler_info
using PiSamplerProperties = ::pi_sampler_properties
using PiSamplerAddressingMode = ::pi_sampler_addressing_mode
using PiSamplerFilterMode = ::pi_sampler_filter_mode
using PiMemImageFormat = ::pi_image_format
using PiMemImageDesc = ::pi_image_desc
using PiMemImageInfo = ::pi_image_info
using PiMemObjectType = ::pi_mem_type
using PiMemImageChannelOrder = ::pi_image_channel_order
using PiMemImageChannelType = ::pi_image_channel_type
Enumerations
enum TraceLevel { PI_TRACE_BASIC = 0x1, PI_TRACE_CALLS = 0x2, PI_TRACE_ALL = -1 }
Functions
bool trace (TraceLevel level)
void die (const char *Message)
void assertion (bool Condition, const char *Message=nullptr)
template<typename T >
void handleUnknownParamName (const char *functionName, T parameter)
void contextSetExtendedDeleter (const cl::sycl::context &constext, pi_context_extended_deleter func, void *user_data)
void * loadOsLibrary (const std::string &Library)
int unloadOsLibrary (void *Library)
int unloadPlugin (void *Library)
void * getOsLibraryFuncAddress (void *Library, const std::string &FunctionName)
std::string platformInfoToString (pi_platform_info info)
template<class To , class From >
To cast (From value)
std::vector< plugin > & initialize ()
template<backend BE>
const plugin & getPlugin ()
uint64_t emitFunctionBeginTrace (const char *FName)
Emits an XPTI trace before a PI API call is made.
void emitFunctionEndTrace (uint64_t CorrelationID, const char *FName)
Emits an XPTI trace after the PI API call has been made.
uint64_t emitFunctionWithArgsBeginTrace (uint32_t FuncID, const char *FName, unsigned char *ArgsData, pi_plugin Plugin)
Notifies XPTI subscribers about PI function calls and packs call arguments.
void emitFunctionWithArgsEndTrace (uint64_t CorrelationID, uint32_t FuncID, const char *FName, unsigned char *ArgsData, pi_result Result, pi_plugin Plugin)
Notifies XPTI subscribers about PI function call result.
std::ostream & operator<< (std::ostream &Out, const DeviceBinaryProperty &P)
PiDeviceBinaryType getBinaryImageFormat (const unsigned char *ImgData, size_t ImgSize)
Tries to determine the device binary image foramat.
template<class To >
To cast (std::vector< cl_event > value)
template<>
pi::PiDevice cast (cl_device_id)
static void initializePlugins (std::vector< plugin > &Plugins)
std::string memFlagToString (pi_mem_flags Flag)
std::string memFlagsToString (pi_mem_flags Flags)
std::vector< std::pair< std::string, backend > > findPlugins ()
void * loadPlugin (const std::string &PluginPath)
bool bindPlugin (void *Library, const std::shared_ptr< PiPlugin > &PluginInformation)
const template plugin & getPlugin< backend::opencl > ()
const template plugin & getPlugin< backend::ext_oneapi_level_zero > ()
const template plugin & getPlugin< backend::ext_intel_esimd_emulator > ()
static pi_uint32 asUint32 (const void *Addr)
template<typename T >
std::enable_if<!std::is_pointer< T >::value, void >::type print (T val)
template<typename T >
std::enable_if< std::is_pointer< T >::value, void >::type print (T val)
template<>
void print (PiPlatform val)
template<>
void print (PiEvent val)
template<>
void print (PiMem val)
template<>
void print (PiEvent *val)
template<>
void print (const PiEvent *val)
template<>
void print (pi_buffer_region rgn)
template<>
void print (pi_buff_rect_region rgn)
template<>
void print (pi_buff_rect_offset off)
template<>
void print (pi_image_region rgn)
template<>
void print (pi_image_offset off)
template<>
void print (const pi_image_desc *desc)
template<>
void print (PiResult val)
template<>
void print (std::nullptr_t)
template<>
void print (char *val)
template<>
void print (const char *val)
void printArgs (void)
template<typename Arg0 , typename... Args>
void printArgs (Arg0 arg0, Args... args)
void printOuts (void)
template<typename Arg0 , typename... Args>
void printOuts (Arg0 arg0, Args... args)
void cuPrint (const char *Message)
void hipPrint (const char *Message)
Variables
std::shared_ptr< plugin > GlobalPlugin
template<>
pi::PiProgram cast (cl_program)
bool XPTIInitDone = false
Typedef Documentation
PiContext
using cl::sycl::detail::pi::PiContext = typedef ::pi_context
Definition at line 106 of file pi.hpp.
PiDevice
using cl::sycl::detail::pi::PiDevice = typedef ::pi_device
Definition at line 102 of file pi.hpp.
PiDeviceBinaryType
using cl::sycl::detail::pi::PiDeviceBinaryType = typedef ::pi_device_binary_type
Definition at line 105 of file pi.hpp.
PiDeviceInfo
using cl::sycl::detail::pi::PiDeviceInfo = typedef ::pi_device_info
Definition at line 104 of file pi.hpp.
PiDeviceType
using cl::sycl::detail::pi::PiDeviceType = typedef ::pi_device_type
Definition at line 103 of file pi.hpp.
PiEvent
using cl::sycl::detail::pi::PiEvent = typedef ::pi_event
Definition at line 113 of file pi.hpp.
PiKernel
using cl::sycl::detail::pi::PiKernel = typedef ::pi_kernel
Definition at line 108 of file pi.hpp.
PiMem
using cl::sycl::detail::pi::PiMem = typedef ::pi_mem
Definition at line 111 of file pi.hpp.
PiMemFlags
using cl::sycl::detail::pi::PiMemFlags = typedef ::pi_mem_flags
Definition at line 112 of file pi.hpp.
PiMemImageChannelOrder
using cl::sycl::detail::pi::PiMemImageChannelOrder = typedef ::pi_image_channel_order
Definition at line 123 of file pi.hpp.
PiMemImageChannelType
using cl::sycl::detail::pi::PiMemImageChannelType = typedef ::pi_image_channel_type
Definition at line 124 of file pi.hpp.
PiMemImageDesc
using cl::sycl::detail::pi::PiMemImageDesc = typedef ::pi_image_desc
Definition at line 120 of file pi.hpp.
PiMemImageFormat
using cl::sycl::detail::pi::PiMemImageFormat = typedef ::pi_image_format
Definition at line 119 of file pi.hpp.
PiMemImageInfo
using cl::sycl::detail::pi::PiMemImageInfo = typedef ::pi_image_info
Definition at line 121 of file pi.hpp.
PiMemObjectType
using cl::sycl::detail::pi::PiMemObjectType = typedef ::pi_mem_type
Definition at line 122 of file pi.hpp.
PiPlatform
using cl::sycl::detail::pi::PiPlatform = typedef ::pi_platform
Definition at line 101 of file pi.hpp.
PiPlugin
using cl::sycl::detail::pi::PiPlugin = typedef ::pi_plugin
Definition at line 99 of file pi.hpp.
PiProgram
using cl::sycl::detail::pi::PiProgram = typedef ::pi_program
Definition at line 107 of file pi.hpp.
PiQueue
using cl::sycl::detail::pi::PiQueue = typedef ::pi_queue
Definition at line 109 of file pi.hpp.
PiQueueProperties
using cl::sycl::detail::pi::PiQueueProperties = typedef ::pi_queue_properties
Definition at line 110 of file pi.hpp.
PiResult
using cl::sycl::detail::pi::PiResult = typedef ::pi_result
Definition at line 100 of file pi.hpp.
PiSampler
using cl::sycl::detail::pi::PiSampler = typedef ::pi_sampler
Definition at line 114 of file pi.hpp.
PiSamplerAddressingMode
using cl::sycl::detail::pi::PiSamplerAddressingMode = typedef ::pi_sampler_addressing_mode
Definition at line 117 of file pi.hpp.
PiSamplerFilterMode
using cl::sycl::detail::pi::PiSamplerFilterMode = typedef ::pi_sampler_filter_mode
Definition at line 118 of file pi.hpp.
PiSamplerInfo
using cl::sycl::detail::pi::PiSamplerInfo = typedef ::pi_sampler_info
Definition at line 115 of file pi.hpp.
PiSamplerProperties
using cl::sycl::detail::pi::PiSamplerProperties = typedef ::pi_sampler_properties
Definition at line 116 of file pi.hpp.
Enumeration Type Documentation
TraceLevel
enum cl::sycl::detail::pi::TraceLevel
Enumerator
PI_TRACE_BASIC
PI_TRACE_CALLS
PI_TRACE_ALL
Definition at line 55 of file pi.hpp.
Function Documentation
assertion()
void cl::sycl::detail::pi::assertion (bool Condition, const char * Message = nullptr)
Definition at line 542 of file pi.cpp.
References die().
Referenced by cast(), cuda_piContextGetInfo(), cuda_piDeviceGetInfo(), cuda_piEventRelease(), cuda_piEventRetain(), cuda_piKernelGetGroupInfo(), cuda_piKernelGetSubGroupInfo(), cuda_piSamplerRelease(), hip_piDeviceGetInfo(), hip_piEventRelease(), hip_piEventRetain(), hip_piKernelGetGroupInfo(), hip_piKernelGetSubGroupInfo(), hip_piSamplerRelease(), and memFlagToString().
asUint32()
static pi_uint32 cl::sycl::detail::pi::asUint32 (const void * Addr) static
Definition at line 627 of file pi.cpp.
Referenced by cl::sycl::detail::appendCompileOptionsFromImage(), and cl::sycl::detail::pi::DeviceBinaryProperty::asUint32().
bindPlugin()
bool cl::sycl::detail::pi::bindPlugin (void * Library, const std::shared_ptr< PiPlugin > & PluginInformation)
Definition at line 349 of file pi.cpp.
References getOsLibraryFuncAddress(), PI_SUCCESS, and piPluginInit().
Referenced by initializePlugins().
cast() [1/3]
template<> pi::PiDevice cl::sycl::detail::pi::cast (cl_device_id) inline
Definition at line 438 of file pi.hpp.
References assertion().
cast() [2/3]
template<class To , class From > To cl::sycl::detail::pi::cast (From value) inline
Definition at line 417 of file pi.hpp.
References assertion().
cast() [3/3]
template<class To > To cl::sycl::detail::pi::cast (std::vector< cl_event > value) inline
Definition at line 425 of file pi.hpp.
References assertion().
contextSetExtendedDeleter()
void cl::sycl::detail::pi::contextSetExtendedDeleter (const cl::sycl::context & constext, pi_context_extended_deleter func, void * user_data)
Definition at line 183 of file pi.cpp.
References cl::sycl::detail::plugin::call(), cl::sycl::detail::getSyclObjImpl(), and piextContextSetExtendedDeleter().
cuPrint()
void cl::sycl::detail::pi::cuPrint (const char * Message)
Definition at line 291 of file pi_cuda.cpp.
Referenced by cuda_piclProgramCreateWithSource(), and cuda_piDeviceGetInfo().
die()
void cl::sycl::detail::pi::die (const char * Message)
Definition at line 537 of file pi.cpp.
Referenced by assertion(), _pi_event::cleanup(), cuda_piContextCreate(), cuda_piDeviceGetInfo(), cuda_piEnqueueMemImageFill(), cuda_piEnqueueNativeKernel(), cuda_piEventCreate(), cuda_piEventGetProfilingInfo(), cuda_piEventSetCallback(), cuda_piEventSetStatus(), cuda_piextContextCreateWithNativeHandle(), cuda_piextDeviceCreateWithNativeHandle(), cuda_piextDeviceSelectBinary(), cuda_piextEventCreateWithNativeHandle(), cuda_piextKernelCreateWithNativeHandle(), cuda_piextKernelSetArgMemObj(), cuda_piextMemCreateWithNativeHandle(), cuda_piextProgramCreateWithNativeHandle(), cuda_piextQueueCreateWithNativeHandle(), cuda_piextUSMEnqueueMemAdvise(), cuda_piextUSMEnqueuePrefetch(), cuda_piMemGetInfo(), cuda_piMemImageCreate(), cuda_piMemImageGetInfo(), cuda_piMemRelease(), cuda_piPlatformGetInfo(), cuda_piProgramCreate(), cuda_piProgramGetBuildInfo(), cuda_piProgramGetInfo(), cuda_piQueueGetInfo(), _pi_context::decrementUnreleasedEventsInPool(), EventRelease(), _pi_queue::executeCommandList(), cl::sycl::detail::SYCLConfig< SYCL_BE >::get(), getKernelNames(), _pi_event::getOrCreateHostVisibleEvent(), _pi_queue::pi_queue_group_t::getZeQueue(), handleUnknownParamName(), hip_piContextCreate(), hip_piDeviceGetInfo(), hip_piEnqueueKernelLaunch(), hip_piEnqueueMemImageFill(), hip_piEnqueueNativeKernel(), hip_piEventCreate(), hip_piEventGetProfilingInfo(), hip_piEventSetCallback(), hip_piEventSetStatus(), hip_piextContextCreateWithNativeHandle(), hip_piextDeviceCreateWithNativeHandle(), hip_piextDeviceSelectBinary(), hip_piextEventCreateWithNativeHandle(), hip_piextKernelSetArgMemObj(), hip_piextMemCreateWithNativeHandle(), hip_piextProgramCreateWithNativeHandle(), hip_piextQueueCreateWithNativeHandle(), hip_piKernelGetGroupInfo(), hip_piMemGetInfo(), hip_piMemImageCreate(), hip_piMemImageGetInfo(), hip_piMemRelease(), hip_piPlatformGetInfo(), hip_piProgramCreate(), hip_piProgramGetBuildInfo(), hip_piProgramGetInfo(), hip_piProgramLink(), hip_piQueueGetInfo(), imageElementByteSize(), piContextGetInfo(), piDeviceGetInfo(), piDeviceRelease(), piEnqueueMemImageFill(), piEnqueueNativeKernel(), piEventSetCallback(), piEventSetStatus(), piEventsWait(), piextContextSetExtendedDeleter(), piextMemCreateWithNativeHandle(), piKernelGetGroupInfo(), piKernelGetSubGroupInfo(), piMemBufferCreate(), piMemBufferPartition(), piMemGetInfo(), piMemImageCreate(), piMemImageGetInfo(), piPlatformGetInfo(), piProgramGetInfo(), piQueueGetInfo(), piSamplerGetInfo(), platformInfoToString(), _pi_event::record(), USMFreeHelper(), ZeCommandListBatchConfig(), ZeMemFreeHelper(), and ReleaseGuard< T >::~ReleaseGuard().
emitFunctionBeginTrace()
uint64_t cl::sycl::detail::pi::emitFunctionBeginTrace (const char * FName)
Emits an XPTI trace before a PI API call is made.
Parameters
FName The name of the PI API call
Returns
The correlation ID for the API call that is to be used by the emitFunctionEndTrace() call
Definition at line 87 of file pi.cpp.
References cl::sycl::detail::SYCL_PICALL_STREAM_NAME.
Referenced by cl::sycl::detail::plugin::call_nocheck().
emitFunctionEndTrace()
void cl::sycl::detail::pi::emitFunctionEndTrace (uint64_t CorrelationID, const char * FName)
Emits an XPTI trace after the PI API call has been made.
Parameters
CorrelationID The correlation ID for the API call generated by the emitFunctionBeginTrace() call.
FName The name of the PI API call
Definition at line 131 of file pi.cpp.
References cl::sycl::detail::SYCL_PICALL_STREAM_NAME.
Referenced by cl::sycl::detail::plugin::call_nocheck().
emitFunctionWithArgsBeginTrace()
uint64_t cl::sycl::detail::pi::emitFunctionWithArgsBeginTrace (uint32_t FuncID, const char * FName, unsigned char * ArgsData, pi_plugin Plugin)
Notifies XPTI subscribers about PI function calls and packs call arguments.
Parameters
FuncID is the API hash ID from PiApiID type trait.
FName The name of the PI API call.
ArgsData is a pointer to packed function call arguments.
Plugin is the plugin, which is used to make call.
Definition at line 146 of file pi.cpp.
References cl::sycl::detail::SYCL_PIDEBUGCALL_STREAM_NAME.
Referenced by cl::sycl::detail::plugin::call_nocheck().
emitFunctionWithArgsEndTrace()
void cl::sycl::detail::pi::emitFunctionWithArgsEndTrace (uint64_t CorrelationID, uint32_t FuncID, const char * FName, unsigned char * ArgsData, pi_result Result, pi_plugin Plugin)
Notifies XPTI subscribers about PI function call result.
Parameters
CorrelationID The correlation ID for the API call generated by the emitFunctionWithArgsBeginTrace() call.
FuncID is the API hash ID from PiApiID type trait.
FName The name of the PI API call.
ArgsData is a pointer to packed function call arguments.
Result is function call result value.
Plugin is the plugin, which is used to make call.
Definition at line 166 of file pi.cpp.
References cl::sycl::detail::SYCL_PIDEBUGCALL_STREAM_NAME.
Referenced by cl::sycl::detail::plugin::call_nocheck().
findPlugins()
std::vector<std::pair<std::string, backend> > cl::sycl::detail::pi::findPlugins ()
Definition at line 273 of file pi.cpp.
References __SYCL_CUDA_PLUGIN_NAME, __SYCL_ESIMD_EMULATOR_PLUGIN_NAME, __SYCL_HIP_PLUGIN_NAME, __SYCL_LEVEL_ZERO_PLUGIN_NAME, __SYCL_OPENCL_PLUGIN_NAME, cl::sycl::all(), cl::sycl::detail::device_filter_list::get(), and std::get().
Referenced by initializePlugins().
getBinaryImageFormat()
RT::PiDeviceBinaryType cl::sycl::detail::pi::getBinaryImageFormat (const unsigned char * ImgData, size_t ImgSize)
Tries to determine the device binary image foramat.
Returns PI_DEVICE_BINARY_TYPE_NONE if unsuccessful.
Definition at line 687 of file pi.cpp.
References PI_DEVICE_BINARY_TYPE_LLVMIR_BITCODE, PI_DEVICE_BINARY_TYPE_NONE, and PI_DEVICE_BINARY_TYPE_SPIRV.
Referenced by cl::sycl::detail::ProgramManager::createPIProgram(), cl::sycl::detail::DynRTDeviceBinaryImage::DynRTDeviceBinaryImage(), and cl::sycl::detail::pi::DeviceBinaryImage::init().
getOsLibraryFuncAddress()
void * cl::sycl::detail::pi::getOsLibraryFuncAddress (void * Library, const std::string & FunctionName)
Definition at line 34 of file posix_pi.cpp.
Referenced by bindPlugin(), and cl::sycl::ext::intel::experimental::detail::compileToSPIRV().
getPlugin()
template<backend BE> const plugin & cl::sycl::detail::pi::getPlugin ()
Definition at line 511 of file pi.cpp.
References initialize(), and PI_INVALID_OPERATION.
Referenced by cl::sycl::detail::queue_impl::createQueue(), cl::sycl::detail::event_impl::get(), cl::sycl::detail::kernel_impl::get(), cl::sycl::detail::queue_impl::get(), cl::sycl::detail::platform_impl::get_devices(), cl::sycl::detail::platform_impl::get_info(), cl::sycl::detail::kernel_impl::get_info(), cl::sycl::detail::device_impl::get_info(), cl::sycl::detail::queue_impl::getExclusiveQueueHandleRef(), cl::sycl::detail::platform_impl::getNative(), cl::sycl::detail::queue_impl::getNative(), cl::sycl::detail::platform_impl::has_extension(), cl::sycl::detail::queue_impl::get_info< info::queue::reference_count >(), cl::sycl::detail::queue_impl::wait(), cl::sycl::detail::event_impl::waitInternal(), cl::sycl::detail::event_impl::~event_impl(), and cl::sycl::detail::queue_impl::~queue_impl().
getPlugin< backend::ext_intel_esimd_emulator >()
const template plugin& cl::sycl::detail::pi::getPlugin< backend::ext_intel_esimd_emulator > ()
getPlugin< backend::ext_oneapi_level_zero >()
const template plugin& cl::sycl::detail::pi::getPlugin< backend::ext_oneapi_level_zero > ()
getPlugin< backend::opencl >()
const template plugin& cl::sycl::detail::pi::getPlugin< backend::opencl > ()
handleUnknownParamName()
template<typename T > void cl::sycl::detail::pi::handleUnknownParamName (const char * functionName, T parameter)
Definition at line 84 of file pi.hpp.
References die().
hipPrint()
void cl::sycl::detail::pi::hipPrint (const char * Message)
Definition at line 344 of file pi_hip.cpp.
Referenced by hip_piclProgramCreateWithSource().
initialize()
std::vector< plugin > & cl::sycl::detail::pi::initialize ()
Definition at line 374 of file pi.cpp.
References initializePlugins().
Referenced by cl::sycl::detail::filterDeviceFilter(), cl::sycl::detail::platform_impl::get_devices(), cl::sycl::detail::platform_impl::get_platforms(), and getPlugin().
initializePlugins()
static void cl::sycl::detail::pi::initializePlugins (std::vector< plugin > & Plugins) static
Definition at line 384 of file pi.cpp.
References _PI_H_VERSION_STRING, bindPlugin(), findPlugins(), std::get(), GlobalPlugin, loadPlugin(), PI_TRACE_ALL, PI_TRACE_BASIC, cl::sycl::detail::SYCL_PICALL_STREAM_NAME, cl::sycl::detail::SYCL_PIDEBUGCALL_STREAM_NAME, cl::sycl::detail::SYCL_STREAM_NAME, trace(), and XPTIInitDone.
Referenced by initialize().
loadOsLibrary()
void * cl::sycl::detail::pi::loadOsLibrary (const std::string & Library)
Definition at line 20 of file posix_pi.cpp.
References PI_TRACE_ALL, and trace().
Referenced by cl::sycl::ext::intel::experimental::detail::compileToSPIRV(), and loadPlugin().
loadPlugin()
void* cl::sycl::detail::pi::loadPlugin (const std::string & PluginPath)
Definition at line 335 of file pi.cpp.
References loadOsLibrary().
Referenced by initializePlugins().
memFlagsToString()
std::string cl::sycl::detail::pi::memFlagsToString (pi_mem_flags Flags)
Definition at line 236 of file pi.cpp.
References memFlagToString(), PI_MEM_FLAGS_ACCESS_RW, PI_MEM_FLAGS_HOST_PTR_COPY, and PI_MEM_FLAGS_HOST_PTR_USE.
memFlagToString()
std::string cl::sycl::detail::pi::memFlagToString (pi_mem_flags Flag)
Definition at line 210 of file pi.cpp.
References assertion(), PI_MEM_FLAGS_ACCESS_RW, PI_MEM_FLAGS_HOST_PTR_COPY, and PI_MEM_FLAGS_HOST_PTR_USE.
Referenced by memFlagsToString().
operator<<()
std::ostream & cl::sycl::detail::pi::operator<< (std::ostream & Out, const DeviceBinaryProperty & P)
Definition at line 547 of file pi.cpp.
References cl::sycl::detail::pi::DeviceBinaryProperty::asByteArray(), cl::sycl::detail::pi::DeviceBinaryProperty::asCString(), cl::sycl::detail::pi::DeviceBinaryProperty::asUint32(), _pi_device_binary_property_struct::Name, PI_PROPERTY_TYPE_BYTE_ARRAY, PI_PROPERTY_TYPE_STRING, PI_PROPERTY_TYPE_UINT32, cl::sycl::detail::pi::DeviceBinaryProperty::Prop, and _pi_device_binary_property_struct::Type.
platformInfoToString()
std::string cl::sycl::detail::pi::platformInfoToString (pi_platform_info info)
Definition at line 193 of file pi.cpp.
References die(), PI_PLATFORM_INFO_EXTENSIONS, PI_PLATFORM_INFO_NAME, PI_PLATFORM_INFO_PROFILE, PI_PLATFORM_INFO_VENDOR, and PI_PLATFORM_INFO_VERSION.
print() [1/17]
template<> void cl::sycl::detail::pi::print (char * val) inline
Definition at line 114 of file plugin_printers.hpp.
print() [2/17]
template<> void cl::sycl::detail::pi::print (const char * val) inline
Definition at line 118 of file plugin_printers.hpp.
Referenced by printArgs().
print() [3/17]
template<> void cl::sycl::detail::pi::print (const pi_image_desc * desc) inline
Definition at line 91 of file plugin_printers.hpp.
References _pi_image_desc::image_array_size, _pi_image_desc::image_depth, _pi_image_desc::image_height, _pi_image_desc::image_row_pitch, _pi_image_desc::image_slice_pitch, _pi_image_desc::image_type, _pi_image_desc::image_width, _pi_image_desc::num_mip_levels, and _pi_image_desc::num_samples.
print() [4/17]
template<> void cl::sycl::detail::pi::print (const PiEvent * val) inline
Definition at line 56 of file plugin_printers.hpp.
print() [5/17]
template<> void cl::sycl::detail::pi::print (pi_buff_rect_offset off) inline
Definition at line 76 of file plugin_printers.hpp.
References pi_buff_rect_offset_struct::x_bytes, pi_buff_rect_offset_struct::y_scalar, and pi_buff_rect_offset_struct::z_scalar.
print() [6/17]
template<> void cl::sycl::detail::pi::print (pi_buff_rect_region rgn) inline
Definition at line 70 of file plugin_printers.hpp.
References pi_buff_rect_region_struct::depth_scalar, pi_buff_rect_region_struct::height_scalar, and pi_buff_rect_region_struct::width_bytes.
print() [7/17]
template<> void cl::sycl::detail::pi::print (pi_buffer_region rgn) inline
Definition at line 65 of file plugin_printers.hpp.
References pi_buffer_region_struct::origin, and pi_buffer_region_struct::size.
print() [8/17]
template<> void cl::sycl::detail::pi::print (pi_image_offset off) inline
Definition at line 86 of file plugin_printers.hpp.
References pi_image_offset_struct::x, pi_image_offset_struct::y, and pi_image_offset_struct::z.
print() [9/17]
template<> void cl::sycl::detail::pi::print (pi_image_region rgn) inline
Definition at line 81 of file plugin_printers.hpp.
References pi_image_region_struct::depth, pi_image_region_struct::height, and pi_image_region_struct::width.
print() [10/17]
template<> void cl::sycl::detail::pi::print (PiEvent * val) inline
Definition at line 47 of file plugin_printers.hpp.
print() [11/17]
template<> void cl::sycl::detail::pi::print (PiEvent val) inline
Definition at line 39 of file plugin_printers.hpp.
print() [12/17]
template<> void cl::sycl::detail::pi::print (PiMem val) inline
Definition at line 43 of file plugin_printers.hpp.
print() [13/17]
template<> void cl::sycl::detail::pi::print (PiPlatform val) inline
Definition at line 35 of file plugin_printers.hpp.
print() [14/17]
template<> void cl::sycl::detail::pi::print (PiResult val) inline
Definition at line 101 of file plugin_printers.hpp.
References PI_SUCCESS.
print() [15/17]
template<> void cl::sycl::detail::pi::print (std::nullptr_t) inline
Definition at line 110 of file plugin_printers.hpp.
print() [16/17]
template<typename T > std::enable_if<!std::is_pointer<T>::value, void>::type cl::sycl::detail::pi::print (T val) inline
Definition at line 24 of file plugin_printers.hpp.
Referenced by cl::sycl::detail::RTDeviceBinaryImage::print(), and cl::sycl::detail::DynRTDeviceBinaryImage::print().
print() [17/17]
template<typename T > std::enable_if<std::is_pointer<T>::value, void>::type cl::sycl::detail::pi::print (T val) inline
Definition at line 30 of file plugin_printers.hpp.
printArgs() [1/2]
template<typename Arg0 , typename... Args> void cl::sycl::detail::pi::printArgs (Arg0 arg0, Args... args)
Definition at line 124 of file plugin_printers.hpp.
References print().
printArgs() [2/2]
void cl::sycl::detail::pi::printArgs (void) inline
Definition at line 122 of file plugin_printers.hpp.
Referenced by cl::sycl::detail::plugin::call_nocheck().
printOuts() [1/2]
template<typename Arg0 , typename... Args> void cl::sycl::detail::pi::printOuts (Arg0 arg0, Args... args)
Definition at line 173 of file plugin_printers.hpp.
References cl::sycl::a.
printOuts() [2/2]
void cl::sycl::detail::pi::printOuts (void) inline
Definition at line 171 of file plugin_printers.hpp.
Referenced by cl::sycl::detail::plugin::call_nocheck().
trace()
bool cl::sycl::detail::pi::trace (TraceLevel level)
Definition at line 368 of file pi.cpp.
References std::get().
Referenced by cl::sycl::detail::plugin::call_nocheck(), initializePlugins(), cl::sycl::detail::IsBannedPlatform(), loadOsLibrary(), cl::sycl::device_selector::select_device(), and cl::sycl::detail::Scheduler::~Scheduler().
unloadOsLibrary()
int cl::sycl::detail::pi::unloadOsLibrary (void * Library)
Definition at line 32 of file posix_pi.cpp.
Referenced by unloadPlugin().
unloadPlugin()
int cl::sycl::detail::pi::unloadPlugin (void * Library)
Definition at line 341 of file pi.cpp.
References unloadOsLibrary().
Referenced by cl::sycl::detail::plugin::unload().
Variable Documentation
cast
template<> pi::PiDevice cl::sycl::detail::pi::cast(cl_device_id) inline
Definition at line 433 of file pi.hpp.
GlobalPlugin
std::shared_ptr< plugin > cl::sycl::detail::pi::GlobalPlugin
Definition at line 270 of file pi.cpp.
Referenced by initializePlugins().
XPTIInitDone
bool cl::sycl::detail::pi::XPTIInitDone = false
Definition at line 83 of file pi.cpp.
Referenced by initializePlugins().