DPC++ Runtime: sycl::_V1::info Namespace Reference
sycl::_V1::info Namespace Reference
Namespaces
context
device
event
event_profiling
kernel
kernel_device_specific
platform
queue
Classes
class param_traits
struct compatibility_param_traits
Enumerations
enum class device_type : uint32_t {
cpu = UR_DEVICE_TYPE_CPU , gpu = UR_DEVICE_TYPE_GPU , accelerator = UR_DEVICE_TYPE_FPGA , custom ,
automatic , host , all = UR_DEVICE_TYPE_ALL
}
enum class partition_property : intptr_t {
no_partition = 0 , partition_equally = UR_DEVICE_PARTITION_EQUALLY , partition_by_counts = UR_DEVICE_PARTITION_BY_COUNTS , partition_by_affinity_domain = UR_DEVICE_PARTITION_BY_AFFINITY_DOMAIN ,
ext_intel_partition_by_cslice = UR_DEVICE_PARTITION_BY_CSLICE
}
enum class partition_affinity_domain : intptr_t {
not_applicable = 0 , numa = UR_DEVICE_AFFINITY_DOMAIN_FLAG_NUMA , L4_cache = UR_DEVICE_AFFINITY_DOMAIN_FLAG_L4_CACHE , L3_cache = UR_DEVICE_AFFINITY_DOMAIN_FLAG_L3_CACHE ,
L2_cache = UR_DEVICE_AFFINITY_DOMAIN_FLAG_L2_CACHE , L1_cache = UR_DEVICE_AFFINITY_DOMAIN_FLAG_L1_CACHE , next_partitionable = UR_DEVICE_AFFINITY_DOMAIN_FLAG_NEXT_PARTITIONABLE
}
enum class local_mem_type : int { none , local , global }
enum class fp_config : uint32_t {
denorm = UR_DEVICE_FP_CAPABILITY_FLAG_DENORM , inf_nan = UR_DEVICE_FP_CAPABILITY_FLAG_INF_NAN , round_to_nearest = UR_DEVICE_FP_CAPABILITY_FLAG_ROUND_TO_NEAREST , round_to_zero = UR_DEVICE_FP_CAPABILITY_FLAG_ROUND_TO_ZERO ,
round_to_inf = UR_DEVICE_FP_CAPABILITY_FLAG_ROUND_TO_INF , fma = UR_DEVICE_FP_CAPABILITY_FLAG_FMA , correctly_rounded_divide_sqrt , soft_float
}
enum class global_mem_cache_type : int { none , read_only , read_write }
enum class execution_capability : unsigned int { exec_kernel , exec_native_kernel }
enum class event_command_status : int32_t { submitted = UR_EVENT_STATUS_SUBMITTED , running = UR_EVENT_STATUS_RUNNING , complete = UR_EVENT_STATUS_COMPLETE , ext_oneapi_unknown = -1 }
Functions
partition_property ConvertPartitionProperty (const ur_device_partition_t &Partition)
partition_affinity_domain ConvertAffinityDomain (const ur_device_affinity_domain_flags_t Domain)
Enumeration Type Documentation
device_type
enum sycl::_V1::info::device_type : uint32_t strong
Enumerator
cpu
gpu
accelerator
custom
automatic
host
all
Definition at line 58 of file info_desc.hpp.
event_command_status
enum sycl::_V1::info::event_command_status : int32_t strong
Enumerator
submitted
running
complete
ext_oneapi_unknown
Definition at line 184 of file info_desc.hpp.
execution_capability
enum sycl::_V1::info::execution_capability : unsigned int strong
Enumerator
exec_kernel
exec_native_kernel
Definition at line 138 of file info_desc.hpp.
fp_config
enum sycl::_V1::info::fp_config : uint32_t strong
Enumerator
denorm
inf_nan
round_to_nearest
round_to_zero
round_to_inf
fma
correctly_rounded_divide_sqrt
soft_float
Definition at line 125 of file info_desc.hpp.
global_mem_cache_type
enum sycl::_V1::info::global_mem_cache_type : int strong
Enumerator
none
read_only
read_write
Definition at line 136 of file info_desc.hpp.
local_mem_type
enum sycl::_V1::info::local_mem_type : int strong
Enumerator
none
local
global
Definition at line 123 of file info_desc.hpp.
partition_affinity_domain
enum sycl::_V1::info::partition_affinity_domain : intptr_t strong
Enumerator
not_applicable
numa
L4_cache
L3_cache
L2_cache
L1_cache
next_partitionable
Definition at line 95 of file info_desc.hpp.
partition_property
enum sycl::_V1::info::partition_property : intptr_t strong
Enumerator
no_partition
partition_equally
partition_by_counts
partition_by_affinity_domain
ext_intel_partition_by_cslice
Definition at line 69 of file info_desc.hpp.
Function Documentation
ConvertAffinityDomain()
partition_affinity_domain sycl::_V1::info::ConvertAffinityDomain (const ur_device_affinity_domain_flags_t Domain) inline
Definition at line 106 of file info_desc.hpp.
Referenced by sycl::_V1::detail::get_device_info_impl< info::partition_affinity_domain, info::device::partition_type_affinity_domain >::get().
ConvertPartitionProperty()
partition_property sycl::_V1::info::ConvertPartitionProperty (const ur_device_partition_t & Partition) inline
Definition at line 80 of file info_desc.hpp.
References ext_intel_partition_by_cslice, no_partition, partition_by_affinity_domain, partition_by_counts, and partition_equally.
Referenced by sycl::_V1::detail::get_device_info_impl< std::vector< info::partition_property >, info::device::partition_properties >::get(), and sycl::_V1::detail::get_device_info_impl< info::partition_property, info::device::partition_type_property >::get().