DPC++ Runtime: cl::sycl::INTEL::gpu Namespace Reference
cl::sycl::INTEL::gpu Namespace Reference
Namespaces
detail
Classes
class AccessorPrivateProxy
struct bitcast_helper
struct common_type
struct computation_type
Get the computation type.
struct compute_format_type
struct compute_format_type< simd< Ty, N >, EltTy >
struct compute_format_type< simd_view< BaseTy, RegionTy >, EltTy >
struct compute_format_type_2d
struct compute_format_type_2d< simd< Ty, N >, EltTy, Height, Width >
struct compute_format_type_2d< simd_view< BaseTy, RegionTy >, EltTy, Height, Width >
struct element_type
struct element_type< simd< Ty, N > >
struct element_type< simd_view< BaseTy, RegionTy > >
struct is_esimd_arithmetic_type
struct is_esimd_arithmetic_type< Ty, __esimd_void_t< decltype(std::declval< Ty >()+std::declval< Ty >()), decltype(std::declval< Ty >() - std::declval< Ty >()), decltype(std::declval< Ty >() *std::declval< Ty >()), decltype(std::declval< Ty >()/std::declval< Ty >())> >
struct is_simd_type
struct is_simd_type< simd< Ty, N > >
struct is_simd_type< simd_view< BaseTy, RegionTy > >
struct is_simd_v
struct is_simd_view_type
struct is_simd_view_type< simd_view< BaseTy, RegionTy > >
struct is_simd_view_v
struct is_vectorizable
struct is_vectorizable< bool >
struct is_vectorizable_v
struct make_esimd_void
struct region_base
struct shape_type
struct shape_type< region1d_t< Ty, Size, Stride > >
struct shape_type< region2d_t< Ty, SizeY, StrideY, SizeX, StrideX > >
struct shape_type< simd_view< BaseTy, RegionTy > >
struct shape_type< std::pair< TopRegionTy, BaseRegionTy > >
class simd
class simd_view
struct vector_type
Typedefs
template<typename T , int Size, int Stride>
using region1d_t = region_base< false, T, 1, 0, Size, Stride >
template<typename T , int SizeY, int StrideY, int SizeX, int StrideX>
using region2d_t = region_base< true, T, SizeY, StrideY, SizeX, StrideX >
using half = cl::sycl::detail::half_impl::StorageT
template<typename T >
using remove_cvref_t = csd::remove_cv_t< csd::remove_reference_t< T > >
template<class... Tys>
using __esimd_void_t = typename make_esimd_void< Tys... >::type
template<typename Ty , int N>
using vector_type_t = typename vector_type< Ty, N >::type
template<int N>
using mask_type_t = typename vector_type< uint16_t, N >::type
template<typename Ty , typename EltTy >
using compute_format_type_t = typename compute_format_type< Ty, EltTy >::type
template<typename Ty , typename EltTy , int Height, int Width>
using compute_format_type_2d_t = typename compute_format_type_2d< Ty, EltTy, Height, Width >::type
template<typename T1 , typename T2 = T1>
using compute_type_t = typename common_type< remove_cvref_t< T1 >, remove_cvref_t< T2 > >::type
using uchar = unsigned char
using ushort = unsigned short
using uint = unsigned int
Enumerations
enum { GENX_NOSAT = 0, GENX_SAT }
enum ChannelMaskType {
ESIMD_R_ENABLE = 1, ESIMD_G_ENABLE = 2, ESIMD_GR_ENABLE = 3, ESIMD_B_ENABLE = 4,
ESIMD_BR_ENABLE = 5, ESIMD_BG_ENABLE = 6, ESIMD_BGR_ENABLE = 7, ESIMD_A_ENABLE = 8,
ESIMD_AR_ENABLE = 9, ESIMD_AG_ENABLE = 10, ESIMD_AGR_ENABLE = 11, ESIMD_AB_ENABLE = 12,
ESIMD_ABR_ENABLE = 13, ESIMD_ABG_ENABLE = 14, ESIMD_ABGR_ENABLE = 15
}
enum EsimdAtomicOpType : uint16_t {
EsimdAtomicOpType::ATOMIC_ADD = 0x0, EsimdAtomicOpType::ATOMIC_SUB = 0x1, EsimdAtomicOpType::ATOMIC_INC = 0x2, EsimdAtomicOpType::ATOMIC_DEC = 0x3,
EsimdAtomicOpType::ATOMIC_MIN = 0x4, EsimdAtomicOpType::ATOMIC_MAX = 0x5, EsimdAtomicOpType::ATOMIC_XCHG = 0x6, EsimdAtomicOpType::ATOMIC_CMPXCHG = 0x7,
EsimdAtomicOpType::ATOMIC_AND = 0x8, EsimdAtomicOpType::ATOMIC_OR = 0x9, EsimdAtomicOpType::ATOMIC_XOR = 0xa, EsimdAtomicOpType::ATOMIC_MINSINT = 0xb,
EsimdAtomicOpType::ATOMIC_MAXSINT = 0xc, EsimdAtomicOpType::ATOMIC_FMAX = 0x10, EsimdAtomicOpType::ATOMIC_FMIN = 0x11, EsimdAtomicOpType::ATOMIC_FCMPWR = 0x12,
EsimdAtomicOpType::ATOMIC_PREDEC = 0xff
}
enum CacheHint : uint8_t {
CacheHint::None = 0, CacheHint::Uncached = 1, CacheHint::WriteBack = 2, CacheHint::WriteThrough = 3,
CacheHint::Streaming = 4, CacheHint::ReadInvalidate = 5
}
enum EsimdFenceMask {
ESIMD_GLOBAL_COHERENT_FENCE = 0x1, ESIMD_L3_FLUSH_INSTRUCTIONS = 0x2, ESIMD_L3_FLUSH_TEXTURE_DATA = 0x4, ESIMD_L3_FLUSH_CONSTANT_DATA = 0x8,
ESIMD_L3_FLUSH_RW_DATA = 0x10, ESIMD_LOCAL_BARRIER = 0x20, ESIMD_L1_FLUASH_RO_DATA = 0x40, ESIMD_SW_BARRIER = 0x80
}
Functions
template<typename BT , int BN, typename RTy >
vector_type_t< typename RTy::element_type, RTy::length > ESIMD_INLINE readRegion (const vector_type_t< BT, BN > &Base, RTy Region)
read from a basic region of a vector, return a vector
template<typename BT , int BN, typename T , typename U >
ESIMD_INLINE vector_type_t< typename T::element_type, T::length > readRegion (const vector_type_t< BT, BN > &Base, std::pair< T, U > Region)
read from a nested region of a vector, return a vector
template<typename T >
T getTopRegion (T Reg)
template<typename T , typename U >
T getTopRegion (std::pair< T, U > Reg)
template<typename T >
T getBaseRegion (T Reg)
template<typename T , typename U >
T getBaseRegion (std::pair< T, U > Reg)
template<typename To , typename From >
To convert (From Val)
template<typename U >
constexpr bool is_type ()
Base case for checking if a type U is one of the types.
template<typename U , typename T , typename... Ts>
constexpr bool is_type ()
template<typename ToEltTy , typename FromEltTy , int FromN, typename = csd::enable_if_t<is_vectorizable<ToEltTy>::value>>
ESIMD_INLINE std::conditional< std::is_same< FromEltTy, ToEltTy >::value, vector_type_t< FromEltTy, FromN >, vector_type_t< ToEltTy, bitcast_helper< ToEltTy, FromEltTy, FromN >::nToElems()> >::type bitcast (vector_type_t< FromEltTy, FromN > Val)
std::ostream & operator<< (std::ostream &O, half const &rhs)
std::istream & operator>> (std::istream &I, half &rhs)
constexpr unsigned int ElemsPerAddrDecoding (unsigned int ElemsPerAddrEncoded)
template<typename U , typename T , int n>
ESIMD_INLINE simd< U, n > convert (simd< T, n > val)
template<typename T0 , typename T1 , int SZ>
ESIMD_NODEBUG ESIMD_INLINE simd< T0, SZ > esimd_sat (simd< T1, SZ > src)
template<typename T0 , typename T1 , int SZ>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< !std::is_same< typename std::remove_const< T0 >::type, typename std::remove_const< T1 >::type >::value, simd< T0, SZ > >::type esimd_abs (simd< T1, SZ > src0, int flag=GENX_NOSAT)
template<typename T0 , typename T1 >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< !std::is_same< typename std::remove_const< T0 >::type, typename std::remove_const< T1 >::type >::value &&detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value, typename std::remove_const< T0 >::type >::type esimd_abs (T1 src0, int flag=GENX_NOSAT)
template<typename T1 , int SZ>
ESIMD_NODEBUG ESIMD_INLINE simd< T1, SZ > esimd_abs (simd< T1, SZ > src0, int flag=GENX_NOSAT)
template<typename T1 >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T1 >::value, typename std::remove_const< T1 >::type >::type esimd_abs (T1 src0, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< U >::value, simd< T0, SZ > >::type esimd_shl (simd< T1, SZ > src0, U src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , typename T2 >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value &&detail::is_esimd_scalar< T2 >::value &&std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< T2 >::value, typename std::remove_const< T0 >::type >::type esimd_shl (T1 src0, T2 src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< U >::value, simd< T0, SZ > >::type esimd_shr (simd< T1, SZ > src0, U src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , typename T2 >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value &&detail::is_esimd_scalar< T2 >::value &&std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< T2 >::value, typename std::remove_const< T0 >::type >::type esimd_shr (T1 src0, T2 src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , int SZ>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_integral< T0 >::value &&std::is_integral< T1 >::value, simd< T0, SZ > >::type esimd_rol (simd< T1, SZ > src0, simd< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< U >::value, simd< T0, SZ > >::type esimd_rol (simd< T1, SZ > src0, U src1)
template<typename T0 , typename T1 , typename T2 >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value &&detail::is_esimd_scalar< T2 >::value &&std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< T2 >::value, typename std::remove_const< T0 >::type >::type esimd_rol (T1 src0, T2 src1)
template<typename T0 , typename T1 , int SZ>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_integral< T0 >::value &&std::is_integral< T1 >::value, simd< T0, SZ > >::type esimd_ror (simd< T1, SZ > src0, simd< T1, SZ > src1)
template<typename T0 , typename T1 , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< U >::value, simd< T0, SZ > >::type esimd_ror (simd< T1, SZ > src0, U src1)
template<typename T0 , typename T1 , typename T2 >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value &&detail::is_esimd_scalar< T2 >::value &&std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< T2 >::value, typename std::remove_const< T0 >::type >::type esimd_ror (T1 src0, T2 src1)
template<typename T0 , typename T1 , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< U >::value, simd< T0, SZ > >::type esimd_lsr (simd< T1, SZ > src0, U src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , typename T2 >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value &&detail::is_esimd_scalar< T2 >::value &&std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< T2 >::value, typename std::remove_const< T0 >::type >::type esimd_lsr (T1 src0, T2 src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , typename T2 >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T1 >::value &&detail::is_esimd_vector< T2 >::value &&std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< T2 >::value, decltype(esimd_lsr< T0 >T2(), T1()))>::type esimd_lsr (T1 src0, T2 src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< U >::value, simd< T0, SZ > >::type esimd_asr (simd< T1, SZ > src0, U src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , typename T2 >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value &&detail::is_esimd_scalar< T2 >::value &&std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< T2 >::value, typename std::remove_const< T0 >::type >::type esimd_asr (T1 src0, T2 src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , typename T2 >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T1 >::value &&detail::is_esimd_vector< T2 >::value &&std::is_integral< T0 >::value &&std::is_integral< T1 >::value &&std::is_integral< T2 >::value, decltype(esimd_asr< T0 >T2(), T1()))>::type esimd_asr (T1 src0, T2 src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , typename U , int SZ>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_dword_type< T0 >::value &&detail::is_dword_type< T1 >::value &&detail::is_dword_type< U >::value, simd< T0, SZ > >::type esimd_imul (simd< T0, SZ > &rmd, simd< T1, SZ > src0, U src1)
template<typename T0 , typename T1 , typename U , int SZ>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< U >::value, simd< T0, SZ > >::type esimd_imul (simd< T0, SZ > &rmd, U src0, simd< T1, SZ > src1)
template<typename T0 , typename T , typename U >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T >::value &&detail::is_esimd_scalar< U >::value &&detail::is_esimd_scalar< T0 >::value, T0 >::type esimd_imul (simd< T0, 1 > &rmd, T src0, U src1)
template<typename T , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_integral< T >::value &&std::is_integral< U >::value, simd< T, SZ > >::type esimd_quot (simd< T, SZ > src0, U src1)
template<typename T0 , typename T1 >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value &&std::is_integral< T0 >::value &&std::is_integral< T1 >::value, typename std::remove_const< T0 >::type >::type esimd_quot (T0 src0, T1 src1)
template<typename T , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_integral< T >::value &&std::is_integral< U >::value, simd< T, SZ > >::type esimd_mod (simd< T, SZ > src0, U src1)
template<typename T0 , typename T1 >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value &&std::is_integral< T0 >::value &&std::is_integral< T1 >::value, typename std::remove_const< T0 >::type >::type esimd_mod (T0 src0, T1 src1)
template<typename T , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_integral< T >::value &&std::is_integral< U >::value, simd< T, SZ > >::type esimd_div (simd< T, SZ > &remainder, simd< T, SZ > src0, U src1)
template<typename T , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_integral< T >::value &&std::is_integral< U >::value &&detail::is_esimd_scalar< U >::value, simd< T, SZ > >::type esimd_div (simd< T, SZ > &remainder, U src0, simd< T, SZ > src1)
template<typename RT , typename T0 , typename T1 >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< RT >::value &&detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value, typename std::remove_const< RT >::type >::type esimd_div (simd< typename std::remove_const< RT >::type, 1 > &remainder, T0 src0, T1 src1)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE simd< T, SZ > esimd_max (simd< T, SZ > src0, simd< T, SZ > src1, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T >::value, simd< T, SZ > >::type esimd_max (simd< T, SZ > src0, T src1, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T >::value, simd< T, SZ > >::type esimd_max (T src0, simd< T, SZ > src1, int flag=GENX_NOSAT)
template<typename T >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T >::value, T >::type esimd_max (T src0, T src1, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE simd< T, SZ > esimd_min (simd< T, SZ > src0, simd< T, SZ > src1, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T >::value, simd< T, SZ > >::type esimd_min (simd< T, SZ > src0, T src1, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T >::value, simd< T, SZ > >::type esimd_min (T src0, simd< T, SZ > src1, int flag=GENX_NOSAT)
template<typename T >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T >::value, T >::type esimd_min (T src0, T src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_fp_or_dword_type< T1 >::value &&std::is_floating_point< T1 >::value &&detail::is_fp_or_dword_type< U >::value &&std::is_floating_point< U >::value, simd< T0, SZ > >::type esimd_dp2 (simd< T1, SZ > src0, U src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_fp_or_dword_type< T1 >::value &&std::is_floating_point< T1 >::value &&detail::is_fp_or_dword_type< U >::value &&std::is_floating_point< U >::value, simd< T0, SZ > >::type esimd_dp3 (simd< T1, SZ > src0, U src1, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_fp_or_dword_type< T1 >::value &&std::is_floating_point< T1 >::value &&detail::is_fp_or_dword_type< U >::value &&std::is_floating_point< U >::value, simd< T0, SZ > >::type esimd_dp4 (simd< T1, SZ > src0, U src1, int flag=GENX_NOSAT)
template<typename T , typename U , int SZ>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_fp_or_dword_type< T >::value &&std::is_floating_point< T >::value &&detail::is_fp_or_dword_type< U >::value &&std::is_floating_point< U >::value, simd< T, SZ > >::type esimd_dph (simd< T, SZ > src0, U src1, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_fp_or_dword_type< T >::value &&std::is_floating_point< T >::value, simd< T, SZ > >::type esimd_line (simd< T, 4 > src0, simd< T, SZ > src1, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_fp_or_dword_type< T >::value &&std::is_floating_point< T >::value, simd< T, SZ > >::type esimd_line (float P, float Q, simd< T, SZ > src1, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE simd< T, SZ > esimd_frc (simd< T, SZ > src0)
template<typename T >
ESIMD_NODEBUG ESIMD_INLINE T esimd_frc (T src0)
template<typename RT , typename T0 , int SZ>
ESIMD_NODEBUG ESIMD_INLINE simd< RT, SZ > esimd_lzd (simd< T0, SZ > src0, int flag=GENX_NOSAT)
template<typename RT , typename T0 >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< RT >::value &&detail::is_esimd_scalar< T0 >::value, typename std::remove_const< RT >::type >::type esimd_lzd (T0 src0, int flag=GENX_NOSAT)
template<typename T , int SZ, typename U , typename V >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_fp_or_dword_type< T >::value &&std::is_floating_point< T >::value &&detail::is_fp_or_dword_type< U >::value &&std::is_floating_point< U >::value, simd< T, SZ > >::type esimd_lrp (simd< T, SZ > src0, U src1, V src2, int flag=GENX_NOSAT)
template<int SZ>
ESIMD_NODEBUG ESIMD_INLINE simd< float, SZ > esimd_pln (simd< float, 4 > src0, simd< float, SZ > src1, simd< float, SZ > src2, int flag=GENX_NOSAT)
template<typename T0 , typename T1 , int SZ>
ESIMD_NODEBUG ESIMD_INLINE simd< T0, SZ > esimd_bf_reverse (simd< T1, SZ > src0)
template<typename T0 , typename T1 >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T1 >::value, typename std::remove_const< T0 >::type >::type esimd_bf_reverse (T1 src0)
template<typename T0 , typename T1 , int SZ, typename U , typename V , typename W >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_integral< T1 >::value, simd< T0, SZ > >::type esimd_bf_insert (U src0, V src1, W src2, simd< T1, SZ > src3)
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T4 >::value, typename std::remove_const< T0 >::type >::type esimd_bf_insert (T1 src0, T2 src1, T3 src2, T4 src3)
template<typename T0 , typename T1 , int SZ, typename U , typename V >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_integral< T1 >::value, simd< T0, SZ > >::type esimd_bf_extract (U src0, V src1, simd< T1, SZ > src2)
template<typename T0 , typename T1 , typename T2 , typename T3 >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar< T0 >::value &&detail::is_esimd_scalar< T3 >::value, typename std::remove_const< T0 >::type >::type esimd_bf_extract (T1 src0, T2 src1, T3 src2)
template<int SZ, typename U >
ESIMD_NODEBUG ESIMD_INLINE simd< float, SZ > esimd_sincos (simd< float, SZ > &dstcos, U src0, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_floating_point< T >::value, simd< T, SZ > >::type esimd_atan (simd< T, SZ > src0, int flag=GENX_NOSAT)
template<typename T >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_floating_point< T >::value, T >::type esimd_atan (T src0, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_floating_point< T >::value, simd< T, SZ > >::type esimd_acos (simd< T, SZ > src0, int flag=GENX_NOSAT)
template<typename T >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_floating_point< T >::value, T >::type esimd_acos (T src0, int flag=GENX_NOSAT)
template<typename T , int SZ>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_floating_point< T >::value, simd< T, SZ > >::type esimd_asin (simd< T, SZ > src0, int flag=GENX_NOSAT)
template<typename T >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_floating_point< T >::value, T >::type esimd_asin (T src0, int flag=GENX_NOSAT)
template<int N>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if<(N==8||N==16||N==32), uint >::type esimd_pack_mask (simd< ushort, N > src0)
template<int N>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if<(N==8||N==16||N==32), simd< ushort, N > >::type esimd_unpack_mask (uint src0)
template<int N>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if<(N !=8 &&N !=16 &&N< 32), uint >::type esimd_pack_mask (simd< ushort, N > src0)
template<typename T , int N>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_integral< T >::value, simd< uint, N > >::type esimd_cbit (simd< T, N > src0)
Count component-wise the total bits set in source operand.
template<typename T >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_integral< T >::value &&detail::is_esimd_scalar< T >::value, uint >::type esimd_cbit (T src)
template<int N>
ESIMD_NODEBUG ESIMD_INLINE simd< unsigned, N > esimd_fbl (simd< unsigned, N > src)
Find component-wise the first bit from LSB side.
template<typename T = void>
ESIMD_NODEBUG ESIMD_INLINE unsigned esimd_fbl (unsigned src)
template<int N>
ESIMD_NODEBUG ESIMD_INLINE simd< int, N > esimd_fbh (simd< int, N > src)
Find component-wise the first bit from MSB side.
template<int N>
ESIMD_NODEBUG ESIMD_INLINE simd< unsigned int, N > esimd_fbh (simd< unsigned int, N > src)
template<typename T >
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_dword_type< T >::value &&detail::is_esimd_scalar< T >::value, T >::type esimd_fbh (T src)
template<typename T = void>
simd< uint, 4 > esimd_rdtsc ()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_dword_type< T1 >::value &&detail::is_dword_type< T2 >::value &&detail::is_dword_type< T3 >::value &&detail::is_dword_type< T4 >::value, simd< T1, N > >::type esimd_dp4a (simd< T2, N > src0, simd< T3, N > src1, simd< T4, N > src2, int flag=GENX_NOSAT)
template<typename RT , int SZ>
ESIMD_INLINE simd< RT, SZ > esimd_floor (const simd< float, SZ > src0, const uint flags=0)
template<typename RT >
ESIMD_INLINE RT esimd_floor (const float &src0, const uint flags=0)
template<typename RT , int SZ>
ESIMD_INLINE simd< RT, SZ > esimd_ceil (const simd< float, SZ > src0, const uint flags=0)
template<typename RT >
ESIMD_INLINE RT esimd_ceil (const float &src0, const uint flags=0)
template<int N>
simd< float, N > esimd_atan2_fast (simd< float, N > y, simd< float, N > x, const uint flags=0)
template<typename T >
float esimd_atan2_fast (T y, T x, const uint flags=0)
template<int N>
simd< float, N > esimd_atan2 (simd< float, N > y, simd< float, N > x, const uint flags=0)
template<typename T >
float esimd_atan2 (T y, T x, const uint flags=0)
template<int N>
simd< float, N > esimd_fmod (simd< float, N > y, simd< float, N > x, const uint flags=0)
template<typename T >
float esimd_fmod (T y, T x, const uint flags=0)
template<int N>
simd< float, N > esimd_sin_emu (simd< float, N > x, const uint flags=0)
template<typename T >
float esimd_sin_emu (T x, const uint flags=0)
template<int N>
simd< float, N > esimd_cos_emu (simd< float, N > x, const uint flags=0)
template<typename T >
float esimd_cos_emu (T x, const uint flags=0)
float esimd_tanh_cody_waite (float x)
template<int N>
simd< float, N > esimd_tanh_cody_waite (simd< float, N > x)
float esimd_tanh (float x)
template<int N>
simd< float, N > esimd_tanh (simd< float, N > x)
template<int N>
ESIMD_INLINE simd< float, N > esimd_atan2_fast (simd< float, N > y, simd< float, N > x, const uint flags)
template<>
ESIMD_INLINE float esimd_atan2_fast (float y, float x, const uint flags)
template<int N>
ESIMD_INLINE simd< float, N > esimd_atan2 (simd< float, N > y, simd< float, N > x, const uint flags)
template<>
ESIMD_INLINE float esimd_atan2 (float y, float x, const uint flags)
template<int N>
ESIMD_INLINE simd< float, N > esimd_fmod (simd< float, N > y, simd< float, N > x, const uint flags)
template<>
ESIMD_INLINE float esimd_fmod (float y, float x, const uint flags)
template<int N>
ESIMD_INLINE simd< float, N > esimd_sin_emu (simd< float, N > x, const uint flags)
template<typename T >
ESIMD_INLINE float esimd_sin_emu (T x0, const uint flags)
template<int N>
ESIMD_INLINE simd< float, N > esimd_cos_emu (simd< float, N > x, const uint flags)
template<typename T >
ESIMD_INLINE float esimd_cos_emu (T x0, const uint flags)
template<int N>
ESIMD_INLINE simd< float, N > esimd_tanh_cody_waite (simd< float, N > x)
template<int N>
ESIMD_INLINE simd< float, N > esimd_tanh (simd< float, N > x)
template<typename T0 , typename T1 , int SZ>
ESIMD_INLINE ESIMD_NODEBUG T0 hmax (simd< T1, SZ > v)
template<typename T0 , typename T1 , int SZ>
ESIMD_INLINE ESIMD_NODEBUG T0 hmin (simd< T1, SZ > v)
template<typename T0 , typename T1 , int SZ, typename BinaryOperation >
ESIMD_INLINE ESIMD_NODEBUG T0 reduce (simd< T1, SZ > v, BinaryOperation op)
template<typename T , int N>
simd< T, N > esimd_dp4 (simd< T, N > v1, simd< T, N > v2)
template<int ElemsPerAddr, typename = std::enable_if_t<(ElemsPerAddr == 1 || ElemsPerAddr == 2 || ElemsPerAddr == 4)>>
constexpr unsigned int ElemsPerAddrEncoding ()
template<typename T , int n, int ElemsPerAddr = 1, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG std::enable_if<((n==8||n==16||n==32) &&(ElemsPerAddr==1||ElemsPerAddr==2||ElemsPerAddr==4)), simd< T, n *ElemsPerAddr > >::type gather (T *p, simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
flat-address gather
template<typename T , int n, int ElemsPerAddr = 1, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG std::enable_if<((n==8||n==16||n==32) &&(ElemsPerAddr==1||ElemsPerAddr==2||ElemsPerAddr==4)), void >::type scatter (T *p, simd< T, n *ElemsPerAddr > vals, simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
flat-address scatter
template<typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG simd< T, n > block_load (const T *const addr)
flat-address block-load
template<typename T , int n, typename AccessorTy >
ESIMD_INLINE ESIMD_NODEBUG simd< T, n > block_load (AccessorTy acc, uint32_t offset)
accessor-based block-load
template<typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG void block_store (T *p, simd< T, n > vals)
flat-address block-store
template<typename T , int n, typename AccessorTy >
ESIMD_INLINE ESIMD_NODEBUG void block_store (AccessorTy acc, uint32_t offset, simd< T, n > vals)
accessor-based block-store
template<typename T , int N, typename AccessorTy , CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG std::enable_if<(sizeof(T)<=4) &&(N==1||N==8||N==16) &&!std::is_pointer< AccessorTy >::value, simd< T, N > >::type gather (AccessorTy acc, simd< uint32_t, N > offsets, uint32_t glob_offset=0)
Accessor-based gather.
template<typename T , int N, typename AccessorTy , CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG std::enable_if<(sizeof(T)<=4) &&(N==1||N==8||N==16) &&!std::is_pointer< AccessorTy >::value, void >::type scatter (AccessorTy acc, simd< T, N > vals, simd< uint32_t, N > offsets, uint32_t glob_offset=0, simd< uint16_t, N > pred=1)
Accessor-based scatter.
template<typename T , typename AccessorTy , CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG T scalar_load (AccessorTy acc, uint32_t offset)
Load a scalar value from an accessor.
template<typename T , typename AccessorTy , CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG void scalar_store (AccessorTy acc, uint32_t offset, T val)
Store a scalar value into an accessor.
template<typename T , int n, ChannelMaskType Mask, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG std::enable_if<(n==16||n==32) &&(sizeof(T)==4), simd< T, n *NumChannels(Mask)> >::type gather4 (T *p, simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
flat-address gather4 only allow simd-16 and simd-32
template<typename T , int n, ChannelMaskType Mask, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_INLINE ESIMD_NODEBUG std::enable_if<(n==16||n==32) &&(sizeof(T)==4), void >::type scatter4 (T *p, simd< T, n *NumChannels(Mask)> vals, simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
flat-address scatter4
template<EsimdAtomicOpType Op, typename T , int N, unsigned NumSrc>
constexpr bool check_atomic ()
check the legality of an atomic call in terms of size and type
template<EsimdAtomicOpType Op, typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< check_atomic< Op, T, n, 0 >), simd< T, n > >::type flat_atomic (T *p, simd< unsigned, n > offset, simd< ushort, n > pred)
flat-address atomic, zero source operand: inc and dec
template<EsimdAtomicOpType Op, typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< check_atomic< Op, T, n, 1 >), simd< T, n > >::type flat_atomic (T *p, simd< unsigned, n > offset, simd< T, n > src0, simd< ushort, n > pred)
flat-address atomic, one source operand, add/sub/min/max etc
template<EsimdAtomicOpType Op, typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< check_atomic< Op, T, n, 2 >), simd< T, n > >::type flat_atomic (T *p, simd< unsigned, n > offset, simd< T, n > src0, simd< T, n > src1, simd< ushort, n > pred)
flat-address atomic, two source operands
ESIMD_NODEBUG void esimd_barrier ()
generic work-group barrier
ESIMD_INLINE ESIMD_NODEBUG void esimd_fence (uint8_t cntl)
esimd_fence sets the memory read/write order
SYCL_EXTERNAL void slm_init (uint32_t size)
SLM functions.
template<typename T , int n>
ESIMD_INLINE ESIMD_NODEBUG std::enable_if<(n==16||n==32), simd< T, n > >::type slm_load (simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
SLM gather only allow simd-16 and simd-32.
template<typename T , int n>
ESIMD_INLINE ESIMD_NODEBUG std::enable_if<(n==16||n==32), void >::type slm_store (simd< T, n > vals, simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
SLM scatter.
template<typename T , int n, ChannelMaskType Mask>
ESIMD_INLINE ESIMD_NODEBUG std::enable_if<(n==8||n==16||n==32) &&(sizeof(T)==4), simd< T, n *NumChannels(Mask)> >::type slm_load4 (simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
SLM gather4 only allow simd-8, simd-16 and simd-32.
template<typename T , int n, ChannelMaskType Mask>
std::enable_if<(n==8||n==16||n==32) &&(sizeof(T)==4), void >::type slm_store4 (simd< T, n *NumChannels(Mask)> vals, simd< uint32_t, n > offsets, simd< uint16_t, n > pred=1)
SLM scatter4.
template<typename T , int n>
ESIMD_INLINE ESIMD_NODEBUG simd< T, n > slm_block_load (uint32_t offset)
SLM block-load.
template<typename T , int n>
ESIMD_INLINE ESIMD_NODEBUG void slm_block_store (uint32_t offset, simd< T, n > vals)
SLM block-store.
template<EsimdAtomicOpType Op, typename T , int n>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< check_atomic< Op, T, n, 0 >), simd< T, n > >::type slm_atomic (simd< uint32_t, n > offsets, simd< ushort, n > pred)
SLM atomic, zero source operand: inc and dec.
template<EsimdAtomicOpType Op, typename T , int n>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< check_atomic< Op, T, n, 1 >), simd< T, n > >::type slm_atomic (simd< uint32_t, n > offsets, simd< T, n > src0, simd< ushort, n > pred)
SLM atomic, one source operand, add/sub/min/max etc.
template<EsimdAtomicOpType Op, typename T , int n>
ESIMD_NODEBUG ESIMD_INLINE std::enable_if< check_atomic< Op, T, n, 2 >), simd< T, n > >::type slm_atomic (simd< uint32_t, n > offsets, simd< T, n > src0, simd< T, n > src1, simd< ushort, n > pred)
SLM atomic, two source operands.
template<typename T , int m, int n, typename AccessorTy , unsigned plane = 0>
ESIMD_INLINE ESIMD_NODEBUG simd< T, m *n > media_block_load (AccessorTy acc, unsigned x, unsigned y)
template<typename T , int m, int n, typename AccessorTy , unsigned plane = 0>
ESIMD_INLINE ESIMD_NODEBUG void media_block_store (AccessorTy acc, unsigned x, unsigned y, simd< T, m *n > vals)
Media block store.
template<typename AccessorTy >
ESIMD_INLINE ESIMD_NODEBUG uint32_t esimd_get_value (AccessorTy acc)
esimd_get_value
template<typename T1 , int n1, typename T2 , int n2, typename T3 , int n3, int N = 16>
ESIMD_INLINE ESIMD_NODEBUG simd< T1, n1 > esimd_raw_sends_load (simd< T1, n1 > msgDst, simd< T2, n2 > msgSrc0, simd< T3, n3 > msgSrc1, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numSrc1, uint8_t numDst, uint8_t isEOT=0, uint8_t isSendc=0, simd< uint16_t, N > mask=1)
Raw send APIs below are used to implement the send messages on Intel(R) processor graphics, as defined in the documentation at https://01.org/sites/default/files/documentation/intel-gfx-prm-osrc-icllp-vol02a-commandreference-instructions_2.pdf.
template<typename T1 , int n1, typename T2 , int n2, int N = 16>
ESIMD_INLINE ESIMD_NODEBUG simd< T1, n1 > esimd_raw_send_load (simd< T1, n1 > msgDst, simd< T2, n2 > msgSrc0, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numDst, uint8_t isEOT=0, uint8_t isSendc=0, simd< uint16_t, N > mask=1)
Raw send load.
template<typename T1 , int n1, typename T2 , int n2, int N = 16>
ESIMD_INLINE ESIMD_NODEBUG void esimd_raw_sends_store (simd< T1, n1 > msgSrc0, simd< T2, n2 > msgSrc1, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numSrc1, uint8_t isEOT=0, uint8_t isSendc=0, simd< uint16_t, N > mask=1)
Raw sends store.
template<typename T1 , int n1, int N = 16>
ESIMD_INLINE ESIMD_NODEBUG void esimd_raw_send_store (simd< T1, n1 > msgSrc0, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t isEOT=0, uint8_t isSendc=0, simd< uint16_t, N > mask=1)
Raw send store.
Variables
static auto constexpr ESIMD_CONST_E = 2.71828f
static auto constexpr ESIMD_CONST_PI = 3.14159f
static auto constexpr ESIMD_CONST_2PI = 6.28318f
static auto constexpr ESIMD_DBL_EPSILON = 0.00001f
static auto constexpr CMPI = 3.14159265f
Typedef Documentation
__esimd_void_t
template<class... Tys> using cl::sycl::INTEL::gpu::__esimd_void_t = typedef typename make_esimd_void<Tys...>::type
Definition at line 36 of file esimd_types.hpp.
compute_format_type_2d_t
template<typename Ty , typename EltTy , int Height, int Width> using cl::sycl::INTEL::gpu::compute_format_type_2d_t = typedef typename compute_format_type_2d<Ty, EltTy, Height, Width>::type
Definition at line 140 of file esimd_types.hpp.
compute_format_type_t
template<typename Ty , typename EltTy > using cl::sycl::INTEL::gpu::compute_format_type_t = typedef typename compute_format_type<Ty, EltTy>::type
Definition at line 105 of file esimd_types.hpp.
compute_type_t
template<typename T1 , typename T2 = T1> using cl::sycl::INTEL::gpu::compute_type_t = typedef typename common_type<remove_cvref_t<T1>, remove_cvref_t<T2> >::type
Definition at line 195 of file esimd_types.hpp.
half
using cl::sycl::INTEL::gpu::half = typedef cl::sycl::detail::half_impl::StorageT
Definition at line 28 of file esimd_types.hpp.
mask_type_t
template<int N> using cl::sycl::INTEL::gpu::mask_type_t = typedef typename vector_type<uint16_t, N>::type
Definition at line 80 of file esimd_types.hpp.
region1d_t
template<typename T , int Size, int Stride> using cl::sycl::INTEL::gpu::region1d_t = typedef region_base<false, T, 1, 0, Size, Stride>
Definition at line 51 of file esimd_region.hpp.
region2d_t
template<typename T , int SizeY, int StrideY, int SizeX, int StrideX> using cl::sycl::INTEL::gpu::region2d_t = typedef region_base<true, T, SizeY, StrideY, SizeX, StrideX>
Definition at line 55 of file esimd_region.hpp.
remove_cvref_t
template<typename T > using cl::sycl::INTEL::gpu::remove_cvref_t = typedef csd::remove_cv_t<csd::remove_reference_t<T> >
Definition at line 31 of file esimd_types.hpp.
uchar
using cl::sycl::INTEL::gpu::uchar = typedef unsigned char
Definition at line 21 of file esimd_enum.hpp.
uint
using cl::sycl::INTEL::gpu::uint = typedef unsigned int
Definition at line 23 of file esimd_enum.hpp.
ushort
using cl::sycl::INTEL::gpu::ushort = typedef unsigned short
Definition at line 22 of file esimd_enum.hpp.
vector_type_t
template<typename Ty , int N> using cl::sycl::INTEL::gpu::vector_type_t = typedef typename vector_type<Ty, N>::type
Definition at line 70 of file esimd_types.hpp.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
GENX_NOSAT
GENX_SAT
Definition at line 49 of file esimd_enum.hpp.
CacheHint
enum cl::sycl::INTEL::gpu::CacheHint : uint8_t strong
Enumerator
None
Uncached
WriteBack
WriteThrough
Streaming
ReadInvalidate
Definition at line 98 of file esimd_enum.hpp.
ChannelMaskType
enum cl::sycl::INTEL::gpu::ChannelMaskType
Enumerator
ESIMD_R_ENABLE
ESIMD_G_ENABLE
ESIMD_GR_ENABLE
ESIMD_B_ENABLE
ESIMD_BR_ENABLE
ESIMD_BG_ENABLE
ESIMD_BGR_ENABLE
ESIMD_A_ENABLE
ESIMD_AR_ENABLE
ESIMD_AG_ENABLE
ESIMD_AGR_ENABLE
ESIMD_AB_ENABLE
ESIMD_ABR_ENABLE
ESIMD_ABG_ENABLE
ESIMD_ABGR_ENABLE
Definition at line 51 of file esimd_enum.hpp.
EsimdAtomicOpType
enum cl::sycl::INTEL::gpu::EsimdAtomicOpType : uint16_t strong
Enumerator
ATOMIC_ADD
ATOMIC_SUB
ATOMIC_INC
ATOMIC_DEC
ATOMIC_MIN
ATOMIC_MAX
ATOMIC_XCHG
ATOMIC_CMPXCHG
ATOMIC_AND
ATOMIC_OR
ATOMIC_XOR
ATOMIC_MINSINT
ATOMIC_MAXSINT
ATOMIC_FMAX
ATOMIC_FMIN
ATOMIC_FCMPWR
ATOMIC_PREDEC
Definition at line 77 of file esimd_enum.hpp.
EsimdFenceMask
enum cl::sycl::INTEL::gpu::EsimdFenceMask
Enumerator
ESIMD_GLOBAL_COHERENT_FENCE
ESIMD_L3_FLUSH_INSTRUCTIONS
ESIMD_L3_FLUSH_TEXTURE_DATA
ESIMD_L3_FLUSH_CONSTANT_DATA
ESIMD_L3_FLUSH_RW_DATA
ESIMD_LOCAL_BARRIER
ESIMD_L1_FLUASH_RO_DATA
ESIMD_SW_BARRIER
Definition at line 572 of file esimd_memory.hpp.
Function Documentation
bitcast()
template<typename ToEltTy , typename FromEltTy , int FromN, typename = csd::enable_if_t<is_vectorizable<ToEltTy>::value>> ESIMD_INLINE std::conditional< std::is_same<FromEltTy, ToEltTy>::value, vector_type_t<FromEltTy, FromN>, vector_type_t<ToEltTy, bitcast_helper<ToEltTy, FromEltTy, FromN>::nToElems()> >::type cl::sycl::INTEL::gpu::bitcast (vector_type_t< FromEltTy, FromN > Val)
Definition at line 235 of file esimd_types.hpp.
block_load() [1/2]
template<typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_INLINE ESIMD_NODEBUG simd<T, n> cl::sycl::INTEL::gpu::block_load (const T *const addr)
flat-address block-load
Definition at line 174 of file esimd_memory.hpp.
References __esimd::isPowerOf2(), and __esimd::OWORD.
block_load() [2/2]
template<typename T , int n, typename AccessorTy > ESIMD_INLINE ESIMD_NODEBUG simd<T, n> cl::sycl::INTEL::gpu::block_load (AccessorTy acc, uint32_t offset)
accessor-based block-load
Definition at line 190 of file esimd_memory.hpp.
References __esimd::isPowerOf2(), and __esimd::OWORD.
block_store() [1/2]
template<typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::INTEL::gpu::block_store (T * p, simd< T, n > vals)
flat-address block-store
Definition at line 212 of file esimd_memory.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), __esimd::isPowerOf2(), and __esimd::OWORD.
block_store() [2/2]
template<typename T , int n, typename AccessorTy > ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::INTEL::gpu::block_store (AccessorTy acc, uint32_t offset, simd< T, n > vals)
accessor-based block-store
Definition at line 228 of file esimd_memory.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, ESIMD_NODEBUG, __esimd::isPowerOf2(), and __esimd::OWORD.
check_atomic()
template<EsimdAtomicOpType Op, typename T , int N, unsigned NumSrc> constexpr bool cl::sycl::INTEL::gpu::check_atomic ()
check the legality of an atomic call in terms of size and type
Definition at line 425 of file esimd_memory.hpp.
References ESIMD_INLINE, ESIMD_NODEBUG, and __esimd::isPowerOf2().
convert() [1/2]
template<typename To , typename From > To cl::sycl::INTEL::gpu::convert (From Val)
Definition at line 197 of file esimd_types.hpp.
convert() [2/2]
template<typename U , typename T , int n> ESIMD_INLINE simd<U, n> cl::sycl::INTEL::gpu::convert (simd< T, n > val)
Definition at line 442 of file esimd.hpp.
ElemsPerAddrDecoding()
constexpr unsigned int cl::sycl::INTEL::gpu::ElemsPerAddrDecoding (unsigned int ElemsPerAddrEncoded)
Definition at line 75 of file esimd_util.hpp.
Referenced by __esimd_flat_read(), __esimd_flat_write(), and __esimd_surf_write().
ElemsPerAddrEncoding()
template<int ElemsPerAddr, typename = std::enable_if_t<(ElemsPerAddr == 1 || ElemsPerAddr == 2 || ElemsPerAddr == 4)>> constexpr unsigned int cl::sycl::INTEL::gpu::ElemsPerAddrEncoding ()
Definition at line 29 of file esimd_memory.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_abs() [1/4]
template<typename T0 , typename T1 , int SZ> ESIMD_NODEBUG ESIMD_INLINE std::enable_if< !std::is_same<typename std::remove_const<T0>::type, typename std::remove_const<T1>::type>::value, simd<T0, SZ> >::type cl::sycl::INTEL::gpu::esimd_abs (simd< T1, SZ > src0, int flag = GENX_NOSAT)
Definition at line 80 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_abs() [2/4]
template<typename T0 , typename T1 > ESIMD_NODEBUG ESIMD_INLINE std::enable_if< !std::is_same<typename std::remove_const<T0>::type, typename std::remove_const<T1>::type>::value && detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value, typename std::remove_const<T0>::type>::type cl::sycl::INTEL::gpu::esimd_abs (T1 src0, int flag = GENX_NOSAT)
Definition at line 91 of file esimd_math.hpp.
esimd_abs() [3/4]
template<typename T1 , int SZ> ESIMD_NODEBUG ESIMD_INLINE simd<T1, SZ> cl::sycl::INTEL::gpu::esimd_abs (simd< T1, SZ > src0, int flag = GENX_NOSAT)
Definition at line 96 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_abs() [4/4]
template<typename T1 > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_esimd_scalar<T1>::value, typename std::remove_const<T1>::type>::type cl::sycl::INTEL::gpu::esimd_abs (T1 src0, int flag = GENX_NOSAT)
Definition at line 105 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
Referenced by esimd_acos(), esimd_asin(), esimd_atan(), cl::sycl::INTEL::gpu::detail::esimd_tanh_cody_waite_impl(), and cl::sycl::INTEL::gpu::detail::esimd_tanh_impl().
esimd_acos() [1/2]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<std::is_floating_point<T>::value, simd<T, SZ> >::type cl::sycl::INTEL::gpu::esimd_acos (simd< T, SZ > src0, int flag = GENX_NOSAT)
Definition at line 1153 of file esimd_math.hpp.
References esimd_abs(), ESIMD_HDR_CONST_PI, ESIMD_INLINE, ESIMD_NODEBUG, GENX_SAT, and cl::sycl::INTEL::gpu::simd< Ty, N >::merge().
esimd_acos() [2/2]
template<typename T > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<std::is_floating_point<T>::value, T>::type cl::sycl::INTEL::gpu::esimd_acos (T src0, int flag = GENX_NOSAT)
Definition at line 1186 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
Referenced by esimd_asin().
esimd_asin() [1/2]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<std::is_floating_point<T>::value, simd<T, SZ> >::type cl::sycl::INTEL::gpu::esimd_asin (simd< T, SZ > src0, int flag = GENX_NOSAT)
Definition at line 1197 of file esimd_math.hpp.
References esimd_abs(), esimd_acos(), ESIMD_HDR_CONST_PI, ESIMD_INLINE, ESIMD_NODEBUG, GENX_SAT, and cl::sycl::INTEL::gpu::simd< Ty, N >::merge().
esimd_asin() [2/2]
template<typename T > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<std::is_floating_point<T>::value, T>::type cl::sycl::INTEL::gpu::esimd_asin (T src0, int flag = GENX_NOSAT)
Definition at line 1214 of file esimd_math.hpp.
esimd_asr() [1/3]
template<typename T0 , typename T1 , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<U>::value, simd<T0, SZ> >::type cl::sycl::INTEL::gpu::esimd_asr (simd< T1, SZ > src0, U src1, int flag = GENX_NOSAT)
Definition at line 320 of file esimd_math.hpp.
References ESIMD_INLINE, ESIMD_NODEBUG, and GENX_SAT.
esimd_asr() [2/3]
template<typename T0 , typename T1 , typename T2 > ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value && detail::is_esimd_scalar<T2>::value && std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<T2>::value, typename std::remove_const<T0>::type>::type cl::sycl::INTEL::gpu::esimd_asr (T1 src0, T2 src1, int flag = GENX_NOSAT)
Definition at line 338 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_asr() [3/3]
template<typename T0 , typename T1 , typename T2 > ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar<T1>::value && detail::is_esimd_vector<T2>::value && std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<T2>::value, decltype(esimd_asr<T0>T2(), T1()))>::type cl::sycl::INTEL::gpu::esimd_asr (T1 src0, T2 src1, int flag = GENX_NOSAT)
Definition at line 352 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_atan() [1/2]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<std::is_floating_point<T>::value, simd<T, SZ> >::type cl::sycl::INTEL::gpu::esimd_atan (simd< T, SZ > src0, int flag = GENX_NOSAT)
Definition at line 1111 of file esimd_math.hpp.
References esimd_abs(), ESIMD_HDR_CONST_PI, ESIMD_INLINE, ESIMD_NODEBUG, GENX_SAT, and cl::sycl::INTEL::gpu::simd< Ty, N >::merge().
esimd_atan() [2/2]
template<typename T > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<std::is_floating_point<T>::value, T>::type cl::sycl::INTEL::gpu::esimd_atan (T src0, int flag = GENX_NOSAT)
Definition at line 1142 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
Referenced by esimd_atan2().
esimd_atan2() [1/4]
template<int N> simd<float, N> cl::sycl::INTEL::gpu::esimd_atan2 (simd< float, N > y, simd< float, N > x, const uint flags = 0)
Definition at line 1464 of file esimd_math.hpp.
References cl::sycl::atan2(), esimd_atan(), GENX_SAT, and cl::sycl::INTEL::gpu::simd< Ty, N >::merge().
esimd_atan2() [2/4]
template<typename T > float cl::sycl::INTEL::gpu::esimd_atan2 (T y, T x, const uint flags = 0)
esimd_atan2() [3/4]
template<int N> ESIMD_INLINE simd<float, N> cl::sycl::INTEL::gpu::esimd_atan2 (simd< float, N > y, simd< float, N > x, const uint flags)
Definition at line 1464 of file esimd_math.hpp.
References cl::sycl::atan2(), esimd_atan(), GENX_SAT, and cl::sycl::INTEL::gpu::simd< Ty, N >::merge().
esimd_atan2() [4/4]
template<> ESIMD_INLINE float cl::sycl::INTEL::gpu::esimd_atan2 (float y, float x, const uint flags)
Definition at line 1483 of file esimd_math.hpp.
References cl::sycl::atan2(), esimd_atan(), ESIMD_CONST_PI, GENX_SAT, and cl::sycl::INTEL::gpu::simd< Ty, N >::merge().
Referenced by esimd_ceil().
esimd_atan2_fast() [1/4]
template<int N> simd<float, N> cl::sycl::INTEL::gpu::esimd_atan2_fast (simd< float, N > y, simd< float, N > x, const uint flags = 0)
Definition at line 1427 of file esimd_math.hpp.
References cl::sycl::atan2(), ESIMD_DBL_EPSILON, GENX_SAT, and cl::sycl::INTEL::gpu::simd< Ty, N >::merge().
esimd_atan2_fast() [2/4]
template<typename T > float cl::sycl::INTEL::gpu::esimd_atan2_fast (T y, T x, const uint flags = 0)
esimd_atan2_fast() [3/4]
template<int N> ESIMD_INLINE simd<float, N> cl::sycl::INTEL::gpu::esimd_atan2_fast (simd< float, N > y, simd< float, N > x, const uint flags)
Definition at line 1427 of file esimd_math.hpp.
References cl::sycl::atan2(), ESIMD_DBL_EPSILON, GENX_SAT, and cl::sycl::INTEL::gpu::simd< Ty, N >::merge().
esimd_atan2_fast() [4/4]
template<> ESIMD_INLINE float cl::sycl::INTEL::gpu::esimd_atan2_fast (float y, float x, const uint flags)
Definition at line 1454 of file esimd_math.hpp.
References cl::sycl::atan2().
Referenced by esimd_ceil().
esimd_barrier()
ESIMD_NODEBUG void cl::sycl::INTEL::gpu::esimd_barrier () inline
generic work-group barrier
Definition at line 570 of file esimd_memory.hpp.
References __esimd_barrier().
esimd_bf_extract() [1/2]
template<typename T0 , typename T1 , int SZ, typename U , typename V > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<std::is_integral<T1>::value, simd<T0, SZ> >::type cl::sycl::INTEL::gpu::esimd_bf_extract (U src0, V src1, simd< T1, SZ > src2)
Definition at line 976 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_bf_extract() [2/2]
template<typename T0 , typename T1 , typename T2 , typename T3 > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T3>::value, typename std::remove_const<T0>::type>::type cl::sycl::INTEL::gpu::esimd_bf_extract (T1 src0, T2 src1, T3 src2)
Definition at line 992 of file esimd_math.hpp.
References cl::sycl::cos(), ESIMD_INLINE, ESIMD_INTRINSIC_DEF, ESIMD_NODEBUG, cl::sycl::exp(), cl::sycl::log(), cl::sycl::pow(), cl::sycl::rsqrt(), cl::sycl::sin(), and cl::sycl::sqrt().
esimd_bf_insert() [1/2]
template<typename T0 , typename T1 , int SZ, typename U , typename V , typename W > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<std::is_integral<T1>::value, simd<T0, SZ> >::type cl::sycl::INTEL::gpu::esimd_bf_insert (U src0, V src1, W src2, simd< T1, SZ > src3)
Definition at line 949 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_bf_insert() [2/2]
template<typename T0 , typename T1 , typename T2 , typename T3 , typename T4 > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T4>::value, typename std::remove_const<T0>::type>::type cl::sycl::INTEL::gpu::esimd_bf_insert (T1 src0, T2 src1, T3 src2, T4 src3)
Definition at line 966 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_bf_reverse() [1/2]
template<typename T0 , typename T1 , int SZ> ESIMD_NODEBUG ESIMD_INLINE simd<T0, SZ> cl::sycl::INTEL::gpu::esimd_bf_reverse (simd< T1, SZ > src0)
Definition at line 929 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_bf_reverse() [2/2]
template<typename T0 , typename T1 > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value, typename std::remove_const<T0>::type>::type cl::sycl::INTEL::gpu::esimd_bf_reverse (T1 src0)
Definition at line 939 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_cbit() [1/2]
template<typename T , int N> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<std::is_integral<T>::value, simd<uint, N> >::type cl::sycl::INTEL::gpu::esimd_cbit (simd< T, N > src0)
Count component-wise the total bits set in source operand.
Definition at line 1276 of file esimd_math.hpp.
References __esimd_cbit(), cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_cbit() [2/2]
template<typename T > ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_integral<T>::value && detail::is_esimd_scalar<T>::value, uint>::type cl::sycl::INTEL::gpu::esimd_cbit (T src)
Definition at line 1283 of file esimd_math.hpp.
esimd_ceil() [1/2]
template<typename RT , int SZ> ESIMD_INLINE simd<RT, SZ> cl::sycl::INTEL::gpu::esimd_ceil (const simd< float, SZ > src0, const uint flags = 0)
Definition at line 1362 of file esimd_math.hpp.
esimd_ceil() [2/2]
template<typename RT > ESIMD_INLINE RT cl::sycl::INTEL::gpu::esimd_ceil (const float & src0, const uint flags = 0)
Definition at line 1368 of file esimd_math.hpp.
References esimd_atan2(), esimd_atan2_fast(), esimd_cos_emu(), esimd_fmod(), esimd_sin_emu(), esimd_tanh(), and esimd_tanh_cody_waite().
esimd_cos_emu() [1/4]
template<int N> simd<float, N> cl::sycl::INTEL::gpu::esimd_cos_emu (simd< float, N > x, const uint flags = 0)
Definition at line 1611 of file esimd_math.hpp.
References esimd_fmod(), GENX_SAT, cl::sycl::INTEL::gpu::simd< Ty, N >::merge(), and cl::sycl::sign().
esimd_cos_emu() [2/4]
template<typename T > float cl::sycl::INTEL::gpu::esimd_cos_emu (T x, const uint flags = 0)
Definition at line 1648 of file esimd_math.hpp.
References esimd_fmod(), GENX_SAT, cl::sycl::INTEL::gpu::simd< Ty, N >::merge(), and cl::sycl::sign().
Referenced by esimd_ceil().
esimd_cos_emu() [3/4]
template<int N> ESIMD_INLINE simd<float, N> cl::sycl::INTEL::gpu::esimd_cos_emu (simd< float, N > x, const uint flags)
Definition at line 1611 of file esimd_math.hpp.
References esimd_fmod(), GENX_SAT, cl::sycl::INTEL::gpu::simd< Ty, N >::merge(), and cl::sycl::sign().
esimd_cos_emu() [4/4]
template<typename T > ESIMD_INLINE float cl::sycl::INTEL::gpu::esimd_cos_emu (T x0, const uint flags)
Definition at line 1648 of file esimd_math.hpp.
References esimd_fmod(), GENX_SAT, cl::sycl::INTEL::gpu::simd< Ty, N >::merge(), and cl::sycl::sign().
Referenced by esimd_ceil().
esimd_div() [1/3]
template<typename T , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_integral<T>::value && std::is_integral<U>::value, simd<T, SZ> >::type cl::sycl::INTEL::gpu::esimd_div (simd< T, SZ > & remainder, simd< T, SZ > src0, U src1)
Definition at line 472 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_div() [2/3]
template<typename T , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<std::is_integral<T>::value && std::is_integral<U>::value && detail::is_esimd_scalar<U>::value, simd<T, SZ> >::type cl::sycl::INTEL::gpu::esimd_div (simd< T, SZ > & remainder, U src0, simd< T, SZ > src1)
Definition at line 483 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_div() [3/3]
template<typename RT , typename T0 , typename T1 > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_esimd_scalar<RT>::value && detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value, typename std::remove_const<RT>::type>::type cl::sycl::INTEL::gpu::esimd_div (simd< typename std::remove_const< RT >::type, 1 > & remainder, T0 src0, T1 src1)
Definition at line 494 of file esimd_math.hpp.
References ESIMD_INLINE, ESIMD_NODEBUG, and cl::sycl::remainder().
esimd_dp2()
template<typename T0 , typename T1 , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_fp_or_dword_type<T1>::value && std::is_floating_point<T1>::value && detail::is_fp_or_dword_type<U>::value && std::is_floating_point<U>::value, simd<T0, SZ> >::type cl::sycl::INTEL::gpu::esimd_dp2 (simd< T1, SZ > src0, U src1, int flag = GENX_NOSAT)
Definition at line 698 of file esimd_math.hpp.
References ESIMD_INLINE, ESIMD_NODEBUG, GENX_SAT, and cl::sycl::INTEL::gpu::simd< Ty, N >::select().
Referenced by esimd_min().
esimd_dp3()
template<typename T0 , typename T1 , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_fp_or_dword_type<T1>::value && std::is_floating_point<T1>::value && detail::is_fp_or_dword_type<U>::value && std::is_floating_point<U>::value, simd<T0, SZ> >::type cl::sycl::INTEL::gpu::esimd_dp3 (simd< T1, SZ > src0, U src1, int flag = GENX_NOSAT)
Definition at line 720 of file esimd_math.hpp.
References ESIMD_INLINE, ESIMD_NODEBUG, GENX_SAT, and cl::sycl::INTEL::gpu::simd< Ty, N >::select().
Referenced by esimd_min().
esimd_dp4() [1/2]
template<typename T0 , typename T1 , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_fp_or_dword_type<T1>::value && std::is_floating_point<T1>::value && detail::is_fp_or_dword_type<U>::value && std::is_floating_point<U>::value, simd<T0, SZ> >::type cl::sycl::INTEL::gpu::esimd_dp4 (simd< T1, SZ > src0, U src1, int flag = GENX_NOSAT)
Definition at line 743 of file esimd_math.hpp.
References ESIMD_INLINE, ESIMD_NODEBUG, GENX_SAT, and cl::sycl::INTEL::gpu::simd< Ty, N >::select().
esimd_dp4() [2/2]
template<typename T , int N> simd<T, N> cl::sycl::INTEL::gpu::esimd_dp4 (simd< T, N > v1, simd< T, N > v2)
Definition at line 1930 of file esimd_math.hpp.
Referenced by esimd_min().
esimd_dp4a()
template<typename T1 , typename T2 , typename T3 , typename T4 , int N> ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_dword_type<T1>::value && detail::is_dword_type<T2>::value && detail::is_dword_type<T3>::value && detail::is_dword_type<T4>::value, simd<T1, N> >::type cl::sycl::INTEL::gpu::esimd_dp4a (simd< T2, N > src0, simd< T3, N > src1, simd< T4, N > src2, int flag = GENX_NOSAT)
Definition at line 1332 of file esimd_math.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), and GENX_SAT.
esimd_dph()
template<typename T , typename U , int SZ> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_fp_or_dword_type<T>::value && std::is_floating_point<T>::value && detail::is_fp_or_dword_type<U>::value && std::is_floating_point<U>::value, simd<T, SZ> >::type cl::sycl::INTEL::gpu::esimd_dph (simd< T, SZ > src0, U src1, int flag = GENX_NOSAT)
Definition at line 767 of file esimd_math.hpp.
References ESIMD_INLINE, ESIMD_NODEBUG, GENX_SAT, and cl::sycl::INTEL::gpu::simd< Ty, N >::select().
Referenced by esimd_min().
esimd_fbh() [1/3]
template<int N> ESIMD_NODEBUG ESIMD_INLINE simd<int, N> cl::sycl::INTEL::gpu::esimd_fbh (simd< int, N > src)
Find component-wise the first bit from MSB side.
Definition at line 1304 of file esimd_math.hpp.
References __esimd_sfbh(), cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_fbh() [2/3]
template<int N> ESIMD_NODEBUG ESIMD_INLINE simd<unsigned int, N> cl::sycl::INTEL::gpu::esimd_fbh (simd< unsigned int, N > src)
Definition at line 1310 of file esimd_math.hpp.
References __esimd_ufbh(), cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_fbh() [3/3]
template<typename T > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_dword_type<T>::value && detail::is_esimd_scalar<T>::value, T>::type cl::sycl::INTEL::gpu::esimd_fbh (T src)
Definition at line 1319 of file esimd_math.hpp.
References ESIMD_INLINE, ESIMD_NODEBUG, and esimd_rdtsc().
esimd_fbl() [1/2]
template<int N> ESIMD_NODEBUG ESIMD_INLINE simd<unsigned, N> cl::sycl::INTEL::gpu::esimd_fbl (simd< unsigned, N > src)
Find component-wise the first bit from LSB side.
Definition at line 1291 of file esimd_math.hpp.
References __esimd_fbl(), and cl::sycl::INTEL::gpu::simd< Ty, N >::data().
esimd_fbl() [2/2]
template<typename T = void> ESIMD_NODEBUG ESIMD_INLINE unsigned cl::sycl::INTEL::gpu::esimd_fbl (unsigned src)
Definition at line 1296 of file esimd_math.hpp.
esimd_fence()
ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::INTEL::gpu::esimd_fence (uint8_t cntl)
esimd_fence sets the memory read/write order
Definition at line 584 of file esimd_memory.hpp.
References __esimd_slm_fence(), ESIMD_INLINE, ESIMD_NODEBUG, slm_init(), SYCL_EXTERNAL, and cl::sycl::info::uint32_t.
esimd_floor() [1/2]
template<typename RT , int SZ> ESIMD_INLINE simd<RT, SZ> cl::sycl::INTEL::gpu::esimd_floor (const simd< float, SZ > src0, const uint flags = 0)
Definition at line 1351 of file esimd_math.hpp.
esimd_floor() [2/2]
template<typename RT > ESIMD_INLINE RT cl::sycl::INTEL::gpu::esimd_floor (const float & src0, const uint flags = 0)
Definition at line 1357 of file esimd_math.hpp.
esimd_fmod() [1/4]
template<int N> simd<float, N> cl::sycl::INTEL::gpu::esimd_fmod (simd< float, N > y, simd< float, N > x, const uint flags = 0)
Definition at line 1503 of file esimd_math.hpp.
References cl::sycl::fmod(), and GENX_SAT.
esimd_fmod() [2/4]
template<typename T > float cl::sycl::INTEL::gpu::esimd_fmod (T y, T x, const uint flags = 0)
esimd_fmod() [3/4]
template<int N> ESIMD_INLINE simd<float, N> cl::sycl::INTEL::gpu::esimd_fmod (simd< float, N > y, simd< float, N > x, const uint flags)
Definition at line 1503 of file esimd_math.hpp.
References cl::sycl::fmod(), and GENX_SAT.
esimd_fmod() [4/4]
template<> ESIMD_INLINE float cl::sycl::INTEL::gpu::esimd_fmod (float y, float x, const uint flags)
Definition at line 1517 of file esimd_math.hpp.
References cl::sycl::fmod(), and GENX_SAT.
Referenced by esimd_ceil(), esimd_cos_emu(), and esimd_sin_emu().
esimd_frc() [1/2]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE simd<T, SZ> cl::sycl::INTEL::gpu::esimd_frc (simd< T, SZ > src0)
Definition at line 818 of file esimd_math.hpp.
References __esimd_frc().
esimd_frc() [2/2]
template<typename T > ESIMD_NODEBUG ESIMD_INLINE T cl::sycl::INTEL::gpu::esimd_frc (T src0)
Definition at line 823 of file esimd_math.hpp.
esimd_get_value()
template<typename AccessorTy > ESIMD_INLINE ESIMD_NODEBUG uint32_t cl::sycl::INTEL::gpu::esimd_get_value (AccessorTy acc)
esimd_get_value
Parameters
acc the SYCL accessor.
Returns the binding table index value.
Definition at line 805 of file esimd_memory.hpp.
References __esimd_get_value(), ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_imul() [1/3]
template<typename T0 , typename T1 , typename U , int SZ> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_dword_type<T0>::value && detail::is_dword_type<T1>::value && detail::is_dword_type<U>::value, simd<T0, SZ> >::type cl::sycl::INTEL::gpu::esimd_imul (simd< T0, SZ > & rmd, simd< T1, SZ > src0, U src1)
Definition at line 365 of file esimd_math.hpp.
References __esimd_smulh(), __esimd_umulh(), cl::sycl::INTEL::gpu::simd< Ty, N >::data(), esimd_imul(), ESIMD_INLINE, ESIMD_NODEBUG, and cl::sycl::INTEL::gpu::simd< Ty, N >::format().
esimd_imul() [2/3]
template<typename T0 , typename T1 , typename U , int SZ> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_esimd_scalar<U>::value, simd<T0, SZ> >::type cl::sycl::INTEL::gpu::esimd_imul (simd< T0, SZ > & rmd, U src0, simd< T1, SZ > src1)
Definition at line 417 of file esimd_math.hpp.
References esimd_imul(), ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_imul() [3/3]
template<typename T0 , typename T , typename U > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_esimd_scalar<T>::value && detail::is_esimd_scalar<U>::value && detail::is_esimd_scalar<T0>::value, T0>::type cl::sycl::INTEL::gpu::esimd_imul (simd< T0, 1 > & rmd, T src0, U src1)
Definition at line 427 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
Referenced by esimd_imul().
esimd_line() [1/2]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_fp_or_dword_type<T>::value && std::is_floating_point<T>::value, simd<T, SZ> >::type cl::sycl::INTEL::gpu::esimd_line (simd< T, 4 > src0, simd< T, SZ > src1, int flag = GENX_NOSAT)
Definition at line 788 of file esimd_math.hpp.
References ESIMD_INLINE, ESIMD_NODEBUG, GENX_SAT, and cl::sycl::INTEL::gpu::simd< Ty, N >::select().
esimd_line() [2/2]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_fp_or_dword_type<T>::value && std::is_floating_point<T>::value, simd<T, SZ> >::type cl::sycl::INTEL::gpu::esimd_line (float P, float Q, simd< T, SZ > src1, int flag = GENX_NOSAT)
Definition at line 809 of file esimd_math.hpp.
References P.
Referenced by esimd_min().
esimd_lrp()
template<typename T , int SZ, typename U , typename V > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_fp_or_dword_type<T>::value && std::is_floating_point<T>::value && detail::is_fp_or_dword_type<U>::value && std::is_floating_point<U>::value, simd<T, SZ> >::type cl::sycl::INTEL::gpu::esimd_lrp (simd< T, SZ > src0, U src1, V src2, int flag = GENX_NOSAT)
Definition at line 886 of file esimd_math.hpp.
References ESIMD_INLINE, ESIMD_NODEBUG, and GENX_SAT.
Referenced by esimd_lzd().
esimd_lsr() [1/3]
template<typename T0 , typename T1 , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<U>::value, simd<T0, SZ> >::type cl::sycl::INTEL::gpu::esimd_lsr (simd< T1, SZ > src0, U src1, int flag = GENX_NOSAT)
Definition at line 277 of file esimd_math.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, ESIMD_NODEBUG, and GENX_SAT.
esimd_lsr() [2/3]
template<typename T0 , typename T1 , typename T2 > ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value && detail::is_esimd_scalar<T2>::value && std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<T2>::value, typename std::remove_const<T0>::type>::type cl::sycl::INTEL::gpu::esimd_lsr (T1 src0, T2 src1, int flag = GENX_NOSAT)
Definition at line 295 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_lsr() [3/3]
template<typename T0 , typename T1 , typename T2 > ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar<T1>::value && detail::is_esimd_vector<T2>::value && std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<T2>::value, decltype(esimd_lsr<T0>T2(), T1()))>::type cl::sycl::INTEL::gpu::esimd_lsr (T1 src0, T2 src1, int flag = GENX_NOSAT)
Definition at line 309 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_lzd() [1/2]
template<typename RT , typename T0 , int SZ> ESIMD_NODEBUG ESIMD_INLINE simd<RT, SZ> cl::sycl::INTEL::gpu::esimd_lzd (simd< T0, SZ > src0, int flag = GENX_NOSAT)
Definition at line 831 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_lzd() [2/2]
template<typename RT , typename T0 > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_esimd_scalar<RT>::value && detail::is_esimd_scalar<T0>::value, typename std::remove_const<RT>::type>::type cl::sycl::INTEL::gpu::esimd_lzd (T0 src0, int flag = GENX_NOSAT)
Definition at line 843 of file esimd_math.hpp.
References ESIMD_INLINE, esimd_lrp(), ESIMD_NODEBUG, GENX_NOSAT, and GENX_SAT.
esimd_max() [1/4]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE simd<T, SZ> cl::sycl::INTEL::gpu::esimd_max (simd< T, SZ > src0, simd< T, SZ > src1, int flag = GENX_NOSAT)
Definition at line 508 of file esimd_math.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, ESIMD_NODEBUG, and GENX_NOSAT.
esimd_max() [2/4]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_esimd_scalar<T>::value, simd<T, SZ> >::type cl::sycl::INTEL::gpu::esimd_max (simd< T, SZ > src0, T src1, int flag = GENX_NOSAT)
Definition at line 527 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_max() [3/4]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_esimd_scalar<T>::value, simd<T, SZ> >::type cl::sycl::INTEL::gpu::esimd_max (T src0, simd< T, SZ > src1, int flag = GENX_NOSAT)
Definition at line 537 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_max() [4/4]
template<typename T > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_esimd_scalar<T>::value, T>::type cl::sycl::INTEL::gpu::esimd_max (T src0, T src1, int flag = GENX_NOSAT)
Definition at line 546 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_min() [1/4]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE simd<T, SZ> cl::sycl::INTEL::gpu::esimd_min (simd< T, SZ > src0, simd< T, SZ > src1, int flag = GENX_NOSAT)
Definition at line 555 of file esimd_math.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, ESIMD_NODEBUG, and GENX_NOSAT.
esimd_min() [2/4]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_esimd_scalar<T>::value, simd<T, SZ> >::type cl::sycl::INTEL::gpu::esimd_min (simd< T, SZ > src0, T src1, int flag = GENX_NOSAT)
Definition at line 574 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_min() [3/4]
template<typename T , int SZ> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_esimd_scalar<T>::value, simd<T, SZ> >::type cl::sycl::INTEL::gpu::esimd_min (T src0, simd< T, SZ > src1, int flag = GENX_NOSAT)
Definition at line 584 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_min() [4/4]
template<typename T > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<detail::is_esimd_scalar<T>::value, T>::type cl::sycl::INTEL::gpu::esimd_min (T src0, T src1, int flag = GENX_NOSAT)
Definition at line 592 of file esimd_math.hpp.
References __esimd_dp4(), cl::sycl::INTEL::gpu::simd< Ty, N >::data(), esimd_dp2(), esimd_dp3(), esimd_dp4(), esimd_dph(), ESIMD_INLINE, esimd_line(), ESIMD_NODEBUG, GENX_NOSAT, GENX_SAT, and P.
esimd_mod() [1/2]
template<typename T , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_integral<T>::value && std::is_integral<U>::value, simd<T, SZ> >::type cl::sycl::INTEL::gpu::esimd_mod (simd< T, SZ > src0, U src1)
Definition at line 455 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_mod() [2/2]
template<typename T0 , typename T1 > ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value && std::is_integral<T0>::value && std::is_integral<T1>::value, typename std::remove_const<T0>::type>::type cl::sycl::INTEL::gpu::esimd_mod (T0 src0, T1 src1)
Definition at line 464 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_pack_mask() [1/2]
template<int N> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<(N == 8 || N == 16 || N == 32), uint>::type cl::sycl::INTEL::gpu::esimd_pack_mask (simd< ushort, N > src0)
Definition at line 1251 of file esimd_math.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_pack_mask() [2/2]
template<int N> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<(N != 8 && N != 16 && N < 32), uint>::type cl::sycl::INTEL::gpu::esimd_pack_mask (simd< ushort, N > src0)
Definition at line 1266 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_pln()
template<int SZ> ESIMD_NODEBUG ESIMD_INLINE simd<float, SZ> cl::sycl::INTEL::gpu::esimd_pln (simd< float, 4 > src0, simd< float, SZ > src1, simd< float, SZ > src2, int flag = GENX_NOSAT)
Definition at line 901 of file esimd_math.hpp.
References GENX_SAT, cl::sycl::INTEL::gpu::simd< Ty, N >::read(), and cl::sycl::INTEL::gpu::simd< Ty, N >::select().
esimd_quot() [1/2]
template<typename T , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE std::enable_if< std::is_integral<T>::value && std::is_integral<U>::value, simd<T, SZ> >::type cl::sycl::INTEL::gpu::esimd_quot (simd< T, SZ > src0, U src1)
Definition at line 438 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_quot() [2/2]
template<typename T0 , typename T1 > ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value && std::is_integral<T0>::value && std::is_integral<T1>::value, typename std::remove_const<T0>::type>::type cl::sycl::INTEL::gpu::esimd_quot (T0 src0, T1 src1)
Definition at line 447 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_raw_send_load()
template<typename T1 , int n1, typename T2 , int n2, int N = 16> ESIMD_INLINE ESIMD_NODEBUG simd<T1, n1> cl::sycl::INTEL::gpu::esimd_raw_send_load (simd< T1, n1 > msgDst, simd< T2, n2 > msgSrc0, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numDst, uint8_t isEOT = 0, uint8_t isSendc = 0, simd< uint16_t, N > mask = 1)
Raw send load.
Parameters
msgDst the old value of the destination operand.
msgSrc0 the first source operand of send message.
exDesc the extended message descriptor.
msgDesc the message descriptor.
execSize the execution size, which must be a compile time constant.
sfid the shared function ID, which must be a compile time constant.
numSrc0 the number of GRFs for source-0, which must be a compile time constant.
numDst the number of GRFs for destination, which must be a compile time constant.
isEOT the flag that indicates whether this is an EOT message, which must be a compile time constant (optional - default to 0).
isSendc the flag that indicates whether sendc should be used, which must be a compile time constant (optional - default to 0).
mask the predicate to specify enabled channels (optional - default to on).
Returns the vector value read from memory.
Definition at line 908 of file esimd_memory.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_raw_send_store()
template<typename T1 , int n1, int N = 16> ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::INTEL::gpu::esimd_raw_send_store (simd< T1, n1 > msgSrc0, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t isEOT = 0, uint8_t isSendc = 0, simd< uint16_t, N > mask = 1)
Raw send store.
Parameters
msgSrc0 the first source operand of send message.
exDesc the extended message descriptor.
msgDesc the message descriptor.
execSize the execution size, which must be a compile time constant.
sfid the shared function ID, which must be a compile time constant.
numSrc0 the number of GRFs for source-0, which must be a compile time constant.
isEOT the flag that indicates whether this is an EOT message, which must be a compile time constant (optional - default to 0).
isSendc the flag that indicates whether sendc should be used, which must be a compile time constant (optional - default to 0).
mask the predicate to specify enabled channels (optional - default to on).
Definition at line 996 of file esimd_memory.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data().
esimd_raw_sends_load()
template<typename T1 , int n1, typename T2 , int n2, typename T3 , int n3, int N = 16> ESIMD_INLINE ESIMD_NODEBUG simd<T1, n1> cl::sycl::INTEL::gpu::esimd_raw_sends_load (simd< T1, n1 > msgDst, simd< T2, n2 > msgSrc0, simd< T3, n3 > msgSrc1, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numSrc1, uint8_t numDst, uint8_t isEOT = 0, uint8_t isSendc = 0, simd< uint16_t, N > mask = 1)
Raw send APIs below are used to implement the send messages on Intel(R) processor graphics, as defined in the documentation at https://01.org/sites/default/files/documentation/intel-gfx-prm-osrc-icllp-vol02a-commandreference-instructions_2.pdf.
Raw sends load.
Parameters
msgDst the old value of the destination operand.
msgSrc0 the first source operand of send message.
msgSrc1 the second source operand of send message.
exDesc the extended message descriptor.
msgDesc the message descriptor.
execSize the execution size, which must be a compile time constant.
sfid the shared function ID, which must be a compile time constant.
numSrc0 the number of GRFs for source-0, which must be a compile time constant.
numSrc1 the number of GRFs for source-1, which must be a compile time constant.
numDst the number of GRFs for destination, which must be a compile time constant.
isEOT the flag that indicates whether this is an EOT message, which must be a compile time constant (optional - default to 0).
isSendc the flag that indicates whether sendc should be used, which must be a compile time constant (optional - default to 0).
mask the predicate to specify enabled channels (optional - default to on).
Returns the vector value read from memory.
Definition at line 857 of file esimd_memory.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_raw_sends_store()
template<typename T1 , int n1, typename T2 , int n2, int N = 16> ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::INTEL::gpu::esimd_raw_sends_store (simd< T1, n1 > msgSrc0, simd< T2, n2 > msgSrc1, uint32_t exDesc, uint32_t msgDesc, uint8_t execSize, uint8_t sfid, uint8_t numSrc0, uint8_t numSrc1, uint8_t isEOT = 0, uint8_t isSendc = 0, simd< uint16_t, N > mask = 1)
Raw sends store.
Parameters
msgSrc0 the first source operand of send message.
msgSrc1 the second source operand of send message.
exDesc the extended message descriptor.
msgDesc the message descriptor.
execSize the execution size, which must be a compile time constant.
sfid the shared function ID, which must be a compile time constant.
numSrc0 the number of GRFs for source-0, which must be a compile time constant.
numSrc1 the number of GRFs for source-1, which must be a compile time constant.
isEOT the flag that indicates whether this is an EOT message, which must be a compile time constant (optional - default to 0).
isSendc the flag that indicates whether sendc should be used, which must be a compile time constant (optional - default to 0).
mask the predicate to specify enabled channels (optional - default to on).
Definition at line 954 of file esimd_memory.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_rdtsc()
template<typename T = void> simd<uint, 4> cl::sycl::INTEL::gpu::esimd_rdtsc ()
Referenced by esimd_fbh().
esimd_rol() [1/3]
template<typename T0 , typename T1 , int SZ> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<std::is_integral<T0>::value && std::is_integral<T1>::value, simd<T0, SZ> >::type cl::sycl::INTEL::gpu::esimd_rol (simd< T1, SZ > src0, simd< T1, SZ > src1)
Definition at line 202 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_rol() [2/3]
template<typename T0 , typename T1 , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<U>::value, simd<T0, SZ> >::type cl::sycl::INTEL::gpu::esimd_rol (simd< T1, SZ > src0, U src1)
Definition at line 212 of file esimd_math.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_rol() [3/3]
template<typename T0 , typename T1 , typename T2 > ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value && detail::is_esimd_scalar<T2>::value && std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<T2>::value, typename std::remove_const<T0>::type>::type cl::sycl::INTEL::gpu::esimd_rol (T1 src0, T2 src1)
Definition at line 225 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_ror() [1/3]
template<typename T0 , typename T1 , int SZ> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<std::is_integral<T0>::value && std::is_integral<T1>::value, simd<T0, SZ> >::type cl::sycl::INTEL::gpu::esimd_ror (simd< T1, SZ > src0, simd< T1, SZ > src1)
Definition at line 239 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_ror() [2/3]
template<typename T0 , typename T1 , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<U>::value, simd<T0, SZ> >::type cl::sycl::INTEL::gpu::esimd_ror (simd< T1, SZ > src0, U src1)
Definition at line 249 of file esimd_math.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_ror() [3/3]
template<typename T0 , typename T1 , typename T2 > ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value && detail::is_esimd_scalar<T2>::value && std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<T2>::value, typename std::remove_const<T0>::type>::type cl::sycl::INTEL::gpu::esimd_ror (T1 src0, T2 src1)
Definition at line 262 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_sat()
template<typename T0 , typename T1 , int SZ> ESIMD_NODEBUG ESIMD_INLINE simd<T0, SZ> cl::sycl::INTEL::gpu::esimd_sat (simd< T1, SZ > src)
Definition at line 26 of file esimd_math.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_shl() [1/2]
template<typename T0 , typename T1 , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<U>::value, simd<T0, SZ> >::type cl::sycl::INTEL::gpu::esimd_shl (simd< T1, SZ > src0, U src1, int flag = GENX_NOSAT)
Definition at line 116 of file esimd_math.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, ESIMD_NODEBUG, and GENX_SAT.
esimd_shl() [2/2]
template<typename T0 , typename T1 , typename T2 > ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value && detail::is_esimd_scalar<T2>::value && std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<T2>::value, typename std::remove_const<T0>::type>::type cl::sycl::INTEL::gpu::esimd_shl (T1 src0, T2 src1, int flag = GENX_NOSAT)
Definition at line 154 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_shr() [1/2]
template<typename T0 , typename T1 , int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE std::enable_if<std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<U>::value, simd<T0, SZ> >::type cl::sycl::INTEL::gpu::esimd_shr (simd< T1, SZ > src0, U src1, int flag = GENX_NOSAT)
Definition at line 169 of file esimd_math.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, ESIMD_NODEBUG, and GENX_SAT.
esimd_shr() [2/2]
template<typename T0 , typename T1 , typename T2 > ESIMD_NODEBUG ESIMD_INLINE std::enable_if< detail::is_esimd_scalar<T0>::value && detail::is_esimd_scalar<T1>::value && detail::is_esimd_scalar<T2>::value && std::is_integral<T0>::value && std::is_integral<T1>::value && std::is_integral<T2>::value, typename std::remove_const<T0>::type>::type cl::sycl::INTEL::gpu::esimd_shr (T1 src0, T2 src1, int flag = GENX_NOSAT)
Definition at line 188 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
esimd_sin_emu() [1/4]
template<int N> simd<float, N> cl::sycl::INTEL::gpu::esimd_sin_emu (simd< float, N > x, const uint flags = 0)
Definition at line 1534 of file esimd_math.hpp.
References esimd_fmod(), GENX_SAT, cl::sycl::INTEL::gpu::simd< Ty, N >::merge(), and cl::sycl::sign().
esimd_sin_emu() [2/4]
template<typename T > float cl::sycl::INTEL::gpu::esimd_sin_emu (T x, const uint flags = 0)
Definition at line 1571 of file esimd_math.hpp.
References esimd_fmod(), GENX_SAT, cl::sycl::INTEL::gpu::simd< Ty, N >::merge(), and cl::sycl::sign().
Referenced by esimd_ceil().
esimd_sin_emu() [3/4]
template<int N> ESIMD_INLINE simd<float, N> cl::sycl::INTEL::gpu::esimd_sin_emu (simd< float, N > x, const uint flags)
Definition at line 1534 of file esimd_math.hpp.
References esimd_fmod(), GENX_SAT, cl::sycl::INTEL::gpu::simd< Ty, N >::merge(), and cl::sycl::sign().
esimd_sin_emu() [4/4]
template<typename T > ESIMD_INLINE float cl::sycl::INTEL::gpu::esimd_sin_emu (T x0, const uint flags)
Definition at line 1571 of file esimd_math.hpp.
References esimd_fmod(), GENX_SAT, cl::sycl::INTEL::gpu::simd< Ty, N >::merge(), and cl::sycl::sign().
Referenced by esimd_ceil().
esimd_sincos()
template<int SZ, typename U > ESIMD_NODEBUG ESIMD_INLINE simd<float, SZ> cl::sycl::INTEL::gpu::esimd_sincos (simd< float, SZ > & dstcos, U src0, int flag = GENX_NOSAT)
Definition at line 1099 of file esimd_math.hpp.
esimd_tanh() [1/3]
ESIMD_INLINE float cl::sycl::INTEL::gpu::esimd_tanh (float x)
Definition at line 1776 of file esimd_math.hpp.
References cl::sycl::INTEL::gpu::detail::esimd_tanh_impl().
esimd_tanh() [2/3]
template<int N> simd<float, N> cl::sycl::INTEL::gpu::esimd_tanh (simd< float, N > x)
Definition at line 1780 of file esimd_math.hpp.
References cl::sycl::INTEL::gpu::detail::esimd_tanh_impl().
Referenced by esimd_ceil().
esimd_tanh() [3/3]
template<int N> ESIMD_INLINE simd<float, N> cl::sycl::INTEL::gpu::esimd_tanh (simd< float, N > x)
Definition at line 1780 of file esimd_math.hpp.
References cl::sycl::INTEL::gpu::detail::esimd_tanh_impl().
Referenced by esimd_ceil().
esimd_tanh_cody_waite() [1/3]
ESIMD_INLINE float cl::sycl::INTEL::gpu::esimd_tanh_cody_waite (float x)
Definition at line 1765 of file esimd_math.hpp.
References cl::sycl::INTEL::gpu::detail::esimd_tanh_cody_waite_impl().
esimd_tanh_cody_waite() [2/3]
template<int N> simd<float, N> cl::sycl::INTEL::gpu::esimd_tanh_cody_waite (simd< float, N > x)
Definition at line 1770 of file esimd_math.hpp.
References cl::sycl::INTEL::gpu::detail::esimd_tanh_cody_waite_impl().
Referenced by esimd_ceil().
esimd_tanh_cody_waite() [3/3]
template<int N> ESIMD_INLINE simd<float, N> cl::sycl::INTEL::gpu::esimd_tanh_cody_waite (simd< float, N > x)
Definition at line 1770 of file esimd_math.hpp.
References cl::sycl::INTEL::gpu::detail::esimd_tanh_cody_waite_impl().
Referenced by esimd_ceil().
esimd_unpack_mask()
template<int N> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<(N == 8 || N == 16 || N == 32), simd<ushort, N> >::type cl::sycl::INTEL::gpu::esimd_unpack_mask (uint src0)
Definition at line 1259 of file esimd_math.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
flat_atomic() [1/3]
template<EsimdAtomicOpType Op, typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<check_atomic<Op, T, n, 0>), simd<T, n> >::type cl::sycl::INTEL::gpu::flat_atomic (T * p, simd< unsigned, n > offset, simd< ushort, n > pred)
flat-address atomic, zero source operand: inc and dec
Definition at line 534 of file esimd_memory.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, and ESIMD_NODEBUG.
flat_atomic() [2/3]
template<EsimdAtomicOpType Op, typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<check_atomic<Op, T, n, 1>), simd<T, n> >::type cl::sycl::INTEL::gpu::flat_atomic (T * p, simd< unsigned, n > offset, simd< T, n > src0, simd< ushort, n > pred)
flat-address atomic, one source operand, add/sub/min/max etc
Definition at line 546 of file esimd_memory.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, and ESIMD_NODEBUG.
flat_atomic() [3/3]
template<EsimdAtomicOpType Op, typename T , int n, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<check_atomic<Op, T, n, 2>), simd<T, n> >::type cl::sycl::INTEL::gpu::flat_atomic (T * p, simd< unsigned, n > offset, simd< T, n > src0, simd< T, n > src1, simd< ushort, n > pred)
flat-address atomic, two source operands
Definition at line 560 of file esimd_memory.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data().
gather() [1/2]
template<typename T , int n, int ElemsPerAddr = 1, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_INLINE ESIMD_NODEBUG std::enable_if<((n == 8 || n == 16 || n == 32) && (ElemsPerAddr == 1 || ElemsPerAddr == 2 || ElemsPerAddr == 4)), simd<T, n * ElemsPerAddr> >::type cl::sycl::INTEL::gpu::gather (T * p, simd< uint32_t, n > offsets, simd< uint16_t, n > pred = 1)
flat-address gather
Definition at line 91 of file esimd_memory.hpp.
References __esimd_rdregion(), ESIMD_INLINE, and ESIMD_NODEBUG.
gather() [2/2]
template<typename T , int N, typename AccessorTy , CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_INLINE ESIMD_NODEBUG std::enable_if<(sizeof(T) <= 4) && (N == 1 || N == 8 || N == 16) && !std::is_pointer<AccessorTy>::value, simd<T, N> >::type cl::sycl::INTEL::gpu::gather (AccessorTy acc, simd< uint32_t, N > offsets, uint32_t glob_offset = 0)
Accessor-based gather.
Collects elements located at given offsets in an accessor and returns them as a single simd object. An element can be 1, 2 or 4-byte value. Template (compile-time constant) parameters:
Template Parameters
T - element type; can only be a 1,2,4-byte integer or float,
N - the number of elements
AccessorTy - sycl::accessor type
L1H - L1 cache hint
L3H - L3 cache hint
Formal parameters:
Parameters
acc - the accessor to gather from
offsets - per-element offsets
glob_offset - offset added to each individual element's offset to compute actual memory access offset for that element
Definition at line 269 of file esimd_memory.hpp.
References __esimd_surf_read(), ESIMD_INLINE, ESIMD_NODEBUG, and cl::sycl::info::uint32_t.
gather4()
template<typename T , int n, ChannelMaskType Mask, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_INLINE ESIMD_NODEBUG std::enable_if<(n == 16 || n == 32) && (sizeof(T) == 4), simd<T, n * NumChannels(Mask)> >::type cl::sycl::INTEL::gpu::gather4 (T * p, simd< uint32_t, n > offsets, simd< uint16_t, n > pred = 1)
flat-address gather4 only allow simd-16 and simd-32
Definition at line 400 of file esimd_memory.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
getBaseRegion() [1/2]
template<typename T > T cl::sycl::INTEL::gpu::getBaseRegion (T Reg)
Definition at line 111 of file esimd_region.hpp.
getBaseRegion() [2/2]
template<typename T , typename U > T cl::sycl::INTEL::gpu::getBaseRegion (std::pair< T, U > Reg)
Definition at line 112 of file esimd_region.hpp.
getTopRegion() [1/2]
template<typename T > T cl::sycl::INTEL::gpu::getTopRegion (T Reg)
Definition at line 106 of file esimd_region.hpp.
Referenced by cl::sycl::INTEL::gpu::simd_view< BaseTy, RegionTy >::getOffsetX(), and cl::sycl::INTEL::gpu::simd_view< BaseTy, RegionTy >::getOffsetY().
getTopRegion() [2/2]
template<typename T , typename U > T cl::sycl::INTEL::gpu::getTopRegion (std::pair< T, U > Reg)
Definition at line 107 of file esimd_region.hpp.
hmax()
template<typename T0 , typename T1 , int SZ> ESIMD_INLINE ESIMD_NODEBUG T0 cl::sycl::INTEL::gpu::hmax (simd< T1, SZ > v)
Definition at line 1903 of file esimd_math.hpp.
hmin()
template<typename T0 , typename T1 , int SZ> ESIMD_INLINE ESIMD_NODEBUG T0 cl::sycl::INTEL::gpu::hmin (simd< T1, SZ > v)
Definition at line 1910 of file esimd_math.hpp.
is_type() [1/2]
template<typename U > constexpr bool cl::sycl::INTEL::gpu::is_type ()
Base case for checking if a type U is one of the types.
Definition at line 208 of file esimd_types.hpp.
is_type() [2/2]
template<typename U , typename T , typename... Ts> constexpr bool cl::sycl::INTEL::gpu::is_type ()
Definition at line 210 of file esimd_types.hpp.
media_block_load()
template<typename T , int m, int n, typename AccessorTy , unsigned plane = 0> ESIMD_INLINE ESIMD_NODEBUG simd<T, m * n> cl::sycl::INTEL::gpu::media_block_load (AccessorTy acc, unsigned x, unsigned y)
Definition at line 712 of file esimd_memory.hpp.
References ESIMD_INLINE, and ESIMD_NODEBUG.
media_block_store()
template<typename T , int m, int n, typename AccessorTy , unsigned plane = 0> ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::INTEL::gpu::media_block_store (AccessorTy acc, unsigned x, unsigned y, simd< T, m *n > vals)
Media block store.
Definition at line 762 of file esimd_memory.hpp.
operator<<()
std::ostream& cl::sycl::INTEL::gpu::operator<< (std::ostream & O, half const & rhs) inline
Definition at line 246 of file esimd_types.hpp.
operator>>()
std::istream& cl::sycl::INTEL::gpu::operator>> (std::istream & I, half & rhs) inline
Definition at line 251 of file esimd_types.hpp.
readRegion() [1/2]
template<typename BT , int BN, typename RTy > vector_type_t<typename RTy::element_type, RTy::length> ESIMD_INLINE cl::sycl::INTEL::gpu::readRegion (const vector_type_t< BT, BN > & Base, RTy Region)
read from a basic region of a vector, return a vector
Definition at line 147 of file esimd_intrin.hpp.
References __esimd_rdregion(), and ESIMD_INLINE.
readRegion() [2/2]
template<typename BT , int BN, typename T , typename U > ESIMD_INLINE vector_type_t<typename T::element_type, T::length> cl::sycl::INTEL::gpu::readRegion (const vector_type_t< BT, BN > & Base, std::pair< T, U > Region)
read from a nested region of a vector, return a vector
Definition at line 169 of file esimd_intrin.hpp.
References __esimd_all(), __esimd_any(), __esimd_vload(), __esimd_vstore(), cl::sycl::length(), and SYCL_EXTERNAL.
reduce()
template<typename T0 , typename T1 , int SZ, typename BinaryOperation > ESIMD_INLINE ESIMD_NODEBUG T0 cl::sycl::INTEL::gpu::reduce (simd< T1, SZ > v, BinaryOperation op)
Definition at line 1917 of file esimd_math.hpp.
Referenced by cl::sycl::ONEAPI::sub_group::barrier(), cl::sycl::ONEAPI::detail::reduAuxCGFuncImpl(), and cl::sycl::ONEAPI::detail::reduCGFuncImpl().
scalar_load()
template<typename T , typename AccessorTy , CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_INLINE ESIMD_NODEBUG T cl::sycl::INTEL::gpu::scalar_load (AccessorTy acc, uint32_t offset)
Load a scalar value from an accessor.
Definition at line 376 of file esimd_memory.hpp.
scalar_store()
template<typename T , typename AccessorTy , CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::INTEL::gpu::scalar_store (AccessorTy acc, uint32_t offset, T val)
Store a scalar value into an accessor.
Definition at line 384 of file esimd_memory.hpp.
References ESIMD_INLINE, ESIMD_NODEBUG, and NumChannels.
scatter() [1/2]
template<typename T , int n, int ElemsPerAddr = 1, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_INLINE ESIMD_NODEBUG std::enable_if<((n == 8 || n == 16 || n == 32) && (ElemsPerAddr == 1 || ElemsPerAddr == 2 || ElemsPerAddr == 4)), void>::type cl::sycl::INTEL::gpu::scatter (T * p, simd< T, n *ElemsPerAddr > vals, simd< uint32_t, n > offsets, simd< uint16_t, n > pred = 1)
flat-address scatter
Definition at line 133 of file esimd_memory.hpp.
References __esimd_wrregion(), and cl::sycl::INTEL::gpu::simd< Ty, N >::data().
scatter() [2/2]
template<typename T , int N, typename AccessorTy , CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_INLINE ESIMD_NODEBUG std::enable_if<(sizeof(T) <= 4) && (N == 1 || N == 8 || N == 16) && !std::is_pointer<AccessorTy>::value, void>::type cl::sycl::INTEL::gpu::scatter (AccessorTy acc, simd< T, N > vals, simd< uint32_t, N > offsets, uint32_t glob_offset = 0, simd< uint16_t, N > pred = 1)
Accessor-based scatter.
Writes elements of a simd object into an accessor at given offsets. An element can be 1, 2 or 4-byte value. Template (compile-time constant) parameters:
Template Parameters
T - element type; can only be a 1,2,4-byte integer or float,
N - the number of elements
AccessorTy - sycl::accessor type
L1H - L1 cache hint
L3H - L3 cache hint
Formal parameters:
Parameters
acc - the accessor to scatter to
vals - values to write
offsets - per-element offsets
glob_offset - offset added to each individual element's offset to compute actual memory access offset for that element
pred - per-element predicates; elements with zero corresponding predicates are not written
Definition at line 334 of file esimd_memory.hpp.
References cl::sycl::info::uint32_t.
scatter4()
template<typename T , int n, ChannelMaskType Mask, CacheHint L1H = CacheHint::None, CacheHint L3H = CacheHint::None> ESIMD_INLINE ESIMD_NODEBUG std::enable_if<(n == 16 || n == 32) && (sizeof(T) == 4), void>::type cl::sycl::INTEL::gpu::scatter4 (T * p, simd< T, n *NumChannels(Mask)> vals, simd< uint32_t, n > offsets, simd< uint16_t, n > pred = 1)
flat-address scatter4
Definition at line 414 of file esimd_memory.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data().
slm_atomic() [1/3]
template<EsimdAtomicOpType Op, typename T , int n> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<check_atomic<Op, T, n, 0>), simd<T, n> >::type cl::sycl::INTEL::gpu::slm_atomic (simd< uint32_t, n > offsets, simd< ushort, n > pred)
SLM atomic, zero source operand: inc and dec.
Definition at line 666 of file esimd_memory.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, and ESIMD_NODEBUG.
slm_atomic() [2/3]
template<EsimdAtomicOpType Op, typename T , int n> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<check_atomic<Op, T, n, 1>), simd<T, n> >::type cl::sycl::INTEL::gpu::slm_atomic (simd< uint32_t, n > offsets, simd< T, n > src0, simd< ushort, n > pred)
SLM atomic, one source operand, add/sub/min/max etc.
Definition at line 674 of file esimd_memory.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, and ESIMD_NODEBUG.
slm_atomic() [3/3]
template<EsimdAtomicOpType Op, typename T , int n> ESIMD_NODEBUG ESIMD_INLINE std::enable_if<check_atomic<Op, T, n, 2>), simd<T, n> >::type cl::sycl::INTEL::gpu::slm_atomic (simd< uint32_t, n > offsets, simd< T, n > src0, simd< T, n > src1, simd< ushort, n > pred)
SLM atomic, two source operands.
Definition at line 684 of file esimd_memory.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, and ESIMD_NODEBUG.
slm_block_load()
template<typename T , int n> ESIMD_INLINE ESIMD_NODEBUG simd<T, n> cl::sycl::INTEL::gpu::slm_block_load (uint32_t offset)
SLM block-load.
Definition at line 632 of file esimd_memory.hpp.
References __esimd::isPowerOf2(), and __esimd::OWORD.
slm_block_store()
template<typename T , int n> ESIMD_INLINE ESIMD_NODEBUG void cl::sycl::INTEL::gpu::slm_block_store (uint32_t offset, simd< T, n > vals)
SLM block-store.
Definition at line 647 of file esimd_memory.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, ESIMD_NODEBUG, __esimd::isPowerOf2(), and __esimd::OWORD.
slm_init()
SYCL_EXTERNAL void cl::sycl::INTEL::gpu::slm_init (uint32_t size)
SLM functions.
declare per-work-group slm size
Definition at line 794 of file esimd_memory.hpp.
Referenced by esimd_fence().
slm_load()
template<typename T , int n> ESIMD_INLINE ESIMD_NODEBUG std::enable_if<(n == 16 || n == 32), simd<T, n> >::type cl::sycl::INTEL::gpu::slm_load (simd< uint32_t, n > offsets, simd< uint16_t, n > pred = 1)
SLM gather only allow simd-16 and simd-32.
Definition at line 598 of file esimd_memory.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, and ESIMD_NODEBUG.
slm_load4()
template<typename T , int n, ChannelMaskType Mask> ESIMD_INLINE ESIMD_NODEBUG std::enable_if<(n == 8 || n == 16 || n == 32) && (sizeof(T) == 4), simd<T, n * NumChannels(Mask)> >::type cl::sycl::INTEL::gpu::slm_load4 (simd< uint32_t, n > offsets, simd< uint16_t, n > pred = 1)
SLM gather4 only allow simd-8, simd-16 and simd-32.
Definition at line 617 of file esimd_memory.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data().
slm_store()
template<typename T , int n> ESIMD_INLINE ESIMD_NODEBUG std::enable_if<(n == 16 || n == 32), void>::type cl::sycl::INTEL::gpu::slm_store (simd< T, n > vals, simd< uint32_t, n > offsets, simd< uint16_t, n > pred = 1)
SLM scatter.
Definition at line 606 of file esimd_memory.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data(), ESIMD_INLINE, ESIMD_NODEBUG, and NumChannels.
slm_store4()
template<typename T , int n, ChannelMaskType Mask> std::enable_if<(n == 8 || n == 16 || n == 32) && (sizeof(T) == 4), void>::type cl::sycl::INTEL::gpu::slm_store4 (simd< T, n *NumChannels(Mask)> vals, simd< uint32_t, n > offsets, simd< uint16_t, n > pred = 1)
SLM scatter4.
Definition at line 625 of file esimd_memory.hpp.
References cl::sycl::INTEL::gpu::simd< Ty, N >::data().
Variable Documentation
CMPI
auto constexpr cl::sycl::INTEL::gpu::CMPI = 3.14159265f static
Definition at line 1529 of file esimd_math.hpp.
ESIMD_CONST_2PI
auto constexpr cl::sycl::INTEL::gpu::ESIMD_CONST_2PI = 6.28318f static
Definition at line 1345 of file esimd_math.hpp.
ESIMD_CONST_E
auto constexpr cl::sycl::INTEL::gpu::ESIMD_CONST_E = 2.71828f static
Definition at line 1343 of file esimd_math.hpp.
ESIMD_CONST_PI
auto constexpr cl::sycl::INTEL::gpu::ESIMD_CONST_PI = 3.14159f static
Definition at line 1344 of file esimd_math.hpp.
Referenced by esimd_atan2().
ESIMD_DBL_EPSILON
auto constexpr cl::sycl::INTEL::gpu::ESIMD_DBL_EPSILON = 0.00001f static
Definition at line 1348 of file esimd_math.hpp.
Referenced by esimd_atan2_fast().