SYCL Runtime: source/detail/pi.cpp File Reference
pi.cpp File Reference
The Plugin Interface
Implementation of C++ wrappers for PI interface.
#include "context_impl.hpp"
#include <CL/sycl/context.hpp>
#include <CL/sycl/detail/common.hpp>
#include <CL/sycl/detail/pi.hpp>
#include <detail/config.hpp>
#include <detail/plugin.hpp>
#include <bitset>
#include <cstdarg>
#include <cstring>
#include <iostream>
#include <map>
#include <sstream>
#include <stddef.h>
#include <string>
Namespaces
cl
---— Error handling, matching OpenCL plugin semantics.
Functions
__SYCL_EXPORT void cl::sycl::detail::pi::contextSetExtendedDeleter (const cl::sycl::context &constext, pi_context_extended_deleter func, void *user_data)
std::string cl::sycl::detail::pi::platformInfoToString (pi_platform_info info)
std::string cl::sycl::detail::pi::memFlagToString (pi_mem_flags Flag)
std::string cl::sycl::detail::pi::memFlagsToString (pi_mem_flags Flags)
bool cl::sycl::detail::pi::findPlugins (vector_class< std::pair< std::string, backend >> &PluginNames)
void * cl::sycl::detail::pi::loadPlugin (const std::string &PluginPath)
bool cl::sycl::detail::pi::bindPlugin (void *Library, PiPlugin *PluginInformation)
bool cl::sycl::detail::pi::trace (TraceLevel level)
vector_class< plugin > cl::sycl::detail::pi::initialize ()
__SYCL_EXPORT void cl::sycl::detail::pi::die (const char *Message)
__SYCL_EXPORT void cl::sycl::detail::pi::assertion (bool Condition, const char *Message=nullptr)
std::ostream & cl::sycl::detail::pi::operator<< (std::ostream &Out, const DeviceBinaryProperty &P)
static pi_uint32 cl::sycl::detail::pi::asUint32 (const void *Addr)
PiDeviceBinaryType cl::sycl::detail::pi::getBinaryImageFormat (const unsigned char *ImgData, size_t ImgSize)
Tries to determine the device binary image foramat.
Variables
bool cl::sycl::detail::pi::XPTIInitDone = false
Detailed Description
Implementation of C++ wrappers for PI interface.
Definition in file pi.cpp.
Function Documentation
getBinaryImageFormat()
RT::PiDeviceBinaryType cl::sycl::detail::pi::getBinaryImageFormat (const unsigned char * ImgData, size_t ImgSize)
Tries to determine the device binary image foramat.
Returns PI_DEVICE_BINARY_TYPE_NONE if unsuccessful.
Definition at line 416 of file pi.cpp.
References pi_device_binary_struct::BinaryStart, pi_device_binary_struct::Format, and cl::sycl::detail::pi::getBinaryImageFormat().
Referenced by cl::sycl::detail::pi::getBinaryImageFormat(), and cl::sycl::detail::pi::DeviceBinaryImage::getSpecConstants().