SYCL Runtime: include/CL/sycl/detail/pi.hpp File Reference
pi.hpp File Reference
The Plugin Interface
C++ wrapper of extern "C" PI interfaces.
#include <CL/sycl/backend_types.hpp>
#include <CL/sycl/detail/common.hpp>
#include <CL/sycl/detail/export.hpp>
#include <CL/sycl/detail/os_util.hpp>
#include <CL/sycl/detail/pi.h>
#include <cassert>
#include <sstream>
#include <string>
#include <CL/sycl/detail/pi.def>
Classes
struct cl::sycl::detail::pi::PiFuncInfo< PiApiOffset >
class cl::sycl::detail::pi::DeviceBinaryProperty
class cl::sycl::detail::pi::DeviceBinaryImage
class cl::sycl::detail::pi::DeviceBinaryImage::PropertyRange
class cl::sycl::detail::pi::DeviceBinaryImage::PropertyRange::ConstIterator
Namespaces
cl
---— Error handling, matching OpenCL plugin semantics.
Macros
#define _PI_API(api) api,
#define OPENCL_PLUGIN_NAME "libpi_opencl.so"
#define CUDA_PLUGIN_NAME "libpi_cuda.so"
#define PI_HANDLE_UNKNOWN_PARAM_NAME(parameter) { cl::sycl::detail::pi::handleUnknownParamName(__func__, parameter); }
#define _PI_API(api)
Typedefs
using cl::sycl::detail::pi::PiPlugin = ::pi_plugin
using cl::sycl::detail::pi::PiResult = ::pi_result
using cl::sycl::detail::pi::PiPlatform = ::pi_platform
using cl::sycl::detail::pi::PiDevice = ::pi_device
using cl::sycl::detail::pi::PiDeviceType = ::pi_device_type
using cl::sycl::detail::pi::PiDeviceInfo = ::pi_device_info
using cl::sycl::detail::pi::PiDeviceBinaryType = ::pi_device_binary_type
using cl::sycl::detail::pi::PiContext = ::pi_context
using cl::sycl::detail::pi::PiProgram = ::pi_program
using cl::sycl::detail::pi::PiKernel = ::pi_kernel
using cl::sycl::detail::pi::PiQueue = ::pi_queue
using cl::sycl::detail::pi::PiQueueProperties = ::pi_queue_properties
using cl::sycl::detail::pi::PiMem = ::pi_mem
using cl::sycl::detail::pi::PiMemFlags = ::pi_mem_flags
using cl::sycl::detail::pi::PiEvent = ::pi_event
using cl::sycl::detail::pi::PiSampler = ::pi_sampler
using cl::sycl::detail::pi::PiSamplerInfo = ::pi_sampler_info
using cl::sycl::detail::pi::PiSamplerProperties = ::pi_sampler_properties
using cl::sycl::detail::pi::PiSamplerAddressingMode = ::pi_sampler_addressing_mode
using cl::sycl::detail::pi::PiSamplerFilterMode = ::pi_sampler_filter_mode
using cl::sycl::detail::pi::PiMemImageFormat = ::pi_image_format
using cl::sycl::detail::pi::PiMemImageDesc = ::pi_image_desc
using cl::sycl::detail::pi::PiMemImageInfo = ::pi_image_info
using cl::sycl::detail::pi::PiMemObjectType = ::pi_mem_type
using cl::sycl::detail::pi::PiMemImageChannelOrder = ::pi_image_channel_order
using cl::sycl::detail::pi::PiMemImageChannelType = ::pi_image_channel_type
Enumerations
enum PiApiKind { _PI_API }
enum TraceLevel { PI_TRACE_BASIC = 0x1, PI_TRACE_CALLS = 0x2, PI_TRACE_ALL = -1 }
Functions
bool cl::sycl::detail::pi::trace (TraceLevel level)
__SYCL_EXPORT void cl::sycl::detail::pi::die (const char *Message)
__SYCL_EXPORT void cl::sycl::detail::pi::assertion (bool Condition, const char *Message=nullptr)
template<typename T >
void cl::sycl::detail::pi::handleUnknownParamName (const char *functionName, T parameter)
__SYCL_EXPORT void cl::sycl::detail::pi::contextSetExtendedDeleter (const cl::sycl::context &constext, pi_context_extended_deleter func, void *user_data)
void * cl::sycl::detail::pi::loadOsLibrary (const std::string &Library)
void * cl::sycl::detail::pi::getOsLibraryFuncAddress (void *Library, const std::string &FunctionName)
std::string cl::sycl::detail::pi::platformInfoToString (pi_platform_info info)
template<class To , class From >
To cl::sycl::detail::pi::cast (From value)
vector_class< plugin > cl::sycl::detail::pi::initialize ()
uint64_t cl::sycl::detail::pi::emitFunctionBeginTrace (const char *FName)
Emits an XPTI trace before a PI API call is made.
void cl::sycl::detail::pi::emitFunctionEndTrace (uint64_t CorrelationID, const char *FName)
Emits an XPTI trace after the PI API call has been made.
template<typename T >
void cl::sycl::detail::pi::print (T val)
template<>
void cl::sycl::detail::pi::print (PiPlatform val)
template<>
void cl::sycl::detail::pi::print (PiResult val)
template<>
void cl::sycl::detail::pi::print (std::nullptr_t val)
void cl::sycl::detail::pi::printArgs (void)
template<typename Arg0 , typename... Args>
void cl::sycl::detail::pi::printArgs (Arg0 arg0, Args... args)
std::ostream & cl::sycl::detail::pi::operator<< (std::ostream &Out, const DeviceBinaryProperty &P)
PiDeviceBinaryType cl::sycl::detail::pi::getBinaryImageFormat (const unsigned char *ImgData, size_t ImgSize)
Tries to determine the device binary image foramat.
template<>
pi::PiProgram cl::sycl::detail::pi::cast (cl_program interop)
template<>
pi::PiDevice cl::sycl::detail::pi::cast (cl_device_id interop)
Variables
std::shared_ptr< plugin > cl::sycl::detail::pi::GlobalPlugin
Detailed Description
C++ wrapper of extern "C" PI interfaces.
Definition in file pi.hpp.
Macro Definition Documentation
_PI_API
#define _PI_API (api)
Value:
template <> struct PiFuncInfo<PiApiKind::api> {                              \
    using FuncPtrT = decltype(&::api);                                         \
    inline std::string getFuncName() { return #api; }                          \
    inline FuncPtrT getFuncPtr(PiPlugin MPlugin) {                             \
      return MPlugin.PiFunctionTable.api;                                      \
    }                                                                          \
  };
Definition at line 143 of file pi.hpp.
Function Documentation
emitFunctionBeginTrace()
uint64_t cl::sycl::detail::pi::emitFunctionBeginTrace (const char * FName)
Emits an XPTI trace before a PI API call is made.
Parameters
FName The name of the PI API call
Returns
The correlation ID for the API call that is to be used by the emitFunctionEndTrace() call
Definition at line 59 of file pi.cpp.
References cl::sycl::detail::pi::emitFunctionBeginTrace().
Referenced by cl::sycl::detail::pi::emitFunctionBeginTrace().
emitFunctionEndTrace()
void cl::sycl::detail::pi::emitFunctionEndTrace (uint64_t CorrelationID, const char * FName)
Emits an XPTI trace after the PI API call has been made.
Parameters
CorrelationID The correlation ID for the API call generated by the emitFunctionBeginTrace() call.
FName The name of the PI API call
Definition at line 103 of file pi.cpp.
References cl::sycl::detail::pi::emitFunctionEndTrace().
Referenced by cl::sycl::detail::pi::emitFunctionEndTrace().
getBinaryImageFormat()
RT::PiDeviceBinaryType cl::sycl::detail::pi::getBinaryImageFormat (const unsigned char * ImgData, size_t ImgSize)
Tries to determine the device binary image foramat.
Returns PI_DEVICE_BINARY_TYPE_NONE if unsuccessful.
Definition at line 477 of file pi.cpp.
References pi_device_binary_struct::BinaryStart, pi_device_binary_struct::Format, and cl::sycl::detail::pi::getBinaryImageFormat().
Referenced by cl::sycl::detail::pi::getBinaryImageFormat(), and cl::sycl::detail::pi::DeviceBinaryImage::getSpecConstants().