DPC++ Runtime: include/sycl/detail/pi.h File Reference
pi.h File Reference
#include <sycl/detail/export.hpp>
#include <cstddef>
#include <cstdint>
#include <variant>
#include <sycl/detail/pi_error.def>
#include <sycl/detail/pi.def>
Classes
struct _pi_offload_entry_struct
struct _pi_device_binary_property_struct
struct _pi_device_binary_property_set_struct
struct pi_device_binary_struct
This struct is a record of the device binary information.
struct pi_buffer_region_struct
struct pi_buff_rect_offset_struct
struct pi_buff_rect_region_struct
struct pi_image_offset_struct
struct pi_image_region_struct
struct pi_device_binaries_struct
This struct is a record of all the device code that may be offloaded.
struct _pi_image_format
struct _pi_image_desc
struct _pi_mem_obj_property
struct pi_ext_command_buffer_desc
struct pi_ext_command_buffer_update_memobj_arg_desc_t
struct pi_ext_command_buffer_update_pointer_arg_desc_t
struct pi_ext_command_buffer_update_value_arg_desc_t
struct pi_ext_command_buffer_update_kernel_launch_desc
struct _pi_plugin
struct _pi_plugin::FunctionPointers
Macros
#define _PI_H_VERSION_MAJOR 16
#define _PI_H_VERSION_MINOR 51
#define _PI_STRING_HELPER(a) #a
#define _PI_CONCAT(a, b) _PI_STRING_HELPER(a.b)
#define _PI_TRIPLE_CONCAT(a, b, c) _PI_STRING_HELPER(a.b.c)
#define _PI_PLUGIN_VERSION_STRING(PluginVersion) _PI_TRIPLE_CONCAT(_PI_H_VERSION_MAJOR, _PI_H_VERSION_MINOR, PluginVersion)
#define _PI_H_VERSION_STRING _PI_CONCAT(_PI_H_VERSION_MAJOR, _PI_H_VERSION_MINOR)
#define _PI_STRING_SUBSTITUTE(X) _PI_STRING_HELPER(X)
#define _PI_PLUGIN_VERSION_CHECK(PI_API_VERSION, PI_PLUGIN_VERSION)
#define _PI_ERRC(NAME, VAL) NAME = VAL,
#define _PI_ERRC_WITH_MSG(NAME, VAL, MSG) NAME = VAL,
#define __SYCL_PI_DEVICE_BINARY_TARGET_UNKNOWN "<unknown>"
Target identification strings for pi_device_binary_struct.DeviceTargetSpec.
#define __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV32 "spir"
SPIR-V 32-bit image <-> "spir", 32-bit OpenCL device.
#define __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64 "spir64"
SPIR-V 64-bit image <-> "spir64", 64-bit OpenCL device.
#define __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_X86_64 "spir64_x86_64"
Device-specific binary images produced from SPIR-V 64-bit <-> various "spir64_*" triples for specific 64-bit OpenCL devices.
#define __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_GEN "spir64_gen"
#define __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_FPGA "spir64_fpga"
#define __SYCL_PI_DEVICE_BINARY_TARGET_NVPTX64 "nvptx64"
PTX 64-bit image <-> "nvptx64", 64-bit NVIDIA PTX device.
#define __SYCL_PI_DEVICE_BINARY_TARGET_AMDGCN "amdgcn"
#define __SYCL_PI_DEVICE_BINARY_TARGET_NATIVE_CPU "native_cpu"
#define PI_DEVICE_INFO_EXTENSION_DEVICELIB_ASSERT "cl_intel_devicelib_assert"
Extension to denote native support of assert feature by an arbitrary device piDeviceGetInfo call should return this extension when the device supports native asserts if supported extensions' names are requested.
#define __SYCL_PI_PROPERTY_SET_SPEC_CONST_MAP "SYCL/specialization constants"
Device binary image property set names recognized by the SYCL runtime.
#define __SYCL_PI_PROPERTY_SET_SPEC_CONST_DEFAULT_VALUES_MAP "SYCL/specialization constants default values"
PropertySetRegistry::SYCL_SPEC_CONSTANTS_DEFAULT_VALUES defined in PropertySetIO.h.
#define __SYCL_PI_PROPERTY_SET_DEVICELIB_REQ_MASK "SYCL/devicelib req mask"
PropertySetRegistry::SYCL_DEVICELIB_REQ_MASK defined in PropertySetIO.h.
#define __SYCL_PI_PROPERTY_SET_KERNEL_PARAM_OPT_INFO "SYCL/kernel param opt"
PropertySetRegistry::SYCL_KERNEL_PARAM_OPT_INFO defined in PropertySetIO.h.
#define __SYCL_PI_PROPERTY_SET_PROGRAM_METADATA "SYCL/program metadata"
PropertySetRegistry::SYCL_KERNEL_PROGRAM_METADATA defined in PropertySetIO.h.
#define __SYCL_PI_PROPERTY_SET_SYCL_MISC_PROP "SYCL/misc properties"
PropertySetRegistry::SYCL_MISC_PROP defined in PropertySetIO.h.
#define __SYCL_PI_PROPERTY_SET_SYCL_ASSERT_USED "SYCL/assert used"
PropertySetRegistry::SYCL_ASSERT_USED defined in PropertySetIO.h.
#define __SYCL_PI_PROPERTY_SET_SYCL_EXPORTED_SYMBOLS "SYCL/exported symbols"
PropertySetRegistry::SYCL_EXPORTED_SYMBOLS defined in PropertySetIO.h.
#define __SYCL_PI_PROPERTY_SET_SYCL_DEVICE_GLOBALS "SYCL/device globals"
PropertySetRegistry::SYCL_DEVICE_GLOBALS defined in PropertySetIO.h.
#define __SYCL_PI_PROPERTY_SET_SYCL_DEVICE_REQUIREMENTS "SYCL/device requirements"
PropertySetRegistry::SYCL_DEVICE_REQUIREMENTS defined in PropertySetIO.h.
#define __SYCL_PI_PROPERTY_SET_SYCL_HOST_PIPES "SYCL/host pipes"
PropertySetRegistry::SYCL_HOST_PIPES defined in PropertySetIO.h.
#define __SYCL_PI_PROGRAM_METADATA_TAG_REQD_WORK_GROUP_SIZE "@reqd_work_group_size"
Program metadata tags recognized by the PI backends.
#define __SYCL_PI_PROGRAM_METADATA_GLOBAL_ID_MAPPING "@global_id_mapping"
#define __SYCL_PI_PROGRAM_METADATA_TAG_NEED_FINALIZATION "Requires finalization"
#define PI_BIT(_i) (1 << _i)
#define _PI_API(api) decltype(::api) *api;
Typedefs
using pi_int32 = int32_t
using pi_uint32 = uint32_t
using pi_uint64 = uint64_t
using pi_bool = pi_uint32
using pi_bitfield = pi_uint64
using pi_native_handle = uintptr_t
using pi_context_properties = intptr_t
using pi_device_exec_capabilities = pi_bitfield
using pi_sampler_properties = pi_bitfield
using pi_memory_order_capabilities = pi_bitfield
using pi_memory_scope_capabilities = pi_bitfield
using pi_mem_flags = pi_bitfield
using pi_map_flags = pi_bitfield
using pi_mem_properties = pi_bitfield
using pi_usm_mem_properties = pi_bitfield
using pi_queue_properties = pi_bitfield
using pi_result = _pi_result
using pi_platform_info = _pi_platform_info
using pi_platform_backend = _pi_platform_backend
using pi_device_type = _pi_device_type
using pi_device_mem_cache_type = _pi_device_mem_cache_type
using pi_device_local_mem_type = _pi_device_local_mem_type
using pi_device_info = _pi_device_info
using pi_program_info = _pi_program_info
using pi_context_info = _pi_context_info
using pi_queue_info = _pi_queue_info
using pi_image_info = _pi_image_info
using pi_kernel_info = _pi_kernel_info
using pi_kernel_group_info = _pi_kernel_group_info
using pi_kernel_sub_group_info = _pi_kernel_sub_group_info
using pi_event_info = _pi_event_info
using pi_command_type = _pi_command_type
using pi_mem_type = _pi_mem_type
using pi_mem_advice = _pi_mem_advice
using pi_image_channel_order = _pi_image_channel_order
using pi_image_channel_type = _pi_image_channel_type
using pi_buffer_create_type = _pi_buffer_create_type
using pi_sampler_addressing_mode = _pi_sampler_addressing_mode
using pi_sampler_filter_mode = _pi_sampler_filter_mode
using pi_sampler_cubemap_filter_mode = _pi_sampler_cubemap_filter_mode
using pi_sampler_info = _pi_sampler_info
using pi_event_status = _pi_event_status
using pi_program_build_info = _pi_program_build_info
using pi_program_build_status = _pi_program_build_status
using pi_program_binary_type = _pi_program_binary_type
using pi_profiling_info = _pi_profiling_info
using pi_kernel_cache_config = _pi_kernel_cache_config
using pi_image_copy_flags = _pi_image_copy_flags
using pi_device_partition_property = intptr_t
using pi_device_affinity_domain = pi_bitfield
using pi_device_fp_config = pi_bitfield
using _pi_offload_entry = _pi_offload_entry_struct *
typedef _pi_device_binary_property_struct * pi_device_binary_property
typedef _pi_device_binary_property_set_struct * pi_device_binary_property_set
using pi_device_binary_type = uint8_t
Types of device binary.
using pi_device_binary = pi_device_binary_struct *
using pi_buffer_region = pi_buffer_region_struct *
using pi_buff_rect_offset = pi_buff_rect_offset_struct *
using pi_buff_rect_region = pi_buff_rect_region_struct *
using pi_image_offset = pi_image_offset_struct *
using pi_image_region = pi_image_region_struct *
using pi_device_binaries = pi_device_binaries_struct *
using pi_platform = _pi_platform *
using pi_device = _pi_device *
using pi_context = _pi_context *
using pi_queue = _pi_queue *
using pi_mem = _pi_mem *
using pi_program = _pi_program *
using pi_kernel = _pi_kernel *
using pi_event = _pi_event *
using pi_sampler = _pi_sampler *
using pi_image_handle = pi_uint64
using pi_image_mem_handle = void *
using pi_interop_mem_handle = pi_uint64
using pi_interop_semaphore_handle = pi_uint64
using pi_image_format = _pi_image_format
using pi_image_desc = _pi_image_desc
using pi_mem_info = _pi_mem_info
using pi_peer_attr = _pi_peer_attr
using pi_plugin = _pi_plugin
typedef void(* pi_context_extended_deleter) (void *user_data)
using pi_kernel_exec_info = _pi_kernel_exec_info
using pi_mem_obj_access = _pi_mem_obj_access
typedef uint32_t pi_mem_access_flag
using pi_mem_obj_property_type = _pi_mem_obj_property_type
using pi_mem_obj_property = _pi_mem_obj_property
using pi_usm_capability_query = _pi_usm_capability_query
using pi_usm_capabilities = _pi_usm_capabilities
using pi_mem_alloc_info = _pi_mem_alloc_info
using pi_usm_type = _pi_usm_type
using pi_usm_migration_flags = _pi_usm_migration_flags
using pi_ext_command_buffer = _pi_ext_command_buffer *
using pi_ext_command_buffer_command = _pi_ext_command_buffer_command *
using pi_ext_sync_point = pi_uint32
Enumerations
enum _pi_result
enum _pi_event_status { PI_EVENT_COMPLETE = 0x0 , PI_EVENT_RUNNING = 0x1 , PI_EVENT_SUBMITTED = 0x2 , PI_EVENT_QUEUED = 0x3 }
enum _pi_platform_info {
PI_PLATFORM_INFO_EXTENSIONS = 0x0904 , PI_PLATFORM_INFO_NAME = 0x0902 , PI_PLATFORM_INFO_PROFILE = 0x0900 , PI_PLATFORM_INFO_VENDOR = 0x0903 ,
PI_PLATFORM_INFO_VERSION = 0x0901 , PI_EXT_PLATFORM_INFO_BACKEND = 0x21000
}
enum _pi_program_build_info { PI_PROGRAM_BUILD_INFO_STATUS = 0x1181 , PI_PROGRAM_BUILD_INFO_OPTIONS = 0x1182 , PI_PROGRAM_BUILD_INFO_LOG = 0x1183 , PI_PROGRAM_BUILD_INFO_BINARY_TYPE = 0x1184 }
enum _pi_program_build_status { PI_PROGRAM_BUILD_STATUS_NONE = -1 , PI_PROGRAM_BUILD_STATUS_ERROR = -2 , PI_PROGRAM_BUILD_STATUS_SUCCESS = 0 , PI_PROGRAM_BUILD_STATUS_IN_PROGRESS = -3 }
enum _pi_program_binary_type { PI_PROGRAM_BINARY_TYPE_NONE = 0x0 , PI_PROGRAM_BINARY_TYPE_COMPILED_OBJECT = 0x1 , PI_PROGRAM_BINARY_TYPE_LIBRARY = 0x2 , PI_PROGRAM_BINARY_TYPE_EXECUTABLE = 0x4 }
enum _pi_device_type : pi_uint64 {
PI_DEVICE_TYPE_DEFAULT , PI_DEVICE_TYPE_ALL = 0xFFFFFFFF , PI_DEVICE_TYPE_CPU = (1 << 1) , PI_DEVICE_TYPE_GPU = (1 << 2) ,
PI_DEVICE_TYPE_ACC = (1 << 3) , PI_DEVICE_TYPE_CUSTOM = (1 << 4)
}
enum _pi_platform_backend {
PI_EXT_PLATFORM_BACKEND_UNKNOWN = 0 , PI_EXT_PLATFORM_BACKEND_LEVEL_ZERO = 1 , PI_EXT_PLATFORM_BACKEND_OPENCL = 2 , PI_EXT_PLATFORM_BACKEND_CUDA = 3 ,
PI_EXT_PLATFORM_BACKEND_HIP = 4 , PI_EXT_PLATFORM_BACKEND_ESIMD = 5 , PI_EXT_PLATFORM_BACKEND_NATIVE_CPU = 6
}
enum _pi_device_mem_cache_type { PI_DEVICE_MEM_CACHE_TYPE_NONE = 0x0 , PI_DEVICE_MEM_CACHE_TYPE_READ_ONLY_CACHE = 0x1 , PI_DEVICE_MEM_CACHE_TYPE_READ_WRITE_CACHE = 0x2 }
enum _pi_device_local_mem_type { PI_DEVICE_LOCAL_MEM_TYPE_LOCAL = 0x1 , PI_DEVICE_LOCAL_MEM_TYPE_GLOBAL = 0x2 }
enum _pi_device_info {
PI_DEVICE_INFO_TYPE = 0x1000 , PI_DEVICE_INFO_VENDOR_ID = 0x1001 , PI_DEVICE_INFO_MAX_COMPUTE_UNITS = 0x1002 , PI_DEVICE_INFO_MAX_WORK_ITEM_DIMENSIONS = 0x1003 ,
PI_DEVICE_INFO_MAX_WORK_ITEM_SIZES = 0x1005 , PI_DEVICE_INFO_MAX_WORK_GROUP_SIZE = 0x1004 , PI_DEVICE_INFO_SINGLE_FP_CONFIG = 0x101B , PI_DEVICE_INFO_HALF_FP_CONFIG = 0x1033 ,
PI_DEVICE_INFO_DOUBLE_FP_CONFIG = 0x1032 , PI_DEVICE_INFO_QUEUE_PROPERTIES = 0x102A , PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_CHAR = 0x1006 , PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_SHORT = 0x1007 ,
PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_INT = 0x1008 , PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_LONG = 0x1009 , PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_FLOAT = 0x100A , PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_DOUBLE = 0x100B ,
PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_HALF = 0x1034 , PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_CHAR = 0x1036 , PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_SHORT = 0x1037 , PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_INT = 0x1038 ,
PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_LONG = 0x1039 , PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_FLOAT = 0x103A , PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_DOUBLE = 0x103B , PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_HALF = 0x103C ,
PI_DEVICE_INFO_MAX_CLOCK_FREQUENCY = 0x100C , PI_DEVICE_INFO_ADDRESS_BITS = 0x100D , PI_DEVICE_INFO_MAX_MEM_ALLOC_SIZE = 0x1010 , PI_DEVICE_INFO_IMAGE_SUPPORT = 0x1016 ,
PI_DEVICE_INFO_MAX_READ_IMAGE_ARGS = 0x100E , PI_DEVICE_INFO_MAX_WRITE_IMAGE_ARGS = 0x100F , PI_DEVICE_INFO_IMAGE2D_MAX_WIDTH = 0x1011 , PI_DEVICE_INFO_IMAGE2D_MAX_HEIGHT = 0x1012 ,
PI_DEVICE_INFO_IMAGE3D_MAX_WIDTH = 0x1013 , PI_DEVICE_INFO_IMAGE3D_MAX_HEIGHT = 0x1014 , PI_DEVICE_INFO_IMAGE3D_MAX_DEPTH = 0x1015 , PI_DEVICE_INFO_IMAGE_MAX_BUFFER_SIZE = 0x1040 ,
PI_DEVICE_INFO_IMAGE_MAX_ARRAY_SIZE = 0x1041 , PI_DEVICE_INFO_MAX_SAMPLERS = 0x1018 , PI_DEVICE_INFO_MAX_PARAMETER_SIZE = 0x1017 , PI_DEVICE_INFO_MEM_BASE_ADDR_ALIGN = 0x1019 ,
PI_DEVICE_INFO_GLOBAL_MEM_CACHE_TYPE = 0x101C , PI_DEVICE_INFO_GLOBAL_MEM_CACHELINE_SIZE = 0x101D , PI_DEVICE_INFO_GLOBAL_MEM_CACHE_SIZE = 0x101E , PI_DEVICE_INFO_GLOBAL_MEM_SIZE = 0x101F ,
PI_DEVICE_INFO_MAX_CONSTANT_BUFFER_SIZE = 0x1020 , PI_DEVICE_INFO_MAX_CONSTANT_ARGS = 0x1021 , PI_DEVICE_INFO_LOCAL_MEM_TYPE = 0x1022 , PI_DEVICE_INFO_LOCAL_MEM_SIZE = 0x1023 ,
PI_DEVICE_INFO_ERROR_CORRECTION_SUPPORT = 0x1024 , PI_DEVICE_INFO_HOST_UNIFIED_MEMORY = 0x1035 , PI_DEVICE_INFO_PROFILING_TIMER_RESOLUTION = 0x1025 , PI_DEVICE_INFO_ENDIAN_LITTLE = 0x1026 ,
PI_DEVICE_INFO_AVAILABLE = 0x1027 , PI_DEVICE_INFO_COMPILER_AVAILABLE = 0x1028 , PI_DEVICE_INFO_LINKER_AVAILABLE = 0x103E , PI_DEVICE_INFO_EXECUTION_CAPABILITIES = 0x1029 ,
PI_DEVICE_INFO_QUEUE_ON_DEVICE_PROPERTIES = 0x104E , PI_DEVICE_INFO_QUEUE_ON_HOST_PROPERTIES = 0x102A , PI_DEVICE_INFO_BUILT_IN_KERNELS = 0x103F , PI_DEVICE_INFO_PLATFORM = 0x1031 ,
PI_DEVICE_INFO_REFERENCE_COUNT = 0x1047 , PI_DEVICE_INFO_IL_VERSION = 0x105B , PI_DEVICE_INFO_NAME = 0x102B , PI_DEVICE_INFO_VENDOR = 0x102C ,
PI_DEVICE_INFO_DRIVER_VERSION = 0x102D , PI_DEVICE_INFO_PROFILE = 0x102E , PI_DEVICE_INFO_VERSION = 0x102F , PI_DEVICE_INFO_OPENCL_C_VERSION = 0x103D ,
PI_DEVICE_INFO_EXTENSIONS = 0x1030 , PI_DEVICE_INFO_PRINTF_BUFFER_SIZE = 0x1049 , PI_DEVICE_INFO_PREFERRED_INTEROP_USER_SYNC = 0x1048 , PI_DEVICE_INFO_PARENT_DEVICE = 0x1042 ,
PI_DEVICE_INFO_PARTITION_PROPERTIES = 0x1044 , PI_DEVICE_INFO_PARTITION_MAX_SUB_DEVICES = 0x1043 , PI_DEVICE_INFO_PARTITION_AFFINITY_DOMAIN = 0x1045 , PI_DEVICE_INFO_PARTITION_TYPE = 0x1046 ,
PI_DEVICE_INFO_MAX_NUM_SUB_GROUPS = 0x105C , PI_DEVICE_INFO_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS = 0x105D , PI_DEVICE_INFO_SUB_GROUP_SIZES_INTEL = 0x4108 , PI_DEVICE_INFO_USM_HOST_SUPPORT = 0x4190 ,
PI_DEVICE_INFO_USM_DEVICE_SUPPORT = 0x4191 , PI_DEVICE_INFO_USM_SINGLE_SHARED_SUPPORT = 0x4192 , PI_DEVICE_INFO_USM_CROSS_SHARED_SUPPORT = 0x4193 , PI_DEVICE_INFO_USM_SYSTEM_SHARED_SUPPORT = 0x4194 ,
PI_DEVICE_INFO_UUID = 0x106A , PI_EXT_ONEAPI_DEVICE_INFO_IP_VERSION = 0x4250 , PI_DEVICE_INFO_DEVICE_ID = 0x4251 , PI_DEVICE_INFO_PCI_ADDRESS = 0x10020 ,
PI_DEVICE_INFO_GPU_EU_COUNT = 0x10021 , PI_DEVICE_INFO_GPU_EU_SIMD_WIDTH = 0x10022 , PI_DEVICE_INFO_GPU_SLICES = 0x10023 , PI_DEVICE_INFO_GPU_SUBSLICES_PER_SLICE = 0x10024 ,
PI_DEVICE_INFO_GPU_EU_COUNT_PER_SUBSLICE = 0x10025 , PI_DEVICE_INFO_MAX_MEM_BANDWIDTH = 0x10026 , PI_DEVICE_INFO_IMAGE_SRGB = 0x10027 , PI_DEVICE_INFO_BUILD_ON_SUBDEVICE = 0x10028 ,
PI_EXT_INTEL_DEVICE_INFO_FREE_MEMORY = 0x10029 , PI_EXT_INTEL_DEVICE_INFO_MEMORY_CLOCK_RATE = 0x10030 , PI_EXT_INTEL_DEVICE_INFO_MEMORY_BUS_WIDTH = 0x10031 , PI_EXT_INTEL_DEVICE_INFO_MAX_COMPUTE_QUEUE_INDICES = 0x10032 ,
PI_DEVICE_INFO_ATOMIC_64 = 0x10110 , PI_EXT_DEVICE_INFO_ATOMIC_MEMORY_ORDER_CAPABILITIES = 0x10111 , PI_EXT_DEVICE_INFO_ATOMIC_MEMORY_SCOPE_CAPABILITIES = 0x11000 , PI_DEVICE_INFO_GPU_HW_THREADS_PER_EU = 0x10112 ,
PI_DEVICE_INFO_BACKEND_VERSION = 0x10113 , PI_EXT_ONEAPI_DEVICE_INFO_BFLOAT16_MATH_FUNCTIONS = 0x1FFFF , PI_EXT_ONEAPI_DEVICE_INFO_MAX_GLOBAL_WORK_GROUPS = 0x20000 , PI_EXT_ONEAPI_DEVICE_INFO_MAX_WORK_GROUPS_1D = 0x20001 ,
PI_EXT_ONEAPI_DEVICE_INFO_MAX_WORK_GROUPS_2D = 0x20002 , PI_EXT_ONEAPI_DEVICE_INFO_MAX_WORK_GROUPS_3D = 0x20003 , PI_EXT_ONEAPI_DEVICE_INFO_CUDA_ASYNC_BARRIER = 0x20004 , PI_EXT_CODEPLAY_DEVICE_INFO_SUPPORTS_FUSION = 0x20005 ,
PI_EXT_DEVICE_INFO_ATOMIC_FENCE_ORDER_CAPABILITIES = 0x20006 , PI_EXT_DEVICE_INFO_ATOMIC_FENCE_SCOPE_CAPABILITIES = 0x20007 , PI_EXT_INTEL_DEVICE_INFO_MEM_CHANNEL_SUPPORT = 0x20008 , PI_EXT_CODEPLAY_DEVICE_INFO_MAX_REGISTERS_PER_WORK_GROUP = 0x20009 ,
PI_EXT_INTEL_DEVICE_INFO_ESIMD_SUPPORT = 0x2000A , PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_IMAGES_SUPPORT = 0x20100 , PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_IMAGES_SHARED_USM_SUPPORT = 0x20101 , PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_IMAGES_1D_USM_SUPPORT = 0x20102 ,
PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_IMAGES_2D_USM_SUPPORT = 0x20103 , PI_EXT_ONEAPI_DEVICE_INFO_IMAGE_PITCH_ALIGN = 0x20104 , PI_EXT_ONEAPI_DEVICE_INFO_MAX_IMAGE_LINEAR_WIDTH = 0x20105 , PI_EXT_ONEAPI_DEVICE_INFO_MAX_IMAGE_LINEAR_HEIGHT = 0x20106 ,
PI_EXT_ONEAPI_DEVICE_INFO_MAX_IMAGE_LINEAR_PITCH = 0x20107 , PI_EXT_ONEAPI_DEVICE_INFO_MIPMAP_SUPPORT = 0x20108 , PI_EXT_ONEAPI_DEVICE_INFO_MIPMAP_ANISOTROPY_SUPPORT = 0x20109 , PI_EXT_ONEAPI_DEVICE_INFO_MIPMAP_MAX_ANISOTROPY = 0x2010A ,
PI_EXT_ONEAPI_DEVICE_INFO_MIPMAP_LEVEL_REFERENCE_SUPPORT = 0x2010B , PI_EXT_ONEAPI_DEVICE_INFO_INTEROP_MEMORY_IMPORT_SUPPORT = 0x2010C , PI_EXT_ONEAPI_DEVICE_INFO_INTEROP_MEMORY_EXPORT_SUPPORT = 0x2010D , PI_EXT_ONEAPI_DEVICE_INFO_INTEROP_SEMAPHORE_IMPORT_SUPPORT = 0x2010E ,
PI_EXT_ONEAPI_DEVICE_INFO_INTEROP_SEMAPHORE_EXPORT_SUPPORT = 0x2010F , PI_EXT_ONEAPI_DEVICE_INFO_MATRIX_COMBINATIONS = 0x20110 , PI_EXT_ONEAPI_DEVICE_INFO_COMPONENT_DEVICES = 0x20111 , PI_EXT_ONEAPI_DEVICE_INFO_COMPOSITE_DEVICE = 0x20112 ,
PI_EXT_ONEAPI_DEVICE_INFO_COMMAND_BUFFER_SUPPORT = 0x20113 , PI_EXT_ONEAPI_DEVICE_INFO_COMMAND_BUFFER_UPDATE_SUPPORT = 0x20114 , PI_EXT_ONEAPI_DEVICE_INFO_CUBEMAP_SUPPORT = 0x20115 , PI_EXT_ONEAPI_DEVICE_INFO_CUBEMAP_SEAMLESS_FILTERING_SUPPORT = 0x20116 ,
PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_1D_USM = 0x20117 , PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_1D = 0x20118 , PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_2D_USM = 0x20119 , PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_2D = 0x2011A ,
PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_3D_USM = 0x2011B , PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_3D = 0x2011C
}
enum _pi_program_info {
PI_PROGRAM_INFO_REFERENCE_COUNT = 0x1160 , PI_PROGRAM_INFO_CONTEXT = 0x1161 , PI_PROGRAM_INFO_NUM_DEVICES = 0x1162 , PI_PROGRAM_INFO_DEVICES = 0x1163 ,
PI_PROGRAM_INFO_SOURCE = 0x1164 , PI_PROGRAM_INFO_BINARY_SIZES = 0x1165 , PI_PROGRAM_INFO_BINARIES = 0x1166 , PI_PROGRAM_INFO_NUM_KERNELS = 0x1167 ,
PI_PROGRAM_INFO_KERNEL_NAMES = 0x1168
}
enum _pi_context_info {
PI_CONTEXT_INFO_DEVICES = 0x1081 , PI_CONTEXT_INFO_PLATFORM = 0x1084 , PI_CONTEXT_INFO_NUM_DEVICES = 0x1083 , PI_CONTEXT_INFO_PROPERTIES = 0x1082 ,
PI_CONTEXT_INFO_REFERENCE_COUNT = 0x1080 , PI_EXT_CONTEXT_INFO_ATOMIC_MEMORY_ORDER_CAPABILITIES = 0x10010 , PI_EXT_CONTEXT_INFO_ATOMIC_MEMORY_SCOPE_CAPABILITIES = 0x10011 , PI_EXT_CONTEXT_INFO_ATOMIC_FENCE_ORDER_CAPABILITIES = 0x10012 ,
PI_EXT_CONTEXT_INFO_ATOMIC_FENCE_SCOPE_CAPABILITIES = 0x10013 , PI_EXT_ONEAPI_CONTEXT_INFO_USM_FILL2D_SUPPORT = 0x30000 , PI_EXT_ONEAPI_CONTEXT_INFO_USM_MEMSET2D_SUPPORT = 0x30001 , PI_EXT_ONEAPI_CONTEXT_INFO_USM_MEMCPY2D_SUPPORT = 0x30002
}
enum _pi_queue_info {
PI_QUEUE_INFO_CONTEXT = 0x1090 , PI_QUEUE_INFO_DEVICE = 0x1091 , PI_QUEUE_INFO_DEVICE_DEFAULT = 0x1095 , PI_QUEUE_INFO_PROPERTIES = 0x1093 ,
PI_QUEUE_INFO_REFERENCE_COUNT = 0x1092 , PI_QUEUE_INFO_SIZE = 0x1094 , PI_EXT_ONEAPI_QUEUE_INFO_EMPTY = 0x2096
}
enum _pi_kernel_info {
PI_KERNEL_INFO_FUNCTION_NAME = 0x1190 , PI_KERNEL_INFO_NUM_ARGS = 0x1191 , PI_KERNEL_INFO_REFERENCE_COUNT = 0x1192 , PI_KERNEL_INFO_CONTEXT = 0x1193 ,
PI_KERNEL_INFO_PROGRAM = 0x1194 , PI_KERNEL_INFO_ATTRIBUTES = 0x1195
}
enum _pi_kernel_group_info {
PI_KERNEL_GROUP_INFO_GLOBAL_WORK_SIZE = 0x11B5 , PI_KERNEL_GROUP_INFO_WORK_GROUP_SIZE = 0x11B0 , PI_KERNEL_GROUP_INFO_COMPILE_WORK_GROUP_SIZE = 0x11B1 , PI_KERNEL_GROUP_INFO_LOCAL_MEM_SIZE = 0x11B2 ,
PI_KERNEL_GROUP_INFO_PREFERRED_WORK_GROUP_SIZE_MULTIPLE = 0x11B3 , PI_KERNEL_GROUP_INFO_PRIVATE_MEM_SIZE = 0x11B4 , PI_KERNEL_GROUP_INFO_NUM_REGS = 0x10112
}
enum _pi_image_info {
PI_IMAGE_INFO_FORMAT = 0x1110 , PI_IMAGE_INFO_ELEMENT_SIZE = 0x1111 , PI_IMAGE_INFO_ROW_PITCH = 0x1112 , PI_IMAGE_INFO_SLICE_PITCH = 0x1113 ,
PI_IMAGE_INFO_WIDTH = 0x1114 , PI_IMAGE_INFO_HEIGHT = 0x1115 , PI_IMAGE_INFO_DEPTH = 0x1116
}
enum _pi_kernel_sub_group_info { PI_KERNEL_MAX_SUB_GROUP_SIZE = 0x2033 , PI_KERNEL_MAX_NUM_SUB_GROUPS = 0x11B9 , PI_KERNEL_COMPILE_NUM_SUB_GROUPS = 0x11BA , PI_KERNEL_COMPILE_SUB_GROUP_SIZE_INTEL = 0x410A }
enum _pi_event_info {
PI_EVENT_INFO_COMMAND_QUEUE = 0x11D0 , PI_EVENT_INFO_CONTEXT = 0x11D4 , PI_EVENT_INFO_COMMAND_TYPE = 0x11D1 , PI_EVENT_INFO_COMMAND_EXECUTION_STATUS = 0x11D3 ,
PI_EVENT_INFO_REFERENCE_COUNT = 0x11D2
}
enum _pi_command_type {
PI_COMMAND_TYPE_NDRANGE_KERNEL = 0x11F0 , PI_COMMAND_TYPE_MEM_BUFFER_READ = 0x11F3 , PI_COMMAND_TYPE_MEM_BUFFER_WRITE = 0x11F4 , PI_COMMAND_TYPE_MEM_BUFFER_COPY = 0x11F5 ,
PI_COMMAND_TYPE_MEM_BUFFER_MAP = 0x11FB , PI_COMMAND_TYPE_MEM_BUFFER_UNMAP = 0x11FD , PI_COMMAND_TYPE_MEM_BUFFER_READ_RECT = 0x1201 , PI_COMMAND_TYPE_MEM_BUFFER_WRITE_RECT = 0x1202 ,
PI_COMMAND_TYPE_MEM_BUFFER_COPY_RECT = 0x1203 , PI_COMMAND_TYPE_USER = 0x1204 , PI_COMMAND_TYPE_MEM_BUFFER_FILL = 0x1207 , PI_COMMAND_TYPE_IMAGE_READ = 0x11F6 ,
PI_COMMAND_TYPE_IMAGE_WRITE = 0x11F7 , PI_COMMAND_TYPE_IMAGE_COPY = 0x11F8 , PI_COMMAND_TYPE_NATIVE_KERNEL = 0x11F2 , PI_COMMAND_TYPE_COPY_BUFFER_TO_IMAGE = 0x11FA ,
PI_COMMAND_TYPE_COPY_IMAGE_TO_BUFFER = 0x11F9 , PI_COMMAND_TYPE_MAP_IMAGE = 0x11FC , PI_COMMAND_TYPE_MARKER = 0x11FE , PI_COMMAND_TYPE_ACQUIRE_GL_OBJECTS = 0x11FF ,
PI_COMMAND_TYPE_RELEASE_GL_OBJECTS = 0x1200 , PI_COMMAND_TYPE_BARRIER = 0x1205 , PI_COMMAND_TYPE_MIGRATE_MEM_OBJECTS = 0x1206 , PI_COMMAND_TYPE_FILL_IMAGE = 0x1208 ,
PI_COMMAND_TYPE_SVM_FREE = 0x1209 , PI_COMMAND_TYPE_SVM_MEMCPY = 0x120A , PI_COMMAND_TYPE_SVM_MEMFILL = 0x120B , PI_COMMAND_TYPE_SVM_MAP = 0x120C ,
PI_COMMAND_TYPE_SVM_UNMAP = 0x120D , PI_COMMAND_TYPE_EXT_COMMAND_BUFFER = 0x12A8 , PI_COMMAND_TYPE_DEVICE_GLOBAL_VARIABLE_READ = 0x418E , PI_COMMAND_TYPE_DEVICE_GLOBAL_VARIABLE_WRITE = 0x418F
}
enum _pi_mem_type {
PI_MEM_TYPE_BUFFER = 0x10F0 , PI_MEM_TYPE_IMAGE2D = 0x10F1 , PI_MEM_TYPE_IMAGE3D = 0x10F2 , PI_MEM_TYPE_IMAGE2D_ARRAY = 0x10F3 ,
PI_MEM_TYPE_IMAGE1D = 0x10F4 , PI_MEM_TYPE_IMAGE1D_ARRAY = 0x10F5 , PI_MEM_TYPE_IMAGE1D_BUFFER = 0x10F6 , PI_MEM_TYPE_IMAGE_CUBEMAP = 0x10F7
}
enum _pi_mem_advice {
PI_MEM_ADVICE_RESET = 0 , PI_MEM_ADVICE_CUDA_SET_READ_MOSTLY = 1 << 0 , PI_MEM_ADVICE_CUDA_UNSET_READ_MOSTLY = 1 << 1 , PI_MEM_ADVICE_CUDA_SET_PREFERRED_LOCATION = 1 << 2 ,
PI_MEM_ADVICE_CUDA_UNSET_PREFERRED_LOCATION = 1 << 3 , PI_MEM_ADVICE_CUDA_SET_ACCESSED_BY = 1 << 4 , PI_MEM_ADVICE_CUDA_UNSET_ACCESSED_BY = 1 << 5 , PI_MEM_ADVICE_CUDA_SET_PREFERRED_LOCATION_HOST = 1 << 6 ,
PI_MEM_ADVICE_CUDA_UNSET_PREFERRED_LOCATION_HOST = 1 << 7 , PI_MEM_ADVICE_CUDA_SET_ACCESSED_BY_HOST = 1 << 8 , PI_MEM_ADVICE_CUDA_UNSET_ACCESSED_BY_HOST = 1 << 9 , PI_MEM_ADVICE_HIP_SET_COARSE_GRAINED = 1 << 10 ,
PI_MEM_ADVICE_HIP_UNSET_COARSE_GRAINED = 1 << 11 , PI_MEM_ADVICE_UNKNOWN = 0x7FFFFFFF
}
enum _pi_image_channel_order {
PI_IMAGE_CHANNEL_ORDER_A = 0x10B1 , PI_IMAGE_CHANNEL_ORDER_R = 0x10B0 , PI_IMAGE_CHANNEL_ORDER_RG = 0x10B2 , PI_IMAGE_CHANNEL_ORDER_RA = 0x10B3 ,
PI_IMAGE_CHANNEL_ORDER_RGB = 0x10B4 , PI_IMAGE_CHANNEL_ORDER_RGBA = 0x10B5 , PI_IMAGE_CHANNEL_ORDER_BGRA = 0x10B6 , PI_IMAGE_CHANNEL_ORDER_ARGB = 0x10B7 ,
PI_IMAGE_CHANNEL_ORDER_ABGR = 0x10C3 , PI_IMAGE_CHANNEL_ORDER_INTENSITY = 0x10B8 , PI_IMAGE_CHANNEL_ORDER_LUMINANCE = 0x10B9 , PI_IMAGE_CHANNEL_ORDER_Rx = 0x10BA ,
PI_IMAGE_CHANNEL_ORDER_RGx = 0x10BB , PI_IMAGE_CHANNEL_ORDER_RGBx = 0x10BC , PI_IMAGE_CHANNEL_ORDER_sRGBA = 0x10C1
}
enum _pi_image_channel_type {
PI_IMAGE_CHANNEL_TYPE_SNORM_INT8 = 0x10D0 , PI_IMAGE_CHANNEL_TYPE_SNORM_INT16 = 0x10D1 , PI_IMAGE_CHANNEL_TYPE_UNORM_INT8 = 0x10D2 , PI_IMAGE_CHANNEL_TYPE_UNORM_INT16 = 0x10D3 ,
PI_IMAGE_CHANNEL_TYPE_UNORM_SHORT_565 = 0x10D4 , PI_IMAGE_CHANNEL_TYPE_UNORM_SHORT_555 = 0x10D5 , PI_IMAGE_CHANNEL_TYPE_UNORM_INT_101010 = 0x10D6 , PI_IMAGE_CHANNEL_TYPE_SIGNED_INT8 = 0x10D7 ,
PI_IMAGE_CHANNEL_TYPE_SIGNED_INT16 = 0x10D8 , PI_IMAGE_CHANNEL_TYPE_SIGNED_INT32 = 0x10D9 , PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT8 = 0x10DA , PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT16 = 0x10DB ,
PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT32 = 0x10DC , PI_IMAGE_CHANNEL_TYPE_HALF_FLOAT = 0x10DD , PI_IMAGE_CHANNEL_TYPE_FLOAT = 0x10DE
}
enum _pi_image_copy_flags { PI_IMAGE_COPY_HOST_TO_DEVICE = 0 , PI_IMAGE_COPY_DEVICE_TO_HOST = 1 , PI_IMAGE_COPY_DEVICE_TO_DEVICE = 2 }
enum _pi_buffer_create_type { PI_BUFFER_CREATE_TYPE_REGION = 0x1220 }
enum _pi_sampler_info {
PI_SAMPLER_INFO_REFERENCE_COUNT = 0x1150 , PI_SAMPLER_INFO_CONTEXT = 0x1151 , PI_SAMPLER_INFO_NORMALIZED_COORDS = 0x1152 , PI_SAMPLER_INFO_ADDRESSING_MODE = 0x1153 ,
PI_SAMPLER_INFO_FILTER_MODE = 0x1154 , PI_SAMPLER_INFO_MIP_FILTER_MODE = 0x1155 , PI_SAMPLER_INFO_LOD_MIN = 0x1156 , PI_SAMPLER_INFO_LOD_MAX = 0x1157
}
enum _pi_sampler_addressing_mode {
PI_SAMPLER_ADDRESSING_MODE_MIRRORED_REPEAT = 0x1134 , PI_SAMPLER_ADDRESSING_MODE_REPEAT = 0x1133 , PI_SAMPLER_ADDRESSING_MODE_CLAMP_TO_EDGE = 0x1131 , PI_SAMPLER_ADDRESSING_MODE_CLAMP = 0x1132 ,
PI_SAMPLER_ADDRESSING_MODE_NONE = 0x1130
}
enum _pi_sampler_filter_mode { PI_SAMPLER_FILTER_MODE_NEAREST = 0x1140 , PI_SAMPLER_FILTER_MODE_LINEAR = 0x1141 }
enum _pi_sampler_cubemap_filter_mode { PI_SAMPLER_CUBEMAP_FILTER_MODE_DISJOINTED = 0x1142 , PI_SAMPLER_CUBEMAP_FILTER_MODE_SEAMLESS = 0x1143 }
enum _pi_profiling_info { PI_PROFILING_INFO_COMMAND_QUEUED = 0x1280 , PI_PROFILING_INFO_COMMAND_SUBMIT = 0x1281 , PI_PROFILING_INFO_COMMAND_START = 0x1282 , PI_PROFILING_INFO_COMMAND_END = 0x1283 }
enum _pi_kernel_cache_config { PI_EXT_KERNEL_EXEC_INFO_CACHE_DEFAULT = 0x0 , PI_EXT_KERNEL_EXEC_INFO_CACHE_LARGE_SLM = 0x1 , PI_EXT_KERNEL_EXEC_INFO_CACHE_LARGE_DATA = 0x2 }
enum pi_property_type { PI_PROPERTY_TYPE_UNKNOWN , PI_PROPERTY_TYPE_UINT32 , PI_PROPERTY_TYPE_BYTE_ARRAY , PI_PROPERTY_TYPE_STRING }
enum _pi_mem_info { PI_MEM_CONTEXT = 0x1106 , PI_MEM_SIZE = 0x1102 }
enum _pi_peer_attr { PI_PEER_ACCESS_SUPPORTED , PI_PEER_ATOMICS_SUPPORTED }
enum _pi_kernel_exec_info { PI_USM_INDIRECT_ACCESS , PI_USM_PTRS = 0x4203 , PI_EXT_KERNEL_EXEC_INFO_CACHE_CONFIG = 0x4204 }
enum _pi_mem_obj_access { PI_ACCESS_READ_WRITE = PI_BIT(0) , PI_ACCESS_WRITE_ONLY = PI_BIT(1) , PI_ACCESS_READ_ONLY = PI_BIT(2) }
enum _pi_mem_obj_property_type { PI_KERNEL_ARG_MEM_OBJ_ACCESS = 27 , PI_ENUM_FORCE_UINT32 = 0x7fffffff }
enum _pi_usm_capability_query {
PI_USM_HOST_SUPPORT = 0x4190 , PI_USM_DEVICE_SUPPORT = 0x4191 , PI_USM_SINGLE_SHARED_SUPPORT = 0x4192 , PI_USM_CROSS_SHARED_SUPPORT = 0x4193 ,
PI_USM_SYSTEM_SHARED_SUPPORT = 0x4194
}
enum _pi_usm_capabilities : pi_bitfield { PI_USM_ACCESS = (1 << 0) , PI_USM_ATOMIC_ACCESS = (1 << 1) , PI_USM_CONCURRENT_ACCESS = (1 << 2) , PI_USM_CONCURRENT_ATOMIC_ACCESS = (1 << 3) }
enum _pi_mem_alloc_info { PI_MEM_ALLOC_TYPE = 0x419A , PI_MEM_ALLOC_BASE_PTR = 0x419B , PI_MEM_ALLOC_SIZE = 0x419C , PI_MEM_ALLOC_DEVICE = 0x419D }
enum _pi_usm_type { PI_MEM_TYPE_UNKNOWN = 0x4196 , PI_MEM_TYPE_HOST = 0x4197 , PI_MEM_TYPE_DEVICE = 0x4198 , PI_MEM_TYPE_SHARED = 0x4199 }
enum _pi_usm_migration_flags : pi_bitfield { PI_USM_MIGRATION_TBD0 = (1 << 0) }
enum pi_ext_structure_type { PI_EXT_STRUCTURE_TYPE_COMMAND_BUFFER_DESC = 0 }
enum _pi_sanitize_type { _PI_SANITIZE_TYPE_NONE = 0x0 , _PI_SANITIZE_TYPE_ADDRESS = 0x1 , _PI_SANITIZE_TYPE_MEMORY = 0x2 , _PI_SANITIZE_TYPE_THREAD = 0x3 }
Functions
pi_result piPluginInit (pi_plugin *plugin_info)
pi_result piPlatformsGet (pi_uint32 num_entries, pi_platform *platforms, pi_uint32 *num_platforms)
pi_result piPlatformGetInfo (pi_platform platform, pi_platform_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
pi_result piextPlatformGetNativeHandle (pi_platform platform, pi_native_handle *nativeHandle)
Gets the native handle of a PI platform object.
pi_result piextPlatformCreateWithNativeHandle (pi_native_handle nativeHandle, pi_platform *platform)
Creates PI platform object from a native handle.
pi_result piDevicesGet (pi_platform platform, pi_device_type device_type, pi_uint32 num_entries, pi_device *devices, pi_uint32 *num_devices)
pi_result piextEnablePeerAccess (pi_device command_device, pi_device peer_device)
pi_result piextDisablePeerAccess (pi_device command_device, pi_device peer_device)
pi_result piextPeerAccessGetInfo (pi_device command_device, pi_device peer_device, pi_peer_attr attr, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
pi_result piDeviceGetInfo (pi_device device, pi_device_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
Returns requested info for provided native device Return PI_DEVICE_INFO_EXTENSION_DEVICELIB_ASSERT for PI_DEVICE_INFO_EXTENSIONS query when the device supports native asserts.
pi_result piDeviceRetain (pi_device device)
pi_result piDeviceRelease (pi_device device)
pi_result piDevicePartition (pi_device device, const pi_device_partition_property *properties, pi_uint32 num_devices, pi_device *out_devices, pi_uint32 *out_num_devices)
pi_result piextDeviceGetNativeHandle (pi_device device, pi_native_handle *nativeHandle)
Gets the native handle of a PI device object.
pi_result piextDeviceCreateWithNativeHandle (pi_native_handle nativeHandle, pi_platform platform, pi_device *device)
Creates PI device object from a native handle.
pi_result piextDeviceSelectBinary (pi_device device, pi_device_binary *binaries, pi_uint32 num_binaries, pi_uint32 *selected_binary_ind)
Selects the most appropriate device binary based on runtime information and the IR characteristics.
pi_result piextGetDeviceFunctionPointer (pi_device device, pi_program program, const char *function_name, pi_uint64 *function_pointer_ret)
Retrieves a device function pointer to a user-defined function.
pi_result piextGetGlobalVariablePointer (pi_device Device, pi_program Program, const char *GlobalVariableName, size_t *GlobalVariableSize, void **GlobalVariablePointerRet)
pi_result piContextCreate (const pi_context_properties *properties, pi_uint32 num_devices, const pi_device *devices, void(*pfn_notify)(const char *errinfo, const void *private_info, size_t cb, void *user_data), void *user_data, pi_context *ret_context)
pi_result piContextGetInfo (pi_context context, pi_context_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
pi_result piContextRetain (pi_context context)
pi_result piContextRelease (pi_context context)
pi_result piextContextSetExtendedDeleter (pi_context context, pi_context_extended_deleter func, void *user_data)
pi_result piextContextGetNativeHandle (pi_context context, pi_native_handle *nativeHandle)
Gets the native handle of a PI context object.
pi_result piextContextCreateWithNativeHandle (pi_native_handle nativeHandle, pi_uint32 numDevices, const pi_device *devices, bool pluginOwnsNativeHandle, pi_context *context)
Creates PI context object from a native handle.
pi_result piQueueCreate (pi_context context, pi_device device, pi_queue_properties properties, pi_queue *queue)
pi_result piextQueueCreate (pi_context context, pi_device device, pi_queue_properties *properties, pi_queue *queue)
pi_result piQueueGetInfo (pi_queue command_queue, pi_queue_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
pi_result piQueueRetain (pi_queue command_queue)
pi_result piQueueRelease (pi_queue command_queue)
pi_result piQueueFinish (pi_queue command_queue)
pi_result piQueueFlush (pi_queue command_queue)
pi_result piextQueueGetNativeHandle (pi_queue queue, pi_native_handle *nativeHandle, int32_t *nativeHandleDesc)
Gets the native handle of a PI queue object.
pi_result piextQueueCreateWithNativeHandle (pi_native_handle nativeHandle, int32_t nativeHandleDesc, pi_context context, pi_device device, bool pluginOwnsNativeHandle, pi_queue_properties *Properties, pi_queue *queue)
Creates PI queue object from a native handle.
pi_result piMemBufferCreate (pi_context context, pi_mem_flags flags, size_t size, void *host_ptr, pi_mem *ret_mem, const pi_mem_properties *properties=nullptr)
pi_result piMemImageCreate (pi_context context, pi_mem_flags flags, const pi_image_format *image_format, const pi_image_desc *image_desc, void *host_ptr, pi_mem *ret_mem)
pi_result piMemGetInfo (pi_mem mem, pi_mem_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
pi_result piMemImageGetInfo (pi_mem image, pi_image_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
pi_result piMemRetain (pi_mem mem)
pi_result piMemRelease (pi_mem mem)
pi_result piMemBufferPartition (pi_mem buffer, pi_mem_flags flags, pi_buffer_create_type buffer_create_type, void *buffer_create_info, pi_mem *ret_mem)
pi_result piextMemGetNativeHandle (pi_mem mem, pi_device dev, pi_native_handle *nativeHandle)
Gets the native handle of a PI mem object.
pi_result piextMemCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, bool ownNativeHandle, pi_mem *mem)
Creates PI mem object from a native handle.
pi_result piextMemImageCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, bool ownNativeHandle, const pi_image_format *ImageFormat, const pi_image_desc *ImageDesc, pi_mem *img)
Creates PI image object from a native handle.
pi_result piProgramCreate (pi_context context, const void *il, size_t length, pi_program *res_program)
pi_result piProgramCreateWithBinary (pi_context context, pi_uint32 num_devices, const pi_device *device_list, const size_t *lengths, const unsigned char **binaries, size_t num_metadata_entries, const pi_device_binary_property *metadata, pi_int32 *binary_status, pi_program *ret_program)
Creates a PI program for a context and loads the given binary into it.
pi_result piProgramGetInfo (pi_program program, pi_program_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
pi_result piProgramLink (pi_context context, pi_uint32 num_devices, const pi_device *device_list, const char *options, pi_uint32 num_input_programs, const pi_program *input_programs, void(*pfn_notify)(pi_program program, void *user_data), void *user_data, pi_program *ret_program)
pi_result piProgramCompile (pi_program program, pi_uint32 num_devices, const pi_device *device_list, const char *options, pi_uint32 num_input_headers, const pi_program *input_headers, const char **header_include_names, void(*pfn_notify)(pi_program program, void *user_data), void *user_data)
pi_result piProgramBuild (pi_program program, pi_uint32 num_devices, const pi_device *device_list, const char *options, void(*pfn_notify)(pi_program program, void *user_data), void *user_data)
pi_result piProgramGetBuildInfo (pi_program program, pi_device device, _pi_program_build_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
pi_result piProgramRetain (pi_program program)
pi_result piProgramRelease (pi_program program)
pi_result piextProgramSetSpecializationConstant (pi_program prog, pi_uint32 spec_id, size_t spec_size, const void *spec_value)
Sets a specialization constant to a specific value.
pi_result piextProgramGetNativeHandle (pi_program program, pi_native_handle *nativeHandle)
Gets the native handle of a PI program object.
pi_result piextProgramCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, bool pluginOwnsNativeHandle, pi_program *program)
Creates PI program object from a native handle.
pi_result piKernelCreate (pi_program program, const char *kernel_name, pi_kernel *ret_kernel)
pi_result piKernelSetArg (pi_kernel kernel, pi_uint32 arg_index, size_t arg_size, const void *arg_value)
pi_result piKernelGetInfo (pi_kernel kernel, pi_kernel_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
pi_result piKernelGetGroupInfo (pi_kernel kernel, pi_device device, pi_kernel_group_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
pi_result piKernelGetSubGroupInfo (pi_kernel kernel, pi_device device, pi_kernel_sub_group_info param_name, size_t input_value_size, const void *input_value, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
API to query information from the sub-group from a kernel.
pi_result piKernelRetain (pi_kernel kernel)
pi_result piKernelRelease (pi_kernel kernel)
pi_result piextKernelSetArgPointer (pi_kernel kernel, pi_uint32 arg_index, size_t arg_size, const void *arg_value)
Sets up pointer arguments for CL kernels.
pi_result piKernelSetExecInfo (pi_kernel kernel, pi_kernel_exec_info value_name, size_t param_value_size, const void *param_value)
API to set attributes controlling kernel execution.
pi_result piextKernelCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, pi_program program, bool pluginOwnsNativeHandle, pi_kernel *kernel)
Creates PI kernel object from a native handle.
pi_result piextKernelGetNativeHandle (pi_kernel kernel, pi_native_handle *nativeHandle)
Gets the native handle of a PI kernel object.
pi_result piextKernelSuggestMaxCooperativeGroupCount (pi_kernel kernel, size_t local_work_size, size_t dynamic_shared_memory_size, pi_uint32 *group_count_ret)
Gets the max work group count for a cooperative kernel.
pi_result piEventCreate (pi_context context, pi_event *ret_event)
Create PI event object in a signalled/completed state.
pi_result piEventGetInfo (pi_event event, pi_event_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
pi_result piEventGetProfilingInfo (pi_event event, pi_profiling_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
pi_result piEventsWait (pi_uint32 num_events, const pi_event *event_list)
pi_result piEventSetCallback (pi_event event, pi_int32 command_exec_callback_type, void(*pfn_notify)(pi_event event, pi_int32 event_command_status, void *user_data), void *user_data)
pi_result piEventSetStatus (pi_event event, pi_int32 execution_status)
pi_result piEventRetain (pi_event event)
pi_result piEventRelease (pi_event event)
pi_result piextEventGetNativeHandle (pi_event event, pi_native_handle *nativeHandle)
Gets the native handle of a PI event object.
pi_result piextEventCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, bool ownNativeHandle, pi_event *event)
Creates PI event object from a native handle.
pi_result piSamplerCreate (pi_context context, const pi_sampler_properties *sampler_properties, pi_sampler *result_sampler)
pi_result piSamplerGetInfo (pi_sampler sampler, pi_sampler_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
pi_result piSamplerRetain (pi_sampler sampler)
pi_result piSamplerRelease (pi_sampler sampler)
pi_result piEnqueueKernelLaunch (pi_queue queue, pi_kernel kernel, pi_uint32 work_dim, const size_t *global_work_offset, const size_t *global_work_size, const size_t *local_work_size, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
pi_result piextEnqueueCooperativeKernelLaunch (pi_queue queue, pi_kernel kernel, pi_uint32 work_dim, const size_t *global_work_offset, const size_t *global_work_size, const size_t *local_work_size, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
pi_result piEnqueueEventsWait (pi_queue command_queue, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
pi_result piEnqueueEventsWaitWithBarrier (pi_queue command_queue, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
pi_result piEnqueueMemBufferRead (pi_queue queue, pi_mem buffer, pi_bool blocking_read, size_t offset, size_t size, void *ptr, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
pi_result piEnqueueMemBufferReadRect (pi_queue command_queue, pi_mem buffer, pi_bool blocking_read, pi_buff_rect_offset buffer_offset, pi_buff_rect_offset host_offset, pi_buff_rect_region region, size_t buffer_row_pitch, size_t buffer_slice_pitch, size_t host_row_pitch, size_t host_slice_pitch, void *ptr, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
pi_result piEnqueueMemBufferWrite (pi_queue command_queue, pi_mem buffer, pi_bool blocking_write, size_t offset, size_t size, const void *ptr, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
pi_result piEnqueueMemBufferWriteRect (pi_queue command_queue, pi_mem buffer, pi_bool blocking_write, pi_buff_rect_offset buffer_offset, pi_buff_rect_offset host_offset, pi_buff_rect_region region, size_t buffer_row_pitch, size_t buffer_slice_pitch, size_t host_row_pitch, size_t host_slice_pitch, const void *ptr, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
pi_result piEnqueueMemBufferCopy (pi_queue command_queue, pi_mem src_buffer, pi_mem dst_buffer, size_t src_offset, size_t dst_offset, size_t size, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
pi_result piEnqueueMemBufferCopyRect (pi_queue command_queue, pi_mem src_buffer, pi_mem dst_buffer, pi_buff_rect_offset src_origin, pi_buff_rect_offset dst_origin, pi_buff_rect_region region, size_t src_row_pitch, size_t src_slice_pitch, size_t dst_row_pitch, size_t dst_slice_pitch, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
pi_result piEnqueueMemBufferFill (pi_queue command_queue, pi_mem buffer, const void *pattern, size_t pattern_size, size_t offset, size_t size, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
pi_result piEnqueueMemImageRead (pi_queue command_queue, pi_mem image, pi_bool blocking_read, pi_image_offset origin, pi_image_region region, size_t row_pitch, size_t slice_pitch, void *ptr, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
pi_result piEnqueueMemImageWrite (pi_queue command_queue, pi_mem image, pi_bool blocking_write, pi_image_offset origin, pi_image_region region, size_t input_row_pitch, size_t input_slice_pitch, const void *ptr, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
pi_result piEnqueueMemImageCopy (pi_queue command_queue, pi_mem src_image, pi_mem dst_image, pi_image_offset src_origin, pi_image_offset dst_origin, pi_image_region region, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
pi_result piEnqueueMemImageFill (pi_queue command_queue, pi_mem image, const void *fill_color, const size_t *origin, const size_t *region, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
pi_result piEnqueueMemBufferMap (pi_queue command_queue, pi_mem buffer, pi_bool blocking_map, pi_map_flags map_flags, size_t offset, size_t size, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event, void **ret_map)
pi_result piEnqueueMemUnmap (pi_queue command_queue, pi_mem memobj, void *mapped_ptr, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
pi_result piextKernelSetArgMemObj (pi_kernel kernel, pi_uint32 arg_index, const pi_mem_obj_property *arg_properties, const pi_mem *arg_value)
pi_result piextKernelSetArgSampler (pi_kernel kernel, pi_uint32 arg_index, const pi_sampler *arg_value)
pi_result piextUSMHostAlloc (void **result_ptr, pi_context context, pi_usm_mem_properties *properties, size_t size, pi_uint32 alignment)
Allocates host memory accessible by the device.
pi_result piextUSMDeviceAlloc (void **result_ptr, pi_context context, pi_device device, pi_usm_mem_properties *properties, size_t size, pi_uint32 alignment)
Allocates device memory.
pi_result piextUSMSharedAlloc (void **result_ptr, pi_context context, pi_device device, pi_usm_mem_properties *properties, size_t size, pi_uint32 alignment)
Allocates memory accessible on both host and device.
pi_result piextUSMPitchedAlloc (void **result_ptr, size_t *result_pitch, pi_context context, pi_device device, pi_usm_mem_properties *properties, size_t width_in_bytes, size_t height, unsigned int element_size_bytes)
Allocates memory accessible on device.
pi_result piextUSMFree (pi_context context, void *ptr)
Indicates that the allocated USM memory is no longer needed on the runtime side.
pi_result piextUSMEnqueueFill (pi_queue queue, void *ptr, const void *pattern, size_t patternSize, size_t count, pi_uint32 num_events_in_waitlist, const pi_event *events_waitlist, pi_event *event)
USM Fill API.
pi_result piextUSMEnqueueMemcpy (pi_queue queue, pi_bool blocking, void *dst_ptr, const void *src_ptr, size_t size, pi_uint32 num_events_in_waitlist, const pi_event *events_waitlist, pi_event *event)
USM Memcpy API.
pi_result piextUSMEnqueuePrefetch (pi_queue queue, const void *ptr, size_t size, pi_usm_migration_flags flags, pi_uint32 num_events_in_waitlist, const pi_event *events_waitlist, pi_event *event)
Hint to migrate memory to the device.
pi_result piextUSMEnqueueMemAdvise (pi_queue queue, const void *ptr, size_t length, pi_mem_advice advice, pi_event *event)
USM Memadvise API.
pi_result piextUSMGetMemAllocInfo (pi_context context, const void *ptr, pi_mem_alloc_info param_name, size_t param_value_size, void *param_value, size_t *param_value_size_ret)
API to query information about USM allocated pointers Valid Queries: PI_MEM_ALLOC_TYPE returns host/device/shared pi_host_usm value PI_MEM_ALLOC_BASE_PTR returns the base ptr of an allocation if the queried pointer fell inside an allocation.
pi_result piextUSMEnqueueFill2D (pi_queue queue, void *ptr, size_t pitch, size_t pattern_size, const void *pattern, size_t width, size_t height, pi_uint32 num_events_in_waitlist, const pi_event *events_waitlist, pi_event *event)
USM 2D fill API.
pi_result piextUSMEnqueueMemset2D (pi_queue queue, void *ptr, size_t pitch, int value, size_t width, size_t height, pi_uint32 num_events_in_waitlist, const pi_event *events_waitlist, pi_event *event)
USM 2D Memset API.
pi_result piextUSMEnqueueMemcpy2D (pi_queue queue, pi_bool blocking, void *dst_ptr, size_t dst_pitch, const void *src_ptr, size_t src_pitch, size_t width, size_t height, pi_uint32 num_events_in_waitlist, const pi_event *events_waitlist, pi_event *event)
USM 2D Memcpy API.
pi_result piextUSMImport (const void *ptr, size_t size, pi_context context)
Import host system memory into USM.
pi_result piextUSMRelease (const void *ptr, pi_context context)
Release host system memory from USM.
pi_result piextEnqueueDeviceGlobalVariableWrite (pi_queue queue, pi_program program, const char *name, pi_bool blocking_write, size_t count, size_t offset, const void *src, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
Device global variable.
pi_result piextEnqueueDeviceGlobalVariableRead (pi_queue queue, pi_program program, const char *name, pi_bool blocking_read, size_t count, size_t offset, void *dst, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
API reading data from a device global variable to host.
pi_result piextEnqueueReadHostPipe (pi_queue queue, pi_program program, const char *pipe_symbol, pi_bool blocking, void *ptr, size_t size, pi_uint32 num_events_in_waitlist, const pi_event *events_waitlist, pi_event *event)
Plugin.
pi_result piextEnqueueWriteHostPipe (pi_queue queue, pi_program program, const char *pipe_symbol, pi_bool blocking, void *ptr, size_t size, pi_uint32 num_events_in_waitlist, const pi_event *events_waitlist, pi_event *event)
Write to pipe of a given name.
pi_result piextPluginGetOpaqueData (void *opaque_data_param, void **opaque_data_return)
API to get Plugin internal data, opaque to SYCL RT.
pi_result piTearDown (void *PluginParameter)
API to notify that the plugin should clean up its resources.
pi_result piPluginGetLastError (char **message)
API to get Plugin specific warning and error messages.
pi_result piPluginGetBackendOption (pi_platform platform, const char *frontend_option, const char **backend_option)
API to get backend specific option.
pi_result piGetDeviceAndHostTimer (pi_device Device, uint64_t *DeviceTime, uint64_t *HostTime)
Queries device for it's global timestamp in nanoseconds, and updates HostTime with the value of the host timer at the closest possible point in time to that at which DeviceTime was returned.
pi_result piextCommandBufferCreate (pi_context context, pi_device device, const pi_ext_command_buffer_desc *desc, pi_ext_command_buffer *ret_command_buffer)
API to create a command-buffer.
pi_result piextCommandBufferRetain (pi_ext_command_buffer command_buffer)
API to increment the reference count of the command-buffer.
pi_result piextCommandBufferRelease (pi_ext_command_buffer command_buffer)
API to decrement the reference count of the command-buffer.
pi_result piextCommandBufferFinalize (pi_ext_command_buffer command_buffer)
API to stop command-buffer recording such that no more commands can be appended, and makes the command-buffer ready to enqueue on a command-queue.
pi_result piextCommandBufferNDRangeKernel (pi_ext_command_buffer command_buffer, pi_kernel kernel, pi_uint32 work_dim, const size_t *global_work_offset, const size_t *global_work_size, const size_t *local_work_size, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point *sync_point_wait_list, pi_ext_sync_point *sync_point, pi_ext_command_buffer_command *command)
API to append a kernel execution command to the command-buffer.
pi_result piextCommandBufferMemcpyUSM (pi_ext_command_buffer command_buffer, void *dst_ptr, const void *src_ptr, size_t size, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point *sync_point_wait_list, pi_ext_sync_point *sync_point)
API to append a USM memcpy command to the command-buffer.
pi_result piextCommandBufferMemBufferCopy (pi_ext_command_buffer command_buffer, pi_mem src_buffer, pi_mem dst_buffer, size_t src_offset, size_t dst_offset, size_t size, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point *sync_point_wait_list, pi_ext_sync_point *sync_point)
API to append a mem buffer copy command to the command-buffer.
pi_result piextCommandBufferMemBufferCopyRect (pi_ext_command_buffer command_buffer, pi_mem src_buffer, pi_mem dst_buffer, pi_buff_rect_offset src_origin, pi_buff_rect_offset dst_origin, pi_buff_rect_region region, size_t src_row_pitch, size_t src_slice_pitch, size_t dst_row_pitch, size_t dst_slice_pitch, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point *sync_point_wait_list, pi_ext_sync_point *sync_point)
API to append a rectangular mem buffer copy command to the command-buffer.
pi_result piextCommandBufferMemBufferRead (pi_ext_command_buffer command_buffer, pi_mem buffer, size_t offset, size_t size, void *dst, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point *sync_point_wait_list, pi_ext_sync_point *sync_point)
API to append a mem buffer read command to the command-buffer.
pi_result piextCommandBufferMemBufferReadRect (pi_ext_command_buffer command_buffer, pi_mem buffer, pi_buff_rect_offset buffer_offset, pi_buff_rect_offset host_offset, pi_buff_rect_region region, size_t buffer_row_pitch, size_t buffer_slice_pitch, size_t host_row_pitch, size_t host_slice_pitch, void *ptr, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point *sync_point_wait_list, pi_ext_sync_point *sync_point)
API to append a rectangular mem buffer read command to the command-buffer.
pi_result piextCommandBufferMemBufferWrite (pi_ext_command_buffer command_buffer, pi_mem buffer, size_t offset, size_t size, const void *ptr, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point *sync_point_wait_list, pi_ext_sync_point *sync_point)
API to append a mem buffer write command to the command-buffer.
pi_result piextCommandBufferMemBufferWriteRect (pi_ext_command_buffer command_buffer, pi_mem buffer, pi_buff_rect_offset buffer_offset, pi_buff_rect_offset host_offset, pi_buff_rect_region region, size_t buffer_row_pitch, size_t buffer_slice_pitch, size_t host_row_pitch, size_t host_slice_pitch, const void *ptr, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point *sync_point_wait_list, pi_ext_sync_point *sync_point)
API to append a rectangular mem buffer write command to the command-buffer.
pi_result piextCommandBufferMemBufferFill (pi_ext_command_buffer command_buffer, pi_mem buffer, const void *pattern, size_t pattern_size, size_t offset, size_t size, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point *sync_point_wait_list, pi_ext_sync_point *sync_point)
API to append a mem buffer fill command to the command-buffer.
pi_result piextCommandBufferFillUSM (pi_ext_command_buffer command_buffer, void *ptr, const void *pattern, size_t pattern_size, size_t size, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point *sync_point_wait_list, pi_ext_sync_point *sync_point)
API to append a USM fill command to the command-buffer.
pi_result piextCommandBufferPrefetchUSM (pi_ext_command_buffer command_buffer, const void *ptr, size_t size, pi_usm_migration_flags flags, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point *sync_point_wait_list, pi_ext_sync_point *sync_point)
API to append a USM Prefetch command to the command-buffer.
pi_result piextCommandBufferAdviseUSM (pi_ext_command_buffer command_buffer, const void *ptr, size_t length, pi_mem_advice advice, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point *sync_point_wait_list, pi_ext_sync_point *sync_point)
API to append a USM Advise command to the command-buffer.
pi_result piextEnqueueCommandBuffer (pi_ext_command_buffer command_buffer, pi_queue queue, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
API to submit the command-buffer to queue for execution, returns an error if the command-buffer is not finalized or another instance of the same command-buffer is currently executing.
pi_result piextCommandBufferUpdateKernelLaunch (pi_ext_command_buffer_command command, pi_ext_command_buffer_update_kernel_launch_desc *desc)
API to update a kernel launch command inside of a command-buffer.
pi_result piextCommandBufferRetainCommand (pi_ext_command_buffer_command command)
API to increment the reference count of a command-buffer command.
pi_result piextCommandBufferReleaseCommand (pi_ext_command_buffer_command command)
API to decrement the reference count of a command-buffer command.
pi_result piextMemUnsampledImageHandleDestroy (pi_context context, pi_device device, pi_image_handle handle)
API to destroy bindless unsampled image handles.
pi_result piextMemSampledImageHandleDestroy (pi_context context, pi_device device, pi_image_handle handle)
API to destroy bindless sampled image handles.
pi_result piextMemImageAllocate (pi_context context, pi_device device, pi_image_format *image_format, pi_image_desc *image_desc, pi_image_mem_handle *ret_mem)
API to allocate memory for bindless images.
pi_result piextMemMipmapGetLevel (pi_context context, pi_device device, pi_image_mem_handle mip_mem, unsigned int level, pi_image_mem_handle *ret_mem)
API to retrieve individual image from mipmap.
pi_result piextMemImageFree (pi_context context, pi_device device, pi_image_mem_handle memory_handle)
API to free memory for bindless images.
pi_result piextMemMipmapFree (pi_context context, pi_device device, pi_image_mem_handle memory_handle)
API to free mipmap memory for bindless images.
pi_result piextMemUnsampledImageCreate (pi_context context, pi_device device, pi_image_mem_handle img_mem, pi_image_format *image_format, pi_image_desc *image_desc, pi_mem *ret_mem, pi_image_handle *ret_handle)
API to create bindless image handles.
pi_result piextMemSampledImageCreate (pi_context context, pi_device device, pi_image_mem_handle img_mem, pi_image_format *image_format, pi_image_desc *image_desc, pi_sampler sampler, pi_mem *ret_mem, pi_image_handle *ret_handle)
API to create sampled bindless image handles.
pi_result piextBindlessImageSamplerCreate (pi_context context, const pi_sampler_properties *sampler_properties, float min_mipmap_level_clamp, float max_mipmap_level_clamp, float max_anisotropy, pi_sampler *result_sampler)
API to create samplers for bindless images.
pi_result piextMemImageCopy (pi_queue command_queue, void *dst_ptr, void *src_ptr, const pi_image_format *image_format, const pi_image_desc *image_desc, const pi_image_copy_flags flags, pi_image_offset src_offset, pi_image_offset dst_offset, pi_image_region copy_extent, pi_image_region host_extent, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
API to copy image data Host to Device or Device to Host.
pi_result piextMemImageGetInfo (const pi_image_mem_handle mem_handle, pi_image_info param_name, void *param_value, size_t *param_value_size_ret)
API to query an image memory handle for specific properties.
pi_result piextMemImportOpaqueFD (pi_context context, pi_device device, size_t size, int file_descriptor, pi_interop_mem_handle *ret_handle)
API to import external memory in the form of a file descriptor.
pi_result piextMemMapExternalArray (pi_context context, pi_device device, pi_image_format *image_format, pi_image_desc *image_desc, pi_interop_mem_handle mem_handle, pi_image_mem_handle *ret_mem)
API to map an interop memory handle to an image memory handle.
pi_result piextMemReleaseInterop (pi_context context, pi_device device, pi_interop_mem_handle memory_handle)
API to destroy interop memory.
pi_result piextImportExternalSemaphoreOpaqueFD (pi_context context, pi_device device, int file_descriptor, pi_interop_semaphore_handle *ret_handle)
API to import an external semaphore in the form of a file descriptor.
pi_result piextDestroyExternalSemaphore (pi_context context, pi_device device, pi_interop_semaphore_handle sem_handle)
API to destroy the external semaphore handle.
pi_result piextWaitExternalSemaphore (pi_queue command_queue, pi_interop_semaphore_handle sem_handle, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
API to instruct the queue with a non-blocking wait on an external semaphore.
pi_result piextSignalExternalSemaphore (pi_queue command_queue, pi_interop_semaphore_handle sem_handle, pi_uint32 num_events_in_wait_list, const pi_event *event_wait_list, pi_event *event)
API to instruct the queue to signal the external semaphore handle once all previous commands have completed execution.
Variables
static constexpr _pi_mem_advice PI_MEM_ADVICE_HIP_SET_READ_MOSTLY
static constexpr _pi_mem_advice PI_MEM_ADVICE_HIP_UNSET_READ_MOSTLY
static constexpr _pi_mem_advice PI_MEM_ADVICE_HIP_SET_PREFERRED_LOCATION
static constexpr _pi_mem_advice PI_MEM_ADVICE_HIP_UNSET_PREFERRED_LOCATION
static constexpr _pi_mem_advice PI_MEM_ADVICE_HIP_SET_ACCESSED_BY
static constexpr _pi_mem_advice PI_MEM_ADVICE_HIP_UNSET_ACCESSED_BY
static constexpr _pi_mem_advice PI_MEM_ADVICE_HIP_SET_PREFERRED_LOCATION_HOST
static constexpr _pi_mem_advice PI_MEM_ADVICE_HIP_UNSET_PREFERRED_LOCATION_HOST
static constexpr _pi_mem_advice PI_MEM_ADVICE_HIP_SET_ACCESSED_BY_HOST
static constexpr _pi_mem_advice PI_MEM_ADVICE_HIP_UNSET_ACCESSED_BY_HOST
const pi_bool PI_TRUE = 1
const pi_bool PI_FALSE = 0
constexpr pi_device_exec_capabilities PI_DEVICE_EXEC_CAPABILITIES_KERNEL
constexpr pi_device_exec_capabilities PI_DEVICE_EXEC_CAPABILITIES_NATIVE_KERNEL = (1 << 1)
constexpr pi_sampler_properties PI_SAMPLER_PROPERTIES_NORMALIZED_COORDS
constexpr pi_sampler_properties PI_SAMPLER_PROPERTIES_ADDRESSING_MODE = 0x1153
constexpr pi_sampler_properties PI_SAMPLER_PROPERTIES_FILTER_MODE = 0x1154
constexpr pi_sampler_properties PI_SAMPLER_PROPERTIES_MIP_FILTER_MODE = 0x1155
constexpr pi_sampler_properties PI_SAMPLER_PROPERTIES_CUBEMAP_FILTER_MODE
constexpr pi_memory_order_capabilities PI_MEMORY_ORDER_RELAXED = 0x01
constexpr pi_memory_order_capabilities PI_MEMORY_ORDER_ACQUIRE = 0x02
constexpr pi_memory_order_capabilities PI_MEMORY_ORDER_RELEASE = 0x04
constexpr pi_memory_order_capabilities PI_MEMORY_ORDER_ACQ_REL = 0x08
constexpr pi_memory_order_capabilities PI_MEMORY_ORDER_SEQ_CST = 0x10
constexpr pi_memory_scope_capabilities PI_MEMORY_SCOPE_WORK_ITEM = 0x01
constexpr pi_memory_scope_capabilities PI_MEMORY_SCOPE_SUB_GROUP = 0x02
constexpr pi_memory_scope_capabilities PI_MEMORY_SCOPE_WORK_GROUP = 0x04
constexpr pi_memory_scope_capabilities PI_MEMORY_SCOPE_DEVICE = 0x08
constexpr pi_memory_scope_capabilities PI_MEMORY_SCOPE_SYSTEM = 0x10
constexpr pi_mem_flags PI_MEM_FLAGS_ACCESS_RW = (1 << 0)
constexpr pi_mem_flags PI_MEM_ACCESS_READ_ONLY = (1 << 2)
constexpr pi_mem_flags PI_MEM_FLAGS_HOST_PTR_USE = (1 << 3)
constexpr pi_mem_flags PI_MEM_FLAGS_HOST_PTR_COPY = (1 << 5)
constexpr pi_mem_flags PI_MEM_FLAGS_HOST_PTR_ALLOC = (1 << 4)
constexpr pi_map_flags PI_MAP_READ = (1 << 0)
constexpr pi_map_flags PI_MAP_WRITE = (1 << 1)
constexpr pi_map_flags PI_MAP_WRITE_INVALIDATE_REGION = (1 << 2)
constexpr pi_mem_properties PI_MEM_PROPERTIES_CHANNEL = 0x4213
constexpr pi_mem_properties PI_MEM_PROPERTIES_ALLOC_BUFFER_LOCATION = 0x419E
constexpr pi_usm_mem_properties PI_MEM_ALLOC_FLAGS = 0x4195
constexpr pi_usm_mem_properties PI_MEM_ALLOC_WRTITE_COMBINED = (1 << 0)
constexpr pi_usm_mem_properties PI_MEM_ALLOC_INITIAL_PLACEMENT_DEVICE
constexpr pi_usm_mem_properties PI_MEM_ALLOC_INITIAL_PLACEMENT_HOST = (1 << 2)
constexpr pi_usm_mem_properties PI_MEM_ALLOC_DEVICE_READ_ONLY = (1 << 3)
constexpr pi_usm_mem_properties PI_MEM_USM_ALLOC_BUFFER_LOCATION = 0x419E
constexpr pi_queue_properties PI_QUEUE_FLAGS = -1
constexpr pi_queue_properties PI_QUEUE_COMPUTE_INDEX = -2
constexpr pi_queue_properties PI_QUEUE_FLAG_OUT_OF_ORDER_EXEC_MODE_ENABLE = (1 << 0)
constexpr pi_queue_properties PI_QUEUE_FLAG_PROFILING_ENABLE = (1 << 1)
constexpr pi_queue_properties PI_QUEUE_FLAG_ON_DEVICE = (1 << 2)
constexpr pi_queue_properties PI_QUEUE_FLAG_ON_DEVICE_DEFAULT = (1 << 3)
constexpr pi_queue_properties PI_EXT_ONEAPI_QUEUE_FLAG_DISCARD_EVENTS = (1 << 4)
constexpr pi_queue_properties PI_EXT_ONEAPI_QUEUE_FLAG_PRIORITY_LOW = (1 << 5)
constexpr pi_queue_properties PI_EXT_ONEAPI_QUEUE_FLAG_PRIORITY_HIGH = (1 << 6)
constexpr pi_queue_properties PI_EXT_QUEUE_FLAG_SUBMISSION_NO_IMMEDIATE = (1 << 7)
constexpr pi_queue_properties PI_EXT_QUEUE_FLAG_SUBMISSION_IMMEDIATE = (1 << 8)
static constexpr pi_device_partition_property PI_DEVICE_PARTITION_EQUALLY
static constexpr pi_device_partition_property PI_DEVICE_PARTITION_BY_COUNTS
static constexpr pi_device_partition_property PI_DEVICE_PARTITION_BY_COUNTS_LIST_END = 0x0
static constexpr pi_device_partition_property PI_DEVICE_PARTITION_BY_AFFINITY_DOMAIN = 0x1088
static constexpr pi_device_partition_property PI_EXT_INTEL_DEVICE_PARTITION_BY_CSLICE = 0x1089
static constexpr pi_device_affinity_domain PI_DEVICE_AFFINITY_DOMAIN_NUMA
static constexpr pi_device_affinity_domain PI_DEVICE_AFFINITY_DOMAIN_L4_CACHE
static constexpr pi_device_affinity_domain PI_DEVICE_AFFINITY_DOMAIN_L3_CACHE
static constexpr pi_device_affinity_domain PI_DEVICE_AFFINITY_DOMAIN_L2_CACHE
static constexpr pi_device_affinity_domain PI_DEVICE_AFFINITY_DOMAIN_L1_CACHE
static constexpr pi_device_affinity_domain PI_DEVICE_AFFINITY_DOMAIN_NEXT_PARTITIONABLE = (1 << 5)
static constexpr pi_device_fp_config PI_FP_DENORM = (1 << 0)
static constexpr pi_device_fp_config PI_FP_INF_NAN = (1 << 1)
static constexpr pi_device_fp_config PI_FP_ROUND_TO_NEAREST = (1 << 2)
static constexpr pi_device_fp_config PI_FP_ROUND_TO_ZERO = (1 << 3)
static constexpr pi_device_fp_config PI_FP_ROUND_TO_INF = (1 << 4)
static constexpr pi_device_fp_config PI_FP_FMA = (1 << 5)
static constexpr pi_device_fp_config PI_FP_SOFT_FLOAT = (1 << 6)
static constexpr pi_device_fp_config PI_FP_CORRECTLY_ROUNDED_DIVIDE_SQRT
static constexpr pi_device_exec_capabilities PI_EXEC_KERNEL = (1 << 0)
static constexpr pi_device_exec_capabilities PI_EXEC_NATIVE_KERNEL = (1 << 1)
static constexpr pi_device_binary_type PI_DEVICE_BINARY_TYPE_NONE = 0
static constexpr pi_device_binary_type PI_DEVICE_BINARY_TYPE_NATIVE = 1
static constexpr pi_device_binary_type PI_DEVICE_BINARY_TYPE_SPIRV = 2
static constexpr pi_device_binary_type PI_DEVICE_BINARY_TYPE_LLVMIR_BITCODE = 3
static const uint16_t PI_DEVICE_BINARY_VERSION = 1
static const uint8_t PI_DEVICE_BINARY_OFFLOAD_KIND_SYCL = 4
static const uint16_t PI_DEVICE_BINARIES_VERSION = 1
Macro Definition Documentation
__SYCL_PI_DEVICE_BINARY_TARGET_AMDGCN
#define __SYCL_PI_DEVICE_BINARY_TARGET_AMDGCN "amdgcn"
Definition at line 991 of file pi.h.
__SYCL_PI_DEVICE_BINARY_TARGET_NATIVE_CPU
#define __SYCL_PI_DEVICE_BINARY_TARGET_NATIVE_CPU "native_cpu"
Definition at line 992 of file pi.h.
__SYCL_PI_DEVICE_BINARY_TARGET_NVPTX64
#define __SYCL_PI_DEVICE_BINARY_TARGET_NVPTX64 "nvptx64"
PTX 64-bit image <-> "nvptx64", 64-bit NVIDIA PTX device.
Definition at line 990 of file pi.h.
__SYCL_PI_DEVICE_BINARY_TARGET_SPIRV32
#define __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV32 "spir"
SPIR-V 32-bit image <-> "spir", 32-bit OpenCL device.
Definition at line 981 of file pi.h.
__SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64
#define __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64 "spir64"
SPIR-V 64-bit image <-> "spir64", 64-bit OpenCL device.
Definition at line 983 of file pi.h.
__SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_FPGA
#define __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_FPGA "spir64_fpga"
Definition at line 988 of file pi.h.
__SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_GEN
#define __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_GEN "spir64_gen"
Definition at line 987 of file pi.h.
__SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_X86_64
#define __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_X86_64 "spir64_x86_64"
Device-specific binary images produced from SPIR-V 64-bit <-> various "spir64_*" triples for specific 64-bit OpenCL devices.
Definition at line 986 of file pi.h.
__SYCL_PI_DEVICE_BINARY_TARGET_UNKNOWN
#define __SYCL_PI_DEVICE_BINARY_TARGET_UNKNOWN "<unknown>"
Target identification strings for pi_device_binary_struct.DeviceTargetSpec.
A device type represented by a particular target triple requires specific binary images. We need to map the image type onto the device target triple
Definition at line 979 of file pi.h.
__SYCL_PI_PROGRAM_METADATA_GLOBAL_ID_MAPPING
#define __SYCL_PI_PROGRAM_METADATA_GLOBAL_ID_MAPPING "@global_id_mapping"
Definition at line 1032 of file pi.h.
__SYCL_PI_PROGRAM_METADATA_TAG_NEED_FINALIZATION
#define __SYCL_PI_PROGRAM_METADATA_TAG_NEED_FINALIZATION "Requires finalization"
Definition at line 1034 of file pi.h.
__SYCL_PI_PROGRAM_METADATA_TAG_REQD_WORK_GROUP_SIZE
#define __SYCL_PI_PROGRAM_METADATA_TAG_REQD_WORK_GROUP_SIZE "@reqd_work_group_size"
Program metadata tags recognized by the PI backends.
For kernels the tag must appear after the kernel name.
Definition at line 1030 of file pi.h.
__SYCL_PI_PROPERTY_SET_DEVICELIB_REQ_MASK
#define __SYCL_PI_PROPERTY_SET_DEVICELIB_REQ_MASK "SYCL/devicelib req mask"
PropertySetRegistry::SYCL_DEVICELIB_REQ_MASK defined in PropertySetIO.h.
Definition at line 1009 of file pi.h.
__SYCL_PI_PROPERTY_SET_KERNEL_PARAM_OPT_INFO
#define __SYCL_PI_PROPERTY_SET_KERNEL_PARAM_OPT_INFO "SYCL/kernel param opt"
PropertySetRegistry::SYCL_KERNEL_PARAM_OPT_INFO defined in PropertySetIO.h.
Definition at line 1011 of file pi.h.
__SYCL_PI_PROPERTY_SET_PROGRAM_METADATA
#define __SYCL_PI_PROPERTY_SET_PROGRAM_METADATA "SYCL/program metadata"
PropertySetRegistry::SYCL_KERNEL_PROGRAM_METADATA defined in PropertySetIO.h.
Definition at line 1013 of file pi.h.
__SYCL_PI_PROPERTY_SET_SPEC_CONST_DEFAULT_VALUES_MAP
#define __SYCL_PI_PROPERTY_SET_SPEC_CONST_DEFAULT_VALUES_MAP "SYCL/specialization constants default values"
PropertySetRegistry::SYCL_SPEC_CONSTANTS_DEFAULT_VALUES defined in PropertySetIO.h.
Definition at line 1006 of file pi.h.
__SYCL_PI_PROPERTY_SET_SPEC_CONST_MAP
#define __SYCL_PI_PROPERTY_SET_SPEC_CONST_MAP "SYCL/specialization constants"
Device binary image property set names recognized by the SYCL runtime.
Name must be consistent with PropertySetRegistry::SYCL_SPECIALIZATION_CONSTANTS defined in PropertySetIO.h
Definition at line 1003 of file pi.h.
__SYCL_PI_PROPERTY_SET_SYCL_ASSERT_USED
#define __SYCL_PI_PROPERTY_SET_SYCL_ASSERT_USED "SYCL/assert used"
PropertySetRegistry::SYCL_ASSERT_USED defined in PropertySetIO.h.
Definition at line 1017 of file pi.h.
__SYCL_PI_PROPERTY_SET_SYCL_DEVICE_GLOBALS
#define __SYCL_PI_PROPERTY_SET_SYCL_DEVICE_GLOBALS "SYCL/device globals"
PropertySetRegistry::SYCL_DEVICE_GLOBALS defined in PropertySetIO.h.
Definition at line 1021 of file pi.h.
__SYCL_PI_PROPERTY_SET_SYCL_DEVICE_REQUIREMENTS
#define __SYCL_PI_PROPERTY_SET_SYCL_DEVICE_REQUIREMENTS "SYCL/device requirements"
PropertySetRegistry::SYCL_DEVICE_REQUIREMENTS defined in PropertySetIO.h.
Definition at line 1023 of file pi.h.
__SYCL_PI_PROPERTY_SET_SYCL_EXPORTED_SYMBOLS
#define __SYCL_PI_PROPERTY_SET_SYCL_EXPORTED_SYMBOLS "SYCL/exported symbols"
PropertySetRegistry::SYCL_EXPORTED_SYMBOLS defined in PropertySetIO.h.
Definition at line 1019 of file pi.h.
__SYCL_PI_PROPERTY_SET_SYCL_HOST_PIPES
#define __SYCL_PI_PROPERTY_SET_SYCL_HOST_PIPES "SYCL/host pipes"
PropertySetRegistry::SYCL_HOST_PIPES defined in PropertySetIO.h.
Definition at line 1026 of file pi.h.
__SYCL_PI_PROPERTY_SET_SYCL_MISC_PROP
#define __SYCL_PI_PROPERTY_SET_SYCL_MISC_PROP "SYCL/misc properties"
PropertySetRegistry::SYCL_MISC_PROP defined in PropertySetIO.h.
Definition at line 1015 of file pi.h.
_PI_API
#define _PI_API (api) decltype(::api) *api;
Definition at line 2946 of file pi.h.
_PI_CONCAT
#define _PI_CONCAT (a, b) _PI_STRING_HELPER(a.b)
Definition at line 181 of file pi.h.
_PI_ERRC
#define _PI_ERRC (NAME, VAL) NAME = VAL,
Definition at line 233 of file pi.h.
_PI_ERRC_WITH_MSG
#define _PI_ERRC_WITH_MSG (NAME, VAL, MSG) NAME = VAL,
Definition at line 234 of file pi.h.
_PI_H_VERSION_MAJOR
#define _PI_H_VERSION_MAJOR 16
Definition at line 177 of file pi.h.
_PI_H_VERSION_MINOR
#define _PI_H_VERSION_MINOR 51
Definition at line 178 of file pi.h.
_PI_H_VERSION_STRING
#define _PI_H_VERSION_STRING _PI_CONCAT(_PI_H_VERSION_MAJOR, _PI_H_VERSION_MINOR)
Definition at line 192 of file pi.h.
_PI_PLUGIN_VERSION_CHECK
#define _PI_PLUGIN_VERSION_CHECK (PI_API_VERSION, PI_PLUGIN_VERSION)
Value:
  if (strncmp(PI_API_VERSION, PI_PLUGIN_VERSION,                               \
              sizeof(_PI_STRING_SUBSTITUTE(_PI_H_VERSION_MAJOR))) < 0) {       \
    return PI_ERROR_INVALID_OPERATION;                                         \
  }
Definition at line 198 of file pi.h.
_PI_PLUGIN_VERSION_STRING
#define _PI_PLUGIN_VERSION_STRING (PluginVersion) _PI_TRIPLE_CONCAT(_PI_H_VERSION_MAJOR, _PI_H_VERSION_MINOR, PluginVersion)
Definition at line 189 of file pi.h.
_PI_STRING_HELPER
#define _PI_STRING_HELPER (a) #a
Definition at line 180 of file pi.h.
_PI_STRING_SUBSTITUTE
#define _PI_STRING_SUBSTITUTE (X) _PI_STRING_HELPER(X)
Definition at line 197 of file pi.h.
_PI_TRIPLE_CONCAT
#define _PI_TRIPLE_CONCAT (a, b, c) _PI_STRING_HELPER(a.b.c)
Definition at line 182 of file pi.h.
PI_BIT
#define PI_BIT (_i) (1 << _i)
Definition at line 1916 of file pi.h.
PI_DEVICE_INFO_EXTENSION_DEVICELIB_ASSERT
#define PI_DEVICE_INFO_EXTENSION_DEVICELIB_ASSERT "cl_intel_devicelib_assert"
Extension to denote native support of assert feature by an arbitrary device piDeviceGetInfo call should return this extension when the device supports native asserts if supported extensions' names are requested.
Definition at line 997 of file pi.h.
Typedef Documentation
_pi_offload_entry
using _pi_offload_entry = _pi_offload_entry_struct *
Definition at line 922 of file pi.h.
pi_bitfield
using pi_bitfield = pi_uint64
Definition at line 224 of file pi.h.
pi_bool
using pi_bool = pi_uint32
Definition at line 223 of file pi.h.
pi_buff_rect_offset
using pi_buff_rect_offset = pi_buff_rect_offset_struct *
Definition at line 1103 of file pi.h.
pi_buff_rect_region
using pi_buff_rect_region = pi_buff_rect_region_struct *
Definition at line 1112 of file pi.h.
pi_buffer_create_type
using pi_buffer_create_type = _pi_buffer_create_type
Definition at line 853 of file pi.h.
pi_buffer_region
using pi_buffer_region = pi_buffer_region_struct *
Definition at line 1094 of file pi.h.
pi_command_type
using pi_command_type = _pi_command_type
Definition at line 848 of file pi.h.
pi_context
using pi_context = _pi_context *
Definition at line 1166 of file pi.h.
pi_context_extended_deleter
typedef void(* pi_context_extended_deleter) (void *user_data)
Definition at line 1357 of file pi.h.
pi_context_info
using pi_context_info = _pi_context_info
Definition at line 841 of file pi.h.
pi_context_properties
using pi_context_properties = intptr_t
Definition at line 732 of file pi.h.
pi_device
using pi_device = _pi_device *
Definition at line 1165 of file pi.h.
pi_device_affinity_domain
using pi_device_affinity_domain = pi_bitfield
Definition at line 882 of file pi.h.
pi_device_binaries
using pi_device_binaries = pi_device_binaries_struct *
Definition at line 1151 of file pi.h.
pi_device_binary
using pi_device_binary = pi_device_binary_struct *
Definition at line 1087 of file pi.h.
pi_device_binary_property
typedef _pi_device_binary_property_struct* pi_device_binary_property
Definition at line 943 of file pi.h.
pi_device_binary_property_set
typedef _pi_device_binary_property_set_struct* pi_device_binary_property_set
Definition at line 952 of file pi.h.
pi_device_binary_type
using pi_device_binary_type = uint8_t
Types of device binary.
Definition at line 955 of file pi.h.
pi_device_exec_capabilities
typedef pi_bitfield pi_device_exec_capabilities
Definition at line 734 of file pi.h.
pi_device_fp_config
using pi_device_fp_config = pi_bitfield
Definition at line 897 of file pi.h.
pi_device_info
using pi_device_info = _pi_device_info
Definition at line 839 of file pi.h.
pi_device_local_mem_type
using pi_device_local_mem_type = _pi_device_local_mem_type
Definition at line 838 of file pi.h.
pi_device_mem_cache_type
using pi_device_mem_cache_type = _pi_device_mem_cache_type
Definition at line 837 of file pi.h.
pi_device_partition_property
using pi_device_partition_property = intptr_t
Definition at line 869 of file pi.h.
pi_device_type
using pi_device_type = _pi_device_type
Definition at line 836 of file pi.h.
pi_event
using pi_event = _pi_event *
Definition at line 1171 of file pi.h.
pi_event_info
using pi_event_info = _pi_event_info
Definition at line 847 of file pi.h.
pi_event_status
using pi_event_status = _pi_event_status
Definition at line 858 of file pi.h.
pi_ext_command_buffer
using pi_ext_command_buffer = _pi_ext_command_buffer *
Definition at line 2366 of file pi.h.
pi_ext_command_buffer_command
using pi_ext_command_buffer_command = _pi_ext_command_buffer_command *
Definition at line 2367 of file pi.h.
pi_ext_sync_point
using pi_ext_sync_point = pi_uint32
Definition at line 2368 of file pi.h.
pi_image_channel_order
using pi_image_channel_order = _pi_image_channel_order
Definition at line 851 of file pi.h.
pi_image_channel_type
using pi_image_channel_type = _pi_image_channel_type
Definition at line 852 of file pi.h.
pi_image_copy_flags
using pi_image_copy_flags = _pi_image_copy_flags
Definition at line 866 of file pi.h.
pi_image_desc
using pi_image_desc = _pi_image_desc
Definition at line 1197 of file pi.h.
pi_image_format
using pi_image_format = _pi_image_format
Definition at line 1196 of file pi.h.
pi_image_handle
using pi_image_handle = pi_uint64
Definition at line 1173 of file pi.h.
pi_image_info
using pi_image_info = _pi_image_info
Definition at line 843 of file pi.h.
pi_image_mem_handle
using pi_image_mem_handle = void *
Definition at line 1174 of file pi.h.
pi_image_offset
using pi_image_offset = pi_image_offset_struct *
Definition at line 1121 of file pi.h.
pi_image_region
using pi_image_region = pi_image_region_struct *
Definition at line 1130 of file pi.h.
pi_int32
using pi_int32 = int32_t
Definition at line 220 of file pi.h.
pi_interop_mem_handle
using pi_interop_mem_handle = pi_uint64
Definition at line 1175 of file pi.h.
pi_interop_semaphore_handle
using pi_interop_semaphore_handle = pi_uint64
Definition at line 1176 of file pi.h.
pi_kernel
using pi_kernel = _pi_kernel *
Definition at line 1170 of file pi.h.
pi_kernel_cache_config
using pi_kernel_cache_config = _pi_kernel_cache_config
Definition at line 864 of file pi.h.
pi_kernel_exec_info
using pi_kernel_exec_info = _pi_kernel_exec_info
Definition at line 1626 of file pi.h.
pi_kernel_group_info
using pi_kernel_group_info = _pi_kernel_group_info
Definition at line 845 of file pi.h.
pi_kernel_info
typedef _pi_kernel_info pi_kernel_info
Definition at line 844 of file pi.h.
pi_kernel_sub_group_info
using pi_kernel_sub_group_info = _pi_kernel_sub_group_info
Definition at line 846 of file pi.h.
pi_map_flags
using pi_map_flags = pi_bitfield
Definition at line 784 of file pi.h.
pi_mem
using pi_mem = _pi_mem *
Definition at line 1168 of file pi.h.
pi_mem_access_flag
typedef uint32_t pi_mem_access_flag
Definition at line 1925 of file pi.h.
pi_mem_advice
using pi_mem_advice = _pi_mem_advice
Definition at line 850 of file pi.h.
pi_mem_alloc_info
using pi_mem_alloc_info = _pi_mem_alloc_info
Definition at line 1997 of file pi.h.
pi_mem_flags
using pi_mem_flags = pi_bitfield
Definition at line 774 of file pi.h.
pi_mem_info
using pi_mem_info = _pi_mem_info
Definition at line 1210 of file pi.h.
pi_mem_obj_access
using pi_mem_obj_access = _pi_mem_obj_access
Definition at line 1924 of file pi.h.
pi_mem_obj_property
using pi_mem_obj_property = _pi_mem_obj_property
Definition at line 1938 of file pi.h.
pi_mem_obj_property_type
using pi_mem_obj_property_type = _pi_mem_obj_property_type
Definition at line 1931 of file pi.h.
pi_mem_properties
using pi_mem_properties = pi_bitfield
Definition at line 790 of file pi.h.
pi_mem_type
using pi_mem_type = _pi_mem_type
Definition at line 849 of file pi.h.
pi_memory_order_capabilities
using pi_memory_order_capabilities = pi_bitfield
Definition at line 749 of file pi.h.
pi_memory_scope_capabilities
using pi_memory_scope_capabilities = pi_bitfield
Definition at line 756 of file pi.h.
pi_native_handle
using pi_native_handle = uintptr_t
Definition at line 225 of file pi.h.
pi_peer_attr
using pi_peer_attr = _pi_peer_attr
Definition at line 1211 of file pi.h.
pi_platform
using pi_platform = _pi_platform *
Definition at line 1164 of file pi.h.
pi_platform_backend
using pi_platform_backend = _pi_platform_backend
Definition at line 835 of file pi.h.
pi_platform_info
using pi_platform_info = _pi_platform_info
Definition at line 834 of file pi.h.
pi_plugin
using pi_plugin = _pi_plugin
Definition at line 1227 of file pi.h.
pi_profiling_info
using pi_profiling_info = _pi_profiling_info
Definition at line 863 of file pi.h.
pi_program
using pi_program = _pi_program *
Definition at line 1169 of file pi.h.
pi_program_binary_type
using pi_program_binary_type = _pi_program_binary_type
Definition at line 861 of file pi.h.
pi_program_build_info
using pi_program_build_info = _pi_program_build_info
Definition at line 859 of file pi.h.
pi_program_build_status
using pi_program_build_status = _pi_program_build_status
Definition at line 860 of file pi.h.
pi_program_info
using pi_program_info = _pi_program_info
Definition at line 840 of file pi.h.
pi_queue
using pi_queue = _pi_queue *
Definition at line 1167 of file pi.h.
pi_queue_info
using pi_queue_info = _pi_queue_info
Definition at line 842 of file pi.h.
pi_queue_properties
using pi_queue_properties = pi_bitfield
Definition at line 809 of file pi.h.
pi_result
using pi_result = _pi_result
Definition at line 833 of file pi.h.
pi_sampler
using pi_sampler = _pi_sampler *
Definition at line 1172 of file pi.h.
pi_sampler_addressing_mode
using pi_sampler_addressing_mode = _pi_sampler_addressing_mode
Definition at line 854 of file pi.h.
pi_sampler_cubemap_filter_mode
using pi_sampler_cubemap_filter_mode = _pi_sampler_cubemap_filter_mode
Definition at line 856 of file pi.h.
pi_sampler_filter_mode
using pi_sampler_filter_mode = _pi_sampler_filter_mode
Definition at line 855 of file pi.h.
pi_sampler_info
using pi_sampler_info = _pi_sampler_info
Definition at line 857 of file pi.h.
pi_sampler_properties
using pi_sampler_properties = pi_bitfield
Definition at line 740 of file pi.h.
pi_uint32
using pi_uint32 = uint32_t
Definition at line 221 of file pi.h.
pi_uint64
using pi_uint64 = uint64_t
Definition at line 222 of file pi.h.
pi_usm_capabilities
using pi_usm_capabilities = _pi_usm_capabilities
Definition at line 1996 of file pi.h.
pi_usm_capability_query
using pi_usm_capability_query = _pi_usm_capability_query
Definition at line 1995 of file pi.h.
pi_usm_mem_properties
using pi_usm_mem_properties = pi_bitfield
Definition at line 796 of file pi.h.
pi_usm_migration_flags
using pi_usm_migration_flags = _pi_usm_migration_flags
Definition at line 1999 of file pi.h.
pi_usm_type
using pi_usm_type = _pi_usm_type
Definition at line 1998 of file pi.h.
Enumeration Type Documentation
_pi_buffer_create_type
enum _pi_buffer_create_type
Enumerator
PI_BUFFER_CREATE_TYPE_REGION
Definition at line 698 of file pi.h.
_pi_command_type
enum _pi_command_type
Enumerator
PI_COMMAND_TYPE_NDRANGE_KERNEL
PI_COMMAND_TYPE_MEM_BUFFER_READ
PI_COMMAND_TYPE_MEM_BUFFER_WRITE
PI_COMMAND_TYPE_MEM_BUFFER_COPY
PI_COMMAND_TYPE_MEM_BUFFER_MAP
PI_COMMAND_TYPE_MEM_BUFFER_UNMAP
PI_COMMAND_TYPE_MEM_BUFFER_READ_RECT
PI_COMMAND_TYPE_MEM_BUFFER_WRITE_RECT
PI_COMMAND_TYPE_MEM_BUFFER_COPY_RECT
PI_COMMAND_TYPE_USER
PI_COMMAND_TYPE_MEM_BUFFER_FILL
PI_COMMAND_TYPE_IMAGE_READ
PI_COMMAND_TYPE_IMAGE_WRITE
PI_COMMAND_TYPE_IMAGE_COPY
PI_COMMAND_TYPE_NATIVE_KERNEL
PI_COMMAND_TYPE_COPY_BUFFER_TO_IMAGE
PI_COMMAND_TYPE_COPY_IMAGE_TO_BUFFER
PI_COMMAND_TYPE_MAP_IMAGE
PI_COMMAND_TYPE_MARKER
PI_COMMAND_TYPE_ACQUIRE_GL_OBJECTS
PI_COMMAND_TYPE_RELEASE_GL_OBJECTS
PI_COMMAND_TYPE_BARRIER
PI_COMMAND_TYPE_MIGRATE_MEM_OBJECTS
PI_COMMAND_TYPE_FILL_IMAGE
PI_COMMAND_TYPE_SVM_FREE
PI_COMMAND_TYPE_SVM_MEMCPY
PI_COMMAND_TYPE_SVM_MEMFILL
PI_COMMAND_TYPE_SVM_MAP
PI_COMMAND_TYPE_SVM_UNMAP
PI_COMMAND_TYPE_EXT_COMMAND_BUFFER
PI_COMMAND_TYPE_DEVICE_GLOBAL_VARIABLE_READ
PI_COMMAND_TYPE_DEVICE_GLOBAL_VARIABLE_WRITE
Definition at line 569 of file pi.h.
_pi_context_info
enum _pi_context_info
Enumerator
PI_CONTEXT_INFO_DEVICES
PI_CONTEXT_INFO_PLATFORM
PI_CONTEXT_INFO_NUM_DEVICES
PI_CONTEXT_INFO_PROPERTIES
PI_CONTEXT_INFO_REFERENCE_COUNT
PI_EXT_CONTEXT_INFO_ATOMIC_MEMORY_ORDER_CAPABILITIES
PI_EXT_CONTEXT_INFO_ATOMIC_MEMORY_SCOPE_CAPABILITIES
PI_EXT_CONTEXT_INFO_ATOMIC_FENCE_ORDER_CAPABILITIES
PI_EXT_CONTEXT_INFO_ATOMIC_FENCE_SCOPE_CAPABILITIES
PI_EXT_ONEAPI_CONTEXT_INFO_USM_FILL2D_SUPPORT
PI_EXT_ONEAPI_CONTEXT_INFO_USM_MEMSET2D_SUPPORT
PI_EXT_ONEAPI_CONTEXT_INFO_USM_MEMCPY2D_SUPPORT
Definition at line 495 of file pi.h.
_pi_device_info
enum _pi_device_info
Enumerator
PI_DEVICE_INFO_TYPE
PI_DEVICE_INFO_VENDOR_ID
PI_DEVICE_INFO_MAX_COMPUTE_UNITS
PI_DEVICE_INFO_MAX_WORK_ITEM_DIMENSIONS
PI_DEVICE_INFO_MAX_WORK_ITEM_SIZES
PI_DEVICE_INFO_MAX_WORK_GROUP_SIZE
PI_DEVICE_INFO_SINGLE_FP_CONFIG
PI_DEVICE_INFO_HALF_FP_CONFIG
PI_DEVICE_INFO_DOUBLE_FP_CONFIG
PI_DEVICE_INFO_QUEUE_PROPERTIES
PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_CHAR
PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_SHORT
PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_INT
PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_LONG
PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_FLOAT
PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_DOUBLE
PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_HALF
PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_CHAR
PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_SHORT
PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_INT
PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_LONG
PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_FLOAT
PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_DOUBLE
PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_HALF
PI_DEVICE_INFO_MAX_CLOCK_FREQUENCY
PI_DEVICE_INFO_ADDRESS_BITS
PI_DEVICE_INFO_MAX_MEM_ALLOC_SIZE
PI_DEVICE_INFO_IMAGE_SUPPORT
PI_DEVICE_INFO_MAX_READ_IMAGE_ARGS
PI_DEVICE_INFO_MAX_WRITE_IMAGE_ARGS
PI_DEVICE_INFO_IMAGE2D_MAX_WIDTH
PI_DEVICE_INFO_IMAGE2D_MAX_HEIGHT
PI_DEVICE_INFO_IMAGE3D_MAX_WIDTH
PI_DEVICE_INFO_IMAGE3D_MAX_HEIGHT
PI_DEVICE_INFO_IMAGE3D_MAX_DEPTH
PI_DEVICE_INFO_IMAGE_MAX_BUFFER_SIZE
PI_DEVICE_INFO_IMAGE_MAX_ARRAY_SIZE
PI_DEVICE_INFO_MAX_SAMPLERS
PI_DEVICE_INFO_MAX_PARAMETER_SIZE
PI_DEVICE_INFO_MEM_BASE_ADDR_ALIGN
PI_DEVICE_INFO_GLOBAL_MEM_CACHE_TYPE
PI_DEVICE_INFO_GLOBAL_MEM_CACHELINE_SIZE
PI_DEVICE_INFO_GLOBAL_MEM_CACHE_SIZE
PI_DEVICE_INFO_GLOBAL_MEM_SIZE
PI_DEVICE_INFO_MAX_CONSTANT_BUFFER_SIZE
PI_DEVICE_INFO_MAX_CONSTANT_ARGS
PI_DEVICE_INFO_LOCAL_MEM_TYPE
PI_DEVICE_INFO_LOCAL_MEM_SIZE
PI_DEVICE_INFO_ERROR_CORRECTION_SUPPORT
PI_DEVICE_INFO_HOST_UNIFIED_MEMORY
PI_DEVICE_INFO_PROFILING_TIMER_RESOLUTION
PI_DEVICE_INFO_ENDIAN_LITTLE
PI_DEVICE_INFO_AVAILABLE
PI_DEVICE_INFO_COMPILER_AVAILABLE
PI_DEVICE_INFO_LINKER_AVAILABLE
PI_DEVICE_INFO_EXECUTION_CAPABILITIES
PI_DEVICE_INFO_QUEUE_ON_DEVICE_PROPERTIES
PI_DEVICE_INFO_QUEUE_ON_HOST_PROPERTIES
PI_DEVICE_INFO_BUILT_IN_KERNELS
PI_DEVICE_INFO_PLATFORM
PI_DEVICE_INFO_REFERENCE_COUNT
PI_DEVICE_INFO_IL_VERSION
PI_DEVICE_INFO_NAME
PI_DEVICE_INFO_VENDOR
PI_DEVICE_INFO_DRIVER_VERSION
PI_DEVICE_INFO_PROFILE
PI_DEVICE_INFO_VERSION
PI_DEVICE_INFO_OPENCL_C_VERSION
PI_DEVICE_INFO_EXTENSIONS
PI_DEVICE_INFO_PRINTF_BUFFER_SIZE
PI_DEVICE_INFO_PREFERRED_INTEROP_USER_SYNC
PI_DEVICE_INFO_PARENT_DEVICE
PI_DEVICE_INFO_PARTITION_PROPERTIES
PI_DEVICE_INFO_PARTITION_MAX_SUB_DEVICES
PI_DEVICE_INFO_PARTITION_AFFINITY_DOMAIN
PI_DEVICE_INFO_PARTITION_TYPE
PI_DEVICE_INFO_MAX_NUM_SUB_GROUPS
PI_DEVICE_INFO_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS
PI_DEVICE_INFO_SUB_GROUP_SIZES_INTEL
PI_DEVICE_INFO_USM_HOST_SUPPORT
PI_DEVICE_INFO_USM_DEVICE_SUPPORT
PI_DEVICE_INFO_USM_SINGLE_SHARED_SUPPORT
PI_DEVICE_INFO_USM_CROSS_SHARED_SUPPORT
PI_DEVICE_INFO_USM_SYSTEM_SHARED_SUPPORT
PI_DEVICE_INFO_UUID
PI_EXT_ONEAPI_DEVICE_INFO_IP_VERSION
PI_DEVICE_INFO_DEVICE_ID
PI_DEVICE_INFO_PCI_ADDRESS
PI_DEVICE_INFO_GPU_EU_COUNT
PI_DEVICE_INFO_GPU_EU_SIMD_WIDTH
PI_DEVICE_INFO_GPU_SLICES
PI_DEVICE_INFO_GPU_SUBSLICES_PER_SLICE
PI_DEVICE_INFO_GPU_EU_COUNT_PER_SUBSLICE
PI_DEVICE_INFO_MAX_MEM_BANDWIDTH
PI_DEVICE_INFO_IMAGE_SRGB
PI_DEVICE_INFO_BUILD_ON_SUBDEVICE
PI_EXT_INTEL_DEVICE_INFO_FREE_MEMORY
PI_EXT_INTEL_DEVICE_INFO_MEMORY_CLOCK_RATE
PI_EXT_INTEL_DEVICE_INFO_MEMORY_BUS_WIDTH
PI_EXT_INTEL_DEVICE_INFO_MAX_COMPUTE_QUEUE_INDICES
PI_DEVICE_INFO_ATOMIC_64
PI_EXT_DEVICE_INFO_ATOMIC_MEMORY_ORDER_CAPABILITIES
PI_EXT_DEVICE_INFO_ATOMIC_MEMORY_SCOPE_CAPABILITIES
PI_DEVICE_INFO_GPU_HW_THREADS_PER_EU
PI_DEVICE_INFO_BACKEND_VERSION
PI_EXT_ONEAPI_DEVICE_INFO_BFLOAT16_MATH_FUNCTIONS
PI_EXT_ONEAPI_DEVICE_INFO_MAX_GLOBAL_WORK_GROUPS
PI_EXT_ONEAPI_DEVICE_INFO_MAX_WORK_GROUPS_1D
PI_EXT_ONEAPI_DEVICE_INFO_MAX_WORK_GROUPS_2D
PI_EXT_ONEAPI_DEVICE_INFO_MAX_WORK_GROUPS_3D
PI_EXT_ONEAPI_DEVICE_INFO_CUDA_ASYNC_BARRIER
PI_EXT_CODEPLAY_DEVICE_INFO_SUPPORTS_FUSION
PI_EXT_DEVICE_INFO_ATOMIC_FENCE_ORDER_CAPABILITIES
PI_EXT_DEVICE_INFO_ATOMIC_FENCE_SCOPE_CAPABILITIES
PI_EXT_INTEL_DEVICE_INFO_MEM_CHANNEL_SUPPORT
PI_EXT_CODEPLAY_DEVICE_INFO_MAX_REGISTERS_PER_WORK_GROUP
PI_EXT_INTEL_DEVICE_INFO_ESIMD_SUPPORT
PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_IMAGES_SUPPORT
PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_IMAGES_SHARED_USM_SUPPORT
PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_IMAGES_1D_USM_SUPPORT
PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_IMAGES_2D_USM_SUPPORT
PI_EXT_ONEAPI_DEVICE_INFO_IMAGE_PITCH_ALIGN
PI_EXT_ONEAPI_DEVICE_INFO_MAX_IMAGE_LINEAR_WIDTH
PI_EXT_ONEAPI_DEVICE_INFO_MAX_IMAGE_LINEAR_HEIGHT
PI_EXT_ONEAPI_DEVICE_INFO_MAX_IMAGE_LINEAR_PITCH
PI_EXT_ONEAPI_DEVICE_INFO_MIPMAP_SUPPORT
PI_EXT_ONEAPI_DEVICE_INFO_MIPMAP_ANISOTROPY_SUPPORT
PI_EXT_ONEAPI_DEVICE_INFO_MIPMAP_MAX_ANISOTROPY
PI_EXT_ONEAPI_DEVICE_INFO_MIPMAP_LEVEL_REFERENCE_SUPPORT
PI_EXT_ONEAPI_DEVICE_INFO_INTEROP_MEMORY_IMPORT_SUPPORT
PI_EXT_ONEAPI_DEVICE_INFO_INTEROP_MEMORY_EXPORT_SUPPORT
PI_EXT_ONEAPI_DEVICE_INFO_INTEROP_SEMAPHORE_IMPORT_SUPPORT
PI_EXT_ONEAPI_DEVICE_INFO_INTEROP_SEMAPHORE_EXPORT_SUPPORT
PI_EXT_ONEAPI_DEVICE_INFO_MATRIX_COMBINATIONS
PI_EXT_ONEAPI_DEVICE_INFO_COMPONENT_DEVICES
PI_EXT_ONEAPI_DEVICE_INFO_COMPOSITE_DEVICE
PI_EXT_ONEAPI_DEVICE_INFO_COMMAND_BUFFER_SUPPORT
PI_EXT_ONEAPI_DEVICE_INFO_COMMAND_BUFFER_UPDATE_SUPPORT
PI_EXT_ONEAPI_DEVICE_INFO_CUBEMAP_SUPPORT
PI_EXT_ONEAPI_DEVICE_INFO_CUBEMAP_SEAMLESS_FILTERING_SUPPORT
PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_1D_USM
PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_1D
PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_2D_USM
PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_2D
PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_3D_USM
PI_EXT_ONEAPI_DEVICE_INFO_BINDLESS_SAMPLED_IMAGE_FETCH_3D
Definition at line 312 of file pi.h.
_pi_device_local_mem_type
enum _pi_device_local_mem_type
Enumerator
PI_DEVICE_LOCAL_MEM_TYPE_LOCAL
PI_DEVICE_LOCAL_MEM_TYPE_GLOBAL
Definition at line 307 of file pi.h.
_pi_device_mem_cache_type
enum _pi_device_mem_cache_type
Enumerator
PI_DEVICE_MEM_CACHE_TYPE_NONE
PI_DEVICE_MEM_CACHE_TYPE_READ_ONLY_CACHE
PI_DEVICE_MEM_CACHE_TYPE_READ_WRITE_CACHE
Definition at line 301 of file pi.h.
_pi_device_type
enum _pi_device_type : pi_uint64
Enumerator
PI_DEVICE_TYPE_DEFAULT
The default device available in the PI plugin.
PI_DEVICE_TYPE_ALL
All devices available in the PI plugin.
PI_DEVICE_TYPE_CPU
A PI device that is the host processor.
PI_DEVICE_TYPE_GPU
A PI device that is a GPU.
PI_DEVICE_TYPE_ACC
A PI device that is a dedicated accelerator.
PI_DEVICE_TYPE_CUSTOM
A PI device that is a custom device.
Definition at line 280 of file pi.h.
_pi_event_info
enum _pi_event_info
Enumerator
PI_EVENT_INFO_COMMAND_QUEUE
PI_EVENT_INFO_CONTEXT
PI_EVENT_INFO_COMMAND_TYPE
PI_EVENT_INFO_COMMAND_EXECUTION_STATUS
PI_EVENT_INFO_REFERENCE_COUNT
Definition at line 561 of file pi.h.
_pi_event_status
enum _pi_event_status
Enumerator
PI_EVENT_COMPLETE
PI_EVENT_RUNNING
PI_EVENT_SUBMITTED
PI_EVENT_QUEUED
Definition at line 240 of file pi.h.
_pi_image_channel_order
enum _pi_image_channel_order
Enumerator
PI_IMAGE_CHANNEL_ORDER_A
PI_IMAGE_CHANNEL_ORDER_R
PI_IMAGE_CHANNEL_ORDER_RG
PI_IMAGE_CHANNEL_ORDER_RA
PI_IMAGE_CHANNEL_ORDER_RGB
PI_IMAGE_CHANNEL_ORDER_RGBA
PI_IMAGE_CHANNEL_ORDER_BGRA
PI_IMAGE_CHANNEL_ORDER_ARGB
PI_IMAGE_CHANNEL_ORDER_ABGR
PI_IMAGE_CHANNEL_ORDER_INTENSITY
PI_IMAGE_CHANNEL_ORDER_LUMINANCE
PI_IMAGE_CHANNEL_ORDER_Rx
PI_IMAGE_CHANNEL_ORDER_RGx
PI_IMAGE_CHANNEL_ORDER_RGBx
PI_IMAGE_CHANNEL_ORDER_sRGBA
Definition at line 656 of file pi.h.
_pi_image_channel_type
enum _pi_image_channel_type
Enumerator
PI_IMAGE_CHANNEL_TYPE_SNORM_INT8
PI_IMAGE_CHANNEL_TYPE_SNORM_INT16
PI_IMAGE_CHANNEL_TYPE_UNORM_INT8
PI_IMAGE_CHANNEL_TYPE_UNORM_INT16
PI_IMAGE_CHANNEL_TYPE_UNORM_SHORT_565
PI_IMAGE_CHANNEL_TYPE_UNORM_SHORT_555
PI_IMAGE_CHANNEL_TYPE_UNORM_INT_101010
PI_IMAGE_CHANNEL_TYPE_SIGNED_INT8
PI_IMAGE_CHANNEL_TYPE_SIGNED_INT16
PI_IMAGE_CHANNEL_TYPE_SIGNED_INT32
PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT8
PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT16
PI_IMAGE_CHANNEL_TYPE_UNSIGNED_INT32
PI_IMAGE_CHANNEL_TYPE_HALF_FLOAT
PI_IMAGE_CHANNEL_TYPE_FLOAT
Definition at line 674 of file pi.h.
_pi_image_copy_flags
enum _pi_image_copy_flags
Enumerator
PI_IMAGE_COPY_HOST_TO_DEVICE
PI_IMAGE_COPY_DEVICE_TO_HOST
PI_IMAGE_COPY_DEVICE_TO_DEVICE
Definition at line 692 of file pi.h.
_pi_image_info
enum _pi_image_info
Enumerator
PI_IMAGE_INFO_FORMAT
PI_IMAGE_INFO_ELEMENT_SIZE
PI_IMAGE_INFO_ROW_PITCH
PI_IMAGE_INFO_SLICE_PITCH
PI_IMAGE_INFO_WIDTH
PI_IMAGE_INFO_HEIGHT
PI_IMAGE_INFO_DEPTH
Definition at line 544 of file pi.h.
_pi_kernel_cache_config
enum _pi_kernel_cache_config
Enumerator
PI_EXT_KERNEL_EXEC_INFO_CACHE_DEFAULT
PI_EXT_KERNEL_EXEC_INFO_CACHE_LARGE_SLM
PI_EXT_KERNEL_EXEC_INFO_CACHE_LARGE_DATA
Definition at line 824 of file pi.h.
_pi_kernel_exec_info
enum _pi_kernel_exec_info
Enumerator
PI_USM_INDIRECT_ACCESS
indicates that the kernel might access data through USM ptrs
PI_USM_PTRS
provides an explicit list of pointers that the kernel will access
PI_EXT_KERNEL_EXEC_INFO_CACHE_CONFIG
provides the preferred cache configuration (large slm or large data)
Definition at line 1617 of file pi.h.
_pi_kernel_group_info
enum _pi_kernel_group_info
Enumerator
PI_KERNEL_GROUP_INFO_GLOBAL_WORK_SIZE
PI_KERNEL_GROUP_INFO_WORK_GROUP_SIZE
PI_KERNEL_GROUP_INFO_COMPILE_WORK_GROUP_SIZE
PI_KERNEL_GROUP_INFO_LOCAL_MEM_SIZE
PI_KERNEL_GROUP_INFO_PREFERRED_WORK_GROUP_SIZE_MULTIPLE
PI_KERNEL_GROUP_INFO_PRIVATE_MEM_SIZE
PI_KERNEL_GROUP_INFO_NUM_REGS
Definition at line 533 of file pi.h.
_pi_kernel_info
enum _pi_kernel_info
Enumerator
PI_KERNEL_INFO_FUNCTION_NAME
PI_KERNEL_INFO_NUM_ARGS
PI_KERNEL_INFO_REFERENCE_COUNT
PI_KERNEL_INFO_CONTEXT
PI_KERNEL_INFO_PROGRAM
PI_KERNEL_INFO_ATTRIBUTES
Definition at line 524 of file pi.h.
_pi_kernel_sub_group_info
enum _pi_kernel_sub_group_info
Enumerator
PI_KERNEL_MAX_SUB_GROUP_SIZE
PI_KERNEL_MAX_NUM_SUB_GROUPS
PI_KERNEL_COMPILE_NUM_SUB_GROUPS
PI_KERNEL_COMPILE_SUB_GROUP_SIZE_INTEL
Definition at line 554 of file pi.h.
_pi_mem_advice
enum _pi_mem_advice
Enumerator
PI_MEM_ADVICE_RESET
PI_MEM_ADVICE_CUDA_SET_READ_MOSTLY
PI_MEM_ADVICE_CUDA_UNSET_READ_MOSTLY
PI_MEM_ADVICE_CUDA_SET_PREFERRED_LOCATION
PI_MEM_ADVICE_CUDA_UNSET_PREFERRED_LOCATION
PI_MEM_ADVICE_CUDA_SET_ACCESSED_BY
PI_MEM_ADVICE_CUDA_UNSET_ACCESSED_BY
PI_MEM_ADVICE_CUDA_SET_PREFERRED_LOCATION_HOST
PI_MEM_ADVICE_CUDA_UNSET_PREFERRED_LOCATION_HOST
PI_MEM_ADVICE_CUDA_SET_ACCESSED_BY_HOST
PI_MEM_ADVICE_CUDA_UNSET_ACCESSED_BY_HOST
PI_MEM_ADVICE_HIP_SET_COARSE_GRAINED
PI_MEM_ADVICE_HIP_UNSET_COARSE_GRAINED
PI_MEM_ADVICE_UNKNOWN
Definition at line 615 of file pi.h.
_pi_mem_alloc_info
enum _pi_mem_alloc_info
Enumerator
PI_MEM_ALLOC_TYPE
PI_MEM_ALLOC_BASE_PTR
PI_MEM_ALLOC_SIZE
PI_MEM_ALLOC_DEVICE
Definition at line 1974 of file pi.h.
_pi_mem_info
enum _pi_mem_info
Enumerator
PI_MEM_CONTEXT
PI_MEM_SIZE
Definition at line 1199 of file pi.h.
_pi_mem_obj_access
enum _pi_mem_obj_access
Enumerator
PI_ACCESS_READ_WRITE
PI_ACCESS_WRITE_ONLY
PI_ACCESS_READ_ONLY
Definition at line 1919 of file pi.h.
_pi_mem_obj_property_type
enum _pi_mem_obj_property_type
Enumerator
PI_KERNEL_ARG_MEM_OBJ_ACCESS
PI_ENUM_FORCE_UINT32
Definition at line 1927 of file pi.h.
_pi_mem_type
enum _pi_mem_type
Enumerator
PI_MEM_TYPE_BUFFER
PI_MEM_TYPE_IMAGE2D
PI_MEM_TYPE_IMAGE3D
PI_MEM_TYPE_IMAGE2D_ARRAY
PI_MEM_TYPE_IMAGE1D
PI_MEM_TYPE_IMAGE1D_ARRAY
PI_MEM_TYPE_IMAGE1D_BUFFER
PI_MEM_TYPE_IMAGE_CUBEMAP
Definition at line 604 of file pi.h.
_pi_peer_attr
enum _pi_peer_attr
Enumerator
PI_PEER_ACCESS_SUPPORTED
returns a uint32_t: 1 if P2P Access is supported otherwise P2P Access is not supported.
PI_PEER_ATOMICS_SUPPORTED
returns a uint32_t: 1 if Atomic operations are supported over the P2P link, otherwise such operations are not supported.
Definition at line 1201 of file pi.h.
_pi_platform_backend
enum _pi_platform_backend
Enumerator
PI_EXT_PLATFORM_BACKEND_UNKNOWN
The backend is not a recognized one.
PI_EXT_PLATFORM_BACKEND_LEVEL_ZERO
The backend is Level Zero.
PI_EXT_PLATFORM_BACKEND_OPENCL
The backend is OpenCL.
PI_EXT_PLATFORM_BACKEND_CUDA
The backend is CUDA.
PI_EXT_PLATFORM_BACKEND_HIP
The backend is HIP.
PI_EXT_PLATFORM_BACKEND_ESIMD
The backend is ESIMD.
PI_EXT_PLATFORM_BACKEND_NATIVE_CPU
The backend is NATIVE_CPU.
Definition at line 291 of file pi.h.
_pi_platform_info
enum _pi_platform_info
Enumerator
PI_PLATFORM_INFO_EXTENSIONS
PI_PLATFORM_INFO_NAME
PI_PLATFORM_INFO_PROFILE
PI_PLATFORM_INFO_VENDOR
PI_PLATFORM_INFO_VERSION
PI_EXT_PLATFORM_INFO_BACKEND
Definition at line 247 of file pi.h.
_pi_profiling_info
enum _pi_profiling_info
Enumerator
PI_PROFILING_INFO_COMMAND_QUEUED
PI_PROFILING_INFO_COMMAND_SUBMIT
PI_PROFILING_INFO_COMMAND_START
PI_PROFILING_INFO_COMMAND_END
Definition at line 763 of file pi.h.
_pi_program_binary_type
enum _pi_program_binary_type
Enumerator
PI_PROGRAM_BINARY_TYPE_NONE
PI_PROGRAM_BINARY_TYPE_COMPILED_OBJECT
PI_PROGRAM_BINARY_TYPE_LIBRARY
PI_PROGRAM_BINARY_TYPE_EXECUTABLE
Definition at line 270 of file pi.h.
_pi_program_build_info
enum _pi_program_build_info
Enumerator
PI_PROGRAM_BUILD_INFO_STATUS
PI_PROGRAM_BUILD_INFO_OPTIONS
PI_PROGRAM_BUILD_INFO_LOG
PI_PROGRAM_BUILD_INFO_BINARY_TYPE
Definition at line 256 of file pi.h.
_pi_program_build_status
enum _pi_program_build_status
Enumerator
PI_PROGRAM_BUILD_STATUS_NONE
PI_PROGRAM_BUILD_STATUS_ERROR
PI_PROGRAM_BUILD_STATUS_SUCCESS
PI_PROGRAM_BUILD_STATUS_IN_PROGRESS
Definition at line 263 of file pi.h.
_pi_program_info
enum _pi_program_info
Enumerator
PI_PROGRAM_INFO_REFERENCE_COUNT
PI_PROGRAM_INFO_CONTEXT
PI_PROGRAM_INFO_NUM_DEVICES
PI_PROGRAM_INFO_DEVICES
PI_PROGRAM_INFO_SOURCE
PI_PROGRAM_INFO_BINARY_SIZES
PI_PROGRAM_INFO_BINARIES
PI_PROGRAM_INFO_NUM_KERNELS
PI_PROGRAM_INFO_KERNEL_NAMES
Definition at line 483 of file pi.h.
_pi_queue_info
enum _pi_queue_info
Enumerator
PI_QUEUE_INFO_CONTEXT
PI_QUEUE_INFO_DEVICE
PI_QUEUE_INFO_DEVICE_DEFAULT
PI_QUEUE_INFO_PROPERTIES
PI_QUEUE_INFO_REFERENCE_COUNT
PI_QUEUE_INFO_SIZE
PI_EXT_ONEAPI_QUEUE_INFO_EMPTY
Definition at line 512 of file pi.h.
_pi_result
enum _pi_result
Definition at line 232 of file pi.h.
_pi_sampler_addressing_mode
enum _pi_sampler_addressing_mode
Enumerator
PI_SAMPLER_ADDRESSING_MODE_MIRRORED_REPEAT
PI_SAMPLER_ADDRESSING_MODE_REPEAT
PI_SAMPLER_ADDRESSING_MODE_CLAMP_TO_EDGE
PI_SAMPLER_ADDRESSING_MODE_CLAMP
PI_SAMPLER_ADDRESSING_MODE_NONE
Definition at line 714 of file pi.h.
_pi_sampler_cubemap_filter_mode
enum _pi_sampler_cubemap_filter_mode
Enumerator
PI_SAMPLER_CUBEMAP_FILTER_MODE_DISJOINTED
PI_SAMPLER_CUBEMAP_FILTER_MODE_SEAMLESS
Definition at line 727 of file pi.h.
_pi_sampler_filter_mode
enum _pi_sampler_filter_mode
Enumerator
PI_SAMPLER_FILTER_MODE_NEAREST
PI_SAMPLER_FILTER_MODE_LINEAR
Definition at line 722 of file pi.h.
_pi_sampler_info
enum _pi_sampler_info
Enumerator
PI_SAMPLER_INFO_REFERENCE_COUNT
PI_SAMPLER_INFO_CONTEXT
PI_SAMPLER_INFO_NORMALIZED_COORDS
PI_SAMPLER_INFO_ADDRESSING_MODE
PI_SAMPLER_INFO_FILTER_MODE
PI_SAMPLER_INFO_MIP_FILTER_MODE
PI_SAMPLER_INFO_LOD_MIN
PI_SAMPLER_INFO_LOD_MAX
Definition at line 703 of file pi.h.
_pi_sanitize_type
enum _pi_sanitize_type
Enumerator
_PI_SANITIZE_TYPE_NONE
_PI_SANITIZE_TYPE_ADDRESS
_PI_SANITIZE_TYPE_MEMORY
_PI_SANITIZE_TYPE_THREAD
Definition at line 2926 of file pi.h.
_pi_usm_capabilities
enum _pi_usm_capabilities : pi_bitfield
Enumerator
PI_USM_ACCESS
PI_USM_ATOMIC_ACCESS
PI_USM_CONCURRENT_ACCESS
PI_USM_CONCURRENT_ATOMIC_ACCESS
Definition at line 1967 of file pi.h.
_pi_usm_capability_query
enum _pi_usm_capability_query
Enumerator
PI_USM_HOST_SUPPORT
PI_USM_DEVICE_SUPPORT
PI_USM_SINGLE_SHARED_SUPPORT
PI_USM_CROSS_SHARED_SUPPORT
PI_USM_SYSTEM_SHARED_SUPPORT
Definition at line 1959 of file pi.h.
_pi_usm_migration_flags
enum _pi_usm_migration_flags : pi_bitfield
Enumerator
PI_USM_MIGRATION_TBD0
Definition at line 1991 of file pi.h.
_pi_usm_type
enum _pi_usm_type
Enumerator
PI_MEM_TYPE_UNKNOWN
PI_MEM_TYPE_HOST
PI_MEM_TYPE_DEVICE
PI_MEM_TYPE_SHARED
Definition at line 1981 of file pi.h.
pi_ext_structure_type
enum pi_ext_structure_type
Enumerator
PI_EXT_STRUCTURE_TYPE_COMMAND_BUFFER_DESC
Definition at line 2370 of file pi.h.
pi_property_type
enum pi_property_type
Enumerator
PI_PROPERTY_TYPE_UNKNOWN
PI_PROPERTY_TYPE_UINT32
PI_PROPERTY_TYPE_BYTE_ARRAY
PI_PROPERTY_TYPE_STRING
Definition at line 925 of file pi.h.
Function Documentation
piContextCreate()
pi_result piContextCreate (const pi_context_properties * properties, pi_uint32 num_devices, const pi_device * devices, void(*)(const char *errinfo, const void *private_info, size_t cb, void *user_data) pfn_notify, void * user_data, pi_context * ret_context)
Referenced by sycl::_V1::detail::context_impl::context_impl().
piContextGetInfo()
pi_result piContextGetInfo (pi_context context, pi_context_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 124 of file pi_cuda.cpp.
References pi2ur::piContextGetInfo().
Referenced by sycl::_V1::detail::context_impl::context_impl(), sycl::_V1::detail::MemoryManager::copy_2d_usm(), sycl::_V1::detail::createBinaryProgram(), sycl::_V1::detail::get_context_info(), and piPluginInit().
piContextRelease()
pi_result piContextRelease (pi_context context)
Definition at line 157 of file pi_cuda.cpp.
References pi2ur::piContextRelease().
Referenced by piPluginInit(), and sycl::_V1::detail::context_impl::~context_impl().
piContextRetain()
pi_result piContextRetain (pi_context context)
Definition at line 152 of file pi_cuda.cpp.
References pi2ur::piContextRetain().
Referenced by sycl::_V1::detail::context_impl::context_impl(), sycl::_V1::detail::context_impl::get(), sycl::_V1::detail::context_impl::getNative(), and piPluginInit().
piDeviceGetInfo()
pi_result piDeviceGetInfo (pi_device device, pi_device_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Returns requested info for provided native device Return PI_DEVICE_INFO_EXTENSION_DEVICELIB_ASSERT for PI_DEVICE_INFO_EXTENSIONS query when the device supports native asserts.
Definition at line 78 of file pi_cuda.cpp.
References pi2ur::piDeviceGetInfo().
Referenced by sycl::_V1::detail::applyAllowList(), sycl::_V1::device::ext_oneapi_cl_profile(), sycl::_V1::device::ext_oneapi_supports_cl_c_feature(), sycl::_V1::device::ext_oneapi_supports_cl_c_version(), sycl::_V1::device::ext_oneapi_supports_cl_extension(), sycl::_V1::detail::get_device_info_impl< ReturnT, Param >::get(), sycl::_V1::detail::get_device_info_impl< platform, Param >::get(), sycl::_V1::detail::get_device_info_impl< std::vector< info::fp_config >, Param >::get(), sycl::_V1::detail::get_device_info_impl< std::vector< info::fp_config >, info::device::single_fp_config >::get(), sycl::_V1::detail::get_device_info_impl< bool, info::device::queue_profiling >::get(), sycl::_V1::detail::get_device_info_impl< std::vector< memory_order >, info::device::atomic_memory_order_capabilities >::get(), sycl::_V1::detail::get_device_info_impl< std::vector< memory_order >, info::device::atomic_fence_order_capabilities >::get(), sycl::_V1::detail::get_device_info_impl< std::vector< memory_scope >, info::device::atomic_memory_scope_capabilities >::get(), sycl::_V1::detail::get_device_info_impl< std::vector< memory_scope >, info::device::atomic_fence_scope_capabilities >::get(), sycl::_V1::detail::get_device_info_impl< bool, info::device::ext_oneapi_bfloat16_math_functions >::get(), sycl::_V1::detail::get_device_info_impl< std::vector< info::execution_capability >, info::device::execution_capabilities >::get(), sycl::_V1::detail::get_device_info_impl< std::vector< info::partition_property >, info::device::partition_properties >::get(), sycl::_V1::detail::get_device_info_impl< std::vector< info::partition_affinity_domain >, info::device::partition_affinity_domains >::get(), sycl::_V1::detail::get_device_info_impl< info::partition_affinity_domain, info::device::partition_type_affinity_domain >::get(), sycl::_V1::detail::get_device_info_impl< info::partition_property, info::device::partition_type_property >::get(), sycl::_V1::detail::get_device_info_impl< std::vector< size_t >, info::device::sub_group_sizes >::get(), sycl::_V1::detail::get_device_info_impl< range< Dimensions >, info::device::max_work_item_sizes< Dimensions > >::get(), sycl::_V1::detail::get_device_info_impl< ext::oneapi::experimental::architecture, ext::oneapi::experimental::info::device::architecture >::get(), sycl::_V1::detail::get_device_info_impl< id< 1 >, ext::oneapi::experimental::info::device::max_work_groups< 1 > >::get(), sycl::_V1::detail::get_device_info_impl< id< 2 >, ext::oneapi::experimental::info::device::max_work_groups< 2 > >::get(), sycl::_V1::detail::get_device_info_impl< id< 3 >, ext::oneapi::experimental::info::device::max_work_groups< 3 > >::get(), sycl::_V1::detail::get_device_info_impl< device, info::device::parent_device >::get(), sycl::_V1::detail::get_device_info_impl< bool, info::device::usm_device_allocations >::get(), sycl::_V1::detail::get_device_info_impl< bool, info::device::usm_host_allocations >::get(), sycl::_V1::detail::get_device_info_impl< bool, info::device::usm_shared_allocations >::get(), sycl::_V1::detail::get_device_info_impl< bool, info::device::usm_restricted_shared_allocations >::get(), sycl::_V1::detail::get_device_info_impl< bool, info::device::usm_system_allocations >::get(), sycl::_V1::detail::get_device_info_impl< uint32_t, ext::codeplay::experimental::info::device::max_registers_per_work_group >::get(), sycl::_V1::detail::get_device_info_impl< std::vector< sycl::device >, ext::oneapi::experimental::info::device::component_devices >::get(), sycl::_V1::detail::get_device_info_impl< sycl::device, ext::oneapi::experimental::info::device::composite_device >::get(), sycl::_V1::detail::device_impl::get_device_info_string(), sycl::_V1::detail::ProgramManager::getBuiltPIProgram(), sycl::_V1::detail::platform_impl::getPlatformFromPiDevice(), sycl::_V1::detail::ProgramManager::getProgramBuildLog(), sycl::_V1::detail::enqueue_kernel_launch::handleInvalidValue(), sycl::_V1::detail::enqueue_kernel_launch::handleInvalidWorkGroupSize(), sycl::_V1::detail::enqueue_kernel_launch::handleInvalidWorkItemSize(), sycl::_V1::detail::device_impl::has(), sycl::_V1::opencl::has_extension(), and piPluginInit().
piDevicePartition()
pi_result piDevicePartition (pi_device device, const pi_device_partition_property * properties, pi_uint32 num_devices, pi_device * out_devices, pi_uint32 * out_num_devices)
Definition at line 85 of file pi_cuda.cpp.
References pi2ur::piDevicePartition().
Referenced by sycl::_V1::detail::device_impl::create_sub_devices(), and piPluginInit().
piDeviceRelease()
pi_result piDeviceRelease (pi_device device)
Definition at line 74 of file pi_cuda.cpp.
References pi2ur::piDeviceRelease().
Referenced by sycl::_V1::detail::platform_impl::get_devices(), piPluginInit(), and sycl::_V1::detail::device_impl::~device_impl().
piDeviceRetain()
pi_result piDeviceRetain (pi_device device)
Definition at line 70 of file pi_cuda.cpp.
References pi2ur::piDeviceRetain().
Referenced by sycl::_V1::detail::device_impl::get(), sycl::_V1::detail::device_impl::getNative(), and piPluginInit().
piDevicesGet()
pi_result piDevicesGet (pi_platform platform, pi_device_type device_type, pi_uint32 num_entries, pi_device * devices, pi_uint32 * num_devices)
Definition at line 63 of file pi_cuda.cpp.
References pi2ur::piDevicesGet().
Referenced by sycl::_V1::detail::platform_impl::get_devices(), and piPluginInit().
piEnqueueEventsWait()
pi_result piEnqueueEventsWait (pi_queue command_queue, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
Definition at line 657 of file pi_cuda.cpp.
References pi2ur::piEnqueueEventsWait().
Referenced by sycl::_V1::detail::MemoryManager::copy_2d_usm(), sycl::_V1::detail::MemoryManager::copy_usm(), sycl::_V1::detail::MemoryManager::fill_2d_usm(), sycl::_V1::detail::MemoryManager::fill_usm(), sycl::_V1::detail::MemoryManager::memset_2d_usm(), piPluginInit(), and sycl::_V1::detail::Command::waitForEvents().
piEnqueueEventsWaitWithBarrier()
pi_result piEnqueueEventsWaitWithBarrier (pi_queue command_queue, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
Definition at line 665 of file pi_cuda.cpp.
References pi2ur::piEnqueueEventsWaitWithBarrier().
Referenced by piPluginInit().
piEnqueueKernelLaunch()
pi_result piEnqueueKernelLaunch (pi_queue queue, pi_kernel kernel, pi_uint32 work_dim, const size_t * global_work_offset, const size_t * global_work_size, const size_t * local_work_size, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
Definition at line 537 of file pi_cuda.cpp.
References pi2ur::piEnqueueKernelLaunch().
Referenced by piPluginInit(), and sycl::_V1::detail::SetKernelParamsAndLaunch().
piEnqueueMemBufferCopy()
pi_result piEnqueueMemBufferCopy (pi_queue command_queue, pi_mem src_buffer, pi_mem dst_buffer, size_t src_offset, size_t dst_offset, size_t size, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
Definition at line 726 of file pi_cuda.cpp.
References pi2ur::piEnqueueMemBufferCopy().
Referenced by sycl::_V1::detail::copyD2D(), and piPluginInit().
piEnqueueMemBufferCopyRect()
pi_result piEnqueueMemBufferCopyRect (pi_queue command_queue, pi_mem src_buffer, pi_mem dst_buffer, pi_buff_rect_offset src_origin, pi_buff_rect_offset dst_origin, pi_buff_rect_region region, size_t src_row_pitch, size_t src_slice_pitch, size_t dst_row_pitch, size_t dst_slice_pitch, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
Definition at line 737 of file pi_cuda.cpp.
References pi2ur::piEnqueueMemBufferCopyRect().
Referenced by sycl::_V1::detail::copyD2D(), and piPluginInit().
piEnqueueMemBufferFill()
pi_result piEnqueueMemBufferFill (pi_queue command_queue, pi_mem buffer, const void * pattern, size_t pattern_size, size_t offset, size_t size, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
Definition at line 750 of file pi_cuda.cpp.
References pi2ur::piEnqueueMemBufferFill().
Referenced by sycl::_V1::detail::MemoryManager::fill(), and piPluginInit().
piEnqueueMemBufferMap()
pi_result piEnqueueMemBufferMap (pi_queue command_queue, pi_mem buffer, pi_bool blocking_map, pi_map_flags map_flags, size_t offset, size_t size, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event, void ** ret_map)
Definition at line 762 of file pi_cuda.cpp.
References pi2ur::piEnqueueMemBufferMap().
Referenced by sycl::_V1::detail::memBufferMapHelper(), and piPluginInit().
piEnqueueMemBufferRead()
pi_result piEnqueueMemBufferRead (pi_queue queue, pi_mem buffer, pi_bool blocking_read, size_t offset, size_t size, void * ptr, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
Definition at line 674 of file pi_cuda.cpp.
References pi2ur::piEnqueueMemBufferRead().
Referenced by sycl::_V1::detail::copyD2H(), and piPluginInit().
piEnqueueMemBufferReadRect()
pi_result piEnqueueMemBufferReadRect (pi_queue command_queue, pi_mem buffer, pi_bool blocking_read, pi_buff_rect_offset buffer_offset, pi_buff_rect_offset host_offset, pi_buff_rect_region region, size_t buffer_row_pitch, size_t buffer_slice_pitch, size_t host_row_pitch, size_t host_slice_pitch, void * ptr, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
Definition at line 686 of file pi_cuda.cpp.
References pi2ur::piEnqueueMemBufferReadRect().
Referenced by sycl::_V1::detail::copyD2H(), and piPluginInit().
piEnqueueMemBufferWrite()
pi_result piEnqueueMemBufferWrite (pi_queue command_queue, pi_mem buffer, pi_bool blocking_write, size_t offset, size_t size, const void * ptr, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
Definition at line 700 of file pi_cuda.cpp.
References pi2ur::piEnqueueMemBufferWrite().
Referenced by sycl::_V1::detail::copyH2D(), and piPluginInit().
piEnqueueMemBufferWriteRect()
pi_result piEnqueueMemBufferWriteRect (pi_queue command_queue, pi_mem buffer, pi_bool blocking_write, pi_buff_rect_offset buffer_offset, pi_buff_rect_offset host_offset, pi_buff_rect_region region, size_t buffer_row_pitch, size_t buffer_slice_pitch, size_t host_row_pitch, size_t host_slice_pitch, const void * ptr, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
Definition at line 712 of file pi_cuda.cpp.
References pi2ur::piEnqueueMemBufferWriteRect().
Referenced by sycl::_V1::detail::copyH2D(), and piPluginInit().
piEnqueueMemImageCopy()
pi_result piEnqueueMemImageCopy (pi_queue command_queue, pi_mem src_image, pi_mem dst_image, pi_image_offset src_origin, pi_image_offset dst_origin, pi_image_region region, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
Definition at line 815 of file pi_cuda.cpp.
References pi2ur::piEnqueueMemImageCopy().
Referenced by sycl::_V1::detail::copyD2D(), and piPluginInit().
piEnqueueMemImageFill()
pi_result piEnqueueMemImageFill (pi_queue command_queue, pi_mem image, const void * fill_color, const size_t * origin, const size_t * region, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
Definition at line 824 of file pi_cuda.cpp.
References pi2ur::piEnqueueMemImageFill().
Referenced by sycl::_V1::detail::MemoryManager::fill(), and piPluginInit().
piEnqueueMemImageRead()
pi_result piEnqueueMemImageRead (pi_queue command_queue, pi_mem image, pi_bool blocking_read, pi_image_offset origin, pi_image_region region, size_t row_pitch, size_t slice_pitch, void * ptr, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
Definition at line 789 of file pi_cuda.cpp.
References pi2ur::piEnqueueMemImageRead().
Referenced by piPluginInit().
piEnqueueMemImageWrite()
pi_result piEnqueueMemImageWrite (pi_queue command_queue, pi_mem image, pi_bool blocking_write, pi_image_offset origin, pi_image_region region, size_t input_row_pitch, size_t input_slice_pitch, const void * ptr, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
Definition at line 801 of file pi_cuda.cpp.
References pi2ur::piEnqueueMemImageWrite().
Referenced by piPluginInit().
piEnqueueMemUnmap()
pi_result piEnqueueMemUnmap (pi_queue command_queue, pi_mem memobj, void * mapped_ptr, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
Definition at line 773 of file pi_cuda.cpp.
References pi2ur::piEnqueueMemUnmap().
Referenced by sycl::_V1::detail::memUnmapHelper(), and piPluginInit().
piEventCreate()
pi_result piEventCreate (pi_context context, pi_event * ret_event)
Create PI event object in a signalled/completed state.
Parameters
context is the PI context of the event.
ret_event is the PI even created.
Definition at line 579 of file pi_cuda.cpp.
References pi2ur::piEventCreate().
Referenced by piPluginInit().
piEventGetInfo()
pi_result piEventGetInfo (pi_event event, pi_event_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 583 of file pi_cuda.cpp.
References pi2ur::piEventGetInfo().
Referenced by sycl::_V1::detail::event_impl::event_impl(), sycl::_V1::detail::event_impl::flushIfNeeded(), sycl::_V1::detail::get_event_info(), and piPluginInit().
piEventGetProfilingInfo()
pi_result piEventGetProfilingInfo (pi_event event, pi_profiling_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 590 of file pi_cuda.cpp.
References pi2ur::piEventGetProfilingInfo().
Referenced by sycl::_V1::detail::get_event_profiling_info(), and piPluginInit().
piEventRelease()
pi_result piEventRelease (pi_event event)
Definition at line 617 of file pi_cuda.cpp.
References pi2ur::piEventRelease().
Referenced by sycl::_V1::detail::DeviceGlobalUSMMem::getInitEvent(), sycl::_V1::detail::context_impl::initializeDeviceGlobals(), piPluginInit(), sycl::_V1::detail::DeviceGlobalMapEntry::removeAssociatedResources(), sycl::_V1::detail::event_impl::~event_impl(), and sycl::_V1::detail::OwnedPiEvent::~OwnedPiEvent().
piEventRetain()
pi_result piEventRetain (pi_event event)
Definition at line 615 of file pi_cuda.cpp.
References pi2ur::piEventRetain().
Referenced by sycl::_V1::detail::MemoryManager::allocateInteropMemObject(), sycl::_V1::detail::event_impl::getNative(), sycl::_V1::detail::make_event(), sycl::_V1::detail::OwnedPiEvent::OwnedPiEvent(), and piPluginInit().
piEventSetCallback()
pi_result piEventSetCallback (pi_event event, pi_int32 command_exec_callback_type, void(*)(pi_event event, pi_int32 event_command_status, void *user_data) pfn_notify, void * user_data)
piEventSetStatus()
pi_result piEventSetStatus (pi_event event, pi_int32 execution_status)
Definition at line 611 of file pi_cuda.cpp.
References pi2ur::piEventSetStatus().
Referenced by piPluginInit().
piEventsWait()
pi_result piEventsWait (pi_uint32 num_events, const pi_event * event_list)
Definition at line 598 of file pi_cuda.cpp.
References pi2ur::piEventsWait().
Referenced by sycl::_V1::detail::memUnmapHelper(), piPluginInit(), sycl::_V1::detail::waitForEvents(), sycl::_V1::detail::Command::waitForEvents(), and sycl::_V1::detail::event_impl::waitInternal().
piextBindlessImageSamplerCreate()
pi_result piextBindlessImageSamplerCreate (pi_context context, const pi_sampler_properties * sampler_properties, float min_mipmap_level_clamp, float max_mipmap_level_clamp, float max_anisotropy, pi_sampler * result_sampler)
API to create samplers for bindless images.
Parameters
context is the pi_context
device is the pi_device
sampler_properties is the pointer to the sampler properties bitfield
min_mipmap_level_clamp is the minimum mipmap level to sample from
max_mipmap_level_clamp is the maximum mipmap level to sample from
max_anisotropy is the maximum anisotropic ratio
result_sampler is the returned sampler
Definition at line 400 of file pi_cuda.cpp.
References pi2ur::piextBindlessImageSamplerCreate().
Referenced by sycl::_V1::ext::oneapi::experimental::create_image().
piextCommandBufferAdviseUSM()
pi_result piextCommandBufferAdviseUSM (pi_ext_command_buffer command_buffer, const void * ptr, size_t length, pi_mem_advice advice, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a USM Advise command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
ptr is the data to be advised.
length is the size in bytes of the memory to advise.
advice is device specific advice.
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1204 of file pi_cuda.cpp.
References pi2ur::piextCommandBufferAdviseUSM().
Referenced by sycl::_V1::detail::MemoryManager::ext_oneapi_advise_usm_cmd_buffer().
piextCommandBufferCreate()
pi_result piextCommandBufferCreate (pi_context context, pi_device device, const pi_ext_command_buffer_desc * desc, pi_ext_command_buffer * ret_command_buffer)
API to create a command-buffer.
Parameters
context The context to associate the command-buffer with.
device The device to associate the command-buffer with.
desc Descriptor for the new command-buffer.
ret_command_buffer Pointer to fill with the address of the new command-buffer.
Definition at line 1068 of file pi_cuda.cpp.
References pi2ur::piextCommandBufferCreate().
Referenced by sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::createCommandBuffers().
piextCommandBufferFillUSM()
pi_result piextCommandBufferFillUSM (pi_ext_command_buffer command_buffer, void * ptr, const void * pattern, size_t pattern_size, size_t size, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a USM fill command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
ptr pointer to the USM allocation to fill.
pattern pointer to the pattern to fill ptr with.
pattern_size size of the pattern in bytes.
size fill size in bytes.
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1184 of file pi_cuda.cpp.
References pi2ur::piextCommandBufferFillUSM().
Referenced by sycl::_V1::detail::MemoryManager::ext_oneapi_fill_usm_cmd_buffer().
piextCommandBufferFinalize()
pi_result piextCommandBufferFinalize (pi_ext_command_buffer command_buffer)
API to stop command-buffer recording such that no more commands can be appended, and makes the command-buffer ready to enqueue on a command-queue.
Parameters
command_buffer The command_buffer to finalize.
Definition at line 1083 of file pi_cuda.cpp.
References pi2ur::piextCommandBufferFinalize().
Referenced by sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::createCommandBuffers().
piextCommandBufferMemBufferCopy()
pi_result piextCommandBufferMemBufferCopy (pi_ext_command_buffer command_buffer, pi_mem src_buffer, pi_mem dst_buffer, size_t src_offset, size_t dst_offset, size_t size, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a mem buffer copy command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
src_buffer is the data to be copied
dst_buffer is the location the data will be copied
src_offset offset into src_buffer
dst_offset offset into dst_buffer
size is number of bytes to copy
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1108 of file pi_cuda.cpp.
References pi2ur::piextCommandBufferMemBufferCopy().
Referenced by sycl::_V1::detail::MemoryManager::ext_oneapi_copyD2D_cmd_buffer().
piextCommandBufferMemBufferCopyRect()
pi_result piextCommandBufferMemBufferCopyRect (pi_ext_command_buffer command_buffer, pi_mem src_buffer, pi_mem dst_buffer, pi_buff_rect_offset src_origin, pi_buff_rect_offset dst_origin, pi_buff_rect_region region, size_t src_row_pitch, size_t src_slice_pitch, size_t dst_row_pitch, size_t dst_slice_pitch, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a rectangular mem buffer copy command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
src_buffer is the data to be copied
dst_buffer is the location the data will be copied
src_origin offset for the start of the region to copy in src_buffer
dst_origin offset for the start of the region to copy in dst_buffer
region The size of the region to be copied
src_row_pitch Row pitch for the src data
src_slice_pitch Slice pitch for the src data
dst_row_pitch Row pitch for the dst data
dst_slice_pitch Slice pitch for the dst data
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1118 of file pi_cuda.cpp.
References pi2ur::piextCommandBufferMemBufferCopyRect().
Referenced by sycl::_V1::detail::MemoryManager::ext_oneapi_copyD2D_cmd_buffer().
piextCommandBufferMemBufferFill()
pi_result piextCommandBufferMemBufferFill (pi_ext_command_buffer command_buffer, pi_mem buffer, const void * pattern, size_t pattern_size, size_t offset, size_t size, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a mem buffer fill command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
buffer is the location to fill the data.
pattern pointer to the pattern to fill the buffer with.
pattern_size size of the pattern in bytes.
offset Offset into the buffer to fill from.
size fill size in bytes.
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1174 of file pi_cuda.cpp.
References pi2ur::piextCommandBufferMemBufferFill().
Referenced by sycl::_V1::detail::MemoryManager::ext_oneapi_fill_cmd_buffer().
piextCommandBufferMemBufferRead()
pi_result piextCommandBufferMemBufferRead (pi_ext_command_buffer command_buffer, pi_mem buffer, size_t offset, size_t size, void * dst, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a mem buffer read command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
buffer is the data to be read
offset offset into buffer
size is number of bytes to read
dst is the pointer to the destination
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1130 of file pi_cuda.cpp.
References pi2ur::piextCommandBufferMemBufferRead().
Referenced by sycl::_V1::detail::MemoryManager::ext_oneapi_copyD2H_cmd_buffer().
piextCommandBufferMemBufferReadRect()
pi_result piextCommandBufferMemBufferReadRect (pi_ext_command_buffer command_buffer, pi_mem buffer, pi_buff_rect_offset buffer_offset, pi_buff_rect_offset host_offset, pi_buff_rect_region region, size_t buffer_row_pitch, size_t buffer_slice_pitch, size_t host_row_pitch, size_t host_slice_pitch, void * ptr, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a rectangular mem buffer read command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
buffer is the data to be read
buffer_offset offset for the start of the region to read in buffer
host_offset offset for the start of the region to be written from ptr
region The size of the region to read
buffer_row_pitch Row pitch for the source buffer data
buffer_slice_pitch Slice pitch for the source buffer data
host_row_pitch Row pitch for the destination data ptr
host_slice_pitch Slice pitch for the destination data ptr
ptr is the location the data will be written
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1139 of file pi_cuda.cpp.
References pi2ur::piextCommandBufferMemBufferReadRect().
Referenced by sycl::_V1::detail::MemoryManager::ext_oneapi_copyD2H_cmd_buffer().
piextCommandBufferMemBufferWrite()
pi_result piextCommandBufferMemBufferWrite (pi_ext_command_buffer command_buffer, pi_mem buffer, size_t offset, size_t size, const void * ptr, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a mem buffer write command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
buffer is the location to write the data
offset offset into buffer
size is number of bytes to write
ptr is the pointer to the source
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1152 of file pi_cuda.cpp.
References pi2ur::piextCommandBufferMemBufferWrite().
Referenced by sycl::_V1::detail::MemoryManager::ext_oneapi_copyH2D_cmd_buffer().
piextCommandBufferMemBufferWriteRect()
pi_result piextCommandBufferMemBufferWriteRect (pi_ext_command_buffer command_buffer, pi_mem buffer, pi_buff_rect_offset buffer_offset, pi_buff_rect_offset host_offset, pi_buff_rect_region region, size_t buffer_row_pitch, size_t buffer_slice_pitch, size_t host_row_pitch, size_t host_slice_pitch, const void * ptr, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a rectangular mem buffer write command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
buffer is the location to write the data
buffer_offset offset for the start of the region to write in buffer
host_offset offset for the start of the region to be read from ptr
region The size of the region to write
buffer_row_pitch Row pitch for the buffer data
buffer_slice_pitch Slice pitch for the buffer data
host_row_pitch Row pitch for the source data ptr
host_slice_pitch Slice pitch for the source data ptr
ptr is the pointer to the source
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1161 of file pi_cuda.cpp.
References pi2ur::piextCommandBufferMemBufferWriteRect().
Referenced by sycl::_V1::detail::MemoryManager::ext_oneapi_copyH2D_cmd_buffer().
piextCommandBufferMemcpyUSM()
pi_result piextCommandBufferMemcpyUSM (pi_ext_command_buffer command_buffer, void * dst_ptr, const void * src_ptr, size_t size, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a USM memcpy command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
dst_ptr is the location the data will be copied
src_ptr is the data to be copied
size is number of bytes to copy
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1099 of file pi_cuda.cpp.
References pi2ur::piextCommandBufferMemcpyUSM().
Referenced by sycl::_V1::detail::MemoryManager::ext_oneapi_copy_usm_cmd_buffer().
piextCommandBufferNDRangeKernel()
pi_result piextCommandBufferNDRangeKernel (pi_ext_command_buffer command_buffer, pi_kernel kernel, pi_uint32 work_dim, const size_t * global_work_offset, const size_t * global_work_size, const size_t * local_work_size, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point, pi_ext_command_buffer_command * command)
API to append a kernel execution command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
kernel The kernel to append.
work_dim Dimension of the kernel execution.
global_work_offset Offset to use when executing kernel.
global_work_size Global work size to use when executing kernel.
local_work_size Local work size to use when executing kernel.
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this kernel execution.
command Return pointer to the command representing this kernel execution.
Definition at line 1087 of file pi_cuda.cpp.
References pi2ur::piextCommandBufferNDRangeKernel().
Referenced by sycl::_V1::detail::enqueueImpCommandBufferKernel().
piextCommandBufferPrefetchUSM()
pi_result piextCommandBufferPrefetchUSM (pi_ext_command_buffer command_buffer, const void * ptr, size_t size, pi_usm_migration_flags flags, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a USM Prefetch command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
ptr points to the memory to migrate.
size is the number of bytes to migrate.
flags is a bitfield used to specify memory migration options.
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1195 of file pi_cuda.cpp.
References pi2ur::piextCommandBufferPrefetchUSM().
Referenced by sycl::_V1::detail::MemoryManager::ext_oneapi_prefetch_usm_cmd_buffer().
piextCommandBufferRelease()
pi_result piextCommandBufferRelease (pi_ext_command_buffer command_buffer)
API to decrement the reference count of the command-buffer.
After the command_buffer reference count becomes zero and has finished execution, the command-buffer is deleted.
Parameters
command_buffer The command_buffer to release.
Definition at line 1079 of file pi_cuda.cpp.
References pi2ur::piextCommandBufferRelease().
Referenced by sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::~exec_graph_impl().
piextCommandBufferReleaseCommand()
pi_result piextCommandBufferReleaseCommand (pi_ext_command_buffer_command command)
API to decrement the reference count of a command-buffer command.
After the command reference count becomes zero, the command is deleted.
Parameters
command The command to release.
Definition at line 1234 of file pi_cuda.cpp.
References pi2ur::piextCommandBufferReleaseCommand().
Referenced by sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::~exec_graph_impl().
piextCommandBufferRetain()
pi_result piextCommandBufferRetain (pi_ext_command_buffer command_buffer)
API to increment the reference count of the command-buffer.
Parameters
command_buffer The command_buffer to retain.
Definition at line 1075 of file pi_cuda.cpp.
References pi2ur::piextCommandBufferRetain().
piextCommandBufferRetainCommand()
pi_result piextCommandBufferRetainCommand (pi_ext_command_buffer_command command)
API to increment the reference count of a command-buffer command.
Parameters
command The command to release.
Definition at line 1229 of file pi_cuda.cpp.
References pi2ur::piextCommandBufferRetainCommand().
piextCommandBufferUpdateKernelLaunch()
pi_result piextCommandBufferUpdateKernelLaunch (pi_ext_command_buffer_command command, pi_ext_command_buffer_update_kernel_launch_desc * desc)
API to update a kernel launch command inside of a command-buffer.
Parameters
command The command to be updated.
desc Descriptor which describes the updated parameters of the kernel launch.
Definition at line 1222 of file pi_cuda.cpp.
References pi2ur::piextCommandBufferUpdateKernelLaunch().
Referenced by sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::updateImpl().
piextContextCreateWithNativeHandle()
pi_result piextContextCreateWithNativeHandle (pi_native_handle nativeHandle, pi_uint32 numDevices, const pi_device * devices, bool pluginOwnsNativeHandle, pi_context * context)
Creates PI context object from a native handle.
NOTE: The created PI object takes ownership of the native handle. NOTE: The number of devices and the list of devices is needed for Level Zero backend because there is no possilibity to query this information from context handle for Level Zero. If backend has API to query a list of devices from the context native handle then these parameters are ignored.
Parameters
nativeHandle is the native handle to create PI context from.
numDevices is the number of devices in the context. Parameter is ignored if number of devices can be queried from the context native handle for a backend.
devices is the list of devices in the context. Parameter is ignored if devices can be queried from the context native handle for a backend.
pluginOwnsNativeHandle Indicates whether the created PI object should take ownership of the native handle.
context is the PI context created from the native handle.
Returns
PI_SUCCESS if successfully created pi_context from the handle. PI_ERROR_OUT_OF_HOST_MEMORY if can't allocate memory for the pi_context object. PI_ERROR_INVALID_VALUE if numDevices == 0 or devices is NULL but backend doesn't have API to query a list of devices from the context native handle. PI_UNKNOWN_ERROR in case of another error.
Definition at line 143 of file pi_cuda.cpp.
References pi2ur::piextContextCreateWithNativeHandle().
Referenced by sycl::_V1::ext::oneapi::level_zero::make_context(), sycl::_V1::detail::make_context(), and piPluginInit().
piextContextGetNativeHandle()
pi_result piextContextGetNativeHandle (pi_context context, pi_native_handle * nativeHandle)
Gets the native handle of a PI context object.
Parameters
context is the PI context to get the native handle of.
nativeHandle is the native handle of context.
Definition at line 138 of file pi_cuda.cpp.
References pi2ur::piextContextGetNativeHandle().
Referenced by sycl::_V1::detail::context_impl::getNative(), and piPluginInit().
piextContextSetExtendedDeleter()
pi_result piextContextSetExtendedDeleter (pi_context context, pi_context_extended_deleter func, void * user_data)
Definition at line 132 of file pi_cuda.cpp.
References pi2ur::piextContextSetExtendedDeleter().
Referenced by sycl::_V1::detail::pi::contextSetExtendedDeleter(), and piPluginInit().
piextDestroyExternalSemaphore()
pi_result piextDestroyExternalSemaphore (pi_context context, pi_device device, pi_interop_semaphore_handle sem_handle)
API to destroy the external semaphore handle.
Parameters
context is the pi_context
device is the pi_device
sem_handle is the interop semaphore handle to the external semaphore to be destroyed
Definition at line 487 of file pi_cuda.cpp.
References pi2ur::piextDestroyExternalSemaphore().
Referenced by sycl::_V1::ext::oneapi::experimental::destroy_external_semaphore().
piextDeviceCreateWithNativeHandle()
pi_result piextDeviceCreateWithNativeHandle (pi_native_handle nativeHandle, pi_platform platform, pi_device * device)
Creates PI device object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI device from.
platform is the platform of the device (optional).
device is the PI device created from the native handle.
Definition at line 106 of file pi_cuda.cpp.
References pi2ur::piextDeviceCreateWithNativeHandle().
Referenced by sycl::_V1::ext::oneapi::level_zero::make_device(), sycl::_V1::detail::make_device(), and piPluginInit().
piextDeviceGetNativeHandle()
pi_result piextDeviceGetNativeHandle (pi_device device, pi_native_handle * nativeHandle)
Gets the native handle of a PI device object.
Parameters
device is the PI device to get the native handle of.
nativeHandle is the native handle of device.
Definition at line 100 of file pi_cuda.cpp.
References pi2ur::piextDeviceGetNativeHandle().
Referenced by sycl::_V1::detail::device_impl::getNative(), and piPluginInit().
piextDeviceSelectBinary()
pi_result piextDeviceSelectBinary (pi_device device, pi_device_binary * binaries, pi_uint32 num_binaries, pi_uint32 * selected_binary_ind)
Selects the most appropriate device binary based on runtime information and the IR characteristics.
Definition at line 93 of file pi_cuda.cpp.
References pi2ur::piextDeviceSelectBinary().
Referenced by sycl::_V1::detail::compatibleWithDevice(), sycl::_V1::detail::getBinImageFromMultiMap(), sycl::_V1::detail::ProgramManager::getDeviceImage(), and piPluginInit().
piextDisablePeerAccess()
pi_result piextDisablePeerAccess (pi_device command_device, pi_device peer_device)
Definition at line 1258 of file pi_cuda.cpp.
References pi2ur::piextDisablePeerAccess().
Referenced by sycl::_V1::device::ext_oneapi_disable_peer_access(), and piPluginInit().
piextEnablePeerAccess()
pi_result piextEnablePeerAccess (pi_device command_device, pi_device peer_device)
Definition at line 1252 of file pi_cuda.cpp.
References pi2ur::piextEnablePeerAccess().
Referenced by sycl::_V1::device::ext_oneapi_enable_peer_access(), and piPluginInit().
piextEnqueueCommandBuffer()
pi_result piextEnqueueCommandBuffer (pi_ext_command_buffer command_buffer, pi_queue queue, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
API to submit the command-buffer to queue for execution, returns an error if the command-buffer is not finalized or another instance of the same command-buffer is currently executing.
Parameters
command_buffer The command-buffer to be submitted.
queue The PI queue to submit on.
num_events_in_wait_list The number of events that this execution depends on.
event_wait_list List of pi_events to wait on.
event The pi_event associated with this enqueue.
Definition at line 1213 of file pi_cuda.cpp.
References pi2ur::piextEnqueueCommandBuffer().
Referenced by sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::enqueue().
piextEnqueueCooperativeKernelLaunch()
pi_result piextEnqueueCooperativeKernelLaunch (pi_queue queue, pi_kernel kernel, pi_uint32 work_dim, const size_t * global_work_offset, const size_t * global_work_size, const size_t * local_work_size, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
Definition at line 547 of file pi_cuda.cpp.
References pi2ur::piextEnqueueCooperativeKernelLaunch().
Referenced by sycl::_V1::detail::SetKernelParamsAndLaunch().
piextEnqueueDeviceGlobalVariableRead()
pi_result piextEnqueueDeviceGlobalVariableRead (pi_queue Queue, pi_program Program, const char * Name, pi_bool BlockingRead, size_t Count, size_t Offset, void * Dst, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * Event)
API reading data from a device global variable to host.
Parameters
queue is the queue
program is the program containing the device global variable
blocking_read is true if the read should block
name is the unique identifier for the device global variable
count is the number of bytes to copy
offset is the byte offset into the device global variable to start copying
dst is a pointer to where the data must be copied to
num_events_in_wait_list is a number of events in the wait list
event_wait_list is the wait list
event is the resulting event
Queue is the queue
Program is the program containing the device global variable
Name is the unique identifier for the device global variable
BlockingRead is true if the read should block
Count is the number of bytes to copy
Offset is the byte offset into the device global variable to start copying
Dst is a pointer to where the data must be copied to
NumEventsInWaitList is a number of events in the wait list
EventWaitList is the wait list
Event is the resulting event
Definition at line 1002 of file pi_cuda.cpp.
References pi2ur::piextEnqueueDeviceGlobalVariableRead().
Referenced by sycl::_V1::detail::memcpyFromDeviceGlobalDirect(), and piPluginInit().
piextEnqueueDeviceGlobalVariableWrite()
pi_result piextEnqueueDeviceGlobalVariableWrite (pi_queue Queue, pi_program Program, const char * Name, pi_bool BlockingWrite, size_t Count, size_t Offset, const void * Src, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * Event)
Device global variable.
API for writing data from host to a device global variable.
Parameters
queue is the queue
program is the program containing the device global variable
blocking_write is true if the write should block
name is the unique identifier for the device global variable
count is the number of bytes to copy
offset is the byte offset into the device global variable to start copying
src is a pointer to where the data must be copied from
num_events_in_wait_list is a number of events in the wait list
event_wait_list is the wait list
event is the resulting event
Device global variable.
Parameters
Queue is the queue
Program is the program containing the device global variable
Name is the unique identifier for the device global variable
BlockingWrite is true if the write should block
Count is the number of bytes to copy
Offset is the byte offset into the device global variable to start copying
Src is a pointer to where the data must be copied from
NumEventsInWaitList is a number of events in the wait list
EventWaitList is the wait list
Event is the resulting event
Definition at line 993 of file pi_cuda.cpp.
References pi2ur::piextEnqueueDeviceGlobalVariableWrite().
Referenced by sycl::_V1::detail::context_impl::initializeDeviceGlobals(), sycl::_V1::detail::memcpyToDeviceGlobalDirect(), and piPluginInit().
piextEnqueueReadHostPipe()
pi_result piextEnqueueReadHostPipe (pi_queue Queue, pi_program Program, const char * PipeSymbol, pi_bool Blocking, void * Ptr, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * Event)
Plugin.
Read from pipe of a given name
Parameters
queue a valid host command-queue in which the read / write command will be queued. command_queue and program must be created with the same OpenCL context.
program a program object with a successfully built executable.
pipe_symbol the name of the program scope pipe global variable.
blocking indicate if the read and write operations are blocking or non-blocking
ptr a pointer to buffer in host memory that will hold resulting data from pipe
size size of the memory region to read or write, in bytes.
num_events_in_waitlist number of events in the wait list.
events_waitlist specify events that need to complete before this particular command can be executed.
event returns an event object that identifies this read / write command and can be used to query or queue a wait for this command to complete.
Plugin.
Parameters
Queue is the queue
Program is the program containing the device variable
PipeSymbol is the unique identifier for the device variable
Blocking is true if the write should block
Ptr is a pointer to where the data will be copied to
Size is size of the data that is read/written from/to pipe
NumEventsInWaitList is a number of events in the wait list
EventWaitList is the wait list
Event is the resulting event
Definition at line 1013 of file pi_cuda.cpp.
References sycl::_V1::detail::pi::die(), PI_ASSERT, and pi2ur::piextEnqueueReadHostPipe().
Referenced by sycl::_V1::detail::enqueueReadWriteHostPipe().
piextEnqueueWriteHostPipe()
pi_result piextEnqueueWriteHostPipe (pi_queue Queue, pi_program Program, const char * PipeSymbol, pi_bool Blocking, void * Ptr, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * Event)
Write to pipe of a given name.
Parameters
queue a valid host command-queue in which the read / write command will be queued. command_queue and program must be created with the same OpenCL context.
program a program object with a successfully built executable.
pipe_symbol the name of the program scope pipe global variable.
blocking indicate if the read and write operations are blocking or non-blocking
ptr a pointer to buffer in host memory that holds data to be written to host pipe.
size size of the memory region to read or write, in bytes.
num_events_in_waitlist number of events in the wait list.
events_waitlist specify events that need to complete before this particular command can be executed.
event returns an event object that identifies this read / write command and can be used to query or queue a wait for this command to complete.
Write to pipe of a given name.
Parameters
Queue is the queue
Program is the program containing the device variable
PipeSymbol is the unique identifier for the device variable
Blocking is true if the write should block
Ptr is a pointer to where the data must be copied from
Size is size of the data that is read/written from/to pipe
NumEventsInWaitList is a number of events in the wait list
EventWaitList is the wait list
Event is the resulting event
Definition at line 1033 of file pi_cuda.cpp.
References sycl::_V1::detail::pi::die(), PI_ASSERT, and pi2ur::piextEnqueueWriteHostPipe().
Referenced by sycl::_V1::detail::enqueueReadWriteHostPipe().
piextEventCreateWithNativeHandle()
pi_result piextEventCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, bool ownNativeHandle, pi_event * event)
Creates PI event object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI event from.
context is the corresponding PI context
pluginOwnsNativeHandle Indicates whether the created PI object should take ownership of the native handle.
event is the PI event created from the native handle.
Definition at line 627 of file pi_cuda.cpp.
References pi2ur::piextEventCreateWithNativeHandle().
Referenced by sycl::_V1::detail::make_event(), and piPluginInit().
piextEventGetNativeHandle()
pi_result piextEventGetNativeHandle (pi_event event, pi_native_handle * nativeHandle)
Gets the native handle of a PI event object.
Parameters
event is the PI event to get the native handle of.
nativeHandle is the native handle of event.
Definition at line 621 of file pi_cuda.cpp.
References pi2ur::piextEventGetNativeHandle().
Referenced by sycl::_V1::detail::event_impl::getNative(), and piPluginInit().
piextGetDeviceFunctionPointer()
pi_result piextGetDeviceFunctionPointer (pi_device device, pi_program program, const char * function_name, pi_uint64 * function_pointer_ret)
Retrieves a device function pointer to a user-defined function.
function_name.
function_pointer_ret is set to 0 if query failed.
program must be built before calling this API.
device must present in the list of devices returned by get_device method for
program.
If a fallback method determines the function exists but the address is not available PI_ERROR_FUNCTION_ADDRESS_IS_NOT_AVAILABLE is returned. If the address does not exist PI_ERROR_INVALID_KERNEL_NAME is returned.
Definition at line 844 of file pi_cuda.cpp.
References pi2ur::piextGetDeviceFunctionPointer().
Referenced by sycl::_V1::detail::program_impl::has_kernel(), and piPluginInit().
piextGetGlobalVariablePointer()
pi_result piextGetGlobalVariablePointer (pi_device Device, pi_program Program, const char * GlobalVariableName, size_t * GlobalVariableSize, void ** GlobalVariablePointerRet)
Definition at line 851 of file pi_cuda.cpp.
References pi2ur::piextGetGlobalVariablePointer().
Referenced by piPluginInit().
piextImportExternalSemaphoreOpaqueFD()
pi_result piextImportExternalSemaphoreOpaqueFD (pi_context context, pi_device device, int file_descriptor, pi_interop_semaphore_handle * ret_handle)
API to import an external semaphore in the form of a file descriptor.
Parameters
context is the pi_context
device is the pi_device
file_descriptor is the file descriptor
ret_handle is the returned interop semaphore handle to the external semaphore
Definition at line 479 of file pi_cuda.cpp.
References pi2ur::piextImportExternalSemaphoreOpaqueFD().
Referenced by sycl::_V1::ext::oneapi::experimental::import_external_semaphore().
piextKernelCreateWithNativeHandle()
pi_result piextKernelCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, pi_program program, bool pluginOwnsNativeHandle, pi_kernel * kernel)
Creates PI kernel object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI kernel from.
context is the PI context of the kernel.
program is the PI program of the kernel.
pluginOwnsNativeHandle Indicates whether the created PI object should take ownership of the native handle.
kernel is the PI kernel created from the native handle.
Definition at line 557 of file pi_cuda.cpp.
References pi2ur::piextKernelCreateWithNativeHandle().
Referenced by sycl::_V1::detail::make_kernel(), and piPluginInit().
piextKernelGetNativeHandle()
pi_result piextKernelGetNativeHandle (pi_kernel kernel, pi_native_handle * nativeHandle)
Gets the native handle of a PI kernel object.
Parameters
kernel is the PI kernel to get the native handle of.
nativeHandle is the native handle of kernel.
Definition at line 567 of file pi_cuda.cpp.
References pi2ur::piextKernelGetNativeHandle().
Referenced by sycl::_V1::detail::kernel_impl::getNative().
piextKernelSetArgMemObj()
pi_result piextKernelSetArgMemObj (pi_kernel kernel, pi_uint32 arg_index, const pi_mem_obj_property * arg_properties, const pi_mem * arg_value)
Definition at line 353 of file pi_cuda.cpp.
References pi2ur::piextKernelSetArgMemObj().
Referenced by piPluginInit(), and sycl::_V1::detail::SetArgBasedOnType().
piextKernelSetArgPointer()
pi_result piextKernelSetArgPointer (pi_kernel kernel, pi_uint32 arg_index, size_t arg_size, const void * arg_value)
Sets up pointer arguments for CL kernels.
An extra indirection is required due to CL argument conventions.
Parameters
kernel is the kernel to be launched
arg_index is the index of the kernel argument
arg_size is the size in bytes of the argument (ignored in CL)
arg_value is the pointer argument
Definition at line 900 of file pi_cuda.cpp.
References pi2ur::piextKernelSetArgPointer().
Referenced by piPluginInit(), and sycl::_V1::detail::SetArgBasedOnType().
piextKernelSetArgSampler()
pi_result piextKernelSetArgSampler (pi_kernel kernel, pi_uint32 arg_index, const pi_sampler * arg_value)
Definition at line 360 of file pi_cuda.cpp.
References pi2ur::piextKernelSetArgSampler().
Referenced by piPluginInit(), and sycl::_V1::detail::SetArgBasedOnType().
piextKernelSuggestMaxCooperativeGroupCount()
pi_result piextKernelSuggestMaxCooperativeGroupCount (pi_kernel kernel, size_t local_work_size, size_t dynamic_shared_memory_size, pi_uint32 * group_count_ret)
Gets the max work group count for a cooperative kernel.
Parameters
kernel is the PI kernel being queried.
local_work_size is the number of work items in a work group that will be used when the kernel is launched.
dynamic_shared_memory_size is the size of dynamic shared memory, for each work group, in bytes, that will be used when the kernel is launched."
group_count_ret is a pointer to where the query result will be stored.
Definition at line 572 of file pi_cuda.cpp.
References pi2ur::piextKernelSuggestMaxCooperativeGroupCount().
Referenced by sycl::_V1::detail::kernel_impl::ext_oneapi_get_info< ext::oneapi::experimental::info::kernel_queue_specific::max_num_work_group_sync >().
piextMemCreateWithNativeHandle()
pi_result piextMemCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, bool ownNativeHandle, pi_mem * mem)
Creates PI mem object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI mem from.
context The PI context of the memory allocation.
ownNativeHandle Indicates if we own the native memory handle or it came from interop that asked to not transfer the ownership to SYCL RT.
mem is the PI mem created from the native handle.
Definition at line 241 of file pi_cuda.cpp.
References pi2ur::piextMemCreateWithNativeHandle().
Referenced by piPluginInit(), and sycl::_V1::detail::SYCLMemObjT::SYCLMemObjT().
piextMemGetNativeHandle()
pi_result piextMemGetNativeHandle (pi_mem mem, pi_device dev, pi_native_handle * nativeHandle)
Gets the native handle of a PI mem object.
Parameters
mem is the PI mem to get the native handle of.
dev is the PI device that the native allocation will be resident on
nativeHandle is the native handle of mem.
Definition at line 236 of file pi_cuda.cpp.
References pi2ur::piextMemGetNativeHandle().
Referenced by sycl::_V1::detail::buffer_impl::getNativeVector(), sycl::_V1::detail::memBufferCreateHelper(), sycl::_V1::detail::memReleaseHelper(), and piPluginInit().
piextMemImageAllocate()
pi_result piextMemImageAllocate (pi_context context, pi_device device, pi_image_format * image_format, pi_image_desc * image_desc, pi_image_mem_handle * ret_mem)
API to allocate memory for bindless images.
Parameters
context is the pi_context
device is the pi_device
flags are extra flags to pass (currently unused)
image_format format of the image (channel order and data type)
image_desc image descriptor
ret_mem is the returning memory handle to newly allocated memory
Definition at line 374 of file pi_cuda.cpp.
References pi2ur::piextMemImageAllocate().
Referenced by sycl::_V1::ext::oneapi::experimental::alloc_image_mem(), and sycl::_V1::ext::oneapi::experimental::alloc_mipmap_mem().
piextMemImageCopy()
pi_result piextMemImageCopy (pi_queue command_queue, void * dst_ptr, void * src_ptr, const pi_image_format * image_format, const pi_image_desc * image_desc, const pi_image_copy_flags flags, pi_image_offset src_offset, pi_image_offset dst_offset, pi_image_region copy_extent, pi_image_region host_extent, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
API to copy image data Host to Device or Device to Host.
Parameters
queue is the queue to submit to
dst_ptr is the location the data will be copied to
src_ptr is the data to be copied
image_format format of the image (channel order and data type)
image_desc image descriptor
flags flags describing copy direction (H2D or D2H)
src_offset is the offset into the source image/memory
dst_offset is the offset into the destination image/memory
copy_extent is the extent (region) of the image/memory to copy
host_extent is the extent (region) of the memory on the host
num_events_in_wait_list is the number of events in the wait list
event_wait_list is the list of events to wait on before copying
event is the returned event representing this operation
Definition at line 427 of file pi_cuda.cpp.
References pi2ur::piextMemImageCopy().
Referenced by sycl::_V1::detail::MemoryManager::copy_image_bindless().
piextMemImageCreateWithNativeHandle()
pi_result piextMemImageCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, bool ownNativeHandle, const pi_image_format * ImageFormat, const pi_image_desc * ImageDesc, pi_mem * img)
Creates PI image object from a native handle.
Parameters
nativeHandle is the native handle to create PI image from.
context The PI context of the memory allocation.
ownNativeHandle Indicates if we own the native memory handle or it came from interop that asked to not transfer the ownership to SYCL RT.
ImageFormat is the pi_image_format struct that specifies the image channnel order and channel data type that match what the nativeHandle uses
ImageDesc is the pi_image_desc struct that specifies the image dimension, pitch, slice and other information about the nativeHandle
img is the PI img created from the native handle.
Definition at line 264 of file pi_cuda.cpp.
References pi2ur::piextMemImageCreateWithNativeHandle().
Referenced by sycl::_V1::detail::SYCLMemObjT::SYCLMemObjT().
piextMemImageFree()
pi_result piextMemImageFree (pi_context context, pi_device device, pi_image_mem_handle memory_handle)
API to free memory for bindless images.
Parameters
context is the pi_context
device is the pi_device
memory_handle is the handle to image memory to be freed
Definition at line 417 of file pi_cuda.cpp.
References pi2ur::piextMemImageFree().
Referenced by sycl::_V1::ext::oneapi::experimental::free_image_mem().
piextMemImageGetInfo()
pi_result piextMemImageGetInfo (const pi_image_mem_handle mem_handle, pi_image_info param_name, void * param_value, size_t * param_value_size_ret)
API to query an image memory handle for specific properties.
Parameters
mem_handle is the handle to the image memory
param_name is the queried info name
param_value is the returned query value
param_value_size_ret is the returned query value size
Definition at line 450 of file pi_cuda.cpp.
References pi2ur::piextMemImageGetInfo().
Referenced by sycl::_V1::ext::oneapi::experimental::get_image_channel_type(), sycl::_V1::ext::oneapi::experimental::get_image_num_channels(), and sycl::_V1::ext::oneapi::experimental::get_image_range().
piextMemImportOpaqueFD()
pi_result piextMemImportOpaqueFD (pi_context context, pi_device device, size_t size, int file_descriptor, pi_interop_mem_handle * ret_handle)
API to import external memory in the form of a file descriptor.
Parameters
context is the pi_context
device is the pi_device
size is the size of the external memory
file_descriptor is the file descriptor
ret_handle is the returned interop memory handle to the external memory
Definition at line 459 of file pi_cuda.cpp.
References pi2ur::piextMemImportOpaqueFD().
Referenced by sycl::_V1::ext::oneapi::experimental::import_external_memory< resource_fd >().
piextMemMapExternalArray()
pi_result piextMemMapExternalArray (pi_context context, pi_device device, pi_image_format * image_format, pi_image_desc * image_desc, pi_interop_mem_handle mem_handle, pi_image_mem_handle * ret_mem)
API to map an interop memory handle to an image memory handle.
Parameters
context is the pi_context
device is the pi_device
image_format format of the image (channel order and data type)
image_desc image descriptor
mem_handle is the interop memory handle to the external memory
ret_mem is the returned image memory handle to the externally allocated memory
Definition at line 465 of file pi_cuda.cpp.
References pi2ur::piextMemMapExternalArray().
Referenced by sycl::_V1::ext::oneapi::experimental::map_external_image_memory().
piextMemMipmapFree()
pi_result piextMemMipmapFree (pi_context context, pi_device device, pi_image_mem_handle memory_handle)
API to free mipmap memory for bindless images.
Parameters
context is the pi_context
device is the pi_device
memory_handle is the handle to image memory to be freed
Definition at line 422 of file pi_cuda.cpp.
References pi2ur::piextMemMipmapFree().
Referenced by sycl::_V1::ext::oneapi::experimental::free_image_mem(), and sycl::_V1::ext::oneapi::experimental::free_mipmap_mem().
piextMemMipmapGetLevel()
pi_result piextMemMipmapGetLevel (pi_context context, pi_device device, pi_image_mem_handle mip_mem, unsigned int level, pi_image_mem_handle * ret_mem)
API to retrieve individual image from mipmap.
Parameters
context is the pi_context
device is the pi_device
mip_mem is the memory handle to the mipmap
level is the requested level of the mipmap
ret_mem is the returning memory handle to the individual image
Definition at line 409 of file pi_cuda.cpp.
References pi2ur::piextMemMipmapGetLevel().
Referenced by sycl::_V1::ext::oneapi::experimental::get_mip_level_mem_handle().
piextMemReleaseInterop()
pi_result piextMemReleaseInterop (pi_context context, pi_device device, pi_interop_mem_handle memory_handle)
API to destroy interop memory.
Parameters
context is the pi_context
device is the pi_device
memory_handle is the handle to interop memory to be freed
Definition at line 473 of file pi_cuda.cpp.
References pi2ur::piextMemReleaseInterop().
Referenced by sycl::_V1::ext::oneapi::experimental::release_external_memory().
piextMemSampledImageCreate()
pi_result piextMemSampledImageCreate (pi_context context, pi_device device, pi_image_mem_handle img_mem, pi_image_format * image_format, pi_image_desc * image_desc, pi_sampler sampler, pi_mem * ret_mem, pi_image_handle * ret_handle)
API to create sampled bindless image handles.
Parameters
context is the pi_context
device is the pi_device
img_mem is the handle to memory from which to create the image
image_format format of the image (channel order and data type)
image_desc image descriptor
sampler is the pi_sampler
ret_mem is the returning pi_mem image object
ret_handle is the returning memory handle to newly allocated memory
Definition at line 391 of file pi_cuda.cpp.
References pi2ur::piextMemSampledImageCreate().
Referenced by sycl::_V1::ext::oneapi::experimental::create_image().
piextMemSampledImageHandleDestroy()
pi_result piextMemSampledImageHandleDestroy (pi_context context, pi_device device, pi_image_handle handle)
API to destroy bindless sampled image handles.
Parameters
context is the pi_context
handle is the image handle
Definition at line 445 of file pi_cuda.cpp.
References pi2ur::piextMemSampledImageHandleDestroy().
Referenced by sycl::_V1::ext::oneapi::experimental::destroy_image_handle().
piextMemUnsampledImageCreate()
pi_result piextMemUnsampledImageCreate (pi_context context, pi_device device, pi_image_mem_handle img_mem, pi_image_format * image_format, pi_image_desc * image_desc, pi_mem * ret_mem, pi_image_handle * ret_handle)
API to create bindless image handles.
Parameters
context is the pi_context
device is the pi_device
img_mem is the handle to memory from which to create the image
image_format format of the image (channel order and data type)
image_desc image descriptor
ret_mem is the returning pi_mem image object
ret_handle is the returning memory handle to newly allocated memory
Definition at line 383 of file pi_cuda.cpp.
References pi2ur::piextMemUnsampledImageCreate().
Referenced by sycl::_V1::ext::oneapi::experimental::create_image().
piextMemUnsampledImageHandleDestroy()
pi_result piextMemUnsampledImageHandleDestroy (pi_context context, pi_device device, pi_image_handle handle)
API to destroy bindless unsampled image handles.
Parameters
context is the pi_context
device is the pi_device
handle is the image handle
Definition at line 440 of file pi_cuda.cpp.
References pi2ur::piextMemUnsampledImageHandleDestroy().
Referenced by sycl::_V1::ext::oneapi::experimental::destroy_image_handle().
piextPeerAccessGetInfo()
pi_result piextPeerAccessGetInfo (pi_device command_device, pi_device peer_device, pi_peer_attr attr, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 1264 of file pi_cuda.cpp.
References pi2ur::piextPeerAccessGetInfo().
Referenced by sycl::_V1::device::ext_oneapi_can_access_peer(), and piPluginInit().
piextPlatformCreateWithNativeHandle()
pi_result piextPlatformCreateWithNativeHandle (pi_native_handle nativeHandle, pi_platform * platform)
Creates PI platform object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI device from.
platform is the PI platform created from the native handle.
Definition at line 47 of file pi_cuda.cpp.
References pi2ur::piextPlatformCreateWithNativeHandle().
Referenced by sycl::_V1::detail::make_platform(), and piPluginInit().
piextPlatformGetNativeHandle()
pi_result piextPlatformGetNativeHandle (pi_platform platform, pi_native_handle * nativeHandle)
Gets the native handle of a PI platform object.
Parameters
platform is the PI platform to get the native handle of.
nativeHandle is the native handle of platform.
Definition at line 42 of file pi_cuda.cpp.
References pi2ur::piextPlatformGetNativeHandle().
Referenced by sycl::_V1::detail::platform_impl::getNative(), and piPluginInit().
piextPluginGetOpaqueData()
pi_result piextPluginGetOpaqueData (void * opaque_data_param, void ** opaque_data_return)
API to get Plugin internal data, opaque to SYCL RT.
Some devices whose device code is compiled by the host compiler (e.g. CPU emulators) may use it to access some device code functionality implemented in/behind the plugin.
Parameters
opaque_data_param - unspecified argument, interpretation is specific to a plugin
opaque_data_return - placeholder for the returned opaque data.
Definition at line 1238 of file pi_cuda.cpp.
References pi2ur::piextPluginGetOpaqueData().
Referenced by sycl::_V1::detail::getPluginOpaqueData(), and piPluginInit().
piextProgramCreateWithNativeHandle()
pi_result piextProgramCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, bool pluginOwnsNativeHandle, pi_program * program)
Creates PI program object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI program from.
context is the PI context of the program.
pluginOwnsNativeHandle Indicates whether the created PI object should take ownership of the native handle.
program is the PI program created from the native handle.
Definition at line 333 of file pi_cuda.cpp.
References pi2ur::piextProgramCreateWithNativeHandle().
Referenced by sycl::_V1::detail::make_kernel_bundle(), and piPluginInit().
piextProgramGetNativeHandle()
pi_result piextProgramGetNativeHandle (pi_program program, pi_native_handle * nativeHandle)
Gets the native handle of a PI program object.
Parameters
program is the PI program to get the native handle of.
nativeHandle is the native handle of program.
Definition at line 328 of file pi_cuda.cpp.
References pi2ur::piextProgramGetNativeHandle().
Referenced by sycl::_V1::detail::device_image_impl::getNative(), sycl::_V1::detail::program_impl::getNative(), and piPluginInit().
piextProgramSetSpecializationConstant()
pi_result piextProgramSetSpecializationConstant (pi_program prog, pi_uint32 spec_id, size_t spec_size, const void * spec_value)
Sets a specialization constant to a specific value.
Note: Only used when specialization constants are natively supported (SPIR-V binaries), and not when they are emulated (AOT binaries).
Parameters
prog the program object which will use the value
spec_id integer ID of the constant
spec_size size of the value
spec_value bytes of the value
Definition at line 1060 of file pi_cuda.cpp.
References pi2ur::piextProgramSetSpecializationConstant().
Referenced by sycl::_V1::detail::enableITTAnnotationsIfNeeded(), sycl::_V1::detail::program_impl::flush_spec_constants(), piPluginInit(), and sycl::_V1::detail::setSpecializationConstants().
piextQueueCreate()
pi_result piextQueueCreate (pi_context context, pi_device device, pi_queue_properties * properties, pi_queue * queue)
Parameters
properties points to a zero-terminated array of extra data describing desired queue properties. Format is {[PROPERTY[, property-specific elements of data]*,]* 0}
Definition at line 167 of file pi_cuda.cpp.
References pi2ur::piextQueueCreate().
Referenced by sycl::_V1::detail::queue_impl::createQueue(), piPluginInit(), and piQueueCreate().
piextQueueCreateWithNativeHandle()
pi_result piextQueueCreateWithNativeHandle (pi_native_handle nativeHandle, int32_t nativeHandleDesc, pi_context context, pi_device device, bool pluginOwnsNativeHandle, pi_queue_properties * Properties, pi_queue * queue)
Creates PI queue object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI queue from.
nativeHandleDesc provides additional properties of the native handle.
context is the PI context of the queue.
device is the PI device associated with the native device used when creating the native queue. This parameter is optional but some backends may fail to create the right PI queue if omitted.
pluginOwnsNativeHandle Indicates whether the created PI object should take ownership of the native handle.
Properties holds queue properties.
queue is the PI queue created from the native handle.
Definition at line 198 of file pi_cuda.cpp.
References pi2ur::piextQueueCreateWithNativeHandle().
Referenced by sycl::_V1::detail::make_queue(), and piPluginInit().
piextQueueGetNativeHandle()
pi_result piextQueueGetNativeHandle (pi_queue queue, pi_native_handle * nativeHandle, int32_t * nativeHandleDesc)
Gets the native handle of a PI queue object.
Parameters
queue is the PI queue to get the native handle of.
nativeHandle is the native handle of queue or commandlist.
nativeHandleDesc provides additional properties of the native handle.
Definition at line 190 of file pi_cuda.cpp.
References pi2ur::piextQueueGetNativeHandle().
Referenced by sycl::_V1::detail::queue_impl::getNative(), and piPluginInit().
piextSignalExternalSemaphore()
pi_result piextSignalExternalSemaphore (pi_queue command_queue, pi_interop_semaphore_handle sem_handle, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
API to instruct the queue to signal the external semaphore handle once all previous commands have completed execution.
Parameters
command_queue is the queue instructed to signal
sem_handle is the interop semaphore handle to signal
num_events_in_wait_list is the number of events in the wait list
event_wait_list is the list of events to wait on before this operation
event is the returned event representing this operation
Definition at line 500 of file pi_cuda.cpp.
References pi2ur::piextSignalExternalSemaphore().
piextUSMDeviceAlloc()
pi_result piextUSMDeviceAlloc (void ** result_ptr, pi_context context, pi_device device, pi_usm_mem_properties * properties, size_t size, pi_uint32 alignment)
Allocates device memory.
Parameters
result_ptr contains the allocated memory
context is the pi_context
device is the device the memory will be allocated on
properties are optional allocation properties
size is the size of the allocation
alignment is the desired alignment of the allocation
Definition at line 860 of file pi_cuda.cpp.
References sycl::_V1::ext::oneapi::experimental::detail::Alignment, and pi2ur::piextUSMDeviceAlloc().
Referenced by sycl::_V1::detail::usm::alignedAllocInternal(), and piPluginInit().
piextUSMEnqueueFill()
pi_result piextUSMEnqueueFill (pi_queue Queue, void * Ptr, const void * Pattern, size_t PatternSize, size_t Count, pi_uint32 NumEventsInWaitlist, const pi_event * EventsWaitlist, pi_event * Event)
USM Fill API.
Parameters
queue is the queue to submit to
ptr is the ptr to fill
pattern is the ptr with the bytes of the pattern to set
patternSize is the size in bytes of the pattern to set
count is the size in bytes to fill
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
Queue is the queue to submit to
Ptr is the ptr to fill
Pattern is the ptr with the bytes of the pattern to set
PatternSize is the size in bytes of the pattern to set
Count is the size in bytes to fill
NumEventsInWaitlist is the number of events to wait on
EventsWaitlist is an array of events to wait on
Event is the event that represents this operation
Definition at line 905 of file pi_cuda.cpp.
References pi2ur::piextUSMEnqueueFill().
Referenced by sycl::_V1::detail::MemoryManager::fill_usm(), and piPluginInit().
piextUSMEnqueueFill2D()
pi_result piextUSMEnqueueFill2D (pi_queue Queue, void * Ptr, size_t Pitch, size_t PatternSize, const void * Pattern, size_t Width, size_t Height, pi_uint32 NumEventsWaitList, const pi_event * EventsWaitList, pi_event * Event)
USM 2D fill API.
Parameters
queue is the queue to submit to
ptr is the ptr to fill
pitch is the total width of the destination memory including padding
pattern is a pointer with the bytes of the pattern to set
pattern_size is the size in bytes of the pattern
width is width in bytes of each row to fill
height is height the columns to fill
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
USM 2D fill API.
Parameters
queue is the queue to submit to
ptr is the ptr to fill
pitch is the total width of the destination memory including padding
pattern is a pointer with the bytes of the pattern to set
pattern_size is the size in bytes of the pattern
width is width in bytes of each row to fill
height is height the columns to fill
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
Definition at line 941 of file pi_cuda.cpp.
References pi2ur::piextUSMEnqueueFill2D().
Referenced by sycl::_V1::detail::MemoryManager::fill_2d_usm(), and piPluginInit().
piextUSMEnqueueMemAdvise()
pi_result piextUSMEnqueueMemAdvise (pi_queue Queue, const void * Ptr, size_t Length, pi_mem_advice Advice, pi_event * OutEvent)
USM Memadvise API.
Parameters
queue is the queue to submit to
ptr is the data to be advised
length is the size in bytes of the memory to advise
advice is device specific advice
event is the event that represents this operation
USM Memadvise API.
Parameters
Queue is the queue to submit to
Ptr is the data to be advised
Length is the size in bytes of the meory to advise
Advice is device specific advice
Event is the event that represents this operation
Definition at line 934 of file pi_cuda.cpp.
References pi2ur::piextUSMEnqueueMemAdvise().
Referenced by sycl::_V1::detail::MemoryManager::advise_usm(), and piPluginInit().
piextUSMEnqueueMemcpy()
pi_result piextUSMEnqueueMemcpy (pi_queue queue, pi_bool blocking, void * dst_ptr, const void * src_ptr, size_t size, pi_uint32 num_events_in_waitlist, const pi_event * events_waitlist, pi_event * event)
USM Memcpy API.
Parameters
queue is the queue to submit to
blocking is whether this operation should block the host
src_ptr is the data to be copied
dst_ptr is the location the data will be copied
size is number of bytes to copy
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
Definition at line 913 of file pi_cuda.cpp.
References pi2ur::piextUSMEnqueueMemcpy().
Referenced by sycl::_V1::detail::MemoryManager::copy_2d_usm(), sycl::_V1::detail::MemoryManager::copy_usm(), and piPluginInit().
piextUSMEnqueueMemcpy2D()
pi_result piextUSMEnqueueMemcpy2D (pi_queue Queue, pi_bool Blocking, void * DstPtr, size_t DstPitch, const void * SrcPtr, size_t SrcPitch, size_t Width, size_t Height, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * Event)
USM 2D Memcpy API.
Parameters
queue is the queue to submit to
blocking is whether this operation should block the host
dst_ptr is the location the data will be copied
dst_pitch is the total width of the destination memory including padding
src_ptr is the data to be copied
src_pitch is the total width of the source memory including padding
width is width in bytes of each row to be copied
height is height the columns to be copied
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
queue is the queue to submit to
blocking is whether this operation should block the host
dst_ptr is the location the data will be copied
dst_pitch is the total width of the destination memory including padding
src_ptr is the data to be copied
dst_pitch is the total width of the source memory including padding
width is width in bytes of each row to be copied
height is height the columns to be copied
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
Definition at line 966 of file pi_cuda.cpp.
References pi2ur::piextUSMEnqueueMemcpy2D().
Referenced by sycl::_V1::detail::MemoryManager::copy_2d_usm(), and piPluginInit().
piextUSMEnqueueMemset2D()
pi_result piextUSMEnqueueMemset2D (pi_queue Queue, void * Ptr, size_t Pitch, int Value, size_t Width, size_t Height, pi_uint32 NumEventsWaitList, const pi_event * EventsWaitlist, pi_event * Event)
USM 2D Memset API.
Parameters
queue is the queue to submit to
ptr is the ptr to fill
pitch is the total width of the destination memory including padding
value the value to fill into the region in
ptr
width is width in bytes of each row to fill
height is height the columns to fill
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
queue is the queue to submit to
ptr is the ptr to fill
pitch is the total width of the destination memory including padding
pattern is a pointer with the bytes of the pattern to set
pattern_size is the size in bytes of the pattern
width is width in bytes of each row to fill
height is height the columns to fill
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
Definition at line 954 of file pi_cuda.cpp.
References pi2ur::piextUSMEnqueueMemset2D().
Referenced by sycl::_V1::detail::MemoryManager::memset_2d_usm(), and piPluginInit().
piextUSMEnqueuePrefetch()
pi_result piextUSMEnqueuePrefetch (pi_queue Queue, const void * Ptr, size_t Size, pi_usm_migration_flags Flags, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * OutEvent)
Hint to migrate memory to the device.
Parameters
queue is the queue to submit to
ptr points to the memory to migrate
size is the number of bytes to migrate
flags is a bitfield used to specify memory migration options
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
Queue is the queue to submit to
Ptr points to the memory to migrate
Size is the number of bytes to migrate
Flags is a bitfield used to specify memory migration options
NumEventsInWaitlist is the number of events to wait on
EventsWaitlist is an array of events to wait on
Event is the event that represents this operation
Definition at line 924 of file pi_cuda.cpp.
References pi2ur::piextUSMEnqueuePrefetch().
Referenced by piPluginInit(), and sycl::_V1::detail::MemoryManager::prefetch_usm().
piextUSMFree()
pi_result piextUSMFree (pi_context context, void * ptr)
Indicates that the allocated USM memory is no longer needed on the runtime side.
The actual freeing of the memory may be done in a blocking or deferred manner, e.g. to avoid issues with indirect memory access from kernels.
Parameters
context is the pi_context of the allocation
ptr is the memory to be freed
Definition at line 895 of file pi_cuda.cpp.
References pi2ur::piextUSMFree().
Referenced by sycl::_V1::detail::usm::freeInternal(), and piPluginInit().
piextUSMGetMemAllocInfo()
pi_result piextUSMGetMemAllocInfo (pi_context Context, const void * Ptr, pi_mem_alloc_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
API to query information about USM allocated pointers Valid Queries: PI_MEM_ALLOC_TYPE returns host/device/shared pi_host_usm value PI_MEM_ALLOC_BASE_PTR returns the base ptr of an allocation if the queried pointer fell inside an allocation.
Result must fit in void * PI_MEM_ALLOC_SIZE returns how big the queried pointer's allocation is in bytes. Result is a size_t. PI_MEM_ALLOC_DEVICE returns the pi_device this was allocated against
Parameters
context is the pi_context
ptr is the pointer to query
param_name is the type of query to perform
param_value_size is the size of the result in bytes
param_value is the result
param_value_size_ret is how many bytes were written
API to query information about USM allocated pointers Valid Queries: PI_MEM_ALLOC_TYPE returns host/device/shared pi_host_usm value PI_MEM_ALLOC_BASE_PTR returns the base ptr of an allocation if the queried pointer fell inside an allocation.
Valid Queries: PI_MEM_ALLOC_TYPE returns host/device/shared pi_usm_type value PI_MEM_ALLOC_BASE_PTR returns the base ptr of an allocation if the queried pointer fell inside an allocation. Result must fit in void * PI_MEM_ALLOC_SIZE returns how big the queried pointer's allocation is in bytes. Result is a size_t. PI_MEM_ALLOC_DEVICE returns the pi_device this was allocated against
Parameters
Context is the pi_context
Ptr is the pointer to query
ParamName is the type of query to perform
ParamValueSize is the size of the result in bytes
ParamValue is the result
ParamValueRet is how many bytes were written
Definition at line 977 of file pi_cuda.cpp.
References pi2ur::piextUSMGetMemAllocInfo().
Referenced by piPluginInit().
piextUSMHostAlloc()
pi_result piextUSMHostAlloc (void ** result_ptr, pi_context context, pi_usm_mem_properties * properties, size_t size, pi_uint32 alignment)
Allocates host memory accessible by the device.
Parameters
result_ptr contains the allocated memory
context is the pi_context
properties are optional allocation properties
size is the size of the allocation
alignment is the desired alignment of the allocation
Definition at line 888 of file pi_cuda.cpp.
References sycl::_V1::ext::oneapi::experimental::detail::Alignment, and pi2ur::piextUSMHostAlloc().
Referenced by sycl::_V1::detail::usm::alignedAllocHost(), and piPluginInit().
piextUSMImport()
pi_result piextUSMImport (const void * ptr, size_t size, pi_context context)
Import host system memory into USM.
Parameters
ptr start address of memory range to import
size is the number of bytes to import
context is the pi_context
Definition at line 985 of file pi_cuda.cpp.
References pi2ur::piextUSMImport().
Referenced by piPluginInit().
piextUSMPitchedAlloc()
pi_result piextUSMPitchedAlloc (void ** result_ptr, size_t * result_pitch, pi_context context, pi_device device, pi_usm_mem_properties * properties, size_t width_in_bytes, size_t height, unsigned int element_size_bytes)
Allocates memory accessible on device.
Parameters
result_ptr contains the allocated memory
result_pitch contains the returned memory pitch
context is the pi_context
device is the device the memory will be allocated on
properties are optional allocation properties
width_in_bytes is the width of the allocation in bytes
height is the height of the allocation in rows
element_size_bytes is the size in bytes of an element in the allocation
Definition at line 878 of file pi_cuda.cpp.
References pi2ur::piextUSMPitchedAlloc().
Referenced by sycl::_V1::ext::oneapi::experimental::pitched_alloc_device().
piextUSMRelease()
pi_result piextUSMRelease (const void * ptr, pi_context context)
Release host system memory from USM.
Parameters
ptr start address of imported memory range
context is the pi_context
Definition at line 989 of file pi_cuda.cpp.
References pi2ur::piextUSMRelease().
Referenced by piPluginInit().
piextUSMSharedAlloc()
pi_result piextUSMSharedAlloc (void ** result_ptr, pi_context context, pi_device device, pi_usm_mem_properties * properties, size_t size, pi_uint32 alignment)
Allocates memory accessible on both host and device.
Parameters
result_ptr contains the allocated memory
context is the pi_context
device is the device the memory will be allocated on
properties are optional allocation properties
size is the size of the allocation
alignment is the desired alignment of the allocation
Definition at line 869 of file pi_cuda.cpp.
References sycl::_V1::ext::oneapi::experimental::detail::Alignment, and pi2ur::piextUSMSharedAlloc().
Referenced by sycl::_V1::detail::usm::alignedAllocInternal(), and piPluginInit().
piextWaitExternalSemaphore()
pi_result piextWaitExternalSemaphore (pi_queue command_queue, pi_interop_semaphore_handle sem_handle, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
API to instruct the queue with a non-blocking wait on an external semaphore.
Parameters
command_queue is the queue instructed to wait
sem_handle is the interop semaphore handle
num_events_in_wait_list is the number of events in the wait list
event_wait_list is the list of events to wait on before this operation
event is the returned event representing this operation
Definition at line 492 of file pi_cuda.cpp.
References pi2ur::piextWaitExternalSemaphore().
piGetDeviceAndHostTimer()
pi_result piGetDeviceAndHostTimer (pi_device Device, uint64_t * DeviceTime, uint64_t * HostTime)
Queries device for it's global timestamp in nanoseconds, and updates HostTime with the value of the host timer at the closest possible point in time to that at which DeviceTime was returned.
Parameters
Device device to query for timestamp
DeviceTime pointer to store device timestamp in nanoseconds. Optional argument, can be nullptr
HostTime pointer to store host timestamp in nanoseconds. Optional argurment, can be nullptr in which case timestamp will not be written
Definition at line 1247 of file pi_cuda.cpp.
References pi2ur::piGetDeviceAndHostTimer().
Referenced by sycl::_V1::detail::device_impl::getCurrentDeviceTime(), sycl::_V1::detail::device_impl::isGetDeviceAndHostTimerSupported(), and piPluginInit().
piKernelCreate()
pi_result piKernelCreate (pi_program program, const char * kernel_name, pi_kernel * ret_kernel)
Definition at line 341 of file pi_cuda.cpp.
References pi2ur::piKernelCreate().
Referenced by sycl::_V1::detail::kernel_bundle_impl::ext_oneapi_get_kernel(), sycl::_V1::detail::ProgramManager::getOrCreateKernel(), and piPluginInit().
piKernelGetGroupInfo()
pi_result piKernelGetGroupInfo (pi_kernel kernel, pi_device device, pi_kernel_group_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 508 of file pi_cuda.cpp.
References pi2ur::piKernelGetGroupInfo().
Referenced by sycl::_V1::detail::enqueueImpCommandBufferKernel(), sycl::_V1::detail::get_kernel_device_specific_info_helper(), sycl::_V1::detail::enqueue_kernel_launch::handleInvalidWorkGroupSize(), piPluginInit(), sycl::_V1::detail::SetKernelParamsAndLaunch(), and sycl::_V1::ext::oneapi::experimental::detail::exec_graph_impl::updateImpl().
piKernelGetInfo()
pi_result piKernelGetInfo (pi_kernel kernel, pi_kernel_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 366 of file pi_cuda.cpp.
References pi2ur::piKernelGetInfo().
Referenced by sycl::_V1::detail::get_kernel_info(), sycl::_V1::detail::ProgramManager::getPiProgramFromPiKernel(), sycl::_V1::detail::enqueue_kernel_launch::handleInvalidWorkGroupSize(), sycl::_V1::detail::kernel_impl::kernel_impl(), and piPluginInit().
piKernelGetSubGroupInfo()
pi_result piKernelGetSubGroupInfo (pi_kernel kernel, pi_device device, pi_kernel_sub_group_info param_name, size_t input_value_size, const void * input_value, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
API to query information from the sub-group from a kernel.
Parameters
kernel is the pi_kernel to query
device is the device the kernel is executed on
param_name is a pi_kernel_sub_group_info enum value that specifies the informtation queried for.
input_value_size is the size of input value passed in ptr input_value param
input_value is the ptr to the input value passed.
param_value_size is the size of the value in bytes.
param_value is a pointer to the value to set.
param_value_size_ret is a pointer to return the size of data in param_value ptr.
All queries expect a return of 4 bytes in param_value_size, param_value_size_ret, and a uint32_t value should to be written in param_value ptr. Note: This behaviour differs from OpenCL. OpenCL returns size_t.
Definition at line 516 of file pi_cuda.cpp.
References pi2ur::piKernelGetSubGroupInfo().
Referenced by sycl::_V1::detail::get_kernel_device_specific_info_helper(), sycl::_V1::detail::get_kernel_device_specific_info_with_input(), and piPluginInit().
piKernelRelease()
pi_result piKernelRelease (pi_kernel kernel)
Definition at line 531 of file pi_cuda.cpp.
References pi2ur::piKernelRelease().
Referenced by sycl::_V1::detail::enqueueImpCommandBufferKernel(), sycl::_V1::detail::enqueueImpKernel(), piPluginInit(), sycl::_V1::detail::kernel_impl::~kernel_impl(), and sycl::_V1::detail::KernelProgramCache::KernelBuildResult::~KernelBuildResult().
piKernelRetain()
pi_result piKernelRetain (pi_kernel kernel)
Definition at line 526 of file pi_cuda.cpp.
References pi2ur::piKernelRetain().
Referenced by sycl::_V1::detail::kernel_impl::get(), sycl::_V1::detail::kernel_impl::getNative(), sycl::_V1::detail::ProgramManager::getOrCreateKernel(), sycl::_V1::detail::make_kernel(), and piPluginInit().
piKernelSetArg()
pi_result piKernelSetArg (pi_kernel kernel, pi_uint32 arg_index, size_t arg_size, const void * arg_value)
Definition at line 347 of file pi_cuda.cpp.
References pi2ur::piKernelSetArg().
Referenced by piPluginInit(), and sycl::_V1::detail::SetArgBasedOnType().
piKernelSetExecInfo()
pi_result piKernelSetExecInfo (pi_kernel kernel, pi_kernel_exec_info value_name, size_t param_value_size, const void * param_value)
API to set attributes controlling kernel execution.
Parameters
kernel is the pi kernel to execute
param_name is a pi_kernel_exec_info value that specifies the info passed to the kernel
param_value_size is the size of the value in bytes
param_value is a pointer to the value to set for the kernel
If param_name is PI_USM_INDIRECT_ACCESS, the value will be a ptr to the pi_bool value PI_TRUE If param_name is PI_USM_PTRS, the value will be an array of ptrs
Definition at line 1053 of file pi_cuda.cpp.
References pi2ur::piKernelSetExecInfo().
Referenced by sycl::_V1::detail::enqueueImpKernel(), sycl::_V1::detail::ProgramManager::getOrCreateKernel(), sycl::_V1::detail::kernel_impl::kernel_impl(), and piPluginInit().
piMemBufferCreate()
pi_result piMemBufferCreate (pi_context context, pi_mem_flags flags, size_t size, void * host_ptr, pi_mem * ret_mem, const pi_mem_properties * properties = nullptr)
Definition at line 210 of file pi_cuda.cpp.
References pi2ur::piMemBufferCreate().
Referenced by sycl::_V1::detail::memBufferCreateHelper(), and piPluginInit().
piMemBufferPartition()
pi_result piMemBufferPartition (pi_mem buffer, pi_mem_flags flags, pi_buffer_create_type buffer_create_type, void * buffer_create_info, pi_mem * ret_mem)
Definition at line 836 of file pi_cuda.cpp.
References pi2ur::piMemBufferPartition().
Referenced by sycl::_V1::detail::MemoryManager::allocateMemSubBuffer(), and piPluginInit().
piMemGetInfo()
pi_result piMemGetInfo (pi_mem mem, pi_mem_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 217 of file pi_cuda.cpp.
References pi2ur::piMemGetInfo().
Referenced by sycl::_V1::detail::SYCLMemObjT::getBufSizeForContext(), piPluginInit(), and sycl::_V1::detail::SYCLMemObjT::SYCLMemObjT().
piMemImageCreate()
pi_result piMemImageCreate (pi_context context, pi_mem_flags flags, const pi_image_format * image_format, const pi_image_desc * image_desc, void * host_ptr, pi_mem * ret_mem)
Definition at line 227 of file pi_cuda.cpp.
References pi2ur::piMemImageCreate().
Referenced by sycl::_V1::detail::MemoryManager::allocateImageObject(), and piPluginInit().
piMemImageGetInfo()
pi_result piMemImageGetInfo (pi_mem image, pi_image_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 781 of file pi_cuda.cpp.
References pi2ur::piMemImageGetInfo().
Referenced by sycl::_V1::detail::getImageInfo(), and piPluginInit().
piMemRelease()
pi_result piMemRelease (pi_mem mem)
Definition at line 225 of file pi_cuda.cpp.
References pi2ur::piMemRelease().
Referenced by sycl::_V1::detail::memReleaseHelper(), piPluginInit(), and sycl::_V1::detail::SYCLMemObjT::updateHostMemory().
piMemRetain()
pi_result piMemRetain (pi_mem mem)
Definition at line 223 of file pi_cuda.cpp.
References pi2ur::piMemRetain().
Referenced by sycl::_V1::detail::buffer_impl::addInteropObject(), sycl::_V1::detail::buffer_impl::getNativeVector(), piPluginInit(), and sycl::_V1::detail::SYCLMemObjT::SYCLMemObjT().
piPlatformGetInfo()
pi_result piPlatformGetInfo (pi_platform platform, pi_platform_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 35 of file pi_cuda.cpp.
References PI_PLATFORM_INFO_NAME, and pi2ur::piPlatformGetInfo().
Referenced by sycl::_V1::detail::get_platform_info_string_impl(), sycl::_V1::opencl::has_extension(), piPluginInit(), and sycl::_V1::detail::platform_impl::platform_impl().
piPlatformsGet()
pi_result piPlatformsGet (pi_uint32 num_entries, pi_platform * platforms, pi_uint32 * num_platforms)
Definition at line 30 of file pi_cuda.cpp.
References Adapters, pi2ur::piPlatformsGet(), and AdapterHolder::Vec.
Referenced by sycl::_V1::detail::platform_impl::get_platforms(), and piPluginInit().
piPluginGetBackendOption()
pi_result piPluginGetBackendOption (pi_platform platform, const char * frontend_option, const char ** backend_option)
API to get backend specific option.
Parameters
frontend_option is a string that contains frontend option.
backend_option is used to return the backend option corresponding to frontend option.
Returns
PI_SUCCESS is returned for valid frontend_option. If a valid backend option is not available, an empty string is returned.
Definition at line 56 of file pi_cuda.cpp.
References pi2ur::piPluginGetBackendOption().
Referenced by sycl::_V1::detail::platform_impl::getBackendOption(), and piPluginInit().
piPluginGetLastError()
pi_result piPluginGetLastError (char ** message)
API to get Plugin specific warning and error messages.
Parameters
message is a returned address to the first element in the message the plugin owns the error message string. The string is thread-local. As a result, different threads may return different errors. A message is overwritten by the following error or warning that is produced within the given thread. The memory is cleaned up at the end of the thread's lifetime.
Returns
PI_SUCCESS if plugin is indicating non-fatal warning. Any other error code indicates that plugin considers this to be a fatal error and the Returns the global timestamp from
Parameters
device,and syncronized host timestamp
Definition at line 52 of file pi_cuda.cpp.
References pi2ur::piPluginGetLastError().
Referenced by sycl::_V1::detail::device_impl::getCurrentDeviceTime().
piPluginInit()
pi_result piPluginInit (pi_plugin * plugin_info)
Definition at line 1275 of file pi_cuda.cpp.
References _PI_API, _PI_LEVEL_ZERO_PLUGIN_VERSION_STRING, _PI_PLUGIN_VERSION_CHECK, _PI_SANITIZE_TYPE_ADDRESS, _PI_UNIFIED_RUNTIME_PLUGIN_VERSION_STRING, Adapters, createCUDATracingContext(), enableCUDATracing(), enableZeTracing(), HANDLE_ERRORS, PI_ASSERT, piContextCreate(), piContextGetInfo(), piContextRelease(), piContextRetain(), piDeviceGetInfo(), piDevicePartition(), piDeviceRelease(), piDeviceRetain(), piDevicesGet(), piEnqueueEventsWait(), piEnqueueEventsWaitWithBarrier(), piEnqueueKernelLaunch(), piEnqueueMemBufferCopy(), piEnqueueMemBufferCopyRect(), piEnqueueMemBufferFill(), piEnqueueMemBufferMap(), piEnqueueMemBufferRead(), piEnqueueMemBufferReadRect(), piEnqueueMemBufferWrite(), piEnqueueMemBufferWriteRect(), piEnqueueMemImageCopy(), piEnqueueMemImageFill(), piEnqueueMemImageRead(), piEnqueueMemImageWrite(), piEnqueueMemUnmap(), piEventCreate(), piEventGetInfo(), piEventGetProfilingInfo(), piEventRelease(), piEventRetain(), piEventSetCallback(), piEventSetStatus(), piEventsWait(), piextContextCreateWithNativeHandle(), piextContextGetNativeHandle(), piextContextSetExtendedDeleter(), piextDeviceCreateWithNativeHandle(), piextDeviceGetNativeHandle(), piextDeviceSelectBinary(), piextDisablePeerAccess(), piextEnablePeerAccess(), piextEnqueueDeviceGlobalVariableRead(), piextEnqueueDeviceGlobalVariableWrite(), piextEventCreateWithNativeHandle(), piextEventGetNativeHandle(), piextGetDeviceFunctionPointer(), piextGetGlobalVariablePointer(), piextKernelCreateWithNativeHandle(), piextKernelSetArgMemObj(), piextKernelSetArgPointer(), piextKernelSetArgSampler(), piextMemCreateWithNativeHandle(), piextMemGetNativeHandle(), piextPeerAccessGetInfo(), piextPlatformCreateWithNativeHandle(), piextPlatformGetNativeHandle(), piextPluginGetOpaqueData(), piextProgramCreateWithNativeHandle(), piextProgramGetNativeHandle(), piextProgramSetSpecializationConstant(), piextQueueCreate(), piextQueueCreateWithNativeHandle(), piextQueueGetNativeHandle(), piextUSMDeviceAlloc(), piextUSMEnqueueFill(), piextUSMEnqueueFill2D(), piextUSMEnqueueMemAdvise(), piextUSMEnqueueMemcpy(), piextUSMEnqueueMemcpy2D(), piextUSMEnqueueMemset2D(), piextUSMEnqueuePrefetch(), piextUSMFree(), piextUSMGetMemAllocInfo(), piextUSMHostAlloc(), piextUSMImport(), piextUSMRelease(), piextUSMSharedAlloc(), _pi_plugin::PiFunctionTable, piGetDeviceAndHostTimer(), piKernelCreate(), piKernelGetGroupInfo(), piKernelGetInfo(), piKernelGetSubGroupInfo(), piKernelRelease(), piKernelRetain(), piKernelSetArg(), piKernelSetExecInfo(), piMemBufferCreate(), piMemBufferPartition(), piMemGetInfo(), piMemImageCreate(), piMemImageGetInfo(), piMemRelease(), piMemRetain(), piPlatformGetInfo(), piPlatformsGet(), piPluginGetBackendOption(), piProgramBuild(), piProgramCompile(), piProgramCreate(), piProgramCreateWithBinary(), piProgramGetBuildInfo(), piProgramGetInfo(), piProgramLink(), piProgramRelease(), piProgramRetain(), piQueueCreate(), piQueueFinish(), piQueueFlush(), piQueueGetInfo(), piQueueRelease(), piQueueRetain(), piSamplerCreate(), piSamplerGetInfo(), piSamplerRelease(), piSamplerRetain(), piTearDown(), _pi_plugin::PiVersion, _pi_plugin::PluginVersion, _pi_plugin::SanitizeType, SupportedVersion, ur2piResult(), and AdapterHolder::Vec.
Referenced by sycl::_V1::detail::pi::bindPlugin().
piProgramBuild()
pi_result piProgramBuild (pi_program program, pi_uint32 num_devices, const pi_device * device_list, const char * options, void(*)(pi_program program, void *user_data) pfn_notify, void * user_data)
Referenced by sycl::_V1::detail::kernel_bundle_impl::build_from_source(), and sycl::_V1::detail::make_kernel_bundle().
piProgramCompile()
pi_result piProgramCompile (pi_program program, pi_uint32 num_devices, const pi_device * device_list, const char * options, pi_uint32 num_input_headers, const pi_program * input_headers, const char ** header_include_names, void(*)(pi_program program, void *user_data) pfn_notify, void * user_data)
Referenced by sycl::_V1::detail::ProgramManager::compile(), sycl::_V1::detail::loadDeviceLibFallback(), and sycl::_V1::detail::make_kernel_bundle().
piProgramCreate()
pi_result piProgramCreate (pi_context context, const void * il, size_t length, pi_program * res_program)
Definition at line 248 of file pi_cuda.cpp.
References pi2ur::piProgramCreate().
Referenced by sycl::_V1::detail::kernel_bundle_impl::build_from_source(), sycl::_V1::detail::createSpirvProgram(), and piPluginInit().
piProgramCreateWithBinary()
pi_result piProgramCreateWithBinary (pi_context context, pi_uint32 num_devices, const pi_device * device_list, const size_t * lengths, const unsigned char ** binaries, size_t num_metadata_entries, const pi_device_binary_property * metadata, pi_int32 * binary_status, pi_program * ret_program)
Creates a PI program for a context and loads the given binary into it.
Parameters
context is the PI context to associate the program with.
num_devices is the number of devices in device_list.
device_list is a pointer to a list of devices. These devices must all be in context.
lengths is an array of sizes in bytes of the binary in binaries.
binaries is a pointer to a list of program binaries.
num_metadata_entries is the number of metadata entries in metadata.
metadata is a pointer to a list of program metadata entries. The use of metadata entries is backend-defined.
binary_status returns whether the program binary was loaded succesfully or not, for each device in device_list. binary_status is ignored if it is null and otherwise it must be an array of num_devices elements.
ret_program is the PI program created from the program binaries.
Definition at line 253 of file pi_cuda.cpp.
References pi2ur::piProgramCreateWithBinary().
Referenced by sycl::_V1::detail::createBinaryProgram(), and piPluginInit().
piProgramGetBuildInfo()
pi_result piProgramGetBuildInfo (pi_program program, pi_device device, _pi_program_build_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 310 of file pi_cuda.cpp.
References pi2ur::piProgramGetBuildInfo().
Referenced by sycl::_V1::detail::ProgramManager::getProgramBuildLog(), sycl::_V1::detail::enqueue_kernel_launch::handleInvalidWorkGroupSize(), sycl::_V1::detail::make_kernel_bundle(), and piPluginInit().
piProgramGetInfo()
pi_result piProgramGetInfo (pi_program program, pi_program_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 272 of file pi_cuda.cpp.
References pi2ur::piProgramGetInfo().
Referenced by sycl::_V1::detail::kernel_bundle_impl::build_from_source(), sycl::_V1::detail::program_impl::get_binaries(), sycl::_V1::detail::ProgramManager::getProgramBuildLog(), sycl::_V1::detail::make_kernel_bundle(), piPluginInit(), and sycl::_V1::detail::PersistentDeviceCodeCache::putItemToDisc().
piProgramLink()
pi_result piProgramLink (pi_context context, pi_uint32 num_devices, const pi_device * device_list, const char * options, pi_uint32 num_input_programs, const pi_program * input_programs, void(*)(pi_program program, void *user_data) pfn_notify, void * user_data, pi_program * ret_program)
Referenced by sycl::_V1::detail::ProgramManager::link(), sycl::_V1::detail::program_impl::link(), sycl::_V1::detail::make_kernel_bundle(), and sycl::_V1::detail::program_impl::program_impl().
piProgramRelease()
pi_result piProgramRelease (pi_program program)
Definition at line 324 of file pi_cuda.cpp.
References pi2ur::piProgramRelease().
Referenced by sycl::_V1::detail::enqueueImpCommandBufferKernel(), sycl::_V1::detail::enqueueImpKernel(), sycl::_V1::detail::program_impl::link(), piPluginInit(), sycl::_V1::detail::context_impl::~context_impl(), sycl::_V1::detail::device_image_impl::~device_image_impl(), sycl::_V1::detail::program_impl::~program_impl(), and sycl::_V1::detail::KernelProgramCache::ProgramBuildResult::~ProgramBuildResult().
piProgramRetain()
pi_result piProgramRetain (pi_program program)
Definition at line 320 of file pi_cuda.cpp.
References pi2ur::piProgramRetain().
Referenced by sycl::_V1::detail::ProgramManager::build(), sycl::_V1::detail::program_impl::get(), sycl::_V1::detail::ProgramManager::getBuiltPIProgram(), sycl::_V1::detail::device_image_impl::getNative(), sycl::_V1::detail::program_impl::getNative(), sycl::_V1::detail::ProgramManager::getOrCreateKernel(), sycl::_V1::detail::make_kernel_bundle(), and piPluginInit().
piQueueCreate()
pi_result piQueueCreate (pi_context context, pi_device device, pi_queue_properties properties, pi_queue * queue)
Definition at line 161 of file pi_cuda.cpp.
References PI_QUEUE_FLAGS, piextQueueCreate(), and pi2ur::piQueueCreate().
Referenced by piPluginInit().
piQueueFinish()
pi_result piQueueFinish (pi_queue command_queue)
Definition at line 186 of file pi_cuda.cpp.
References pi2ur::piQueueFinish().
Referenced by sycl::_V1::detail::queue_impl::getExclusiveQueueHandleRef(), piPluginInit(), and sycl::_V1::detail::queue_impl::wait().
piQueueFlush()
pi_result piQueueFlush (pi_queue command_queue)
Definition at line 188 of file pi_cuda.cpp.
References pi2ur::piQueueFlush().
Referenced by sycl::_V1::detail::event_impl::flushIfNeeded(), and piPluginInit().
piQueueGetInfo()
pi_result piQueueGetInfo (pi_queue command_queue, pi_queue_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 172 of file pi_cuda.cpp.
References pi2ur::piQueueGetInfo().
Referenced by sycl::_V1::detail::queue_impl::ext_oneapi_empty(), piPluginInit(), and sycl::_V1::detail::queue_impl::get_info< info::queue::reference_count >().
piQueueRelease()
pi_result piQueueRelease (pi_queue command_queue)
Definition at line 182 of file pi_cuda.cpp.
References pi2ur::piQueueRelease().
Referenced by piPluginInit(), and sycl::_V1::detail::queue_impl::~queue_impl().
piQueueRetain()
pi_result piQueueRetain (pi_queue command_queue)
Definition at line 180 of file pi_cuda.cpp.
References pi2ur::piQueueRetain().
Referenced by sycl::_V1::detail::queue_impl::get(), sycl::_V1::detail::queue_impl::getNative(), and piPluginInit().
piSamplerCreate()
pi_result piSamplerCreate (pi_context context, const pi_sampler_properties * sampler_properties, pi_sampler * result_sampler)
Definition at line 635 of file pi_cuda.cpp.
References pi2ur::piSamplerCreate().
Referenced by sycl::_V1::detail::sampler_impl::getOrCreateSampler(), and piPluginInit().
piSamplerGetInfo()
pi_result piSamplerGetInfo (pi_sampler sampler, pi_sampler_info param_name, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
Definition at line 641 of file pi_cuda.cpp.
References pi2ur::piSamplerGetInfo().
Referenced by piPluginInit(), and sycl::_V1::detail::sampler_impl::sampler_impl().
piSamplerRelease()
pi_result piSamplerRelease (pi_sampler sampler)
Definition at line 653 of file pi_cuda.cpp.
References pi2ur::piSamplerRelease().
Referenced by piPluginInit(), and sycl::_V1::detail::sampler_impl::~sampler_impl().
piSamplerRetain()
pi_result piSamplerRetain (pi_sampler sampler)
Definition at line 649 of file pi_cuda.cpp.
References pi2ur::piSamplerRetain().
Referenced by piPluginInit(), and sycl::_V1::detail::sampler_impl::sampler_impl().
piTearDown()
pi_result piTearDown (void * PluginParameter)
API to notify that the plugin should clean up its resources.
No PI calls should be made until the next piPluginInit call.
Parameters
PluginParameter placeholder for future use, currenly not used.
Definition at line 1243 of file pi_cuda.cpp.
References Adapters, pi2ur::piTearDown(), releaseAdapters(), and AdapterHolder::Vec.
Referenced by piPluginInit(), and sycl::_V1::detail::GlobalHandler::unloadPlugins().
Variable Documentation
PI_DEVICE_AFFINITY_DOMAIN_L1_CACHE
constexpr pi_device_affinity_domain PI_DEVICE_AFFINITY_DOMAIN_L1_CACHE static constexpr
Initial value:
=
    (1 << 4)
Definition at line 891 of file pi.h.
Referenced by sycl::_V1::detail::get_device_info_impl< info::partition_affinity_domain, info::device::partition_type_affinity_domain >::get(), and sycl::_V1::detail::read_domain_bitfield().
PI_DEVICE_AFFINITY_DOMAIN_L2_CACHE
constexpr pi_device_affinity_domain PI_DEVICE_AFFINITY_DOMAIN_L2_CACHE static constexpr
Initial value:
=
    (1 << 3)
Definition at line 889 of file pi.h.
Referenced by sycl::_V1::detail::get_device_info_impl< info::partition_affinity_domain, info::device::partition_type_affinity_domain >::get(), and sycl::_V1::detail::read_domain_bitfield().
PI_DEVICE_AFFINITY_DOMAIN_L3_CACHE
constexpr pi_device_affinity_domain PI_DEVICE_AFFINITY_DOMAIN_L3_CACHE static constexpr
Initial value:
=
    (1 << 2)
Definition at line 887 of file pi.h.
Referenced by sycl::_V1::detail::get_device_info_impl< info::partition_affinity_domain, info::device::partition_type_affinity_domain >::get(), and sycl::_V1::detail::read_domain_bitfield().
PI_DEVICE_AFFINITY_DOMAIN_L4_CACHE
constexpr pi_device_affinity_domain PI_DEVICE_AFFINITY_DOMAIN_L4_CACHE static constexpr
Initial value:
=
    (1 << 1)
Definition at line 885 of file pi.h.
Referenced by sycl::_V1::detail::get_device_info_impl< info::partition_affinity_domain, info::device::partition_type_affinity_domain >::get(), and sycl::_V1::detail::read_domain_bitfield().
PI_DEVICE_AFFINITY_DOMAIN_NEXT_PARTITIONABLE
constexpr pi_device_affinity_domain PI_DEVICE_AFFINITY_DOMAIN_NEXT_PARTITIONABLE = (1 << 5) static constexpr
Definition at line 894 of file pi.h.
Referenced by sycl::_V1::detail::read_domain_bitfield(), and ur2piDeviceInfoValue().
PI_DEVICE_AFFINITY_DOMAIN_NUMA
constexpr pi_device_affinity_domain PI_DEVICE_AFFINITY_DOMAIN_NUMA static constexpr
Initial value:
=
    (1 << 0)
Definition at line 883 of file pi.h.
Referenced by sycl::_V1::detail::get_device_info_impl< info::partition_affinity_domain, info::device::partition_type_affinity_domain >::get(), sycl::_V1::detail::read_domain_bitfield(), and ur2piDeviceInfoValue().
PI_DEVICE_BINARIES_VERSION
const uint16_t PI_DEVICE_BINARIES_VERSION = 1 static
Definition at line 1133 of file pi.h.
Referenced by sycl::_V1::detail::DeviceBinariesCollection::getPIDeviceStruct().
PI_DEVICE_BINARY_OFFLOAD_KIND_SYCL
const uint8_t PI_DEVICE_BINARY_OFFLOAD_KIND_SYCL = 4 static
Definition at line 970 of file pi.h.
Referenced by sycl::_V1::detail::DynRTDeviceBinaryImage::DynRTDeviceBinaryImage(), and sycl::_V1::detail::DeviceBinaryContainer::getPIDeviceBinary().
PI_DEVICE_BINARY_TYPE_LLVMIR_BITCODE
constexpr pi_device_binary_type PI_DEVICE_BINARY_TYPE_LLVMIR_BITCODE = 3 static constexpr
Definition at line 964 of file pi.h.
Referenced by sycl::_V1::detail::pi::getBinaryImageFormat(), and sycl::_V1::detail::getFormatStr().
PI_DEVICE_BINARY_TYPE_NATIVE
constexpr pi_device_binary_type PI_DEVICE_BINARY_TYPE_NATIVE = 1 static constexpr
Definition at line 959 of file pi.h.
Referenced by sycl::_V1::detail::pi::getBinaryImageFormat(), sycl::_V1::detail::getFormatStr(), and sycl::_V1::detail::IsSupportedImageFormat().
PI_DEVICE_BINARY_TYPE_NONE
constexpr pi_device_binary_type PI_DEVICE_BINARY_TYPE_NONE = 0 static constexpr
Definition at line 957 of file pi.h.
Referenced by sycl::_V1::detail::ProgramManager::createPIProgram(), sycl::_V1::detail::pi::getBinaryImageFormat(), sycl::_V1::detail::getFormatStr(), and sycl::_V1::detail::RTDeviceBinaryImage::init().
PI_DEVICE_BINARY_TYPE_SPIRV
constexpr pi_device_binary_type PI_DEVICE_BINARY_TYPE_SPIRV = 2 static constexpr
Definition at line 962 of file pi.h.
Referenced by sycl::_V1::detail::ProgramManager::build(), sycl::_V1::detail::ProgramManager::compile(), sycl::_V1::detail::ProgramManager::createPIProgram(), sycl::_V1::detail::DynRTDeviceBinaryImage::DynRTDeviceBinaryImage(), sycl::_V1::detail::pi::getBinaryImageFormat(), sycl::_V1::detail::ProgramManager::getBuiltPIProgram(), sycl::_V1::detail::getFormatStr(), sycl::_V1::detail::isDeviceBinaryTypeSupported(), sycl::_V1::detail::IsSupportedImageFormat(), and sycl::_V1::detail::RTDeviceBinaryImage::supportsSpecConstants().
PI_DEVICE_BINARY_VERSION
const uint16_t PI_DEVICE_BINARY_VERSION = 1 static
Definition at line 967 of file pi.h.
Referenced by sycl::_V1::detail::DynRTDeviceBinaryImage::DynRTDeviceBinaryImage(), and sycl::_V1::detail::DeviceBinaryContainer::getPIDeviceBinary().
PI_DEVICE_EXEC_CAPABILITIES_KERNEL
constexpr pi_device_exec_capabilities PI_DEVICE_EXEC_CAPABILITIES_KERNEL constexpr
Initial value:
=
    (1 << 0)
Definition at line 735 of file pi.h.
Referenced by ur2piDeviceInfoValue().
PI_DEVICE_EXEC_CAPABILITIES_NATIVE_KERNEL
constexpr pi_device_exec_capabilities PI_DEVICE_EXEC_CAPABILITIES_NATIVE_KERNEL = (1 << 1) constexpr
Definition at line 738 of file pi.h.
Referenced by ur2piDeviceInfoValue().
PI_DEVICE_PARTITION_BY_AFFINITY_DOMAIN
constexpr pi_device_partition_property PI_DEVICE_PARTITION_BY_AFFINITY_DOMAIN = 0x1088 static constexpr
Definition at line 877 of file pi.h.
Referenced by sycl::_V1::detail::device_impl::create_sub_devices(), pi2ur::piDevicePartition(), and ur2piDeviceInfoValue().
PI_DEVICE_PARTITION_BY_COUNTS
constexpr pi_device_partition_property PI_DEVICE_PARTITION_BY_COUNTS static constexpr
Initial value:
=
    0x1087
Definition at line 872 of file pi.h.
Referenced by sycl::_V1::detail::device_impl::create_sub_devices(), pi2ur::piDevicePartition(), and ur2piDeviceInfoValue().
PI_DEVICE_PARTITION_BY_COUNTS_LIST_END
constexpr pi_device_partition_property PI_DEVICE_PARTITION_BY_COUNTS_LIST_END = 0x0 static constexpr
Definition at line 875 of file pi.h.
Referenced by sycl::_V1::detail::device_impl::create_sub_devices().
PI_DEVICE_PARTITION_EQUALLY
constexpr pi_device_partition_property PI_DEVICE_PARTITION_EQUALLY static constexpr
Initial value:
=
    0x1086
Definition at line 870 of file pi.h.
Referenced by sycl::_V1::detail::device_impl::create_sub_devices(), pi2ur::piDevicePartition(), and ur2piDeviceInfoValue().
PI_EXEC_KERNEL
constexpr pi_device_exec_capabilities PI_EXEC_KERNEL = (1 << 0) static constexpr
Definition at line 910 of file pi.h.
Referenced by sycl::_V1::detail::read_execution_bitfield().
PI_EXEC_NATIVE_KERNEL
constexpr pi_device_exec_capabilities PI_EXEC_NATIVE_KERNEL = (1 << 1) static constexpr
Definition at line 911 of file pi.h.
Referenced by sycl::_V1::detail::read_execution_bitfield().
PI_EXT_INTEL_DEVICE_PARTITION_BY_CSLICE
constexpr pi_device_partition_property PI_EXT_INTEL_DEVICE_PARTITION_BY_CSLICE = 0x1089 static constexpr
Definition at line 879 of file pi.h.
Referenced by sycl::_V1::detail::device_impl::create_sub_devices(), pi2ur::piDevicePartition(), and ur2piDeviceInfoValue().
PI_EXT_ONEAPI_QUEUE_FLAG_DISCARD_EVENTS
constexpr pi_queue_properties PI_EXT_ONEAPI_QUEUE_FLAG_DISCARD_EVENTS = (1 << 4) constexpr
Definition at line 817 of file pi.h.
Referenced by sycl::_V1::detail::queue_impl::createPiQueueProperties(), pi2ur::piextQueueCreate(), and pi2ur::piextQueueCreateWithNativeHandle().
PI_EXT_ONEAPI_QUEUE_FLAG_PRIORITY_HIGH
constexpr pi_queue_properties PI_EXT_ONEAPI_QUEUE_FLAG_PRIORITY_HIGH = (1 << 6) constexpr
Definition at line 819 of file pi.h.
Referenced by sycl::_V1::detail::queue_impl::createPiQueueProperties(), pi2ur::piextQueueCreate(), and pi2ur::piextQueueCreateWithNativeHandle().
PI_EXT_ONEAPI_QUEUE_FLAG_PRIORITY_LOW
constexpr pi_queue_properties PI_EXT_ONEAPI_QUEUE_FLAG_PRIORITY_LOW = (1 << 5) constexpr
Definition at line 818 of file pi.h.
Referenced by sycl::_V1::detail::queue_impl::createPiQueueProperties(), pi2ur::piextQueueCreate(), and pi2ur::piextQueueCreateWithNativeHandle().
PI_EXT_QUEUE_FLAG_SUBMISSION_IMMEDIATE
constexpr pi_queue_properties PI_EXT_QUEUE_FLAG_SUBMISSION_IMMEDIATE = (1 << 8) constexpr
Definition at line 821 of file pi.h.
Referenced by sycl::_V1::detail::queue_impl::createPiQueueProperties(), and pi2ur::piextQueueCreate().
PI_EXT_QUEUE_FLAG_SUBMISSION_NO_IMMEDIATE
constexpr pi_queue_properties PI_EXT_QUEUE_FLAG_SUBMISSION_NO_IMMEDIATE = (1 << 7) constexpr
Definition at line 820 of file pi.h.
Referenced by sycl::_V1::detail::queue_impl::createPiQueueProperties(), and pi2ur::piextQueueCreate().
PI_FALSE
const pi_bool PI_FALSE = 0
Definition at line 701 of file pi.h.
Referenced by sycl::_V1::detail::MemoryManager::copy_2d_usm(), sycl::_V1::detail::MemoryManager::copy_usm(), sycl::_V1::detail::copyD2H(), sycl::_V1::detail::copyH2D(), sycl::_V1::detail::device_impl::has(), and sycl::_V1::detail::MemoryManager::map().
PI_FP_CORRECTLY_ROUNDED_DIVIDE_SQRT
constexpr pi_device_fp_config PI_FP_CORRECTLY_ROUNDED_DIVIDE_SQRT static constexpr
Initial value:
=
    (1 << 7)
Definition at line 905 of file pi.h.
Referenced by sycl::_V1::detail::read_fp_bitfield().
PI_FP_DENORM
constexpr pi_device_fp_config PI_FP_DENORM = (1 << 0) static constexpr
Definition at line 898 of file pi.h.
Referenced by sycl::_V1::detail::read_fp_bitfield().
PI_FP_FMA
constexpr pi_device_fp_config PI_FP_FMA = (1 << 5) static constexpr
Definition at line 903 of file pi.h.
Referenced by sycl::_V1::detail::read_fp_bitfield().
PI_FP_INF_NAN
constexpr pi_device_fp_config PI_FP_INF_NAN = (1 << 1) static constexpr
Definition at line 899 of file pi.h.
Referenced by sycl::_V1::detail::read_fp_bitfield().
PI_FP_ROUND_TO_INF
constexpr pi_device_fp_config PI_FP_ROUND_TO_INF = (1 << 4) static constexpr
Definition at line 902 of file pi.h.
Referenced by sycl::_V1::detail::read_fp_bitfield().
PI_FP_ROUND_TO_NEAREST
constexpr pi_device_fp_config PI_FP_ROUND_TO_NEAREST = (1 << 2) static constexpr
Definition at line 900 of file pi.h.
Referenced by sycl::_V1::detail::read_fp_bitfield().
PI_FP_ROUND_TO_ZERO
constexpr pi_device_fp_config PI_FP_ROUND_TO_ZERO = (1 << 3) static constexpr
Definition at line 901 of file pi.h.
Referenced by sycl::_V1::detail::read_fp_bitfield().
PI_FP_SOFT_FLOAT
constexpr pi_device_fp_config PI_FP_SOFT_FLOAT = (1 << 6) static constexpr
Definition at line 904 of file pi.h.
Referenced by sycl::_V1::detail::read_fp_bitfield().
PI_MAP_READ
constexpr pi_map_flags PI_MAP_READ = (1 << 0) constexpr
Definition at line 785 of file pi.h.
Referenced by sycl::_V1::detail::MemoryManager::map(), and pi2ur::piEnqueueMemBufferMap().
PI_MAP_WRITE
constexpr pi_map_flags PI_MAP_WRITE = (1 << 1) constexpr
Definition at line 786 of file pi.h.
Referenced by sycl::_V1::detail::MemoryManager::map(), and pi2ur::piEnqueueMemBufferMap().
PI_MAP_WRITE_INVALIDATE_REGION
constexpr pi_map_flags PI_MAP_WRITE_INVALIDATE_REGION = (1 << 2) constexpr
Definition at line 787 of file pi.h.
Referenced by sycl::_V1::detail::MemoryManager::map(), and pi2ur::piEnqueueMemBufferMap().
PI_MEM_ACCESS_READ_ONLY
constexpr pi_mem_flags PI_MEM_ACCESS_READ_ONLY = (1 << 2) constexpr
Definition at line 777 of file pi.h.
Referenced by sycl::_V1::detail::getMemObjCreationFlags(), pi2ur::piMemBufferCreate(), pi2ur::piMemBufferPartition(), and pi2ur::piMemImageCreate().
PI_MEM_ADVICE_HIP_SET_ACCESSED_BY
constexpr _pi_mem_advice PI_MEM_ADVICE_HIP_SET_ACCESSED_BY static constexpr
Initial value:
=
    PI_MEM_ADVICE_CUDA_SET_ACCESSED_BY
Definition at line 642 of file pi.h.
PI_MEM_ADVICE_HIP_SET_ACCESSED_BY_HOST
constexpr _pi_mem_advice PI_MEM_ADVICE_HIP_SET_ACCESSED_BY_HOST static constexpr
Initial value:
=
    PI_MEM_ADVICE_CUDA_SET_ACCESSED_BY_HOST
Definition at line 651 of file pi.h.
PI_MEM_ADVICE_HIP_SET_PREFERRED_LOCATION
constexpr _pi_mem_advice PI_MEM_ADVICE_HIP_SET_PREFERRED_LOCATION static constexpr
Initial value:
=
    PI_MEM_ADVICE_CUDA_SET_PREFERRED_LOCATION
Definition at line 638 of file pi.h.
PI_MEM_ADVICE_HIP_SET_PREFERRED_LOCATION_HOST
constexpr _pi_mem_advice PI_MEM_ADVICE_HIP_SET_PREFERRED_LOCATION_HOST static constexpr
Initial value:
=
    PI_MEM_ADVICE_CUDA_SET_PREFERRED_LOCATION_HOST
Definition at line 646 of file pi.h.
PI_MEM_ADVICE_HIP_SET_READ_MOSTLY
constexpr _pi_mem_advice PI_MEM_ADVICE_HIP_SET_READ_MOSTLY static constexpr
Initial value:
=
    PI_MEM_ADVICE_CUDA_SET_READ_MOSTLY
Definition at line 634 of file pi.h.
PI_MEM_ADVICE_HIP_UNSET_ACCESSED_BY
constexpr _pi_mem_advice PI_MEM_ADVICE_HIP_UNSET_ACCESSED_BY static constexpr
Initial value:
=
    PI_MEM_ADVICE_CUDA_UNSET_ACCESSED_BY
Definition at line 644 of file pi.h.
PI_MEM_ADVICE_HIP_UNSET_ACCESSED_BY_HOST
constexpr _pi_mem_advice PI_MEM_ADVICE_HIP_UNSET_ACCESSED_BY_HOST static constexpr
Initial value:
=
    PI_MEM_ADVICE_CUDA_UNSET_ACCESSED_BY_HOST
Definition at line 653 of file pi.h.
PI_MEM_ADVICE_HIP_UNSET_PREFERRED_LOCATION
constexpr _pi_mem_advice PI_MEM_ADVICE_HIP_UNSET_PREFERRED_LOCATION static constexpr
Initial value:
=
    PI_MEM_ADVICE_CUDA_UNSET_PREFERRED_LOCATION
Definition at line 640 of file pi.h.
PI_MEM_ADVICE_HIP_UNSET_PREFERRED_LOCATION_HOST
constexpr _pi_mem_advice PI_MEM_ADVICE_HIP_UNSET_PREFERRED_LOCATION_HOST static constexpr
Initial value:
=
        PI_MEM_ADVICE_CUDA_UNSET_PREFERRED_LOCATION_HOST
Definition at line 649 of file pi.h.
PI_MEM_ADVICE_HIP_UNSET_READ_MOSTLY
constexpr _pi_mem_advice PI_MEM_ADVICE_HIP_UNSET_READ_MOSTLY static constexpr
Initial value:
=
    PI_MEM_ADVICE_CUDA_UNSET_READ_MOSTLY
Definition at line 636 of file pi.h.
PI_MEM_ALLOC_DEVICE_READ_ONLY
constexpr pi_usm_mem_properties PI_MEM_ALLOC_DEVICE_READ_ONLY = (1 << 3) constexpr
Definition at line 803 of file pi.h.
Referenced by sycl::_V1::detail::usm::alignedAllocInternal(), and pi2ur::piextUSMSharedAlloc().
PI_MEM_ALLOC_FLAGS
constexpr pi_usm_mem_properties PI_MEM_ALLOC_FLAGS = 0x4195 constexpr
Definition at line 797 of file pi.h.
Referenced by sycl::_V1::detail::usm::alignedAllocInternal(), and pi2ur::piextUSMSharedAlloc().
PI_MEM_ALLOC_INITIAL_PLACEMENT_DEVICE
constexpr pi_usm_mem_properties PI_MEM_ALLOC_INITIAL_PLACEMENT_DEVICE constexpr
Initial value:
=
    (1 << 1)
Definition at line 799 of file pi.h.
Referenced by pi2ur::piextUSMSharedAlloc().
PI_MEM_ALLOC_INITIAL_PLACEMENT_HOST
constexpr pi_usm_mem_properties PI_MEM_ALLOC_INITIAL_PLACEMENT_HOST = (1 << 2) constexpr
Definition at line 801 of file pi.h.
Referenced by pi2ur::piextUSMSharedAlloc().
PI_MEM_ALLOC_WRTITE_COMBINED
constexpr pi_usm_mem_properties PI_MEM_ALLOC_WRTITE_COMBINED = (1 << 0) constexpr
Definition at line 798 of file pi.h.
Referenced by pi2ur::piextUSMSharedAlloc().
PI_MEM_FLAGS_ACCESS_RW
constexpr pi_mem_flags PI_MEM_FLAGS_ACCESS_RW = (1 << 0) constexpr
Definition at line 776 of file pi.h.
Referenced by sycl::_V1::detail::MemoryManager::allocateMemSubBuffer(), sycl::_V1::detail::device_image_impl::get_spec_const_buffer_ref(), sycl::_V1::detail::getMemObjCreationFlags(), sycl::_V1::detail::pi::memFlagsToString(), sycl::_V1::detail::pi::memFlagToString(), pi2ur::piMemBufferCreate(), pi2ur::piMemBufferPartition(), and pi2ur::piMemImageCreate().
PI_MEM_FLAGS_HOST_PTR_ALLOC
constexpr pi_mem_flags PI_MEM_FLAGS_HOST_PTR_ALLOC = (1 << 4) constexpr
Definition at line 781 of file pi.h.
Referenced by sycl::_V1::detail::MemoryManager::allocateBufferObject(), pi2ur::piMemBufferCreate(), pi2ur::piMemBufferPartition(), and pi2ur::piMemImageCreate().
PI_MEM_FLAGS_HOST_PTR_COPY
constexpr pi_mem_flags PI_MEM_FLAGS_HOST_PTR_COPY = (1 << 5) constexpr
Definition at line 780 of file pi.h.
Referenced by sycl::_V1::detail::device_image_impl::get_spec_const_buffer_ref(), sycl::_V1::detail::pi::memFlagsToString(), sycl::_V1::detail::pi::memFlagToString(), pi2ur::piMemBufferCreate(), pi2ur::piMemBufferPartition(), and pi2ur::piMemImageCreate().
PI_MEM_FLAGS_HOST_PTR_USE
constexpr pi_mem_flags PI_MEM_FLAGS_HOST_PTR_USE = (1 << 3) constexpr
Definition at line 779 of file pi.h.
Referenced by sycl::_V1::detail::getMemObjCreationFlags(), sycl::_V1::detail::pi::memFlagsToString(), sycl::_V1::detail::pi::memFlagToString(), pi2ur::piMemBufferCreate(), pi2ur::piMemBufferPartition(), and pi2ur::piMemImageCreate().
PI_MEM_PROPERTIES_ALLOC_BUFFER_LOCATION
constexpr pi_mem_properties PI_MEM_PROPERTIES_ALLOC_BUFFER_LOCATION = 0x419E constexpr
Definition at line 792 of file pi.h.
Referenced by sycl::_V1::detail::MemoryManager::allocateBufferObject(), and pi2ur::piMemBufferCreate().
PI_MEM_PROPERTIES_CHANNEL
constexpr pi_mem_properties PI_MEM_PROPERTIES_CHANNEL = 0x4213 constexpr
Definition at line 791 of file pi.h.
Referenced by sycl::_V1::detail::MemoryManager::allocateBufferObject(), and pi2ur::piMemBufferCreate().
PI_MEM_USM_ALLOC_BUFFER_LOCATION
constexpr pi_usm_mem_properties PI_MEM_USM_ALLOC_BUFFER_LOCATION = 0x419E constexpr
Definition at line 805 of file pi.h.
Referenced by sycl::_V1::detail::usm::alignedAllocHost(), sycl::_V1::detail::usm::alignedAllocInternal(), pi2ur::piextUSMDeviceAlloc(), pi2ur::piextUSMHostAlloc(), and pi2ur::piextUSMSharedAlloc().
PI_MEMORY_ORDER_ACQ_REL
constexpr pi_memory_order_capabilities PI_MEMORY_ORDER_ACQ_REL = 0x08 constexpr
Definition at line 753 of file pi.h.
Referenced by sycl::_V1::detail::readMemoryOrderBitfield(), and ur2piDeviceInfoValue().
PI_MEMORY_ORDER_ACQUIRE
constexpr pi_memory_order_capabilities PI_MEMORY_ORDER_ACQUIRE = 0x02 constexpr
Definition at line 751 of file pi.h.
Referenced by sycl::_V1::detail::readMemoryOrderBitfield(), and ur2piDeviceInfoValue().
PI_MEMORY_ORDER_RELAXED
constexpr pi_memory_order_capabilities PI_MEMORY_ORDER_RELAXED = 0x01 constexpr
Definition at line 750 of file pi.h.
Referenced by sycl::_V1::detail::readMemoryOrderBitfield(), and ur2piDeviceInfoValue().
PI_MEMORY_ORDER_RELEASE
constexpr pi_memory_order_capabilities PI_MEMORY_ORDER_RELEASE = 0x04 constexpr
Definition at line 752 of file pi.h.
Referenced by sycl::_V1::detail::readMemoryOrderBitfield(), and ur2piDeviceInfoValue().
PI_MEMORY_ORDER_SEQ_CST
constexpr pi_memory_order_capabilities PI_MEMORY_ORDER_SEQ_CST = 0x10 constexpr
Definition at line 754 of file pi.h.
Referenced by sycl::_V1::detail::readMemoryOrderBitfield(), and ur2piDeviceInfoValue().
PI_MEMORY_SCOPE_DEVICE
constexpr pi_memory_scope_capabilities PI_MEMORY_SCOPE_DEVICE = 0x08 constexpr
Definition at line 760 of file pi.h.
Referenced by sycl::_V1::detail::readMemoryScopeBitfield(), and ur2piDeviceInfoValue().
PI_MEMORY_SCOPE_SUB_GROUP
constexpr pi_memory_scope_capabilities PI_MEMORY_SCOPE_SUB_GROUP = 0x02 constexpr
Definition at line 758 of file pi.h.
Referenced by sycl::_V1::detail::readMemoryScopeBitfield(), and ur2piDeviceInfoValue().
PI_MEMORY_SCOPE_SYSTEM
constexpr pi_memory_scope_capabilities PI_MEMORY_SCOPE_SYSTEM = 0x10 constexpr
Definition at line 761 of file pi.h.
Referenced by sycl::_V1::detail::readMemoryScopeBitfield(), and ur2piDeviceInfoValue().
PI_MEMORY_SCOPE_WORK_GROUP
constexpr pi_memory_scope_capabilities PI_MEMORY_SCOPE_WORK_GROUP = 0x04 constexpr
Definition at line 759 of file pi.h.
Referenced by sycl::_V1::detail::readMemoryScopeBitfield(), and ur2piDeviceInfoValue().
PI_MEMORY_SCOPE_WORK_ITEM
constexpr pi_memory_scope_capabilities PI_MEMORY_SCOPE_WORK_ITEM = 0x01 constexpr
Definition at line 757 of file pi.h.
Referenced by sycl::_V1::detail::readMemoryScopeBitfield(), and ur2piDeviceInfoValue().
PI_QUEUE_COMPUTE_INDEX
constexpr pi_queue_properties PI_QUEUE_COMPUTE_INDEX = -2 constexpr
Definition at line 811 of file pi.h.
Referenced by sycl::_V1::detail::queue_impl::createQueue(), and pi2ur::piextQueueCreate().
PI_QUEUE_FLAG_ON_DEVICE
constexpr pi_queue_properties PI_QUEUE_FLAG_ON_DEVICE = (1 << 2) constexpr
Definition at line 815 of file pi.h.
Referenced by pi2ur::piextQueueCreate(), pi2ur::piextQueueCreateWithNativeHandle(), and ur2piDeviceInfoValue().
PI_QUEUE_FLAG_ON_DEVICE_DEFAULT
constexpr pi_queue_properties PI_QUEUE_FLAG_ON_DEVICE_DEFAULT = (1 << 3) constexpr
Definition at line 816 of file pi.h.
Referenced by pi2ur::piextQueueCreate(), pi2ur::piextQueueCreateWithNativeHandle(), and ur2piDeviceInfoValue().
PI_QUEUE_FLAG_OUT_OF_ORDER_EXEC_MODE_ENABLE
constexpr pi_queue_properties PI_QUEUE_FLAG_OUT_OF_ORDER_EXEC_MODE_ENABLE = (1 << 0) constexpr
Definition at line 813 of file pi.h.
Referenced by sycl::_V1::detail::queue_impl::createPiQueueProperties(), pi2ur::piextQueueCreate(), pi2ur::piextQueueCreateWithNativeHandle(), and ur2piDeviceInfoValue().
PI_QUEUE_FLAG_PROFILING_ENABLE
constexpr pi_queue_properties PI_QUEUE_FLAG_PROFILING_ENABLE = (1 << 1) constexpr
Definition at line 814 of file pi.h.
Referenced by sycl::_V1::detail::queue_impl::createPiQueueProperties(), sycl::_V1::detail::get_device_info_impl< bool, info::device::queue_profiling >::get(), pi2ur::piextQueueCreate(), pi2ur::piextQueueCreateWithNativeHandle(), and ur2piDeviceInfoValue().
PI_QUEUE_FLAGS
constexpr pi_queue_properties PI_QUEUE_FLAGS = -1 constexpr
Definition at line 810 of file pi.h.
Referenced by sycl::_V1::detail::queue_impl::createQueue(), sycl::_V1::detail::make_queue(), pi2ur::piextQueueCreate(), pi2ur::piQueueCreate(), and piQueueCreate().
PI_SAMPLER_PROPERTIES_ADDRESSING_MODE
constexpr pi_sampler_properties PI_SAMPLER_PROPERTIES_ADDRESSING_MODE = 0x1153 constexpr
Definition at line 743 of file pi.h.
Referenced by sycl::_V1::ext::oneapi::experimental::create_image(), pi2ur::piextBindlessImageSamplerCreate(), and pi2ur::piSamplerCreate().
PI_SAMPLER_PROPERTIES_CUBEMAP_FILTER_MODE
constexpr pi_sampler_properties PI_SAMPLER_PROPERTIES_CUBEMAP_FILTER_MODE constexpr
Initial value:
=
    0x1156
Definition at line 746 of file pi.h.
Referenced by sycl::_V1::ext::oneapi::experimental::create_image(), and pi2ur::piextBindlessImageSamplerCreate().
PI_SAMPLER_PROPERTIES_FILTER_MODE
constexpr pi_sampler_properties PI_SAMPLER_PROPERTIES_FILTER_MODE = 0x1154 constexpr
Definition at line 744 of file pi.h.
Referenced by sycl::_V1::ext::oneapi::experimental::create_image(), pi2ur::piextBindlessImageSamplerCreate(), and pi2ur::piSamplerCreate().
PI_SAMPLER_PROPERTIES_MIP_FILTER_MODE
constexpr pi_sampler_properties PI_SAMPLER_PROPERTIES_MIP_FILTER_MODE = 0x1155 constexpr
Definition at line 745 of file pi.h.
Referenced by sycl::_V1::ext::oneapi::experimental::create_image(), and pi2ur::piextBindlessImageSamplerCreate().
PI_SAMPLER_PROPERTIES_NORMALIZED_COORDS
constexpr pi_sampler_properties PI_SAMPLER_PROPERTIES_NORMALIZED_COORDS constexpr
Initial value:
=
    0x1152
Definition at line 741 of file pi.h.
Referenced by sycl::_V1::ext::oneapi::experimental::create_image(), pi2ur::piextBindlessImageSamplerCreate(), and pi2ur::piSamplerCreate().
PI_TRUE
const pi_bool PI_TRUE = 1
Definition at line 700 of file pi.h.
Referenced by sycl::_V1::detail::ProgramManager::getBuiltPIProgram(), sycl::_V1::detail::ProgramManager::getOrCreateKernel(), and sycl::_V1::detail::kernel_impl::kernel_impl().