DPC++ Runtime: plugins/level_zero/pi_level_zero.cpp File Reference
pi_level_zero.cpp File Reference
The Plugin Interface » Level Zero Plugin
#include "pi_level_zero.hpp"
#include <CL/sycl/detail/spinlock.hpp>
#include <algorithm>
#include <cstdarg>
#include <cstdio>
#include <cstring>
#include <memory>
#include <set>
#include <sstream>
#include <string>
#include <thread>
#include <utility>
#include <level_zero/zet_api.h>
#include "usm_allocator.hpp"
#include <CL/sycl/detail/pi.def>
Classes
struct CommandListBatchConfig
class ZeUSMImportExtension
class UsmAllocationException
Macros
#define ZE_CALL(ZeName, ZeArgs)
#define ZE_CALL_NOCHECK(ZeName, ZeArgs) ZeCall().doCall(ZeName ZeArgs, #ZeName, #ZeArgs, false)
#define PI_CALL(Call)
#define ZE_ERRCASE(ERR)
#define PI_ASSERT(condition, error)
#define _PI_API(api) (PluginInit->PiFunctionTable).api = (decltype(&::api))(&api);
Typedefs
typedef struct CommandListBatchConfig zeCommandListBatchConfig
Functions
static pi_result EventRelease (pi_event Event, pi_queue LockedQueue)
static pi_result QueueRelease (pi_queue Queue, pi_queue LockedQueue)
static pi_result EventCreate (pi_context Context, pi_queue Queue, bool HostVisible, pi_event *RetEvent)
static pi_result enqueueMemCopyHelper (pi_command_type CommandType, pi_queue Queue, void *Dst, pi_bool BlockingWrite, size_t Size, const void *Src, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event, bool PreferCopyEngine=false)
static pi_result enqueueMemCopyRectHelper (pi_command_type CommandType, pi_queue Queue, void *SrcBuffer, void *DstBuffer, pi_buff_rect_offset SrcOrigin, pi_buff_rect_offset DstOrigin, pi_buff_rect_region Region, size_t SrcRowPitch, size_t SrcSlicePitch, size_t DstRowPitch, size_t DstSlicePitch, pi_bool Blocking, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event, bool PreferCopyEngine=false)
void zeParseError (ze_result_t ZeError, const char *&ErrorString)
static void piQueueRetainNoLock (pi_queue Queue)
static pi_result createEventAndAssociateQueue (pi_queue Queue, pi_event *Event, pi_command_type CommandType, pi_command_list_ptr_t CommandList, bool ForceHostVisible=false)
static const zeCommandListBatchConfig ZeCommandListBatchConfig (bool IsCopy)
static void printZeEventList (const _pi_ze_event_list_t &PiZeEventList)
static ze_result_t checkUnresolvedSymbols (ze_module_handle_t ZeModule, ze_module_build_log_handle_t *ZeBuildLog)
static bool setEnvVar (const char *name, const char *value)
pi_result piPlatformsGet (pi_uint32 NumEntries, pi_platform *Platforms, pi_uint32 *NumPlatforms)
pi_result piPlatformGetInfo (pi_platform Platform, pi_platform_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piextPlatformGetNativeHandle (pi_platform Platform, pi_native_handle *NativeHandle)
Gets the native handle of a PI platform object.
pi_result piextPlatformCreateWithNativeHandle (pi_native_handle NativeHandle, pi_platform *Platform)
Creates PI platform object from a native handle.
pi_result piDevicesGet (pi_platform Platform, pi_device_type DeviceType, pi_uint32 NumEntries, pi_device *Devices, pi_uint32 *NumDevices)
pi_result piDeviceRetain (pi_device Device)
pi_result piDeviceRelease (pi_device Device)
pi_result piDeviceGetInfo (pi_device Device, pi_device_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
Returns requested info for provided native device Return PI_DEVICE_INFO_EXTENSION_DEVICELIB_ASSERT for PI_DEVICE_INFO_EXTENSIONS query when the device supports native asserts.
pi_result piDevicePartition (pi_device Device, const pi_device_partition_property *Properties, pi_uint32 NumDevices, pi_device *OutDevices, pi_uint32 *OutNumDevices)
pi_result piextDeviceSelectBinary (pi_device Device, pi_device_binary *Binaries, pi_uint32 NumBinaries, pi_uint32 *SelectedBinaryInd)
Selects the most appropriate device binary based on runtime information and the IR characteristics.
pi_result piextDeviceGetNativeHandle (pi_device Device, pi_native_handle *NativeHandle)
Gets the native handle of a PI device object.
pi_result piextDeviceCreateWithNativeHandle (pi_native_handle NativeHandle, pi_platform Platform, pi_device *Device)
Creates PI device object from a native handle.
pi_result piContextCreate (const pi_context_properties *Properties, pi_uint32 NumDevices, const pi_device *Devices, void(*PFnNotify)(const char *ErrInfo, const void *PrivateInfo, size_t CB, void *UserData), void *UserData, pi_context *RetContext)
pi_result piContextGetInfo (pi_context Context, pi_context_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piextContextSetExtendedDeleter (pi_context Context, pi_context_extended_deleter Function, void *UserData)
pi_result piextContextGetNativeHandle (pi_context Context, pi_native_handle *NativeHandle)
Gets the native handle of a PI context object.
pi_result piextContextCreateWithNativeHandle (pi_native_handle NativeHandle, pi_uint32 NumDevices, const pi_device *Devices, bool OwnNativeHandle, pi_context *RetContext)
Creates PI context object from a native handle.
pi_result piContextRetain (pi_context Context)
pi_result ContextReleaseHelper (pi_context Context)
pi_result piContextRelease (pi_context Context)
pi_result piQueueCreate (pi_context Context, pi_device Device, pi_queue_properties Properties, pi_queue *Queue)
pi_result piQueueGetInfo (pi_queue Queue, pi_queue_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piQueueRetain (pi_queue Queue)
pi_result piQueueRelease (pi_queue Queue)
pi_result piQueueFinish (pi_queue Queue)
pi_result piQueueFlush (pi_queue Queue)
pi_result piextQueueGetNativeHandle (pi_queue Queue, pi_native_handle *NativeHandle)
Gets the native handle of a PI queue object.
pi_result piextQueueCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, pi_queue *Queue, bool OwnNativeHandle)
Creates PI queue object from a native handle.
static pi_result ZeDeviceMemAllocHelper (void **ResultPtr, pi_context Context, pi_device Device, size_t Size)
static pi_result ZeHostMemAllocHelper (void **ResultPtr, pi_context Context, size_t Size)
pi_result piMemBufferCreate (pi_context Context, pi_mem_flags Flags, size_t Size, void *HostPtr, pi_mem *RetMem, const pi_mem_properties *properties)
pi_result piMemGetInfo (pi_mem Mem, cl_mem_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piMemRetain (pi_mem Mem)
static pi_result ZeMemFreeHelper (pi_context Context, void *Ptr)
pi_result piMemRelease (pi_mem Mem)
pi_result piMemImageCreate (pi_context Context, pi_mem_flags Flags, const pi_image_format *ImageFormat, const pi_image_desc *ImageDesc, void *HostPtr, pi_mem *RetImage)
pi_result piextMemGetNativeHandle (pi_mem Mem, pi_native_handle *NativeHandle)
Gets the native handle of a PI mem object.
pi_result piextMemCreateWithNativeHandle (pi_native_handle NativeHandle, pi_mem *Mem)
Creates PI mem object from a native handle.
pi_result piProgramCreate (pi_context Context, const void *ILBytes, size_t Length, pi_program *Program)
pi_result piProgramCreateWithBinary (pi_context Context, pi_uint32 NumDevices, const pi_device *DeviceList, const size_t *Lengths, const unsigned char **Binaries, size_t NumMetadataEntries, const pi_device_binary_property *Metadata, pi_int32 *BinaryStatus, pi_program *Program)
Creates a PI program for a context and loads the given binary into it.
pi_result piclProgramCreateWithSource (pi_context Context, pi_uint32 Count, const char **Strings, const size_t *Lengths, pi_program *RetProgram)
pi_result piProgramGetInfo (pi_program Program, pi_program_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piProgramLink (pi_context Context, pi_uint32 NumDevices, const pi_device *DeviceList, const char *Options, pi_uint32 NumInputPrograms, const pi_program *InputPrograms, void(*PFnNotify)(pi_program Program, void *UserData), void *UserData, pi_program *RetProgram)
pi_result piProgramCompile (pi_program Program, pi_uint32 NumDevices, const pi_device *DeviceList, const char *Options, pi_uint32 NumInputHeaders, const pi_program *InputHeaders, const char **HeaderIncludeNames, void(*PFnNotify)(pi_program Program, void *UserData), void *UserData)
pi_result piProgramBuild (pi_program Program, pi_uint32 NumDevices, const pi_device *DeviceList, const char *Options, void(*PFnNotify)(pi_program Program, void *UserData), void *UserData)
pi_result piProgramGetBuildInfo (pi_program Program, pi_device Device, cl_program_build_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piProgramRetain (pi_program Program)
pi_result piProgramRelease (pi_program Program)
pi_result piextProgramGetNativeHandle (pi_program Program, pi_native_handle *NativeHandle)
Gets the native handle of a PI program object.
pi_result piextProgramCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, bool ownNativeHandle, pi_program *Program)
Creates PI program object from a native handle.
pi_result piKernelCreate (pi_program Program, const char *KernelName, pi_kernel *RetKernel)
pi_result piKernelSetArg (pi_kernel Kernel, pi_uint32 ArgIndex, size_t ArgSize, const void *ArgValue)
pi_result piextKernelSetArgMemObj (pi_kernel Kernel, pi_uint32 ArgIndex, const pi_mem *ArgValue)
pi_result piextKernelSetArgSampler (pi_kernel Kernel, pi_uint32 ArgIndex, const pi_sampler *ArgValue)
pi_result piKernelGetInfo (pi_kernel Kernel, pi_kernel_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piKernelGetGroupInfo (pi_kernel Kernel, pi_device Device, pi_kernel_group_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piKernelGetSubGroupInfo (pi_kernel Kernel, pi_device Device, pi_kernel_sub_group_info ParamName, size_t InputValueSize, const void *InputValue, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
API to query information from the sub-group from a kernel.
pi_result piKernelRetain (pi_kernel Kernel)
static pi_result USMFreeHelper (pi_context Context, void *Ptr)
pi_result piKernelRelease (pi_kernel Kernel)
pi_result piEnqueueKernelLaunch (pi_queue Queue, pi_kernel Kernel, pi_uint32 WorkDim, const size_t *GlobalWorkOffset, const size_t *GlobalWorkSize, const size_t *LocalWorkSize, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piextKernelCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, pi_program Program, bool OwnNativeHandle, pi_kernel *Kernel)
Creates PI kernel object from a native handle.
pi_result piextKernelGetNativeHandle (pi_kernel Kernel, pi_native_handle *NativeHandle)
Gets the native handle of a PI kernel object.
pi_result piEventCreate (pi_context Context, pi_event *RetEvent)
pi_result piEventGetInfo (pi_event Event, pi_event_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piEventGetProfilingInfo (pi_event Event, pi_profiling_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piEventsWait (pi_uint32 NumEvents, const pi_event *EventList)
pi_result piEventSetCallback (pi_event Event, pi_int32 CommandExecCallbackType, void(*PFnNotify)(pi_event Event, pi_int32 EventCommandStatus, void *UserData), void *UserData)
pi_result piEventSetStatus (pi_event Event, pi_int32 ExecutionStatus)
pi_result piEventRetain (pi_event Event)
pi_result piEventRelease (pi_event Event)
pi_result piextEventGetNativeHandle (pi_event Event, pi_native_handle *NativeHandle)
Gets the native handle of a PI event object.
pi_result piextEventCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, bool OwnNativeHandle, pi_event *Event)
Creates PI event object from a native handle.
pi_result piSamplerCreate (pi_context Context, const pi_sampler_properties *SamplerProperties, pi_sampler *RetSampler)
pi_result piSamplerGetInfo (pi_sampler Sampler, pi_sampler_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piSamplerRetain (pi_sampler Sampler)
pi_result piSamplerRelease (pi_sampler Sampler)
pi_result piEnqueueEventsWait (pi_queue Queue, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueEventsWaitWithBarrier (pi_queue Queue, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferRead (pi_queue Queue, pi_mem Src, pi_bool BlockingRead, size_t Offset, size_t Size, void *Dst, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferReadRect (pi_queue Queue, pi_mem Buffer, pi_bool BlockingRead, pi_buff_rect_offset BufferOffset, pi_buff_rect_offset HostOffset, pi_buff_rect_region Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, void *Ptr, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferWrite (pi_queue Queue, pi_mem Buffer, pi_bool BlockingWrite, size_t Offset, size_t Size, const void *Ptr, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferWriteRect (pi_queue Queue, pi_mem Buffer, pi_bool BlockingWrite, pi_buff_rect_offset BufferOffset, pi_buff_rect_offset HostOffset, pi_buff_rect_region Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, const void *Ptr, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferCopy (pi_queue Queue, pi_mem SrcBuffer, pi_mem DstBuffer, size_t SrcOffset, size_t DstOffset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferCopyRect (pi_queue Queue, pi_mem SrcBuffer, pi_mem DstBuffer, pi_buff_rect_offset SrcOrigin, pi_buff_rect_offset DstOrigin, pi_buff_rect_region Region, size_t SrcRowPitch, size_t SrcSlicePitch, size_t DstRowPitch, size_t DstSlicePitch, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
static pi_result enqueueMemFillHelper (pi_command_type CommandType, pi_queue Queue, void *Ptr, const void *Pattern, size_t PatternSize, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferFill (pi_queue Queue, pi_mem Buffer, const void *Pattern, size_t PatternSize, size_t Offset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
static pi_result USMHostAllocImpl (void **ResultPtr, pi_context Context, pi_usm_mem_properties *Properties, size_t Size, pi_uint32 Alignment)
pi_result piEnqueueMemBufferMap (pi_queue Queue, pi_mem Buffer, pi_bool BlockingMap, pi_map_flags MapFlags, size_t Offset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event, void **RetMap)
pi_result piEnqueueMemUnmap (pi_queue Queue, pi_mem MemObj, void *MappedPtr, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piMemImageGetInfo (pi_mem Image, pi_image_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
static pi_result getImageRegionHelper (pi_mem Mem, pi_image_offset Origin, pi_image_region Region, ze_image_region_t &ZeRegion)
static pi_result enqueueMemImageCommandHelper (pi_command_type CommandType, pi_queue Queue, const void *Src, void *Dst, pi_bool IsBlocking, pi_image_offset SrcOrigin, pi_image_offset DstOrigin, pi_image_region Region, size_t RowPitch, size_t SlicePitch, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event, bool PreferCopyEngine=false)
pi_result piEnqueueMemImageRead (pi_queue Queue, pi_mem Image, pi_bool BlockingRead, pi_image_offset Origin, pi_image_region Region, size_t RowPitch, size_t SlicePitch, void *Ptr, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemImageWrite (pi_queue Queue, pi_mem Image, pi_bool BlockingWrite, pi_image_offset Origin, pi_image_region Region, size_t InputRowPitch, size_t InputSlicePitch, const void *Ptr, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemImageCopy (pi_queue Queue, pi_mem SrcImage, pi_mem DstImage, pi_image_offset SrcOrigin, pi_image_offset DstOrigin, pi_image_region Region, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemImageFill (pi_queue Queue, pi_mem Image, const void *FillColor, const size_t *Origin, const size_t *Region, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piMemBufferPartition (pi_mem Buffer, pi_mem_flags Flags, pi_buffer_create_type BufferCreateType, void *BufferCreateInfo, pi_mem *RetMem)
pi_result piEnqueueNativeKernel (pi_queue Queue, void(*UserFunc)(void *), void *Args, size_t CbArgs, pi_uint32 NumMemObjects, const pi_mem *MemList, const void **ArgsMemLoc, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
static bool is_in_separated_string (const std::string &str, char delimiter, const std::string &sub_str)
pi_result piextGetDeviceFunctionPointer (pi_device Device, pi_program Program, const char *FunctionName, pi_uint64 *FunctionPointerRet)
Retrieves a device function pointer to a user-defined function.
static bool ShouldUseUSMAllocator ()
static pi_result USMDeviceAllocImpl (void **ResultPtr, pi_context Context, pi_device Device, pi_usm_mem_properties *Properties, size_t Size, pi_uint32 Alignment)
static pi_result USMSharedAllocImpl (void **ResultPtr, pi_context Context, pi_device Device, pi_usm_mem_properties *Properties, size_t Size, pi_uint32 Alignment)
static pi_result USMFreeImpl (pi_context Context, void *Ptr)
pi_result piextUSMDeviceAlloc (void **ResultPtr, pi_context Context, pi_device Device, pi_usm_mem_properties *Properties, size_t Size, pi_uint32 Alignment)
Allocates device memory.
pi_result piextUSMSharedAlloc (void **ResultPtr, pi_context Context, pi_device Device, pi_usm_mem_properties *Properties, size_t Size, pi_uint32 Alignment)
Allocates memory accessible on both host and device.
pi_result piextUSMHostAlloc (void **ResultPtr, pi_context Context, pi_usm_mem_properties *Properties, size_t Size, pi_uint32 Alignment)
Allocates host memory accessible by the device.
pi_result piextUSMFree (pi_context Context, void *Ptr)
Indicates that the allocated USM memory is no longer needed on the runtime side.
pi_result piextKernelSetArgPointer (pi_kernel Kernel, pi_uint32 ArgIndex, size_t ArgSize, const void *ArgValue)
Sets up pointer arguments for CL kernels.
pi_result piextUSMEnqueueMemset (pi_queue Queue, void *Ptr, pi_int32 Value, size_t Count, pi_uint32 NumEventsInWaitlist, const pi_event *EventsWaitlist, pi_event *Event)
USM Memset API.
static bool IsDevicePointer (pi_context Context, const void *Ptr)
pi_result piextUSMEnqueueMemcpy (pi_queue Queue, pi_bool Blocking, void *DstPtr, const void *SrcPtr, size_t Size, pi_uint32 NumEventsInWaitlist, const pi_event *EventsWaitlist, pi_event *Event)
USM Memcpy API.
pi_result piextUSMEnqueuePrefetch (pi_queue Queue, const void *Ptr, size_t Size, pi_usm_migration_flags Flags, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
Hint to migrate memory to the device.
pi_result piextUSMEnqueueMemAdvise (pi_queue Queue, const void *Ptr, size_t Length, pi_mem_advice Advice, pi_event *Event)
USM memadvise API to govern behavior of automatic migration mechanisms.
pi_result piextUSMGetMemAllocInfo (pi_context Context, const void *Ptr, pi_mem_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
API to query information about USM allocated pointers.
pi_result piKernelSetExecInfo (pi_kernel Kernel, pi_kernel_exec_info ParamName, size_t ParamValueSize, const void *ParamValue)
API to set attributes controlling kernel execution.
pi_result piextProgramSetSpecializationConstant (pi_program Prog, pi_uint32 SpecID, size_t, const void *SpecValue)
Sets a specialization constant to a specific value.
pi_result piPluginInit (pi_plugin *PluginInit)
pi_result piextPluginGetOpaqueData (void *opaque_data_param, void **opaque_data_return)
API to get Plugin internal data, opaque to SYCL RT.
pi_result piTearDown (void *PluginParameter)
API to notify that the plugin should clean up its resources.
Variables
static const std::pair< int, int > getRangeOfAllowedComputeEngines
static const std::pair< int, int > getRangeOfAllowedCopyEngines
static const bool CopyEngineRequested
static std::vector< pi_platform > * PiPlatformsCache
static sycl::detail::SpinLock * PiPlatformsCacheMutex
static bool PiPlatformCachePopulated = false
static bool PiDriverGlobalOffsetExtensionFound = false
static bool PiDriverModuleProgramExtensionFound = false
constexpr char ZE_SUPPORTED_EXTENSIONS []
static const int ZeMaxCommandListCacheSize
static const zeCommandListBatchConfig ZeCommandListBatchComputeConfig
static const zeCommandListBatchConfig ZeCommandListBatchCopyConfig
static const bool FilterEventWaitList
decltype(piEventCreate) piEventCreate
static class ZeUSMImportExtension ZeUSMImport
static const bool UseUSMAllocator = ShouldUseUSMAllocator()
Detailed Description
Implementation of Level Zero Plugin.
Definition in file pi_level_zero.cpp.
Macro Definition Documentation
_PI_API
#define _PI_API (api) (PluginInit->PiFunctionTable).api = (decltype(&::api))(&api);
PI_ASSERT
#define PI_ASSERT (condition, error)
Value:
  if (!(condition))                                                            \
    return error;
Definition at line 589 of file pi_level_zero.cpp.
PI_CALL
#define PI_CALL (Call)
Value:
  {                                                                            \
    if (PrintPiTrace)                                                          \
      fprintf(stderr, "PI ---> %s\n", #Call);                                  \
    pi_result Result = (Call);                                                 \
    if (Result != PI_SUCCESS)                                                  \
      return Result;                                                           \
  }
Definition at line 159 of file pi_level_zero.cpp.
ZE_CALL
#define ZE_CALL (ZeName, ZeArgs)
Value:
  {                                                                            \
    ze_result_t ZeResult = ZeName ZeArgs;                                      \
    if (auto Result = ZeCall().doCall(ZeResult, #ZeName, #ZeArgs, true))       \
      return mapError(Result);                                                 \
  }
Definition at line 148 of file pi_level_zero.cpp.
ZE_CALL_NOCHECK
#define ZE_CALL_NOCHECK (ZeName, ZeArgs) ZeCall().doCall(ZeName ZeArgs, #ZeName, #ZeArgs, false)
Definition at line 155 of file pi_level_zero.cpp.
ZE_ERRCASE
#define ZE_ERRCASE (ERR)
Value:
  case ERR:                                                                    \
    ErrorString = "" #ERR;                                                     \
    break;
Typedef Documentation
zeCommandListBatchConfig
typedef struct CommandListBatchConfig zeCommandListBatchConfig
Function Documentation
checkUnresolvedSymbols()
static ze_result_t checkUnresolvedSymbols (ze_module_handle_t ZeModule, ze_module_build_log_handle_t * ZeBuildLog) static
Definition at line 4465 of file pi_level_zero.cpp.
References ZE_CALL_NOCHECK.
Referenced by piProgramBuild(), and piProgramLink().
ContextReleaseHelper()
pi_result ContextReleaseHelper (pi_context Context)
Definition at line 3014 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_platform::Contexts, _pi_context::Devices, _pi_context::finalize(), _pi_context::OwnZeContext, PI_ASSERT, PI_INVALID_CONTEXT, PI_SUCCESS, ZE_CALL, and _pi_context::ZeContext.
Referenced by piContextRelease(), USMFreeHelper(), and ZeMemFreeHelper().
createEventAndAssociateQueue()
static pi_result createEventAndAssociateQueue (pi_queue Queue, pi_event * Event, pi_command_type CommandType, pi_command_list_ptr_t CommandList, bool ForceHostVisible = false) inline static
Definition at line 608 of file pi_level_zero.cpp.
References _pi_queue::CommandListMap, _pi_queue::Context, EventCreate(), PI_CALL, PI_SUCCESS, piEventRetain(), and piQueueRetainNoLock().
Referenced by enqueueMemCopyHelper(), enqueueMemCopyRectHelper(), enqueueMemFillHelper(), enqueueMemImageCommandHelper(), _pi_queue::executeCommandList(), _pi_event::getOrCreateHostVisibleEvent(), piEnqueueEventsWait(), piEnqueueEventsWaitWithBarrier(), piEnqueueKernelLaunch(), piEnqueueMemBufferMap(), piEnqueueMemUnmap(), piextUSMEnqueueMemAdvise(), and piextUSMEnqueuePrefetch().
enqueueMemCopyHelper()
static pi_result enqueueMemCopyHelper (pi_command_type CommandType, pi_queue Queue, void * Dst, pi_bool BlockingWrite, size_t Size, const void * Src, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event, bool PreferCopyEngine = false) static
Definition at line 5776 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_ze_event_list_t::createAndRetainPiZeEventList(), createEventAndAssociateQueue(), _pi_queue::executeCommandList(), _pi_context::getAvailableCommandList(), PI_ASSERT, PI_INVALID_EVENT, PI_INVALID_QUEUE, PI_SUCCESS, printZeEventList(), _pi_queue::useCopyEngine(), and ZE_CALL.
Referenced by piEnqueueMemBufferCopy(), piEnqueueMemBufferRead(), piEnqueueMemBufferWrite(), and piextUSMEnqueueMemcpy().
enqueueMemCopyRectHelper()
static pi_result enqueueMemCopyRectHelper (pi_command_type CommandType, pi_queue Queue, void * SrcBuffer, void * DstBuffer, pi_buff_rect_offset SrcOrigin, pi_buff_rect_offset DstOrigin, pi_buff_rect_region Region, size_t SrcRowPitch, size_t SrcSlicePitch, size_t DstRowPitch, size_t DstSlicePitch, pi_bool Blocking, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event, bool PreferCopyEngine = false) static
Definition at line 5836 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_ze_event_list_t::createAndRetainPiZeEventList(), createEventAndAssociateQueue(), pi_buff_rect_region_struct::depth_scalar, _pi_queue::executeCommandList(), _pi_context::getAvailableCommandList(), pi_buff_rect_region_struct::height_scalar, PI_ASSERT, PI_INVALID_EVENT, PI_INVALID_VALUE, PI_SUCCESS, printZeEventList(), _pi_queue::useCopyEngine(), pi_buff_rect_region_struct::width_bytes, pi_buff_rect_offset_struct::x_bytes, pi_buff_rect_offset_struct::y_scalar, pi_buff_rect_offset_struct::z_scalar, and ZE_CALL.
Referenced by piEnqueueMemBufferCopyRect(), piEnqueueMemBufferReadRect(), and piEnqueueMemBufferWriteRect().
enqueueMemFillHelper()
static pi_result enqueueMemFillHelper (pi_command_type CommandType, pi_queue Queue, void * Ptr, const void * Pattern, size_t PatternSize, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event) static
Definition at line 6025 of file pi_level_zero.cpp.
References _pi_device::queue_group_info_t::Compute, _pi_queue::Context, _pi_ze_event_list_t::createAndRetainPiZeEventList(), createEventAndAssociateQueue(), _pi_queue::Device, _pi_queue::executeCommandList(), _pi_context::getAvailableCommandList(), _pi_device::hasCopyEngine(), _pi_device::hasLinkCopyEngine(), _pi_device::hasMainCopyEngine(), _pi_device::queue_group_info_t::LinkCopy, _pi_device::queue_group_info_t::MainCopy, PI_ASSERT, PI_INVALID_EVENT, PI_INVALID_QUEUE, PI_INVALID_VALUE, PI_SUCCESS, printZeEventList(), _pi_device::QueueGroup, _pi_queue::useCopyEngine(), and ZE_CALL.
Referenced by piEnqueueMemBufferFill(), and piextUSMEnqueueMemset().
enqueueMemImageCommandHelper()
static pi_result enqueueMemImageCommandHelper (pi_command_type CommandType, pi_queue Queue, const void * Src, void * Dst, pi_bool IsBlocking, pi_image_offset SrcOrigin, pi_image_offset DstOrigin, pi_image_region Region, size_t RowPitch, size_t SlicePitch, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event, bool PreferCopyEngine = false) static
Definition at line 6453 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_ze_event_list_t::createAndRetainPiZeEventList(), createEventAndAssociateQueue(), _pi_queue::executeCommandList(), _pi_context::getAvailableCommandList(), getImageRegionHelper(), _pi_mem::getZeHandle(), _pi_mem::isImage(), PI_ASSERT, PI_COMMAND_TYPE_IMAGE_COPY, PI_COMMAND_TYPE_IMAGE_READ, PI_COMMAND_TYPE_IMAGE_WRITE, PI_INVALID_EVENT, PI_INVALID_IMAGE_SIZE, PI_INVALID_MEM_OBJECT, PI_INVALID_OPERATION, PI_INVALID_QUEUE, PI_SUCCESS, _pi_queue::useCopyEngine(), ZE_CALL, and _pi_image::ZeImageDesc.
Referenced by piEnqueueMemImageCopy(), piEnqueueMemImageRead(), and piEnqueueMemImageWrite().
EventCreate()
static pi_result EventCreate (pi_context Context, pi_queue Queue, bool HostVisible, pi_event * RetEvent) static
Definition at line 5002 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_context::getFreeSlotInExistingOrNewPool(), PI_ASSERT, PI_COMMAND_TYPE_USER, PI_ERROR_UNKNOWN, PI_INVALID_VALUE, PI_OUT_OF_HOST_MEMORY, PI_QUEUE_PROFILING_ENABLE, PI_SUCCESS, _pi_queue::Properties, and ZE_CALL.
Referenced by createEventAndAssociateQueue(), and piEventCreate().
EventRelease()
static pi_result EventRelease (pi_event Event, pi_queue LockedQueue) static
Definition at line 5372 of file pi_level_zero.cpp.
References _pi_event::CleanedUp, _pi_event::cleanup(), _pi_event::CommandData, _pi_event::CommandType, _pi_queue::Context, _pi_event::Context, _pi_context::decrementUnreleasedEventsInPool(), cl::sycl::detail::pi::die(), _pi_event::HostVisibleEvent, _pi_event::OwnZeEvent, PI_ASSERT, PI_CALL, PI_COMMAND_TYPE_MEM_BUFFER_UNMAP, PI_INVALID_EVENT, PI_SUCCESS, _pi_event::Queue, QueueRelease(), ZE_CALL, _pi_event::ZeEvent, and ZeMemFreeHelper().
Referenced by _pi_event::cleanup(), piEventRelease(), and _pi_queue::resetCommandList().
getImageRegionHelper()
static pi_result getImageRegionHelper (pi_mem Mem, pi_image_offset Origin, pi_image_region Region, ze_image_region_t & ZeRegion) static
Definition at line 6408 of file pi_level_zero.cpp.
References pi_image_region_struct::depth, pi_image_region_struct::height, _pi_mem::isImage(), PI_ASSERT, PI_INVALID_MEM_OBJECT, PI_INVALID_VALUE, PI_SUCCESS, pi_image_region_struct::width, pi_image_offset_struct::x, pi_image_offset_struct::y, pi_image_offset_struct::z, and _pi_image::ZeImageDesc.
Referenced by enqueueMemImageCommandHelper().
is_in_separated_string()
static bool is_in_separated_string (const std::string & str, char delimiter, const std::string & sub_str) static
Definition at line 6750 of file pi_level_zero.cpp.
References cl::sycl::length().
Referenced by piextGetDeviceFunctionPointer().
IsDevicePointer()
static bool IsDevicePointer (pi_context Context, const void * Ptr) static
Definition at line 7367 of file pi_level_zero.cpp.
References _pi_queue::Context, ZE_CALL, and _pi_context::ZeContext.
Referenced by piextUSMEnqueueMemcpy().
piclProgramCreateWithSource()
pi_result piclProgramCreateWithSource (pi_context Context, pi_uint32 Count, const char ** Strings, const size_t * Lengths, pi_program * RetProgram)
Definition at line 3909 of file pi_level_zero.cpp.
References _pi_queue::Context, and PI_INVALID_OPERATION.
piContextCreate()
pi_result piContextCreate (const pi_context_properties * Properties, pi_uint32 NumDevices, const pi_device * Devices, void(*)(const char *ErrInfo, const void *PrivateInfo, size_t CB, void *UserData) PFnNotify, void * UserData, pi_context * RetContext)
Definition at line 2899 of file pi_level_zero.cpp.
References _pi_platform::Contexts, _pi_platform::ContextsMutex, PI_ASSERT, PI_ERROR_UNKNOWN, PI_INVALID_DEVICE, PI_INVALID_VALUE, PI_OUT_OF_HOST_MEMORY, PI_SUCCESS, _pi_queue::Properties, ZE_CALL, and _pi_platform::ZeDriver.
piContextGetInfo()
pi_result piContextGetInfo (pi_context Context, pi_context_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 2934 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_context::Devices, cl::sycl::detail::pi::die(), PI_ASSERT, PI_CONTEXT_INFO_ATOMIC_MEMORY_SCOPE_CAPABILITIES, PI_CONTEXT_INFO_DEVICES, PI_CONTEXT_INFO_NUM_DEVICES, PI_CONTEXT_INFO_REFERENCE_COUNT, PI_INVALID_CONTEXT, and PI_SUCCESS.
Referenced by cl::sycl::detail::context_impl::context_impl(), cl::sycl::detail::context_impl::get_info< info::context::atomic_memory_order_capabilities >(), cl::sycl::detail::context_impl::get_info< info::context::atomic_memory_scope_capabilities >(), cl::sycl::detail::createBinaryProgram(), cl::sycl::detail::get_context_info< param >::get(), cl::sycl::detail::get_context_info< info::context::atomic_memory_order_capabilities >::get(), and piPluginInit().
piContextRelease()
pi_result piContextRelease (pi_context Context)
TODO : Encapsulating accesses (add/remove) for Addr2CmBufferSVM
Definition at line 3049 of file pi_level_zero.cpp.
References _pi_queue::Context, ContextReleaseHelper(), _pi_platform::ContextsMutex, and _pi_context::Devices.
Referenced by piKernelRelease(), piPluginInit(), and cl::sycl::detail::context_impl::~context_impl().
piContextRetain()
pi_result piContextRetain (pi_context Context)
Definition at line 3003 of file pi_level_zero.cpp.
References _pi_queue::Context, PI_ASSERT, PI_INVALID_CONTEXT, and PI_SUCCESS.
Referenced by cl::sycl::detail::context_impl::context_impl(), cl::sycl::detail::context_impl::get(), cl::sycl::detail::context_impl::getNative(), piextKernelCreateWithNativeHandle(), piextUSMDeviceAlloc(), piextUSMHostAlloc(), piextUSMSharedAlloc(), piKernelCreate(), piPluginInit(), ZeDeviceMemAllocHelper(), and ZeHostMemAllocHelper().
piDeviceGetInfo()
pi_result piDeviceGetInfo (pi_device Device, pi_device_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Returns requested info for provided native device Return PI_DEVICE_INFO_EXTENSION_DEVICELIB_ASSERT for PI_DEVICE_INFO_EXTENSIONS query when the device supports native asserts.
Combination of ESIMDEmuPluginDataVersion and ESIMDEmuPluginInterfaceVersion : 0.a.b a : ESIMDEmuPluginInterfaceVersion b : ESIMDEmuPluginDataVersion
TODO : Check
TODO : Check. CM_MAX_1D_SURF_WIDTH from CM_EMU
TODO : Check
TODO : Check. CM_MAX_SAMPLERS_PER_KERNEL from CM_EMU
TODO : Check
TODO : Check. half_type.hpp from CM_EMU
Definition at line 2241 of file pi_level_zero.cpp.
References _pi_queue::Device, cl::sycl::detail::pi::die(), _pi_device::isSubDevice(), PI_ASSERT, PI_DEVICE_AFFINITY_DOMAIN_NEXT_PARTITIONABLE, PI_DEVICE_AFFINITY_DOMAIN_NUMA, PI_DEVICE_EXEC_CAPABILITIES_NATIVE_KERNEL, PI_DEVICE_INFO_ADDRESS_BITS, PI_DEVICE_INFO_ATOMIC_64, PI_DEVICE_INFO_ATOMIC_MEMORY_SCOPE_CAPABILITIES, PI_DEVICE_INFO_AVAILABLE, PI_DEVICE_INFO_BUILD_ON_SUBDEVICE, PI_DEVICE_INFO_BUILT_IN_KERNELS, PI_DEVICE_INFO_COMPILER_AVAILABLE, PI_DEVICE_INFO_DOUBLE_FP_CONFIG, PI_DEVICE_INFO_DRIVER_VERSION, PI_DEVICE_INFO_ENDIAN_LITTLE, PI_DEVICE_INFO_ERROR_CORRECTION_SUPPORT, PI_DEVICE_INFO_EXECUTION_CAPABILITIES, PI_DEVICE_INFO_EXTENSIONS, PI_DEVICE_INFO_GLOBAL_MEM_CACHE_SIZE, PI_DEVICE_INFO_GLOBAL_MEM_CACHE_TYPE, PI_DEVICE_INFO_GLOBAL_MEM_CACHELINE_SIZE, PI_DEVICE_INFO_GLOBAL_MEM_SIZE, PI_DEVICE_INFO_GPU_EU_COUNT, PI_DEVICE_INFO_GPU_EU_COUNT_PER_SUBSLICE, PI_DEVICE_INFO_GPU_EU_SIMD_WIDTH, PI_DEVICE_INFO_GPU_HW_THREADS_PER_EU, PI_DEVICE_INFO_GPU_SLICES, PI_DEVICE_INFO_GPU_SUBSLICES_PER_SLICE, PI_DEVICE_INFO_HALF_FP_CONFIG, PI_DEVICE_INFO_HOST_UNIFIED_MEMORY, PI_DEVICE_INFO_IL_VERSION, PI_DEVICE_INFO_IMAGE2D_MAX_HEIGHT, PI_DEVICE_INFO_IMAGE2D_MAX_WIDTH, PI_DEVICE_INFO_IMAGE3D_MAX_DEPTH, PI_DEVICE_INFO_IMAGE3D_MAX_HEIGHT, PI_DEVICE_INFO_IMAGE3D_MAX_WIDTH, PI_DEVICE_INFO_IMAGE_MAX_ARRAY_SIZE, PI_DEVICE_INFO_IMAGE_MAX_BUFFER_SIZE, PI_DEVICE_INFO_IMAGE_SUPPORT, PI_DEVICE_INFO_LINKER_AVAILABLE, PI_DEVICE_INFO_LOCAL_MEM_SIZE, PI_DEVICE_INFO_LOCAL_MEM_TYPE, PI_DEVICE_INFO_MAX_CLOCK_FREQUENCY, PI_DEVICE_INFO_MAX_COMPUTE_UNITS, PI_DEVICE_INFO_MAX_CONSTANT_ARGS, PI_DEVICE_INFO_MAX_CONSTANT_BUFFER_SIZE, PI_DEVICE_INFO_MAX_MEM_ALLOC_SIZE, PI_DEVICE_INFO_MAX_MEM_BANDWIDTH, PI_DEVICE_INFO_MAX_NUM_SUB_GROUPS, PI_DEVICE_INFO_MAX_PARAMETER_SIZE, PI_DEVICE_INFO_MAX_READ_IMAGE_ARGS, PI_DEVICE_INFO_MAX_SAMPLERS, PI_DEVICE_INFO_MAX_WORK_GROUP_SIZE, PI_DEVICE_INFO_MAX_WORK_ITEM_DIMENSIONS, PI_DEVICE_INFO_MAX_WORK_ITEM_SIZES, PI_DEVICE_INFO_MAX_WRITE_IMAGE_ARGS, PI_DEVICE_INFO_MEM_BASE_ADDR_ALIGN, PI_DEVICE_INFO_NAME, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_CHAR, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_DOUBLE, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_FLOAT, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_HALF, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_INT, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_LONG, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_SHORT, PI_DEVICE_INFO_OPENCL_C_VERSION, PI_DEVICE_INFO_PARENT_DEVICE, PI_DEVICE_INFO_PARTITION_AFFINITY_DOMAIN, PI_DEVICE_INFO_PARTITION_MAX_SUB_DEVICES, PI_DEVICE_INFO_PARTITION_PROPERTIES, PI_DEVICE_INFO_PARTITION_TYPE, PI_DEVICE_INFO_PCI_ADDRESS, PI_DEVICE_INFO_PLATFORM, PI_DEVICE_INFO_PREFERRED_INTEROP_USER_SYNC, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_CHAR, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_DOUBLE, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_FLOAT, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_HALF, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_INT, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_LONG, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_SHORT, PI_DEVICE_INFO_PRINTF_BUFFER_SIZE, PI_DEVICE_INFO_PROFILE, PI_DEVICE_INFO_PROFILING_TIMER_RESOLUTION, PI_DEVICE_INFO_QUEUE_PROPERTIES, PI_DEVICE_INFO_REFERENCE_COUNT, PI_DEVICE_INFO_SINGLE_FP_CONFIG, PI_DEVICE_INFO_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS, PI_DEVICE_INFO_SUB_GROUP_SIZES_INTEL, PI_DEVICE_INFO_TYPE, PI_DEVICE_INFO_USM_CROSS_SHARED_SUPPORT, PI_DEVICE_INFO_USM_DEVICE_SUPPORT, PI_DEVICE_INFO_USM_HOST_SUPPORT, PI_DEVICE_INFO_USM_SINGLE_SHARED_SUPPORT, PI_DEVICE_INFO_USM_SYSTEM_SHARED_SUPPORT, PI_DEVICE_INFO_UUID, PI_DEVICE_INFO_VENDOR, PI_DEVICE_INFO_VENDOR_ID, PI_DEVICE_INFO_VERSION, PI_DEVICE_LOCAL_MEM_TYPE_LOCAL, PI_DEVICE_MEM_CACHE_TYPE_READ_WRITE_CACHE, PI_DEVICE_PARTITION_BY_AFFINITY_DOMAIN, PI_DEVICE_TYPE_ACC, PI_DEVICE_TYPE_CPU, PI_DEVICE_TYPE_GPU, PI_EXT_ONEAPI_DEVICE_INFO_MAX_WORK_GROUPS_3D, PI_FALSE, PI_FP_CORRECTLY_ROUNDED_DIVIDE_SQRT, PI_FP_DENORM, PI_FP_FMA, PI_FP_INF_NAN, PI_FP_ROUND_TO_INF, PI_FP_ROUND_TO_NEAREST, PI_FP_ROUND_TO_ZERO, PI_INVALID_DEVICE, PI_INVALID_VALUE, PI_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE, PI_QUEUE_PROFILING_ENABLE, PI_SUCCESS, PI_USM_ACCESS, PI_USM_ATOMIC_ACCESS, PI_USM_CONCURRENT_ACCESS, PI_USM_CONCURRENT_ATOMIC_ACCESS, _pi_device::Platform, _pi_platform::populateDeviceCacheIfNeeded(), _pi_device::RootDevice, _pi_device::SubDevices, cl::sycl::detail::totalSize(), ZE_CALL, ZE_SUPPORTED_EXTENSIONS, _pi_device::ZeDevice, _pi_device::ZeDeviceCacheProperties, _pi_device::ZeDeviceComputeProperties, _pi_device::ZeDeviceImageProperties, _pi_device::ZeDeviceMemoryAccessProperties, _pi_device::ZeDeviceMemoryProperties, _pi_device::ZeDeviceModuleProperties, _pi_device::ZeDeviceProperties, _pi_platform::ZeDriverApiVersion, and _pi_platform::ZeDriverVersion.
piDevicePartition()
pi_result piDevicePartition (pi_device Device, const pi_device_partition_property * Properties, pi_uint32 NumDevices, pi_device * OutDevices, pi_uint32 * OutNumDevices)
Definition at line 2764 of file pi_level_zero.cpp.
References _pi_queue::Device, PI_ASSERT, PI_CALL, PI_DEVICE_AFFINITY_DOMAIN_NEXT_PARTITIONABLE, PI_DEVICE_AFFINITY_DOMAIN_NUMA, PI_DEVICE_PARTITION_BY_AFFINITY_DOMAIN, PI_INVALID_DEVICE, PI_INVALID_VALUE, PI_SUCCESS, piDeviceRetain(), _pi_device::Platform, _pi_platform::populateDeviceCacheIfNeeded(), _pi_queue::Properties, and _pi_device::SubDevices.
Referenced by cl::sycl::detail::device_impl::create_sub_devices(), and piPluginInit().
piDeviceRelease()
pi_result piDeviceRelease (pi_device Device)
Definition at line 2224 of file pi_level_zero.cpp.
References _pi_queue::Device, cl::sycl::detail::pi::die(), _pi_device::isSubDevice(), PI_ASSERT, PI_INVALID_DEVICE, and PI_SUCCESS.
Referenced by piPluginInit(), and cl::sycl::detail::device_impl::~device_impl().
piDeviceRetain()
pi_result piDeviceRetain (pi_device Device)
Definition at line 2214 of file pi_level_zero.cpp.
References _pi_queue::Device, _pi_device::isSubDevice(), PI_ASSERT, PI_INVALID_DEVICE, and PI_SUCCESS.
Referenced by cl::sycl::detail::device_impl::get(), cl::sycl::detail::device_impl::getNative(), piDevicePartition(), and piPluginInit().
piDevicesGet()
pi_result piDevicesGet (pi_platform Platform, pi_device_type DeviceType, pi_uint32 NumEntries, pi_device * Devices, pi_uint32 * NumDevices)
Runtime queries number of devices
No GPU entry to fill 'Devices' array
Definition at line 2040 of file pi_level_zero.cpp.
References PI_ASSERT, PI_DEVICE_TYPE_ACC, PI_DEVICE_TYPE_ALL, PI_DEVICE_TYPE_CPU, PI_DEVICE_TYPE_DEFAULT, PI_DEVICE_TYPE_GPU, PI_INVALID_DEVICE, PI_INVALID_PLATFORM, PI_INVALID_VALUE, PI_SUCCESS, _pi_platform::PiDevicesCache, and _pi_platform::populateDeviceCacheIfNeeded().
piEnqueueEventsWait()
pi_result piEnqueueEventsWait (pi_queue Queue, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 5619 of file pi_level_zero.cpp.
References _pi_queue::CommandListMap, _pi_queue::ComputeQueueGroup, _pi_queue::Context, _pi_queue::CopyQueueGroup, _pi_ze_event_list_t::createAndRetainPiZeEventList(), createEventAndAssociateQueue(), _pi_queue::executeCommandList(), _pi_context::getAvailableCommandList(), _pi_queue::LastCommandEvent, PI_ASSERT, PI_COMMAND_TYPE_USER, PI_INVALID_EVENT, PI_INVALID_QUEUE, PI_INVALID_VALUE, PI_SUCCESS, ZE_CALL, and _pi_queue::pi_queue_group_t::ZeQueues.
Referenced by cl::sycl::detail::MemoryManager::copy_usm(), cl::sycl::detail::MemoryManager::fill_usm(), piPluginInit(), and cl::sycl::detail::Command::waitForEvents().
piEnqueueEventsWaitWithBarrier()
pi_result piEnqueueEventsWaitWithBarrier (pi_queue Queue, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 5690 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_ze_event_list_t::createAndRetainPiZeEventList(), createEventAndAssociateQueue(), _pi_queue::executeCommandList(), _pi_context::getAvailableCommandList(), PI_ASSERT, PI_COMMAND_TYPE_USER, PI_INVALID_EVENT, PI_INVALID_QUEUE, PI_SUCCESS, and ZE_CALL.
Referenced by piPluginInit().
piEnqueueKernelLaunch()
pi_result piEnqueueKernelLaunch (pi_queue Queue, pi_kernel Kernel, pi_uint32 WorkDim, const size_t * GlobalWorkOffset, const size_t * GlobalWorkSize, const size_t * LocalWorkSize, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 4770 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_ze_event_list_t::createAndRetainPiZeEventList(), createEventAndAssociateQueue(), _pi_queue::executeCommandList(), _pi_context::getAvailableCommandList(), _pi_queue::KernelsToBeSubmitted, PI_ASSERT, PI_CALL, PI_COMMAND_TYPE_NDRANGE_KERNEL, PI_INVALID_EVENT, PI_INVALID_KERNEL, PI_INVALID_QUEUE, PI_INVALID_VALUE, PI_INVALID_WORK_DIMENSION, PI_INVALID_WORK_GROUP_SIZE, PI_SUCCESS, PiDriverGlobalOffsetExtensionFound, piKernelRetain(), printZeEventList(), ZE_CALL, and _pi_kernel::ZeKernel.
Referenced by piPluginInit(), and cl::sycl::detail::SetKernelParamsAndLaunch().
piEnqueueMemBufferCopy()
pi_result piEnqueueMemBufferCopy (pi_queue Queue, pi_mem SrcBuffer, pi_mem DstBuffer, size_t SrcOffset, size_t DstOffset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 5971 of file pi_level_zero.cpp.
References enqueueMemCopyHelper(), _pi_mem::getZeHandle(), _pi_mem::OnHost, PI_ASSERT, PI_COMMAND_TYPE_MEM_BUFFER_COPY, PI_INVALID_MEM_OBJECT, and PI_INVALID_QUEUE.
Referenced by cl::sycl::detail::copyD2D(), and piPluginInit().
piEnqueueMemBufferCopyRect()
pi_result piEnqueueMemBufferCopyRect (pi_queue Queue, pi_mem SrcBuffer, pi_mem DstBuffer, pi_buff_rect_offset SrcOrigin, pi_buff_rect_offset DstOrigin, pi_buff_rect_region Region, size_t SrcRowPitch, size_t SrcSlicePitch, size_t DstRowPitch, size_t DstSlicePitch, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 5998 of file pi_level_zero.cpp.
References enqueueMemCopyRectHelper(), _pi_mem::getZeHandle(), _pi_mem::OnHost, PI_ASSERT, PI_COMMAND_TYPE_MEM_BUFFER_COPY_RECT, PI_INVALID_MEM_OBJECT, and PI_INVALID_QUEUE.
Referenced by cl::sycl::detail::copyD2D(), and piPluginInit().
piEnqueueMemBufferFill()
pi_result piEnqueueMemBufferFill (pi_queue Queue, pi_mem Buffer, const void * Pattern, size_t PatternSize, size_t Offset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 6114 of file pi_level_zero.cpp.
References enqueueMemFillHelper(), _pi_mem::getZeHandle(), PI_ASSERT, PI_COMMAND_TYPE_MEM_BUFFER_FILL, PI_INVALID_MEM_OBJECT, and PI_INVALID_QUEUE.
Referenced by cl::sycl::detail::MemoryManager::fill(), and piPluginInit().
piEnqueueMemBufferMap()
pi_result piEnqueueMemBufferMap (pi_queue Queue, pi_mem Buffer, pi_bool BlockingMap, pi_map_flags MapFlags, size_t Offset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event, void ** RetMap)
Definition at line 6135 of file pi_level_zero.cpp.
References _pi_queue::CommandListMap, _pi_queue::Context, _pi_ze_event_list_t::createAndRetainPiZeEventList(), createEventAndAssociateQueue(), _pi_queue::executeCommandList(), _pi_context::getAvailableCommandList(), _pi_mem::getZeHandle(), _pi_mem::HostPtrImported, _pi_queue::isInOrderQueue(), _pi_queue::LastCommandEvent, _pi_mem::MapHostPtr, _pi_mem::Mappings, cl::sycl::detail::memcpy(), _pi_mem::OnHost, PI_ASSERT, PI_CALL, PI_COMMAND_TYPE_MEM_BUFFER_MAP, PI_INVALID_EVENT, PI_INVALID_MEM_OBJECT, PI_INVALID_QUEUE, PI_INVALID_VALUE, PI_MAP_WRITE_INVALIDATE_REGION, PI_SUCCESS, piEventRetain(), piEventsWait(), ZE_CALL, and ZeHostMemAllocHelper().
piEnqueueMemBufferRead()
pi_result piEnqueueMemBufferRead (pi_queue Queue, pi_mem Src, pi_bool BlockingRead, size_t Offset, size_t Size, void * Dst, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
TODO : Support Blocked read, 'Queue' handling
Definition at line 5729 of file pi_level_zero.cpp.
References enqueueMemCopyHelper(), _pi_mem::getZeHandle(), PI_ASSERT, PI_COMMAND_TYPE_MEM_BUFFER_READ, PI_INVALID_MEM_OBJECT, and PI_INVALID_QUEUE.
Referenced by cl::sycl::detail::copyD2H(), and piPluginInit().
piEnqueueMemBufferReadRect()
pi_result piEnqueueMemBufferReadRect (pi_queue Queue, pi_mem Buffer, pi_bool BlockingRead, pi_buff_rect_offset BufferOffset, pi_buff_rect_offset HostOffset, pi_buff_rect_region Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, void * Ptr, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 5746 of file pi_level_zero.cpp.
References enqueueMemCopyRectHelper(), _pi_mem::getZeHandle(), PI_ASSERT, PI_COMMAND_TYPE_MEM_BUFFER_READ_RECT, PI_INVALID_MEM_OBJECT, and PI_INVALID_QUEUE.
Referenced by cl::sycl::detail::copyD2H(), and piPluginInit().
piEnqueueMemBufferWrite()
pi_result piEnqueueMemBufferWrite (pi_queue Queue, pi_mem Buffer, pi_bool BlockingWrite, size_t Offset, size_t Size, const void * Ptr, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 5932 of file pi_level_zero.cpp.
References enqueueMemCopyHelper(), _pi_mem::getZeHandle(), PI_ASSERT, PI_COMMAND_TYPE_MEM_BUFFER_WRITE, PI_INVALID_MEM_OBJECT, and PI_INVALID_QUEUE.
Referenced by cl::sycl::detail::copyH2D(), and piPluginInit().
piEnqueueMemBufferWriteRect()
pi_result piEnqueueMemBufferWriteRect (pi_queue Queue, pi_mem Buffer, pi_bool BlockingWrite, pi_buff_rect_offset BufferOffset, pi_buff_rect_offset HostOffset, pi_buff_rect_region Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, const void * Ptr, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 5951 of file pi_level_zero.cpp.
References enqueueMemCopyRectHelper(), _pi_mem::getZeHandle(), PI_ASSERT, PI_COMMAND_TYPE_MEM_BUFFER_WRITE_RECT, PI_INVALID_MEM_OBJECT, and PI_INVALID_QUEUE.
Referenced by cl::sycl::detail::copyH2D(), and piPluginInit().
piEnqueueMemImageCopy()
pi_result piEnqueueMemImageCopy (pi_queue Queue, pi_mem SrcImage, pi_mem DstImage, pi_image_offset SrcOrigin, pi_image_offset DstOrigin, pi_image_region Region, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 6634 of file pi_level_zero.cpp.
References enqueueMemImageCommandHelper(), _pi_mem::OnHost, PI_ASSERT, PI_COMMAND_TYPE_IMAGE_COPY, and PI_INVALID_QUEUE.
Referenced by cl::sycl::detail::copyD2D(), and piPluginInit().
piEnqueueMemImageFill()
pi_result piEnqueueMemImageFill (pi_queue Queue, pi_mem Image, const void * FillColor, const size_t * Origin, const size_t * Region, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 6655 of file pi_level_zero.cpp.
References cl::sycl::detail::pi::die(), PI_ASSERT, and PI_INVALID_QUEUE.
Referenced by cl::sycl::detail::MemoryManager::fill(), and piPluginInit().
piEnqueueMemImageRead()
pi_result piEnqueueMemImageRead (pi_queue Queue, pi_mem Image, pi_bool BlockingRead, pi_image_offset Origin, pi_image_region Region, size_t RowPitch, size_t SlicePitch, void * Ptr, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
TODO : Support Blocked read, 'Queue' handling
Definition at line 6590 of file pi_level_zero.cpp.
References enqueueMemImageCommandHelper(), PI_ASSERT, PI_COMMAND_TYPE_IMAGE_READ, and PI_INVALID_QUEUE.
Referenced by piPluginInit().
piEnqueueMemImageWrite()
pi_result piEnqueueMemImageWrite (pi_queue Queue, pi_mem Image, pi_bool BlockingWrite, pi_image_offset Origin, pi_image_region Region, size_t InputRowPitch, size_t InputSlicePitch, const void * Ptr, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 6611 of file pi_level_zero.cpp.
References enqueueMemImageCommandHelper(), PI_ASSERT, PI_COMMAND_TYPE_IMAGE_WRITE, and PI_INVALID_QUEUE.
Referenced by piPluginInit().
piEnqueueMemUnmap()
pi_result piEnqueueMemUnmap (pi_queue Queue, pi_mem MemObj, void * MappedPtr, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 6272 of file pi_level_zero.cpp.
References _pi_queue::CommandListMap, _pi_queue::Context, _pi_ze_event_list_t::createAndRetainPiZeEventList(), createEventAndAssociateQueue(), _pi_queue::executeCommandList(), _pi_context::getAvailableCommandList(), _pi_mem::getZeHandle(), _pi_queue::isInOrderQueue(), _pi_queue::LastCommandEvent, _pi_mem::MapHostPtr, _pi_mem::Mappings, cl::sycl::detail::memcpy(), _pi_mem::Mapping::Offset, _pi_mem::OnHost, PI_ASSERT, PI_CALL, PI_COMMAND_TYPE_MEM_BUFFER_UNMAP, PI_INVALID_EVENT, PI_INVALID_QUEUE, PI_INVALID_VALUE, PI_SUCCESS, piEventRetain(), piEventsWait(), _pi_mem::Mapping::Size, and ZE_CALL.
Referenced by cl::sycl::detail::memUnmapHelper(), and piPluginInit().
piEnqueueNativeKernel()
pi_result piEnqueueNativeKernel (pi_queue Queue, void(*)(void *) UserFunc, void * Args, size_t CbArgs, pi_uint32 NumMemObjects, const pi_mem * MemList, const void ** ArgsMemLoc, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 6720 of file pi_level_zero.cpp.
References cl::sycl::detail::pi::die(), PI_ASSERT, and PI_INVALID_QUEUE.
Referenced by piPluginInit().
piEventCreate()
pi_result piEventCreate (pi_context Context, pi_event * RetEvent)
Definition at line 5053 of file pi_level_zero.cpp.
References _pi_queue::Context, and EventCreate().
piEventGetInfo()
pi_result piEventGetInfo (pi_event Event, pi_event_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 5057 of file pi_level_zero.cpp.
References _pi_event::CommandType, _pi_event::Completed, _pi_event::Context, _pi_queue::executeOpenCommandListWithEvent(), _pi_event::HostVisibleEvent, PI_ASSERT, PI_EVENT_INFO_COMMAND_EXECUTION_STATUS, PI_EVENT_INFO_COMMAND_QUEUE, PI_EVENT_INFO_COMMAND_TYPE, PI_EVENT_INFO_CONTEXT, PI_EVENT_INFO_REFERENCE_COUNT, PI_INVALID_EVENT, PI_INVALID_VALUE, PI_SUCCESS, _pi_event::Queue, and ZE_CALL_NOCHECK.
Referenced by cl::sycl::detail::event_impl::event_impl(), cl::sycl::detail::event_impl::flushIfNeeded(), cl::sycl::detail::get_event_info< Param >::get(), and piPluginInit().
piEventGetProfilingInfo()
pi_result piEventGetProfilingInfo (pi_event Event, pi_profiling_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 5115 of file pi_level_zero.cpp.
References _pi_event::Context, _pi_queue::Device, _pi_context::Devices, PI_ASSERT, PI_INVALID_EVENT, PI_INVALID_VALUE, PI_PROFILING_INFO_COMMAND_END, PI_PROFILING_INFO_COMMAND_QUEUED, PI_PROFILING_INFO_COMMAND_START, PI_PROFILING_INFO_COMMAND_SUBMIT, PI_PROFILING_INFO_NOT_AVAILABLE, PI_QUEUE_PROFILING_ENABLE, PI_SUCCESS, _pi_queue::Properties, _pi_event::Queue, ZE_CALL, _pi_device::ZeDeviceProperties, and _pi_event::ZeEvent.
Referenced by cl::sycl::detail::get_event_profiling_info< Param >::get(), and piPluginInit().
piEventRelease()
pi_result piEventRelease (pi_event Event)
Definition at line 5368 of file pi_level_zero.cpp.
References EventRelease().
Referenced by _pi_queue::executeCommandList(), piPluginInit(), and cl::sycl::detail::event_impl::~event_impl().
piEventRetain()
pi_result piEventRetain (pi_event Event)
Definition at line 5363 of file pi_level_zero.cpp.
References PI_SUCCESS.
Referenced by cl::sycl::detail::MemoryManager::allocateInteropMemObject(), _pi_ze_event_list_t::createAndRetainPiZeEventList(), createEventAndAssociateQueue(), cl::sycl::detail::event_impl::event_impl(), _pi_queue::executeCommandList(), cl::sycl::detail::event_impl::get(), cl::sycl::detail::event_impl::getNative(), piEnqueueMemBufferMap(), piEnqueueMemUnmap(), and piPluginInit().
piEventSetCallback()
pi_result piEventSetCallback (pi_event Event, pi_int32 CommandExecCallbackType, void(*)(pi_event Event, pi_int32 EventCommandStatus, void *UserData) PFnNotify, void * UserData)
Definition at line 5343 of file pi_level_zero.cpp.
References cl::sycl::detail::pi::die(), and PI_SUCCESS.
piEventSetStatus()
pi_result piEventSetStatus (pi_event Event, pi_int32 ExecutionStatus)
Definition at line 5356 of file pi_level_zero.cpp.
References cl::sycl::detail::pi::die(), and PI_SUCCESS.
Referenced by piPluginInit().
piEventsWait()
pi_result piEventsWait (pi_uint32 NumEvents, const pi_event * EventList)
Definition at line 5296 of file pi_level_zero.cpp.
References _pi_event::cleanup(), cl::sycl::detail::pi::die(), _pi_event::HostVisibleEvent, PI_INVALID_EVENT, PI_SUCCESS, _pi_event::Queue, and ZE_CALL.
Referenced by cl::sycl::detail::memUnmapHelper(), piEnqueueMemBufferMap(), piEnqueueMemUnmap(), piPluginInit(), cl::sycl::detail::waitForEvents(), cl::sycl::detail::Command::waitForEvents(), and cl::sycl::detail::event_impl::waitInternal().
piextContextCreateWithNativeHandle()
pi_result piextContextCreateWithNativeHandle (pi_native_handle nativeHandle, pi_uint32 numDevices, const pi_device * devices, bool pluginOwnsNativeHandle, pi_context * context)
Creates PI context object from a native handle.
NOTE: The created PI object takes ownership of the native handle. NOTE: The number of devices and the list of devices is needed for Level Zero backend because there is no possilibity to query this information from context handle for Level Zero. If backend has API to query a list of devices from the context native handle then these parameters are ignored.
Parameters
nativeHandle is the native handle to create PI context from.
numDevices is the number of devices in the context. Parameter is ignored if number of devices can be queried from the context native handle for a backend.
devices is the list of devices in the context. Parameter is ignored if devices can be queried from the context native handle for a backend.
pluginOwnsNativeHandle Indicates whether the created PI object should take ownership of the native handle.
context is the PI context created from the native handle.
Returns
PI_SUCCESS if successfully created pi_context from the handle. PI_OUT_OF_HOST_MEMORY if can't allocate memory for the pi_context object. PI_INVALID_VALUE if numDevices == 0 or devices is NULL but backend doesn't have API to query a list of devices from the context native handle. PI_UNKNOWN_ERROR in case of another error.
Definition at line 2980 of file pi_level_zero.cpp.
References PI_ASSERT, PI_ERROR_UNKNOWN, PI_INVALID_DEVICE, PI_INVALID_VALUE, PI_OUT_OF_HOST_MEMORY, and PI_SUCCESS.
piextContextGetNativeHandle()
pi_result piextContextGetNativeHandle (pi_context context, pi_native_handle * nativeHandle)
Gets the native handle of a PI context object.
Parameters
context is the PI context to get the native handle of.
nativeHandle is the native handle of context.
Definition at line 2969 of file pi_level_zero.cpp.
References _pi_queue::Context, PI_ASSERT, PI_INVALID_CONTEXT, PI_INVALID_VALUE, PI_SUCCESS, and _pi_context::ZeContext.
piextContextSetExtendedDeleter()
pi_result piextContextSetExtendedDeleter (pi_context Context, pi_context_extended_deleter Function, void * UserData)
Definition at line 2959 of file pi_level_zero.cpp.
References _pi_queue::Context, cl::sycl::detail::pi::die(), and PI_SUCCESS.
Referenced by cl::sycl::detail::pi::contextSetExtendedDeleter(), and piPluginInit().
piextDeviceCreateWithNativeHandle()
pi_result piextDeviceCreateWithNativeHandle (pi_native_handle nativeHandle, pi_platform platform, pi_device * device)
Creates PI device object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI device from.
platform is the platform of the device (optional).
device is the PI device created from the native handle.
Definition at line 2863 of file pi_level_zero.cpp.
References _pi_queue::Device, PI_ASSERT, PI_INVALID_DEVICE, PI_INVALID_PLATFORM, PI_INVALID_VALUE, PI_SUCCESS, PiPlatformCachePopulated, PiPlatformsCache, and PiPlatformsCacheMutex.
piextDeviceGetNativeHandle()
pi_result piextDeviceGetNativeHandle (pi_device device, pi_native_handle * nativeHandle)
Gets the native handle of a PI device object.
Parameters
device is the PI device to get the native handle of.
nativeHandle is the native handle of device.
Definition at line 2852 of file pi_level_zero.cpp.
References _pi_queue::Device, PI_ASSERT, PI_INVALID_DEVICE, PI_INVALID_VALUE, PI_SUCCESS, and _pi_device::ZeDevice.
piextDeviceSelectBinary()
pi_result piextDeviceSelectBinary (pi_device Device, pi_device_binary * Binaries, pi_uint32 NumBinaries, pi_uint32 * SelectedBinaryInd)
Selects the most appropriate device binary based on runtime information and the IR characteristics.
TODO : Support multiple images and enable selection algorithm for the images
Definition at line 2806 of file pi_level_zero.cpp.
References __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64, __SYCL_PI_DEVICE_BINARY_TARGET_SPIRV64_GEN, _pi_queue::Device, max(), PI_ASSERT, PI_INVALID_BINARY, PI_INVALID_DEVICE, PI_INVALID_VALUE, and PI_SUCCESS.
piextEventCreateWithNativeHandle()
pi_result piextEventCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, bool ownNativeHandle, pi_event * event)
Creates PI event object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI event from.
context is the corresponding PI context
pluginOwnsNativeHandle Indicates whether the created PI object should take ownership of the native handle.
event is the PI event created from the native handle.
Definition at line 5434 of file pi_level_zero.cpp.
References _pi_queue::Context, PI_ASSERT, PI_COMMAND_TYPE_USER, PI_INVALID_CONTEXT, PI_INVALID_EVENT, PI_INVALID_VALUE, and PI_SUCCESS.
piextEventGetNativeHandle()
pi_result piextEventGetNativeHandle (pi_event event, pi_native_handle * nativeHandle)
Gets the native handle of a PI event object.
Parameters
event is the PI event to get the native handle of.
nativeHandle is the native handle of event.
Definition at line 5416 of file pi_level_zero.cpp.
References _pi_queue::executeOpenCommandListWithEvent(), PI_ASSERT, PI_INVALID_EVENT, PI_INVALID_VALUE, PI_SUCCESS, _pi_event::Queue, and _pi_event::ZeEvent.
Referenced by cl::sycl::detail::event_impl::getNative(), and piPluginInit().
piextGetDeviceFunctionPointer()
pi_result piextGetDeviceFunctionPointer (pi_device device, pi_program program, const char * function_name, pi_uint64 * function_pointer_ret)
Retrieves a device function pointer to a user-defined function.
function_name.
function_pointer_ret is set to 0 if query failed.
program must be built before calling this API.
device must present in the list of devices returned by get_device method for
program.
If a fallback method determines the function exists but the address is not available PI_FUNCTION_ADDRESS_IS_NOT_AVAILABLE is returned. If the address does not exist PI_INVALID_KERNEL_NAME is returned.
Definition at line 6773 of file pi_level_zero.cpp.
References _pi_queue::Device, _pi_program::Exe, is_in_separated_string(), PI_ASSERT, PI_CALL, PI_FUNCTION_ADDRESS_IS_NOT_AVAILABLE, PI_INVALID_KERNEL_NAME, PI_INVALID_PROGRAM, PI_INVALID_PROGRAM_EXECUTABLE, PI_PROGRAM_INFO_KERNEL_NAMES, piProgramGetInfo(), _pi_program::State, ZE_CALL_NOCHECK, and _pi_program::ZeModule.
piextKernelCreateWithNativeHandle()
pi_result piextKernelCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, pi_program program, bool pluginOwnsNativeHandle, pi_kernel * kernel)
Creates PI kernel object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI kernel from.
context is the PI context of the kernel.
program is the PI program of the kernel.
pluginOwnsNativeHandle Indicates whether the created PI object should take ownership of the native handle.
kernel is the PI kernel created from the native handle.
Definition at line 4911 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_program::Context, PI_ASSERT, PI_CALL, PI_INVALID_CONTEXT, PI_INVALID_KERNEL, PI_INVALID_PROGRAM, PI_INVALID_VALUE, PI_SUCCESS, piContextRetain(), piProgramRetain(), _pi_queue::Properties, and ZE_CALL_NOCHECK.
piextKernelGetNativeHandle()
pi_result piextKernelGetNativeHandle (pi_kernel kernel, pi_native_handle * nativeHandle)
Gets the native handle of a PI kernel object.
Parameters
kernel is the PI kernel to get the native handle of.
nativeHandle is the native handle of kernel.
Definition at line 4940 of file pi_level_zero.cpp.
References PI_ASSERT, PI_INVALID_KERNEL, PI_INVALID_VALUE, PI_SUCCESS, and _pi_kernel::ZeKernel.
piextKernelSetArgMemObj()
pi_result piextKernelSetArgMemObj (pi_kernel Kernel, pi_uint32 ArgIndex, const pi_mem * ArgValue)
Definition at line 4556 of file pi_level_zero.cpp.
References PI_ASSERT, PI_INVALID_KERNEL, PI_SUCCESS, ZE_CALL, and _pi_kernel::ZeKernel.
piextKernelSetArgPointer()
pi_result piextKernelSetArgPointer (pi_kernel kernel, pi_uint32 arg_index, size_t arg_size, const void * arg_value)
Sets up pointer arguments for CL kernels.
An extra indirection is required due to CL argument conventions.
Parameters
kernel is the kernel to be launched
arg_index is the index of the kernel argument
arg_size is the size in bytes of the argument (ignored in CL)
arg_value is the pointer argument
Definition at line 7329 of file pi_level_zero.cpp.
References PI_CALL, PI_SUCCESS, and piKernelSetArg().
piextKernelSetArgSampler()
pi_result piextKernelSetArgSampler (pi_kernel Kernel, pi_uint32 ArgIndex, const pi_sampler * ArgValue)
Definition at line 4574 of file pi_level_zero.cpp.
References PI_ASSERT, PI_INVALID_KERNEL, PI_SUCCESS, ZE_CALL, and _pi_kernel::ZeKernel.
piextMemCreateWithNativeHandle()
pi_result piextMemCreateWithNativeHandle (pi_native_handle nativeHandle, pi_mem * mem)
Creates PI mem object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI mem from.
mem is the PI mem created from the native handle.
Definition at line 3830 of file pi_level_zero.cpp.
References cl::sycl::detail::pi::die(), and PI_SUCCESS.
piextMemGetNativeHandle()
pi_result piextMemGetNativeHandle (pi_mem mem, pi_native_handle * nativeHandle)
Gets the native handle of a PI mem object.
Parameters
mem is the PI mem to get the native handle of.
nativeHandle is the native handle of mem.
Definition at line 3823 of file pi_level_zero.cpp.
References _pi_mem::getZeHandle(), PI_ASSERT, PI_INVALID_MEM_OBJECT, and PI_SUCCESS.
piextPlatformCreateWithNativeHandle()
pi_result piextPlatformCreateWithNativeHandle (pi_native_handle nativeHandle, pi_platform * platform)
Creates PI platform object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI device from.
platform is the PI platform created from the native handle.
Definition at line 1981 of file pi_level_zero.cpp.
References PI_ASSERT, PI_CALL, PI_INVALID_PLATFORM, PI_INVALID_VALUE, PI_SUCCESS, and piPlatformsGet().
piextPlatformGetNativeHandle()
pi_result piextPlatformGetNativeHandle (pi_platform platform, pi_native_handle * nativeHandle)
Gets the native handle of a PI platform object.
Parameters
platform is the PI platform to get the native handle of.
nativeHandle is the native handle of platform.
Definition at line 1970 of file pi_level_zero.cpp.
References PI_ASSERT, PI_INVALID_PLATFORM, PI_INVALID_VALUE, PI_SUCCESS, and _pi_platform::ZeDriver.
piextPluginGetOpaqueData()
pi_result piextPluginGetOpaqueData (void * opaque_data_param, void ** opaque_data_return)
API to get Plugin internal data, opaque to SYCL RT.
Some devices whose device code is compiled by the host compiler (e.g. CPU emulators) may use it to access some device code functionality implemented in/behind the plugin.
Parameters
opaque_data_param - unspecified argument, interpretation is specific to a plugin
opaque_data_return - placeholder for the returned opaque data.
Definition at line 7670 of file pi_level_zero.cpp.
References PI_ERROR_UNKNOWN.
Referenced by cl::sycl::detail::getPluginOpaqueData().
piextProgramCreateWithNativeHandle()
pi_result piextProgramCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, bool pluginOwnsNativeHandle, pi_program * program)
Creates PI program object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI program from.
context is the PI context of the program.
pluginOwnsNativeHandle Indicates whether the created PI object should take ownership of the native handle.
program is the PI program created from the native handle.
Definition at line 4415 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_program::Exe, PI_ASSERT, PI_ERROR_UNKNOWN, PI_INVALID_CONTEXT, PI_INVALID_PROGRAM, PI_INVALID_VALUE, PI_OUT_OF_HOST_MEMORY, and PI_SUCCESS.
piextProgramGetNativeHandle()
pi_result piextProgramGetNativeHandle (pi_program program, pi_native_handle * nativeHandle)
Gets the native handle of a PI program object.
Parameters
program is the PI program to get the native handle of.
nativeHandle is the native handle of program.
Definition at line 4394 of file pi_level_zero.cpp.
References _pi_program::Exe, PI_ASSERT, PI_INVALID_OPERATION, PI_INVALID_PROGRAM, PI_INVALID_VALUE, PI_SUCCESS, _pi_program::State, and _pi_program::ZeModule.
piextProgramSetSpecializationConstant()
pi_result piextProgramSetSpecializationConstant (pi_program prog, pi_uint32 spec_id, size_t spec_size, const void * spec_value)
Sets a specialization constant to a specific value.
Parameters
prog the program object which will use the value
spec_id integer ID of the constant
spec_size size of the value
spec_value bytes of the value
Definition at line 7637 of file pi_level_zero.cpp.
References PI_SUCCESS, and _pi_program::SpecConstants.
piextQueueCreateWithNativeHandle()
pi_result piextQueueCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, pi_queue * queue, bool pluginOwnsNativeHandle)
Creates PI queue object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI queue from.
context is the PI context of the queue.
queue is the PI queue created from the native handle.
pluginOwnsNativeHandle Indicates whether the created PI object should take ownership of the native handle.
Definition at line 3304 of file pi_level_zero.cpp.
References _pi_queue::_pi_queue(), _pi_queue::Context, _pi_queue::Device, _pi_context::Devices, PI_ASSERT, PI_INVALID_CONTEXT, PI_INVALID_QUEUE, PI_INVALID_VALUE, and PI_SUCCESS.
piextQueueGetNativeHandle()
pi_result piextQueueGetNativeHandle (pi_queue queue, pi_native_handle * nativeHandle)
Gets the native handle of a PI queue object.
Parameters
queue is the PI queue to get the native handle of.
nativeHandle is the native handle of queue.
Definition at line 3290 of file pi_level_zero.cpp.
References _pi_queue::ComputeQueueGroup, PI_ASSERT, PI_INVALID_QUEUE, PI_INVALID_VALUE, PI_SUCCESS, and _pi_queue::pi_queue_group_t::ZeQueues.
piextUSMDeviceAlloc()
pi_result piextUSMDeviceAlloc (void ** result_ptr, pi_context context, pi_device device, pi_usm_mem_properties * properties, size_t size, pi_uint32 alignment)
Allocates device memory.
Parameters
result_ptr contains the allocated memory
context is the pi_context
device is the device the memory will be allocated on
properties are optional allocation properties
size is the size of the allocation
alignment is the desired alignment of the allocation
Definition at line 7004 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_platform::ContextsMutex, _pi_queue::Device, _pi_context::DeviceMemAllocContexts, UsmAllocationException::getError(), _pi_context::MemAllocs, PI_CALL, PI_ERROR_UNKNOWN, PI_INVALID_VALUE, PI_SUCCESS, piContextRetain(), _pi_device::Platform, _pi_queue::Properties, UseUSMAllocator, and USMDeviceAllocImpl().
Referenced by piMemBufferCreate().
piextUSMEnqueueMemAdvise()
pi_result piextUSMEnqueueMemAdvise (pi_queue Queue, const void * Ptr, size_t Length, pi_mem_advice Advice, pi_event * Event)
USM memadvise API to govern behavior of automatic migration mechanisms.
USM Memadvise API.
Parameters
Queue is the queue to submit to
Ptr is the data to be advised
Length is the size in bytes of the meory to advise
Advice is device specific advice
Event is the event that represents this operation
Definition at line 7484 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_ze_event_list_t::createAndRetainPiZeEventList(), createEventAndAssociateQueue(), _pi_queue::Device, _pi_queue::executeCommandList(), _pi_context::getAvailableCommandList(), PI_ASSERT, PI_COMMAND_TYPE_USER, PI_INVALID_EVENT, PI_INVALID_QUEUE, PI_SUCCESS, ZE_CALL, and _pi_device::ZeDevice.
piextUSMEnqueueMemcpy()
pi_result piextUSMEnqueueMemcpy (pi_queue queue, pi_bool blocking, void * dst_ptr, const void * src_ptr, size_t size, pi_uint32 num_events_in_waitlist, const pi_event * events_waitlist, pi_event * event)
USM Memcpy API.
Parameters
queue is the queue to submit to
blocking is whether this operation should block the host
src_ptr is the data to be copied
dst_ptr is the location the data will be copied
size is number of bytes to copy
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
Definition at line 7379 of file pi_level_zero.cpp.
References _pi_queue::Context, enqueueMemCopyHelper(), IsDevicePointer(), PI_ASSERT, PI_COMMAND_TYPE_MEM_BUFFER_COPY, PI_INVALID_QUEUE, and PI_INVALID_VALUE.
piextUSMEnqueueMemset()
pi_result piextUSMEnqueueMemset (pi_queue Queue, void * Ptr, pi_int32 Value, size_t Count, pi_uint32 NumEventsInWaitlist, const pi_event * EventsWaitlist, pi_event * Event)
USM Memset API.
Parameters
Queue is the queue to submit to
Ptr is the ptr to memset
Value is value to set. It is interpreted as an 8-bit value and the upper 24 bits are ignored
Count is the size in bytes to memset
NumEventsInWaitlist is the number of events to wait on
EventsWaitlist is an array of events to wait on
Event is the event that represents this operation
Definition at line 7347 of file pi_level_zero.cpp.
References enqueueMemFillHelper(), PI_ASSERT, PI_COMMAND_TYPE_MEM_BUFFER_FILL, PI_INVALID_QUEUE, and PI_INVALID_VALUE.
piextUSMEnqueuePrefetch()
pi_result piextUSMEnqueuePrefetch (pi_queue Queue, const void * Ptr, size_t Size, pi_usm_migration_flags Flags, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Hint to migrate memory to the device.
Parameters
Queue is the queue to submit to
Ptr points to the memory to migrate
Size is the number of bytes to migrate
Flags is a bitfield used to specify memory migration options
NumEventsInWaitlist is the number of events to wait on
EventsWaitlist is an array of events to wait on
Event is the event that represents this operation
Please note that the following code should be run before the subsequent getAvailableCommandList() call so that there is no dead-lock from waiting unsubmitted events in an open batch.
Definition at line 7416 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_ze_event_list_t::createAndRetainPiZeEventList(), createEventAndAssociateQueue(), _pi_queue::executeCommandList(), _pi_context::getAvailableCommandList(), PI_ASSERT, PI_COMMAND_TYPE_USER, PI_INVALID_EVENT, PI_INVALID_QUEUE, PI_INVALID_VALUE, PI_SUCCESS, and ZE_CALL.
piextUSMFree()
pi_result piextUSMFree (pi_context context, void * ptr)
Indicates that the allocated USM memory is no longer needed on the runtime side.
The actual freeing of the memory may be done in a blocking or deferred manner, e.g. to avoid issues with indirect memory access from kernels.
Parameters
context is the pi_context of the allocation
ptr is the memory to be freed
Definition at line 7320 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_platform::ContextsMutex, _pi_context::Devices, and USMFreeHelper().
Referenced by piMemRelease().
piextUSMGetMemAllocInfo()
pi_result piextUSMGetMemAllocInfo (pi_context Context, const void * Ptr, pi_mem_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
API to query information about USM allocated pointers.
API to query information about USM allocated pointers Valid Queries: PI_MEM_ALLOC_TYPE returns host/device/shared pi_host_usm value PI_MEM_ALLOC_BASE_PTR returns the base ptr of an allocation if the queried pointer fell inside an allocation.
Valid Queries: PI_MEM_ALLOC_TYPE returns host/device/shared pi_usm_type value PI_MEM_ALLOC_BASE_PTR returns the base ptr of an allocation if the queried pointer fell inside an allocation. Result must fit in void * PI_MEM_ALLOC_SIZE returns how big the queried pointer's allocation is in bytes. Result is a size_t. PI_MEM_ALLOC_DEVICE returns the pi_device this was allocated against
Parameters
Context is the pi_context
Ptr is the pointer to query
ParamName is the type of query to perform
ParamValueSize is the size of the result in bytes
ParamValue is the result
ParamValueRet is how many bytes were written
Definition at line 7552 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_queue::Device, _pi_context::Devices, PI_ASSERT, PI_INVALID_CONTEXT, PI_INVALID_VALUE, PI_MEM_ALLOC_BASE_PTR, PI_MEM_ALLOC_DEVICE, PI_MEM_ALLOC_SIZE, PI_MEM_ALLOC_TYPE, PI_MEM_TYPE_DEVICE, PI_MEM_TYPE_HOST, PI_MEM_TYPE_SHARED, PI_MEM_TYPE_UNKNOWN, PI_SUCCESS, ZE_CALL, and _pi_context::ZeContext.
piextUSMHostAlloc()
pi_result piextUSMHostAlloc (void ** result_ptr, pi_context context, pi_usm_mem_properties * properties, size_t size, pi_uint32 alignment)
Allocates host memory accessible by the device.
Parameters
result_ptr contains the allocated memory
context is the pi_context
properties are optional allocation properties
size is the size of the allocation
alignment is the desired alignment of the allocation
Definition at line 7143 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_platform::ContextsMutex, _pi_context::Devices, UsmAllocationException::getError(), _pi_context::HostMemAllocContext, _pi_context::MemAllocs, PI_CALL, PI_ERROR_UNKNOWN, PI_INVALID_VALUE, PI_SUCCESS, piContextRetain(), _pi_queue::Properties, UseUSMAllocator, and USMHostAllocImpl().
Referenced by piMemBufferCreate().
piextUSMSharedAlloc()
pi_result piextUSMSharedAlloc (void ** result_ptr, pi_context context, pi_device device, pi_usm_mem_properties * properties, size_t size, pi_uint32 alignment)
Allocates memory accessible on both host and device.
Parameters
result_ptr contains the allocated memory
context is the pi_context
device is the device the memory will be allocated on
properties are optional allocation properties
size is the size of the allocation
alignment is the desired alignment of the allocation
Definition at line 7067 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_platform::ContextsMutex, _pi_queue::Device, cl::sycl::detail::DeviceReadOnly, UsmAllocationException::getError(), _pi_context::MemAllocs, PI_ASSERT, PI_CALL, PI_ERROR_UNKNOWN, PI_INVALID_VALUE, PI_MEM_ALLOC_DEVICE_READ_ONLY, PI_MEM_ALLOC_FLAGS, PI_SUCCESS, piContextRetain(), _pi_device::Platform, _pi_queue::Properties, _pi_context::SharedMemAllocContexts, _pi_context::SharedReadOnlyAllocs, _pi_context::SharedReadOnlyMemAllocContexts, UseUSMAllocator, and USMSharedAllocImpl().
piKernelCreate()
pi_result piKernelCreate (pi_program Program, const char * KernelName, pi_kernel * RetKernel)
Definition at line 4487 of file pi_level_zero.cpp.
References _pi_program::Context, _pi_program::Exe, PI_ASSERT, PI_CALL, PI_ERROR_UNKNOWN, PI_INVALID_PROGRAM, PI_INVALID_PROGRAM_EXECUTABLE, PI_INVALID_VALUE, PI_OUT_OF_HOST_MEMORY, PI_SUCCESS, piContextRetain(), piProgramRetain(), _pi_queue::Properties, _pi_program::State, ZE_CALL, ZE_CALL_NOCHECK, and _pi_program::ZeModule.
piKernelGetGroupInfo()
pi_result piKernelGetGroupInfo (pi_kernel Kernel, pi_device Device, pi_kernel_group_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 4639 of file pi_level_zero.cpp.
References _pi_queue::Device, cl::sycl::detail::pi::die(), PI_ASSERT, PI_INVALID_DEVICE, PI_INVALID_KERNEL, PI_INVALID_VALUE, PI_KERNEL_GROUP_INFO_COMPILE_WORK_GROUP_SIZE, PI_KERNEL_GROUP_INFO_GLOBAL_WORK_SIZE, PI_KERNEL_GROUP_INFO_LOCAL_MEM_SIZE, PI_KERNEL_GROUP_INFO_NUM_REGS, PI_KERNEL_GROUP_INFO_PREFERRED_WORK_GROUP_SIZE_MULTIPLE, PI_KERNEL_GROUP_INFO_PRIVATE_MEM_SIZE, PI_KERNEL_GROUP_INFO_WORK_GROUP_SIZE, PI_SUCCESS, ZE_CALL, _pi_device::ZeDeviceComputeProperties, _pi_device::ZeDeviceProperties, _pi_kernel::ZeKernel, and _pi_kernel::ZeKernelProperties.
piKernelGetInfo()
pi_result piKernelGetInfo (pi_kernel Kernel, pi_kernel_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 4586 of file pi_level_zero.cpp.
References _pi_program::Context, PI_ASSERT, PI_ERROR_UNKNOWN, PI_INVALID_KERNEL, PI_INVALID_VALUE, PI_KERNEL_INFO_ATTRIBUTES, PI_KERNEL_INFO_CONTEXT, PI_KERNEL_INFO_FUNCTION_NAME, PI_KERNEL_INFO_NUM_ARGS, PI_KERNEL_INFO_PROGRAM, PI_KERNEL_INFO_REFERENCE_COUNT, PI_OUT_OF_HOST_MEMORY, PI_SUCCESS, _pi_kernel::Program, ZE_CALL, _pi_kernel::ZeKernel, and _pi_kernel::ZeKernelProperties.
Referenced by cl::sycl::detail::get_kernel_info< std::string, Param >::get(), cl::sycl::detail::get_kernel_info< cl_uint, Param >::get(), cl::sycl::detail::ProgramManager::getPiProgramFromPiKernel(), cl::sycl::detail::enqueue_kernel_launch::handleInvalidWorkGroupSize(), cl::sycl::detail::kernel_impl::kernel_impl(), and piPluginInit().
piKernelGetSubGroupInfo()
pi_result piKernelGetSubGroupInfo (pi_kernel kernel, pi_device device, pi_kernel_sub_group_info param_name, size_t input_value_size, const void * input_value, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
API to query information from the sub-group from a kernel.
Parameters
kernel is the pi_kernel to query
device is the device the kernel is executed on
param_name is a pi_kernel_sub_group_info enum value that specifies the informtation queried for.
input_value_size is the size of input value passed in ptr input_value param
input_value is the ptr to the input value passed.
param_value_size is the size of the value in bytes.
param_value is a pointer to the value to set.
param_value_size_ret is a pointer to return the size of data in param_value ptr.
All queries expect a return of 4 bytes in param_value_size, param_value_size_ret, and a uint32_t value should to be written in param_value ptr. Note: This behaviour differs from OpenCL. OpenCL returns size_t.
Definition at line 4691 of file pi_level_zero.cpp.
References _pi_queue::Device, cl::sycl::detail::pi::die(), PI_KERNEL_COMPILE_NUM_SUB_GROUPS, PI_KERNEL_COMPILE_SUB_GROUP_SIZE_INTEL, PI_KERNEL_MAX_NUM_SUB_GROUPS, PI_KERNEL_MAX_SUB_GROUP_SIZE, PI_SUCCESS, and _pi_kernel::ZeKernelProperties.
piKernelRelease()
pi_result piKernelRelease (pi_kernel Kernel)
Definition at line 4729 of file pi_level_zero.cpp.
References _pi_program::Context, _pi_platform::ContextsMutex, _pi_context::Devices, _pi_kernel::MemAllocs, _pi_kernel::OwnZeKernel, PI_ASSERT, PI_CALL, PI_INVALID_KERNEL, PI_SUCCESS, piContextRelease(), piProgramRelease(), _pi_kernel::Program, _pi_kernel::SubmissionsCount, USMFreeHelper(), ZE_CALL, and _pi_kernel::ZeKernel.
Referenced by _pi_event::cleanup(), piPluginInit(), cl::sycl::detail::kernel_impl::~kernel_impl(), and cl::sycl::detail::KernelProgramCache::~KernelProgramCache().
piKernelRetain()
pi_result piKernelRetain (pi_kernel Kernel)
Definition at line 4717 of file pi_level_zero.cpp.
References PI_ASSERT, PI_CALL, PI_INVALID_KERNEL, PI_SUCCESS, piProgramRetain(), and _pi_kernel::Program.
Referenced by cl::sycl::detail::kernel_impl::get(), cl::sycl::detail::kernel_impl::getNative(), cl::sycl::detail::kernel_impl::kernel_impl(), cl::sycl::detail::make_kernel(), piEnqueueKernelLaunch(), and piPluginInit().
piKernelSetArg()
pi_result piKernelSetArg (pi_kernel Kernel, pi_uint32 ArgIndex, size_t ArgSize, const void * ArgValue)
Definition at line 4530 of file pi_level_zero.cpp.
References PI_ASSERT, PI_INVALID_KERNEL, PI_SUCCESS, ZE_CALL, and _pi_kernel::ZeKernel.
Referenced by piextKernelSetArgPointer(), piPluginInit(), and cl::sycl::detail::SetKernelParamsAndLaunch().
piKernelSetExecInfo()
pi_result piKernelSetExecInfo (pi_kernel kernel, pi_kernel_exec_info value_name, size_t param_value_size, const void * param_value)
API to set attributes controlling kernel execution.
Parameters
kernel is the pi kernel to execute
param_name is a pi_kernel_exec_info value that specifies the info passed to the kernel
param_value_size is the size of the value in bytes
param_value is a pointer to the value to set for the kernel
If param_name is PI_USM_INDIRECT_ACCESS, the value will be a ptr to the pi_bool value PI_TRUE If param_name is PI_USM_PTRS, the value will be an array of ptrs
Definition at line 7613 of file pi_level_zero.cpp.
References PI_ASSERT, PI_INVALID_KERNEL, PI_INVALID_VALUE, PI_SUCCESS, PI_TRUE, PI_USM_INDIRECT_ACCESS, ZE_CALL, and _pi_kernel::ZeKernel.
piMemBufferCreate()
pi_result piMemBufferCreate (pi_context Context, pi_mem_flags Flags, size_t Size, void * HostPtr, pi_mem * RetMem, const pi_mem_properties * properties)
Definition at line 3395 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_context::Devices, cl::sycl::detail::pi::die(), ZeUSMImportExtension::doZeUSMImport(), enableBufferPooling(), ZeUSMImportExtension::Enabled, cl::sycl::detail::memcpy(), PI_ASSERT, PI_CALL, PI_ERROR_UNKNOWN, PI_INVALID_CONTEXT, PI_INVALID_VALUE, PI_MEM_ACCESS_READ_ONLY, PI_MEM_FLAGS_ACCESS_RW, PI_MEM_FLAGS_HOST_PTR_ALLOC, PI_MEM_FLAGS_HOST_PTR_COPY, PI_MEM_FLAGS_HOST_PTR_USE, PI_OUT_OF_HOST_MEMORY, PI_SUCCESS, piextUSMDeviceAlloc(), piextUSMHostAlloc(), _pi_context::SingleRootDevice, ZE_CALL, _pi_context::ZeCommandListInit, _pi_context::ZeContext, ZeDeviceMemAllocHelper(), ZeHostMemAllocHelper(), and ZeUSMImport.
piMemBufferPartition()
pi_result piMemBufferPartition (pi_mem Buffer, pi_mem_flags Flags, pi_buffer_create_type BufferCreateType, void * BufferCreateInfo, pi_mem * RetMem)
Definition at line 6678 of file pi_level_zero.cpp.
References _pi_mem::Context, cl::sycl::detail::pi::die(), _pi_mem::getZeHandle(), _pi_mem::isImage(), PI_ASSERT, PI_BUFFER_CREATE_TYPE_REGION, PI_ERROR_UNKNOWN, PI_INVALID_BUFFER_SIZE, PI_INVALID_MEM_OBJECT, PI_INVALID_VALUE, PI_MEM_FLAGS_ACCESS_RW, PI_OUT_OF_HOST_MEMORY, and PI_SUCCESS.
piMemGetInfo()
pi_result piMemGetInfo (pi_mem Mem, cl_mem_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 3564 of file pi_level_zero.cpp.
References cl::sycl::detail::pi::die().
Referenced by cl::sycl::detail::SYCLMemObjT::getBufSizeForContext(), cl::sycl::detail::image_impl< Dimensions >::image_impl(), piPluginInit(), and cl::sycl::detail::SYCLMemObjT::SYCLMemObjT().
piMemImageCreate()
pi_result piMemImageCreate (pi_context Context, pi_mem_flags Flags, const pi_image_format * ImageFormat, const pi_image_desc * ImageDesc, void * HostPtr, pi_mem * RetImage)
Definition at line 3652 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_queue::Device, _pi_context::Devices, cl::sycl::detail::pi::die(), _pi_image_desc::image_array_size, _pi_image_format::image_channel_data_type, _pi_image_format::image_channel_order, _pi_image_desc::image_depth, _pi_image_desc::image_height, _pi_image_desc::image_type, _pi_image_desc::image_width, _pi_image_desc::num_mip_levels, PI_ASSERT, PI_ERROR_UNKNOWN, PI_INVALID_CONTEXT, PI_INVALID_IMAGE_FORMAT_DESCRIPTOR, PI_INVALID_VALUE, PI_MEM_FLAGS_ACCESS_RW, PI_MEM_FLAGS_HOST_PTR_COPY, PI_MEM_FLAGS_HOST_PTR_USE, PI_MEM_TYPE_IMAGE1D, PI_MEM_TYPE_IMAGE1D_ARRAY, PI_MEM_TYPE_IMAGE2D, PI_MEM_TYPE_IMAGE2D_ARRAY, PI_MEM_TYPE_IMAGE3D, PI_OUT_OF_HOST_MEMORY, PI_SUCCESS, _pi_context::SingleRootDevice, ZE_CALL, _pi_context::ZeCommandListInit, _pi_context::ZeContext, and _pi_device::ZeDevice.
piMemImageGetInfo()
pi_result piMemImageGetInfo (pi_mem Image, pi_image_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 6393 of file pi_level_zero.cpp.
References cl::sycl::detail::pi::die().
Referenced by cl::sycl::detail::getImageInfo(), and piPluginInit().
piMemRelease()
pi_result piMemRelease (pi_mem Mem)
Definition at line 3616 of file pi_level_zero.cpp.
References _pi_mem::Context, _pi_context::Devices, ZeUSMImportExtension::doZeUSMRelease(), enableBufferPooling(), _pi_mem::getZeHandle(), _pi_mem::HostPtrImported, _pi_mem::isImage(), _pi_mem::MapHostPtr, PI_ASSERT, PI_CALL, PI_INVALID_MEM_OBJECT, PI_SUCCESS, piextUSMFree(), ZE_CALL, ZeMemFreeHelper(), and ZeUSMImport.
Referenced by cl::sycl::detail::memReleaseHelper(), piPluginInit(), and cl::sycl::detail::SYCLMemObjT::updateHostMemory().
piMemRetain()
pi_result piMemRetain (pi_mem Mem)
Definition at line 3577 of file pi_level_zero.cpp.
References PI_ASSERT, PI_INVALID_MEM_OBJECT, and PI_SUCCESS.
Referenced by piPluginInit(), and cl::sycl::detail::SYCLMemObjT::SYCLMemObjT().
piPlatformGetInfo()
pi_result piPlatformGetInfo (pi_platform Platform, pi_platform_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 1920 of file pi_level_zero.cpp.
References PI_ASSERT, PI_INVALID_PLATFORM, PI_INVALID_VALUE, PI_PLATFORM_INFO_EXTENSIONS, PI_PLATFORM_INFO_NAME, PI_PLATFORM_INFO_PROFILE, PI_PLATFORM_INFO_VENDOR, PI_PLATFORM_INFO_VERSION, PI_SUCCESS, ZE_SUPPORTED_EXTENSIONS, _pi_platform::ZeDriverApiVersion, and _pi_platform::ZeDriverVersion.
Referenced by cl::sycl::detail::get_platform_info< std::string, param >::get(), and piPluginInit().
piPlatformsGet()
pi_result piPlatformsGet (pi_uint32 NumEntries, pi_platform * Platforms, pi_uint32 * NumPlatforms)
Runtime queries number of Platforms
Definition at line 1802 of file pi_level_zero.cpp.
References _pi_platform::initialize(), PI_ASSERT, PI_ERROR_UNKNOWN, PI_INVALID_PLATFORM, PI_INVALID_VALUE, PI_OUT_OF_HOST_MEMORY, PI_SUCCESS, PiPlatformCachePopulated, PiPlatformsCache, PiPlatformsCacheMutex, PrintPiTrace, setEnvVar(), ZE_CALL, and ZE_CALL_NOCHECK.
Referenced by piextPlatformCreateWithNativeHandle().
piPluginInit()
pi_result piPluginInit (pi_plugin * PluginInit)
Definition at line 7653 of file pi_level_zero.cpp.
References _PI_H_VERSION_STRING, PI_ASSERT, PI_INVALID_VALUE, PI_SUCCESS, and _pi_plugin::PluginVersion.
piProgramBuild()
pi_result piProgramBuild (pi_program Program, pi_uint32 NumDevices, const pi_device * DeviceList, const char * Options, void(*)(pi_program Program, void *UserData) PFnNotify, void * UserData)
Definition at line 4241 of file pi_level_zero.cpp.
References checkUnresolvedSymbols(), _pi_program::Code, _pi_program::CodeLength, _pi_program::Context, _pi_context::Devices, _pi_program::Exe, _pi_program::IL, _pi_program::Invalid, _pi_program::Native, PI_ASSERT, PI_BUILD_PROGRAM_FAILURE, PI_INVALID_OPERATION, PI_INVALID_PROGRAM, PI_INVALID_VALUE, PI_SUCCESS, _pi_program::State, _pi_program::SpecConstantShim::ze(), ZE_CALL_NOCHECK, _pi_program::ZeBuildLog, _pi_context::ZeContext, _pi_device::ZeDevice, and _pi_program::ZeModule.
piProgramCompile()
pi_result piProgramCompile (pi_program Program, pi_uint32 NumDevices, const pi_device * DeviceList, const char * Options, pi_uint32 NumInputHeaders, const pi_program * InputHeaders, const char ** HeaderIncludeNames, void(*)(pi_program Program, void *UserData) PFnNotify, void * UserData)
Definition at line 4202 of file pi_level_zero.cpp.
References _pi_program::BuildFlags, _pi_program::IL, _pi_program::Object, PI_ASSERT, PI_INVALID_OPERATION, PI_INVALID_PROGRAM, PI_INVALID_VALUE, PI_SUCCESS, and _pi_program::State.
piProgramCreate()
pi_result piProgramCreate (pi_context Context, const void * ILBytes, size_t Length, pi_program * Program)
Definition at line 3838 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_program::IL, PI_ASSERT, PI_ERROR_UNKNOWN, PI_INVALID_CONTEXT, PI_INVALID_PROGRAM, PI_INVALID_VALUE, PI_OUT_OF_HOST_MEMORY, and PI_SUCCESS.
piProgramCreateWithBinary()
pi_result piProgramCreateWithBinary (pi_context context, pi_uint32 num_devices, const pi_device * device_list, const size_t * lengths, const unsigned char ** binaries, size_t num_metadata_entries, const pi_device_binary_property * metadata, pi_int32 * binary_status, pi_program * ret_program)
Creates a PI program for a context and loads the given binary into it.
Parameters
context is the PI context to associate the program with.
num_devices is the number of devices in device_list.
device_list is a pointer to a list of devices. These devices must all be in context.
lengths is an array of sizes in bytes of the binary in binaries.
binaries is a pointer to a list of program binaries.
num_metadata_entries is the number of metadata entries in metadata.
metadata is a pointer to a list of program metadata entries. The use of metadata entries is backend-defined.
binary_status returns whether the program binary was loaded succesfully or not, for each device in device_list. binary_status is ignored if it is null and otherwise it must be an array of num_devices elements.
ret_program is the PI program created from the program binaries.
Definition at line 3858 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_program::Native, PI_ASSERT, PI_ERROR_UNKNOWN, PI_INVALID_CONTEXT, PI_INVALID_PROGRAM, PI_INVALID_VALUE, PI_OUT_OF_HOST_MEMORY, and PI_SUCCESS.
piProgramGetBuildInfo()
pi_result piProgramGetBuildInfo (pi_program Program, pi_device Device, cl_program_build_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 4326 of file pi_level_zero.cpp.
References _pi_queue::Device, _pi_program::ErrorMessage, _pi_program::Exe, _pi_program::Object, PI_INVALID_VALUE, PI_SUCCESS, _pi_program::State, ZE_CALL, and _pi_program::ZeBuildLog.
Referenced by cl::sycl::detail::ProgramManager::getProgramBuildLog(), cl::sycl::detail::enqueue_kernel_launch::handleInvalidWorkGroupSize(), cl::sycl::detail::make_kernel_bundle(), and piPluginInit().
piProgramGetInfo()
pi_result piProgramGetInfo (pi_program Program, pi_program_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 3923 of file pi_level_zero.cpp.
References _pi_program::Code, _pi_program::CodeLength, _pi_program::Context, _pi_context::Devices, cl::sycl::detail::pi::die(), _pi_program::Exe, _pi_program::IL, cl::sycl::detail::memcpy(), _pi_program::Native, _pi_program::Object, PI_ASSERT, PI_ERROR_UNKNOWN, PI_INVALID_PROGRAM, PI_INVALID_PROGRAM_EXECUTABLE, PI_OUT_OF_HOST_MEMORY, PI_PROGRAM_INFO_BINARIES, PI_PROGRAM_INFO_BINARY_SIZES, PI_PROGRAM_INFO_DEVICES, PI_PROGRAM_INFO_KERNEL_NAMES, PI_PROGRAM_INFO_NUM_DEVICES, PI_PROGRAM_INFO_NUM_KERNELS, PI_PROGRAM_INFO_REFERENCE_COUNT, PI_SUCCESS, _pi_program::State, ZE_CALL, and _pi_program::ZeModule.
Referenced by cl::sycl::detail::program_impl::get_binaries(), cl::sycl::detail::ProgramManager::getProgramBuildLog(), cl::sycl::detail::make_kernel_bundle(), piextGetDeviceFunctionPointer(), piPluginInit(), cl::sycl::detail::program_impl::get_info< info::program::reference_count >(), and cl::sycl::detail::PersistentDeviceCodeCache::putItemToDisc().
piProgramLink()
pi_result piProgramLink (pi_context Context, pi_uint32 NumDevices, const pi_device * DeviceList, const char * Options, pi_uint32 NumInputPrograms, const pi_program * InputPrograms, void(*)(pi_program Program, void *UserData) PFnNotify, void * UserData, pi_program * RetProgram)
Definition at line 4027 of file pi_level_zero.cpp.
References _pi_program::BuildFlags, checkUnresolvedSymbols(), _pi_program::Code, _pi_program::CodeLength, _pi_queue::Context, _pi_context::Devices, _pi_program::Exe, _pi_program::Invalid, _pi_program::Object, PI_ASSERT, PI_ERROR_UNKNOWN, PI_INVALID_DEVICE, PI_INVALID_OPERATION, PI_INVALID_VALUE, PI_LINK_PROGRAM_FAILURE, PI_OUT_OF_HOST_MEMORY, PI_SUCCESS, PiDriverModuleProgramExtensionFound, ZE_CALL_NOCHECK, _pi_context::ZeContext, and _pi_device::ZeDevice.
piProgramRelease()
pi_result piProgramRelease (pi_program Program)
Definition at line 4384 of file pi_level_zero.cpp.
References PI_ASSERT, PI_INVALID_PROGRAM, PI_INVALID_VALUE, and PI_SUCCESS.
Referenced by piKernelRelease(), piPluginInit(), cl::sycl::detail::context_impl::~context_impl(), cl::sycl::detail::device_image_impl::~device_image_impl(), cl::sycl::detail::KernelProgramCache::~KernelProgramCache(), and cl::sycl::detail::program_impl::~program_impl().
piProgramRetain()
pi_result piProgramRetain (pi_program Program)
Definition at line 4378 of file pi_level_zero.cpp.
References PI_ASSERT, PI_INVALID_PROGRAM, and PI_SUCCESS.
Referenced by cl::sycl::detail::ProgramManager::build(), cl::sycl::detail::program_impl::build_with_kernel_name(), cl::sycl::detail::program_impl::get(), cl::sycl::detail::program_impl::getNative(), piextKernelCreateWithNativeHandle(), piKernelCreate(), piKernelRetain(), and piPluginInit().
piQueueCreate()
pi_result piQueueCreate (pi_context Context, pi_device Device, pi_queue_properties Properties, pi_queue * Queue)
Definition at line 3059 of file pi_level_zero.cpp.
References _pi_queue::_pi_queue(), _pi_queue::Context, _pi_queue::Device, _pi_context::Devices, _pi_device::hasLinkCopyEngine(), _pi_device::hasMainCopyEngine(), PI_ASSERT, PI_ERROR_UNKNOWN, PI_INVALID_CONTEXT, PI_INVALID_DEVICE, PI_INVALID_QUEUE, PI_INVALID_VALUE, PI_OUT_OF_HOST_MEMORY, PI_QUEUE_ON_DEVICE, PI_QUEUE_ON_DEVICE_DEFAULT, PI_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE, PI_QUEUE_PROFILING_ENABLE, PI_SUCCESS, _pi_queue::Properties, and _pi_device::QueueGroup.
piQueueFinish()
pi_result piQueueFinish (pi_queue Queue)
Definition at line 3248 of file pi_level_zero.cpp.
References _pi_queue::ComputeQueueGroup, _pi_queue::CopyQueueGroup, _pi_queue::executeAllOpenCommandLists(), _pi_queue::LastCommandEvent, PI_ASSERT, PI_INVALID_QUEUE, PI_SUCCESS, ZE_CALL, and _pi_queue::pi_queue_group_t::ZeQueues.
Referenced by cl::sycl::detail::queue_impl::getExclusiveQueueHandleRef(), piPluginInit(), and cl::sycl::detail::queue_impl::wait().
piQueueFlush()
pi_result piQueueFlush (pi_queue Queue)
Definition at line 3285 of file pi_level_zero.cpp.
References PI_SUCCESS.
Referenced by cl::sycl::detail::event_impl::flushIfNeeded(), and piPluginInit().
piQueueGetInfo()
pi_result piQueueGetInfo (pi_queue Queue, pi_queue_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 3109 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_queue::Device, cl::sycl::detail::pi::die(), PI_ASSERT, PI_INVALID_QUEUE, PI_INVALID_VALUE, PI_QUEUE_INFO_CONTEXT, PI_QUEUE_INFO_DEVICE, PI_QUEUE_INFO_DEVICE_DEFAULT, PI_QUEUE_INFO_PROPERTIES, PI_QUEUE_INFO_REFERENCE_COUNT, PI_QUEUE_INFO_SIZE, and PI_SUCCESS.
Referenced by piPluginInit(), and cl::sycl::detail::queue_impl::get_info< info::queue::reference_count >().
piQueueRelease()
pi_result piQueueRelease (pi_queue Queue)
Definition at line 3150 of file pi_level_zero.cpp.
References _pi_queue::CommandListMap, _pi_queue::ComputeQueueGroup, _pi_queue::CopyQueueGroup, _pi_queue::executeAllOpenCommandLists(), _pi_queue::Healthy, PI_ASSERT, PI_CALL, PI_INVALID_QUEUE, PI_SUCCESS, QueueRelease(), _pi_queue::RefCountExternal, _pi_queue::resetCommandList(), ZE_CALL, and _pi_queue::pi_queue_group_t::ZeQueues.
Referenced by piPluginInit(), and cl::sycl::detail::queue_impl::~queue_impl().
piQueueRetain()
pi_result piQueueRetain (pi_queue Queue)
Definition at line 3142 of file pi_level_zero.cpp.
References PI_SUCCESS, piQueueRetainNoLock(), and _pi_queue::RefCountExternal.
Referenced by cl::sycl::detail::queue_impl::get(), cl::sycl::detail::queue_impl::getNative(), and piPluginInit().
piQueueRetainNoLock()
static void piQueueRetainNoLock (pi_queue Queue) inline static
Definition at line 597 of file pi_level_zero.cpp.
Referenced by createEventAndAssociateQueue(), and piQueueRetain().
piSamplerCreate()
pi_result piSamplerCreate (pi_context Context, const pi_sampler_properties * SamplerProperties, pi_sampler * RetSampler)
Definition at line 5456 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_queue::Device, _pi_context::Devices, PI_ASSERT, PI_ERROR_UNKNOWN, PI_FALSE, PI_INVALID_CONTEXT, PI_INVALID_VALUE, PI_OUT_OF_HOST_MEMORY, PI_SAMPLER_ADDRESSING_MODE_CLAMP, PI_SAMPLER_ADDRESSING_MODE_CLAMP_TO_EDGE, PI_SAMPLER_ADDRESSING_MODE_MIRRORED_REPEAT, PI_SAMPLER_ADDRESSING_MODE_NONE, PI_SAMPLER_ADDRESSING_MODE_REPEAT, PI_SAMPLER_FILTER_MODE_LINEAR, PI_SAMPLER_FILTER_MODE_NEAREST, PI_SAMPLER_PROPERTIES_ADDRESSING_MODE, PI_SAMPLER_PROPERTIES_FILTER_MODE, PI_SAMPLER_PROPERTIES_NORMALIZED_COORDS, PI_SUCCESS, PI_TRUE, ZE_CALL, _pi_context::ZeContext, and _pi_device::ZeDevice.
piSamplerGetInfo()
pi_result piSamplerGetInfo (pi_sampler Sampler, pi_sampler_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 5586 of file pi_level_zero.cpp.
References cl::sycl::detail::pi::die().
Referenced by piPluginInit(), and cl::sycl::detail::sampler_impl::sampler_impl().
piSamplerRelease()
pi_result piSamplerRelease (pi_sampler Sampler)
Definition at line 5606 of file pi_level_zero.cpp.
References PI_ASSERT, PI_INVALID_SAMPLER, PI_SUCCESS, ZE_CALL, and _pi_sampler::ZeSampler.
Referenced by piPluginInit(), and cl::sycl::detail::sampler_impl::~sampler_impl().
piSamplerRetain()
pi_result piSamplerRetain (pi_sampler Sampler)
Definition at line 5599 of file pi_level_zero.cpp.
References PI_ASSERT, PI_INVALID_SAMPLER, and PI_SUCCESS.
Referenced by piPluginInit(), and cl::sycl::detail::sampler_impl::sampler_impl().
piTearDown()
pi_result piTearDown (void * PluginParameter)
API to notify that the plugin should clean up its resources.
No PI calls should be made until the next piPluginInit call.
Parameters
PluginParameter placeholder for future use, currenly not used.
Skipping map entry for SLM_BTI
Definition at line 7680 of file pi_level_zero.cpp.
References PI_INVALID_MEM_OBJECT, PI_SUCCESS, PiPlatformsCache, and PiPlatformsCacheMutex.
printZeEventList()
static void printZeEventList (const _pi_ze_event_list_t & PiZeEventList) static
Definition at line 1624 of file pi_level_zero.cpp.
References _pi_ze_event_list_t::Length, and _pi_ze_event_list_t::ZeEventList.
Referenced by enqueueMemCopyHelper(), enqueueMemCopyRectHelper(), enqueueMemFillHelper(), and piEnqueueKernelLaunch().
QueueRelease()
static pi_result QueueRelease (pi_queue Queue, pi_queue LockedQueue) static
Definition at line 3204 of file pi_level_zero.cpp.
References _pi_queue::ComputeCommandBatch, _pi_queue::ComputeQueueGroup, _pi_queue::CopyCommandBatch, _pi_queue::CopyQueueGroup, _pi_queue::CommandBatch::NumTimesClosedEarly, _pi_queue::CommandBatch::NumTimesClosedFull, _pi_queue::OwnZeCommandQueue, PI_ASSERT, PI_INVALID_QUEUE, PI_SUCCESS, ZE_CALL, and _pi_queue::pi_queue_group_t::ZeQueues.
Referenced by EventRelease(), and piQueueRelease().
setEnvVar()
static bool setEnvVar (const char * name, const char * value) static
Definition at line 1687 of file pi_level_zero.cpp.
Referenced by piPlatformsGet(), and ZeUSMImportExtension::setZeUSMImport().
ShouldUseUSMAllocator()
static bool ShouldUseUSMAllocator () static
Definition at line 6826 of file pi_level_zero.cpp.
USMDeviceAllocImpl()
static pi_result USMDeviceAllocImpl (void ** ResultPtr, pi_context Context, pi_device Device, pi_usm_mem_properties * Properties, size_t Size, pi_uint32 Alignment) static
Definition at line 6833 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_queue::Device, PI_ASSERT, PI_INVALID_CONTEXT, PI_INVALID_DEVICE, PI_INVALID_VALUE, PI_MEM_ALLOC_FLAGS, PI_SUCCESS, _pi_queue::Properties, ZE_CALL, _pi_context::ZeContext, _pi_device::ZeDevice, and _pi_device::ZeDeviceProperties.
Referenced by USMDeviceMemoryAlloc::allocateImpl(), and piextUSMDeviceAlloc().
USMFreeHelper()
static pi_result USMFreeHelper (pi_context Context, void * Ptr) static
Definition at line 7208 of file pi_level_zero.cpp.
References _pi_queue::Context, ContextReleaseHelper(), _pi_queue::Device, _pi_context::DeviceMemAllocContexts, _pi_context::Devices, cl::sycl::detail::pi::die(), UsmAllocationException::getError(), _pi_context::HostMemAllocContext, _pi_context::MemAllocs, PI_ASSERT, PI_CALL, PI_ERROR_UNKNOWN, PI_INVALID_DEVICE, PI_INVALID_VALUE, PI_SUCCESS, _pi_context::SharedMemAllocContexts, _pi_context::SharedReadOnlyAllocs, _pi_context::SharedReadOnlyMemAllocContexts, UseUSMAllocator, USMFreeImpl(), ZE_CALL, _pi_context::ZeContext, and _pi_device::ZeDevice.
Referenced by piextUSMFree(), and piKernelRelease().
USMFreeImpl()
static pi_result USMFreeImpl (pi_context Context, void * Ptr) static
Definition at line 6922 of file pi_level_zero.cpp.
References _pi_queue::Context, PI_SUCCESS, ZE_CALL, and _pi_context::ZeContext.
Referenced by USMMemoryAllocBase::deallocate(), and USMFreeHelper().
USMHostAllocImpl()
static pi_result USMHostAllocImpl (void ** ResultPtr, pi_context Context, pi_usm_mem_properties * Properties, size_t Size, pi_uint32 Alignment) static
Definition at line 6899 of file pi_level_zero.cpp.
References _pi_queue::Context, PI_ASSERT, PI_INVALID_CONTEXT, PI_INVALID_VALUE, PI_MEM_ALLOC_FLAGS, PI_SUCCESS, _pi_queue::Properties, ZE_CALL, and _pi_context::ZeContext.
Referenced by USMHostMemoryAlloc::allocateImpl(), and piextUSMHostAlloc().
USMSharedAllocImpl()
static pi_result USMSharedAllocImpl (void ** ResultPtr, pi_context Context, pi_device Device, pi_usm_mem_properties * Properties, size_t Size, pi_uint32 Alignment) static
Definition at line 6867 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_queue::Device, PI_ASSERT, PI_INVALID_CONTEXT, PI_INVALID_DEVICE, PI_INVALID_VALUE, PI_SUCCESS, _pi_queue::Properties, ZE_CALL, _pi_context::ZeContext, _pi_device::ZeDevice, and _pi_device::ZeDeviceProperties.
Referenced by USMSharedMemoryAlloc::allocateImpl(), USMSharedReadOnlyMemoryAlloc::allocateImpl(), and piextUSMSharedAlloc().
ZeCommandListBatchConfig()
static const zeCommandListBatchConfig ZeCommandListBatchConfig (bool IsCopy) static
Definition at line 925 of file pi_level_zero.cpp.
References cl::sycl::detail::pi::die().
Referenced by _pi_queue::adjustBatchSizeForFullBatch(), _pi_queue::adjustBatchSizeForPartialBatch(), and _pi_queue::executeCommandList().
ZeDeviceMemAllocHelper()
static pi_result ZeDeviceMemAllocHelper (void ** ResultPtr, pi_context Context, pi_device Device, size_t Size) static
Definition at line 3329 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_platform::ContextsMutex, _pi_queue::Device, _pi_context::MemAllocs, PI_CALL, PI_SUCCESS, piContextRetain(), _pi_device::Platform, ZE_CALL, _pi_context::ZeContext, and _pi_device::ZeDevice.
Referenced by piMemBufferCreate().
ZeHostMemAllocHelper()
static pi_result ZeHostMemAllocHelper (void ** ResultPtr, pi_context Context, size_t Size) static
Definition at line 3364 of file pi_level_zero.cpp.
References _pi_queue::Context, _pi_platform::ContextsMutex, _pi_context::Devices, _pi_context::MemAllocs, PI_CALL, PI_SUCCESS, piContextRetain(), ZE_CALL, and _pi_context::ZeContext.
Referenced by piEnqueueMemBufferMap(), and piMemBufferCreate().
ZeMemFreeHelper()
static pi_result ZeMemFreeHelper (pi_context Context, void * Ptr) static
Definition at line 3588 of file pi_level_zero.cpp.
References _pi_queue::Context, ContextReleaseHelper(), _pi_platform::ContextsMutex, _pi_context::Devices, cl::sycl::detail::pi::die(), _pi_context::MemAllocs, PI_CALL, PI_SUCCESS, ZE_CALL, and _pi_context::ZeContext.
Referenced by EventRelease(), and piMemRelease().
zeParseError()
void zeParseError (ze_result_t ZeError, const char *& ErrorString) inline
Definition at line 524 of file pi_level_zero.cpp.
References ZE_ERRCASE.
Variable Documentation
CopyEngineRequested
const bool CopyEngineRequested static
Initial value:
= [] {
  int LowerCopyQueueIndex = getRangeOfAllowedCopyEngines.first;
  int UpperCopyQueueIndex = getRangeOfAllowedCopyEngines.second;
  return ((LowerCopyQueueIndex != -1) || (UpperCopyQueueIndex != -1));
}()
Definition at line 406 of file pi_level_zero.cpp.
Referenced by _pi_device::initialize().
FilterEventWaitList
const bool FilterEventWaitList static
Initial value:
= [] {
  const char *Ret = std::getenv("SYCL_PI_LEVEL_ZERO_FILTER_EVENT_WAIT_LIST");
  const bool RetVal = Ret ? std::stoi(Ret) : 1;
  return RetVal;
}()
Definition at line 1520 of file pi_level_zero.cpp.
Referenced by _pi_ze_event_list_t::createAndRetainPiZeEventList().
getRangeOfAllowedComputeEngines
const std::pair<int, int> getRangeOfAllowedComputeEngines static
Initial value:
= [] {
  const char *EnvVar = std::getenv("SYCL_PI_LEVEL_ZERO_USE_COMPUTE_ENGINE");
  if (!EnvVar)
    return std::pair<int, int>(0, 0);
  auto EnvVarValue = std::atoi(EnvVar);
  if (EnvVarValue >= 0) {
    return std::pair<int, int>(EnvVarValue, EnvVarValue);
  }
  return std::pair<int, int>(0, INT_MAX);
}()
Definition at line 355 of file pi_level_zero.cpp.
getRangeOfAllowedCopyEngines
const std::pair<int, int> getRangeOfAllowedCopyEngines static
Initial value:
= [] {
  const char *EnvVar = std::getenv("SYCL_PI_LEVEL_ZERO_USE_COPY_ENGINE");
  if (!EnvVar)
    return std::pair<int, int>(0, INT_MAX);
  std::string CopyEngineRange = EnvVar;
  auto pos = CopyEngineRange.find(":");
  if (pos == std::string::npos) {
    bool UseCopyEngine = (std::stoi(CopyEngineRange) != 0);
    if (UseCopyEngine)
      return std::pair<int, int>(0, INT_MAX);
    return std::pair<int, int>(-1, -1);
  }
  int LowerCopyEngineIndex = std::stoi(CopyEngineRange.substr(0, pos));
  int UpperCopyEngineIndex = std::stoi(CopyEngineRange.substr(pos + 1));
  if ((LowerCopyEngineIndex > UpperCopyEngineIndex) ||
      (LowerCopyEngineIndex < -1) || (UpperCopyEngineIndex < -1)) {
    zePrint("SYCL_PI_LEVEL_ZERO_USE_COPY_ENGINE: invalid value provided, "
            "default set.\n");
    LowerCopyEngineIndex = 0;
    UpperCopyEngineIndex = INT_MAX;
  }
  return std::pair<int, int>(LowerCopyEngineIndex, UpperCopyEngineIndex);
}()
Definition at line 378 of file pi_level_zero.cpp.
PiDriverGlobalOffsetExtensionFound
bool PiDriverGlobalOffsetExtensionFound = false static
Definition at line 424 of file pi_level_zero.cpp.
Referenced by _pi_platform::initialize(), and piEnqueueKernelLaunch().
PiDriverModuleProgramExtensionFound
bool PiDriverModuleProgramExtensionFound = false static
Definition at line 425 of file pi_level_zero.cpp.
Referenced by _pi_platform::initialize(), and piProgramLink().
piEventCreate
decltype(piEventCreate) piEventCreate
Definition at line 1679 of file pi_level_zero.cpp.
Referenced by cl::sycl::detail::event_impl::getNative(), and piPluginInit().
PiPlatformCachePopulated
bool PiPlatformCachePopulated = false static
Definition at line 421 of file pi_level_zero.cpp.
Referenced by piextDeviceCreateWithNativeHandle(), and piPlatformsGet().
PiPlatformsCache
std::vector<pi_platform>* PiPlatformsCache static
Initial value:
=
    new std::vector<pi_platform>
Definition at line 417 of file pi_level_zero.cpp.
Referenced by piextDeviceCreateWithNativeHandle(), piPlatformsGet(), and piTearDown().
PiPlatformsCacheMutex
sycl::detail::SpinLock* PiPlatformsCacheMutex static
Initial value:
=
    new sycl::detail::SpinLock
Definition at line 419 of file pi_level_zero.cpp.
Referenced by piextDeviceCreateWithNativeHandle(), piPlatformsGet(), and piTearDown().
UseUSMAllocator
const bool UseUSMAllocator = ShouldUseUSMAllocator() static
Definition at line 6831 of file pi_level_zero.cpp.
Referenced by piextUSMDeviceAlloc(), piextUSMHostAlloc(), piextUSMSharedAlloc(), and USMFreeHelper().
ZE_SUPPORTED_EXTENSIONS
constexpr char ZE_SUPPORTED_EXTENSIONS[] constexpr
Initial value:
=
    "cl_khr_il_program cl_khr_subgroups cl_intel_subgroups "
    "cl_intel_subgroups_short cl_intel_required_subgroup_size "
Definition at line 503 of file pi_level_zero.cpp.
Referenced by piDeviceGetInfo(), and piPlatformGetInfo().
ZeCommandListBatchComputeConfig
const zeCommandListBatchConfig ZeCommandListBatchComputeConfig static
Initial value:
= [] {
  using IsCopy = bool;
  return ZeCommandListBatchConfig(IsCopy{false});
}()
Definition at line 1011 of file pi_level_zero.cpp.
Referenced by _pi_queue::adjustBatchSizeForFullBatch(), _pi_queue::adjustBatchSizeForPartialBatch(), and _pi_queue::executeCommandList().
ZeCommandListBatchCopyConfig
const zeCommandListBatchConfig ZeCommandListBatchCopyConfig static
Initial value:
= [] {
  using IsCopy = bool;
  return ZeCommandListBatchConfig(IsCopy{true});
}()
Definition at line 1017 of file pi_level_zero.cpp.
Referenced by _pi_queue::adjustBatchSizeForFullBatch(), _pi_queue::adjustBatchSizeForPartialBatch(), and _pi_queue::executeCommandList().
ZeMaxCommandListCacheSize
const int ZeMaxCommandListCacheSize static
Initial value:
= [] {
  const char *CommandListCacheSize =
      std::getenv("SYCL_PI_LEVEL_ZERO_MAX_COMMAND_LIST_CACHE");
  pi_uint32 CommandListCacheSizeValue;
  try {
    CommandListCacheSizeValue =
        CommandListCacheSize ? std::stoi(CommandListCacheSize) : 20000;
  } catch (std::exception const &) {
    zePrint(
        "SYCL_PI_LEVEL_ZERO_MAX_COMMAND_LIST_CACHE: invalid value provided, "
        "default set.\n");
    CommandListCacheSizeValue = 20000;
  }
  return CommandListCacheSizeValue;
}()
Definition at line 881 of file pi_level_zero.cpp.
Referenced by _pi_context::getAvailableCommandList().
ZeUSMImport
class ZeUSMImportExtension ZeUSMImport static
Referenced by _pi_platform::initialize(), piMemBufferCreate(), and piMemRelease().