DPC++ Runtime: plugins/level_zero/pi_level0.cpp File Reference
pi_level0.cpp File Reference
The Plugin Interface » Level Zero Plugin
Implementation of Level Zero Plugin.
#include "pi_level0.hpp"
#include <cstdarg>
#include <cstdio>
#include <cstring>
#include <map>
#include <memory>
#include <string>
#include <thread>
#include <utility>
#include <vector>
#include <level_zero/zet_api.h>
#include <CL/sycl/detail/pi.def>
Macros
#define ZE_ERRCASE(ERR)
#define ZE_CALL(Call)
#define ZE_CALL_NOCHECK(Call) ZeCall().doCall(Call, #Call, false)
#define _PI_API(api) (PluginInit->PiFunctionTable).api = (decltype(&::api))(&api);
Enumerations
enum
Functions
static pi_result mapError (ze_result_t ZeResult)
static pi_result enqueueMemCopyHelper (pi_command_type CommandType, pi_queue Queue, void *Dst, pi_bool BlockingWrite, size_t Size, const void *Src, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
static pi_result enqueueMemCopyRectHelper (pi_command_type CommandType, pi_queue Queue, void *SrcBuffer, void *DstBuffer, const size_t *SrcOrigin, const size_t *DstOrigin, const size_t *Region, size_t SrcRowPitch, size_t SrcSlicePitch, size_t DstRowPitch, size_t DstSlicePitch, pi_bool Blocking, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
void zeParseError (ze_result_t ZeError, std::string &ErrorString)
pi_result piPlatformsGet (pi_uint32 NumEntries, pi_platform *Platforms, pi_uint32 *NumPlatforms)
pi_result piPlatformGetInfo (pi_platform Platform, pi_platform_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piextPlatformGetNativeHandle (pi_platform Platform, pi_native_handle *NativeHandle)
Gets the native handle of a PI platform object.
pi_result piextPlatformCreateWithNativeHandle (pi_native_handle NativeHandle, pi_platform *Platform)
Creates PI platform object from a native handle.
pi_result piDevicesGet (pi_platform Platform, pi_device_type DeviceType, pi_uint32 NumEntries, pi_device *Devices, pi_uint32 *NumDevices)
pi_result piDeviceRetain (pi_device Device)
pi_result piDeviceRelease (pi_device Device)
pi_result piDeviceGetInfo (pi_device Device, pi_device_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piDevicePartition (pi_device Device, const pi_device_partition_property *Properties, pi_uint32 NumDevices, pi_device *OutDevices, pi_uint32 *OutNumDevices)
pi_result piextDeviceSelectBinary (pi_device Device, pi_device_binary *Binaries, pi_uint32 NumBinaries, pi_uint32 *SelectedBinaryInd)
Selects the most appropriate device binary based on runtime information and the IR characteristics.
pi_result piextDeviceGetNativeHandle (pi_device Device, pi_native_handle *NativeHandle)
Gets the native handle of a PI device object.
pi_result piextDeviceCreateWithNativeHandle (pi_native_handle NativeHandle, pi_platform Platform, pi_device *Device)
Creates PI device object from a native handle.
pi_result piContextCreate (const pi_context_properties *Properties, pi_uint32 NumDevices, const pi_device *Devices, void(*PFnNotify)(const char *ErrInfo, const void *PrivateInfo, size_t CB, void *UserData), void *UserData, pi_context *RetContext)
pi_result piContextGetInfo (pi_context Context, pi_context_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piextContextSetExtendedDeleter (pi_context Context, pi_context_extended_deleter Function, void *UserData)
pi_result piextContextGetNativeHandle (pi_context Context, pi_native_handle *NativeHandle)
Gets the native handle of a PI context object.
pi_result piextContextCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context *Context)
Creates PI context object from a native handle.
pi_result piContextRetain (pi_context Context)
pi_result piContextRelease (pi_context Context)
pi_result piQueueCreate (pi_context Context, pi_device Device, pi_queue_properties Properties, pi_queue *Queue)
pi_result piQueueGetInfo (pi_queue Queue, pi_queue_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piQueueRetain (pi_queue Queue)
pi_result piQueueRelease (pi_queue Queue)
pi_result piQueueFinish (pi_queue Queue)
pi_result piextQueueGetNativeHandle (pi_queue Queue, pi_native_handle *NativeHandle)
Gets the native handle of a PI queue object.
pi_result piextQueueCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, pi_queue *Queue)
Creates PI queue object from a native handle.
pi_result piMemBufferCreate (pi_context Context, pi_mem_flags Flags, size_t Size, void *HostPtr, pi_mem *RetMem)
pi_result piMemGetInfo (pi_mem Mem, cl_mem_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piMemRetain (pi_mem Mem)
pi_result piMemRelease (pi_mem Mem)
pi_result piMemImageCreate (pi_context Context, pi_mem_flags Flags, const pi_image_format *ImageFormat, const pi_image_desc *ImageDesc, void *HostPtr, pi_mem *RetImage)
pi_result piextMemGetNativeHandle (pi_mem Mem, pi_native_handle *NativeHandle)
Gets the native handle of a PI mem object.
pi_result piextMemCreateWithNativeHandle (pi_native_handle NativeHandle, pi_mem *Mem)
Creates PI mem object from a native handle.
pi_result piProgramCreate (pi_context Context, const void *IL, size_t Length, pi_program *Program)
pi_result piProgramCreateWithBinary (pi_context Context, pi_uint32 NumDevices, const pi_device *DeviceList, const size_t *Lengths, const unsigned char **Binaries, pi_int32 *BinaryStatus, pi_program *RetProgram)
pi_result piclProgramCreateWithSource (pi_context Context, pi_uint32 Count, const char **Strings, const size_t *Lengths, pi_program *RetProgram)
pi_result piProgramGetInfo (pi_program Program, pi_program_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piProgramLink (pi_context Context, pi_uint32 NumDevices, const pi_device *DeviceList, const char *Options, pi_uint32 NumInputPrograms, const pi_program *InputPrograms, void(*PFnNotify)(pi_program Program, void *UserData), void *UserData, pi_program *RetProgram)
pi_result piProgramCompile (pi_program Program, pi_uint32 NumDevices, const pi_device *DeviceList, const char *Options, pi_uint32 NumInputHeaders, const pi_program *InputHeaders, const char **HeaderIncludeNames, void(*PFnNotify)(pi_program Program, void *UserData), void *UserData)
pi_result piProgramBuild (pi_program Program, pi_uint32 NumDevices, const pi_device *DeviceList, const char *Options, void(*PFnNotify)(pi_program Program, void *UserData), void *UserData)
pi_result piProgramGetBuildInfo (pi_program Program, pi_device Device, cl_program_build_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piProgramRetain (pi_program Program)
pi_result piProgramRelease (pi_program Program)
pi_result piextProgramGetNativeHandle (pi_program Program, pi_native_handle *NativeHandle)
Gets the native handle of a PI program object.
pi_result piextProgramCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, pi_program *Program)
Creates PI program object from a native handle.
pi_result piKernelCreate (pi_program Program, const char *KernelName, pi_kernel *RetKernel)
pi_result piKernelSetArg (pi_kernel Kernel, pi_uint32 ArgIndex, size_t ArgSize, const void *ArgValue)
pi_result piextKernelSetArgMemObj (pi_kernel Kernel, pi_uint32 ArgIndex, const pi_mem *ArgValue)
pi_result piextKernelSetArgSampler (pi_kernel Kernel, pi_uint32 ArgIndex, const pi_sampler *ArgValue)
pi_result piKernelGetInfo (pi_kernel Kernel, pi_kernel_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piKernelGetGroupInfo (pi_kernel Kernel, pi_device Device, pi_kernel_group_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piKernelGetSubGroupInfo (pi_kernel Kernel, pi_device Device, pi_kernel_sub_group_info ParamName, size_t InputValueSize, const void *InputValue, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
API to query information from the sub-group from a kernel.
pi_result piKernelRetain (pi_kernel Kernel)
pi_result piKernelRelease (pi_kernel Kernel)
pi_result piEnqueueKernelLaunch (pi_queue Queue, pi_kernel Kernel, pi_uint32 WorkDim, const size_t *GlobalWorkOffset, const size_t *GlobalWorkSize, const size_t *LocalWorkSize, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEventCreate (pi_context Context, pi_event *RetEvent)
pi_result piEventGetInfo (pi_event Event, pi_event_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piEventGetProfilingInfo (pi_event Event, pi_profiling_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piEventsWait (pi_uint32 NumEvents, const pi_event *EventList)
pi_result piEventSetCallback (pi_event Event, pi_int32 CommandExecCallbackType, void(*PFnNotify)(pi_event Event, pi_int32 EventCommandStatus, void *UserData), void *UserData)
pi_result piEventSetStatus (pi_event Event, pi_int32 ExecutionStatus)
pi_result piEventRetain (pi_event Event)
pi_result piEventRelease (pi_event Event)
pi_result piextEventGetNativeHandle (pi_event Event, pi_native_handle *NativeHandle)
Gets the native handle of a PI event object.
pi_result piextEventCreateWithNativeHandle (pi_native_handle NativeHandle, pi_event *Event)
Creates PI event object from a native handle.
pi_result piSamplerCreate (pi_context Context, const pi_sampler_properties *SamplerProperties, pi_sampler *RetSampler)
pi_result piSamplerGetInfo (pi_sampler Sampler, pi_sampler_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piSamplerRetain (pi_sampler Sampler)
pi_result piSamplerRelease (pi_sampler Sampler)
pi_result piEnqueueEventsWait (pi_queue Queue, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueEventsWaitWithBarrier (pi_queue Queue, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferRead (pi_queue Queue, pi_mem Src, pi_bool BlockingRead, size_t Offset, size_t Size, void *Dst, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferReadRect (pi_queue Queue, pi_mem Buffer, pi_bool BlockingRead, const size_t *BufferOffset, const size_t *HostOffset, const size_t *Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, void *Ptr, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferWrite (pi_queue Queue, pi_mem Buffer, pi_bool BlockingWrite, size_t Offset, size_t Size, const void *Ptr, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferWriteRect (pi_queue Queue, pi_mem Buffer, pi_bool BlockingWrite, const size_t *BufferOffset, const size_t *HostOffset, const size_t *Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, const void *Ptr, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferCopy (pi_queue Queue, pi_mem SrcBuffer, pi_mem DstBuffer, size_t SrcOffset, size_t DstOffset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferCopyRect (pi_queue Queue, pi_mem SrcBuffer, pi_mem DstBuffer, const size_t *SrcOrigin, const size_t *DstOrigin, const size_t *Region, size_t SrcRowPitch, size_t SrcSlicePitch, size_t DstRowPitch, size_t DstSlicePitch, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
static pi_result enqueueMemFillHelper (pi_command_type CommandType, pi_queue Queue, void *Ptr, const void *Pattern, size_t PatternSize, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferFill (pi_queue Queue, pi_mem Buffer, const void *Pattern, size_t PatternSize, size_t Offset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferMap (pi_queue Queue, pi_mem Buffer, pi_bool BlockingMap, cl_map_flags MapFlags, size_t Offset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event, void **RetMap)
pi_result piEnqueueMemUnmap (pi_queue Queue, pi_mem MemObj, void *MappedPtr, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piMemImageGetInfo (pi_mem Image, pi_image_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
static ze_image_region_t getImageRegionHelper (pi_mem Mem, const size_t *Origin, const size_t *Region)
static pi_result enqueueMemImageCommandHelper (pi_command_type CommandType, pi_queue Queue, const void *Src, void *Dst, pi_bool IsBlocking, const size_t *SrcOrigin, const size_t *DstOrigin, const size_t *Region, size_t RowPitch, size_t SlicePitch, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemImageRead (pi_queue Queue, pi_mem Image, pi_bool BlockingRead, const size_t *Origin, const size_t *Region, size_t RowPitch, size_t SlicePitch, void *Ptr, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemImageWrite (pi_queue Queue, pi_mem Image, pi_bool BlockingWrite, const size_t *Origin, const size_t *Region, size_t InputRowPitch, size_t InputSlicePitch, const void *Ptr, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemImageCopy (pi_queue Queue, pi_mem SrcImage, pi_mem DstImage, const size_t *SrcOrigin, const size_t *DstOrigin, const size_t *Region, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemImageFill (pi_queue Queue, pi_mem Image, const void *FillColor, const size_t *Origin, const size_t *Region, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piMemBufferPartition (pi_mem Buffer, pi_mem_flags Flags, pi_buffer_create_type BufferCreateType, void *BufferCreateInfo, pi_mem *RetMem)
pi_result piEnqueueNativeKernel (pi_queue Queue, void(*UserFunc)(void *), void *Args, size_t CbArgs, pi_uint32 NumMemObjects, const pi_mem *MemList, const void **ArgsMemLoc, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piextGetDeviceFunctionPointer (pi_device Device, pi_program Program, const char *FunctionName, pi_uint64 *FunctionPointerRet)
Retrieves a device function pointer to a user-defined function.
pi_result piextUSMHostAlloc (void **ResultPtr, pi_context Context, pi_usm_mem_properties *Properties, size_t Size, pi_uint32 Alignment)
Allocates host memory accessible by the device.
pi_result piextUSMDeviceAlloc (void **ResultPtr, pi_context Context, pi_device Device, pi_usm_mem_properties *Properties, size_t Size, pi_uint32 Alignment)
Allocates device memory.
pi_result piextUSMSharedAlloc (void **ResultPtr, pi_context Context, pi_device Device, pi_usm_mem_properties *Properties, size_t Size, pi_uint32 Alignment)
Allocates memory accessible on both host and device.
pi_result piextUSMFree (pi_context Context, void *Ptr)
Frees allocated USM memory.
pi_result piextKernelSetArgPointer (pi_kernel Kernel, pi_uint32 ArgIndex, size_t ArgSize, const void *ArgValue)
Sets up pointer arguments for CL kernels.
pi_result piextUSMEnqueueMemset (pi_queue Queue, void *Ptr, pi_int32 Value, size_t Count, pi_uint32 NumEventsInWaitlist, const pi_event *EventsWaitlist, pi_event *Event)
USM Memset API.
pi_result piextUSMEnqueueMemcpy (pi_queue Queue, pi_bool Blocking, void *DstPtr, const void *SrcPtr, size_t Size, pi_uint32 NumEventsInWaitlist, const pi_event *EventsWaitlist, pi_event *Event)
USM Memcpy API.
pi_result piextUSMEnqueuePrefetch (pi_queue Queue, const void *Ptr, size_t Size, pi_usm_migration_flags Flags, pi_uint32 NumEventsInWaitlist, const pi_event *EventsWaitlist, pi_event *Event)
Hint to migrate memory to the device.
pi_result piextUSMEnqueueMemAdvise (pi_queue Queue, const void *Ptr, size_t Length, pi_mem_advice Advice, pi_event *Event)
USM memadvise API to govern behavior of automatic migration mechanisms.
pi_result piextUSMGetMemAllocInfo (pi_context Context, const void *Ptr, pi_mem_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
API to query information about USM allocated pointers Valid Queries: PI_MEM_ALLOC_TYPE returns host/device/shared pi_usm_type value PI_MEM_ALLOC_BASE_PTR returns the base ptr of an allocation if the queried pointer fell inside an allocation.
pi_result piKernelSetExecInfo (pi_kernel Kernel, pi_kernel_exec_info ParamName, size_t ParamValueSize, const void *ParamValue)
API to set attributes controlling kernel execution.
pi_result piextProgramSetSpecializationConstant (pi_program Prog, pi_uint32 SpecID, size_t, const void *SpecValue)
Sets a specialization constant to a specific value.
pi_result piPluginInit (pi_plugin *PluginInit)
Variables
constexpr char ZE_SUPPORTED_EXTENSIONS []
decltype(piEventCreate) piEventCreate
std::once_flag OnceFlag
Detailed Description
Implementation of Level Zero Plugin.
Definition in file pi_level0.cpp.
Macro Definition Documentation
_PI_API
#define _PI_API (api) (PluginInit->PiFunctionTable).api = (decltype(&::api))(&api);
ZE_CALL
#define ZE_CALL (Call)
Value:
if (auto Result = ZeCall().doCall(Call, #Call, true))                        \
    return mapError(Result);
Definition at line 349 of file pi_level0.cpp.
Referenced by _pi_device::createCommandList(), enqueueMemCopyHelper(), enqueueMemCopyRectHelper(), enqueueMemFillHelper(), enqueueMemImageCommandHelper(), _pi_queue::executeCommandList(), _pi_device::initialize(), piDeviceGetInfo(), piDevicePartition(), piDeviceRelease(), piDevicesGet(), piEnqueueEventsWaitWithBarrier(), piEnqueueKernelLaunch(), piEnqueueMemBufferMap(), piEnqueueMemUnmap(), piEventCreate(), piEventGetProfilingInfo(), piEventRelease(), piEventsWait(), piextGetDeviceFunctionPointer(), piextKernelSetArgMemObj(), piextKernelSetArgSampler(), piextUSMDeviceAlloc(), piextUSMEnqueueMemAdvise(), piextUSMEnqueuePrefetch(), piextUSMFree(), piextUSMGetMemAllocInfo(), piextUSMHostAlloc(), piextUSMSharedAlloc(), piKernelCreate(), piKernelGetGroupInfo(), piKernelGetInfo(), piKernelSetArg(), piKernelSetExecInfo(), piMemBufferCreate(), piMemImageCreate(), piMemRelease(), piPlatformsGet(), piProgramBuild(), piProgramGetBuildInfo(), piProgramGetInfo(), piQueueCreate(), piQueueFinish(), piQueueRelease(), piSamplerCreate(), and piSamplerRelease().
ZE_CALL_NOCHECK
#define ZE_CALL_NOCHECK (Call) ZeCall().doCall(Call, #Call, false)
Definition at line 352 of file pi_level0.cpp.
Referenced by piEventGetInfo(), and piPlatformsGet().
ZE_ERRCASE
#define ZE_ERRCASE (ERR)
Value:
case ERR:                                                                    \
    ErrorString = "" #ERR;                                                     \
    break;
Referenced by zeParseError().
Enumeration Type Documentation
anonymous enum
anonymous enum
Definition at line 31 of file pi_level0.cpp.
Function Documentation
enqueueMemCopyHelper()
static pi_result enqueueMemCopyHelper (pi_command_type CommandType, pi_queue Queue, void * Dst, pi_bool BlockingWrite, size_t Size, const void * Src, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event) static
Definition at line 2685 of file pi_level0.cpp.
References _pi_queue::Context, _pi_device::createCommandList(), _pi_event::createZeEventList(), _pi_event::deleteZeEventList(), _pi_context::Device, _pi_queue::executeCommandList(), PI_SUCCESS, piEventCreate, and ZE_CALL.
Referenced by mapError(), piEnqueueMemBufferCopy(), piEnqueueMemBufferRead(), piEnqueueMemBufferWrite(), and piextUSMEnqueueMemcpy().
enqueueMemCopyRectHelper()
static pi_result enqueueMemCopyRectHelper (pi_command_type CommandType, pi_queue Queue, void * SrcBuffer, void * DstBuffer, const size_t * SrcOrigin, const size_t * DstOrigin, const size_t * Region, size_t SrcRowPitch, size_t SrcSlicePitch, size_t DstRowPitch, size_t DstSlicePitch, pi_bool Blocking, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event) static
Definition at line 2736 of file pi_level0.cpp.
References _pi_queue::Context, _pi_device::createCommandList(), _pi_event::createZeEventList(), _pi_event::deleteZeEventList(), _pi_context::Device, _pi_queue::executeCommandList(), pi_cast(), PI_SUCCESS, piEventCreate, cl::sycl::detail::uint32_t, and ZE_CALL.
Referenced by mapError(), piEnqueueMemBufferCopyRect(), piEnqueueMemBufferReadRect(), and piEnqueueMemBufferWriteRect().
enqueueMemFillHelper()
static pi_result enqueueMemFillHelper (pi_command_type CommandType, pi_queue Queue, void * Ptr, const void * Pattern, size_t PatternSize, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event) static
Definition at line 2903 of file pi_level0.cpp.
References _pi_queue::Context, _pi_device::createCommandList(), _pi_event::createZeEventList(), _pi_event::deleteZeEventList(), _pi_context::Device, _pi_queue::executeCommandList(), PI_SUCCESS, piEventCreate, and ZE_CALL.
Referenced by piEnqueueMemBufferFill(), and piextUSMEnqueueMemset().
enqueueMemImageCommandHelper()
static pi_result enqueueMemImageCommandHelper (pi_command_type CommandType, pi_queue Queue, const void * Src, void * Dst, pi_bool IsBlocking, const size_t * SrcOrigin, const size_t * DstOrigin, const size_t * Region, size_t RowPitch, size_t SlicePitch, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event) static
Definition at line 3159 of file pi_level0.cpp.
References _pi_queue::Context, _pi_device::createCommandList(), _pi_event::createZeEventList(), _pi_event::deleteZeEventList(), _pi_context::Device, _pi_queue::executeCommandList(), getImageRegionHelper(), _pi_mem::getZeHandle(), _pi_mem::isImage(), pi_cast(), PI_COMMAND_TYPE_IMAGE_COPY, PI_COMMAND_TYPE_IMAGE_READ, PI_COMMAND_TYPE_IMAGE_WRITE, PI_INVALID_OPERATION, PI_SUCCESS, piEventCreate, ZE_CALL, and _pi_image::ZeImageDesc.
Referenced by piEnqueueMemImageCopy(), piEnqueueMemImageRead(), and piEnqueueMemImageWrite().
getImageRegionHelper()
static ze_image_region_t getImageRegionHelper (pi_mem Mem, const size_t * Origin, const size_t * Region) static
Definition at line 3121 of file pi_level0.cpp.
References _pi_mem::isImage(), pi_cast(), cl::sycl::detail::uint32_t, and _pi_image::ZeImageDesc.
Referenced by enqueueMemImageCommandHelper().
mapError()
static pi_result mapError (ze_result_t ZeResult) static
Definition at line 242 of file pi_level0.cpp.
References enqueueMemCopyHelper(), enqueueMemCopyRectHelper(), PI_BUILD_PROGRAM_FAILURE, PI_DEVICE_NOT_FOUND, PI_ERROR_UNKNOWN, PI_INVALID_BINARY, PI_INVALID_EVENT, PI_INVALID_KERNEL_NAME, PI_INVALID_OPERATION, PI_INVALID_PLATFORM, PI_INVALID_VALUE, PI_INVALID_WORK_GROUP_SIZE, and PI_SUCCESS.
Referenced by piPlatformsGet().
piclProgramCreateWithSource()
pi_result piclProgramCreateWithSource (pi_context Context, pi_uint32 Count, const char ** Strings, const size_t * Lengths, pi_program * RetProgram)
Definition at line 1724 of file pi_level0.cpp.
References PI_INVALID_OPERATION.
piContextCreate()
pi_result piContextCreate (const pi_context_properties * Properties, pi_uint32 NumDevices, const pi_device * Devices, void(*)(const char *ErrInfo, const void *PrivateInfo, size_t CB, void *UserData) PFnNotify, void * UserData, pi_context * RetContext)
Definition at line 1204 of file pi_level0.cpp.
References PI_ERROR_UNKNOWN, PI_INVALID_VALUE, PI_OUT_OF_HOST_MEMORY, and PI_SUCCESS.
piContextGetInfo()
pi_result piContextGetInfo (pi_context Context, pi_context_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 1232 of file pi_level0.cpp.
References _pi_context::Device, die(), PI_CONTEXT_INFO_DEVICES, PI_CONTEXT_INFO_NUM_DEVICES, PI_CONTEXT_INFO_REFERENCE_COUNT, PI_SUCCESS, and _pi_object::RefCount.
Referenced by cl::sycl::detail::context_impl::context_impl(), cl::sycl::detail::createBinaryProgram(), cl::sycl::detail::get_context_info< param >::get(), cl::sycl::detail::getFirstDevice(), and piPluginInit().
piContextRelease()
pi_result piContextRelease (pi_context Context)
Definition at line 1281 of file pi_level0.cpp.
References PI_SUCCESS, and _pi_object::RefCount.
Referenced by piPluginInit(), and cl::sycl::detail::context_impl::~context_impl().
piContextRetain()
pi_result piContextRetain (pi_context Context)
Definition at line 1274 of file pi_level0.cpp.
References PI_SUCCESS, and _pi_object::RefCount.
Referenced by cl::sycl::detail::context_impl::context_impl(), cl::sycl::detail::context_impl::get(), and piPluginInit().
piDeviceGetInfo()
pi_result piDeviceGetInfo (pi_device Device, pi_device_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 666 of file pi_level0.cpp.
References _pi_device::IsSubDevice, PI_DEVICE_AFFINITY_DOMAIN_NEXT_PARTITIONABLE, PI_DEVICE_EXEC_CAPABILITIES_NATIVE_KERNEL, PI_DEVICE_INFO_ADDRESS_BITS, PI_DEVICE_INFO_AVAILABLE, PI_DEVICE_INFO_BUILT_IN_KERNELS, PI_DEVICE_INFO_COMPILER_AVAILABLE, PI_DEVICE_INFO_DOUBLE_FP_CONFIG, PI_DEVICE_INFO_DRIVER_VERSION, PI_DEVICE_INFO_ENDIAN_LITTLE, PI_DEVICE_INFO_ERROR_CORRECTION_SUPPORT, PI_DEVICE_INFO_EXECUTION_CAPABILITIES, PI_DEVICE_INFO_EXTENSIONS, PI_DEVICE_INFO_GLOBAL_MEM_CACHE_SIZE, PI_DEVICE_INFO_GLOBAL_MEM_CACHE_TYPE, PI_DEVICE_INFO_GLOBAL_MEM_CACHELINE_SIZE, PI_DEVICE_INFO_GLOBAL_MEM_SIZE, PI_DEVICE_INFO_HALF_FP_CONFIG, PI_DEVICE_INFO_HOST_UNIFIED_MEMORY, PI_DEVICE_INFO_IL_VERSION, PI_DEVICE_INFO_IMAGE2D_MAX_HEIGHT, PI_DEVICE_INFO_IMAGE2D_MAX_WIDTH, PI_DEVICE_INFO_IMAGE3D_MAX_DEPTH, PI_DEVICE_INFO_IMAGE3D_MAX_HEIGHT, PI_DEVICE_INFO_IMAGE3D_MAX_WIDTH, PI_DEVICE_INFO_IMAGE_MAX_ARRAY_SIZE, PI_DEVICE_INFO_IMAGE_MAX_BUFFER_SIZE, PI_DEVICE_INFO_IMAGE_SUPPORT, PI_DEVICE_INFO_LINKER_AVAILABLE, PI_DEVICE_INFO_LOCAL_MEM_SIZE, PI_DEVICE_INFO_LOCAL_MEM_TYPE, PI_DEVICE_INFO_MAX_CLOCK_FREQUENCY, PI_DEVICE_INFO_MAX_COMPUTE_UNITS, PI_DEVICE_INFO_MAX_CONSTANT_ARGS, PI_DEVICE_INFO_MAX_CONSTANT_BUFFER_SIZE, PI_DEVICE_INFO_MAX_MEM_ALLOC_SIZE, PI_DEVICE_INFO_MAX_NUM_SUB_GROUPS, PI_DEVICE_INFO_MAX_PARAMETER_SIZE, PI_DEVICE_INFO_MAX_READ_IMAGE_ARGS, PI_DEVICE_INFO_MAX_SAMPLERS, PI_DEVICE_INFO_MAX_WORK_GROUP_SIZE, PI_DEVICE_INFO_MAX_WORK_ITEM_DIMENSIONS, PI_DEVICE_INFO_MAX_WORK_ITEM_SIZES, PI_DEVICE_INFO_MAX_WRITE_IMAGE_ARGS, PI_DEVICE_INFO_MEM_BASE_ADDR_ALIGN, PI_DEVICE_INFO_NAME, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_CHAR, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_DOUBLE, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_FLOAT, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_HALF, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_INT, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_LONG, PI_DEVICE_INFO_NATIVE_VECTOR_WIDTH_SHORT, PI_DEVICE_INFO_OPENCL_C_VERSION, PI_DEVICE_INFO_PARENT_DEVICE, PI_DEVICE_INFO_PARTITION_AFFINITY_DOMAIN, PI_DEVICE_INFO_PARTITION_MAX_SUB_DEVICES, PI_DEVICE_INFO_PARTITION_PROPERTIES, PI_DEVICE_INFO_PARTITION_TYPE, PI_DEVICE_INFO_PLATFORM, PI_DEVICE_INFO_PREFERRED_INTEROP_USER_SYNC, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_CHAR, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_DOUBLE, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_FLOAT, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_HALF, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_INT, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_LONG, PI_DEVICE_INFO_PREFERRED_VECTOR_WIDTH_SHORT, PI_DEVICE_INFO_PRINTF_BUFFER_SIZE, PI_DEVICE_INFO_PROFILE, PI_DEVICE_INFO_PROFILING_TIMER_RESOLUTION, PI_DEVICE_INFO_QUEUE_PROPERTIES, PI_DEVICE_INFO_REFERENCE_COUNT, PI_DEVICE_INFO_SINGLE_FP_CONFIG, PI_DEVICE_INFO_SUB_GROUP_INDEPENDENT_FORWARD_PROGRESS, PI_DEVICE_INFO_SUB_GROUP_SIZES_INTEL, PI_DEVICE_INFO_TYPE, PI_DEVICE_INFO_USM_CROSS_SHARED_SUPPORT, PI_DEVICE_INFO_USM_DEVICE_SUPPORT, PI_DEVICE_INFO_USM_HOST_SUPPORT, PI_DEVICE_INFO_USM_SINGLE_SHARED_SUPPORT, PI_DEVICE_INFO_USM_SYSTEM_SHARED_SUPPORT, PI_DEVICE_INFO_VENDOR, PI_DEVICE_INFO_VENDOR_ID, PI_DEVICE_INFO_VERSION, PI_DEVICE_LOCAL_MEM_TYPE_LOCAL, PI_DEVICE_MEM_CACHE_TYPE_READ_WRITE_CACHE, PI_DEVICE_PARTITION_BY_AFFINITY_DOMAIN, PI_DEVICE_TYPE_GPU, PI_ERROR_UNKNOWN, PI_FP_DENORM, PI_FP_FMA, PI_FP_INF_NAN, PI_FP_ROUND_TO_INF, PI_FP_ROUND_TO_NEAREST, PI_FP_ROUND_TO_ZERO, PI_INVALID_VALUE, PI_OUT_OF_HOST_MEMORY, PI_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE, PI_QUEUE_PROFILING_ENABLE, PI_SUCCESS, PI_USM_ACCESS, PI_USM_ATOMIC_ACCESS, PI_USM_CONCURRENT_ACCESS, PI_USM_CONCURRENT_ATOMIC_ACCESS, _pi_device::Platform, _pi_object::RefCount, cl::sycl::detail::uint32_t, ZE_CALL, ZE_SUPPORTED_EXTENSIONS, _pi_device::ZeDevice, _pi_device::ZeDeviceComputeProperties, _pi_device::ZeDeviceProperties, _pi_platform::ZeDriverApiVersion, and _pi_platform::ZeDriverVersion.
Referenced by cl::sycl::detail::device_impl::device_impl(), cl::sycl::detail::get_device_info< T, param >::get(), cl::sycl::detail::get_device_info< platform, param >::get(), cl::sycl::detail::get_device_info< string_class, param >::get(), cl::sycl::detail::get_device_info< id< 3 >, param >::get(), cl::sycl::detail::get_device_info< vector_class< info::fp_config >, param >::get(), cl::sycl::detail::get_device_info< vector_class< info::fp_config >, info::device::single_fp_config >::get(), cl::sycl::detail::get_device_info< bool, info::device::queue_profiling >::get(), cl::sycl::detail::get_device_info< vector_class< info::execution_capability >, info::device::execution_capabilities >::get(), cl::sycl::detail::get_device_info< vector_class< info::partition_property >, info::device::partition_properties >::get(), cl::sycl::detail::get_device_info< vector_class< info::partition_affinity_domain >, info::device::partition_affinity_domains >::get(), cl::sycl::detail::get_device_info< info::partition_affinity_domain, info::device::partition_type_affinity_domain >::get(), cl::sycl::detail::get_device_info< info::partition_property, info::device::partition_type_property >::get(), cl::sycl::detail::get_device_info< vector_class< size_t >, info::device::sub_group_sizes >::get(), cl::sycl::detail::get_device_info< id< 3 >, info::device::max_work_item_sizes >::get(), cl::sycl::detail::get_device_info< device, info::device::parent_device >::get(), cl::sycl::detail::get_device_info< bool, info::device::usm_device_allocations >::get(), cl::sycl::detail::get_device_info< bool, info::device::usm_host_allocations >::get(), cl::sycl::detail::get_device_info< bool, info::device::usm_shared_allocations >::get(), cl::sycl::detail::get_device_info< bool, info::device::usm_restricted_shared_allocations >::get(), cl::sycl::detail::get_device_info< bool, info::device::usm_system_allocator >::get(), cl::sycl::detail::ProgramManager::getProgramBuildLog(), cl::sycl::detail::enqueue_kernel_launch::handleInvalidWorkGroupSize(), cl::sycl::detail::enqueue_kernel_launch::handleInvalidWorkItemSize(), and piPluginInit().
piDevicePartition()
pi_result piDevicePartition (pi_device Device, const pi_device_partition_property * Properties, pi_uint32 NumDevices, pi_device * OutDevices, pi_uint32 * OutNumDevices)
Definition at line 1105 of file pi_level0.cpp.
References _pi_device::initialize(), PI_DEVICE_AFFINITY_DOMAIN_NEXT_PARTITIONABLE, PI_DEVICE_PARTITION_BY_AFFINITY_DOMAIN, PI_ERROR_UNKNOWN, PI_INVALID_OPERATION, PI_INVALID_VALUE, PI_OUT_OF_HOST_MEMORY, PI_SUCCESS, _pi_device::Platform, cl::sycl::detail::uint32_t, ZE_CALL, and _pi_device::ZeDevice.
Referenced by cl::sycl::detail::device_impl::create_sub_devices(), and piPluginInit().
piDeviceRelease()
pi_result piDeviceRelease (pi_device Device)
Definition at line 652 of file pi_level0.cpp.
References PI_SUCCESS, _pi_object::RefCount, ZE_CALL, and _pi_device::ZeCommandListInit.
Referenced by piPluginInit(), and cl::sycl::detail::device_impl::~device_impl().
piDeviceRetain()
pi_result piDeviceRetain (pi_device Device)
Definition at line 642 of file pi_level0.cpp.
References _pi_device::IsSubDevice, PI_SUCCESS, and _pi_object::RefCount.
Referenced by cl::sycl::detail::device_impl::device_impl(), cl::sycl::detail::device_impl::get(), and piPluginInit().
piDevicesGet()
pi_result piDevicesGet (pi_platform Platform, pi_device_type DeviceType, pi_uint32 NumEntries, pi_device * Devices, pi_uint32 * NumDevices)
Definition at line 594 of file pi_level0.cpp.
References _pi_device::initialize(), PI_DEVICE_TYPE_DEFAULT, PI_DEVICE_TYPE_GPU, PI_ERROR_UNKNOWN, PI_OUT_OF_HOST_MEMORY, PI_SUCCESS, cl::sycl::detail::uint32_t, ZE_CALL, and _pi_platform::ZeDriver.
piEnqueueEventsWait()
pi_result piEnqueueEventsWait (pi_queue Queue, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 2606 of file pi_level0.cpp.
References die().
Referenced by cl::sycl::detail::DispatchNativeKernel(), piPluginInit(), and cl::sycl::detail::Command::waitForEvents().
piEnqueueEventsWaitWithBarrier()
pi_result piEnqueueEventsWaitWithBarrier (pi_queue Queue, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 2613 of file pi_level0.cpp.
References _pi_queue::Context, _pi_device::createCommandList(), _pi_event::createZeEventList(), _pi_event::deleteZeEventList(), _pi_context::Device, PI_COMMAND_TYPE_USER, PI_SUCCESS, piEventCreate, and ZE_CALL.
Referenced by cl::sycl::detail::DispatchNativeKernel(), and piPluginInit().
piEnqueueKernelLaunch()
pi_result piEnqueueKernelLaunch (pi_queue Queue, pi_kernel Kernel, pi_uint32 WorkDim, const size_t * GlobalWorkOffset, const size_t * GlobalWorkSize, const size_t * LocalWorkSize, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 2181 of file pi_level0.cpp.
References _pi_queue::Context, _pi_program::Context, _pi_device::createCommandList(), _pi_event::createZeEventList(), _pi_event::deleteZeEventList(), _pi_context::Device, _pi_queue::executeCommandList(), pi_cast(), PI_COMMAND_TYPE_NDRANGE_KERNEL, PI_INVALID_VALUE, PI_SUCCESS, piEventCreate, _pi_kernel::Program, cl::sycl::detail::uint32_t, ZE_CALL, and _pi_kernel::ZeKernel.
Referenced by piPluginInit(), and cl::sycl::detail::ReverseRangeDimensionsForKernel().
piEnqueueMemBufferCopy()
pi_result piEnqueueMemBufferCopy (pi_queue Queue, pi_mem SrcBuffer, pi_mem DstBuffer, size_t SrcOffset, size_t DstOffset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 2865 of file pi_level0.cpp.
References enqueueMemCopyHelper(), _pi_mem::getZeHandle(), and PI_COMMAND_TYPE_MEM_BUFFER_COPY.
Referenced by cl::sycl::detail::copyD2D(), and piPluginInit().
piEnqueueMemBufferCopyRect()
pi_result piEnqueueMemBufferCopyRect (pi_queue Queue, pi_mem SrcBuffer, pi_mem DstBuffer, const size_t * SrcOrigin, const size_t * DstOrigin, const size_t * Region, size_t SrcRowPitch, size_t SrcSlicePitch, size_t DstRowPitch, size_t DstSlicePitch, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 2883 of file pi_level0.cpp.
References enqueueMemCopyRectHelper(), _pi_mem::getZeHandle(), and PI_COMMAND_TYPE_MEM_BUFFER_COPY_RECT.
Referenced by cl::sycl::detail::copyD2D(), and piPluginInit().
piEnqueueMemBufferFill()
pi_result piEnqueueMemBufferFill (pi_queue Queue, pi_mem Buffer, const void * Pattern, size_t PatternSize, size_t Offset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 2960 of file pi_level0.cpp.
References enqueueMemFillHelper(), _pi_mem::getZeHandle(), and PI_COMMAND_TYPE_MEM_BUFFER_FILL.
Referenced by cl::sycl::detail::MemoryManager::fill(), and piPluginInit().
piEnqueueMemBufferMap()
pi_result piEnqueueMemBufferMap (pi_queue Queue, pi_mem Buffer, pi_bool BlockingMap, cl_map_flags MapFlags, size_t Offset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event, void ** RetMap)
Definition at line 2975 of file pi_level0.cpp.
References _pi_mem::addMapping(), _pi_queue::Context, _pi_device::createCommandList(), _pi_event::createZeEventList(), _pi_event::deleteZeEventList(), _pi_context::Device, _pi_queue::executeCommandList(), _pi_mem::getZeHandle(), _pi_mem::MapHostPtr, PI_COMMAND_TYPE_MEM_BUFFER_MAP, PI_SUCCESS, piEventCreate, _pi_device::Platform, ZE_CALL, and _pi_platform::ZeDriver.
piEnqueueMemBufferRead()
pi_result piEnqueueMemBufferRead (pi_queue Queue, pi_mem Src, pi_bool BlockingRead, size_t Offset, size_t Size, void * Dst, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 2653 of file pi_level0.cpp.
References enqueueMemCopyHelper(), _pi_mem::getZeHandle(), and PI_COMMAND_TYPE_MEM_BUFFER_READ.
Referenced by cl::sycl::detail::copyD2H(), and piPluginInit().
piEnqueueMemBufferReadRect()
pi_result piEnqueueMemBufferReadRect (pi_queue Queue, pi_mem Buffer, pi_bool BlockingRead, const size_t * BufferOffset, const size_t * HostOffset, const size_t * Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, void * Ptr, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 2666 of file pi_level0.cpp.
References enqueueMemCopyRectHelper(), _pi_mem::getZeHandle(), and PI_COMMAND_TYPE_MEM_BUFFER_READ_RECT.
Referenced by cl::sycl::detail::copyD2H(), and piPluginInit().
piEnqueueMemBufferWrite()
pi_result piEnqueueMemBufferWrite (pi_queue Queue, pi_mem Buffer, pi_bool BlockingWrite, size_t Offset, size_t Size, const void * Ptr, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 2833 of file pi_level0.cpp.
References enqueueMemCopyHelper(), _pi_mem::getZeHandle(), and PI_COMMAND_TYPE_MEM_BUFFER_WRITE.
Referenced by cl::sycl::detail::copyH2D(), and piPluginInit().
piEnqueueMemBufferWriteRect()
pi_result piEnqueueMemBufferWriteRect (pi_queue Queue, pi_mem Buffer, pi_bool BlockingWrite, const size_t * BufferOffset, const size_t * HostOffset, const size_t * Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, const void * Ptr, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 2849 of file pi_level0.cpp.
References enqueueMemCopyRectHelper(), _pi_mem::getZeHandle(), and PI_COMMAND_TYPE_MEM_BUFFER_WRITE_RECT.
Referenced by cl::sycl::detail::copyH2D(), and piPluginInit().
piEnqueueMemImageCopy()
pi_result piEnqueueMemImageCopy (pi_queue Queue, pi_mem SrcImage, pi_mem DstImage, const size_t * SrcOrigin, const size_t * DstOrigin, const size_t * Region, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 3309 of file pi_level0.cpp.
References enqueueMemImageCommandHelper(), and PI_COMMAND_TYPE_IMAGE_COPY.
Referenced by cl::sycl::detail::copyD2D(), and piPluginInit().
piEnqueueMemImageFill()
pi_result piEnqueueMemImageFill (pi_queue Queue, pi_mem Image, const void * FillColor, const size_t * Origin, const size_t * Region, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 3325 of file pi_level0.cpp.
References die().
Referenced by cl::sycl::detail::MemoryManager::fill(), and piPluginInit().
piEnqueueMemImageRead()
pi_result piEnqueueMemImageRead (pi_queue Queue, pi_mem Image, pi_bool BlockingRead, const size_t * Origin, const size_t * Region, size_t RowPitch, size_t SlicePitch, void * Ptr, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 3272 of file pi_level0.cpp.
References enqueueMemImageCommandHelper(), and PI_COMMAND_TYPE_IMAGE_READ.
Referenced by cl::sycl::detail::copyD2H(), and piPluginInit().
piEnqueueMemImageWrite()
pi_result piEnqueueMemImageWrite (pi_queue Queue, pi_mem Image, pi_bool BlockingWrite, const size_t * Origin, const size_t * Region, size_t InputRowPitch, size_t InputSlicePitch, const void * Ptr, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 3290 of file pi_level0.cpp.
References enqueueMemImageCommandHelper(), and PI_COMMAND_TYPE_IMAGE_WRITE.
Referenced by cl::sycl::detail::copyH2D(), and piPluginInit().
piEnqueueMemUnmap()
pi_result piEnqueueMemUnmap (pi_queue Queue, pi_mem MemObj, void * MappedPtr, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 3050 of file pi_level0.cpp.
References _pi_queue::Context, _pi_device::createCommandList(), _pi_event::createZeEventList(), _pi_event::deleteZeEventList(), _pi_context::Device, _pi_queue::executeCommandList(), _pi_mem::getZeHandle(), _pi_mem::MapHostPtr, _pi_mem::Mapping::Offset, PI_COMMAND_TYPE_MEM_BUFFER_UNMAP, PI_SUCCESS, piEventCreate, _pi_mem::removeMapping(), _pi_mem::Mapping::Size, and ZE_CALL.
Referenced by piPluginInit(), and cl::sycl::detail::MemoryManager::unmap().
piEnqueueNativeKernel()
pi_result piEnqueueNativeKernel (pi_queue Queue, void(*)(void *) UserFunc, void * Args, size_t CbArgs, pi_uint32 NumMemObjects, const pi_mem * MemList, const void ** ArgsMemLoc, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 3368 of file pi_level0.cpp.
References die().
Referenced by cl::sycl::detail::DispatchNativeKernel(), and piPluginInit().
piEventCreate()
pi_result piEventCreate (pi_context Context, pi_event * RetEvent)
Definition at line 2289 of file pi_level0.cpp.
References _pi_context::getFreeSlotInExistingOrNewPool(), PI_COMMAND_TYPE_USER, PI_ERROR_UNKNOWN, PI_OUT_OF_HOST_MEMORY, PI_SUCCESS, and ZE_CALL.
piEventGetInfo()
pi_result piEventGetInfo (pi_event Event, pi_event_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 2314 of file pi_level0.cpp.
References _pi_event::CommandType, _pi_queue::Context, PI_EVENT_INFO_COMMAND_EXECUTION_STATUS, PI_EVENT_INFO_COMMAND_QUEUE, PI_EVENT_INFO_COMMAND_TYPE, PI_EVENT_INFO_CONTEXT, PI_EVENT_INFO_REFERENCE_COUNT, PI_INVALID_VALUE, PI_SUCCESS, _pi_event::Queue, _pi_object::RefCount, ZE_CALL_NOCHECK, and _pi_event::ZeEvent.
Referenced by cl::sycl::detail::event_impl::event_impl(), cl::sycl::detail::get_event_info< Param >::get(), and piPluginInit().
piEventGetProfilingInfo()
pi_result piEventGetProfilingInfo (pi_event Event, pi_profiling_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 2351 of file pi_level0.cpp.
References _pi_queue::Context, _pi_context::Device, PI_INVALID_VALUE, PI_PROFILING_INFO_COMMAND_END, PI_PROFILING_INFO_COMMAND_QUEUED, PI_PROFILING_INFO_COMMAND_START, PI_PROFILING_INFO_COMMAND_SUBMIT, PI_SUCCESS, _pi_event::Queue, ZE_CALL, _pi_device::ZeDeviceProperties, and _pi_event::ZeEvent.
Referenced by cl::sycl::detail::get_event_profiling_info< Param >::get(), and piPluginInit().
piEventRelease()
pi_result piEventRelease (pi_event Event)
Definition at line 2429 of file pi_level0.cpp.
References _pi_event::CommandData, _pi_event::CommandType, _pi_queue::Context, _pi_event::Context, _pi_context::decrementAliveEventsInPool(), _pi_context::Device, PI_COMMAND_TYPE_MEM_BUFFER_UNMAP, PI_SUCCESS, _pi_device::Platform, _pi_event::Queue, _pi_object::RefCount, ZE_CALL, _pi_event::ZeCommandList, _pi_platform::ZeDriver, _pi_event::ZeEvent, and _pi_event::ZeEventPool.
Referenced by piPluginInit(), and cl::sycl::detail::event_impl::~event_impl().
piEventRetain()
pi_result piEventRetain (pi_event Event)
Definition at line 2424 of file pi_level0.cpp.
References PI_SUCCESS, and _pi_object::RefCount.
Referenced by cl::sycl::detail::MemoryManager::allocateInteropMemObject(), cl::sycl::detail::event_impl::event_impl(), cl::sycl::detail::event_impl::get(), and piPluginInit().
piEventSetCallback()
pi_result piEventSetCallback (pi_event Event, pi_int32 CommandExecCallbackType, void(*)(pi_event Event, pi_int32 EventCommandStatus, void *UserData) PFnNotify, void * UserData)
Definition at line 2410 of file pi_level0.cpp.
References die(), and PI_SUCCESS.
piEventSetStatus()
pi_result piEventSetStatus (pi_event Event, pi_int32 ExecutionStatus)
Definition at line 2419 of file pi_level0.cpp.
References die(), and PI_SUCCESS.
Referenced by piPluginInit().
piEventsWait()
pi_result piEventsWait (pi_uint32 NumEvents, const pi_event * EventList)
Definition at line 2387 of file pi_level0.cpp.
References PI_INVALID_EVENT, PI_SUCCESS, cl::sycl::detail::uint32_t, ZE_CALL, _pi_event::ZeCommandList, and _pi_event::ZeEvent.
Referenced by cl::sycl::detail::DispatchNativeKernel(), piPluginInit(), cl::sycl::detail::waitForEvents(), cl::sycl::detail::Command::waitForEvents(), and cl::sycl::detail::event_impl::waitInternal().
piextContextCreateWithNativeHandle()
pi_result piextContextCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context * context)
Creates PI context object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI context from.
context is the PI context created from the native handle.
Definition at line 1268 of file pi_level0.cpp.
References die(), and PI_SUCCESS.
piextContextGetNativeHandle()
pi_result piextContextGetNativeHandle (pi_context context, pi_native_handle * nativeHandle)
Gets the native handle of a PI context object.
Parameters
context is the PI context to get the native handle of.
nativeHandle is the native handle of context.
Definition at line 1262 of file pi_level0.cpp.
References die(), and PI_SUCCESS.
piextContextSetExtendedDeleter()
pi_result piextContextSetExtendedDeleter (pi_context Context, pi_context_extended_deleter Function, void * UserData)
Definition at line 1255 of file pi_level0.cpp.
References die(), and PI_SUCCESS.
Referenced by cl::sycl::detail::pi::contextSetExtendedDeleter(), and piPluginInit().
piextDeviceCreateWithNativeHandle()
pi_result piextDeviceCreateWithNativeHandle (pi_native_handle nativeHandle, pi_platform platform, pi_device * device)
Creates PI device object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI device from.
platform is the platform of the device.
device is the PI device created from the native handle.
Definition at line 1191 of file pi_level0.cpp.
References pi_cast().
piextDeviceGetNativeHandle()
pi_result piextDeviceGetNativeHandle (pi_device device, pi_native_handle * nativeHandle)
Gets the native handle of a PI device object.
Parameters
device is the PI device to get the native handle of.
nativeHandle is the native handle of device.
Definition at line 1180 of file pi_level0.cpp.
References pi_cast(), PI_SUCCESS, and _pi_device::ZeDevice.
piextDeviceSelectBinary()
pi_result piextDeviceSelectBinary (pi_device Device, pi_device_binary * Binaries, pi_uint32 NumBinaries, pi_uint32 * SelectedBinaryInd)
Selects the most appropriate device binary based on runtime information and the IR characteristics.
Definition at line 1162 of file pi_level0.cpp.
References PI_SUCCESS.
piextEventCreateWithNativeHandle()
pi_result piextEventCreateWithNativeHandle (pi_native_handle nativeHandle, pi_event * event)
Creates PI event object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI event from.
event is the PI event created from the native handle.
Definition at line 2461 of file pi_level0.cpp.
References die(), and PI_SUCCESS.
piextEventGetNativeHandle()
pi_result piextEventGetNativeHandle (pi_event event, pi_native_handle * nativeHandle)
Gets the native handle of a PI event object.
Parameters
event is the PI event to get the native handle of.
nativeHandle is the native handle of event.
Definition at line 2455 of file pi_level0.cpp.
References die(), and PI_SUCCESS.
Referenced by cl::sycl::detail::event_impl::getNative(), and piPluginInit().
piextGetDeviceFunctionPointer()
pi_result piextGetDeviceFunctionPointer (pi_device device, pi_program program, const char * function_name, pi_uint64 * function_pointer_ret)
Retrieves a device function pointer to a user-defined function.
function_name.
function_pointer_ret is set to 0 if query failed.
program must be built before calling this API.
device must present in the list of devices returned by get_device method for
program.
Definition at line 3381 of file pi_level0.cpp.
References PI_SUCCESS, ZE_CALL, and _pi_program::ZeModule.
piextKernelSetArgMemObj()
pi_result piextKernelSetArgMemObj (pi_kernel Kernel, pi_uint32 ArgIndex, const pi_mem * ArgValue)
Definition at line 2011 of file pi_level0.cpp.
References PI_SUCCESS, ZE_CALL, and _pi_kernel::ZeKernel.
piextKernelSetArgPointer()
pi_result piextKernelSetArgPointer (pi_kernel kernel, pi_uint32 arg_index, size_t arg_size, const void * arg_value)
Sets up pointer arguments for CL kernels.
An extra indirection is required due to CL argument conventions.
Parameters
kernel is the kernel to be launched
arg_index is the index of the kernel argument
arg_size is the size in bytes of the argument (ignored in CL)
arg_value is the pointer argument
Definition at line 3456 of file pi_level0.cpp.
References piKernelSetArg().
piextKernelSetArgSampler()
pi_result piextKernelSetArgSampler (pi_kernel Kernel, pi_uint32 ArgIndex, const pi_sampler * ArgValue)
Definition at line 2028 of file pi_level0.cpp.
References PI_SUCCESS, ZE_CALL, and _pi_kernel::ZeKernel.
piextMemCreateWithNativeHandle()
pi_result piextMemCreateWithNativeHandle (pi_native_handle nativeHandle, pi_mem * mem)
Creates PI mem object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI mem from.
mem is the PI mem created from the native handle.
Definition at line 1651 of file pi_level0.cpp.
References die(), and PI_SUCCESS.
piextMemGetNativeHandle()
pi_result piextMemGetNativeHandle (pi_mem mem, pi_native_handle * nativeHandle)
Gets the native handle of a PI mem object.
Parameters
mem is the PI mem to get the native handle of.
nativeHandle is the native handle of mem.
Definition at line 1646 of file pi_level0.cpp.
References die(), and PI_SUCCESS.
piextPlatformCreateWithNativeHandle()
pi_result piextPlatformCreateWithNativeHandle (pi_native_handle nativeHandle, pi_platform * platform)
Creates PI platform object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI device from.
platform is the PI platform created from the native handle.
Definition at line 583 of file pi_level0.cpp.
References pi_cast(), and PI_SUCCESS.
piextPlatformGetNativeHandle()
pi_result piextPlatformGetNativeHandle (pi_platform platform, pi_native_handle * nativeHandle)
Gets the native handle of a PI platform object.
Parameters
platform is the PI platform to get the native handle of.
nativeHandle is the native handle of platform.
Definition at line 572 of file pi_level0.cpp.
References pi_cast(), PI_SUCCESS, and _pi_platform::ZeDriver.
piextProgramCreateWithNativeHandle()
pi_result piextProgramCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, pi_program * program)
Creates PI program object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI program from.
context is the PI context of the program.
program is the PI program created from the native handle.
Definition at line 1929 of file pi_level0.cpp.
References pi_cast(), PI_ERROR_UNKNOWN, PI_OUT_OF_HOST_MEMORY, and PI_SUCCESS.
piextProgramGetNativeHandle()
pi_result piextProgramGetNativeHandle (pi_program program, pi_native_handle * nativeHandle)
Gets the native handle of a PI program object.
Parameters
program is the PI program to get the native handle of.
nativeHandle is the native handle of program.
Definition at line 1918 of file pi_level0.cpp.
References pi_cast(), PI_SUCCESS, and _pi_program::ZeModule.
piextProgramSetSpecializationConstant()
pi_result piextProgramSetSpecializationConstant (pi_program prog, pi_uint32 spec_id, size_t spec_size, const void * spec_value)
Sets a specialization constant to a specific value.
Parameters
prog the program object which will use the value
spec_id integer ID of the constant
spec_size size of the value
spec_value bytes of the value
Definition at line 3744 of file pi_level0.cpp.
References PI_SUCCESS, _pi_program::ZeSpecConstants, and _pi_program::ZeSpecConstantsMutex.
piextQueueCreateWithNativeHandle()
pi_result piextQueueCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, pi_queue * queue)
Creates PI queue object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI queue from.
context is the PI context of the queue.
queue is the PI queue created from the native handle.
Definition at line 1395 of file pi_level0.cpp.
References pi_cast(), and PI_SUCCESS.
piextQueueGetNativeHandle()
pi_result piextQueueGetNativeHandle (pi_queue queue, pi_native_handle * nativeHandle)
Gets the native handle of a PI queue object.
Parameters
queue is the PI queue to get the native handle of.
nativeHandle is the native handle of queue.
Definition at line 1384 of file pi_level0.cpp.
References pi_cast(), PI_SUCCESS, and _pi_queue::ZeCommandQueue.
piextUSMDeviceAlloc()
pi_result piextUSMDeviceAlloc (void ** result_ptr, pi_context context, pi_device device, pi_usm_mem_properties * properties, size_t size, pi_uint32 alignment)
Allocates device memory.
Parameters
result_ptr contains the allocated memory
context is the pi_context
device is the device the memory will be allocated on
pi_usm_mem_properties are optional allocation properties
size_t is the size of the allocation
alignment is the desired alignment of the allocation
Definition at line 3408 of file pi_level0.cpp.
References _pi_context::Device, PI_MEM_ALLOC_FLAGS, PI_SUCCESS, _pi_device::Platform, ZE_CALL, _pi_device::ZeDevice, and _pi_platform::ZeDriver.
piextUSMEnqueueMemAdvise()
pi_result piextUSMEnqueueMemAdvise (pi_queue Queue, const void * Ptr, size_t Length, pi_mem_advice Advice, pi_event * Event)
USM memadvise API to govern behavior of automatic migration mechanisms.
USM Memadvise API.
Parameters
Queue is the queue to submit to
Ptr is the data to be advised
Length is the size in bytes of the meory to advise
Advice is device specific advice
Event is the event that represents this operation
Definition at line 3570 of file pi_level0.cpp.
References _pi_queue::Context, _pi_device::createCommandList(), _pi_context::Device, _pi_queue::executeCommandList(), PI_COMMAND_TYPE_USER, PI_INVALID_VALUE, PI_MEM_ADVICE_BIAS_CACHED, PI_MEM_ADVICE_BIAS_UNCACHED, PI_MEM_ADVICE_CLEAR_ACCESSED_BY, PI_MEM_ADVICE_CLEAR_NON_ATOMIC_MOSTLY, PI_MEM_ADVICE_CLEAR_PREFERRED_LOCATION, PI_MEM_ADVICE_CLEAR_READ_MOSTLY, PI_MEM_ADVICE_SET_ACCESSED_BY, PI_MEM_ADVICE_SET_NON_ATOMIC_MOSTLY, PI_MEM_ADVICE_SET_PREFERRED_LOCATION, PI_MEM_ADVICE_SET_READ_MOSTLY, PI_SUCCESS, piEventCreate, ZE_CALL, and _pi_device::ZeDevice.
piextUSMEnqueueMemcpy()
pi_result piextUSMEnqueueMemcpy (pi_queue queue, pi_bool blocking, void * dst_ptr, const void * src_ptr, size_t size, pi_uint32 num_events_in_waitlist, const pi_event * events_waitlist, pi_event * event)
USM Memcpy API.
Parameters
queue is the queue to submit to
blocking is whether this operation should block the host
src_ptr is the data to be copied
dst_ptr is the location the data will be copied
size is number of bytes to copy
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
Definition at line 3489 of file pi_level0.cpp.
References enqueueMemCopyHelper(), PI_COMMAND_TYPE_MEM_BUFFER_COPY, and PI_INVALID_VALUE.
piextUSMEnqueueMemset()
pi_result piextUSMEnqueueMemset (pi_queue Queue, void * Ptr, pi_int32 Value, size_t Count, pi_uint32 NumEventsInWaitlist, const pi_event * EventsWaitlist, pi_event * Event)
USM Memset API.
Parameters
Queue is the queue to submit to
Ptr is the ptr to memset
Value is value to set. It is interpreted as an 8-bit value and the upper 24 bits are ignored
Count is the size in bytes to memset
NumEventsInWaitlist is the number of events to wait on
EventsWaitlist is an array of events to wait on
Event is the event that represents this operation
Definition at line 3473 of file pi_level0.cpp.
References enqueueMemFillHelper(), PI_COMMAND_TYPE_MEM_BUFFER_FILL, and PI_INVALID_VALUE.
piextUSMEnqueuePrefetch()
pi_result piextUSMEnqueuePrefetch (pi_queue Queue, const void * Ptr, size_t Size, pi_usm_migration_flags Flags, pi_uint32 NumEventsInWaitlist, const pi_event * EventsWaitlist, pi_event * Event)
Hint to migrate memory to the device.
Parameters
Queue is the queue to submit to
Ptr points to the memory to migrate
Size is the number of bytes to migrate
Flags is a bitfield used to specify memory migration options
NumEventsInWaitlist is the number of events to wait on
EventsWaitlist is an array of events to wait on
Event is the event that represents this operation
Definition at line 3514 of file pi_level0.cpp.
References _pi_queue::Context, _pi_device::createCommandList(), _pi_event::createZeEventList(), _pi_event::deleteZeEventList(), _pi_context::Device, _pi_queue::executeCommandList(), PI_COMMAND_TYPE_USER, PI_SUCCESS, PI_USM_MIGRATION_TBD0, piEventCreate, and ZE_CALL.
piextUSMFree()
pi_result piextUSMFree (pi_context context, void * ptr)
Frees allocated USM memory.
Parameters
context is the pi_context of the allocation
ptr is the memory to be freed
Definition at line 3451 of file pi_level0.cpp.
References _pi_context::Device, PI_SUCCESS, _pi_device::Platform, ZE_CALL, and _pi_platform::ZeDriver.
piextUSMGetMemAllocInfo()
pi_result piextUSMGetMemAllocInfo (pi_context Context, const void * Ptr, pi_mem_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
API to query information about USM allocated pointers Valid Queries: PI_MEM_ALLOC_TYPE returns host/device/shared pi_usm_type value PI_MEM_ALLOC_BASE_PTR returns the base ptr of an allocation if the queried pointer fell inside an allocation.
API to query information about USM allocated pointers Valid Queries: PI_MEM_ALLOC_TYPE returns host/device/shared pi_host_usm value PI_MEM_ALLOC_BASE_PTR returns the base ptr of an allocation if the queried pointer fell inside an allocation.
Result must fit in void * PI_MEM_ALLOC_SIZE returns how big the queried pointer's allocation is in bytes. Result is a size_t. PI_MEM_ALLOC_DEVICE returns the pi_device this was allocated against
Parameters
Context is the pi_context
Ptr is the pointer to query
ParamName is the type of query to perform
ParamValueSize is the size of the result in bytes
ParamValue is the result
ParamValueRet is how many bytes were written
Definition at line 3657 of file pi_level0.cpp.
References _pi_context::Device, die(), PI_INVALID_VALUE, PI_MEM_ALLOC_BASE_PTR, PI_MEM_ALLOC_DEVICE, PI_MEM_ALLOC_SIZE, PI_MEM_ALLOC_TYPE, PI_MEM_TYPE_DEVICE, PI_MEM_TYPE_HOST, PI_MEM_TYPE_SHARED, PI_MEM_TYPE_UNKNOWN, PI_SUCCESS, _pi_device::Platform, ZE_CALL, and _pi_platform::ZeDriver.
piextUSMHostAlloc()
pi_result piextUSMHostAlloc (void ** result_ptr, pi_context context, pi_usm_mem_properties * properties, size_t size, pi_uint32 alignment)
Allocates host memory accessible by the device.
Parameters
result_ptr contains the allocated memory
context is the pi_context
pi_usm_mem_properties are optional allocation properties
size_t is the size of the allocation
alignment is the desired alignment of the allocation
Definition at line 3391 of file pi_level0.cpp.
References _pi_context::Device, PI_MEM_ALLOC_FLAGS, PI_SUCCESS, _pi_device::Platform, ZE_CALL, and _pi_platform::ZeDriver.
piextUSMSharedAlloc()
pi_result piextUSMSharedAlloc (void ** result_ptr, pi_context context, pi_device device, pi_usm_mem_properties * properties, size_t size, pi_uint32 alignment)
Allocates memory accessible on both host and device.
Parameters
result_ptr contains the allocated memory
context is the pi_context
device is the device the memory will be allocated on
pi_usm_mem_properties are optional allocation properties
size_t is the size of the allocation
alignment is the desired alignment of the allocation
Definition at line 3428 of file pi_level0.cpp.
References _pi_context::Device, PI_MEM_ALLOC_FLAGS, PI_SUCCESS, _pi_device::Platform, ZE_CALL, _pi_device::ZeDevice, and _pi_platform::ZeDriver.
piKernelCreate()
pi_result piKernelCreate (pi_program Program, const char * KernelName, pi_kernel * RetKernel)
Definition at line 1960 of file pi_level0.cpp.
References pi_cast(), PI_ERROR_UNKNOWN, PI_OUT_OF_HOST_MEMORY, PI_SUCCESS, ZE_CALL, and _pi_program::ZeModule.
piKernelGetGroupInfo()
pi_result piKernelGetGroupInfo (pi_kernel Kernel, pi_device Device, pi_kernel_group_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 2089 of file pi_level0.cpp.
References PI_INVALID_VALUE, PI_KERNEL_GROUP_INFO_COMPILE_WORK_GROUP_SIZE, PI_KERNEL_GROUP_INFO_GLOBAL_WORK_SIZE, PI_KERNEL_GROUP_INFO_LOCAL_MEM_SIZE, PI_KERNEL_GROUP_INFO_PREFERRED_WORK_GROUP_SIZE_MULTIPLE, PI_KERNEL_GROUP_INFO_PRIVATE_MEM_SIZE, PI_KERNEL_GROUP_INFO_WORK_GROUP_SIZE, PI_SUCCESS, cl::sycl::detail::uint32_t, ZE_CALL, _pi_device::ZeDevice, and _pi_kernel::ZeKernel.
Referenced by cl::sycl::detail::get_kernel_work_group_info< T, Param >::get(), cl::sycl::detail::get_kernel_work_group_info< cl::sycl::range< 3 >, Param >::get(), cl::sycl::detail::enqueue_kernel_launch::handleInvalidWorkGroupSize(), and piPluginInit().
piKernelGetInfo()
pi_result piKernelGetInfo (pi_kernel Kernel, pi_kernel_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 2038 of file pi_level0.cpp.
References _pi_program::Context, _pi_kernel::KernelName, PI_ERROR_UNKNOWN, PI_INVALID_VALUE, PI_KERNEL_INFO_ATTRIBUTES, PI_KERNEL_INFO_CONTEXT, PI_KERNEL_INFO_FUNCTION_NAME, PI_KERNEL_INFO_NUM_ARGS, PI_KERNEL_INFO_PROGRAM, PI_KERNEL_INFO_REFERENCE_COUNT, PI_OUT_OF_HOST_MEMORY, PI_SUCCESS, _pi_kernel::Program, _pi_object::RefCount, cl::sycl::detail::uint32_t, ZE_CALL, and _pi_kernel::ZeKernel.
Referenced by cl::sycl::detail::get_kernel_info< string_class, Param >::get(), cl::sycl::detail::get_kernel_info< cl_uint, Param >::get(), cl::sycl::detail::ProgramManager::getPiProgramFromPiKernel(), cl::sycl::detail::enqueue_kernel_launch::handleInvalidWorkGroupSize(), cl::sycl::detail::kernel_impl::kernel_impl(), and piPluginInit().
piKernelGetSubGroupInfo()
pi_result piKernelGetSubGroupInfo (pi_kernel kernel, pi_device device, pi_kernel_sub_group_info param_name, size_t input_value_size, const void * input_value, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
API to query information from the sub-group from a kernel.
Parameters
kernel is the pi_kernel to query
device is the device the kernel is executed on
param_name is a pi_kernel_sub_group_info enum value that specifies the informtation queried for.
input_value_size is the size of input value passed in ptr input_value param
input_value is the ptr to the input value passed.
param_value_size is the size of the value in bytes.
param_value is a pointer to the value to set.
param_value_size_ret is a pointer to return the size of data in param_value ptr.
All queries expect a return of 4 bytes in param_value_size, param_value_size_ret, and a uint32_t value should to be written in param_value ptr. Note: This behaviour differs from OpenCL. OpenCL returns size_t.
Definition at line 2154 of file pi_level0.cpp.
References die().
piKernelRelease()
pi_result piKernelRelease (pi_kernel Kernel)
Definition at line 2171 of file pi_level0.cpp.
References PI_SUCCESS, and _pi_object::RefCount.
Referenced by piPluginInit(), cl::sycl::detail::kernel_impl::~kernel_impl(), and cl::sycl::detail::KernelProgramCache::~KernelProgramCache().
piKernelRetain()
pi_result piKernelRetain (pi_kernel Kernel)
Definition at line 2164 of file pi_level0.cpp.
References PI_SUCCESS, and _pi_object::RefCount.
Referenced by cl::sycl::detail::kernel_impl::get(), cl::sycl::detail::program_impl::get_binaries(), cl::sycl::detail::kernel_impl::kernel_impl(), and piPluginInit().
piKernelSetArg()
pi_result piKernelSetArg (pi_kernel Kernel, pi_uint32 ArgIndex, size_t ArgSize, const void * ArgValue)
Definition at line 1986 of file pi_level0.cpp.
References PI_SUCCESS, ZE_CALL, and _pi_kernel::ZeKernel.
Referenced by piextKernelSetArgPointer(), piPluginInit(), and cl::sycl::detail::ReverseRangeDimensionsForKernel().
piKernelSetExecInfo()
pi_result piKernelSetExecInfo (pi_kernel kernel, pi_kernel_exec_info value_name, size_t param_value_size, const void * param_value)
API to set attributes controlling kernel execution.
Parameters
kernel is the pi kernel to execute
param_name is a pi_kernel_exec_info value that specifies the info passed to the kernel
param_value_size is the size of the value in bytes
param_value is a pointer to the value to set for the kernel
If param_name is PI_USM_INDIRECT_ACCESS, the value will be a ptr to the pi_bool value PI_TRUE If param_name is PI_USM_PTRS, the value will be an array of ptrs
Definition at line 3717 of file pi_level0.cpp.
References PI_INVALID_VALUE, PI_SUCCESS, PI_TRUE, PI_USM_INDIRECT_ACCESS, ZE_CALL, and _pi_kernel::ZeKernel.
piMemBufferCreate()
pi_result piMemBufferCreate (pi_context Context, pi_mem_flags Flags, size_t Size, void * HostPtr, pi_mem * RetMem)
Definition at line 1407 of file pi_level0.cpp.
References _pi_context::Device, die(), PI_ERROR_UNKNOWN, PI_MEM_FLAGS_ACCESS_RW, PI_MEM_FLAGS_HOST_PTR_COPY, PI_MEM_FLAGS_HOST_PTR_USE, PI_OUT_OF_HOST_MEMORY, PI_SUCCESS, _pi_device::Platform, ZE_CALL, _pi_device::ZeCommandListInit, _pi_device::ZeDevice, and _pi_platform::ZeDriver.
piMemBufferPartition()
pi_result piMemBufferPartition (pi_mem Buffer, pi_mem_flags Flags, pi_buffer_create_type BufferCreateType, void * BufferCreateInfo, pi_mem * RetMem)
Definition at line 3336 of file pi_level0.cpp.
References _pi_mem::getZeHandle(), _pi_mem::isImage(), PI_BUFFER_CREATE_TYPE_REGION, PI_ERROR_UNKNOWN, PI_MEM_FLAGS_ACCESS_RW, PI_OUT_OF_HOST_MEMORY, PI_SUCCESS, and _pi_mem::Platform.
piMemGetInfo()
pi_result piMemGetInfo (pi_mem Mem, cl_mem_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 1452 of file pi_level0.cpp.
References die().
Referenced by cl::sycl::detail::SYCLMemObjT::getBufSizeForContext(), cl::sycl::detail::image_impl< Dimensions >::image_impl(), piPluginInit(), and cl::sycl::detail::SYCLMemObjT::SYCLMemObjT().
piMemImageCreate()
pi_result piMemImageCreate (pi_context Context, pi_mem_flags Flags, const pi_image_format * ImageFormat, const pi_image_desc * ImageDesc, void * HostPtr, pi_mem * RetImage)
Definition at line 1482 of file pi_level0.cpp.
References _pi_context::Device, die(), _pi_image_desc::image_array_size, _pi_image_format::image_channel_data_type, _pi_image_format::image_channel_order, _pi_image_desc::image_depth, _pi_image_desc::image_height, _pi_image_desc::image_type, _pi_image_desc::image_width, _pi_image_desc::num_mip_levels, pi_cast(), PI_ERROR_UNKNOWN, PI_INVALID_VALUE, PI_MEM_FLAGS_ACCESS_RW, PI_MEM_FLAGS_HOST_PTR_COPY, PI_MEM_FLAGS_HOST_PTR_USE, PI_MEM_TYPE_IMAGE1D, PI_MEM_TYPE_IMAGE1D_ARRAY, PI_MEM_TYPE_IMAGE2D, PI_MEM_TYPE_IMAGE2D_ARRAY, PI_MEM_TYPE_IMAGE3D, PI_OUT_OF_HOST_MEMORY, PI_SUCCESS, _pi_device::Platform, cl::sycl::detail::uint32_t, ZE_CALL, _pi_device::ZeCommandListInit, and _pi_device::ZeDevice.
piMemImageGetInfo()
pi_result piMemImageGetInfo (pi_mem Image, pi_image_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 3111 of file pi_level0.cpp.
References die().
Referenced by cl::sycl::detail::getImageInfo(), and piPluginInit().
piMemRelease()
pi_result piMemRelease (pi_mem Mem)
Definition at line 1466 of file pi_level0.cpp.
References _pi_mem::getZeHandle(), _pi_mem::isImage(), PI_SUCCESS, _pi_mem::Platform, _pi_object::RefCount, ZE_CALL, and _pi_platform::ZeDriver.
Referenced by piPluginInit(), cl::sycl::detail::MemoryManager::releaseImageBuffer(), cl::sycl::detail::MemoryManager::releaseMemObj(), and cl::sycl::detail::SYCLMemObjT::updateHostMemory().
piMemRetain()
pi_result piMemRetain (pi_mem Mem)
Definition at line 1460 of file pi_level0.cpp.
References PI_SUCCESS, and _pi_object::RefCount.
Referenced by piPluginInit(), and cl::sycl::detail::SYCLMemObjT::SYCLMemObjT().
piPlatformGetInfo()
pi_result piPlatformGetInfo (pi_platform Platform, pi_platform_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 523 of file pi_level0.cpp.
References die(), PI_PLATFORM_INFO_EXTENSIONS, PI_PLATFORM_INFO_NAME, PI_PLATFORM_INFO_PROFILE, PI_PLATFORM_INFO_VENDOR, PI_PLATFORM_INFO_VERSION, PI_SUCCESS, _pi_platform::ZeDriverApiVersion, and _pi_platform::ZeDriverVersion.
Referenced by cl::sycl::detail::get_platform_info< string_class, param >::get(), and piPluginInit().
piPlatformsGet()
pi_result piPlatformsGet (pi_uint32 NumEntries, pi_platform * Platforms, pi_uint32 * NumPlatforms)
Definition at line 432 of file pi_level0.cpp.
References mapError(), PI_ERROR_UNKNOWN, PI_INVALID_VALUE, PI_OUT_OF_HOST_MEMORY, PI_SUCCESS, cl::sycl::detail::uint32_t, ZE_CALL, ZE_CALL_NOCHECK, _pi_platform::ZeDriverApiVersion, and _pi_platform::ZeDriverVersion.
piPluginInit()
pi_result piPluginInit (pi_plugin * PluginInit)
Definition at line 3761 of file pi_level0.cpp.
References _PI_H_VERSION_STRING, PI_SUCCESS, and _pi_plugin::PluginVersion.
piProgramBuild()
pi_result piProgramBuild (pi_program Program, pi_uint32 NumDevices, const pi_device * DeviceList, const char * Options, void(*)(pi_program Program, void *UserData) PFnNotify, void * UserData)
Definition at line 1821 of file pi_level0.cpp.
References _pi_program::Context, _pi_context::Device, PI_SUCCESS, ZE_CALL, _pi_program::ZeBuildLog, _pi_device::ZeDevice, _pi_program::ZeModule, _pi_program::ZeModuleDesc, _pi_program::ZeSpecConstants, and _pi_program::ZeSpecConstantsMutex.
Referenced by piProgramCompile().
piProgramCompile()
pi_result piProgramCompile (pi_program Program, pi_uint32 NumDevices, const pi_device * DeviceList, const char * Options, pi_uint32 NumInputHeaders, const pi_program * InputHeaders, const char ** HeaderIncludeNames, void(*)(pi_program Program, void *UserData) PFnNotify, void * UserData)
Definition at line 1805 of file pi_level0.cpp.
References piProgramBuild().
piProgramCreate()
pi_result piProgramCreate (pi_context Context, const void * IL, size_t Length, pi_program * Program)
Definition at line 1657 of file pi_level0.cpp.
References cl::sycl::detail::memcpy(), PI_ERROR_UNKNOWN, PI_OUT_OF_HOST_MEMORY, and PI_SUCCESS.
piProgramCreateWithBinary()
pi_result piProgramCreateWithBinary (pi_context Context, pi_uint32 NumDevices, const pi_device * DeviceList, const size_t * Lengths, const unsigned char ** Binaries, pi_int32 * BinaryStatus, pi_program * RetProgram)
Definition at line 1684 of file pi_level0.cpp.
References _pi_context::Device, cl::sycl::detail::memcpy(), pi_cast(), PI_ERROR_UNKNOWN, PI_OUT_OF_HOST_MEMORY, and PI_SUCCESS.
piProgramGetBuildInfo()
pi_result piProgramGetBuildInfo (pi_program Program, pi_device Device, cl_program_build_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 1864 of file pi_level0.cpp.
References PI_INVALID_VALUE, PI_SUCCESS, ZE_CALL, and _pi_program::ZeBuildLog.
Referenced by cl::sycl::detail::ProgramManager::getProgramBuildLog(), cl::sycl::detail::enqueue_kernel_launch::handleInvalidWorkGroupSize(), piPluginInit(), and cl::sycl::detail::program_impl::program_impl().
piProgramGetInfo()
pi_result piProgramGetInfo (pi_program Program, pi_program_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 1733 of file pi_level0.cpp.
References _pi_program::Context, _pi_context::Device, die(), pi_cast(), PI_ERROR_UNKNOWN, PI_OUT_OF_HOST_MEMORY, PI_PROGRAM_INFO_BINARIES, PI_PROGRAM_INFO_BINARY_SIZES, PI_PROGRAM_INFO_DEVICES, PI_PROGRAM_INFO_KERNEL_NAMES, PI_PROGRAM_INFO_NUM_DEVICES, PI_PROGRAM_INFO_NUM_KERNELS, PI_PROGRAM_INFO_REFERENCE_COUNT, PI_SUCCESS, _pi_object::RefCount, cl::sycl::detail::uint32_t, ZE_CALL, and _pi_program::ZeModule.
Referenced by cl::sycl::detail::program_impl::get_binaries(), cl::sycl::detail::ProgramManager::getProgramBuildLog(), piPluginInit(), cl::sycl::detail::program_impl::program_impl(), and cl::sycl::detail::program_impl::get_info< info::program::reference_count >().
piProgramLink()
pi_result piProgramLink (pi_context Context, pi_uint32 NumDevices, const pi_device * DeviceList, const char * Options, pi_uint32 NumInputPrograms, const pi_program * InputPrograms, void(*)(pi_program Program, void *UserData) PFnNotify, void * UserData, pi_program * RetProgram)
Definition at line 1792 of file pi_level0.cpp.
References PI_SUCCESS.
piProgramRelease()
pi_result piProgramRelease (pi_program Program)
Definition at line 1905 of file pi_level0.cpp.
References PI_SUCCESS, _pi_object::RefCount, _pi_program::ZeBuildLog, and _pi_program::ZeModuleDesc.
Referenced by piPluginInit(), cl::sycl::detail::context_impl::~context_impl(), cl::sycl::detail::KernelProgramCache::~KernelProgramCache(), and cl::sycl::detail::program_impl::~program_impl().
piProgramRetain()
pi_result piProgramRetain (pi_program Program)
Definition at line 1899 of file pi_level0.cpp.
References PI_SUCCESS, and _pi_object::RefCount.
Referenced by cl::sycl::detail::program_impl::build_with_kernel_name(), cl::sycl::detail::program_impl::get(), piPluginInit(), and cl::sycl::detail::program_impl::program_impl().
piQueueCreate()
pi_result piQueueCreate (pi_context Context, pi_device Device, pi_queue_properties Properties, pi_queue * Queue)
Definition at line 1290 of file pi_level0.cpp.
References _pi_context::Device, PI_ERROR_UNKNOWN, PI_INVALID_CONTEXT, PI_INVALID_DEVICE, PI_OUT_OF_HOST_MEMORY, PI_QUEUE_ON_DEVICE, PI_QUEUE_ON_DEVICE_DEFAULT, PI_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE, PI_QUEUE_PROFILING_ENABLE, PI_SUCCESS, ZE_CALL, and _pi_device::ZeDevice.
piQueueFinish()
pi_result piQueueFinish (pi_queue Queue)
Definition at line 1377 of file pi_level0.cpp.
References PI_SUCCESS, ZE_CALL, and _pi_queue::ZeCommandQueue.
Referenced by cl::sycl::detail::queue_impl::getExclusiveQueueHandleRef(), and piPluginInit().
piQueueGetInfo()
pi_result piQueueGetInfo (pi_queue Queue, pi_queue_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 1331 of file pi_level0.cpp.
References _pi_queue::Context, _pi_context::Device, die(), PI_INVALID_VALUE, PI_QUEUE_INFO_CONTEXT, PI_QUEUE_INFO_DEVICE, PI_QUEUE_INFO_DEVICE_DEFAULT, PI_QUEUE_INFO_PROPERTIES, PI_QUEUE_INFO_REFERENCE_COUNT, PI_QUEUE_INFO_SIZE, PI_SUCCESS, and _pi_object::RefCount.
Referenced by piPluginInit(), cl::sycl::detail::queue_impl::queue_impl(), and cl::sycl::detail::queue_impl::get_info< info::queue::reference_count >().
piQueueRelease()
pi_result piQueueRelease (pi_queue Queue)
Definition at line 1369 of file pi_level0.cpp.
References PI_SUCCESS, _pi_object::RefCount, ZE_CALL, and _pi_queue::ZeCommandQueue.
Referenced by cl::sycl::detail::DispatchNativeKernel(), piPluginInit(), and cl::sycl::detail::queue_impl::~queue_impl().
piQueueRetain()
pi_result piQueueRetain (pi_queue Queue)
Definition at line 1364 of file pi_level0.cpp.
References PI_SUCCESS, and _pi_object::RefCount.
Referenced by cl::sycl::detail::queue_impl::get(), piPluginInit(), and cl::sycl::detail::queue_impl::queue_impl().
piSamplerCreate()
pi_result piSamplerCreate (pi_context Context, const pi_sampler_properties * SamplerProperties, pi_sampler * RetSampler)
Definition at line 2470 of file pi_level0.cpp.
References _pi_context::Device, pi_cast(), PI_ERROR_UNKNOWN, PI_FALSE, PI_INVALID_VALUE, PI_OUT_OF_HOST_MEMORY, PI_SAMPLER_ADDRESSING_MODE_CLAMP, PI_SAMPLER_ADDRESSING_MODE_CLAMP_TO_EDGE, PI_SAMPLER_ADDRESSING_MODE_MIRRORED_REPEAT, PI_SAMPLER_ADDRESSING_MODE_NONE, PI_SAMPLER_ADDRESSING_MODE_REPEAT, PI_SAMPLER_FILTER_MODE_LINEAR, PI_SAMPLER_FILTER_MODE_NEAREST, PI_SAMPLER_PROPERTIES_ADDRESSING_MODE, PI_SAMPLER_PROPERTIES_FILTER_MODE, PI_SAMPLER_PROPERTIES_NORMALIZED_COORDS, PI_SUCCESS, PI_TRUE, ZE_CALL, and _pi_device::ZeDevice.
piSamplerGetInfo()
pi_result piSamplerGetInfo (pi_sampler Sampler, pi_sampler_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 2580 of file pi_level0.cpp.
References die().
Referenced by piPluginInit(), and cl::sycl::detail::sampler_impl::sampler_impl().
piSamplerRelease()
pi_result piSamplerRelease (pi_sampler Sampler)
Definition at line 2594 of file pi_level0.cpp.
References PI_SUCCESS, _pi_object::RefCount, ZE_CALL, and _pi_sampler::ZeSampler.
Referenced by piPluginInit(), and cl::sycl::detail::sampler_impl::~sampler_impl().
piSamplerRetain()
pi_result piSamplerRetain (pi_sampler Sampler)
Definition at line 2588 of file pi_level0.cpp.
References PI_SUCCESS, and _pi_object::RefCount.
Referenced by piPluginInit(), and cl::sycl::detail::sampler_impl::sampler_impl().
zeParseError()
void zeParseError (ze_result_t ZeError, std::string & ErrorString) inline
Definition at line 289 of file pi_level0.cpp.
References ZE_ERRCASE.
Variable Documentation
OnceFlag
std::once_flag OnceFlag
Definition at line 430 of file pi_level0.cpp.
piEventCreate
decltype(piEventCreate) piEventCreate
Definition at line 428 of file pi_level0.cpp.
Referenced by enqueueMemCopyHelper(), enqueueMemCopyRectHelper(), enqueueMemFillHelper(), enqueueMemImageCommandHelper(), piEnqueueEventsWaitWithBarrier(), piEnqueueKernelLaunch(), piEnqueueMemBufferMap(), piEnqueueMemUnmap(), piextUSMEnqueueMemAdvise(), piextUSMEnqueuePrefetch(), and piPluginInit().
ZE_SUPPORTED_EXTENSIONS
constexpr char ZE_SUPPORTED_EXTENSIONS[]
Initial value:
=
    "cl_khr_il_program cl_khr_subgroups cl_intel_subgroups "
    "cl_intel_subgroups_short cl_intel_required_subgroup_size "
Definition at line 237 of file pi_level0.cpp.
Referenced by piDeviceGetInfo().