DPC++ Runtime: plugins/native_cpu/pi_native_cpu.cpp File Reference
pi_native_cpu.cpp File Reference
#include "pi_native_cpu.hpp"
#include <sycl/detail/pi.def>
Macros
#define EXPORT_PI_API_SYMBOLS
#define _PI_API(api) decltype(pi2ur::api) api;
#define _PI_API(api) (PluginInit->PiFunctionTable).api = (decltype(&::api))(&api);
Functions
pi_result piPlatformsGet (pi_uint32 NumEntries, pi_platform *Platforms, pi_uint32 *NumPlatforms)
pi_result piPlatformGetInfo (pi_platform Platform, pi_platform_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piextPlatformGetNativeHandle (pi_platform Platform, pi_native_handle *NativeHandle)
Gets the native handle of a PI platform object.
pi_result piextPlatformCreateWithNativeHandle (pi_native_handle NativeHandle, pi_platform *Platform)
Creates PI platform object from a native handle.
pi_result piPluginGetLastError (char **message)
API to get Plugin specific warning and error messages.
pi_result piPluginGetBackendOption (pi_platform platform, const char *frontend_option, const char **backend_option)
API to get backend specific option.
pi_result piDevicesGet (pi_platform Platform, pi_device_type DeviceType, pi_uint32 NumEntries, pi_device *Devices, pi_uint32 *NumDevices)
pi_result piDeviceRetain (pi_device Device)
pi_result piDeviceRelease (pi_device Device)
pi_result piDeviceGetInfo (pi_device Device, pi_device_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
Returns requested info for provided native device Return PI_DEVICE_INFO_EXTENSION_DEVICELIB_ASSERT for PI_DEVICE_INFO_EXTENSIONS query when the device supports native asserts.
pi_result piDevicePartition (pi_device Device, const pi_device_partition_property *Properties, pi_uint32 NumDevices, pi_device *OutDevices, pi_uint32 *OutNumDevices)
pi_result piextDeviceSelectBinary (pi_device Device, pi_device_binary *Binaries, pi_uint32 NumBinaries, pi_uint32 *SelectedBinaryInd)
Selects the most appropriate device binary based on runtime information and the IR characteristics.
pi_result piextDeviceGetNativeHandle (pi_device Device, pi_native_handle *NativeHandle)
Gets the native handle of a PI device object.
pi_result piextDeviceCreateWithNativeHandle (pi_native_handle NativeHandle, pi_platform Platform, pi_device *Device)
Creates PI device object from a native handle.
pi_result piContextCreate (const pi_context_properties *Properties, pi_uint32 NumDevices, const pi_device *Devices, void(*PFnNotify)(const char *ErrInfo, const void *PrivateInfo, size_t CB, void *UserData), void *UserData, pi_context *RetContext)
pi_result piContextGetInfo (pi_context Context, pi_context_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piextContextSetExtendedDeleter (pi_context Context, pi_context_extended_deleter Function, void *UserData)
pi_result piextContextGetNativeHandle (pi_context Context, pi_native_handle *NativeHandle)
Gets the native handle of a PI context object.
pi_result piextContextCreateWithNativeHandle (pi_native_handle NativeHandle, pi_uint32 NumDevices, const pi_device *Devices, bool OwnNativeHandle, pi_context *RetContext)
Creates PI context object from a native handle.
pi_result piContextRetain (pi_context Context)
pi_result piContextRelease (pi_context Context)
pi_result piQueueCreate (pi_context Context, pi_device Device, pi_queue_properties Flags, pi_queue *Queue)
pi_result piextQueueCreate (pi_context Context, pi_device Device, pi_queue_properties *Properties, pi_queue *Queue)
pi_result piQueueGetInfo (pi_queue Queue, pi_queue_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piQueueRetain (pi_queue Queue)
pi_result piQueueRelease (pi_queue Queue)
pi_result piQueueFinish (pi_queue Queue)
pi_result piQueueFlush (pi_queue Queue)
pi_result piextQueueGetNativeHandle (pi_queue Queue, pi_native_handle *NativeHandle, int32_t *NativeHandleDesc)
Gets the native handle of a PI queue object.
pi_result piextQueueCreateWithNativeHandle (pi_native_handle NativeHandle, int32_t NativeHandleDesc, pi_context Context, pi_device Device, bool OwnNativeHandle, pi_queue_properties *Properties, pi_queue *Queue)
Creates PI queue object from a native handle.
pi_result piMemBufferCreate (pi_context Context, pi_mem_flags Flags, size_t Size, void *HostPtr, pi_mem *RetMem, const pi_mem_properties *properties)
pi_result piMemGetInfo (pi_mem Mem, pi_mem_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piMemRetain (pi_mem Mem)
pi_result piMemRelease (pi_mem Mem)
pi_result piMemImageCreate (pi_context Context, pi_mem_flags Flags, const pi_image_format *ImageFormat, const pi_image_desc *ImageDesc, void *HostPtr, pi_mem *RetImage)
pi_result piextMemGetNativeHandle (pi_mem Mem, pi_device Dev, pi_native_handle *NativeHandle)
Gets the native handle of a PI mem object.
pi_result piextMemCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, bool ownNativeHandle, pi_mem *Mem)
Creates PI mem object from a native handle.
pi_result piProgramCreate (pi_context Context, const void *ILBytes, size_t Length, pi_program *Program)
pi_result piProgramCreateWithBinary (pi_context Context, pi_uint32 NumDevices, const pi_device *DeviceList, const size_t *Lengths, const unsigned char **Binaries, size_t NumMetadataEntries, const pi_device_binary_property *Metadata, pi_int32 *BinaryStatus, pi_program *Program)
Creates a PI program for a context and loads the given binary into it.
pi_result piextMemImageCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, bool OwnNativeHandle, const pi_image_format *ImageFormat, const pi_image_desc *ImageDesc, pi_mem *Img)
Creates PI image object from a native handle.
pi_result piProgramGetInfo (pi_program Program, pi_program_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piProgramLink (pi_context Context, pi_uint32 NumDevices, const pi_device *DeviceList, const char *Options, pi_uint32 NumInputPrograms, const pi_program *InputPrograms, void(*PFnNotify)(pi_program Program, void *UserData), void *UserData, pi_program *RetProgram)
pi_result piProgramCompile (pi_program Program, pi_uint32 NumDevices, const pi_device *DeviceList, const char *Options, pi_uint32 NumInputHeaders, const pi_program *InputHeaders, const char **HeaderIncludeNames, void(*PFnNotify)(pi_program Program, void *UserData), void *UserData)
pi_result piProgramBuild (pi_program Program, pi_uint32 NumDevices, const pi_device *DeviceList, const char *Options, void(*PFnNotify)(pi_program Program, void *UserData), void *UserData)
pi_result piProgramGetBuildInfo (pi_program Program, pi_device Device, pi_program_build_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piProgramRetain (pi_program Program)
pi_result piProgramRelease (pi_program Program)
pi_result piextProgramGetNativeHandle (pi_program Program, pi_native_handle *NativeHandle)
Gets the native handle of a PI program object.
pi_result piextProgramCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, bool OwnNativeHandle, pi_program *Program)
Creates PI program object from a native handle.
pi_result piKernelCreate (pi_program Program, const char *KernelName, pi_kernel *RetKernel)
pi_result piKernelSetArg (pi_kernel Kernel, pi_uint32 ArgIndex, size_t ArgSize, const void *ArgValue)
pi_result piextKernelSetArgMemObj (pi_kernel Kernel, pi_uint32 ArgIndex, const pi_mem_obj_property *ArgProperties, const pi_mem *ArgValue)
pi_result piextKernelSetArgSampler (pi_kernel Kernel, pi_uint32 ArgIndex, const pi_sampler *ArgValue)
pi_result piKernelGetInfo (pi_kernel Kernel, pi_kernel_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piextMemImageAllocate (pi_context Context, pi_device Device, pi_image_format *ImageFormat, pi_image_desc *ImageDesc, pi_image_mem_handle *RetMem)
API to allocate memory for bindless images.
pi_result piextMemUnsampledImageCreate (pi_context Context, pi_device Device, pi_image_mem_handle ImgMem, pi_image_format *ImageFormat, pi_image_desc *ImageDesc, pi_mem *RetMem, pi_image_handle *RetHandle)
API to create bindless image handles.
pi_result piextMemSampledImageCreate (pi_context Context, pi_device Device, pi_image_mem_handle ImgMem, pi_image_format *ImageFormat, pi_image_desc *ImageDesc, pi_sampler Sampler, pi_mem *RetMem, pi_image_handle *RetHandle)
API to create sampled bindless image handles.
pi_result piextBindlessImageSamplerCreate (pi_context Context, const pi_sampler_properties *SamplerProperties, float MinMipmapLevelClamp, float MaxMipmapLevelClamp, float MaxAnisotropy, pi_sampler *RetSampler)
API to create samplers for bindless images.
pi_result piextMemMipmapGetLevel (pi_context Context, pi_device Device, pi_image_mem_handle MipMem, unsigned int Level, pi_image_mem_handle *RetMem)
API to retrieve individual image from mipmap.
pi_result piextMemImageFree (pi_context Context, pi_device Device, pi_image_mem_handle MemoryHandle)
API to free memory for bindless images.
pi_result piextMemMipmapFree (pi_context Context, pi_device Device, pi_image_mem_handle MemoryHandle)
API to free mipmap memory for bindless images.
pi_result piextMemImageCopy (pi_queue Queue, void *DstPtr, void *SrcPtr, const pi_image_format *ImageFormat, const pi_image_desc *ImageDesc, const pi_image_copy_flags Flags, pi_image_offset SrcOffset, pi_image_offset DstOffset, pi_image_region CopyExtent, pi_image_region HostExtent, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
API to copy image data Host to Device or Device to Host.
pi_result piextMemUnsampledImageHandleDestroy (pi_context Context, pi_device Device, pi_image_handle Handle)
API to destroy bindless unsampled image handles.
pi_result piextMemSampledImageHandleDestroy (pi_context Context, pi_device Device, pi_image_handle Handle)
API to destroy bindless sampled image handles.
pi_result piextMemImageGetInfo (pi_image_mem_handle MemHandle, pi_image_info ParamName, void *ParamValue, size_t *ParamValueSizeRet)
API to query an image memory handle for specific properties.
pi_result piextMemImportOpaqueFD (pi_context Context, pi_device Device, size_t Size, int FileDescriptor, pi_interop_mem_handle *RetHandle)
API to import external memory in the form of a file descriptor.
pi_result piextMemMapExternalArray (pi_context Context, pi_device Device, pi_image_format *ImageFormat, pi_image_desc *ImageDesc, pi_interop_mem_handle MemHandle, pi_image_mem_handle *RetMem)
API to map an interop memory handle to an image memory handle.
pi_result piextMemReleaseInterop (pi_context Context, pi_device Device, pi_interop_mem_handle ExtMem)
API to destroy interop memory.
pi_result piextImportExternalSemaphoreOpaqueFD (pi_context Context, pi_device Device, int FileDescriptor, pi_interop_semaphore_handle *RetHandle)
API to import an external semaphore in the form of a file descriptor.
pi_result piextDestroyExternalSemaphore (pi_context Context, pi_device Device, pi_interop_semaphore_handle SemHandle)
API to destroy the external semaphore handle.
pi_result piextWaitExternalSemaphore (pi_queue Queue, pi_interop_semaphore_handle SemHandle, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
API to instruct the queue with a non-blocking wait on an external semaphore.
pi_result piextSignalExternalSemaphore (pi_queue Queue, pi_interop_semaphore_handle SemHandle, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
API to instruct the queue to signal the external semaphore handle once all previous commands have completed execution.
pi_result piKernelGetGroupInfo (pi_kernel Kernel, pi_device Device, pi_kernel_group_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piKernelGetSubGroupInfo (pi_kernel Kernel, pi_device Device, pi_kernel_sub_group_info ParamName, size_t InputValueSize, const void *InputValue, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
API to query information from the sub-group from a kernel.
pi_result piKernelRetain (pi_kernel Kernel)
pi_result piKernelRelease (pi_kernel Kernel)
pi_result piEnqueueKernelLaunch (pi_queue Queue, pi_kernel Kernel, pi_uint32 WorkDim, const size_t *GlobalWorkOffset, const size_t *GlobalWorkSize, const size_t *LocalWorkSize, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *OutEvent)
pi_result piextKernelCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, pi_program Program, bool OwnNativeHandle, pi_kernel *Kernel)
Creates PI kernel object from a native handle.
pi_result piextKernelGetNativeHandle (pi_kernel Kernel, pi_native_handle *NativeHandle)
Gets the native handle of a PI kernel object.
pi_result piEventCreate (pi_context Context, pi_event *RetEvent)
Create PI event object in a signalled/completed state.
pi_result piEventGetInfo (pi_event Event, pi_event_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piEventGetProfilingInfo (pi_event Event, pi_profiling_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piEventsWait (pi_uint32 NumEvents, const pi_event *EventList)
pi_result piEventSetCallback (pi_event Event, pi_int32 CommandExecCallbackType, void(*PFnNotify)(pi_event Event, pi_int32 EventCommandStatus, void *UserData), void *UserData)
pi_result piEventSetStatus (pi_event Event, pi_int32 ExecutionStatus)
pi_result piEventRetain (pi_event Event)
pi_result piEventRelease (pi_event Event)
pi_result piextEventGetNativeHandle (pi_event Event, pi_native_handle *NativeHandle)
Gets the native handle of a PI event object.
pi_result piextEventCreateWithNativeHandle (pi_native_handle NativeHandle, pi_context Context, bool OwnNativeHandle, pi_event *Event)
Creates PI event object from a native handle.
pi_result piSamplerCreate (pi_context Context, const pi_sampler_properties *SamplerProperties, pi_sampler *RetSampler)
pi_result piSamplerGetInfo (pi_sampler Sampler, pi_sampler_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piSamplerRetain (pi_sampler Sampler)
pi_result piSamplerRelease (pi_sampler Sampler)
pi_result piEnqueueEventsWait (pi_queue Queue, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *OutEvent)
pi_result piEnqueueEventsWaitWithBarrier (pi_queue Queue, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *OutEvent)
pi_result piEnqueueMemBufferRead (pi_queue Queue, pi_mem Src, pi_bool BlockingRead, size_t Offset, size_t Size, void *Dst, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferReadRect (pi_queue Queue, pi_mem Buffer, pi_bool BlockingRead, pi_buff_rect_offset BufferOffset, pi_buff_rect_offset HostOffset, pi_buff_rect_region Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, void *Ptr, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferWrite (pi_queue Queue, pi_mem Buffer, pi_bool BlockingWrite, size_t Offset, size_t Size, const void *Ptr, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferWriteRect (pi_queue Queue, pi_mem Buffer, pi_bool BlockingWrite, pi_buff_rect_offset BufferOffset, pi_buff_rect_offset HostOffset, pi_buff_rect_region Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, const void *Ptr, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferCopy (pi_queue Queue, pi_mem SrcMem, pi_mem DstMem, size_t SrcOffset, size_t DstOffset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferCopyRect (pi_queue Queue, pi_mem SrcMem, pi_mem DstMem, pi_buff_rect_offset SrcOrigin, pi_buff_rect_offset DstOrigin, pi_buff_rect_region Region, size_t SrcRowPitch, size_t SrcSlicePitch, size_t DstRowPitch, size_t DstSlicePitch, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferFill (pi_queue Queue, pi_mem Buffer, const void *Pattern, size_t PatternSize, size_t Offset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemBufferMap (pi_queue Queue, pi_mem Mem, pi_bool BlockingMap, pi_map_flags MapFlags, size_t Offset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *OutEvent, void **RetMap)
pi_result piEnqueueMemUnmap (pi_queue Queue, pi_mem Mem, void *MappedPtr, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *OutEvent)
pi_result piMemImageGetInfo (pi_mem Image, pi_image_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piEnqueueMemImageRead (pi_queue Queue, pi_mem Image, pi_bool BlockingRead, pi_image_offset Origin, pi_image_region Region, size_t RowPitch, size_t SlicePitch, void *Ptr, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemImageWrite (pi_queue Queue, pi_mem Image, pi_bool BlockingWrite, pi_image_offset Origin, pi_image_region Region, size_t InputRowPitch, size_t InputSlicePitch, const void *Ptr, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemImageCopy (pi_queue Queue, pi_mem SrcImage, pi_mem DstImage, pi_image_offset SrcOrigin, pi_image_offset DstOrigin, pi_image_region Region, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piEnqueueMemImageFill (pi_queue Queue, pi_mem Image, const void *FillColor, const size_t *Origin, const size_t *Region, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
pi_result piMemBufferPartition (pi_mem Buffer, pi_mem_flags Flags, pi_buffer_create_type BufferCreateType, void *BufferCreateInfo, pi_mem *RetMem)
pi_result piextGetDeviceFunctionPointer (pi_device Device, pi_program Program, const char *FunctionName, pi_uint64 *FunctionPointerRet)
Retrieves a device function pointer to a user-defined function.
pi_result piextGetGlobalVariablePointer (pi_device Device, pi_program Program, const char *GlobalVariableName, size_t *GlobalVariableSize, void **GlobalVariablePointerRet)
pi_result piextUSMDeviceAlloc (void **ResultPtr, pi_context Context, pi_device Device, pi_usm_mem_properties *Properties, size_t Size, pi_uint32 Alignment)
Allocates device memory.
pi_result piextUSMSharedAlloc (void **ResultPtr, pi_context Context, pi_device Device, pi_usm_mem_properties *Properties, size_t Size, pi_uint32 Alignment)
Allocates memory accessible on both host and device.
pi_result piextUSMPitchedAlloc (void **ResultPtr, size_t *ResultPitch, pi_context Context, pi_device Device, pi_usm_mem_properties *Properties, size_t WidthInBytes, size_t Height, unsigned int ElementSizeBytes)
Allocates memory accessible on device.
pi_result piextUSMHostAlloc (void **ResultPtr, pi_context Context, pi_usm_mem_properties *Properties, size_t Size, pi_uint32 Alignment)
Allocates host memory accessible by the device.
pi_result piextUSMFree (pi_context Context, void *Ptr)
Indicates that the allocated USM memory is no longer needed on the runtime side.
pi_result piextKernelSetArgPointer (pi_kernel Kernel, pi_uint32 ArgIndex, size_t ArgSize, const void *ArgValue)
Sets up pointer arguments for CL kernels.
pi_result piextUSMEnqueueFill (pi_queue Queue, void *Ptr, const void *Pattern, size_t PatternSize, size_t Count, pi_uint32 NumEventsInWaitlist, const pi_event *EventsWaitlist, pi_event *Event)
USM Fill API.
pi_result piextUSMEnqueueMemcpy (pi_queue Queue, pi_bool Blocking, void *DstPtr, const void *SrcPtr, size_t Size, pi_uint32 NumEventsInWaitlist, const pi_event *EventsWaitlist, pi_event *Event)
USM Memcpy API.
pi_result piextUSMEnqueuePrefetch (pi_queue Queue, const void *Ptr, size_t Size, pi_usm_migration_flags Flags, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *OutEvent)
Hint to migrate memory to the device.
pi_result piextUSMEnqueueMemAdvise (pi_queue Queue, const void *Ptr, size_t Length, pi_mem_advice Advice, pi_event *OutEvent)
USM Memadvise API.
pi_result piextUSMEnqueueFill2D (pi_queue Queue, void *Ptr, size_t Pitch, size_t PatternSize, const void *Pattern, size_t Width, size_t Height, pi_uint32 NumEventsWaitList, const pi_event *EventsWaitList, pi_event *Event)
USM 2D fill API.
pi_result piextUSMEnqueueMemset2D (pi_queue Queue, void *Ptr, size_t Pitch, int Value, size_t Width, size_t Height, pi_uint32 NumEventsWaitList, const pi_event *EventsWaitlist, pi_event *Event)
USM 2D Memset API.
pi_result piextUSMEnqueueMemcpy2D (pi_queue Queue, pi_bool Blocking, void *DstPtr, size_t DstPitch, const void *SrcPtr, size_t SrcPitch, size_t Width, size_t Height, pi_uint32 NumEventsInWaitlist, const pi_event *EventWaitlist, pi_event *Event)
USM 2D Memcpy API.
pi_result piextUSMGetMemAllocInfo (pi_context Context, const void *Ptr, pi_mem_alloc_info ParamName, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
API to query information about USM allocated pointers Valid Queries: PI_MEM_ALLOC_TYPE returns host/device/shared pi_host_usm value PI_MEM_ALLOC_BASE_PTR returns the base ptr of an allocation if the queried pointer fell inside an allocation.
pi_result piextUSMImport (const void *HostPtr, size_t Size, pi_context Context)
Import host system memory into USM.
pi_result piextUSMRelease (const void *HostPtr, pi_context Context)
Release host system memory from USM.
pi_result piextEnqueueDeviceGlobalVariableWrite (pi_queue Queue, pi_program Program, const char *Name, pi_bool BlockingWrite, size_t Count, size_t Offset, const void *Src, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *Event)
Device global variable.
pi_result piextEnqueueDeviceGlobalVariableRead (pi_queue Queue, pi_program Program, const char *Name, pi_bool BlockingRead, size_t Count, size_t Offset, void *Dst, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *Event)
API reading data from a device global variable to host.
pi_result piextEnqueueReadHostPipe (pi_queue Queue, pi_program Program, const char *PipeSymbol, pi_bool Blocking, void *Ptr, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *Event)
Plugin.
pi_result piextEnqueueWriteHostPipe (pi_queue Queue, pi_program Program, const char *PipeSymbol, pi_bool Blocking, void *Ptr, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event *EventsWaitList, pi_event *Event)
Write to pipe of a given name.
pi_result piKernelSetExecInfo (pi_kernel Kernel, pi_kernel_exec_info ParamName, size_t ParamValueSize, const void *ParamValue)
API to set attributes controlling kernel execution.
pi_result piextProgramSetSpecializationConstant (pi_program Prog, pi_uint32 SpecID, size_t Size, const void *SpecValue)
Sets a specialization constant to a specific value.
pi_result piextCommandBufferCreate (pi_context Context, pi_device Device, const pi_ext_command_buffer_desc *Desc, pi_ext_command_buffer *RetCommandBuffer)
API to create a command-buffer.
pi_result piextCommandBufferRetain (pi_ext_command_buffer CommandBuffer)
API to increment the reference count of the command-buffer.
pi_result piextCommandBufferRelease (pi_ext_command_buffer CommandBuffer)
API to decrement the reference count of the command-buffer.
pi_result piextCommandBufferFinalize (pi_ext_command_buffer CommandBuffer)
API to stop command-buffer recording such that no more commands can be appended, and makes the command-buffer ready to enqueue on a command-queue.
pi_result piextCommandBufferNDRangeKernel (pi_ext_command_buffer CommandBuffer, pi_kernel Kernel, pi_uint32 WorkDim, const size_t *GlobalWorkOffset, const size_t *GlobalWorkSize, const size_t *LocalWorkSize, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint, pi_ext_command_buffer_command *Command)
API to append a kernel execution command to the command-buffer.
pi_result piextCommandBufferMemcpyUSM (pi_ext_command_buffer CommandBuffer, void *DstPtr, const void *SrcPtr, size_t Size, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
API to append a USM memcpy command to the command-buffer.
pi_result piextCommandBufferMemBufferCopy (pi_ext_command_buffer CommandBuffer, pi_mem SrcMem, pi_mem DstMem, size_t SrcOffset, size_t DstOffset, size_t Size, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
API to append a mem buffer copy command to the command-buffer.
pi_result piextCommandBufferMemBufferCopyRect (pi_ext_command_buffer CommandBuffer, pi_mem SrcMem, pi_mem DstMem, pi_buff_rect_offset SrcOrigin, pi_buff_rect_offset DstOrigin, pi_buff_rect_region Region, size_t SrcRowPitch, size_t SrcSlicePitch, size_t DstRowPitch, size_t DstSlicePitch, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
API to append a rectangular mem buffer copy command to the command-buffer.
pi_result piextCommandBufferMemBufferRead (pi_ext_command_buffer CommandBuffer, pi_mem Buffer, size_t Offset, size_t Size, void *Dst, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
API to append a mem buffer read command to the command-buffer.
pi_result piextCommandBufferMemBufferReadRect (pi_ext_command_buffer CommandBuffer, pi_mem Buffer, pi_buff_rect_offset BufferOffset, pi_buff_rect_offset HostOffset, pi_buff_rect_region Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, void *Ptr, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
API to append a rectangular mem buffer read command to the command-buffer.
pi_result piextCommandBufferMemBufferWrite (pi_ext_command_buffer CommandBuffer, pi_mem Buffer, size_t Offset, size_t Size, const void *Ptr, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
API to append a mem buffer write command to the command-buffer.
pi_result piextCommandBufferMemBufferWriteRect (pi_ext_command_buffer CommandBuffer, pi_mem Buffer, pi_buff_rect_offset BufferOffset, pi_buff_rect_offset HostOffset, pi_buff_rect_region Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, const void *Ptr, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
API to append a rectangular mem buffer write command to the command-buffer.
pi_result piextEnqueueCommandBuffer (pi_ext_command_buffer CommandBuffer, pi_queue Queue, pi_uint32 NumEventsInWaitList, const pi_event *EventWaitList, pi_event *Event)
API to submit the command-buffer to queue for execution, returns an error if the command-buffer is not finalized or another instance of the same command-buffer is currently executing.
pi_result piextCommandBufferUpdateKernelLaunch (pi_ext_command_buffer_command Command, pi_ext_command_buffer_update_kernel_launch_desc *Desc)
API to update a kernel launch command inside of a command-buffer.
pi_result piextCommandBufferRetainCommand (pi_ext_command_buffer_command Command)
API to increment the reference count of a command-buffer command.
pi_result piextCommandBufferReleaseCommand (pi_ext_command_buffer_command Command)
API to decrement the reference count of a command-buffer command.
pi_result piextPluginGetOpaqueData (void *opaque_data_param, void **opaque_data_return)
API to get Plugin internal data, opaque to SYCL RT.
pi_result piTearDown (void *PluginParameter)
API to notify that the plugin should clean up its resources.
pi_result piGetDeviceAndHostTimer (pi_device Device, uint64_t *DeviceTime, uint64_t *HostTime)
Queries device for it's global timestamp in nanoseconds, and updates HostTime with the value of the host timer at the closest possible point in time to that at which DeviceTime was returned.
pi_result piextEnablePeerAccess (pi_device command_device, pi_device peer_device)
pi_result piextDisablePeerAccess (pi_device command_device, pi_device peer_device)
pi_result piextPeerAccessGetInfo (pi_device command_device, pi_device peer_device, pi_peer_attr attr, size_t ParamValueSize, void *ParamValue, size_t *ParamValueSizeRet)
pi_result piextCommandBufferMemBufferFill (pi_ext_command_buffer CommandBuffer, pi_mem Buffer, const void *Pattern, size_t PatternSize, size_t Offset, size_t Size, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
API to append a mem buffer fill command to the command-buffer.
pi_result piextCommandBufferFillUSM (pi_ext_command_buffer CommandBuffer, void *Ptr, const void *Pattern, size_t PatternSize, size_t Size, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
API to append a USM fill command to the command-buffer.
pi_result piextCommandBufferPrefetchUSM (pi_ext_command_buffer CommandBuffer, const void *Ptr, size_t Size, pi_usm_migration_flags Flags, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
API to append a USM Prefetch command to the command-buffer.
pi_result piextCommandBufferAdviseUSM (pi_ext_command_buffer CommandBuffer, const void *Ptr, size_t Length, pi_mem_advice Advice, pi_uint32 NumSyncPointsInWaitList, const pi_ext_sync_point *SyncPointWaitList, pi_ext_sync_point *SyncPoint)
API to append a USM Advise command to the command-buffer.
pi_result piextEnqueueCooperativeKernelLaunch (pi_queue, pi_kernel, pi_uint32, const size_t *, const size_t *, const size_t *, pi_uint32, const pi_event *, pi_event *)
pi_result piextKernelSuggestMaxCooperativeGroupCount (pi_kernel, size_t, size_t, pi_uint32 *)
Gets the max work group count for a cooperative kernel.
pi_result piPluginInit (pi_plugin *PluginInit)
Macro Definition Documentation
_PI_API [1/2]
#define _PI_API (api) decltype(pi2ur::api) api;
Definition at line 1297 of file pi_native_cpu.cpp.
_PI_API [2/2]
#define _PI_API (api) (PluginInit->PiFunctionTable).api = (decltype(&::api))(&api);
Definition at line 1297 of file pi_native_cpu.cpp.
EXPORT_PI_API_SYMBOLS
#define EXPORT_PI_API_SYMBOLS
Definition at line 13 of file pi_native_cpu.cpp.
Function Documentation
piContextCreate()
pi_result piContextCreate (const pi_context_properties * Properties, pi_uint32 NumDevices, const pi_device * Devices, void(*)(const char *ErrInfo, const void *PrivateInfo, size_t CB, void *UserData) PFnNotify, void * UserData, pi_context * RetContext)
Definition at line 120 of file pi_native_cpu.cpp.
References pi2ur::piContextCreate().
piContextGetInfo()
pi_result piContextGetInfo (pi_context Context, pi_context_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 130 of file pi_native_cpu.cpp.
References pi2ur::piContextGetInfo().
piContextRelease()
pi_result piContextRelease (pi_context Context)
Definition at line 164 of file pi_native_cpu.cpp.
References pi2ur::piContextRelease().
piContextRetain()
pi_result piContextRetain (pi_context Context)
Definition at line 159 of file pi_native_cpu.cpp.
References pi2ur::piContextRetain().
piDeviceGetInfo()
pi_result piDeviceGetInfo (pi_device Device, pi_device_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Returns requested info for provided native device Return PI_DEVICE_INFO_EXTENSION_DEVICELIB_ASSERT for PI_DEVICE_INFO_EXTENSIONS query when the device supports native asserts.
Definition at line 83 of file pi_native_cpu.cpp.
References pi2ur::piDeviceGetInfo().
piDevicePartition()
pi_result piDevicePartition (pi_device Device, const pi_device_partition_property * Properties, pi_uint32 NumDevices, pi_device * OutDevices, pi_uint32 * OutNumDevices)
Definition at line 90 of file pi_native_cpu.cpp.
References pi2ur::piDevicePartition().
piDeviceRelease()
pi_result piDeviceRelease (pi_device Device)
Definition at line 79 of file pi_native_cpu.cpp.
References pi2ur::piDeviceRelease().
piDeviceRetain()
pi_result piDeviceRetain (pi_device Device)
Definition at line 75 of file pi_native_cpu.cpp.
References pi2ur::piDeviceRetain().
piDevicesGet()
pi_result piDevicesGet (pi_platform Platform, pi_device_type DeviceType, pi_uint32 NumEntries, pi_device * Devices, pi_uint32 * NumDevices)
Definition at line 68 of file pi_native_cpu.cpp.
References pi2ur::piDevicesGet().
piEnqueueEventsWait()
pi_result piEnqueueEventsWait (pi_queue Queue, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * OutEvent)
Definition at line 660 of file pi_native_cpu.cpp.
References pi2ur::piEnqueueEventsWait().
piEnqueueEventsWaitWithBarrier()
pi_result piEnqueueEventsWaitWithBarrier (pi_queue Queue, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * OutEvent)
Definition at line 668 of file pi_native_cpu.cpp.
References pi2ur::piEnqueueEventsWaitWithBarrier().
piEnqueueKernelLaunch()
pi_result piEnqueueKernelLaunch (pi_queue Queue, pi_kernel Kernel, pi_uint32 WorkDim, const size_t * GlobalWorkOffset, const size_t * GlobalWorkSize, const size_t * LocalWorkSize, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * OutEvent)
Definition at line 546 of file pi_native_cpu.cpp.
References pi2ur::piEnqueueKernelLaunch().
piEnqueueMemBufferCopy()
pi_result piEnqueueMemBufferCopy (pi_queue Queue, pi_mem SrcMem, pi_mem DstMem, size_t SrcOffset, size_t DstOffset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 729 of file pi_native_cpu.cpp.
References pi2ur::piEnqueueMemBufferCopy().
piEnqueueMemBufferCopyRect()
pi_result piEnqueueMemBufferCopyRect (pi_queue Queue, pi_mem SrcMem, pi_mem DstMem, pi_buff_rect_offset SrcOrigin, pi_buff_rect_offset DstOrigin, pi_buff_rect_region Region, size_t SrcRowPitch, size_t SrcSlicePitch, size_t DstRowPitch, size_t DstSlicePitch, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 740 of file pi_native_cpu.cpp.
References pi2ur::piEnqueueMemBufferCopyRect().
piEnqueueMemBufferFill()
pi_result piEnqueueMemBufferFill (pi_queue Queue, pi_mem Buffer, const void * Pattern, size_t PatternSize, size_t Offset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 753 of file pi_native_cpu.cpp.
References pi2ur::piEnqueueMemBufferFill().
piEnqueueMemBufferMap()
pi_result piEnqueueMemBufferMap (pi_queue Queue, pi_mem Mem, pi_bool BlockingMap, pi_map_flags MapFlags, size_t Offset, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * OutEvent, void ** RetMap)
Definition at line 765 of file pi_native_cpu.cpp.
References pi2ur::piEnqueueMemBufferMap().
piEnqueueMemBufferRead()
pi_result piEnqueueMemBufferRead (pi_queue Queue, pi_mem Src, pi_bool BlockingRead, size_t Offset, size_t Size, void * Dst, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 677 of file pi_native_cpu.cpp.
References pi2ur::piEnqueueMemBufferRead().
piEnqueueMemBufferReadRect()
pi_result piEnqueueMemBufferReadRect (pi_queue Queue, pi_mem Buffer, pi_bool BlockingRead, pi_buff_rect_offset BufferOffset, pi_buff_rect_offset HostOffset, pi_buff_rect_region Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, void * Ptr, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 689 of file pi_native_cpu.cpp.
References pi2ur::piEnqueueMemBufferReadRect().
piEnqueueMemBufferWrite()
pi_result piEnqueueMemBufferWrite (pi_queue Queue, pi_mem Buffer, pi_bool BlockingWrite, size_t Offset, size_t Size, const void * Ptr, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 703 of file pi_native_cpu.cpp.
References pi2ur::piEnqueueMemBufferWrite().
piEnqueueMemBufferWriteRect()
pi_result piEnqueueMemBufferWriteRect (pi_queue Queue, pi_mem Buffer, pi_bool BlockingWrite, pi_buff_rect_offset BufferOffset, pi_buff_rect_offset HostOffset, pi_buff_rect_region Region, size_t BufferRowPitch, size_t BufferSlicePitch, size_t HostRowPitch, size_t HostSlicePitch, const void * Ptr, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 715 of file pi_native_cpu.cpp.
References pi2ur::piEnqueueMemBufferWriteRect().
piEnqueueMemImageCopy()
pi_result piEnqueueMemImageCopy (pi_queue Queue, pi_mem SrcImage, pi_mem DstImage, pi_image_offset SrcOrigin, pi_image_offset DstOrigin, pi_image_region Region, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 818 of file pi_native_cpu.cpp.
References pi2ur::piEnqueueMemImageCopy().
piEnqueueMemImageFill()
pi_result piEnqueueMemImageFill (pi_queue Queue, pi_mem Image, const void * FillColor, const size_t * Origin, const size_t * Region, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 827 of file pi_native_cpu.cpp.
References pi2ur::piEnqueueMemImageFill().
piEnqueueMemImageRead()
pi_result piEnqueueMemImageRead (pi_queue Queue, pi_mem Image, pi_bool BlockingRead, pi_image_offset Origin, pi_image_region Region, size_t RowPitch, size_t SlicePitch, void * Ptr, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 792 of file pi_native_cpu.cpp.
References pi2ur::piEnqueueMemImageRead().
piEnqueueMemImageWrite()
pi_result piEnqueueMemImageWrite (pi_queue Queue, pi_mem Image, pi_bool BlockingWrite, pi_image_offset Origin, pi_image_region Region, size_t InputRowPitch, size_t InputSlicePitch, const void * Ptr, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * Event)
Definition at line 804 of file pi_native_cpu.cpp.
References pi2ur::piEnqueueMemImageWrite().
piEnqueueMemUnmap()
pi_result piEnqueueMemUnmap (pi_queue Queue, pi_mem Mem, void * MappedPtr, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * OutEvent)
Definition at line 776 of file pi_native_cpu.cpp.
References pi2ur::piEnqueueMemUnmap().
piEventCreate()
pi_result piEventCreate (pi_context context, pi_event * ret_event)
Create PI event object in a signalled/completed state.
Parameters
context is the PI context of the event.
ret_event is the PI even created.
Definition at line 576 of file pi_native_cpu.cpp.
References pi2ur::piEventCreate().
piEventGetInfo()
pi_result piEventGetInfo (pi_event Event, pi_event_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 580 of file pi_native_cpu.cpp.
References pi2ur::piEventGetInfo().
piEventGetProfilingInfo()
pi_result piEventGetProfilingInfo (pi_event Event, pi_profiling_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 587 of file pi_native_cpu.cpp.
References pi2ur::piEventGetProfilingInfo().
piEventRelease()
pi_result piEventRelease (pi_event Event)
Definition at line 614 of file pi_native_cpu.cpp.
References pi2ur::piEventRelease().
piEventRetain()
pi_result piEventRetain (pi_event Event)
Definition at line 612 of file pi_native_cpu.cpp.
References pi2ur::piEventRetain().
piEventSetCallback()
pi_result piEventSetCallback (pi_event Event, pi_int32 CommandExecCallbackType, void(*)(pi_event Event, pi_int32 EventCommandStatus, void *UserData) PFnNotify, void * UserData)
Definition at line 599 of file pi_native_cpu.cpp.
References pi2ur::piEventSetCallback().
piEventSetStatus()
pi_result piEventSetStatus (pi_event Event, pi_int32 ExecutionStatus)
Definition at line 608 of file pi_native_cpu.cpp.
References pi2ur::piEventSetStatus().
piEventsWait()
pi_result piEventsWait (pi_uint32 NumEvents, const pi_event * EventList)
Definition at line 595 of file pi_native_cpu.cpp.
References pi2ur::piEventsWait().
piextBindlessImageSamplerCreate()
pi_result piextBindlessImageSamplerCreate (pi_context context, const pi_sampler_properties * sampler_properties, float min_mipmap_level_clamp, float max_mipmap_level_clamp, float max_anisotropy, pi_sampler * result_sampler)
API to create samplers for bindless images.
Parameters
context is the pi_context
device is the pi_device
sampler_properties is the pointer to the sampler properties bitfield
min_mipmap_level_clamp is the minimum mipmap level to sample from
max_mipmap_level_clamp is the maximum mipmap level to sample from
max_anisotropy is the maximum anisotropic ratio
result_sampler is the returned sampler
Definition at line 407 of file pi_native_cpu.cpp.
References pi2ur::piextBindlessImageSamplerCreate().
piextCommandBufferAdviseUSM()
pi_result piextCommandBufferAdviseUSM (pi_ext_command_buffer command_buffer, const void * ptr, size_t length, pi_mem_advice advice, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a USM Advise command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
ptr is the data to be advised.
length is the size in bytes of the memory to advise.
advice is device specific advice.
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1273 of file pi_native_cpu.cpp.
References pi2ur::piextCommandBufferAdviseUSM().
piextCommandBufferCreate()
pi_result piextCommandBufferCreate (pi_context context, pi_device device, const pi_ext_command_buffer_desc * desc, pi_ext_command_buffer * ret_command_buffer)
API to create a command-buffer.
Parameters
context The context to associate the command-buffer with.
device The device to associate the command-buffer with.
desc Descriptor for the new command-buffer.
ret_command_buffer Pointer to fill with the address of the new command-buffer.
Definition at line 1076 of file pi_native_cpu.cpp.
References pi2ur::piextCommandBufferCreate().
piextCommandBufferFillUSM()
pi_result piextCommandBufferFillUSM (pi_ext_command_buffer command_buffer, void * ptr, const void * pattern, size_t pattern_size, size_t size, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a USM fill command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
ptr pointer to the USM allocation to fill.
pattern pointer to the pattern to fill ptr with.
pattern_size size of the pattern in bytes.
size fill size in bytes.
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1253 of file pi_native_cpu.cpp.
References pi2ur::piextCommandBufferFillUSM().
piextCommandBufferFinalize()
pi_result piextCommandBufferFinalize (pi_ext_command_buffer command_buffer)
API to stop command-buffer recording such that no more commands can be appended, and makes the command-buffer ready to enqueue on a command-queue.
Parameters
command_buffer The command_buffer to finalize.
Definition at line 1091 of file pi_native_cpu.cpp.
References pi2ur::piextCommandBufferFinalize().
piextCommandBufferMemBufferCopy()
pi_result piextCommandBufferMemBufferCopy (pi_ext_command_buffer command_buffer, pi_mem src_buffer, pi_mem dst_buffer, size_t src_offset, size_t dst_offset, size_t size, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a mem buffer copy command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
src_buffer is the data to be copied
dst_buffer is the location the data will be copied
src_offset offset into src_buffer
dst_offset offset into dst_buffer
size is number of bytes to copy
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1116 of file pi_native_cpu.cpp.
References pi2ur::piextCommandBufferMemBufferCopy().
piextCommandBufferMemBufferCopyRect()
pi_result piextCommandBufferMemBufferCopyRect (pi_ext_command_buffer command_buffer, pi_mem src_buffer, pi_mem dst_buffer, pi_buff_rect_offset src_origin, pi_buff_rect_offset dst_origin, pi_buff_rect_region region, size_t src_row_pitch, size_t src_slice_pitch, size_t dst_row_pitch, size_t dst_slice_pitch, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a rectangular mem buffer copy command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
src_buffer is the data to be copied
dst_buffer is the location the data will be copied
src_origin offset for the start of the region to copy in src_buffer
dst_origin offset for the start of the region to copy in dst_buffer
region The size of the region to be copied
src_row_pitch Row pitch for the src data
src_slice_pitch Slice pitch for the src data
dst_row_pitch Row pitch for the dst data
dst_slice_pitch Slice pitch for the dst data
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1126 of file pi_native_cpu.cpp.
References pi2ur::piextCommandBufferMemBufferCopyRect().
piextCommandBufferMemBufferFill()
pi_result piextCommandBufferMemBufferFill (pi_ext_command_buffer command_buffer, pi_mem buffer, const void * pattern, size_t pattern_size, size_t offset, size_t size, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a mem buffer fill command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
buffer is the location to fill the data.
pattern pointer to the pattern to fill the buffer with.
pattern_size size of the pattern in bytes.
offset Offset into the buffer to fill from.
size fill size in bytes.
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1243 of file pi_native_cpu.cpp.
References pi2ur::piextCommandBufferMemBufferFill().
piextCommandBufferMemBufferRead()
pi_result piextCommandBufferMemBufferRead (pi_ext_command_buffer command_buffer, pi_mem buffer, size_t offset, size_t size, void * dst, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a mem buffer read command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
buffer is the data to be read
offset offset into buffer
size is number of bytes to read
dst is the pointer to the destination
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1138 of file pi_native_cpu.cpp.
References pi2ur::piextCommandBufferMemBufferRead().
piextCommandBufferMemBufferReadRect()
pi_result piextCommandBufferMemBufferReadRect (pi_ext_command_buffer command_buffer, pi_mem buffer, pi_buff_rect_offset buffer_offset, pi_buff_rect_offset host_offset, pi_buff_rect_region region, size_t buffer_row_pitch, size_t buffer_slice_pitch, size_t host_row_pitch, size_t host_slice_pitch, void * ptr, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a rectangular mem buffer read command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
buffer is the data to be read
buffer_offset offset for the start of the region to read in buffer
host_offset offset for the start of the region to be written from ptr
region The size of the region to read
buffer_row_pitch Row pitch for the source buffer data
buffer_slice_pitch Slice pitch for the source buffer data
host_row_pitch Row pitch for the destination data ptr
host_slice_pitch Slice pitch for the destination data ptr
ptr is the location the data will be written
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1147 of file pi_native_cpu.cpp.
References pi2ur::piextCommandBufferMemBufferReadRect().
piextCommandBufferMemBufferWrite()
pi_result piextCommandBufferMemBufferWrite (pi_ext_command_buffer command_buffer, pi_mem buffer, size_t offset, size_t size, const void * ptr, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a mem buffer write command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
buffer is the location to write the data
offset offset into buffer
size is number of bytes to write
ptr is the pointer to the source
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1160 of file pi_native_cpu.cpp.
References pi2ur::piextCommandBufferMemBufferWrite().
piextCommandBufferMemBufferWriteRect()
pi_result piextCommandBufferMemBufferWriteRect (pi_ext_command_buffer command_buffer, pi_mem buffer, pi_buff_rect_offset buffer_offset, pi_buff_rect_offset host_offset, pi_buff_rect_region region, size_t buffer_row_pitch, size_t buffer_slice_pitch, size_t host_row_pitch, size_t host_slice_pitch, const void * ptr, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a rectangular mem buffer write command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
buffer is the location to write the data
buffer_offset offset for the start of the region to write in buffer
host_offset offset for the start of the region to be read from ptr
region The size of the region to write
buffer_row_pitch Row pitch for the buffer data
buffer_slice_pitch Slice pitch for the buffer data
host_row_pitch Row pitch for the source data ptr
host_slice_pitch Slice pitch for the source data ptr
ptr is the pointer to the source
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1169 of file pi_native_cpu.cpp.
References pi2ur::piextCommandBufferMemBufferWriteRect().
piextCommandBufferMemcpyUSM()
pi_result piextCommandBufferMemcpyUSM (pi_ext_command_buffer command_buffer, void * dst_ptr, const void * src_ptr, size_t size, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a USM memcpy command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
dst_ptr is the location the data will be copied
src_ptr is the data to be copied
size is number of bytes to copy
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1107 of file pi_native_cpu.cpp.
References pi2ur::piextCommandBufferMemcpyUSM().
piextCommandBufferNDRangeKernel()
pi_result piextCommandBufferNDRangeKernel (pi_ext_command_buffer command_buffer, pi_kernel kernel, pi_uint32 work_dim, const size_t * global_work_offset, const size_t * global_work_size, const size_t * local_work_size, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point, pi_ext_command_buffer_command * command)
API to append a kernel execution command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
kernel The kernel to append.
work_dim Dimension of the kernel execution.
global_work_offset Offset to use when executing kernel.
global_work_size Global work size to use when executing kernel.
local_work_size Local work size to use when executing kernel.
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this kernel execution.
command Return pointer to the command representing this kernel execution.
Definition at line 1095 of file pi_native_cpu.cpp.
References pi2ur::piextCommandBufferNDRangeKernel().
piextCommandBufferPrefetchUSM()
pi_result piextCommandBufferPrefetchUSM (pi_ext_command_buffer command_buffer, const void * ptr, size_t size, pi_usm_migration_flags flags, pi_uint32 num_sync_points_in_wait_list, const pi_ext_sync_point * sync_point_wait_list, pi_ext_sync_point * sync_point)
API to append a USM Prefetch command to the command-buffer.
Parameters
command_buffer The command-buffer to append onto.
ptr points to the memory to migrate.
size is the number of bytes to migrate.
flags is a bitfield used to specify memory migration options.
num_sync_points_in_wait_list The number of sync points in the provided wait list.
sync_point_wait_list A list of sync points that this command must wait on.
sync_point The sync_point associated with this memory operation.
Definition at line 1264 of file pi_native_cpu.cpp.
References pi2ur::piextCommandBufferPrefetchUSM().
piextCommandBufferRelease()
pi_result piextCommandBufferRelease (pi_ext_command_buffer command_buffer)
API to decrement the reference count of the command-buffer.
After the command_buffer reference count becomes zero and has finished execution, the command-buffer is deleted.
Parameters
command_buffer The command_buffer to release.
Definition at line 1087 of file pi_native_cpu.cpp.
References pi2ur::piextCommandBufferRelease().
piextCommandBufferReleaseCommand()
pi_result piextCommandBufferReleaseCommand (pi_ext_command_buffer_command command)
API to decrement the reference count of a command-buffer command.
After the command reference count becomes zero, the command is deleted.
Parameters
command The command to release.
Definition at line 1203 of file pi_native_cpu.cpp.
References pi2ur::piextCommandBufferReleaseCommand().
piextCommandBufferRetain()
pi_result piextCommandBufferRetain (pi_ext_command_buffer command_buffer)
API to increment the reference count of the command-buffer.
Parameters
command_buffer The command_buffer to retain.
Definition at line 1083 of file pi_native_cpu.cpp.
References pi2ur::piextCommandBufferRetain().
piextCommandBufferRetainCommand()
pi_result piextCommandBufferRetainCommand (pi_ext_command_buffer_command command)
API to increment the reference count of a command-buffer command.
Parameters
command The command to release.
Definition at line 1198 of file pi_native_cpu.cpp.
References pi2ur::piextCommandBufferRetainCommand().
piextCommandBufferUpdateKernelLaunch()
pi_result piextCommandBufferUpdateKernelLaunch (pi_ext_command_buffer_command command, pi_ext_command_buffer_update_kernel_launch_desc * desc)
API to update a kernel launch command inside of a command-buffer.
Parameters
command The command to be updated.
desc Descriptor which describes the updated parameters of the kernel launch.
Definition at line 1191 of file pi_native_cpu.cpp.
References pi2ur::piextCommandBufferUpdateKernelLaunch().
piextContextCreateWithNativeHandle()
pi_result piextContextCreateWithNativeHandle (pi_native_handle nativeHandle, pi_uint32 numDevices, const pi_device * devices, bool pluginOwnsNativeHandle, pi_context * context)
Creates PI context object from a native handle.
NOTE: The created PI object takes ownership of the native handle. NOTE: The number of devices and the list of devices is needed for Level Zero backend because there is no possilibity to query this information from context handle for Level Zero. If backend has API to query a list of devices from the context native handle then these parameters are ignored.
Parameters
nativeHandle is the native handle to create PI context from.
numDevices is the number of devices in the context. Parameter is ignored if number of devices can be queried from the context native handle for a backend.
devices is the list of devices in the context. Parameter is ignored if devices can be queried from the context native handle for a backend.
pluginOwnsNativeHandle Indicates whether the created PI object should take ownership of the native handle.
context is the PI context created from the native handle.
Returns
PI_SUCCESS if successfully created pi_context from the handle. PI_ERROR_OUT_OF_HOST_MEMORY if can't allocate memory for the pi_context object. PI_ERROR_INVALID_VALUE if numDevices == 0 or devices is NULL but backend doesn't have API to query a list of devices from the context native handle. PI_UNKNOWN_ERROR in case of another error.
Definition at line 150 of file pi_native_cpu.cpp.
References pi2ur::piextContextCreateWithNativeHandle().
piextContextGetNativeHandle()
pi_result piextContextGetNativeHandle (pi_context context, pi_native_handle * nativeHandle)
Gets the native handle of a PI context object.
Parameters
context is the PI context to get the native handle of.
nativeHandle is the native handle of context.
Definition at line 145 of file pi_native_cpu.cpp.
References pi2ur::piextContextGetNativeHandle().
piextContextSetExtendedDeleter()
pi_result piextContextSetExtendedDeleter (pi_context Context, pi_context_extended_deleter Function, void * UserData)
Definition at line 139 of file pi_native_cpu.cpp.
References pi2ur::piextContextSetExtendedDeleter().
piextDestroyExternalSemaphore()
pi_result piextDestroyExternalSemaphore (pi_context context, pi_device device, pi_interop_semaphore_handle sem_handle)
API to destroy the external semaphore handle.
Parameters
context is the pi_context
device is the pi_device
sem_handle is the interop semaphore handle to the external semaphore to be destroyed
Definition at line 494 of file pi_native_cpu.cpp.
References pi2ur::piextDestroyExternalSemaphore().
piextDeviceCreateWithNativeHandle()
pi_result piextDeviceCreateWithNativeHandle (pi_native_handle nativeHandle, pi_platform platform, pi_device * device)
Creates PI device object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI device from.
platform is the platform of the device (optional).
device is the PI device created from the native handle.
Definition at line 112 of file pi_native_cpu.cpp.
References pi2ur::piextDeviceCreateWithNativeHandle().
piextDeviceGetNativeHandle()
pi_result piextDeviceGetNativeHandle (pi_device device, pi_native_handle * nativeHandle)
Gets the native handle of a PI device object.
Parameters
device is the PI device to get the native handle of.
nativeHandle is the native handle of device.
Definition at line 106 of file pi_native_cpu.cpp.
References pi2ur::piextDeviceGetNativeHandle().
piextDeviceSelectBinary()
pi_result piextDeviceSelectBinary (pi_device Device, pi_device_binary * Binaries, pi_uint32 NumBinaries, pi_uint32 * SelectedBinaryInd)
Selects the most appropriate device binary based on runtime information and the IR characteristics.
Definition at line 99 of file pi_native_cpu.cpp.
References pi2ur::piextDeviceSelectBinary().
piextDisablePeerAccess()
pi_result piextDisablePeerAccess (pi_device command_device, pi_device peer_device)
Definition at line 1227 of file pi_native_cpu.cpp.
References pi2ur::piextDisablePeerAccess().
piextEnablePeerAccess()
pi_result piextEnablePeerAccess (pi_device command_device, pi_device peer_device)
Definition at line 1221 of file pi_native_cpu.cpp.
References pi2ur::piextEnablePeerAccess().
piextEnqueueCommandBuffer()
pi_result piextEnqueueCommandBuffer (pi_ext_command_buffer command_buffer, pi_queue queue, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
API to submit the command-buffer to queue for execution, returns an error if the command-buffer is not finalized or another instance of the same command-buffer is currently executing.
Parameters
command_buffer The command-buffer to be submitted.
queue The PI queue to submit on.
num_events_in_wait_list The number of events that this execution depends on.
event_wait_list List of pi_events to wait on.
event The pi_event associated with this enqueue.
Definition at line 1182 of file pi_native_cpu.cpp.
References pi2ur::piextEnqueueCommandBuffer().
piextEnqueueCooperativeKernelLaunch()
pi_result piextEnqueueCooperativeKernelLaunch (pi_queue queue, pi_kernel kernel, pi_uint32 work_dim, const size_t * global_work_offset, const size_t * global_work_size, const size_t * local_work_size, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
Definition at line 1282 of file pi_native_cpu.cpp.
piextEnqueueDeviceGlobalVariableRead()
pi_result piextEnqueueDeviceGlobalVariableRead (pi_queue Queue, pi_program Program, const char * Name, pi_bool BlockingRead, size_t Count, size_t Offset, void * Dst, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * Event)
API reading data from a device global variable to host.
Parameters
queue is the queue
program is the program containing the device global variable
blocking_read is true if the read should block
name is the unique identifier for the device global variable
count is the number of bytes to copy
offset is the byte offset into the device global variable to start copying
dst is a pointer to where the data must be copied to
num_events_in_wait_list is a number of events in the wait list
event_wait_list is the wait list
event is the resulting event
Queue is the queue
Program is the program containing the device global variable
Name is the unique identifier for the device global variable
BlockingRead is true if the read should block
Count is the number of bytes to copy
Offset is the byte offset into the device global variable to start copying
Dst is a pointer to where the data must be copied to
NumEventsInWaitList is a number of events in the wait list
EventWaitList is the wait list
Event is the resulting event
Definition at line 1005 of file pi_native_cpu.cpp.
References pi2ur::piextEnqueueDeviceGlobalVariableRead().
piextEnqueueDeviceGlobalVariableWrite()
pi_result piextEnqueueDeviceGlobalVariableWrite (pi_queue Queue, pi_program Program, const char * Name, pi_bool BlockingWrite, size_t Count, size_t Offset, const void * Src, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * Event)
Device global variable.
API for writing data from host to a device global variable.
Parameters
queue is the queue
program is the program containing the device global variable
blocking_write is true if the write should block
name is the unique identifier for the device global variable
count is the number of bytes to copy
offset is the byte offset into the device global variable to start copying
src is a pointer to where the data must be copied from
num_events_in_wait_list is a number of events in the wait list
event_wait_list is the wait list
event is the resulting event
Device global variable.
Parameters
Queue is the queue
Program is the program containing the device global variable
Name is the unique identifier for the device global variable
BlockingWrite is true if the write should block
Count is the number of bytes to copy
Offset is the byte offset into the device global variable to start copying
Src is a pointer to where the data must be copied from
NumEventsInWaitList is a number of events in the wait list
EventWaitList is the wait list
Event is the resulting event
Definition at line 996 of file pi_native_cpu.cpp.
References pi2ur::piextEnqueueDeviceGlobalVariableWrite().
piextEnqueueReadHostPipe()
pi_result piextEnqueueReadHostPipe (pi_queue Queue, pi_program Program, const char * PipeSymbol, pi_bool Blocking, void * Ptr, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * Event)
Plugin.
Read from pipe of a given name
Parameters
queue a valid host command-queue in which the read / write command will be queued. command_queue and program must be created with the same OpenCL context.
program a program object with a successfully built executable.
pipe_symbol the name of the program scope pipe global variable.
blocking indicate if the read and write operations are blocking or non-blocking
ptr a pointer to buffer in host memory that will hold resulting data from pipe
size size of the memory region to read or write, in bytes.
num_events_in_waitlist number of events in the wait list.
events_waitlist specify events that need to complete before this particular command can be executed.
event returns an event object that identifies this read / write command and can be used to query or queue a wait for this command to complete.
Plugin.
Parameters
Queue is the queue
Program is the program containing the device variable
PipeSymbol is the unique identifier for the device variable
Blocking is true if the write should block
Ptr is a pointer to where the data will be copied to
Size is size of the data that is read/written from/to pipe
NumEventsInWaitList is a number of events in the wait list
EventWaitList is the wait list
Event is the resulting event
Definition at line 1017 of file pi_native_cpu.cpp.
References sycl::_V1::detail::pi::die(), and PI_ASSERT.
piextEnqueueWriteHostPipe()
pi_result piextEnqueueWriteHostPipe (pi_queue Queue, pi_program Program, const char * PipeSymbol, pi_bool Blocking, void * Ptr, size_t Size, pi_uint32 NumEventsInWaitList, const pi_event * EventsWaitList, pi_event * Event)
Write to pipe of a given name.
Parameters
queue a valid host command-queue in which the read / write command will be queued. command_queue and program must be created with the same OpenCL context.
program a program object with a successfully built executable.
pipe_symbol the name of the program scope pipe global variable.
blocking indicate if the read and write operations are blocking or non-blocking
ptr a pointer to buffer in host memory that holds data to be written to host pipe.
size size of the memory region to read or write, in bytes.
num_events_in_waitlist number of events in the wait list.
events_waitlist specify events that need to complete before this particular command can be executed.
event returns an event object that identifies this read / write command and can be used to query or queue a wait for this command to complete.
Write to pipe of a given name.
Parameters
Queue is the queue
Program is the program containing the device variable
PipeSymbol is the unique identifier for the device variable
Blocking is true if the write should block
Ptr is a pointer to where the data must be copied from
Size is size of the data that is read/written from/to pipe
NumEventsInWaitList is a number of events in the wait list
EventWaitList is the wait list
Event is the resulting event
Definition at line 1039 of file pi_native_cpu.cpp.
References sycl::_V1::detail::pi::die(), and PI_ASSERT.
piextEventCreateWithNativeHandle()
pi_result piextEventCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, bool ownNativeHandle, pi_event * event)
Creates PI event object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI event from.
context is the corresponding PI context
pluginOwnsNativeHandle Indicates whether the created PI object should take ownership of the native handle.
event is the PI event created from the native handle.
Definition at line 624 of file pi_native_cpu.cpp.
References pi2ur::piextEventCreateWithNativeHandle().
piextEventGetNativeHandle()
pi_result piextEventGetNativeHandle (pi_event event, pi_native_handle * nativeHandle)
Gets the native handle of a PI event object.
Parameters
event is the PI event to get the native handle of.
nativeHandle is the native handle of event.
Definition at line 618 of file pi_native_cpu.cpp.
References pi2ur::piextEventGetNativeHandle().
piextGetDeviceFunctionPointer()
pi_result piextGetDeviceFunctionPointer (pi_device device, pi_program program, const char * function_name, pi_uint64 * function_pointer_ret)
Retrieves a device function pointer to a user-defined function.
function_name.
function_pointer_ret is set to 0 if query failed.
program must be built before calling this API.
device must present in the list of devices returned by get_device method for
program.
If a fallback method determines the function exists but the address is not available PI_ERROR_FUNCTION_ADDRESS_IS_NOT_AVAILABLE is returned. If the address does not exist PI_ERROR_INVALID_KERNEL_NAME is returned.
Definition at line 847 of file pi_native_cpu.cpp.
References pi2ur::piextGetDeviceFunctionPointer().
piextGetGlobalVariablePointer()
pi_result piextGetGlobalVariablePointer (pi_device Device, pi_program Program, const char * GlobalVariableName, size_t * GlobalVariableSize, void ** GlobalVariablePointerRet)
Definition at line 855 of file pi_native_cpu.cpp.
References pi2ur::piextGetGlobalVariablePointer().
piextImportExternalSemaphoreOpaqueFD()
pi_result piextImportExternalSemaphoreOpaqueFD (pi_context context, pi_device device, int file_descriptor, pi_interop_semaphore_handle * ret_handle)
API to import an external semaphore in the form of a file descriptor.
Parameters
context is the pi_context
device is the pi_device
file_descriptor is the file descriptor
ret_handle is the returned interop semaphore handle to the external semaphore
Definition at line 486 of file pi_native_cpu.cpp.
References pi2ur::piextImportExternalSemaphoreOpaqueFD().
piextKernelCreateWithNativeHandle()
pi_result piextKernelCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, pi_program program, bool pluginOwnsNativeHandle, pi_kernel * kernel)
Creates PI kernel object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI kernel from.
context is the PI context of the kernel.
program is the PI program of the kernel.
pluginOwnsNativeHandle Indicates whether the created PI object should take ownership of the native handle.
kernel is the PI kernel created from the native handle.
Definition at line 556 of file pi_native_cpu.cpp.
References pi2ur::piextKernelCreateWithNativeHandle().
piextKernelGetNativeHandle()
pi_result piextKernelGetNativeHandle (pi_kernel kernel, pi_native_handle * nativeHandle)
Gets the native handle of a PI kernel object.
Parameters
kernel is the PI kernel to get the native handle of.
nativeHandle is the native handle of kernel.
Definition at line 566 of file pi_native_cpu.cpp.
References pi2ur::piextKernelGetNativeHandle().
piextKernelSetArgMemObj()
pi_result piextKernelSetArgMemObj (pi_kernel Kernel, pi_uint32 ArgIndex, const pi_mem_obj_property * ArgProperties, const pi_mem * ArgValue)
Definition at line 360 of file pi_native_cpu.cpp.
References pi2ur::piextKernelSetArgMemObj().
piextKernelSetArgPointer()
pi_result piextKernelSetArgPointer (pi_kernel kernel, pi_uint32 arg_index, size_t arg_size, const void * arg_value)
Sets up pointer arguments for CL kernels.
An extra indirection is required due to CL argument conventions.
Parameters
kernel is the kernel to be launched
arg_index is the index of the kernel argument
arg_size is the size in bytes of the argument (ignored in CL)
arg_value is the pointer argument
Definition at line 903 of file pi_native_cpu.cpp.
References pi2ur::piextKernelSetArgPointer().
piextKernelSetArgSampler()
pi_result piextKernelSetArgSampler (pi_kernel Kernel, pi_uint32 ArgIndex, const pi_sampler * ArgValue)
Definition at line 367 of file pi_native_cpu.cpp.
References pi2ur::piextKernelSetArgSampler().
piextKernelSuggestMaxCooperativeGroupCount()
pi_result piextKernelSuggestMaxCooperativeGroupCount (pi_kernel kernel, size_t local_work_size, size_t dynamic_shared_memory_size, pi_uint32 * group_count_ret)
Gets the max work group count for a cooperative kernel.
Parameters
kernel is the PI kernel being queried.
local_work_size is the number of work items in a work group that will be used when the kernel is launched.
dynamic_shared_memory_size is the size of dynamic shared memory, for each work group, in bytes, that will be used when the kernel is launched."
group_count_ret is a pointer to where the query result will be stored.
Definition at line 1290 of file pi_native_cpu.cpp.
piextMemCreateWithNativeHandle()
pi_result piextMemCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, bool ownNativeHandle, pi_mem * mem)
Creates PI mem object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI mem from.
context The PI context of the memory allocation.
ownNativeHandle Indicates if we own the native memory handle or it came from interop that asked to not transfer the ownership to SYCL RT.
mem is the PI mem created from the native handle.
Definition at line 248 of file pi_native_cpu.cpp.
References pi2ur::piextMemCreateWithNativeHandle().
piextMemGetNativeHandle()
pi_result piextMemGetNativeHandle (pi_mem mem, pi_device dev, pi_native_handle * nativeHandle)
Gets the native handle of a PI mem object.
Parameters
mem is the PI mem to get the native handle of.
dev is the PI device that the native allocation will be resident on
nativeHandle is the native handle of mem.
Definition at line 243 of file pi_native_cpu.cpp.
References pi2ur::piextMemGetNativeHandle().
piextMemImageAllocate()
pi_result piextMemImageAllocate (pi_context context, pi_device device, pi_image_format * image_format, pi_image_desc * image_desc, pi_image_mem_handle * ret_mem)
API to allocate memory for bindless images.
Parameters
context is the pi_context
device is the pi_device
flags are extra flags to pass (currently unused)
image_format format of the image (channel order and data type)
image_desc image descriptor
ret_mem is the returning memory handle to newly allocated memory
Definition at line 381 of file pi_native_cpu.cpp.
References pi2ur::piextMemImageAllocate().
piextMemImageCopy()
pi_result piextMemImageCopy (pi_queue command_queue, void * dst_ptr, void * src_ptr, const pi_image_format * image_format, const pi_image_desc * image_desc, const pi_image_copy_flags flags, pi_image_offset src_offset, pi_image_offset dst_offset, pi_image_region copy_extent, pi_image_region host_extent, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
API to copy image data Host to Device or Device to Host.
Parameters
queue is the queue to submit to
dst_ptr is the location the data will be copied to
src_ptr is the data to be copied
image_format format of the image (channel order and data type)
image_desc image descriptor
flags flags describing copy direction (H2D or D2H)
src_offset is the offset into the source image/memory
dst_offset is the offset into the destination image/memory
copy_extent is the extent (region) of the image/memory to copy
host_extent is the extent (region) of the memory on the host
num_events_in_wait_list is the number of events in the wait list
event_wait_list is the list of events to wait on before copying
event is the returned event representing this operation
Definition at line 434 of file pi_native_cpu.cpp.
References pi2ur::piextMemImageCopy().
piextMemImageCreateWithNativeHandle()
pi_result piextMemImageCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, bool ownNativeHandle, const pi_image_format * ImageFormat, const pi_image_desc * ImageDesc, pi_mem * img)
Creates PI image object from a native handle.
Parameters
nativeHandle is the native handle to create PI image from.
context The PI context of the memory allocation.
ownNativeHandle Indicates if we own the native memory handle or it came from interop that asked to not transfer the ownership to SYCL RT.
ImageFormat is the pi_image_format struct that specifies the image channnel order and channel data type that match what the nativeHandle uses
ImageDesc is the pi_image_desc struct that specifies the image dimension, pitch, slice and other information about the nativeHandle
img is the PI img created from the native handle.
Definition at line 271 of file pi_native_cpu.cpp.
References pi2ur::piextMemImageCreateWithNativeHandle().
piextMemImageFree()
pi_result piextMemImageFree (pi_context context, pi_device device, pi_image_mem_handle memory_handle)
API to free memory for bindless images.
Parameters
context is the pi_context
device is the pi_device
memory_handle is the handle to image memory to be freed
Definition at line 424 of file pi_native_cpu.cpp.
References pi2ur::piextMemImageFree().
piextMemImageGetInfo()
pi_result piextMemImageGetInfo (const pi_image_mem_handle mem_handle, pi_image_info param_name, void * param_value, size_t * param_value_size_ret)
API to query an image memory handle for specific properties.
Parameters
mem_handle is the handle to the image memory
param_name is the queried info name
param_value is the returned query value
param_value_size_ret is the returned query value size
Definition at line 457 of file pi_native_cpu.cpp.
References pi2ur::piextMemImageGetInfo().
piextMemImportOpaqueFD()
pi_result piextMemImportOpaqueFD (pi_context context, pi_device device, size_t size, int file_descriptor, pi_interop_mem_handle * ret_handle)
API to import external memory in the form of a file descriptor.
Parameters
context is the pi_context
device is the pi_device
size is the size of the external memory
file_descriptor is the file descriptor
ret_handle is the returned interop memory handle to the external memory
Definition at line 466 of file pi_native_cpu.cpp.
References pi2ur::piextMemImportOpaqueFD().
piextMemMapExternalArray()
pi_result piextMemMapExternalArray (pi_context context, pi_device device, pi_image_format * image_format, pi_image_desc * image_desc, pi_interop_mem_handle mem_handle, pi_image_mem_handle * ret_mem)
API to map an interop memory handle to an image memory handle.
Parameters
context is the pi_context
device is the pi_device
image_format format of the image (channel order and data type)
image_desc image descriptor
mem_handle is the interop memory handle to the external memory
ret_mem is the returned image memory handle to the externally allocated memory
Definition at line 472 of file pi_native_cpu.cpp.
References pi2ur::piextMemMapExternalArray().
piextMemMipmapFree()
pi_result piextMemMipmapFree (pi_context context, pi_device device, pi_image_mem_handle memory_handle)
API to free mipmap memory for bindless images.
Parameters
context is the pi_context
device is the pi_device
memory_handle is the handle to image memory to be freed
Definition at line 429 of file pi_native_cpu.cpp.
References pi2ur::piextMemMipmapFree().
piextMemMipmapGetLevel()
pi_result piextMemMipmapGetLevel (pi_context context, pi_device device, pi_image_mem_handle mip_mem, unsigned int level, pi_image_mem_handle * ret_mem)
API to retrieve individual image from mipmap.
Parameters
context is the pi_context
device is the pi_device
mip_mem is the memory handle to the mipmap
level is the requested level of the mipmap
ret_mem is the returning memory handle to the individual image
Definition at line 416 of file pi_native_cpu.cpp.
References pi2ur::piextMemMipmapGetLevel().
piextMemReleaseInterop()
pi_result piextMemReleaseInterop (pi_context context, pi_device device, pi_interop_mem_handle memory_handle)
API to destroy interop memory.
Parameters
context is the pi_context
device is the pi_device
memory_handle is the handle to interop memory to be freed
Definition at line 480 of file pi_native_cpu.cpp.
References pi2ur::piextMemReleaseInterop().
piextMemSampledImageCreate()
pi_result piextMemSampledImageCreate (pi_context context, pi_device device, pi_image_mem_handle img_mem, pi_image_format * image_format, pi_image_desc * image_desc, pi_sampler sampler, pi_mem * ret_mem, pi_image_handle * ret_handle)
API to create sampled bindless image handles.
Parameters
context is the pi_context
device is the pi_device
img_mem is the handle to memory from which to create the image
image_format format of the image (channel order and data type)
image_desc image descriptor
sampler is the pi_sampler
ret_mem is the returning pi_mem image object
ret_handle is the returning memory handle to newly allocated memory
Definition at line 398 of file pi_native_cpu.cpp.
References pi2ur::piextMemSampledImageCreate().
piextMemSampledImageHandleDestroy()
pi_result piextMemSampledImageHandleDestroy (pi_context context, pi_device device, pi_image_handle handle)
API to destroy bindless sampled image handles.
Parameters
context is the pi_context
handle is the image handle
Definition at line 452 of file pi_native_cpu.cpp.
References pi2ur::piextMemSampledImageHandleDestroy().
piextMemUnsampledImageCreate()
pi_result piextMemUnsampledImageCreate (pi_context context, pi_device device, pi_image_mem_handle img_mem, pi_image_format * image_format, pi_image_desc * image_desc, pi_mem * ret_mem, pi_image_handle * ret_handle)
API to create bindless image handles.
Parameters
context is the pi_context
device is the pi_device
img_mem is the handle to memory from which to create the image
image_format format of the image (channel order and data type)
image_desc image descriptor
ret_mem is the returning pi_mem image object
ret_handle is the returning memory handle to newly allocated memory
Definition at line 390 of file pi_native_cpu.cpp.
References pi2ur::piextMemUnsampledImageCreate().
piextMemUnsampledImageHandleDestroy()
pi_result piextMemUnsampledImageHandleDestroy (pi_context context, pi_device device, pi_image_handle handle)
API to destroy bindless unsampled image handles.
Parameters
context is the pi_context
device is the pi_device
handle is the image handle
Definition at line 447 of file pi_native_cpu.cpp.
References pi2ur::piextMemUnsampledImageHandleDestroy().
piextPeerAccessGetInfo()
pi_result piextPeerAccessGetInfo (pi_device command_device, pi_device peer_device, pi_peer_attr attr, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 1233 of file pi_native_cpu.cpp.
References pi2ur::piextPeerAccessGetInfo().
piextPlatformCreateWithNativeHandle()
pi_result piextPlatformCreateWithNativeHandle (pi_native_handle nativeHandle, pi_platform * platform)
Creates PI platform object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI device from.
platform is the PI platform created from the native handle.
Definition at line 51 of file pi_native_cpu.cpp.
References pi2ur::piextPlatformCreateWithNativeHandle().
piextPlatformGetNativeHandle()
pi_result piextPlatformGetNativeHandle (pi_platform platform, pi_native_handle * nativeHandle)
Gets the native handle of a PI platform object.
Parameters
platform is the PI platform to get the native handle of.
nativeHandle is the native handle of platform.
Definition at line 45 of file pi_native_cpu.cpp.
References pi2ur::piextPlatformGetNativeHandle().
piextPluginGetOpaqueData()
pi_result piextPluginGetOpaqueData (void * opaque_data_param, void ** opaque_data_return)
API to get Plugin internal data, opaque to SYCL RT.
Some devices whose device code is compiled by the host compiler (e.g. CPU emulators) may use it to access some device code functionality implemented in/behind the plugin.
Parameters
opaque_data_param - unspecified argument, interpretation is specific to a plugin
opaque_data_return - placeholder for the returned opaque data.
Definition at line 1207 of file pi_native_cpu.cpp.
References pi2ur::piextPluginGetOpaqueData().
piextProgramCreateWithNativeHandle()
pi_result piextProgramCreateWithNativeHandle (pi_native_handle nativeHandle, pi_context context, bool pluginOwnsNativeHandle, pi_program * program)
Creates PI program object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI program from.
context is the PI context of the program.
pluginOwnsNativeHandle Indicates whether the created PI object should take ownership of the native handle.
program is the PI program created from the native handle.
Definition at line 340 of file pi_native_cpu.cpp.
References pi2ur::piextProgramCreateWithNativeHandle().
piextProgramGetNativeHandle()
pi_result piextProgramGetNativeHandle (pi_program program, pi_native_handle * nativeHandle)
Gets the native handle of a PI program object.
Parameters
program is the PI program to get the native handle of.
nativeHandle is the native handle of program.
Definition at line 335 of file pi_native_cpu.cpp.
References pi2ur::piextProgramGetNativeHandle().
piextProgramSetSpecializationConstant()
pi_result piextProgramSetSpecializationConstant (pi_program prog, pi_uint32 spec_id, size_t spec_size, const void * spec_value)
Sets a specialization constant to a specific value.
Note: Only used when specialization constants are natively supported (SPIR-V binaries), and not when they are emulated (AOT binaries).
Parameters
prog the program object which will use the value
spec_id integer ID of the constant
spec_size size of the value
spec_value bytes of the value
Definition at line 1068 of file pi_native_cpu.cpp.
References pi2ur::piextProgramSetSpecializationConstant().
piextQueueCreate()
pi_result piextQueueCreate (pi_context context, pi_device device, pi_queue_properties * properties, pi_queue * queue)
Parameters
properties points to a zero-terminated array of extra data describing desired queue properties. Format is {[PROPERTY[, property-specific elements of data]*,]* 0}
Definition at line 174 of file pi_native_cpu.cpp.
References pi2ur::piextQueueCreate().
Referenced by piQueueCreate().
piextQueueCreateWithNativeHandle()
pi_result piextQueueCreateWithNativeHandle (pi_native_handle nativeHandle, int32_t nativeHandleDesc, pi_context context, pi_device device, bool pluginOwnsNativeHandle, pi_queue_properties * Properties, pi_queue * queue)
Creates PI queue object from a native handle.
NOTE: The created PI object takes ownership of the native handle.
Parameters
nativeHandle is the native handle to create PI queue from.
nativeHandleDesc provides additional properties of the native handle.
context is the PI context of the queue.
device is the PI device associated with the native device used when creating the native queue. This parameter is optional but some backends may fail to create the right PI queue if omitted.
pluginOwnsNativeHandle Indicates whether the created PI object should take ownership of the native handle.
Properties holds queue properties.
queue is the PI queue created from the native handle.
Definition at line 205 of file pi_native_cpu.cpp.
References pi2ur::piextQueueCreateWithNativeHandle().
piextQueueGetNativeHandle()
pi_result piextQueueGetNativeHandle (pi_queue queue, pi_native_handle * nativeHandle, int32_t * nativeHandleDesc)
Gets the native handle of a PI queue object.
Parameters
queue is the PI queue to get the native handle of.
nativeHandle is the native handle of queue or commandlist.
nativeHandleDesc provides additional properties of the native handle.
Definition at line 197 of file pi_native_cpu.cpp.
References pi2ur::piextQueueGetNativeHandle().
piextSignalExternalSemaphore()
pi_result piextSignalExternalSemaphore (pi_queue command_queue, pi_interop_semaphore_handle sem_handle, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
API to instruct the queue to signal the external semaphore handle once all previous commands have completed execution.
Parameters
command_queue is the queue instructed to signal
sem_handle is the interop semaphore handle to signal
num_events_in_wait_list is the number of events in the wait list
event_wait_list is the list of events to wait on before this operation
event is the returned event representing this operation
Definition at line 507 of file pi_native_cpu.cpp.
References pi2ur::piextSignalExternalSemaphore().
piextUSMDeviceAlloc()
pi_result piextUSMDeviceAlloc (void ** result_ptr, pi_context context, pi_device device, pi_usm_mem_properties * properties, size_t size, pi_uint32 alignment)
Allocates device memory.
Parameters
result_ptr contains the allocated memory
context is the pi_context
device is the device the memory will be allocated on
properties are optional allocation properties
size is the size of the allocation
alignment is the desired alignment of the allocation
Definition at line 864 of file pi_native_cpu.cpp.
References sycl::_V1::ext::oneapi::experimental::detail::Alignment, and pi2ur::piextUSMDeviceAlloc().
piextUSMEnqueueFill()
pi_result piextUSMEnqueueFill (pi_queue Queue, void * Ptr, const void * Pattern, size_t PatternSize, size_t Count, pi_uint32 NumEventsInWaitlist, const pi_event * EventsWaitlist, pi_event * Event)
USM Fill API.
Parameters
queue is the queue to submit to
ptr is the ptr to fill
pattern is the ptr with the bytes of the pattern to set
patternSize is the size in bytes of the pattern to set
count is the size in bytes to fill
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
Queue is the queue to submit to
Ptr is the ptr to fill
Pattern is the ptr with the bytes of the pattern to set
PatternSize is the size in bytes of the pattern to set
Count is the size in bytes to fill
NumEventsInWaitlist is the number of events to wait on
EventsWaitlist is an array of events to wait on
Event is the event that represents this operation
Definition at line 908 of file pi_native_cpu.cpp.
References pi2ur::piextUSMEnqueueFill().
piextUSMEnqueueFill2D()
pi_result piextUSMEnqueueFill2D (pi_queue Queue, void * Ptr, size_t Pitch, size_t PatternSize, const void * Pattern, size_t Width, size_t Height, pi_uint32 NumEventsWaitList, const pi_event * EventsWaitList, pi_event * Event)
USM 2D fill API.
Parameters
queue is the queue to submit to
ptr is the ptr to fill
pitch is the total width of the destination memory including padding
pattern is a pointer with the bytes of the pattern to set
pattern_size is the size in bytes of the pattern
width is width in bytes of each row to fill
height is height the columns to fill
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
USM 2D fill API.
Parameters
queue is the queue to submit to
ptr is the ptr to fill
pitch is the total width of the destination memory including padding
pattern is a pointer with the bytes of the pattern to set
pattern_size is the size in bytes of the pattern
width is width in bytes of each row to fill
height is height the columns to fill
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
Definition at line 944 of file pi_native_cpu.cpp.
References pi2ur::piextUSMEnqueueFill2D().
piextUSMEnqueueMemAdvise()
pi_result piextUSMEnqueueMemAdvise (pi_queue Queue, const void * Ptr, size_t Length, pi_mem_advice Advice, pi_event * OutEvent)
USM Memadvise API.
Parameters
queue is the queue to submit to
ptr is the data to be advised
length is the size in bytes of the memory to advise
advice is device specific advice
event is the event that represents this operation
USM Memadvise API.
Parameters
Queue is the queue to submit to
Ptr is the data to be advised
Length is the size in bytes of the meory to advise
Advice is device specific advice
Event is the event that represents this operation
Definition at line 937 of file pi_native_cpu.cpp.
References pi2ur::piextUSMEnqueueMemAdvise().
piextUSMEnqueueMemcpy()
pi_result piextUSMEnqueueMemcpy (pi_queue queue, pi_bool blocking, void * dst_ptr, const void * src_ptr, size_t size, pi_uint32 num_events_in_waitlist, const pi_event * events_waitlist, pi_event * event)
USM Memcpy API.
Parameters
queue is the queue to submit to
blocking is whether this operation should block the host
src_ptr is the data to be copied
dst_ptr is the location the data will be copied
size is number of bytes to copy
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
Definition at line 916 of file pi_native_cpu.cpp.
References pi2ur::piextUSMEnqueueMemcpy().
piextUSMEnqueueMemcpy2D()
pi_result piextUSMEnqueueMemcpy2D (pi_queue Queue, pi_bool Blocking, void * DstPtr, size_t DstPitch, const void * SrcPtr, size_t SrcPitch, size_t Width, size_t Height, pi_uint32 NumEventsInWaitlist, const pi_event * EventWaitlist, pi_event * Event)
USM 2D Memcpy API.
Parameters
queue is the queue to submit to
blocking is whether this operation should block the host
dst_ptr is the location the data will be copied
dst_pitch is the total width of the destination memory including padding
src_ptr is the data to be copied
src_pitch is the total width of the source memory including padding
width is width in bytes of each row to be copied
height is height the columns to be copied
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
queue is the queue to submit to
blocking is whether this operation should block the host
dst_ptr is the location the data will be copied
dst_pitch is the total width of the destination memory including padding
src_ptr is the data to be copied
dst_pitch is the total width of the source memory including padding
width is width in bytes of each row to be copied
height is height the columns to be copied
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
Definition at line 969 of file pi_native_cpu.cpp.
References pi2ur::piextUSMEnqueueMemcpy2D().
piextUSMEnqueueMemset2D()
pi_result piextUSMEnqueueMemset2D (pi_queue Queue, void * Ptr, size_t Pitch, int Value, size_t Width, size_t Height, pi_uint32 NumEventsWaitList, const pi_event * EventsWaitlist, pi_event * Event)
USM 2D Memset API.
Parameters
queue is the queue to submit to
ptr is the ptr to fill
pitch is the total width of the destination memory including padding
value the value to fill into the region in
ptr
width is width in bytes of each row to fill
height is height the columns to fill
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
queue is the queue to submit to
ptr is the ptr to fill
pitch is the total width of the destination memory including padding
pattern is a pointer with the bytes of the pattern to set
pattern_size is the size in bytes of the pattern
width is width in bytes of each row to fill
height is height the columns to fill
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
Definition at line 957 of file pi_native_cpu.cpp.
References pi2ur::piextUSMEnqueueMemset2D().
piextUSMEnqueuePrefetch()
pi_result piextUSMEnqueuePrefetch (pi_queue Queue, const void * Ptr, size_t Size, pi_usm_migration_flags Flags, pi_uint32 NumEventsInWaitList, const pi_event * EventWaitList, pi_event * OutEvent)
Hint to migrate memory to the device.
Parameters
queue is the queue to submit to
ptr points to the memory to migrate
size is the number of bytes to migrate
flags is a bitfield used to specify memory migration options
num_events_in_waitlist is the number of events to wait on
events_waitlist is an array of events to wait on
event is the event that represents this operation
Queue is the queue to submit to
Ptr points to the memory to migrate
Size is the number of bytes to migrate
Flags is a bitfield used to specify memory migration options
NumEventsInWaitlist is the number of events to wait on
EventsWaitlist is an array of events to wait on
Event is the event that represents this operation
Definition at line 927 of file pi_native_cpu.cpp.
References pi2ur::piextUSMEnqueuePrefetch().
piextUSMFree()
pi_result piextUSMFree (pi_context context, void * ptr)
Indicates that the allocated USM memory is no longer needed on the runtime side.
The actual freeing of the memory may be done in a blocking or deferred manner, e.g. to avoid issues with indirect memory access from kernels.
Parameters
context is the pi_context of the allocation
ptr is the memory to be freed
Definition at line 898 of file pi_native_cpu.cpp.
References pi2ur::piextUSMFree().
piextUSMGetMemAllocInfo()
pi_result piextUSMGetMemAllocInfo (pi_context Context, const void * Ptr, pi_mem_alloc_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
API to query information about USM allocated pointers Valid Queries: PI_MEM_ALLOC_TYPE returns host/device/shared pi_host_usm value PI_MEM_ALLOC_BASE_PTR returns the base ptr of an allocation if the queried pointer fell inside an allocation.
Result must fit in void * PI_MEM_ALLOC_SIZE returns how big the queried pointer's allocation is in bytes. Result is a size_t. PI_MEM_ALLOC_DEVICE returns the pi_device this was allocated against
Parameters
context is the pi_context
ptr is the pointer to query
param_name is the type of query to perform
param_value_size is the size of the result in bytes
param_value is the result
param_value_size_ret is how many bytes were written
API to query information about USM allocated pointers Valid Queries: PI_MEM_ALLOC_TYPE returns host/device/shared pi_host_usm value PI_MEM_ALLOC_BASE_PTR returns the base ptr of an allocation if the queried pointer fell inside an allocation.
Valid Queries: PI_MEM_ALLOC_TYPE returns host/device/shared pi_usm_type value PI_MEM_ALLOC_BASE_PTR returns the base ptr of an allocation if the queried pointer fell inside an allocation. Result must fit in void * PI_MEM_ALLOC_SIZE returns how big the queried pointer's allocation is in bytes. Result is a size_t. PI_MEM_ALLOC_DEVICE returns the pi_device this was allocated against
Parameters
Context is the pi_context
Ptr is the pointer to query
ParamName is the type of query to perform
ParamValueSize is the size of the result in bytes
ParamValue is the result
ParamValueRet is how many bytes were written
Definition at line 980 of file pi_native_cpu.cpp.
References pi2ur::piextUSMGetMemAllocInfo().
piextUSMHostAlloc()
pi_result piextUSMHostAlloc (void ** result_ptr, pi_context context, pi_usm_mem_properties * properties, size_t size, pi_uint32 alignment)
Allocates host memory accessible by the device.
Parameters
result_ptr contains the allocated memory
context is the pi_context
properties are optional allocation properties
size is the size of the allocation
alignment is the desired alignment of the allocation
Definition at line 891 of file pi_native_cpu.cpp.
References sycl::_V1::ext::oneapi::experimental::detail::Alignment, and pi2ur::piextUSMHostAlloc().
piextUSMImport()
pi_result piextUSMImport (const void * ptr, size_t size, pi_context context)
Import host system memory into USM.
Parameters
ptr start address of memory range to import
size is the number of bytes to import
context is the pi_context
Definition at line 988 of file pi_native_cpu.cpp.
References pi2ur::piextUSMImport().
piextUSMPitchedAlloc()
pi_result piextUSMPitchedAlloc (void ** result_ptr, size_t * result_pitch, pi_context context, pi_device device, pi_usm_mem_properties * properties, size_t width_in_bytes, size_t height, unsigned int element_size_bytes)
Allocates memory accessible on device.
Parameters
result_ptr contains the allocated memory
result_pitch contains the returned memory pitch
context is the pi_context
device is the device the memory will be allocated on
properties are optional allocation properties
width_in_bytes is the width of the allocation in bytes
height is the height of the allocation in rows
element_size_bytes is the size in bytes of an element in the allocation
Definition at line 882 of file pi_native_cpu.cpp.
References pi2ur::piextUSMPitchedAlloc().
piextUSMRelease()
pi_result piextUSMRelease (const void * ptr, pi_context context)
Release host system memory from USM.
Parameters
ptr start address of imported memory range
context is the pi_context
Definition at line 992 of file pi_native_cpu.cpp.
References pi2ur::piextUSMRelease().
piextUSMSharedAlloc()
pi_result piextUSMSharedAlloc (void ** result_ptr, pi_context context, pi_device device, pi_usm_mem_properties * properties, size_t size, pi_uint32 alignment)
Allocates memory accessible on both host and device.
Parameters
result_ptr contains the allocated memory
context is the pi_context
device is the device the memory will be allocated on
properties are optional allocation properties
size is the size of the allocation
alignment is the desired alignment of the allocation
Definition at line 873 of file pi_native_cpu.cpp.
References sycl::_V1::ext::oneapi::experimental::detail::Alignment, and pi2ur::piextUSMSharedAlloc().
piextWaitExternalSemaphore()
pi_result piextWaitExternalSemaphore (pi_queue command_queue, pi_interop_semaphore_handle sem_handle, pi_uint32 num_events_in_wait_list, const pi_event * event_wait_list, pi_event * event)
API to instruct the queue with a non-blocking wait on an external semaphore.
Parameters
command_queue is the queue instructed to wait
sem_handle is the interop semaphore handle
num_events_in_wait_list is the number of events in the wait list
event_wait_list is the list of events to wait on before this operation
event is the returned event representing this operation
Definition at line 499 of file pi_native_cpu.cpp.
References pi2ur::piextWaitExternalSemaphore().
piGetDeviceAndHostTimer()
pi_result piGetDeviceAndHostTimer (pi_device Device, uint64_t * DeviceTime, uint64_t * HostTime)
Queries device for it's global timestamp in nanoseconds, and updates HostTime with the value of the host timer at the closest possible point in time to that at which DeviceTime was returned.
Parameters
Device device to query for timestamp
DeviceTime pointer to store device timestamp in nanoseconds. Optional argument, can be nullptr
HostTime pointer to store host timestamp in nanoseconds. Optional argurment, can be nullptr in which case timestamp will not be written
Definition at line 1216 of file pi_native_cpu.cpp.
References pi2ur::piGetDeviceAndHostTimer().
piKernelCreate()
pi_result piKernelCreate (pi_program Program, const char * KernelName, pi_kernel * RetKernel)
Definition at line 348 of file pi_native_cpu.cpp.
References pi2ur::piKernelCreate().
piKernelGetGroupInfo()
pi_result piKernelGetGroupInfo (pi_kernel Kernel, pi_device Device, pi_kernel_group_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 515 of file pi_native_cpu.cpp.
References pi2ur::piKernelGetGroupInfo().
piKernelGetInfo()
pi_result piKernelGetInfo (pi_kernel Kernel, pi_kernel_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 373 of file pi_native_cpu.cpp.
References pi2ur::piKernelGetInfo().
piKernelGetSubGroupInfo()
pi_result piKernelGetSubGroupInfo (pi_kernel kernel, pi_device device, pi_kernel_sub_group_info param_name, size_t input_value_size, const void * input_value, size_t param_value_size, void * param_value, size_t * param_value_size_ret)
API to query information from the sub-group from a kernel.
Parameters
kernel is the pi_kernel to query
device is the device the kernel is executed on
param_name is a pi_kernel_sub_group_info enum value that specifies the informtation queried for.
input_value_size is the size of input value passed in ptr input_value param
input_value is the ptr to the input value passed.
param_value_size is the size of the value in bytes.
param_value is a pointer to the value to set.
param_value_size_ret is a pointer to return the size of data in param_value ptr.
All queries expect a return of 4 bytes in param_value_size, param_value_size_ret, and a uint32_t value should to be written in param_value ptr. Note: This behaviour differs from OpenCL. OpenCL returns size_t.
Definition at line 524 of file pi_native_cpu.cpp.
References pi2ur::piKernelGetSubGroupInfo().
piKernelRelease()
pi_result piKernelRelease (pi_kernel Kernel)
Definition at line 540 of file pi_native_cpu.cpp.
References pi2ur::piKernelRelease().
piKernelRetain()
pi_result piKernelRetain (pi_kernel Kernel)
Definition at line 535 of file pi_native_cpu.cpp.
References pi2ur::piKernelRetain().
piKernelSetArg()
pi_result piKernelSetArg (pi_kernel Kernel, pi_uint32 ArgIndex, size_t ArgSize, const void * ArgValue)
Definition at line 354 of file pi_native_cpu.cpp.
References pi2ur::piKernelSetArg().
piKernelSetExecInfo()
pi_result piKernelSetExecInfo (pi_kernel kernel, pi_kernel_exec_info value_name, size_t param_value_size, const void * param_value)
API to set attributes controlling kernel execution.
Parameters
kernel is the pi kernel to execute
param_name is a pi_kernel_exec_info value that specifies the info passed to the kernel
param_value_size is the size of the value in bytes
param_value is a pointer to the value to set for the kernel
If param_name is PI_USM_INDIRECT_ACCESS, the value will be a ptr to the pi_bool value PI_TRUE If param_name is PI_USM_PTRS, the value will be an array of ptrs
Definition at line 1061 of file pi_native_cpu.cpp.
References pi2ur::piKernelSetExecInfo().
piMemBufferCreate()
pi_result piMemBufferCreate (pi_context Context, pi_mem_flags Flags, size_t Size, void * HostPtr, pi_mem * RetMem, const pi_mem_properties * properties)
Definition at line 217 of file pi_native_cpu.cpp.
References pi2ur::piMemBufferCreate().
piMemBufferPartition()
pi_result piMemBufferPartition (pi_mem Buffer, pi_mem_flags Flags, pi_buffer_create_type BufferCreateType, void * BufferCreateInfo, pi_mem * RetMem)
Definition at line 839 of file pi_native_cpu.cpp.
References pi2ur::piMemBufferPartition().
piMemGetInfo()
pi_result piMemGetInfo (pi_mem Mem, pi_mem_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 224 of file pi_native_cpu.cpp.
References pi2ur::piMemGetInfo().
piMemImageCreate()
pi_result piMemImageCreate (pi_context Context, pi_mem_flags Flags, const pi_image_format * ImageFormat, const pi_image_desc * ImageDesc, void * HostPtr, pi_mem * RetImage)
Definition at line 234 of file pi_native_cpu.cpp.
References pi2ur::piMemImageCreate().
piMemImageGetInfo()
pi_result piMemImageGetInfo (pi_mem Image, pi_image_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 784 of file pi_native_cpu.cpp.
References pi2ur::piMemImageGetInfo().
piMemRelease()
pi_result piMemRelease (pi_mem Mem)
Definition at line 232 of file pi_native_cpu.cpp.
References pi2ur::piMemRelease().
piMemRetain()
pi_result piMemRetain (pi_mem Mem)
Definition at line 230 of file pi_native_cpu.cpp.
References pi2ur::piMemRetain().
piPlatformGetInfo()
pi_result piPlatformGetInfo (pi_platform Platform, pi_platform_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 38 of file pi_native_cpu.cpp.
References pi2ur::piPlatformGetInfo().
piPlatformsGet()
pi_result piPlatformsGet (pi_uint32 NumEntries, pi_platform * Platforms, pi_uint32 * NumPlatforms)
Definition at line 33 of file pi_native_cpu.cpp.
References pi2ur::piPlatformsGet().
piPluginGetBackendOption()
pi_result piPluginGetBackendOption (pi_platform platform, const char * frontend_option, const char ** backend_option)
API to get backend specific option.
Parameters
frontend_option is a string that contains frontend option.
backend_option is used to return the backend option corresponding to frontend option.
Returns
PI_SUCCESS is returned for valid frontend_option. If a valid backend option is not available, an empty string is returned.
Definition at line 61 of file pi_native_cpu.cpp.
References pi2ur::piPluginGetBackendOption().
piPluginGetLastError()
pi_result piPluginGetLastError (char ** message)
API to get Plugin specific warning and error messages.
Parameters
message is a returned address to the first element in the message the plugin owns the error message string. The string is thread-local. As a result, different threads may return different errors. A message is overwritten by the following error or warning that is produced within the given thread. The memory is cleaned up at the end of the thread's lifetime.
Returns
PI_SUCCESS if plugin is indicating non-fatal warning. Any other error code indicates that plugin considers this to be a fatal error and the Returns the global timestamp from
Parameters
device,and syncronized host timestamp
Definition at line 57 of file pi_native_cpu.cpp.
References pi2ur::piPluginGetLastError().
piPluginInit()
pi_result piPluginInit (pi_plugin * PluginInit)
Definition at line 1305 of file pi_native_cpu.cpp.
piProgramBuild()
pi_result piProgramBuild (pi_program Program, pi_uint32 NumDevices, const pi_device * DeviceList, const char * Options, void(*)(pi_program Program, void *UserData) PFnNotify, void * UserData)
Definition at line 309 of file pi_native_cpu.cpp.
References pi2ur::piProgramBuild().
piProgramCompile()
pi_result piProgramCompile (pi_program Program, pi_uint32 NumDevices, const pi_device * DeviceList, const char * Options, pi_uint32 NumInputHeaders, const pi_program * InputHeaders, const char ** HeaderIncludeNames, void(*)(pi_program Program, void *UserData) PFnNotify, void * UserData)
Definition at line 298 of file pi_native_cpu.cpp.
References pi2ur::piProgramCompile().
piProgramCreate()
pi_result piProgramCreate (pi_context Context, const void * ILBytes, size_t Length, pi_program * Program)
Definition at line 255 of file pi_native_cpu.cpp.
References pi2ur::piProgramCreate().
piProgramCreateWithBinary()
pi_result piProgramCreateWithBinary (pi_context context, pi_uint32 num_devices, const pi_device * device_list, const size_t * lengths, const unsigned char ** binaries, size_t num_metadata_entries, const pi_device_binary_property * metadata, pi_int32 * binary_status, pi_program * ret_program)
Creates a PI program for a context and loads the given binary into it.
Parameters
context is the PI context to associate the program with.
num_devices is the number of devices in device_list.
device_list is a pointer to a list of devices. These devices must all be in context.
lengths is an array of sizes in bytes of the binary in binaries.
binaries is a pointer to a list of program binaries.
num_metadata_entries is the number of metadata entries in metadata.
metadata is a pointer to a list of program metadata entries. The use of metadata entries is backend-defined.
binary_status returns whether the program binary was loaded succesfully or not, for each device in device_list. binary_status is ignored if it is null and otherwise it must be an array of num_devices elements.
ret_program is the PI program created from the program binaries.
Definition at line 260 of file pi_native_cpu.cpp.
References pi2ur::piProgramCreateWithBinary().
piProgramGetBuildInfo()
pi_result piProgramGetBuildInfo (pi_program Program, pi_device Device, pi_program_build_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 317 of file pi_native_cpu.cpp.
References pi2ur::piProgramGetBuildInfo().
piProgramGetInfo()
pi_result piProgramGetInfo (pi_program Program, pi_program_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 279 of file pi_native_cpu.cpp.
References pi2ur::piProgramGetInfo().
piProgramLink()
pi_result piProgramLink (pi_context Context, pi_uint32 NumDevices, const pi_device * DeviceList, const char * Options, pi_uint32 NumInputPrograms, const pi_program * InputPrograms, void(*)(pi_program Program, void *UserData) PFnNotify, void * UserData, pi_program * RetProgram)
Definition at line 287 of file pi_native_cpu.cpp.
References pi2ur::piProgramLink().
piProgramRelease()
pi_result piProgramRelease (pi_program Program)
Definition at line 331 of file pi_native_cpu.cpp.
References pi2ur::piProgramRelease().
piProgramRetain()
pi_result piProgramRetain (pi_program Program)
Definition at line 327 of file pi_native_cpu.cpp.
References pi2ur::piProgramRetain().
piQueueCreate()
pi_result piQueueCreate (pi_context Context, pi_device Device, pi_queue_properties Flags, pi_queue * Queue)
Definition at line 168 of file pi_native_cpu.cpp.
References PI_QUEUE_FLAGS, and piextQueueCreate().
piQueueFinish()
pi_result piQueueFinish (pi_queue Queue)
Definition at line 193 of file pi_native_cpu.cpp.
References pi2ur::piQueueFinish().
piQueueFlush()
pi_result piQueueFlush (pi_queue Queue)
Definition at line 195 of file pi_native_cpu.cpp.
References pi2ur::piQueueFlush().
piQueueGetInfo()
pi_result piQueueGetInfo (pi_queue Queue, pi_queue_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 179 of file pi_native_cpu.cpp.
References pi2ur::piQueueGetInfo().
piQueueRelease()
pi_result piQueueRelease (pi_queue Queue)
Definition at line 189 of file pi_native_cpu.cpp.
References pi2ur::piQueueRelease().
piQueueRetain()
pi_result piQueueRetain (pi_queue Queue)
Definition at line 187 of file pi_native_cpu.cpp.
References pi2ur::piQueueRetain().
piSamplerCreate()
pi_result piSamplerCreate (pi_context Context, const pi_sampler_properties * SamplerProperties, pi_sampler * RetSampler)
Definition at line 635 of file pi_native_cpu.cpp.
References pi2ur::piSamplerCreate().
piSamplerGetInfo()
pi_result piSamplerGetInfo (pi_sampler Sampler, pi_sampler_info ParamName, size_t ParamValueSize, void * ParamValue, size_t * ParamValueSizeRet)
Definition at line 641 of file pi_native_cpu.cpp.
References pi2ur::piSamplerGetInfo().
piSamplerRelease()
pi_result piSamplerRelease (pi_sampler Sampler)
Definition at line 653 of file pi_native_cpu.cpp.
References pi2ur::piSamplerRelease().
piSamplerRetain()
pi_result piSamplerRetain (pi_sampler Sampler)
Definition at line 649 of file pi_native_cpu.cpp.
References pi2ur::piSamplerRetain().
piTearDown()
pi_result piTearDown (void * PluginParameter)
API to notify that the plugin should clean up its resources.
No PI calls should be made until the next piPluginInit call.
Parameters
PluginParameter placeholder for future use, currenly not used.
Definition at line 1212 of file pi_native_cpu.cpp.
References pi2ur::piTearDown().