DPC++ Runtime: plugins/level_zero/pi_level_zero.hpp File Reference
pi_level_zero.hpp File Reference
The Plugin Interface » Level Zero Plugin
Declarations for Level Zero Plugin.
#include <CL/sycl/detail/pi.h>
#include <atomic>
#include <cassert>
#include <cstring>
#include <iostream>
#include <list>
#include <map>
#include <memory>
#include <mutex>
#include <unordered_map>
#include <vector>
#include <level_zero/ze_api.h>
#include "usm_allocator.hpp"
Classes
struct _pi_object
struct _pi_platform
A PI platform stores all known PI devices, in the CUDA plugin this is just a vector of available devices since initialization is done when devices are used.
class USMMemoryAllocBase
class USMSharedMemoryAlloc
class USMDeviceMemoryAlloc
struct _pi_device
PI device mapping to a CUdevice.
struct _pi_context
PI context mapping to a CUDA context object.
struct _pi_queue
PI queue mapping on to CUstream objects.
struct _pi_mem
PI Mem mapping to CUDA memory allocations, both data and texture/surface.
struct _pi_mem::Mapping
struct _pi_buffer
struct _pi_image
struct _pi_event
PI Event mapping to CUevent.
struct _pi_program
Implementation of PI Program on CUDA Module object.
class _pi_program::LinkedReleaser
class _pi_program::ModuleIterator
struct _pi_kernel
Implementation of a PI Kernel for CUDA.
struct _pi_sampler
Implementation of samplers for CUDA.
Functions
template<class To , class From >
To pi_cast (From Value)
template<>
uint32_t pi_cast (uint64_t Value)
void die (const char *Message)
Detailed Description
Declarations for Level Zero Plugin.
It is the interface between the device-agnostic SYCL runtime layer and underlying Level Zero runtime.
Definition in file pi_level_zero.hpp.
Function Documentation
die()
void die (const char * Message)
Definition at line 52 of file pi_level_zero.hpp.
Referenced by cl::sycl::detail::pi::assertion(), cl::sycl::detail::SYCLConfig< SYCL_BE >::get(), cl::sycl::detail::pi::handleUnknownParamName(), piContextGetInfo(), piEnqueueEventsWait(), piEnqueueMemImageFill(), piEnqueueNativeKernel(), piEventSetCallback(), piEventSetStatus(), piextContextCreateWithNativeHandle(), piextContextSetExtendedDeleter(), piextEventCreateWithNativeHandle(), piextEventGetNativeHandle(), piextMemCreateWithNativeHandle(), piextMemGetNativeHandle(), piextProgramGetNativeHandle(), piKernelGetSubGroupInfo(), piMemBufferCreate(), piMemGetInfo(), piMemImageCreate(), piMemImageGetInfo(), piPlatformGetInfo(), piProgramGetInfo(), piQueueGetInfo(), piSamplerGetInfo(), cl::sycl::detail::pi::platformInfoToString(), and zeModuleDynamicLinkMock().
pi_cast() [1/2]
template<class To , class From > To pi_cast (From Value)
Definition at line 37 of file pi_level_zero.hpp.
Referenced by enqueueMemCopyRectHelper(), enqueueMemImageCommandHelper(), getImageRegionHelper(), piEnqueueKernelLaunch(), piextContextGetNativeHandle(), piextDeviceCreateWithNativeHandle(), piextDeviceGetNativeHandle(), piextPlatformCreateWithNativeHandle(), piextPlatformGetNativeHandle(), piextProgramCreateWithNativeHandle(), piextProgramGetNativeHandle(), piextQueueCreateWithNativeHandle(), piextQueueGetNativeHandle(), piextUSMEnqueueMemAdvise(), piMemImageCreate(), piProgramGetInfo(), and piSamplerCreate().
pi_cast() [2/2]
template<> uint32_t pi_cast (uint64_t Value)
Definition at line 43 of file pi_level_zero.hpp.
References cl::sycl::info::uint32_t.