DPC++ Runtime: include/CL/__spirv/spirv_ops.hpp File Reference
spirv_ops.hpp File Reference
#include <CL/__spirv/spirv_types.hpp>
#include <CL/sycl/detail/defines.hpp>
#include <CL/sycl/detail/export.hpp>
#include <cstddef>
#include <cstdint>
#include <type_traits>
Macros
#define __SYCL_CONVERGENT__
Functions
template<typename dataT >
__SYCL_CONVERGENT__ __ocl_event_t __SYCL_OpGroupAsyncCopyGlobalToLocal (__spv::Scope::Flag, dataT *Dest, dataT *Src, size_t NumElements, size_t Stride, __ocl_event_t) noexcept
template<typename dataT >
__SYCL_CONVERGENT__ __ocl_event_t __SYCL_OpGroupAsyncCopyLocalToGlobal (__spv::Scope::Flag, dataT *Dest, dataT *Src, size_t NumElements, size_t Stride, __ocl_event_t) noexcept
void __spirv_ocl_prefetch (const char *Ptr, size_t NumBytes) noexcept
__SYCL_CONVERGENT__ SYCL_EXTERNAL void __spirv_ControlBarrier (__spv::Scope Execution, __spv::Scope Memory, uint32_t Semantics) noexcept
__SYCL_CONVERGENT__ SYCL_EXTERNAL void __spirv_MemoryBarrier (__spv::Scope Memory, uint32_t Semantics) noexcept
__SYCL_CONVERGENT__ SYCL_EXTERNAL void __spirv_GroupWaitEvents (__spv::Scope Execution, uint32_t NumEvents, __ocl_event_t *WaitEvents) noexcept
Macro Definition Documentation
__SYCL_CONVERGENT__
#define __SYCL_CONVERGENT__
Definition at line 21 of file spirv_ops.hpp.
Referenced by __SYCL_OpGroupAsyncCopyGlobalToLocal(), and __SYCL_OpGroupAsyncCopyLocalToGlobal().
Function Documentation
__spirv_ControlBarrier()
__SYCL_CONVERGENT__ SYCL_EXTERNAL void __spirv_ControlBarrier (__spv::Scope Execution, __spv::Scope Memory, uint32_t Semantics) noexcept
Definition at line 26 of file spirv_ops.cpp.
Referenced by __SYCL_OpGroupAsyncCopyLocalToGlobal(), cl::sycl::nd_item< dimensions >::barrier(), cl::sycl::ONEAPI::sub_group::barrier(), and cl::sycl::detail::workGroupBarrier().
__spirv_GroupWaitEvents()
__SYCL_CONVERGENT__ SYCL_EXTERNAL void __spirv_GroupWaitEvents (__spv::Scope Execution, uint32_t NumEvents, __ocl_event_t * WaitEvents) noexcept
Definition at line 18 of file spirv_ops.cpp.
Referenced by __SYCL_OpGroupAsyncCopyLocalToGlobal(), and cl::sycl::device_event::wait().
__spirv_MemoryBarrier()
__SYCL_CONVERGENT__ SYCL_EXTERNAL void __spirv_MemoryBarrier (__spv::Scope Memory, uint32_t Semantics) noexcept
Definition at line 36 of file spirv_ops.cpp.
References cl::sycl::ONEAPI::memory_order_seq_cst.
Referenced by __SYCL_OpGroupAsyncCopyLocalToGlobal(), cl::sycl::ONEAPI::atomic_fence(), and cl::sycl::group< dimensions >::mem_fence().
__spirv_ocl_prefetch()
void __spirv_ocl_prefetch (const char * Ptr, size_t NumBytes) noexcept
Definition at line 47 of file spirv_ops.cpp.
References cl::sycl::detail::PlatformUtil::prefetch().
Referenced by __SYCL_OpGroupAsyncCopyLocalToGlobal(), and cl::sycl::multi_ptr< ElementType, Space >::prefetch().
__SYCL_OpGroupAsyncCopyGlobalToLocal()
template<typename dataT > __SYCL_CONVERGENT__ __ocl_event_t __SYCL_OpGroupAsyncCopyGlobalToLocal (__spv::Scope::Flag , dataT * Dest, dataT * Src, size_t NumElements, size_t Stride, __ocl_event_t) noexcept
Definition at line 530 of file spirv_ops.hpp.
References __SYCL_CONVERGENT__.
Referenced by cl::sycl::group< dimensions >::async_work_group_copy().
__SYCL_OpGroupAsyncCopyLocalToGlobal()
template<typename dataT > __SYCL_CONVERGENT__ __ocl_event_t __SYCL_OpGroupAsyncCopyLocalToGlobal (__spv::Scope::Flag , dataT * Dest, dataT * Src, size_t NumElements, size_t Stride, __ocl_event_t) noexcept
Definition at line 542 of file spirv_ops.hpp.
References __spirv_ControlBarrier(), __spirv_GroupWaitEvents(), __spirv_MemoryBarrier(), __spirv_ocl_prefetch(), __SYCL_CONVERGENT__, SYCL_EXTERNAL, and cl::sycl::info::uint32_t.
Referenced by cl::sycl::group< dimensions >::async_work_group_copy().