DPC++ Runtime: source/spirv_ops.cpp File Reference
spirv_ops.cpp File Reference
#include <CL/__spirv/spirv_ops.hpp>
#include <CL/sycl/exception.hpp>
#include <detail/platform_util.hpp>
#include <atomic>
Functions
void __spirv_GroupWaitEvents (__spv::Scope Execution, uint32_t NumEvents, __ocl_event_t *WaitEvents) noexcept
void __spirv_ControlBarrier (__spv::Scope Execution, __spv::Scope Memory, uint32_t Semantics) noexcept
void __spirv_MemoryBarrier (__spv::Scope Memory, uint32_t Semantics) noexcept
void __spirv_ocl_prefetch (const char *Ptr, size_t NumBytes) noexcept
Function Documentation
__spirv_ControlBarrier()
void __spirv_ControlBarrier (__spv::Scope Execution, __spv::Scope Memory, uint32_t Semantics) noexcept
Definition at line 23 of file spirv_ops.cpp.
Referenced by cl::sycl::nd_item< dimensions >::barrier(), cl::sycl::intel::sub_group::barrier(), cl::sycl::intel::barrier(), OpGroupAsyncCopyLocalToGlobal(), and cl::sycl::detail::workGroupBarrier().
__spirv_GroupWaitEvents()
void __spirv_GroupWaitEvents (__spv::Scope Execution, uint32_t NumEvents, __ocl_event_t * WaitEvents) noexcept
Definition at line 18 of file spirv_ops.cpp.
Referenced by OpGroupAsyncCopyLocalToGlobal(), and cl::sycl::device_event::wait().
__spirv_MemoryBarrier()
void __spirv_MemoryBarrier (__spv::Scope Memory, uint32_t Semantics) noexcept
Definition at line 30 of file spirv_ops.cpp.
References cl::sycl::intel::memory_order_seq_cst.
Referenced by cl::sycl::intel::atomic_fence(), cl::sycl::group< dimensions >::mem_fence(), and OpGroupAsyncCopyLocalToGlobal().
__spirv_ocl_prefetch()
void __spirv_ocl_prefetch (const char * Ptr, size_t NumBytes) noexcept
Definition at line 39 of file spirv_ops.cpp.
References cl::sycl::detail::PlatformUtil::prefetch().
Referenced by OpGroupAsyncCopyLocalToGlobal(), and cl::sycl::multi_ptr< ElementType, Space >::prefetch().