DPC++ Runtime: _pi_ze_event_list_t Struct Reference
_pi_ze_event_list_t Struct Reference
#include <level_zero/pi_level_zero.hpp>
Public Member Functions
pi_result createAndRetainPiZeEventList (pi_uint32 EventListLength, const pi_event *EventList, pi_queue CurQueue)
pi_result collectEventsForReleaseAndDestroyPiZeEventList (std::list< pi_event > &EventsToBeReleased)
_pi_ze_event_list_t & operator= (const _pi_ze_event_list_t &other)
Public Attributes
ze_event_handle_t * ZeEventList = {nullptr}
pi_event * PiEventList = {nullptr}
pi_uint32 Length = {0}
std::mutex PiZeEventListMutex
Detailed Description
Definition at line 727 of file pi_level_zero.hpp.
Member Function Documentation
collectEventsForReleaseAndDestroyPiZeEventList()
pi_result _pi_ze_event_list_t::collectEventsForReleaseAndDestroyPiZeEventList (std::list< pi_event > & EventsToBeReleased)
Definition at line 1094 of file pi_level_zero.cpp.
References Length, PI_SUCCESS, PiEventList, PiZeEventListMutex, and ZeEventList.
Referenced by cleanupAfterEvent().
createAndRetainPiZeEventList()
pi_result _pi_ze_event_list_t::createAndRetainPiZeEventList (pi_uint32 EventListLength, const pi_event * EventList, pi_queue CurQueue)
Definition at line 1011 of file pi_level_zero.cpp.
References FilterEventWaitList, _pi_queue::isInOrderQueue(), _pi_queue::LastCommandEvent, Length, PI_CALL, PI_OUT_OF_HOST_MEMORY, PI_SUCCESS, PiEventList, piEventRetain(), _pi_event::Queue, ZE_CALL_NOCHECK, _pi_event::ZeEvent, and ZeEventList.
Referenced by enqueueMemCopyHelper(), enqueueMemCopyRectHelper(), enqueueMemFillHelper(), enqueueMemImageCommandHelper(), piEnqueueEventsWait(), piEnqueueEventsWaitWithBarrier(), piEnqueueKernelLaunch(), piEnqueueMemBufferMap(), piEnqueueMemUnmap(), and piextUSMEnqueuePrefetch().
operator=()
_pi_ze_event_list_t& _pi_ze_event_list_t::operator= (const _pi_ze_event_list_t & other) inline
Definition at line 764 of file pi_level_zero.hpp.
References Length, PiEventList, and ZeEventList.
Member Data Documentation
Length
pi_uint32 _pi_ze_event_list_t::Length = {0}
Definition at line 737 of file pi_level_zero.hpp.
Referenced by collectEventsForReleaseAndDestroyPiZeEventList(), createAndRetainPiZeEventList(), operator=(), and printZeEventList().
PiEventList
pi_event* _pi_ze_event_list_t::PiEventList = {nullptr}
Definition at line 732 of file pi_level_zero.hpp.
Referenced by collectEventsForReleaseAndDestroyPiZeEventList(), createAndRetainPiZeEventList(), and operator=().
PiZeEventListMutex
std::mutex _pi_ze_event_list_t::PiZeEventListMutex
Definition at line 744 of file pi_level_zero.hpp.
Referenced by collectEventsForReleaseAndDestroyPiZeEventList().
ZeEventList
ze_event_handle_t* _pi_ze_event_list_t::ZeEventList = {nullptr}
Definition at line 729 of file pi_level_zero.hpp.
Referenced by collectEventsForReleaseAndDestroyPiZeEventList(), createAndRetainPiZeEventList(), operator=(), and printZeEventList().
The documentation for this struct was generated from the following files:
plugins/level_zero/pi_level_zero.hpp
plugins/level_zero/pi_level_zero.cpp