DPC++ Runtime: _pi_context Struct Reference
_pi_context Struct Reference
PI context mapping to a CUDA context object.
#include <cuda/pi_cuda.hpp>
Classes
struct deleter_data
Public Types
enum kind { kind::primary, kind::user_defined }
using native_type = CUcontext
Public Member Functions
_pi_context (kind k, CUcontext ctxt, _pi_device *devId)
~_pi_context ()
void invoke_extended_deleters ()
void set_extended_deleter (pi_context_extended_deleter function, void *user_data)
pi_device get_device () const noexcept
native_type get () const noexcept
bool is_primary () const noexcept
pi_uint32 increment_reference_count () noexcept
pi_uint32 decrement_reference_count () noexcept
pi_uint32 get_reference_count () const noexcept
_pi_context (pi_device Device)
ze_result_t getFreeSlotInExistingOrNewPool (ze_event_pool_handle_t &, size_t &)
ze_result_t decrementAliveEventsInPool (ze_event_pool_handle_t pool)
Public Member Functions inherited from _pi_object
_pi_object ()
Public Attributes
enum _pi_context::kind kind_
native_type cuContext_
_pi_device * deviceId_
std::atomic_uint32_t refCount_
CUevent evBase_
pi_device Device
Public Attributes inherited from _pi_object
std::atomic< pi_uint32 > RefCount
Detailed Description
PI context mapping to a CUDA context object.
There is no direct mapping between a CUDA context and a PI context, main differences described below:
CUDA context vs PI context
One of the main differences between the PI API and the CUDA driver API is that the second modifies the state of the threads by assigning CUcontext objects to threads. CUcontext objects store data associated with a given device and control access to said device from the user side. PI API context are objects that are passed to functions, and not bound to threads. The _pi_context object doesn't implement this behavior, only holds the CUDA context data. The RAII object ScopedContext implements the active context behavior.
Primary vs User-defined context
CUDA has two different types of context, the Primary context, which is usable by all threads on a given process for a given device, and the aforementioned custom contexts. CUDA documentation, and performance analysis, indicates it is recommended to use Primary context whenever possible. Primary context is used as well by the CUDA Runtime API. For PI applications to interop with CUDA Runtime API, they have to use the primary context - and make that active in the thread. The _pi_context object can be constructed with a kind parameter that allows to construct a Primary or user-defined context, so that the PI object interface is always the same.
Destructor callback
Required to implement CP023, SYCL Extended Context Destruction, the PI Context can store a number of callback functions that will be called upon destruction of the PI Context. See proposal for details.
Definition at line 123 of file pi_cuda.hpp.
Member Typedef Documentation
native_type
using _pi_context::native_type = CUcontext
Definition at line 132 of file pi_cuda.hpp.
Member Enumeration Documentation
kind
enum _pi_context::kind strong
Enumerator
primary
user_defined
Definition at line 134 of file pi_cuda.hpp.
Constructor & Destructor Documentation
_pi_context() [1/2]
_pi_context::_pi_context (kind k, CUcontext ctxt, _pi_device * devId) inline
Definition at line 141 of file pi_cuda.hpp.
References cuda_piDeviceRetain().
~_pi_context()
_pi_context::~_pi_context () inline
Definition at line 147 of file pi_cuda.hpp.
References cuda_piDeviceRelease().
_pi_context() [2/2]
_pi_context::_pi_context (pi_device Device) inline
Definition at line 116 of file pi_level0.hpp.
Member Function Documentation
decrement_reference_count()
pi_uint32 _pi_context::decrement_reference_count () inline noexcept
Definition at line 170 of file pi_cuda.hpp.
Referenced by cuda_piContextRelease().
decrementAliveEventsInPool()
ze_result_t _pi_context::decrementAliveEventsInPool (ze_event_pool_handle_t pool)
Definition at line 224 of file pi_level0.cpp.
Referenced by piEventRelease().
get()
native_type _pi_context::get () const inline noexcept
Definition at line 164 of file pi_cuda.hpp.
Referenced by cuda_piContextRelease(), and cuda_piextContextGetNativeHandle().
get_device()
pi_device _pi_context::get_device () const inline noexcept
Definition at line 162 of file pi_cuda.hpp.
Referenced by cuda_piContextGetInfo(), cuda_piContextRelease(), cuda_piextUSMEnqueuePrefetch(), and cuda_piQueueCreate().
get_reference_count()
pi_uint32 _pi_context::get_reference_count () const inline noexcept
Definition at line 172 of file pi_cuda.hpp.
Referenced by cuda_piContextGetInfo(), and cuda_piContextRetain().
getFreeSlotInExistingOrNewPool()
ze_result_t _pi_context::getFreeSlotInExistingOrNewPool (ze_event_pool_handle_t & ZePool, size_t & Index)
Definition at line 169 of file pi_level0.cpp.
Referenced by piEventCreate().
increment_reference_count()
pi_uint32 _pi_context::increment_reference_count () inline noexcept
Definition at line 168 of file pi_cuda.hpp.
Referenced by cuda_piContextRetain().
invoke_extended_deleters()
void _pi_context::invoke_extended_deleters () inline
Definition at line 149 of file pi_cuda.hpp.
Referenced by cuda_piContextRelease().
is_primary()
bool _pi_context::is_primary () const inline noexcept
Definition at line 166 of file pi_cuda.hpp.
Referenced by cuda_piContextRelease().
set_extended_deleter()
void _pi_context::set_extended_deleter (pi_context_extended_deleter function, void * user_data) inline
Definition at line 156 of file pi_cuda.hpp.
Referenced by cuda_piextContextSetExtendedDeleter().
Member Data Documentation
cuContext_
native_type _pi_context::cuContext_
Definition at line 135 of file pi_cuda.hpp.
Device
pi_device _pi_context::Device
Definition at line 123 of file pi_level0.hpp.
Referenced by enqueueMemCopyHelper(), enqueueMemCopyRectHelper(), enqueueMemFillHelper(), enqueueMemImageCommandHelper(), piclProgramCreateWithBinary(), piContextGetInfo(), piEnqueueKernelLaunch(), piEnqueueMemBufferMap(), piEnqueueMemUnmap(), piEventGetProfilingInfo(), piEventRelease(), piextUSMDeviceAlloc(), piextUSMEnqueueMemAdvise(), piextUSMEnqueuePrefetch(), piextUSMFree(), piextUSMGetMemAllocInfo(), piextUSMHostAlloc(), piextUSMSharedAlloc(), piMemBufferCreate(), piMemImageCreate(), piProgramCreate(), piProgramGetInfo(), piQueueCreate(), piQueueGetInfo(), and piSamplerCreate().
deviceId_
_pi_device* _pi_context::deviceId_
Definition at line 136 of file pi_cuda.hpp.
Referenced by cuda_piProgramGetInfo().
evBase_
CUevent _pi_context::evBase_
Definition at line 139 of file pi_cuda.hpp.
Referenced by _pi_event::get_end_time(), _pi_event::get_queued_time(), and _pi_event::get_start_time().
kind_
enum _pi_context::kind _pi_context::kind_
refCount_
std::atomic_uint32_t _pi_context::refCount_
Definition at line 137 of file pi_cuda.hpp.
The documentation for this struct was generated from the following files:
plugins/cuda/pi_cuda.hpp
plugins/level_zero/pi_level0.hpp
plugins/level_zero/pi_level0.cpp