DPC++ Runtime: _pi_sampler Struct Reference
_pi_sampler Struct Reference
Implementation of samplers for CUDA.
#include <cuda/pi_cuda.hpp>
Public Member Functions
_pi_sampler (pi_context context)
pi_uint32 increment_reference_count () noexcept
pi_uint32 decrement_reference_count () noexcept
pi_uint32 get_reference_count () const noexcept
_pi_sampler (pi_context context)
pi_uint32 increment_reference_count () noexcept
pi_uint32 decrement_reference_count () noexcept
pi_uint32 get_reference_count () const noexcept
_pi_sampler (ze_sampler_handle_t Sampler)
Public Attributes
std::atomic_uint32_t refCount_
pi_uint32 props_
pi_context context_
ze_sampler_handle_t ZeSampler
Detailed Description
Implementation of samplers for CUDA.
Implementation of samplers for HIP.
Sampler property layout: | 31 30 ... 6 5 | 4 3 2 | 1 | 0 | | N/A | addressing mode | fiter mode | normalize coords |
Definition at line 751 of file pi_cuda.hpp.
Constructor & Destructor Documentation
_pi_sampler() [1/3]
_pi_sampler::_pi_sampler (pi_context context) inline
Definition at line 756 of file pi_cuda.hpp.
_pi_sampler() [2/3]
_pi_sampler::_pi_sampler (pi_context context) inline
Definition at line 726 of file pi_hip.hpp.
_pi_sampler() [3/3]
_pi_sampler::_pi_sampler (ze_sampler_handle_t Sampler) inline
Definition at line 1309 of file pi_level_zero.hpp.
Member Function Documentation
decrement_reference_count() [1/2]
pi_uint32 _pi_sampler::decrement_reference_count () inline noexcept
Definition at line 731 of file pi_hip.hpp.
References refCount_.
decrement_reference_count() [2/2]
pi_uint32 _pi_sampler::decrement_reference_count () inline noexcept
Definition at line 761 of file pi_cuda.hpp.
References refCount_.
Referenced by cuda_piSamplerRelease(), and hip_piSamplerRelease().
get_reference_count() [1/2]
pi_uint32 _pi_sampler::get_reference_count () const inline noexcept
Definition at line 733 of file pi_hip.hpp.
References refCount_.
get_reference_count() [2/2]
pi_uint32 _pi_sampler::get_reference_count () const inline noexcept
Definition at line 763 of file pi_cuda.hpp.
References refCount_.
Referenced by cuda_piSamplerGetInfo(), cuda_piSamplerRelease(), hip_piSamplerGetInfo(), and hip_piSamplerRelease().
increment_reference_count() [1/2]
pi_uint32 _pi_sampler::increment_reference_count () inline noexcept
Definition at line 729 of file pi_hip.hpp.
References refCount_.
increment_reference_count() [2/2]
pi_uint32 _pi_sampler::increment_reference_count () inline noexcept
Definition at line 759 of file pi_cuda.hpp.
References refCount_.
Referenced by cuda_piSamplerRetain(), and hip_piSamplerRetain().
Member Data Documentation
context_
pi_context _pi_sampler::context_
Definition at line 754 of file pi_cuda.hpp.
Referenced by cuda_piSamplerGetInfo(), and hip_piSamplerGetInfo().
props_
pi_uint32 _pi_sampler::props_
Definition at line 753 of file pi_cuda.hpp.
Referenced by cuda_piSamplerGetInfo(), and hip_piSamplerGetInfo().
refCount_
std::atomic_uint32_t _pi_sampler::refCount_
Definition at line 752 of file pi_cuda.hpp.
Referenced by decrement_reference_count(), get_reference_count(), and increment_reference_count().
ZeSampler
ze_sampler_handle_t _pi_sampler::ZeSampler
Definition at line 1312 of file pi_level_zero.hpp.
Referenced by piSamplerRelease().
The documentation for this struct was generated from the following files:
plugins/cuda/pi_cuda.hpp
plugins/hip/pi_hip.hpp
plugins/level_zero/pi_level_zero.hpp