DPC++ Runtime: _pi_mem::mem_::surface_mem_ Struct Reference
_pi_mem::mem_::surface_mem_ Struct Reference
#include <cuda/pi_cuda.hpp>
Public Member Functions
CUarray get_array () const noexcept
CUsurfObject get_surface () const noexcept
pi_mem_type get_image_type () const noexcept
hipArray * get_array () const noexcept
hipSurfaceObject_t get_surface () const noexcept
pi_mem_type get_image_type () const noexcept
Public Attributes
CUarray array_
CUsurfObject surfObj_
pi_mem_type imageType_
hipArray * array_
hipSurfaceObject_t surfObj_
Detailed Description
Definition at line 305 of file pi_cuda.hpp.
Member Function Documentation
get_array() [1/2]
hipArray* _pi_mem::mem_::surface_mem_::get_array () const inline noexcept
Definition at line 296 of file pi_hip.hpp.
References array_.
get_array() [2/2]
CUarray _pi_mem::mem_::surface_mem_::get_array () const inline noexcept
Definition at line 310 of file pi_cuda.hpp.
References array_.
Referenced by cuda_piEnqueueMemImageCopy(), cuda_piextKernelSetArgMemObj(), hip_piEnqueueMemImageCopy(), and hip_piextKernelSetArgMemObj().
get_image_type() [1/2]
pi_mem_type _pi_mem::mem_::surface_mem_::get_image_type () const inline noexcept
Definition at line 300 of file pi_hip.hpp.
References imageType_.
get_image_type() [2/2]
pi_mem_type _pi_mem::mem_::surface_mem_::get_image_type () const inline noexcept
Definition at line 314 of file pi_cuda.hpp.
References imageType_.
Referenced by cuda_piEnqueueMemImageCopy(), and hip_piEnqueueMemImageCopy().
get_surface() [1/2]
hipSurfaceObject_t _pi_mem::mem_::surface_mem_::get_surface () const inline noexcept
Definition at line 298 of file pi_hip.hpp.
References surfObj_.
get_surface() [2/2]
CUsurfObject _pi_mem::mem_::surface_mem_::get_surface () const inline noexcept
Definition at line 312 of file pi_cuda.hpp.
References surfObj_.
Referenced by cuda_piextKernelSetArgMemObj(), and hip_piextKernelSetArgMemObj().
Member Data Documentation
array_ [1/2]
hipArray* _pi_mem::mem_::surface_mem_::array_
Definition at line 292 of file pi_hip.hpp.
array_ [2/2]
CUarray _pi_mem::mem_::surface_mem_::array_
Definition at line 306 of file pi_cuda.hpp.
Referenced by get_array().
imageType_
pi_mem_type _pi_mem::mem_::surface_mem_::imageType_
Definition at line 308 of file pi_cuda.hpp.
Referenced by get_image_type().
surfObj_ [1/2]
hipSurfaceObject_t _pi_mem::mem_::surface_mem_::surfObj_
Definition at line 293 of file pi_hip.hpp.
surfObj_ [2/2]
CUsurfObject _pi_mem::mem_::surface_mem_::surfObj_
Definition at line 307 of file pi_cuda.hpp.
Referenced by get_surface().
The documentation for this struct was generated from the following files:
plugins/cuda/pi_cuda.hpp
plugins/hip/pi_hip.hpp