DPC++ Runtime: sycl::_V1::ext::oneapi::sub_group_mask::reference Struct Reference
sycl::_V1::ext::oneapi::sub_group_mask::reference Struct Reference
#include <sycl/ext/oneapi/sub_group_mask.hpp>
Public Member Functions
reference & operator= (bool x)
reference & operator= (const reference &x)
bool operator~ () const
operator bool () const
reference & flip ()
reference (sub_group_mask &gmask, size_t pos)
Detailed Description
Definition at line 64 of file sub_group_mask.hpp.
Constructor & Destructor Documentation
reference()
sycl::_V1::ext::oneapi::sub_group_mask::reference::reference (sub_group_mask & gmask, size_t pos) inline
Definition at line 84 of file sub_group_mask.hpp.
Member Function Documentation
flip()
reference& sycl::_V1::ext::oneapi::sub_group_mask::reference::flip () inline
Definition at line 79 of file sub_group_mask.hpp.
References operator=().
operator bool()
sycl::_V1::ext::oneapi::sub_group_mask::reference::operator bool () const inline
Definition at line 78 of file sub_group_mask.hpp.
operator=() [1/2]
reference& sycl::_V1::ext::oneapi::sub_group_mask::reference::operator= (bool x) inline
Definition at line 65 of file sub_group_mask.hpp.
Referenced by flip(), and operator=().
operator=() [2/2]
reference& sycl::_V1::ext::oneapi::sub_group_mask::reference::operator= (const reference & x) inline
Definition at line 73 of file sub_group_mask.hpp.
References operator=().
operator~()
bool sycl::_V1::ext::oneapi::sub_group_mask::reference::operator~ () const inline
Definition at line 77 of file sub_group_mask.hpp.
The documentation for this struct was generated from the following file:
include/sycl/ext/oneapi/sub_group_mask.hpp