DPC++ Runtime: sycl::_V1::detail::code_location Struct Reference
sycl::_V1::detail::code_location Struct Reference
#include <sycl/detail/common.hpp>
Public Member Functions
constexpr code_location (const char *file, const char *func, int line, int col) noexcept
constexpr code_location () noexcept
constexpr unsigned long lineNumber () const noexcept
constexpr unsigned long columnNumber () const noexcept
constexpr const char * fileName () const noexcept
constexpr const char * functionName () const noexcept
Static Public Member Functions
static constexpr code_location current (const char *fileName=__CODELOC_FILE_NAME, const char *funcName=__CODELOC_FUNCTION, unsigned long lineNo=__CODELOC_LINE, unsigned long columnNo=__CODELOC_COLUMN) noexcept
Detailed Description
Definition at line 66 of file common.hpp.
Constructor & Destructor Documentation
code_location() [1/2]
constexpr sycl::_V1::detail::code_location::code_location (const char * file, const char * func, int line, int col) inline constexpr noexcept
Definition at line 80 of file common.hpp.
code_location() [2/2]
constexpr sycl::_V1::detail::code_location::code_location () inline constexpr noexcept
Definition at line 84 of file common.hpp.
Referenced by current().
Member Function Documentation
columnNumber()
constexpr unsigned long sycl::_V1::detail::code_location::columnNumber () const inline constexpr noexcept
Definition at line 88 of file common.hpp.
Referenced by sycl::_V1::detail::queue_impl::instrumentationProlog(), and sycl::_V1::detail::report().
current()
static constexpr code_location sycl::_V1::detail::code_location::current (const char * fileName = __CODELOC_FILE_NAME, const char * funcName = __CODELOC_FUNCTION, unsigned long lineNo = __CODELOC_LINE, unsigned long columnNo = __CODELOC_COLUMN) inline static constexpr noexcept
Definition at line 68 of file common.hpp.
References code_location(), and fileName().
fileName()
constexpr const char* sycl::_V1::detail::code_location::fileName () const inline constexpr noexcept
Definition at line 89 of file common.hpp.
Referenced by current(), sycl::_V1::detail::queue_impl::instrumentationProlog(), sycl::_V1::detail::report(), and sycl::_V1::detail::tls_code_loc_t::tls_code_loc_t().
functionName()
constexpr const char* sycl::_V1::detail::code_location::functionName () const inline constexpr noexcept
Definition at line 90 of file common.hpp.
Referenced by sycl::_V1::detail::queue_impl::instrumentationProlog(), sycl::_V1::detail::report(), and sycl::_V1::detail::tls_code_loc_t::tls_code_loc_t().
lineNumber()
constexpr unsigned long sycl::_V1::detail::code_location::lineNumber () const inline constexpr noexcept
Definition at line 87 of file common.hpp.
Referenced by sycl::_V1::detail::queue_impl::instrumentationProlog(), and sycl::_V1::detail::report().
The documentation for this struct was generated from the following file:
include/sycl/detail/common.hpp