DPC++ Runtime: sycl::_V1::detail::get_device_info_impl< ReturnT, Param > Struct Template Reference
sycl::_V1::detail::get_device_info_impl< ReturnT, Param > Struct Template Reference
#include <detail/device_info.hpp>
Static Public Member Functions
static ReturnT get (const DeviceImplPtr &Dev)
Detailed Description
template<typename ReturnT, typename Param>
struct sycl::_V1::detail::get_device_info_impl< ReturnT, Param >
Definition at line 140 of file device_info.hpp.
Member Function Documentation
get()
template<typename ReturnT , typename Param > static ReturnT sycl::_V1::detail::get_device_info_impl< ReturnT, Param >::get (const DeviceImplPtr & Dev) inline static
Definition at line 141 of file device_info.hpp.
References piDeviceGetInfo().
Referenced by sycl::_V1::detail::get_device_info_impl< std::vector< info::fp_config >, Param >::get(), sycl::_V1::detail::get_device_info_impl< std::vector< std::string >, info::device::extensions >::get(), sycl::_V1::detail::get_device_info_impl< bool, info::device::kernel_kernel_pipe_support >::get(), sycl::_V1::detail::get_device_info_impl< std::vector< ext::oneapi::experimental::matrix::combination >, ext::oneapi::experimental::info::device::matrix_combinations >::get(), sycl::_V1::detail::get_device_info_impl< id< 1 >, ext::oneapi::experimental::info::device::max_work_groups< 1 > >::get(), sycl::_V1::detail::get_device_info_impl< id< 2 >, ext::oneapi::experimental::info::device::max_work_groups< 2 > >::get(), sycl::_V1::detail::get_device_info_impl< id< 3 >, ext::oneapi::experimental::info::device::max_work_groups< 3 > >::get(), sycl::_V1::detail::get_device_info_impl< size_t, info::device::ext_oneapi_max_global_work_groups >::get(), sycl::_V1::detail::get_device_info_impl< id< 1 >, info::device::ext_oneapi_max_work_groups_1d >::get(), sycl::_V1::detail::get_device_info_impl< id< 2 >, info::device::ext_oneapi_max_work_groups_2d >::get(), sycl::_V1::detail::get_device_info_impl< id< 3 >, info::device::ext_oneapi_max_work_groups_3d >::get(), and sycl::_V1::detail::get_device_info().
The documentation for this struct was generated from the following file:
source/detail/device_info.hpp