DPC++ Runtime: sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_atomic_cross_wg > Struct Reference
sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_atomic_cross_wg > Struct Reference
#include <sycl/reduction.hpp>
Static Public Member Functions
template<typename KernelName , int Dims, typename PropertiesT , typename KernelType , typename Reduction >
static void run (handler &CGH, std::shared_ptr< detail::queue_impl > &Queue, nd_range< Dims > NDRange, PropertiesT &Properties, Reduction &Redu, KernelType &KernelFunc)
Detailed Description
Definition at line 1586 of file reduction.hpp.
Member Function Documentation
run()
template<typename KernelName , int Dims, typename PropertiesT , typename KernelType , typename Reduction > static void sycl::_V1::detail::NDRangeReduction< reduction::strategy::group_reduce_and_atomic_cross_wg >::run (handler & CGH, std::shared_ptr< detail::queue_impl > & Queue, nd_range< Dims > NDRange, PropertiesT & Properties, Reduction & Redu, KernelType & KernelFunc) inline static
Definition at line 1589 of file reduction.hpp.
References sycl::_V1::detail::getReducerAccess(), sycl::_V1::detail::reduction::group_reduce_and_atomic_cross_wg, sycl::_V1::handler::parallel_for(), and sycl::_V1::reduce_over_group().
The documentation for this struct was generated from the following file:
include/sycl/reduction.hpp