DPC++ Runtime: sycl::_V1::detail::DeviceGlobalMapEntry Struct Reference
sycl::_V1::detail::DeviceGlobalMapEntry Struct Reference
#include <detail/device_global_map_entry.hpp>
Public Member Functions
DeviceGlobalMapEntry (std::string UniqueId, const void *DeviceGlobalPtr)
DeviceGlobalMapEntry (std::string UniqueId, RTDeviceBinaryImage *Img, std::uint32_t DeviceGlobalTSize, bool IsDeviceImageScopeDecorated)
void initialize (const void *DeviceGlobalPtr)
void initialize (RTDeviceBinaryImage *Img, std::uint32_t DeviceGlobalTSize, bool IsDeviceImageScopeDecorated)
DeviceGlobalUSMMem & getOrAllocateDeviceGlobalUSM (const std::shared_ptr< queue_impl > &QueueImpl)
void removeAssociatedResources (const context_impl *CtxImpl)
Public Attributes
std::string MUniqueId
const void * MDeviceGlobalPtr = nullptr
std::unordered_set< RTDeviceBinaryImage * > MImages
std::set< std::uintptr_t > MImageIdentifiers
std::uint32_t MDeviceGlobalTSize = 0
bool MIsDeviceImageScopeDecorated = false
Detailed Description
Definition at line 52 of file device_global_map_entry.hpp.
Constructor & Destructor Documentation
DeviceGlobalMapEntry() [1/2]
sycl::_V1::detail::DeviceGlobalMapEntry::DeviceGlobalMapEntry (std::string UniqueId, const void * DeviceGlobalPtr) inline
Definition at line 69 of file device_global_map_entry.hpp.
DeviceGlobalMapEntry() [2/2]
sycl::_V1::detail::DeviceGlobalMapEntry::DeviceGlobalMapEntry (std::string UniqueId, RTDeviceBinaryImage * Img, std::uint32_t DeviceGlobalTSize, bool IsDeviceImageScopeDecorated) inline
Definition at line 74 of file device_global_map_entry.hpp.
Member Function Documentation
getOrAllocateDeviceGlobalUSM()
DeviceGlobalUSMMem & sycl::_V1::detail::DeviceGlobalMapEntry::getOrAllocateDeviceGlobalUSM (const std::shared_ptr< queue_impl > & QueueImpl)
Definition at line 44 of file device_global_map_entry.cpp.
References sycl::_V1::detail::usm::alignedAllocInternal(), sycl::_V1::detail::MemoryManager::copy_usm(), MDeviceGlobalPtr, MDeviceGlobalTSize, and MIsDeviceImageScopeDecorated.
Referenced by sycl::_V1::detail::memcpyFromDeviceGlobalUSM(), and sycl::_V1::detail::memcpyToDeviceGlobalUSM().
initialize() [1/2]
void sycl::_V1::detail::DeviceGlobalMapEntry::initialize (const void * DeviceGlobalPtr) inline
Definition at line 83 of file device_global_map_entry.hpp.
References MDeviceGlobalPtr.
initialize() [2/2]
void sycl::_V1::detail::DeviceGlobalMapEntry::initialize (RTDeviceBinaryImage * Img, std::uint32_t DeviceGlobalTSize, bool IsDeviceImageScopeDecorated) inline
Definition at line 92 of file device_global_map_entry.hpp.
References MDeviceGlobalTSize, MImageIdentifiers, MImages, and MIsDeviceImageScopeDecorated.
removeAssociatedResources()
void sycl::_V1::detail::DeviceGlobalMapEntry::removeAssociatedResources (const context_impl * CtxImpl)
Definition at line 92 of file device_global_map_entry.cpp.
References sycl::_V1::detail::usm::freeInternal(), sycl::_V1::detail::context_impl::getDevices(), sycl::_V1::detail::context_impl::getPlugin(), sycl::_V1::detail::getSyclObjImpl(), and piEventRelease().
Referenced by sycl::_V1::detail::context_impl::~context_impl().
Member Data Documentation
MDeviceGlobalPtr
const void* sycl::_V1::detail::DeviceGlobalMapEntry::MDeviceGlobalPtr = nullptr
Definition at line 56 of file device_global_map_entry.hpp.
Referenced by getOrAllocateDeviceGlobalUSM(), and initialize().
MDeviceGlobalTSize
std::uint32_t sycl::_V1::detail::DeviceGlobalMapEntry::MDeviceGlobalTSize = 0
Definition at line 63 of file device_global_map_entry.hpp.
Referenced by sycl::_V1::detail::MemoryManager::copy_from_device_global(), sycl::_V1::detail::MemoryManager::copy_to_device_global(), getOrAllocateDeviceGlobalUSM(), and initialize().
MImageIdentifiers
std::set<std::uintptr_t> sycl::_V1::detail::DeviceGlobalMapEntry::MImageIdentifiers
Definition at line 61 of file device_global_map_entry.hpp.
Referenced by sycl::_V1::detail::getOrBuildProgramForDeviceGlobal(), sycl::_V1::detail::context_impl::getProgramForDeviceGlobal(), initialize(), and sycl::_V1::detail::isDeviceGlobalUsedInKernel().
MImages
std::unordered_set<RTDeviceBinaryImage *> sycl::_V1::detail::DeviceGlobalMapEntry::MImages
Definition at line 58 of file device_global_map_entry.hpp.
Referenced by sycl::_V1::detail::getOrBuildProgramForDeviceGlobal(), and initialize().
MIsDeviceImageScopeDecorated
bool sycl::_V1::detail::DeviceGlobalMapEntry::MIsDeviceImageScopeDecorated = false
Definition at line 65 of file device_global_map_entry.hpp.
Referenced by sycl::_V1::detail::MemoryManager::copy_from_device_global(), sycl::_V1::detail::MemoryManager::copy_to_device_global(), getOrAllocateDeviceGlobalUSM(), sycl::_V1::detail::getOrBuildProgramForDeviceGlobal(), and initialize().
MUniqueId
std::string sycl::_V1::detail::DeviceGlobalMapEntry::MUniqueId
Definition at line 54 of file device_global_map_entry.hpp.
Referenced by sycl::_V1::detail::memcpyFromDeviceGlobalDirect(), and sycl::_V1::detail::memcpyToDeviceGlobalDirect().
The documentation for this struct was generated from the following files:
source/detail/device_global_map_entry.hpp
source/detail/device_global_map_entry.cpp