DPC++ Runtime: _pi_program Struct Reference
_pi_program Struct Reference
Implementation of PI Program on CUDA Module object.
#include <cuda/pi_cuda.hpp>
Classes
class SpecConstantShim
Public Types
enum state {
IL, Native, Object, Exe,
Invalid
}
using native_type = CUmodule
using native_type = hipModule_t
Public Member Functions
_pi_program (pi_context ctxt)
~_pi_program ()
pi_result set_metadata (const pi_device_binary_property *metadata, size_t length)
pi_result set_binary (const char *binary, size_t binarySizeInBytes)
pi_result build_program (const char *build_options)
pi_context get_context () const
native_type get () const noexcept
pi_uint32 increment_reference_count () noexcept
pi_uint32 decrement_reference_count () noexcept
pi_uint32 get_reference_count () const noexcept
_pi_program ()
_pi_program (pi_context ctxt)
~_pi_program ()
pi_result set_binary (const char *binary, size_t binarySizeInBytes)
pi_result build_program (const char *build_options)
pi_context get_context () const
native_type get () const noexcept
pi_uint32 increment_reference_count () noexcept
pi_uint32 decrement_reference_count () noexcept
pi_uint32 get_reference_count () const noexcept
_pi_program (state St, pi_context Context, const void *Input, size_t Length)
_pi_program (state St, pi_context Context, ze_module_handle_t ZeModule, ze_module_build_log_handle_t ZeBuildLog)
_pi_program (state St, pi_context Context, ze_module_handle_t ZeModule, bool OwnZeModule)
_pi_program (state St, pi_context Context, const std::string &ErrorMessage)
~_pi_program ()
Public Attributes
native_type module_
const char * binary_
size_t binarySizeInBytes_
std::atomic_uint32_t refCount_
_pi_context * context_
std::unordered_map< std::string, std::tuple< uint32_t, uint32_t, uint32_t > > kernelReqdWorkGroupSizeMD_
char errorLog_ [MAX_LOG_SIZE]
char infoLog_ [MAX_LOG_SIZE]
std::string buildOptions_
pi_program_build_status buildStatus_ = PI_PROGRAM_BUILD_STATUS_NONE
pi_context Context
const pi_context Context
const bool OwnZeModule
const std::string ErrorMessage
state State
std::unique_ptr< uint8_t[]> Code
size_t CodeLength
std::unordered_map< uint32_t, const void * > SpecConstants
std::string BuildFlags
ze_module_handle_t ZeModule
ze_module_build_log_handle_t ZeBuildLog
Static Public Attributes
constexpr static size_t MAX_LOG_SIZE = 8192u
Detailed Description
Implementation of PI Program on CUDA Module object.
Implementation of PI Program on HIP Module object.
Definition at line 524 of file pi_cuda.hpp.
Member Typedef Documentation
native_type [1/2]
using _pi_program::native_type = hipModule_t
Definition at line 508 of file pi_hip.hpp.
native_type [2/2]
using _pi_program::native_type = CUmodule
Definition at line 525 of file pi_cuda.hpp.
Member Enumeration Documentation
state
enum _pi_program::state
Enumerator
IL
Native
Object
Exe
Invalid
Definition at line 1136 of file pi_level_zero.hpp.
Constructor & Destructor Documentation
_pi_program() [1/7]
_pi_program::_pi_program (pi_context ctxt)
Definition at line 481 of file pi_cuda.cpp.
~_pi_program() [1/3]
_pi_program::~_pi_program ()
Definition at line 487 of file pi_cuda.cpp.
References context_, and cuda_piContextRelease().
_pi_program() [2/7]
_pi_program::_pi_program () inline
Definition at line 214 of file pi_esimd_emulator.hpp.
_pi_program() [3/7]
_pi_program::_pi_program (pi_context ctxt)
~_pi_program() [2/3]
_pi_program::~_pi_program ()
_pi_program() [4/7]
_pi_program::_pi_program (state St, pi_context Context, const void * Input, size_t Length) inline
Definition at line 1187 of file pi_level_zero.hpp.
References USMMemoryAllocBase::Context.
_pi_program() [5/7]
_pi_program::_pi_program (state St, pi_context Context, ze_module_handle_t ZeModule, ze_module_build_log_handle_t ZeBuildLog) inline
Definition at line 1195 of file pi_level_zero.hpp.
References USMMemoryAllocBase::Context.
_pi_program() [6/7]
_pi_program::_pi_program (state St, pi_context Context, ze_module_handle_t ZeModule, bool OwnZeModule) inline
Definition at line 1201 of file pi_level_zero.hpp.
References USMMemoryAllocBase::Context.
_pi_program() [7/7]
_pi_program::_pi_program (state St, pi_context Context, const std::string & ErrorMessage) inline
Definition at line 1207 of file pi_level_zero.hpp.
References USMMemoryAllocBase::Context.
~_pi_program() [3/3]
_pi_program::~_pi_program ()
Member Function Documentation
build_program() [1/2]
pi_result _pi_program::build_program (const char * build_options)
build_program() [2/2]
pi_result _pi_program::build_program (const char * build_options)
Definition at line 537 of file pi_cuda.cpp.
References binary_, buildOptions_, buildStatus_, errorLog_, infoLog_, MAX_LOG_SIZE, module_, PI_BUILD_PROGRAM_FAILURE, PI_PROGRAM_BUILD_STATUS_ERROR, PI_PROGRAM_BUILD_STATUS_SUCCESS, and PI_SUCCESS.
Referenced by cuda_piProgramBuild(), cuda_piProgramCompile(), hip_piProgramBuild(), and hip_piProgramCompile().
decrement_reference_count() [1/2]
pi_uint32 _pi_program::decrement_reference_count () inline noexcept
Definition at line 534 of file pi_hip.hpp.
References refCount_.
decrement_reference_count() [2/2]
pi_uint32 _pi_program::decrement_reference_count () inline noexcept
Definition at line 558 of file pi_cuda.hpp.
References refCount_.
Referenced by cuda_piProgramRelease(), and hip_piProgramRelease().
get() [1/2]
native_type _pi_program::get () const inline noexcept
Definition at line 530 of file pi_hip.hpp.
References module_.
get() [2/2]
native_type _pi_program::get () const inline noexcept
Definition at line 554 of file pi_cuda.hpp.
References module_.
Referenced by cuda_piextGetDeviceFunctionPointer(), cuda_piextProgramGetNativeHandle(), cuda_piKernelCreate(), cuda_piProgramRelease(), hip_piextGetDeviceFunctionPointer(), hip_piextProgramGetNativeHandle(), hip_piKernelCreate(), and hip_piProgramRelease().
get_context() [1/2]
pi_context _pi_program::get_context () const inline
Definition at line 528 of file pi_hip.hpp.
References context_.
get_context() [2/2]
pi_context _pi_program::get_context () const inline
Definition at line 552 of file pi_cuda.hpp.
References context_.
Referenced by cuda_piextGetDeviceFunctionPointer(), cuda_piKernelCreate(), cuda_piProgramBuild(), cuda_piProgramCompile(), cuda_piProgramRelease(), hip_piextGetDeviceFunctionPointer(), hip_piKernelCreate(), hip_piProgramBuild(), hip_piProgramCompile(), and hip_piProgramRelease().
get_reference_count() [1/2]
pi_uint32 _pi_program::get_reference_count () const inline noexcept
Definition at line 536 of file pi_hip.hpp.
References refCount_.
get_reference_count() [2/2]
pi_uint32 _pi_program::get_reference_count () const inline noexcept
Definition at line 560 of file pi_cuda.hpp.
References refCount_.
Referenced by cuda_piProgramGetInfo(), cuda_piProgramRelease(), cuda_piProgramRetain(), hip_piProgramGetInfo(), hip_piProgramRelease(), and hip_piProgramRetain().
increment_reference_count() [1/2]
pi_uint32 _pi_program::increment_reference_count () inline noexcept
Definition at line 532 of file pi_hip.hpp.
References refCount_.
increment_reference_count() [2/2]
pi_uint32 _pi_program::increment_reference_count () inline noexcept
Definition at line 556 of file pi_cuda.hpp.
References refCount_.
Referenced by cuda_piProgramRetain(), and hip_piProgramRetain().
set_binary() [1/2]
pi_result _pi_program::set_binary (const char * binary, size_t binarySizeInBytes)
set_binary() [2/2]
pi_result _pi_program::set_binary (const char * binary, size_t binarySizeInBytes)
Definition at line 529 of file pi_cuda.cpp.
References binary_, binarySizeInBytes_, cl::sycl::length(), and PI_SUCCESS.
set_metadata()
pi_result _pi_program::set_metadata (const pi_device_binary_property * metadata, size_t length)
Definition at line 502 of file pi_cuda.cpp.
References __SYCL_PI_PROGRAM_METADATA_TAG_REQD_WORK_GROUP_SIZE, get_kernel_metadata(), kernelReqdWorkGroupSizeMD_, cl::sycl::length(), cl::sycl::detail::make_tuple(), _pi_device_binary_property_struct::Name, PI_SUCCESS, _pi_device_binary_property_struct::ValAddr, and _pi_device_binary_property_struct::ValSize.
Member Data Documentation
binary_
const char * _pi_program::binary_
Definition at line 527 of file pi_cuda.hpp.
Referenced by build_program(), cuda_piProgramGetInfo(), cuda_piProgramLink(), hip_piProgramGetInfo(), and set_binary().
binarySizeInBytes_
size_t _pi_program::binarySizeInBytes_
Definition at line 528 of file pi_cuda.hpp.
Referenced by cuda_piProgramGetInfo(), cuda_piProgramLink(), hip_piProgramGetInfo(), and set_binary().
BuildFlags
std::string _pi_program::BuildFlags
Definition at line 1238 of file pi_level_zero.hpp.
Referenced by piProgramCompile(), and piProgramLink().
buildOptions_
std::string _pi_program::buildOptions_
Definition at line 539 of file pi_cuda.hpp.
Referenced by build_program(), cuda_piProgramGetBuildInfo(), and hip_piProgramGetBuildInfo().
buildStatus_
pi_program_build_status _pi_program::buildStatus_ = PI_PROGRAM_BUILD_STATUS_NONE
Definition at line 540 of file pi_cuda.hpp.
Referenced by build_program(), cuda_piProgramGetBuildInfo(), and hip_piProgramGetBuildInfo().
Code
std::unique_ptr<uint8_t[]> _pi_program::Code
Definition at line 1227 of file pi_level_zero.hpp.
Referenced by piProgramBuild(), piProgramGetInfo(), and piProgramLink().
CodeLength
size_t _pi_program::CodeLength
Definition at line 1228 of file pi_level_zero.hpp.
Referenced by piProgramBuild(), piProgramGetInfo(), and piProgramLink().
Context [1/2]
pi_context _pi_program::Context
Definition at line 217 of file pi_esimd_emulator.hpp.
Referenced by piextKernelCreateWithNativeHandle(), piKernelCreate(), piKernelGetInfo(), piKernelRelease(), piProgramBuild(), and piProgramGetInfo().
Context [2/2]
const pi_context _pi_program::Context
Definition at line 1213 of file pi_level_zero.hpp.
context_
_pi_context * _pi_program::context_
Definition at line 530 of file pi_cuda.hpp.
Referenced by cuda_piProgramGetInfo(), get_context(), hip_piProgramGetInfo(), and ~_pi_program().
errorLog_
char _pi_program::errorLog_
Definition at line 538 of file pi_cuda.hpp.
Referenced by build_program().
ErrorMessage
const std::string _pi_program::ErrorMessage
Definition at line 1221 of file pi_level_zero.hpp.
Referenced by piProgramGetBuildInfo().
infoLog_
char _pi_program::infoLog_
Definition at line 538 of file pi_cuda.hpp.
Referenced by build_program(), cuda_piProgramGetBuildInfo(), and hip_piProgramGetBuildInfo().
kernelReqdWorkGroupSizeMD_
std::unordered_map<std::string, std::tuple<uint32_t, uint32_t, uint32_t> > _pi_program::kernelReqdWorkGroupSizeMD_
Definition at line 534 of file pi_cuda.hpp.
Referenced by set_metadata().
MAX_LOG_SIZE
constexpr static size_t _pi_program::MAX_LOG_SIZE = 8192u static constexpr
Definition at line 536 of file pi_cuda.hpp.
Referenced by build_program(), cuda_piProgramGetBuildInfo(), and hip_piProgramGetBuildInfo().
module_
native_type _pi_program::module_
Definition at line 526 of file pi_cuda.hpp.
Referenced by build_program(), and get().
OwnZeModule
const bool _pi_program::OwnZeModule
Definition at line 1217 of file pi_level_zero.hpp.
refCount_
std::atomic_uint32_t _pi_program::refCount_
Definition at line 529 of file pi_cuda.hpp.
Referenced by decrement_reference_count(), get_reference_count(), and increment_reference_count().
SpecConstants
std::unordered_map<uint32_t, const void *> _pi_program::SpecConstants
Definition at line 1234 of file pi_level_zero.hpp.
Referenced by piextProgramSetSpecializationConstant(), and _pi_program::SpecConstantShim::SpecConstantShim().
State
state _pi_program::State
Definition at line 1223 of file pi_level_zero.hpp.
Referenced by piextGetDeviceFunctionPointer(), piextProgramGetNativeHandle(), piKernelCreate(), piProgramBuild(), piProgramCompile(), piProgramGetBuildInfo(), and piProgramGetInfo().
ZeBuildLog
ze_module_build_log_handle_t _pi_program::ZeBuildLog
Definition at line 1244 of file pi_level_zero.hpp.
Referenced by piProgramBuild(), and piProgramGetBuildInfo().
ZeModule
ze_module_handle_t _pi_program::ZeModule
Definition at line 1241 of file pi_level_zero.hpp.
Referenced by piextGetDeviceFunctionPointer(), piextProgramGetNativeHandle(), piKernelCreate(), piProgramBuild(), and piProgramGetInfo().
The documentation for this struct was generated from the following files:
plugins/cuda/pi_cuda.hpp
plugins/hip/pi_hip.hpp
plugins/esimd_emulator/pi_esimd_emulator.hpp
plugins/level_zero/pi_level_zero.hpp
plugins/cuda/pi_cuda.cpp
plugins/hip/pi_hip.cpp
plugins/level_zero/pi_level_zero.cpp