DPC++ Runtime: InvokeImpl< NDims > Struct Template Reference
InvokeImpl< NDims > Struct Template Reference
Static Public Member Functions
static sycl::range< NDims > get_range (const size_t *Array)
static void invoke (pi_kernel Kernel, const size_t *GlobalWorkOffset, const size_t *GlobalWorkSize, const size_t *LocalWorkSize)
Detailed Description
template<int NDims>
struct InvokeImpl< NDims >
Definition at line 324 of file pi_esimd_emulator.cpp.
Member Function Documentation
get_range()
template<int NDims> static sycl::range<NDims> InvokeImpl< NDims >::get_range (const size_t * Array) inline static
Definition at line 326 of file pi_esimd_emulator.cpp.
Referenced by InvokeImpl< NDims >::invoke().
invoke()
template<int NDims> static void InvokeImpl< NDims >::invoke (pi_kernel Kernel, const size_t * GlobalWorkOffset, const size_t * GlobalWorkSize, const size_t * LocalWorkSize) inline static
Definition at line 335 of file pi_esimd_emulator.cpp.
References InvokeImpl< NDims >::get_range(), and libCMBatch< DIMS >::runIterationSpace().
Referenced by piEnqueueKernelLaunch().
The documentation for this struct was generated from the following file:
plugins/esimd_emulator/pi_esimd_emulator.cpp