DPC++ Runtime: sycl::_V1::detail::DeviceGlobalUSMMem Struct Reference
sycl::_V1::detail::DeviceGlobalUSMMem Struct Reference
#include <detail/device_global_map_entry.hpp>
Public Member Functions
DeviceGlobalUSMMem (void *Ptr)
~DeviceGlobalUSMMem ()
void *const & getPtr () const noexcept
OwnedPiEvent getInitEvent (const PluginPtr &Plugin)
Friends
struct DeviceGlobalMapEntry
Detailed Description
Definition at line 34 of file device_global_map_entry.hpp.
Constructor & Destructor Documentation
DeviceGlobalUSMMem()
sycl::_V1::detail::DeviceGlobalUSMMem::DeviceGlobalUSMMem (void * Ptr) inline
Definition at line 35 of file device_global_map_entry.hpp.
~DeviceGlobalUSMMem()
sycl::_V1::detail::DeviceGlobalUSMMem::~DeviceGlobalUSMMem ()
Definition at line 20 of file device_global_map_entry.cpp.
Member Function Documentation
getInitEvent()
OwnedPiEvent sycl::_V1::detail::DeviceGlobalUSMMem::getInitEvent (const PluginPtr & Plugin)
Definition at line 28 of file device_global_map_entry.cpp.
References sycl::_V1::info::complete, and piEventRelease().
Referenced by sycl::_V1::detail::context_impl::initializeDeviceGlobals(), sycl::_V1::detail::memcpyFromDeviceGlobalUSM(), and sycl::_V1::detail::memcpyToDeviceGlobalUSM().
getPtr()
void* const& sycl::_V1::detail::DeviceGlobalUSMMem::getPtr () const inline noexcept
Definition at line 38 of file device_global_map_entry.hpp.
Referenced by sycl::_V1::detail::context_impl::initializeDeviceGlobals(), sycl::_V1::detail::memcpyFromDeviceGlobalUSM(), and sycl::_V1::detail::memcpyToDeviceGlobalUSM().
Friends And Related Function Documentation
DeviceGlobalMapEntry
friend struct DeviceGlobalMapEntry friend
Definition at line 49 of file device_global_map_entry.hpp.
The documentation for this struct was generated from the following files:
source/detail/device_global_map_entry.hpp
source/detail/device_global_map_entry.cpp