DPC++ Runtime: cl::sycl::intel::sub_group Struct Reference
cl::sycl::intel::sub_group Struct Reference
#include <CL/sycl/intel/sub_group.hpp>
Public Types
using id_type = id< 1 >
using range_type = range< 1 >
using linear_id_type = uint32_t
template<typename T >
using EnableIfIsScalarArithmetic = sycl::detail::enable_if_t< sycl::detail::is_scalar_arithmetic< T >::value, T >
Public Member Functions
id_type get_local_id () const
linear_id_type get_local_linear_id () const
range_type get_local_range () const
range_type get_max_local_range () const
id_type get_group_id () const
linear_id_type get_group_linear_id () const
range_type get_group_range () const
template<typename T >
T shuffle (T x, id_type local_id) const
template<typename T >
T shuffle_down (T x, uint32_t delta) const
template<typename T >
T shuffle_up (T x, uint32_t delta) const
template<typename T >
T shuffle_xor (T x, id_type value) const
template<typename T >
T shuffle (T x, T y, id_type local_id) const
template<typename T >
T shuffle_down (T current, T next, uint32_t delta) const
template<typename T >
T shuffle_up (T previous, T current, uint32_t delta) const
template<typename T , access::address_space Space>
sycl::detail::enable_if_t< sycl::detail::sub_group::AcceptableForGlobalLoadStore< T, Space >::value, T > load (const multi_ptr< T, Space > src) const
template<typename T , access::address_space Space>
sycl::detail::enable_if_t< sycl::detail::sub_group::AcceptableForLocalLoadStore< T, Space >::value, T > load (const multi_ptr< T, Space > src) const
template<int N, typename T , access::address_space Space>
sycl::detail::enable_if_t< sycl::detail::sub_group::AcceptableForGlobalLoadStore< T, Space >::value &&N !=1, vec< T, N > > load (const multi_ptr< T, Space > src) const
template<int N, typename T , access::address_space Space>
sycl::detail::enable_if_t< sycl::detail::sub_group::AcceptableForLocalLoadStore< T, Space >::value, vec< T, N > > load (const multi_ptr< T, Space > src) const
template<int N, typename T , access::address_space Space>
sycl::detail::enable_if_t< sycl::detail::sub_group::AcceptableForGlobalLoadStore< T, Space >::value &&N==1, vec< T, 1 > > load (const multi_ptr< T, Space > src) const
template<typename T , access::address_space Space>
sycl::detail::enable_if_t< sycl::detail::sub_group::AcceptableForGlobalLoadStore< T, Space >::value > store (multi_ptr< T, Space > dst, const T &x) const
template<typename T , access::address_space Space>
sycl::detail::enable_if_t< sycl::detail::sub_group::AcceptableForLocalLoadStore< T, Space >::value > store (multi_ptr< T, Space > dst, const T &x) const
template<int N, typename T , access::address_space Space>
sycl::detail::enable_if_t< sycl::detail::sub_group::AcceptableForGlobalLoadStore< T, Space >::value &&N==1 > store (multi_ptr< T, Space > dst, const vec< T, 1 > &x) const
template<int N, typename T , access::address_space Space>
sycl::detail::enable_if_t< sycl::detail::sub_group::AcceptableForGlobalLoadStore< T, Space >::value &&N !=1 > store (multi_ptr< T, Space > dst, const vec< T, N > &x) const
template<int N, typename T , access::address_space Space>
sycl::detail::enable_if_t< sycl::detail::sub_group::AcceptableForLocalLoadStore< T, Space >::value > store (multi_ptr< T, Space > dst, const vec< T, N > &x) const
void barrier () const
__SYCL_DEPRECATED("Sub-group barrier accepting fence_space is deprecated." "Use barrier() without a fence_space instead.") void barrier(access sub_group ()=default
Static Public Attributes
static constexpr int dimensions = 1
Detailed Description
Definition at line 123 of file sub_group.hpp.
Member Typedef Documentation
EnableIfIsScalarArithmetic
template<typename T > using cl::sycl::intel::sub_group::EnableIfIsScalarArithmetic = sycl::detail::enable_if_t<sycl::detail::is_scalar_arithmetic<T>::value, T>
Definition at line 198 of file sub_group.hpp.
id_type
using cl::sycl::intel::sub_group::id_type = id<1>
Definition at line 125 of file sub_group.hpp.
linear_id_type
using cl::sycl::intel::sub_group::linear_id_type = uint32_t
Definition at line 127 of file sub_group.hpp.
range_type
using cl::sycl::intel::sub_group::range_type = range<1>
Definition at line 126 of file sub_group.hpp.
Constructor & Destructor Documentation
sub_group()
__SYCL_DEPRECATED ("Sub-group barrier accepting fence_space is deprecated." "Use barrier() without a fence_space instead.") void barrier(access cl::sycl::intel::sub_group::sub_group () default
Member Function Documentation
barrier()
void cl::sycl::intel::sub_group::barrier () const inline
Definition at line 445 of file sub_group.hpp.
References __spirv_ControlBarrier(), __SYCL_DEPRECATED, __spv::MemorySemanticsMask::AcquireRelease, cl::sycl::intel::broadcast(), __spv::MemorySemanticsMask::CrossWorkgroupMemory, cl::sycl::intel::exclusive_scan(), __spv::ExclusiveScan, cl::sycl::detail::getSPIRVMemorySemanticsMask(), cl::sycl::intel::inclusive_scan(), __spv::InclusiveScan, PI_INVALID_DEVICE, __spv::Reduce, cl::sycl::intel::reduce(), __spv::Scope::Subgroup, __spv::MemorySemanticsMask::SubgroupMemory, and __spv::MemorySemanticsMask::WorkgroupMemory.
get_group_id()
id_type cl::sycl::intel::sub_group::get_group_id () const inline
Definition at line 168 of file sub_group.hpp.
References PI_INVALID_DEVICE.
get_group_linear_id()
linear_id_type cl::sycl::intel::sub_group::get_group_linear_id () const inline
Definition at line 177 of file sub_group.hpp.
References PI_INVALID_DEVICE.
get_group_range()
range_type cl::sycl::intel::sub_group::get_group_range () const inline
Definition at line 186 of file sub_group.hpp.
References PI_INVALID_DEVICE.
get_local_id()
id_type cl::sycl::intel::sub_group::get_local_id () const inline
Definition at line 132 of file sub_group.hpp.
References PI_INVALID_DEVICE.
get_local_linear_id()
linear_id_type cl::sycl::intel::sub_group::get_local_linear_id () const inline
Definition at line 141 of file sub_group.hpp.
References PI_INVALID_DEVICE.
get_local_range()
range_type cl::sycl::intel::sub_group::get_local_range () const inline
Definition at line 150 of file sub_group.hpp.
References PI_INVALID_DEVICE.
get_max_local_range()
range_type cl::sycl::intel::sub_group::get_max_local_range () const inline
Definition at line 159 of file sub_group.hpp.
References PI_INVALID_DEVICE.
load() [1/5]
template<typename T , access::address_space Space> sycl::detail::enable_if_t< sycl::detail::sub_group::AcceptableForGlobalLoadStore<T, Space>::value, T> cl::sycl::intel::sub_group::load (const multi_ptr< T, Space > src) const inline
Definition at line 299 of file sub_group.hpp.
References PI_INVALID_DEVICE.
load() [2/5]
template<typename T , access::address_space Space> sycl::detail::enable_if_t< sycl::detail::sub_group::AcceptableForLocalLoadStore<T, Space>::value, T> cl::sycl::intel::sub_group::load (const multi_ptr< T, Space > src) const inline
Definition at line 312 of file sub_group.hpp.
References cl::sycl::multi_ptr< ElementType, Space >::get(), and PI_INVALID_DEVICE.
load() [3/5]
template<int N, typename T , access::address_space Space> sycl::detail::enable_if_t< sycl::detail::sub_group::AcceptableForGlobalLoadStore<T, Space>::value && N != 1, vec<T, N> > cl::sycl::intel::sub_group::load (const multi_ptr< T, Space > src) const inline
Definition at line 327 of file sub_group.hpp.
References PI_INVALID_DEVICE.
load() [4/5]
template<int N, typename T , access::address_space Space> sycl::detail::enable_if_t< sycl::detail::sub_group::AcceptableForLocalLoadStore<T, Space>::value, vec<T, N> > cl::sycl::intel::sub_group::load (const multi_ptr< T, Space > src) const inline
Definition at line 341 of file sub_group.hpp.
References cl::sycl::multi_ptr< ElementType, Space >::get(), and PI_INVALID_DEVICE.
load() [5/5]
template<int N, typename T , access::address_space Space> sycl::detail::enable_if_t< sycl::detail::sub_group::AcceptableForGlobalLoadStore<T, Space>::value && N == 1, vec<T, 1> > cl::sycl::intel::sub_group::load (const multi_ptr< T, Space > src) const inline
Definition at line 360 of file sub_group.hpp.
References PI_INVALID_DEVICE.
shuffle() [1/2]
template<typename T > T cl::sycl::intel::sub_group::shuffle (T x, id_type local_id) const inline
Definition at line 203 of file sub_group.hpp.
References PI_INVALID_DEVICE.
shuffle() [2/2]
template<typename T > T cl::sycl::intel::sub_group::shuffle (T x, T y, id_type local_id) const inline
Definition at line 252 of file sub_group.hpp.
References __SYCL_DEPRECATED, and PI_INVALID_DEVICE.
shuffle_down() [1/2]
template<typename T > T cl::sycl::intel::sub_group::shuffle_down (T x, uint32_t delta) const inline
Definition at line 214 of file sub_group.hpp.
References PI_INVALID_DEVICE.
shuffle_down() [2/2]
template<typename T > T cl::sycl::intel::sub_group::shuffle_down (T current, T next, uint32_t delta) const inline
Definition at line 267 of file sub_group.hpp.
References __SYCL_DEPRECATED, and PI_INVALID_DEVICE.
shuffle_up() [1/2]
template<typename T > T cl::sycl::intel::sub_group::shuffle_up (T x, uint32_t delta) const inline
Definition at line 225 of file sub_group.hpp.
References PI_INVALID_DEVICE.
shuffle_up() [2/2]
template<typename T > T cl::sycl::intel::sub_group::shuffle_up (T previous, T current, uint32_t delta) const inline
Definition at line 281 of file sub_group.hpp.
References PI_INVALID_DEVICE.
shuffle_xor()
template<typename T > T cl::sycl::intel::sub_group::shuffle_xor (T x, id_type value) const inline
Definition at line 236 of file sub_group.hpp.
References __SYCL_DEPRECATED, and PI_INVALID_DEVICE.
store() [1/5]
template<typename T , access::address_space Space> sycl::detail::enable_if_t< sycl::detail::sub_group::AcceptableForGlobalLoadStore<T, Space>::value> cl::sycl::intel::sub_group::store (multi_ptr< T, Space > dst, const T & x) const inline
Definition at line 373 of file sub_group.hpp.
References PI_INVALID_DEVICE.
store() [2/5]
template<typename T , access::address_space Space> sycl::detail::enable_if_t< sycl::detail::sub_group::AcceptableForLocalLoadStore<T, Space>::value> cl::sycl::intel::sub_group::store (multi_ptr< T, Space > dst, const T & x) const inline
Definition at line 387 of file sub_group.hpp.
References cl::sycl::multi_ptr< ElementType, Space >::get(), and PI_INVALID_DEVICE.
store() [3/5]
template<int N, typename T , access::address_space Space> sycl::detail::enable_if_t< sycl::detail::sub_group::AcceptableForGlobalLoadStore<T, Space>::value && N == 1> cl::sycl::intel::sub_group::store (multi_ptr< T, Space > dst, const vec< T, 1 > & x) const inline
Definition at line 402 of file sub_group.hpp.
References PI_INVALID_DEVICE.
store() [4/5]
template<int N, typename T , access::address_space Space> sycl::detail::enable_if_t< sycl::detail::sub_group::AcceptableForGlobalLoadStore<T, Space>::value && N != 1> cl::sycl::intel::sub_group::store (multi_ptr< T, Space > dst, const vec< T, N > & x) const inline
Definition at line 417 of file sub_group.hpp.
References PI_INVALID_DEVICE.
store() [5/5]
template<int N, typename T , access::address_space Space> sycl::detail::enable_if_t< sycl::detail::sub_group::AcceptableForLocalLoadStore<T, Space>::value> cl::sycl::intel::sub_group::store (multi_ptr< T, Space > dst, const vec< T, N > & x) const inline
Definition at line 431 of file sub_group.hpp.
References cl::sycl::multi_ptr< ElementType, Space >::get(), and PI_INVALID_DEVICE.
Member Data Documentation
dimensions
constexpr int cl::sycl::intel::sub_group::dimensions = 1 static
Definition at line 128 of file sub_group.hpp.
The documentation for this struct was generated from the following file:
include/CL/sycl/intel/sub_group.hpp