DPC++ Runtime: sycl::_V1::detail::OwnedPiEvent Struct Reference
sycl::_V1::detail::OwnedPiEvent Struct Reference
#include <detail/pi_utils.hpp>
Public Member Functions
OwnedPiEvent (const PluginPtr &Plugin)
OwnedPiEvent (sycl::detail::pi::PiEvent Event, const PluginPtr &Plugin, bool TakeOwnership=false)
~OwnedPiEvent ()
OwnedPiEvent (OwnedPiEvent &&Other)
OwnedPiEvent (const OwnedPiEvent &Other)=delete
operator bool ()
sycl::detail::pi::PiEvent GetEvent ()
sycl::detail::pi::PiEvent TransferOwnership ()
Detailed Description
Definition at line 22 of file pi_utils.hpp.
Constructor & Destructor Documentation
OwnedPiEvent() [1/4]
sycl::_V1::detail::OwnedPiEvent::OwnedPiEvent (const PluginPtr & Plugin) inline
Definition at line 23 of file pi_utils.hpp.
OwnedPiEvent() [2/4]
sycl::_V1::detail::OwnedPiEvent::OwnedPiEvent (sycl::detail::pi::PiEvent Event, const PluginPtr & Plugin, bool TakeOwnership = false) inline
Definition at line 25 of file pi_utils.hpp.
References piEventRetain().
~OwnedPiEvent()
sycl::_V1::detail::OwnedPiEvent::~OwnedPiEvent () inline
Definition at line 33 of file pi_utils.hpp.
References piEventRelease().
OwnedPiEvent() [3/4]
sycl::_V1::detail::OwnedPiEvent::OwnedPiEvent (OwnedPiEvent && Other) inline
Definition at line 39 of file pi_utils.hpp.
OwnedPiEvent() [4/4]
sycl::_V1::detail::OwnedPiEvent::OwnedPiEvent (const OwnedPiEvent & Other) delete
Member Function Documentation
GetEvent()
sycl::detail::pi::PiEvent sycl::_V1::detail::OwnedPiEvent::GetEvent () inline
Definition at line 50 of file pi_utils.hpp.
Referenced by sycl::_V1::detail::memcpyFromDeviceGlobalUSM(), and sycl::_V1::detail::memcpyToDeviceGlobalUSM().
operator bool()
sycl::_V1::detail::OwnedPiEvent::operator bool () inline
Definition at line 48 of file pi_utils.hpp.
TransferOwnership()
sycl::detail::pi::PiEvent sycl::_V1::detail::OwnedPiEvent::TransferOwnership () inline
Definition at line 54 of file pi_utils.hpp.
The documentation for this struct was generated from the following file:
source/detail/pi_utils.hpp