DPC++ Runtime: sycl::_V1::sub_group Struct Reference
sycl::_V1::sub_group Struct Reference
#include <sycl/sub_group.hpp>
Public Types
using id_type = id< 1 >
using range_type = range< 1 >
using linear_id_type = uint32_t
template<typename T >
using EnableIfIsScalarArithmetic = std::enable_if_t< sycl::detail::is_scalar_arithmetic< T >::value, T >
Public Member Functions
id_type get_local_id () const
linear_id_type get_local_linear_id () const
range_type get_local_range () const
range_type get_max_local_range () const
id_type get_group_id () const
linear_id_type get_group_linear_id () const
range_type get_group_range () const
template<typename T >
T shuffle (T x, id_type local_id) const
template<typename T >
T shuffle_down (T x, uint32_t delta) const
template<typename T >
T shuffle_up (T x, uint32_t delta) const
template<typename T >
T shuffle_xor (T x, id_type value) const
template<typename CVT , typename T = std::remove_cv_t<CVT>>
T load (CVT *src) const
template<typename CVT , access::address_space Space, access::decorated IsDecorated, typename T = std::remove_cv_t<CVT>>
std::enable_if_t< sycl::detail::sub_group::AcceptableForGlobalLoadStore< T, Space >::value, T > load (const multi_ptr< CVT, Space, IsDecorated > cv_src) const
template<typename CVT , access::address_space Space, access::decorated IsDecorated, typename T = std::remove_cv_t<CVT>>
std::enable_if_t< sycl::detail::sub_group::AcceptableForLocalLoadStore< T, Space >::value, T > load (const multi_ptr< CVT, Space, IsDecorated > cv_src) const
template<int N, typename CVT , access::address_space Space, access::decorated IsDecorated, typename T = std::remove_cv_t<CVT>>
std::enable_if_t< sycl::detail::sub_group::AcceptableForGlobalLoadStore< T, Space >::value, vec< T, N > > load (const multi_ptr< CVT, Space, IsDecorated > src) const
template<int N, typename CVT , access::address_space Space, access::decorated IsDecorated, typename T = std::remove_cv_t<CVT>>
std::enable_if_t< sycl::detail::sub_group::AcceptableForLocalLoadStore< T, Space >::value, vec< T, N > > load (const multi_ptr< CVT, Space, IsDecorated > cv_src) const
template<typename T >
void store (T *dst, const T &x) const
template<typename T , access::address_space Space, access::decorated DecorateAddress>
std::enable_if_t< sycl::detail::sub_group::AcceptableForGlobalLoadStore< T, Space >::value > store (multi_ptr< T, Space, DecorateAddress > dst, const T &x) const
template<typename T , access::address_space Space, access::decorated DecorateAddress>
std::enable_if_t< sycl::detail::sub_group::AcceptableForLocalLoadStore< T, Space >::value > store (multi_ptr< T, Space, DecorateAddress > dst, const T &x) const
template<int N, typename T , access::address_space Space, access::decorated DecorateAddress>
std::enable_if_t< sycl::detail::sub_group::AcceptableForGlobalLoadStore< T, Space >::value > store (multi_ptr< T, Space, DecorateAddress > dst, const vec< T, N > &x) const
template<int N, typename T , access::address_space Space, access::decorated DecorateAddress>
std::enable_if_t< sycl::detail::sub_group::AcceptableForLocalLoadStore< T, Space >::value > store (multi_ptr< T, Space, DecorateAddress > dst, const vec< T, N > &x) const
__SYCL_DEPRECATED ("Sub-group barrier with no arguments is deprecated." "Use sycl::group_barrier with the sub-group as the argument instead.") void barrier() const
__SYCL_DEPRECATED ("Sub-group barrier accepting fence_space is deprecated." "Use sycl::group_barrier with the sub-group as the argument instead.") void barrier(access
Static Public Attributes
static constexpr int dimensions = 1
static constexpr sycl::memory_scope fence_scope
Protected Member Functions
sub_group ()=default
Friends
template<int dimensions>
class sycl::nd_item
bool operator!= (const sub_group &lhs, const sub_group &rhs)
sub_group ext::oneapi::this_work_item::get_sub_group ()
Detailed Description
Definition at line 139 of file sub_group.hpp.
Member Typedef Documentation
EnableIfIsScalarArithmetic
template<typename T > using sycl::_V1::sub_group::EnableIfIsScalarArithmetic = std::enable_if_t<sycl::detail::is_scalar_arithmetic<T>::value, T>
Definition at line 214 of file sub_group.hpp.
id_type
using sycl::_V1::sub_group::id_type = id<1>
Definition at line 141 of file sub_group.hpp.
linear_id_type
using sycl::_V1::sub_group::linear_id_type = uint32_t
Definition at line 143 of file sub_group.hpp.
range_type
using sycl::_V1::sub_group::range_type = range<1>
Definition at line 142 of file sub_group.hpp.
Constructor & Destructor Documentation
sub_group()
sycl::_V1::sub_group::sub_group () protected default
Member Function Documentation
__SYCL_DEPRECATED() [1/2]
sycl::_V1::sub_group::__SYCL_DEPRECATED ("Sub-group barrier accepting fence_space is deprecated." "Use sycl::group_barrier with the sub-group as the argument instead.") inline
Definition at line 632 of file sub_group.hpp.
References __spirv_ControlBarrier(), sycl::_V1::feature_not_supported, sycl::_V1::detail::getSPIRVMemorySemanticsMask(), sycl::_V1::make_error_code(), and __spv::Scope::Subgroup.
__SYCL_DEPRECATED() [2/2]
sycl::_V1::sub_group::__SYCL_DEPRECATED ("Sub-group barrier with no arguments is deprecated." "Use sycl::group_barrier with the sub-group as the argument instead.") const inline
Definition at line 615 of file sub_group.hpp.
References __spirv_ControlBarrier(), __spv::MemorySemanticsMask::AcquireRelease, __spv::MemorySemanticsMask::CrossWorkgroupMemory, sycl::_V1::feature_not_supported, sycl::_V1::make_error_code(), __spv::Scope::Subgroup, __spv::MemorySemanticsMask::SubgroupMemory, and __spv::MemorySemanticsMask::WorkgroupMemory.
get_group_id()
id_type sycl::_V1::sub_group::get_group_id () const inline
Definition at line 186 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, and sycl::_V1::make_error_code().
Referenced by get_group_linear_id().
get_group_linear_id()
linear_id_type sycl::_V1::sub_group::get_group_linear_id () const inline
Definition at line 195 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, get_group_id(), and sycl::_V1::make_error_code().
get_group_range()
range_type sycl::_V1::sub_group::get_group_range () const inline
Definition at line 204 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, and sycl::_V1::make_error_code().
get_local_id()
id_type sycl::_V1::sub_group::get_local_id () const inline
Definition at line 150 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, and sycl::_V1::make_error_code().
Referenced by get_local_linear_id(), load(), and store().
get_local_linear_id()
linear_id_type sycl::_V1::sub_group::get_local_linear_id () const inline
Definition at line 159 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, get_local_id(), and sycl::_V1::make_error_code().
Referenced by syclcompat::match_all_over_sub_group(), syclcompat::match_any_over_sub_group(), syclcompat::permute_sub_group_by_xor(), syclcompat::experimental::permute_sub_group_by_xor(), syclcompat::select_from_sub_group(), syclcompat::experimental::select_from_sub_group(), syclcompat::shift_sub_group_left(), syclcompat::experimental::shift_sub_group_left(), syclcompat::shift_sub_group_right(), and syclcompat::experimental::shift_sub_group_right().
get_local_range()
range_type sycl::_V1::sub_group::get_local_range () const inline
Definition at line 168 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, and sycl::_V1::make_error_code().
get_max_local_range()
range_type sycl::_V1::sub_group::get_max_local_range () const inline
Definition at line 177 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, and sycl::_V1::make_error_code().
Referenced by load(), and store().
load() [1/5]
template<typename CVT , access::address_space Space, access::decorated IsDecorated, typename T = std::remove_cv_t<CVT>> std::enable_if_t< sycl::detail::sub_group::AcceptableForGlobalLoadStore<T, Space>::value, T> sycl::_V1::sub_group::load (const multi_ptr< CVT, Space, IsDecorated > cv_src) const inline
Definition at line 318 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, get_local_id(), sycl::_V1::detail::GetUnqualMultiPtr(), and sycl::_V1::make_error_code().
load() [2/5]
template<typename CVT , access::address_space Space, access::decorated IsDecorated, typename T = std::remove_cv_t<CVT>> std::enable_if_t< sycl::detail::sub_group::AcceptableForLocalLoadStore<T, Space>::value, T> sycl::_V1::sub_group::load (const multi_ptr< CVT, Space, IsDecorated > cv_src) const inline
Definition at line 338 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, get_local_id(), sycl::_V1::detail::GetUnqualMultiPtr(), and sycl::_V1::make_error_code().
load() [3/5]
template<int N, typename CVT , access::address_space Space, access::decorated IsDecorated, typename T = std::remove_cv_t<CVT>> std::enable_if_t< sycl::detail::sub_group::AcceptableForLocalLoadStore<T, Space>::value, vec<T, N> > sycl::_V1::sub_group::load (const multi_ptr< CVT, Space, IsDecorated > cv_src) const inline
Definition at line 436 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, get_local_id(), get_max_local_range(), sycl::_V1::detail::GetUnqualMultiPtr(), and sycl::_V1::make_error_code().
load() [4/5]
template<int N, typename CVT , access::address_space Space, access::decorated IsDecorated, typename T = std::remove_cv_t<CVT>> std::enable_if_t< sycl::detail::sub_group::AcceptableForGlobalLoadStore<T, Space>::value, vec<T, N> > sycl::_V1::sub_group::load (const multi_ptr< CVT, Space, IsDecorated > src) const inline
Definition at line 424 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, and sycl::_V1::make_error_code().
load() [5/5]
template<typename CVT , typename T = std::remove_cv_t<CVT>> T sycl::_V1::sub_group::load (CVT * src) const inline
Definition at line 307 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, and sycl::_V1::make_error_code().
shuffle()
template<typename T > T sycl::_V1::sub_group::shuffle (T x, id_type local_id) const inline
Definition at line 221 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, sycl::_V1::make_error_code(), and sycl::_V1::x.
shuffle_down()
template<typename T > T sycl::_V1::sub_group::shuffle_down (T x, uint32_t delta) const inline
Definition at line 234 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, sycl::_V1::make_error_code(), and sycl::_V1::x.
shuffle_up()
template<typename T > T sycl::_V1::sub_group::shuffle_up (T x, uint32_t delta) const inline
Definition at line 247 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, sycl::_V1::make_error_code(), and sycl::_V1::x.
shuffle_xor()
template<typename T > T sycl::_V1::sub_group::shuffle_xor (T x, id_type value) const inline
Definition at line 260 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, sycl::_V1::make_error_code(), and sycl::_V1::x.
store() [1/5]
template<typename T , access::address_space Space, access::decorated DecorateAddress> std::enable_if_t< sycl::detail::sub_group::AcceptableForGlobalLoadStore<T, Space>::value> sycl::_V1::sub_group::store (multi_ptr< T, Space, DecorateAddress > dst, const T & x) const inline
Definition at line 501 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, get_local_id(), sycl::_V1::make_error_code(), and sycl::_V1::x.
store() [2/5]
template<typename T , access::address_space Space, access::decorated DecorateAddress> std::enable_if_t< sycl::detail::sub_group::AcceptableForLocalLoadStore<T, Space>::value> sycl::_V1::sub_group::store (multi_ptr< T, Space, DecorateAddress > dst, const T & x) const inline
Definition at line 520 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, get_local_id(), sycl::_V1::make_error_code(), and sycl::_V1::x.
store() [3/5]
template<int N, typename T , access::address_space Space, access::decorated DecorateAddress> std::enable_if_t< sycl::detail::sub_group::AcceptableForGlobalLoadStore<T, Space>::value> sycl::_V1::sub_group::store (multi_ptr< T, Space, DecorateAddress > dst, const vec< T, N > & x) const inline
Definition at line 589 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, sycl::_V1::make_error_code(), and sycl::_V1::x.
store() [4/5]
template<int N, typename T , access::address_space Space, access::decorated DecorateAddress> std::enable_if_t< sycl::detail::sub_group::AcceptableForLocalLoadStore<T, Space>::value> sycl::_V1::sub_group::store (multi_ptr< T, Space, DecorateAddress > dst, const vec< T, N > & x) const inline
Definition at line 601 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, get_local_id(), get_max_local_range(), sycl::_V1::make_error_code(), and sycl::_V1::x.
store() [5/5]
template<typename T > void sycl::_V1::sub_group::store (T * dst, const T & x) const inline
Definition at line 489 of file sub_group.hpp.
References sycl::_V1::feature_not_supported, sycl::_V1::make_error_code(), and sycl::_V1::x.
Friends And Related Function Documentation
ext::oneapi::this_work_item::get_sub_group
sub_group ext::oneapi::this_work_item::get_sub_group () friend
operator!=
bool operator!= (const sub_group & lhs, const sub_group & rhs) friend
Definition at line 805 of file sub_group.hpp.
sycl::nd_item
template<int dimensions> friend class sycl::nd_item friend
Definition at line 817 of file sub_group.hpp.
Member Data Documentation
dimensions
constexpr int sycl::_V1::sub_group::dimensions = 1 static constexpr
Definition at line 144 of file sub_group.hpp.
fence_scope
constexpr sycl::memory_scope sycl::_V1::sub_group::fence_scope static constexpr
Initial value:
=
      sycl::memory_scope::sub_group
Definition at line 145 of file sub_group.hpp.
The documentation for this struct was generated from the following file:
include/sycl/sub_group.hpp