DPC++ Runtime: _pi_mem Struct Reference
_pi_mem Struct Reference abstract
PI Mem mapping to CUDA memory allocations, both data and texture/surface.
#include <cuda/pi_cuda.hpp>
Classes
struct Mapping
union mem_
A PI Memory object represents either plain memory allocations ("Buffers" in OpenCL) or typed allocations ("Images" in OpenCL).
Public Types
enum mem_type { mem_type::buffer, mem_type::surface, mem_type::buffer, mem_type::surface }
enum mem_type { mem_type::buffer, mem_type::surface, mem_type::buffer, mem_type::surface }
using pi_context = _pi_context *
using pi_context = _pi_context *
Public Member Functions
_pi_mem (pi_context ctxt, pi_mem parent, mem_::buffer_mem_::alloc_mode mode, CUdeviceptr ptr, void *host_ptr, size_t size)
Constructs the PI MEM handler for a non-typed allocation ("buffer")
_pi_mem (pi_context ctxt, CUarray array, CUsurfObject surf, pi_mem_type image_type, void *host_ptr)
Constructs the PI allocation for an Image object (surface in CUDA)
~_pi_mem ()
bool is_buffer () const noexcept
bool is_sub_buffer () const noexcept
bool is_image () const noexcept
pi_context get_context () const noexcept
pi_uint32 increment_reference_count () noexcept
pi_uint32 decrement_reference_count () noexcept
pi_uint32 get_reference_count () const noexcept
_pi_mem ()=default
_pi_mem_type getMemType () const
_pi_mem (pi_context ctxt, pi_mem parent, mem_::buffer_mem_::alloc_mode mode, hipDeviceptr_t ptr, void *host_ptr, size_t size)
Constructs the PI MEM handler for a non-typed allocation ("buffer")
_pi_mem (pi_context ctxt, hipArray *array, hipSurfaceObject_t surf, pi_mem_type image_type, void *host_ptr)
Constructs the PI allocation for an Image object.
~_pi_mem ()
bool is_buffer () const noexcept
bool is_sub_buffer () const noexcept
bool is_image () const noexcept
pi_context get_context () const noexcept
pi_uint32 increment_reference_count () noexcept
pi_uint32 decrement_reference_count () noexcept
pi_uint32 get_reference_count () const noexcept
virtual void * getZeHandle ()=0
virtual void * getZeHandlePtr ()=0
virtual bool isImage () const =0
virtual ~_pi_mem ()=default
Public Attributes
pi_context context_
std::atomic_uint32_t refCount_
Reference counting of the handler.
enum _pi_mem::mem_type mem_type_
union _pi_mem::mem_ mem_
pi_context Context
char * MapHostPtr = nullptr
std::mutex SurfaceLock
unsigned int SurfaceIndex
std::unordered_map< void *, Mapping > Mappings
std::mutex MappingsMutex
const bool OnHost
bool HostPtrImported
Protected Member Functions
_pi_mem (pi_context ctxt, char *HostPtr, _pi_mem_type MemTypeArg, unsigned int SurfaceIdxArg)
_pi_mem (pi_context Ctx, char *HostPtr, bool MemOnHost=false, bool ImportedHostPtr=false)
Detailed Description
PI Mem mapping to CUDA memory allocations, both data and texture/surface.
PI Mem mapping to HIP memory allocations, both data and texture/surface.
Represents non-SVM allocations on the CUDA backend. Keeps tracks of all mapped regions used for Map/Unmap calls. Only one region can be active at the same time per allocation.
Represents non-SVM allocations on the HIP backend. Keeps tracks of all mapped regions used for Map/Unmap calls. Only one region can be active at the same time per allocation.
Definition at line 209 of file pi_cuda.hpp.
Member Typedef Documentation
pi_context [1/2]
using _pi_mem::pi_context = _pi_context *
Definition at line 187 of file pi_hip.hpp.
pi_context [2/2]
using _pi_mem::pi_context = _pi_context *
Definition at line 212 of file pi_cuda.hpp.
Member Enumeration Documentation
mem_type [1/2]
enum _pi_mem::mem_type strong
Enumerator
buffer
surface
buffer
surface
Definition at line 194 of file pi_hip.hpp.
mem_type [2/2]
enum _pi_mem::mem_type strong
Enumerator
buffer
surface
buffer
surface
Definition at line 219 of file pi_cuda.hpp.
Constructor & Destructor Documentation
_pi_mem() [1/7]
_pi_mem::_pi_mem (pi_context ctxt, pi_mem parent, mem_::buffer_mem_::alloc_mode mode, CUdeviceptr ptr, void * host_ptr, size_t size) inline
Constructs the PI MEM handler for a non-typed allocation ("buffer")
Definition at line 319 of file pi_cuda.hpp.
_pi_mem() [2/7]
_pi_mem::_pi_mem (pi_context ctxt, CUarray array, CUsurfObject surf, pi_mem_type image_type, void * host_ptr) inline
Constructs the PI allocation for an Image object (surface in CUDA)
Definition at line 338 of file pi_cuda.hpp.
~_pi_mem() [1/3]
_pi_mem::~_pi_mem () inline
Definition at line 350 of file pi_cuda.hpp.
References buffer, _pi_mem::mem_::buffer_mem_, context_, cuda_piContextRelease(), cuda_piMemRelease(), is_sub_buffer(), mem_type_, and _pi_mem::mem_::buffer_mem_::parent_.
_pi_mem() [3/7]
_pi_mem::_pi_mem () default
_pi_mem() [4/7]
_pi_mem::_pi_mem (pi_context ctxt, char * HostPtr, _pi_mem_type MemTypeArg, unsigned int SurfaceIdxArg) inline protected
Definition at line 141 of file pi_esimd_emulator.hpp.
_pi_mem() [5/7]
_pi_mem::_pi_mem (pi_context ctxt, pi_mem parent, mem_::buffer_mem_::alloc_mode mode, hipDeviceptr_t ptr, void * host_ptr, size_t size) inline
Constructs the PI MEM handler for a non-typed allocation ("buffer")
Definition at line 305 of file pi_hip.hpp.
_pi_mem() [6/7]
_pi_mem::_pi_mem (pi_context ctxt, hipArray * array, hipSurfaceObject_t surf, pi_mem_type image_type, void * host_ptr) inline
Constructs the PI allocation for an Image object.
Definition at line 324 of file pi_hip.hpp.
~_pi_mem() [2/3]
_pi_mem::~_pi_mem () inline
Definition at line 334 of file pi_hip.hpp.
References buffer, _pi_mem::mem_::buffer_mem_, context_, hip_piContextRelease(), hip_piMemRelease(), is_sub_buffer(), mem_type_, and _pi_mem::mem_::buffer_mem_::parent_.
~_pi_mem() [3/3]
virtual _pi_mem::~_pi_mem () virtual default
_pi_mem() [7/7]
_pi_mem::_pi_mem (pi_context Ctx, char * HostPtr, bool MemOnHost = false, bool ImportedHostPtr = false) inline protected
Definition at line 959 of file pi_level_zero.hpp.
Member Function Documentation
decrement_reference_count() [1/2]
pi_uint32 _pi_mem::decrement_reference_count () inline noexcept
Definition at line 357 of file pi_hip.hpp.
References refCount_.
decrement_reference_count() [2/2]
pi_uint32 _pi_mem::decrement_reference_count () inline noexcept
Definition at line 373 of file pi_cuda.hpp.
References refCount_.
Referenced by cuda_piMemRelease(), and hip_piMemRelease().
get_context() [1/2]
pi_context _pi_mem::get_context () const inline noexcept
Definition at line 353 of file pi_hip.hpp.
References context_.
get_context() [2/2]
pi_context _pi_mem::get_context () const inline noexcept
Definition at line 369 of file pi_cuda.hpp.
References context_.
get_reference_count() [1/2]
pi_uint32 _pi_mem::get_reference_count () const inline noexcept
Definition at line 359 of file pi_hip.hpp.
References refCount_.
get_reference_count() [2/2]
pi_uint32 _pi_mem::get_reference_count () const inline noexcept
Definition at line 375 of file pi_cuda.hpp.
References refCount_.
Referenced by cuda_piMemRetain(), and hip_piMemRetain().
getMemType()
_pi_mem_type _pi_mem::getMemType () const inline
Definition at line 138 of file pi_esimd_emulator.hpp.
Referenced by piMemRelease().
getZeHandle()
virtual void* _pi_mem::getZeHandle () pure virtual
Implemented in _pi_image, and _pi_buffer.
Referenced by enqueueMemImageCommandHelper(), piEnqueueMemBufferCopy(), piEnqueueMemBufferCopyRect(), piEnqueueMemBufferFill(), piEnqueueMemBufferMap(), piEnqueueMemBufferRead(), piEnqueueMemBufferReadRect(), piEnqueueMemBufferWrite(), piEnqueueMemBufferWriteRect(), piEnqueueMemUnmap(), piextMemGetNativeHandle(), piMemBufferPartition(), and piMemRelease().
getZeHandlePtr()
virtual void* _pi_mem::getZeHandlePtr () pure virtual
Implemented in _pi_image, and _pi_buffer.
increment_reference_count() [1/2]
pi_uint32 _pi_mem::increment_reference_count () inline noexcept
Definition at line 355 of file pi_hip.hpp.
References refCount_.
increment_reference_count() [2/2]
pi_uint32 _pi_mem::increment_reference_count () inline noexcept
Definition at line 371 of file pi_cuda.hpp.
References refCount_.
Referenced by cuda_piMemRetain(), and hip_piMemRetain().
is_buffer() [1/2]
bool _pi_mem::is_buffer () const inline noexcept
Definition at line 345 of file pi_hip.hpp.
References buffer, and mem_type_.
is_buffer() [2/2]
bool _pi_mem::is_buffer () const inline noexcept
Definition at line 361 of file pi_cuda.hpp.
References buffer, and mem_type_.
Referenced by cuda_piMemBufferPartition(), hip_piMemBufferPartition(), and is_sub_buffer().
is_image() [1/2]
bool _pi_mem::is_image () const inline noexcept
Definition at line 351 of file pi_hip.hpp.
References mem_type_, and surface.
is_image() [2/2]
bool _pi_mem::is_image () const inline noexcept
Definition at line 367 of file pi_cuda.hpp.
References mem_type_, and surface.
is_sub_buffer() [1/2]
bool _pi_mem::is_sub_buffer () const inline noexcept
Definition at line 347 of file pi_hip.hpp.
References _pi_mem::mem_::buffer_mem_, is_buffer(), and _pi_mem::mem_::buffer_mem_::parent_.
is_sub_buffer() [2/2]
bool _pi_mem::is_sub_buffer () const inline noexcept
Definition at line 363 of file pi_cuda.hpp.
References _pi_mem::mem_::buffer_mem_, is_buffer(), and _pi_mem::mem_::buffer_mem_::parent_.
Referenced by cuda_piMemBufferPartition(), cuda_piMemRelease(), hip_piMemBufferPartition(), hip_piMemRelease(), and ~_pi_mem().
isImage()
virtual bool _pi_mem::isImage () const pure virtual
Implemented in _pi_image, and _pi_buffer.
Referenced by enqueueMemImageCommandHelper(), getImageRegionHelper(), piMemBufferPartition(), and piMemRelease().
Member Data Documentation
Context
pi_context _pi_mem::Context
Definition at line 111 of file pi_esimd_emulator.hpp.
Referenced by piMemBufferPartition(), piMemRelease(), and piTearDown().
context_
pi_context _pi_mem::context_
Definition at line 215 of file pi_cuda.hpp.
Referenced by cuda_piMemBufferPartition(), get_context(), hip_piMemBufferPartition(), and ~_pi_mem().
HostPtrImported
bool _pi_mem::HostPtrImported
Definition at line 930 of file pi_level_zero.hpp.
Referenced by piEnqueueMemBufferMap(), and piMemRelease().
MapHostPtr
char * _pi_mem::MapHostPtr = nullptr
Definition at line 114 of file pi_esimd_emulator.hpp.
Referenced by piEnqueueMemBufferMap(), piEnqueueMemBufferRead(), piEnqueueMemImageRead(), piEnqueueMemUnmap(), piMemRelease(), sycl_get_cm_buffer_params(), and sycl_get_cm_image_params().
Mappings
std::unordered_map< void *, Mapping > _pi_mem::Mappings
Definition at line 134 of file pi_esimd_emulator.hpp.
Referenced by piEnqueueMemBufferMap(), piEnqueueMemUnmap(), and piMemRelease().
MappingsMutex
std::mutex _pi_mem::MappingsMutex
Definition at line 136 of file pi_esimd_emulator.hpp.
Referenced by piEnqueueMemBufferMap(), piEnqueueMemUnmap(), and piMemRelease().
mem_
union _pi_mem::mem_ _pi_mem::mem_
Referenced by cuda_piEnqueueMemBufferCopy(), cuda_piEnqueueMemBufferCopyRect(), cuda_piEnqueueMemBufferFill(), cuda_piEnqueueMemBufferMap(), cuda_piEnqueueMemBufferRead(), cuda_piEnqueueMemBufferReadRect(), cuda_piEnqueueMemBufferWrite(), cuda_piEnqueueMemBufferWriteRect(), cuda_piEnqueueMemImageCopy(), cuda_piEnqueueMemUnmap(), cuda_piextKernelSetArgMemObj(), cuda_piextMemGetNativeHandle(), cuda_piMemBufferPartition(), hip_piEnqueueMemBufferCopy(), hip_piEnqueueMemBufferCopyRect(), hip_piEnqueueMemBufferFill(), hip_piEnqueueMemBufferMap(), hip_piEnqueueMemBufferRead(), hip_piEnqueueMemBufferReadRect(), hip_piEnqueueMemBufferWrite(), hip_piEnqueueMemBufferWriteRect(), hip_piEnqueueMemImageCopy(), hip_piEnqueueMemUnmap(), hip_piextKernelSetArgMemObj(), and hip_piMemBufferPartition().
mem_type_
enum _pi_mem::mem_type _pi_mem::mem_type_
Referenced by cuda_piEnqueueMemBufferMap(), cuda_piEnqueueMemImageCopy(), cuda_piEnqueueMemUnmap(), cuda_piextKernelSetArgMemObj(), cuda_piMemRelease(), hip_piEnqueueMemBufferMap(), hip_piEnqueueMemImageCopy(), hip_piEnqueueMemUnmap(), hip_piextKernelSetArgMemObj(), hip_piMemRelease(), is_buffer(), is_image(), and ~_pi_mem().
OnHost
const bool _pi_mem::OnHost
Definition at line 927 of file pi_level_zero.hpp.
Referenced by piEnqueueMemBufferCopy(), piEnqueueMemBufferCopyRect(), piEnqueueMemBufferMap(), piEnqueueMemImageCopy(), and piEnqueueMemUnmap().
refCount_
std::atomic_uint32_t _pi_mem::refCount_
Reference counting of the handler.
Definition at line 218 of file pi_cuda.hpp.
Referenced by decrement_reference_count(), get_reference_count(), and increment_reference_count().
SurfaceIndex
unsigned int _pi_mem::SurfaceIndex
Definition at line 120 of file pi_esimd_emulator.hpp.
Referenced by piMemRelease(), and sycl_get_cm_surface_index().
SurfaceLock
std::mutex _pi_mem::SurfaceLock
Definition at line 116 of file pi_esimd_emulator.hpp.
Referenced by sycl_get_cm_buffer_params(), and sycl_get_cm_image_params().
The documentation for this struct was generated from the following files:
plugins/cuda/pi_cuda.hpp
plugins/hip/pi_hip.hpp
plugins/esimd_emulator/pi_esimd_emulator.hpp
plugins/level_zero/pi_level_zero.hpp