DPC++ Runtime: _pi_kernel Struct Reference
_pi_kernel Struct Reference
Implementation of a PI Kernel for CUDA.
#include <cuda/pi_cuda.hpp>
Classes
struct arguments
Structure that holds the arguments to the kernel.
Public Types
using native_type = CUfunction
Public Member Functions
_pi_kernel (CUfunction func, CUfunction funcWithOffsetParam, const char *name, pi_program program, pi_context ctxt)
_pi_kernel (CUfunction func, const char *name, pi_program program, pi_context ctxt)
~_pi_kernel ()
pi_program get_program () const noexcept
pi_uint32 increment_reference_count () noexcept
pi_uint32 decrement_reference_count () noexcept
pi_uint32 get_reference_count () const noexcept
native_type get () const noexcept
native_type get_with_offset_parameter () const noexcept
bool has_with_offset_parameter () const noexcept
pi_context get_context () const noexcept
const char * get_name () const noexcept
pi_uint32 get_num_args () const noexcept
Returns the number of arguments, excluding the implicit global offset.
void set_kernel_arg (int index, size_t size, const void *arg)
void set_kernel_local_arg (int index, size_t size)
void set_implicit_offset_arg (size_t size, std::uint32_t *implicitOffset)
arguments::args_index_t get_arg_indices () const
pi_uint32 get_local_size () const noexcept
void clear_local_size ()
_pi_kernel (ze_kernel_handle_t Kernel, pi_program Program, const char *KernelName)
Public Member Functions inherited from _pi_object
_pi_object ()
Public Attributes
native_type function_
native_type functionWithOffsetParam_
std::string name_
pi_context context_
pi_program program_
std::atomic_uint32_t refCount_
struct _pi_kernel::arguments args_
ze_kernel_handle_t ZeKernel
pi_program Program
std::string KernelName
Public Attributes inherited from _pi_object
std::atomic< pi_uint32 > RefCount
Detailed Description
Implementation of a PI Kernel for CUDA.
PI Kernels are used to set kernel arguments, creating a state on the Kernel object for a given invocation. This is not the case of CUFunction objects, which are simply passed together with the arguments on the invocation. The PI Kernel implementation for CUDA stores the list of arguments, argument sizes and offsets to emulate the interface of PI Kernel, saving the arguments for the later dispatch. Note that in PI API, the Local memory is specified as a size per individual argument, but in CUDA only the total usage of shared memory is required since it is not passed as a parameter. A compiler pass converts the PI API local memory model into the CUDA shared model. This object simply calculates the total of shared memory, and the initial offsets of each parameter.
Definition at line 542 of file pi_cuda.hpp.
Member Typedef Documentation
native_type
using _pi_kernel::native_type = CUfunction
Definition at line 543 of file pi_cuda.hpp.
Constructor & Destructor Documentation
_pi_kernel() [1/3]
_pi_kernel::_pi_kernel (CUfunction func, CUfunction funcWithOffsetParam, const char * name, pi_program program, pi_context ctxt) inline
Definition at line 622 of file pi_cuda.hpp.
References cuda_piContextRetain(), and cuda_piProgramRetain().
_pi_kernel() [2/3]
_pi_kernel::_pi_kernel (CUfunction func, const char * name, pi_program program, pi_context ctxt) inline
Definition at line 630 of file pi_cuda.hpp.
~_pi_kernel()
_pi_kernel::~_pi_kernel () inline
Definition at line 634 of file pi_cuda.hpp.
References cuda_piContextRelease(), and cuda_piProgramRelease().
_pi_kernel() [3/3]
_pi_kernel::_pi_kernel (ze_kernel_handle_t Kernel, pi_program Program, const char * KernelName) inline
Definition at line 617 of file pi_level_zero.hpp.
Member Function Documentation
clear_local_size()
void _pi_kernel::clear_local_size () inline
Definition at line 686 of file pi_cuda.hpp.
Referenced by cuda_piEnqueueKernelLaunch().
decrement_reference_count()
pi_uint32 _pi_kernel::decrement_reference_count () inline noexcept
Definition at line 644 of file pi_cuda.hpp.
Referenced by cuda_piKernelRelease().
get()
native_type _pi_kernel::get () const inline noexcept
Definition at line 648 of file pi_cuda.hpp.
Referenced by cuda_piEnqueueKernelLaunch(), and cuda_piKernelGetGroupInfo().
get_arg_indices()
arguments::args_index_t _pi_kernel::get_arg_indices () const inline
Definition at line 680 of file pi_cuda.hpp.
Referenced by cuda_piEnqueueKernelLaunch().
get_context()
pi_context _pi_kernel::get_context () const inline noexcept
Definition at line 658 of file pi_cuda.hpp.
Referenced by cuda_piEnqueueKernelLaunch(), and cuda_piKernelGetInfo().
get_local_size()
pi_uint32 _pi_kernel::get_local_size () const inline noexcept
Definition at line 684 of file pi_cuda.hpp.
Referenced by cuda_piEnqueueKernelLaunch().
get_name()
const char* _pi_kernel::get_name () const inline noexcept
Definition at line 660 of file pi_cuda.hpp.
Referenced by cuda_piKernelGetInfo().
get_num_args()
pi_uint32 _pi_kernel::get_num_args () const inline noexcept
Returns the number of arguments, excluding the implicit global offset.
Note this only returns the current known number of arguments, not the real one required by the kernel, since this cannot be queried from the CUDA Driver API
Definition at line 666 of file pi_cuda.hpp.
Referenced by cuda_piKernelGetInfo().
get_program()
pi_program _pi_kernel::get_program () const inline noexcept
Definition at line 640 of file pi_cuda.hpp.
Referenced by cuda_piKernelGetInfo().
get_reference_count()
pi_uint32 _pi_kernel::get_reference_count () const inline noexcept
Definition at line 646 of file pi_cuda.hpp.
Referenced by cuda_piKernelGetInfo(), cuda_piKernelRelease(), and cuda_piKernelRetain().
get_with_offset_parameter()
native_type _pi_kernel::get_with_offset_parameter () const inline noexcept
Definition at line 650 of file pi_cuda.hpp.
Referenced by cuda_piEnqueueKernelLaunch().
has_with_offset_parameter()
bool _pi_kernel::has_with_offset_parameter () const inline noexcept
Definition at line 654 of file pi_cuda.hpp.
increment_reference_count()
pi_uint32 _pi_kernel::increment_reference_count () inline noexcept
Definition at line 642 of file pi_cuda.hpp.
Referenced by cuda_piKernelRetain().
set_implicit_offset_arg()
void _pi_kernel::set_implicit_offset_arg (size_t size, std::uint32_t * implicitOffset) inline
Definition at line 676 of file pi_cuda.hpp.
Referenced by cuda_piEnqueueKernelLaunch().
set_kernel_arg()
void _pi_kernel::set_kernel_arg (int index, size_t size, const void * arg) inline
Definition at line 668 of file pi_cuda.hpp.
Referenced by cuda_piextKernelSetArgMemObj(), cuda_piextKernelSetArgPointer(), cuda_piextKernelSetArgSampler(), and cuda_piKernelSetArg().
set_kernel_local_arg()
void _pi_kernel::set_kernel_local_arg (int index, size_t size) inline
Definition at line 672 of file pi_cuda.hpp.
Referenced by cuda_piKernelSetArg().
Member Data Documentation
args_
struct _pi_kernel::arguments _pi_kernel::args_
context_
pi_context _pi_kernel::context_
Definition at line 548 of file pi_cuda.hpp.
function_
native_type _pi_kernel::function_
Definition at line 545 of file pi_cuda.hpp.
functionWithOffsetParam_
native_type _pi_kernel::functionWithOffsetParam_
Definition at line 546 of file pi_cuda.hpp.
KernelName
std::string _pi_kernel::KernelName
Definition at line 628 of file pi_level_zero.hpp.
Referenced by piKernelGetInfo().
name_
std::string _pi_kernel::name_
Definition at line 547 of file pi_cuda.hpp.
Program
pi_program _pi_kernel::Program
Definition at line 625 of file pi_level_zero.hpp.
Referenced by piEnqueueKernelLaunch(), and piKernelGetInfo().
program_
pi_program _pi_kernel::program_
Definition at line 549 of file pi_cuda.hpp.
refCount_
std::atomic_uint32_t _pi_kernel::refCount_
Definition at line 550 of file pi_cuda.hpp.
ZeKernel
ze_kernel_handle_t _pi_kernel::ZeKernel
Definition at line 622 of file pi_level_zero.hpp.
Referenced by piEnqueueKernelLaunch(), piextKernelSetArgMemObj(), piextKernelSetArgSampler(), piKernelGetGroupInfo(), piKernelGetInfo(), piKernelGetSubGroupInfo(), piKernelRelease(), piKernelSetArg(), and piKernelSetExecInfo().
The documentation for this struct was generated from the following files:
plugins/cuda/pi_cuda.hpp
plugins/level_zero/pi_level_zero.hpp