DPC++ Runtime: _pi_queue Struct Reference
_pi_queue Struct Reference
PI queue mapping on to CUstream objects.
#include <cuda/pi_cuda.hpp>
Classes
struct CommandBatch
struct pi_queue_group_t
Public Types
using native_type = CUstream
using native_type = hipStream_t
using queue_type = _pi_device::queue_group_info_t::type
typedef struct _pi_queue::CommandBatch command_batch
Public Member Functions
_pi_queue (CUstream stream, _pi_context *context, _pi_device *device, pi_queue_properties properties)
~_pi_queue ()
native_type get () const noexcept
_pi_context * get_context () const
pi_uint32 increment_reference_count () noexcept
pi_uint32 decrement_reference_count () noexcept
pi_uint32 get_reference_count () const noexcept
pi_uint32 get_next_event_id () noexcept
_pi_queue (pi_context ContextArg, cm_support::CmQueue *CmQueueArg)
_pi_queue (hipStream_t stream, _pi_context *context, _pi_device *device, pi_queue_properties properties)
~_pi_queue ()
native_type get () const noexcept
_pi_context * get_context () const
pi_uint32 increment_reference_count () noexcept
pi_uint32 decrement_reference_count () noexcept
pi_uint32 get_reference_count () const noexcept
pi_uint32 get_next_event_id () noexcept
_pi_queue (std::vector< ze_command_queue_handle_t > &ComputeQueues, std::vector< ze_command_queue_handle_t > &CopyQueues, pi_context Context, pi_device Device, bool OwnZeCommandQueue, pi_queue_properties Properties=0)
pi_queue_group_t & getQueueGroup (bool UseCopyEngine)
bool useCopyEngine (bool PreferCopyEngine=true) const
bool isBatchingAllowed (bool IsCopy) const
bool isInOrderQueue () const
void adjustBatchSizeForFullBatch (bool IsCopy)
void adjustBatchSizeForPartialBatch (bool IsCopy)
pi_result resetCommandList (pi_command_list_ptr_t CommandList, bool MakeAvailable)
bool hasOpenCommandList (bool IsCopy) const
pi_result executeCommandList (pi_command_list_ptr_t CommandList, bool IsBlocking=false, bool OKToBatchCommand=false)
pi_result executeOpenCommandList (bool IsCopy)
pi_result executeOpenCommandListWithEvent (pi_event Event)
pi_result executeAllOpenCommandLists ()
Public Attributes
native_type stream_
_pi_context * context_
_pi_device * device_
pi_queue_properties properties_
std::atomic_uint32_t refCount_
std::atomic_uint32_t eventCount_
pi_context Context = nullptr
cm_support::CmQueue * CmQueuePtr = nullptr
pi_queue_group_t ComputeQueueGroup {this, queue_type::Compute}
pi_queue_group_t CopyQueueGroup {this, queue_type::MainCopy}
const pi_context Context
const pi_device Device
pi_event LastCommandEvent = nullptr
std::vector< pi_kernel > KernelsToBeSubmitted
bool OwnZeCommandQueue
pi_command_list_map_t CommandListMap
command_batch ComputeCommandBatch
command_batch CopyCommandBatch
pi_queue_properties Properties
std::atomic< pi_uint32 > RefCountExternal {1}
bool Healthy {true}
Detailed Description
PI queue mapping on to CUstream objects.
PI queue mapping on to hipStream_t objects.
Definition at line 380 of file pi_cuda.hpp.
Member Typedef Documentation
command_batch
typedef struct _pi_queue::CommandBatch _pi_queue::command_batch
native_type [1/2]
using _pi_queue::native_type = hipStream_t
Definition at line 365 of file pi_hip.hpp.
native_type [2/2]
using _pi_queue::native_type = CUstream
Definition at line 381 of file pi_cuda.hpp.
queue_type
using _pi_queue::queue_type = _pi_device::queue_group_info_t::type
Definition at line 729 of file pi_level_zero.hpp.
Constructor & Destructor Documentation
_pi_queue() [1/4]
_pi_queue::_pi_queue (CUstream stream, _pi_context * context, _pi_device * device, pi_queue_properties properties) inline
Definition at line 390 of file pi_cuda.hpp.
Referenced by piextQueueCreateWithNativeHandle(), and piQueueCreate().
~_pi_queue() [1/2]
_pi_queue::~_pi_queue () inline
Definition at line 398 of file pi_cuda.hpp.
References context_, cuda_piContextRelease(), cuda_piDeviceRelease(), and device_.
_pi_queue() [2/4]
_pi_queue::_pi_queue (pi_context ContextArg, cm_support::CmQueue * CmQueueArg) inline
Definition at line 100 of file pi_esimd_emulator.hpp.
_pi_queue() [3/4]
_pi_queue::_pi_queue (hipStream_t stream, _pi_context * context, _pi_device * device, pi_queue_properties properties) inline
Definition at line 374 of file pi_hip.hpp.
~_pi_queue() [2/2]
_pi_queue::~_pi_queue () inline
Definition at line 382 of file pi_hip.hpp.
References context_, device_, hip_piContextRelease(), and hip_piDeviceRelease().
_pi_queue() [4/4]
_pi_queue::_pi_queue (std::vector< ze_command_queue_handle_t > & ComputeQueues, std::vector< ze_command_queue_handle_t > & CopyQueues, pi_context Context, pi_device Device, bool OwnZeCommandQueue, pi_queue_properties Properties = 0)
Definition at line 1022 of file pi_level_zero.cpp.
References Context.
Member Function Documentation
adjustBatchSizeForFullBatch()
void _pi_queue::adjustBatchSizeForFullBatch (bool IsCopy)
Definition at line 1212 of file pi_level_zero.cpp.
References ComputeCommandBatch, CopyCommandBatch, CommandListBatchConfig::dynamic(), CommandListBatchConfig::DynamicSizeMax, CommandListBatchConfig::DynamicSizeStep, _pi_queue::CommandBatch::NumTimesClosedEarly, CommandListBatchConfig::NumTimesClosedEarlyThreshold, _pi_queue::CommandBatch::NumTimesClosedFull, CommandListBatchConfig::NumTimesClosedFullThreshold, _pi_queue::CommandBatch::QueueBatchSize, ZeCommandListBatchComputeConfig, ZeCommandListBatchConfig(), and ZeCommandListBatchCopyConfig.
Referenced by executeCommandList().
adjustBatchSizeForPartialBatch()
void _pi_queue::adjustBatchSizeForPartialBatch (bool IsCopy)
Definition at line 1239 of file pi_level_zero.cpp.
References ComputeCommandBatch, CopyCommandBatch, CommandListBatchConfig::dynamic(), _pi_queue::CommandBatch::NumTimesClosedEarly, _pi_queue::CommandBatch::NumTimesClosedFull, _pi_queue::CommandBatch::OpenCommandList, _pi_queue::CommandBatch::QueueBatchSize, ZeCommandListBatchComputeConfig, ZeCommandListBatchConfig(), and ZeCommandListBatchCopyConfig.
Referenced by executeOpenCommandList().
decrement_reference_count() [1/2]
pi_uint32 _pi_queue::decrement_reference_count () inline noexcept
Definition at line 393 of file pi_hip.hpp.
References refCount_.
decrement_reference_count() [2/2]
pi_uint32 _pi_queue::decrement_reference_count () inline noexcept
Definition at line 409 of file pi_cuda.hpp.
References refCount_.
Referenced by cuda_piQueueRelease(), and hip_piQueueRelease().
executeAllOpenCommandLists()
pi_result _pi_queue::executeAllOpenCommandLists () inline
Definition at line 897 of file pi_level_zero.hpp.
References PI_SUCCESS.
Referenced by _pi_ze_event_list_t::createAndRetainPiZeEventList(), piQueueFinish(), and piQueueRelease().
executeCommandList()
pi_result _pi_queue::executeCommandList (pi_command_list_ptr_t CommandList, bool IsBlocking = false, bool OKToBatchCommand = false)
Definition at line 1265 of file pi_level_zero.cpp.
References adjustBatchSizeForFullBatch(), _pi_event::CleanedUp, CommandListMap, ComputeCommandBatch, _pi_platform::Contexts, _pi_platform::ContextsMutex, CopyCommandBatch, createEventAndAssociateQueue(), Device, cl::sycl::detail::pi::die(), CommandListBatchConfig::dynamic(), hasOpenCommandList(), Healthy, isBatchingAllowed(), KernelsToBeSubmitted, LastCommandEvent, _pi_queue::CommandBatch::OpenCommandList, PI_CALL, PI_COMMAND_EXECUTION_FAILURE, PI_COMMAND_TYPE_USER, PI_SUCCESS, piEventRelease(), piEventRetain(), _pi_device::Platform, PrintPiTrace, _pi_queue::CommandBatch::QueueBatchSize, ZE_CALL, ZE_CALL_NOCHECK, ZeCommandListBatchComputeConfig, ZeCommandListBatchConfig(), ZeCommandListBatchCopyConfig, and _pi_event::ZeEvent.
Referenced by enqueueMemCopyHelper(), enqueueMemCopyRectHelper(), enqueueMemFillHelper(), enqueueMemImageCommandHelper(), executeOpenCommandList(), piEnqueueEventsWait(), piEnqueueEventsWaitWithBarrier(), piEnqueueKernelLaunch(), piEnqueueMemBufferMap(), piEnqueueMemUnmap(), piextUSMEnqueueMemAdvise(), and piextUSMEnqueuePrefetch().
executeOpenCommandList()
pi_result _pi_queue::executeOpenCommandList (bool IsCopy)
Definition at line 1506 of file pi_level_zero.cpp.
References adjustBatchSizeForPartialBatch(), CommandListMap, ComputeCommandBatch, CopyCommandBatch, executeCommandList(), hasOpenCommandList(), _pi_queue::CommandBatch::OpenCommandList, and PI_SUCCESS.
Referenced by executeOpenCommandListWithEvent(), and _pi_context::getAvailableCommandList().
executeOpenCommandListWithEvent()
pi_result _pi_queue::executeOpenCommandListWithEvent (pi_event Event)
Definition at line 1489 of file pi_level_zero.cpp.
References ComputeCommandBatch, CopyCommandBatch, executeOpenCommandList(), hasOpenCommandList(), _pi_queue::CommandBatch::OpenCommandList, PI_SUCCESS, and _pi_event::ZeCommandList.
Referenced by piEventGetInfo(), and piextEventGetNativeHandle().
get() [1/2]
native_type _pi_queue::get () const inline noexcept
Definition at line 387 of file pi_hip.hpp.
References stream_.
get() [2/2]
native_type _pi_queue::get () const inline noexcept
Definition at line 403 of file pi_cuda.hpp.
References stream_.
Referenced by cuda_piEnqueueKernelLaunch(), cuda_piEnqueueMemBufferCopy(), cuda_piEnqueueMemBufferCopyRect(), cuda_piEnqueueMemBufferFill(), cuda_piEnqueueMemBufferRead(), cuda_piEnqueueMemBufferReadRect(), cuda_piEnqueueMemBufferWrite(), cuda_piEnqueueMemBufferWriteRect(), cuda_piEnqueueMemImageCopy(), cuda_piEnqueueMemImageRead(), cuda_piEnqueueMemImageWrite(), hip_piEnqueueKernelLaunch(), hip_piEnqueueMemBufferCopy(), hip_piEnqueueMemBufferCopyRect(), hip_piEnqueueMemBufferFill(), hip_piEnqueueMemBufferRead(), hip_piEnqueueMemBufferReadRect(), hip_piEnqueueMemBufferWrite(), hip_piEnqueueMemBufferWriteRect(), hip_piEnqueueMemImageCopy(), hip_piEnqueueMemImageRead(), and hip_piEnqueueMemImageWrite().
get_context() [1/2]
_pi_context* _pi_queue::get_context () const inline
Definition at line 389 of file pi_hip.hpp.
References context_.
get_context() [2/2]
_pi_context* _pi_queue::get_context () const inline
Definition at line 405 of file pi_cuda.hpp.
References context_.
Referenced by cuda_piEnqueueEventsWaitWithBarrier(), cuda_piEnqueueKernelLaunch(), cuda_piEnqueueMemBufferCopy(), cuda_piEnqueueMemBufferCopyRect(), cuda_piEnqueueMemBufferFill(), cuda_piEnqueueMemBufferMap(), cuda_piEnqueueMemBufferRead(), cuda_piEnqueueMemBufferReadRect(), cuda_piEnqueueMemBufferWrite(), cuda_piEnqueueMemBufferWriteRect(), cuda_piEnqueueMemImageCopy(), cuda_piEnqueueMemImageRead(), cuda_piEnqueueMemImageWrite(), cuda_piEnqueueMemUnmap(), cuda_piQueueFinish(), cuda_piQueueRelease(), hip_piEnqueueEventsWaitWithBarrier(), hip_piEnqueueKernelLaunch(), hip_piEnqueueMemBufferCopy(), hip_piEnqueueMemBufferCopyRect(), hip_piEnqueueMemBufferFill(), hip_piEnqueueMemBufferMap(), hip_piEnqueueMemBufferRead(), hip_piEnqueueMemBufferReadRect(), hip_piEnqueueMemBufferWrite(), hip_piEnqueueMemBufferWriteRect(), hip_piEnqueueMemImageCopy(), hip_piEnqueueMemImageRead(), hip_piEnqueueMemImageWrite(), hip_piEnqueueMemUnmap(), hip_piQueueFinish(), and hip_piQueueRelease().
get_next_event_id() [1/2]
pi_uint32 _pi_queue::get_next_event_id () inline noexcept
Definition at line 397 of file pi_hip.hpp.
References eventCount_.
get_next_event_id() [2/2]
pi_uint32 _pi_queue::get_next_event_id () inline noexcept
Definition at line 413 of file pi_cuda.hpp.
References eventCount_.
get_reference_count() [1/2]
pi_uint32 _pi_queue::get_reference_count () const inline noexcept
Definition at line 395 of file pi_hip.hpp.
References refCount_.
get_reference_count() [2/2]
pi_uint32 _pi_queue::get_reference_count () const inline noexcept
Definition at line 411 of file pi_cuda.hpp.
References refCount_.
Referenced by cuda_piQueueGetInfo(), cuda_piQueueRetain(), hip_piQueueGetInfo(), and hip_piQueueRetain().
getQueueGroup()
pi_queue_group_t& _pi_queue::getQueueGroup (bool UseCopyEngine) inline
Definition at line 768 of file pi_level_zero.hpp.
Referenced by _pi_context::getAvailableCommandList().
hasOpenCommandList()
bool _pi_queue::hasOpenCommandList (bool IsCopy) const inline
Definition at line 868 of file pi_level_zero.hpp.
References _pi_queue::CommandBatch::OpenCommandList.
Referenced by executeCommandList(), executeOpenCommandList(), executeOpenCommandListWithEvent(), and _pi_context::getAvailableCommandList().
increment_reference_count() [1/2]
pi_uint32 _pi_queue::increment_reference_count () inline noexcept
Definition at line 391 of file pi_hip.hpp.
References refCount_.
increment_reference_count() [2/2]
pi_uint32 _pi_queue::increment_reference_count () inline noexcept
Definition at line 407 of file pi_cuda.hpp.
References refCount_.
Referenced by cuda_piQueueRetain(), and hip_piQueueRetain().
isBatchingAllowed()
bool _pi_queue::isBatchingAllowed (bool IsCopy) const
Definition at line 1425 of file pi_level_zero.cpp.
References ComputeCommandBatch, CopyCommandBatch, and _pi_queue::CommandBatch::QueueBatchSize.
Referenced by executeCommandList().
isInOrderQueue()
bool _pi_queue::isInOrderQueue () const
Definition at line 832 of file pi_level_zero.cpp.
References PI_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE, and Properties.
Referenced by _pi_ze_event_list_t::createAndRetainPiZeEventList(), piEnqueueMemBufferMap(), piEnqueueMemUnmap(), and useCopyEngine().
resetCommandList()
pi_result _pi_queue::resetCommandList (pi_command_list_ptr_t CommandList, bool MakeAvailable)
Definition at line 837 of file pi_level_zero.cpp.
References Context, Device, EventRelease(), PI_CALL, PI_SUCCESS, ZE_CALL, _pi_context::ZeCommandListCacheMutex, _pi_context::ZeComputeCommandListCache, _pi_context::ZeCopyCommandListCache, and _pi_device::ZeDevice.
Referenced by _pi_context::getAvailableCommandList(), and piQueueRelease().
useCopyEngine()
bool _pi_queue::useCopyEngine (bool PreferCopyEngine = true) const
Definition at line 5768 of file pi_level_zero.cpp.
References CopyQueueGroup, isInOrderQueue(), and _pi_queue::pi_queue_group_t::ZeQueues.
Referenced by enqueueMemCopyHelper(), enqueueMemCopyRectHelper(), enqueueMemFillHelper(), and enqueueMemImageCommandHelper().
Member Data Documentation
CmQueuePtr
cm_support::CmQueue* _pi_queue::CmQueuePtr = nullptr
Definition at line 105 of file pi_esimd_emulator.hpp.
Referenced by piQueueRelease().
CommandListMap
pi_command_list_map_t _pi_queue::CommandListMap
Definition at line 806 of file pi_level_zero.hpp.
Referenced by createEventAndAssociateQueue(), executeCommandList(), executeOpenCommandList(), _pi_context::getAvailableCommandList(), piEnqueueEventsWait(), piEnqueueMemBufferMap(), piEnqueueMemUnmap(), and piQueueRelease().
ComputeCommandBatch
command_batch _pi_queue::ComputeCommandBatch
Definition at line 831 of file pi_level_zero.hpp.
Referenced by adjustBatchSizeForFullBatch(), adjustBatchSizeForPartialBatch(), executeCommandList(), executeOpenCommandList(), executeOpenCommandListWithEvent(), _pi_context::getAvailableCommandList(), isBatchingAllowed(), and QueueRelease().
ComputeQueueGroup
pi_queue_group_t _pi_queue::ComputeQueueGroup {this, queue_type::Compute}
Definition at line 761 of file pi_level_zero.hpp.
Referenced by piEnqueueEventsWait(), piextQueueGetNativeHandle(), piQueueFinish(), piQueueRelease(), and QueueRelease().
Context [1/2]
pi_context _pi_queue::Context = nullptr
Definition at line 104 of file pi_esimd_emulator.hpp.
Referenced by _pi_queue(), USMSharedMemoryAlloc::allocateImpl(), USMSharedReadOnlyMemoryAlloc::allocateImpl(), USMDeviceMemoryAlloc::allocateImpl(), USMHostMemoryAlloc::allocateImpl(), ContextReleaseHelper(), createEventAndAssociateQueue(), USMMemoryAllocBase::deallocate(), enqueueMemCopyHelper(), enqueueMemCopyRectHelper(), enqueueMemFillHelper(), enqueueMemImageCommandHelper(), EventCreate(), EventRelease(), _pi_context::getAvailableCommandList(), _pi_queue::pi_queue_group_t::getZeQueue(), IsDevicePointer(), piclProgramCreateWithSource(), piContextGetInfo(), piContextRelease(), piContextRetain(), piEnqueueEventsWait(), piEnqueueEventsWaitWithBarrier(), piEnqueueKernelLaunch(), piEnqueueMemBufferMap(), piEnqueueMemUnmap(), piEventCreate(), piextContextGetNativeHandle(), piextContextSetExtendedDeleter(), piextEventCreateWithNativeHandle(), piextKernelCreateWithNativeHandle(), piextProgramCreateWithNativeHandle(), piextQueueCreateWithNativeHandle(), piextUSMDeviceAlloc(), piextUSMEnqueueMemAdvise(), piextUSMEnqueueMemcpy(), piextUSMEnqueuePrefetch(), piextUSMFree(), piextUSMGetMemAllocInfo(), piextUSMHostAlloc(), piextUSMSharedAlloc(), piMemBufferCreate(), piMemImageCreate(), piProgramCreate(), piProgramCreateWithBinary(), piProgramLink(), piQueueCreate(), piQueueGetInfo(), piSamplerCreate(), resetCommandList(), USMDeviceAllocImpl(), USMFreeHelper(), USMFreeImpl(), USMHostAllocImpl(), USMSharedAllocImpl(), ZeDeviceMemAllocHelper(), ZeHostMemAllocHelper(), and ZeMemFreeHelper().
Context [2/2]
const pi_context _pi_queue::Context
Definition at line 780 of file pi_level_zero.hpp.
context_
_pi_context * _pi_queue::context_
Definition at line 384 of file pi_cuda.hpp.
Referenced by cuda_piQueueGetInfo(), get_context(), hip_piQueueGetInfo(), and ~_pi_queue().
CopyCommandBatch
command_batch _pi_queue::CopyCommandBatch
Definition at line 831 of file pi_level_zero.hpp.
Referenced by adjustBatchSizeForFullBatch(), adjustBatchSizeForPartialBatch(), executeCommandList(), executeOpenCommandList(), executeOpenCommandListWithEvent(), _pi_context::getAvailableCommandList(), isBatchingAllowed(), and QueueRelease().
CopyQueueGroup
pi_queue_group_t _pi_queue::CopyQueueGroup {this, queue_type::MainCopy}
Definition at line 766 of file pi_level_zero.hpp.
Referenced by piEnqueueEventsWait(), piQueueFinish(), piQueueRelease(), QueueRelease(), and useCopyEngine().
Device
const pi_device _pi_queue::Device
Definition at line 785 of file pi_level_zero.hpp.
Referenced by USMSharedMemoryAlloc::allocateImpl(), USMSharedReadOnlyMemoryAlloc::allocateImpl(), USMDeviceMemoryAlloc::allocateImpl(), enqueueMemFillHelper(), executeCommandList(), _pi_context::getAvailableCommandList(), _pi_queue::pi_queue_group_t::getZeQueue(), pi_command_list_info_t::isCopy(), piDeviceGetInfo(), piDevicePartition(), piDeviceRelease(), piDeviceRetain(), piEventGetProfilingInfo(), piextDeviceCreateWithNativeHandle(), piextDeviceGetNativeHandle(), piextDeviceSelectBinary(), piextGetDeviceFunctionPointer(), piextQueueCreateWithNativeHandle(), piextUSMDeviceAlloc(), piextUSMEnqueueMemAdvise(), piextUSMGetMemAllocInfo(), piextUSMSharedAlloc(), piKernelGetGroupInfo(), piKernelGetSubGroupInfo(), piMemImageCreate(), piProgramGetBuildInfo(), piQueueCreate(), piQueueGetInfo(), piSamplerCreate(), resetCommandList(), USMDeviceAllocImpl(), USMFreeHelper(), USMSharedAllocImpl(), and ZeDeviceMemAllocHelper().
device_
_pi_device * _pi_queue::device_
Definition at line 385 of file pi_cuda.hpp.
Referenced by cuda_piEnqueueKernelLaunch(), cuda_piQueueGetInfo(), hip_piEnqueueKernelLaunch(), hip_piQueueGetInfo(), and ~_pi_queue().
eventCount_
std::atomic_uint32_t _pi_queue::eventCount_
Definition at line 388 of file pi_cuda.hpp.
Referenced by get_next_event_id().
Healthy
bool _pi_queue::Healthy {true}
Definition at line 914 of file pi_level_zero.hpp.
Referenced by executeCommandList(), and piQueueRelease().
KernelsToBeSubmitted
std::vector<pi_kernel> _pi_queue::KernelsToBeSubmitted
Definition at line 799 of file pi_level_zero.hpp.
Referenced by executeCommandList(), and piEnqueueKernelLaunch().
LastCommandEvent
pi_event _pi_queue::LastCommandEvent = nullptr
Definition at line 791 of file pi_level_zero.hpp.
Referenced by _pi_ze_event_list_t::createAndRetainPiZeEventList(), executeCommandList(), piEnqueueEventsWait(), piEnqueueMemBufferMap(), piEnqueueMemUnmap(), and piQueueFinish().
OwnZeCommandQueue
bool _pi_queue::OwnZeCommandQueue
Definition at line 803 of file pi_level_zero.hpp.
Referenced by QueueRelease().
Properties
pi_queue_properties _pi_queue::Properties
Definition at line 840 of file pi_level_zero.hpp.
Referenced by EventCreate(), isInOrderQueue(), piContextCreate(), piDevicePartition(), piEventGetProfilingInfo(), piextKernelCreateWithNativeHandle(), piextUSMDeviceAlloc(), piextUSMHostAlloc(), piextUSMSharedAlloc(), piKernelCreate(), piQueueCreate(), USMDeviceAllocImpl(), USMHostAllocImpl(), and USMSharedAllocImpl().
properties_
pi_queue_properties _pi_queue::properties_
Definition at line 386 of file pi_cuda.hpp.
Referenced by cuda_piQueueGetInfo(), and hip_piQueueGetInfo().
refCount_
std::atomic_uint32_t _pi_queue::refCount_
Definition at line 387 of file pi_cuda.hpp.
Referenced by decrement_reference_count(), get_reference_count(), and increment_reference_count().
RefCountExternal
std::atomic<pi_uint32> _pi_queue::RefCountExternal {1}
Definition at line 911 of file pi_level_zero.hpp.
Referenced by piQueueRelease(), and piQueueRetain().
stream_
native_type _pi_queue::stream_
Definition at line 383 of file pi_cuda.hpp.
Referenced by cuda_piQueueFinish(), get(), and hip_piQueueFinish().
The documentation for this struct was generated from the following files:
plugins/cuda/pi_cuda.hpp
plugins/hip/pi_hip.hpp
plugins/level_zero/pi_level_zero.hpp
plugins/esimd_emulator/pi_esimd_emulator.hpp
plugins/level_zero/pi_level_zero.cpp