DPC++ Runtime: _pi_event Struct Reference
_pi_event Struct Reference
PI Event mapping to CUevent.
#include <cuda/pi_cuda.hpp>
Public Types
using native_type = CUevent
using native_type = hipEvent_t
Public Member Functions
pi_result record ()
pi_result wait ()
pi_result start ()
native_type get () const noexcept
pi_queue get_queue () const noexcept
pi_command_type get_command_type () const noexcept
pi_uint32 get_reference_count () const noexcept
bool is_recorded () const noexcept
bool is_started () const noexcept
bool is_completed () const noexcept
pi_int32 get_execution_status () const noexcept
pi_context get_context () const noexcept
pi_uint32 increment_reference_count ()
pi_uint32 decrement_reference_count ()
pi_uint32 get_event_id () const noexcept
pi_uint64 get_queued_time () const
pi_uint64 get_start_time () const
pi_uint64 get_end_time () const
pi_result release ()
~_pi_event ()
_pi_event ()
pi_result record ()
pi_result wait ()
pi_result start ()
native_type get () const noexcept
pi_queue get_queue () const noexcept
pi_command_type get_command_type () const noexcept
pi_uint32 get_reference_count () const noexcept
bool is_recorded () const noexcept
bool is_started () const noexcept
bool is_completed () const noexcept
pi_int32 get_execution_status () const noexcept
pi_context get_context () const noexcept
pi_uint32 increment_reference_count ()
pi_uint32 decrement_reference_count ()
pi_uint32 get_event_id () const noexcept
pi_uint64 get_queued_time () const
pi_uint64 get_start_time () const
pi_uint64 get_end_time () const
pi_result release ()
~_pi_event ()
_pi_event (ze_event_handle_t ZeEvent, ze_event_pool_handle_t ZeEventPool, pi_context Context, pi_command_type CommandType, bool OwnZeEvent)
bool isHostVisible () const
pi_result getOrCreateHostVisibleEvent (ze_event_handle_t &HostVisibleEvent)
bool isProfilingEnabled () const
pi_result cleanup (pi_queue LockedQueue=nullptr)
Static Public Member Functions
static pi_event make_native (pi_command_type type, pi_queue queue)
static pi_event make_native (pi_command_type type, pi_queue queue)
Public Attributes
cm_support::CmEvent * CmEventPtr = nullptr
cm_support::CmQueue * OwnerQueue = nullptr
pi_context Context = nullptr
bool IsDummyEvent = false
ze_event_handle_t ZeEvent
bool OwnZeEvent
ze_event_pool_handle_t ZeEventPool
pi_event HostVisibleEvent = {nullptr}
ze_command_list_handle_t ZeCommandList
pi_queue Queue = {nullptr}
pi_command_type CommandType
void * CommandData
_pi_ze_event_list_t WaitList
bool CleanedUp = {false}
bool Completed = {false}
Detailed Description
PI Event mapping to CUevent.
PI Event mapping to hipEvent_t.
Definition at line 420 of file pi_cuda.hpp.
Member Typedef Documentation
native_type [1/2]
using _pi_event::native_type = hipEvent_t
Definition at line 406 of file pi_hip.hpp.
native_type [2/2]
using _pi_event::native_type = CUevent
Definition at line 422 of file pi_cuda.hpp.
Constructor & Destructor Documentation
~_pi_event() [1/2]
_pi_event::~_pi_event ()
Definition at line 347 of file pi_cuda.cpp.
References cuda_piContextRelease(), and cuda_piQueueRelease().
_pi_event() [1/2]
_pi_event::_pi_event () inline
Definition at line 205 of file pi_esimd_emulator.hpp.
Referenced by make_native().
~_pi_event() [2/2]
_pi_event::~_pi_event ()
_pi_event() [2/2]
_pi_event::_pi_event (ze_event_handle_t ZeEvent, ze_event_pool_handle_t ZeEventPool, pi_context Context, pi_command_type CommandType, bool OwnZeEvent) inline
Definition at line 1058 of file pi_level_zero.hpp.
Member Function Documentation
cleanup()
pi_result _pi_event::cleanup (pi_queue LockedQueue = nullptr)
Definition at line 5178 of file pi_level_zero.cpp.
References _pi_ze_event_list_t::collectEventsForReleaseAndDestroyPiZeEventList(), CommandData, CommandType, cl::sycl::detail::pi::die(), EventRelease(), PI_CALL, PI_COMMAND_TYPE_MEM_BUFFER_COPY, PI_COMMAND_TYPE_NDRANGE_KERNEL, PI_SUCCESS, piKernelRelease(), Queue, WaitList, and ZE_CALL_NOCHECK.
Referenced by EventRelease(), and piEventsWait().
decrement_reference_count() [1/2]
pi_uint32 _pi_event::decrement_reference_count () inline
Definition at line 444 of file pi_hip.hpp.
decrement_reference_count() [2/2]
pi_uint32 _pi_event::decrement_reference_count () inline
Definition at line 460 of file pi_cuda.hpp.
get() [1/2]
native_type _pi_event::get () const inline noexcept
Definition at line 414 of file pi_hip.hpp.
get() [2/2]
native_type _pi_event::get () const inline noexcept
Definition at line 430 of file pi_cuda.hpp.
Referenced by cl::sycl::detail::Command::waitForEvents().
get_command_type() [1/2]
pi_command_type _pi_event::get_command_type () const inline noexcept
Definition at line 418 of file pi_hip.hpp.
get_command_type() [2/2]
pi_command_type _pi_event::get_command_type () const inline noexcept
Definition at line 434 of file pi_cuda.hpp.
get_context() [1/2]
pi_context _pi_event::get_context () const inline noexcept
Definition at line 440 of file pi_hip.hpp.
get_context() [2/2]
pi_context _pi_event::get_context () const inline noexcept
Definition at line 456 of file pi_cuda.hpp.
Referenced by cuda_piEventsWait(), and hip_piEventsWait().
get_end_time() [1/2]
pi_uint64 _pi_event::get_end_time () const
get_end_time() [2/2]
pi_uint64 _pi_event::get_end_time () const
Definition at line 406 of file pi_cuda.cpp.
get_event_id() [1/2]
pi_uint32 _pi_event::get_event_id () const inline noexcept
Definition at line 446 of file pi_hip.hpp.
get_event_id() [2/2]
pi_uint32 _pi_event::get_event_id () const inline noexcept
Definition at line 462 of file pi_cuda.hpp.
get_execution_status() [1/2]
pi_int32 _pi_event::get_execution_status () const inline noexcept
Definition at line 428 of file pi_hip.hpp.
References is_completed(), is_recorded(), PI_EVENT_COMPLETE, PI_EVENT_RUNNING, and PI_EVENT_SUBMITTED.
get_execution_status() [2/2]
pi_int32 _pi_event::get_execution_status () const inline noexcept
Definition at line 444 of file pi_cuda.hpp.
References is_completed(), is_recorded(), PI_EVENT_COMPLETE, PI_EVENT_RUNNING, and PI_EVENT_SUBMITTED.
get_queue() [1/2]
pi_queue _pi_event::get_queue () const inline noexcept
Definition at line 416 of file pi_hip.hpp.
get_queue() [2/2]
pi_queue _pi_event::get_queue () const inline noexcept
Definition at line 432 of file pi_cuda.hpp.
get_queued_time() [1/2]
pi_uint64 _pi_event::get_queued_time () const
get_queued_time() [2/2]
pi_uint64 _pi_event::get_queued_time () const
Definition at line 389 of file pi_cuda.cpp.
get_reference_count() [1/2]
pi_uint32 _pi_event::get_reference_count () const inline noexcept
Definition at line 420 of file pi_hip.hpp.
get_reference_count() [2/2]
pi_uint32 _pi_event::get_reference_count () const inline noexcept
Definition at line 436 of file pi_cuda.hpp.
get_start_time() [1/2]
pi_uint64 _pi_event::get_start_time () const
get_start_time() [2/2]
pi_uint64 _pi_event::get_start_time () const
Definition at line 398 of file pi_cuda.cpp.
getOrCreateHostVisibleEvent()
pi_result _pi_event::getOrCreateHostVisibleEvent (ze_event_handle_t & HostVisibleEvent)
Definition at line 4954 of file pi_level_zero.cpp.
References createEventAndAssociateQueue(), cl::sycl::detail::pi::die(), PI_COMMAND_TYPE_USER, PI_SUCCESS, and ZE_CALL.
increment_reference_count() [1/2]
pi_uint32 _pi_event::increment_reference_count () inline
Definition at line 442 of file pi_hip.hpp.
increment_reference_count() [2/2]
pi_uint32 _pi_event::increment_reference_count () inline
Definition at line 458 of file pi_cuda.hpp.
is_completed() [1/2]
bool _pi_event::is_completed () const noexcept
is_completed() [2/2]
bool _pi_event::is_completed () const noexcept
Definition at line 372 of file pi_cuda.cpp.
Referenced by get_execution_status().
is_recorded() [1/2]
bool _pi_event::is_recorded () const inline noexcept
Definition at line 422 of file pi_hip.hpp.
is_recorded() [2/2]
bool _pi_event::is_recorded () const inline noexcept
Definition at line 438 of file pi_cuda.hpp.
Referenced by get_execution_status().
is_started() [1/2]
bool _pi_event::is_started () const inline noexcept
Definition at line 424 of file pi_hip.hpp.
is_started() [2/2]
bool _pi_event::is_started () const inline noexcept
Definition at line 440 of file pi_cuda.hpp.
isHostVisible()
bool _pi_event::isHostVisible () const inline
Definition at line 1085 of file pi_level_zero.hpp.
Referenced by _pi_context::decrementUnreleasedEventsInPool().
isProfilingEnabled()
bool _pi_event::isProfilingEnabled () const inline
Definition at line 1091 of file pi_level_zero.hpp.
References PI_QUEUE_PROFILING_ENABLE.
Referenced by _pi_context::decrementUnreleasedEventsInPool().
make_native() [1/2]
static pi_event _pi_event::make_native (pi_command_type type, pi_queue queue) inline static
Definition at line 461 of file pi_hip.hpp.
References _pi_event().
make_native() [2/2]
static pi_event _pi_event::make_native (pi_command_type type, pi_queue queue) inline static
Definition at line 477 of file pi_cuda.hpp.
References _pi_event().
Referenced by cuda_piEnqueueEventsWaitWithBarrier(), cuda_piEnqueueKernelLaunch(), cuda_piEnqueueMemBufferCopy(), cuda_piEnqueueMemBufferCopyRect(), cuda_piEnqueueMemBufferFill(), cuda_piEnqueueMemBufferMap(), cuda_piEnqueueMemBufferRead(), cuda_piEnqueueMemBufferReadRect(), cuda_piEnqueueMemBufferWrite(), cuda_piEnqueueMemBufferWriteRect(), cuda_piEnqueueMemImageCopy(), cuda_piEnqueueMemImageRead(), cuda_piEnqueueMemImageWrite(), cuda_piEnqueueMemUnmap(), cuda_piextUSMEnqueueMemAdvise(), cuda_piextUSMEnqueueMemcpy(), cuda_piextUSMEnqueueMemset(), cuda_piextUSMEnqueuePrefetch(), hip_piEnqueueEventsWaitWithBarrier(), hip_piEnqueueKernelLaunch(), hip_piEnqueueMemBufferCopy(), hip_piEnqueueMemBufferCopyRect(), hip_piEnqueueMemBufferFill(), hip_piEnqueueMemBufferMap(), hip_piEnqueueMemBufferRead(), hip_piEnqueueMemBufferReadRect(), hip_piEnqueueMemBufferWrite(), hip_piEnqueueMemBufferWriteRect(), hip_piEnqueueMemImageCopy(), hip_piEnqueueMemImageRead(), hip_piEnqueueMemImageWrite(), hip_piEnqueueMemUnmap(), hip_piextUSMEnqueueMemcpy(), hip_piextUSMEnqueueMemset(), and hip_piextUSMEnqueuePrefetch().
record() [1/2]
pi_result _pi_event::record ()
record() [2/2]
pi_result _pi_event::record ()
Definition at line 414 of file pi_cuda.cpp.
References cl::sycl::detail::pi::die(), PI_INVALID_EVENT, PI_INVALID_OPERATION, PI_INVALID_QUEUE, and PI_SUCCESS.
release() [1/2]
pi_result _pi_event::release ()
release() [2/2]
pi_result _pi_event::release ()
Definition at line 458 of file pi_cuda.cpp.
References PI_QUEUE_PROFILING_ENABLE, and PI_SUCCESS.
Referenced by piEnqueueKernelLaunch(), piEnqueueMemBufferMap(), piEnqueueMemBufferRead(), piEnqueueMemImageRead(), and piEnqueueMemUnmap().
start() [1/2]
pi_result _pi_event::start ()
start() [2/2]
pi_result _pi_event::start ()
Definition at line 354 of file pi_cuda.cpp.
References PI_QUEUE_PROFILING_ENABLE, and PI_SUCCESS.
wait() [1/2]
pi_result _pi_event::wait ()
wait() [2/2]
pi_result _pi_event::wait ()
Definition at line 446 of file pi_cuda.cpp.
Member Data Documentation
CleanedUp
bool _pi_event::CleanedUp = {false}
Definition at line 1125 of file pi_level_zero.hpp.
Referenced by EventRelease(), and _pi_queue::executeCommandList().
CmEventPtr
cm_support::CmEvent* _pi_event::CmEventPtr = nullptr
Definition at line 207 of file pi_esimd_emulator.hpp.
Referenced by piEventRelease(), and piEventsWait().
CommandData
void* _pi_event::CommandData
Definition at line 1111 of file pi_level_zero.hpp.
Referenced by cleanup(), and EventRelease().
CommandType
pi_command_type _pi_event::CommandType
Definition at line 1104 of file pi_level_zero.hpp.
Referenced by cleanup(), EventRelease(), and piEventGetInfo().
Completed
bool _pi_event::Completed = {false}
Definition at line 1131 of file pi_level_zero.hpp.
Referenced by piEventGetInfo().
Context
pi_context _pi_event::Context = nullptr
Definition at line 209 of file pi_esimd_emulator.hpp.
Referenced by EventRelease(), piEventGetInfo(), and piEventGetProfilingInfo().
HostVisibleEvent
pi_event _pi_event::HostVisibleEvent = {nullptr}
Definition at line 1084 of file pi_level_zero.hpp.
Referenced by _pi_ze_event_list_t::createAndRetainPiZeEventList(), EventRelease(), piEventGetInfo(), and piEventsWait().
IsDummyEvent
bool _pi_event::IsDummyEvent = false
Definition at line 210 of file pi_esimd_emulator.hpp.
Referenced by piEventRelease().
OwnerQueue
cm_support::CmQueue* _pi_event::OwnerQueue = nullptr
Definition at line 208 of file pi_esimd_emulator.hpp.
Referenced by piEventRelease().
OwnZeEvent
bool _pi_event::OwnZeEvent
Definition at line 1069 of file pi_level_zero.hpp.
Referenced by EventRelease().
Queue
pi_queue _pi_event::Queue = {nullptr}
Definition at line 1103 of file pi_level_zero.hpp.
Referenced by cleanup(), _pi_ze_event_list_t::createAndRetainPiZeEventList(), EventRelease(), piEventGetInfo(), piEventGetProfilingInfo(), piEventsWait(), and piextEventGetNativeHandle().
WaitList
_pi_ze_event_list_t _pi_event::WaitList
Definition at line 1117 of file pi_level_zero.hpp.
Referenced by cleanup().
ZeCommandList
ze_command_list_handle_t _pi_event::ZeCommandList
Definition at line 1099 of file pi_level_zero.hpp.
Referenced by _pi_queue::executeOpenCommandListWithEvent().
ZeEvent
ze_event_handle_t _pi_event::ZeEvent
Definition at line 1065 of file pi_level_zero.hpp.
Referenced by _pi_ze_event_list_t::createAndRetainPiZeEventList(), EventRelease(), _pi_queue::executeCommandList(), piEventGetProfilingInfo(), and piextEventGetNativeHandle().
ZeEventPool
ze_event_pool_handle_t _pi_event::ZeEventPool
Definition at line 1072 of file pi_level_zero.hpp.
Referenced by _pi_context::decrementUnreleasedEventsInPool().
The documentation for this struct was generated from the following files:
plugins/cuda/pi_cuda.hpp
plugins/hip/pi_hip.hpp
plugins/esimd_emulator/pi_esimd_emulator.hpp
plugins/level_zero/pi_level_zero.hpp
plugins/cuda/pi_cuda.cpp
plugins/hip/pi_hip.cpp
plugins/level_zero/pi_level_zero.cpp