DPC++ Runtime: plugins/level_zero/usm_allocator.cpp File Reference
usm_allocator.cpp File Reference
#include <algorithm>
#include <array>
#include <bitset>
#include <cassert>
#include <cctype>
#include <iomanip>
#include <iostream>
#include <list>
#include <memory>
#include <mutex>
#include <shared_mutex>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>
#include "usm_allocator.hpp"
#include <CL/sycl/detail/spinlock.hpp>
Classes
class settings::SetLimits
class Slab
class Bucket
class USMAllocContext::USMAllocImpl
Namespaces
settings
Functions
constexpr auto settings::operator""_B (unsigned long long x) -> size_t
constexpr auto settings::operator""_KB (unsigned long long x) -> size_t
constexpr auto settings::operator""_MB (unsigned long long x) -> size_t
constexpr auto settings::operator""_GB (unsigned long long x) -> size_t
static void * AlignPtrDown (void *Ptr, const size_t Alignment)
static void * AlignPtrUp (void *Ptr, const size_t Alignment)
static size_t AlignUp (size_t Val, size_t Alignment)
bool operator== (const Slab &Lhs, const Slab &Rhs)
std::ostream & operator<< (std::ostream &Os, const Slab &Slab)
bool enableBufferPooling ()
Variables
static constexpr size_t settings::MinBucketSize [SystemMemory::All] = {64, 512, 512, 512}
static constexpr size_t settings::CutOff = (size_t)1 << 31
static sycl::detail::SpinLock settings::PoolLock
static class settings::SetLimits settings::USMSettings
static const char * MemTypeNames [SystemMemory::All]
Function Documentation
AlignPtrDown()
static void* AlignPtrDown (void * Ptr, const size_t Alignment) static
Definition at line 307 of file usm_allocator.cpp.
Referenced by AlignPtrUp(), and USMAllocContext::USMAllocImpl::deallocate().
AlignPtrUp()
static void* AlignPtrUp (void * Ptr, const size_t Alignment) static
Definition at line 314 of file usm_allocator.cpp.
References AlignPtrDown().
Referenced by USMAllocContext::USMAllocImpl::allocate().
AlignUp()
static size_t AlignUp (size_t Val, size_t Alignment) static
Definition at line 325 of file usm_allocator.cpp.
Referenced by USMAllocContext::USMAllocImpl::allocate().
enableBufferPooling()
bool enableBufferPooling ()
Definition at line 1049 of file usm_allocator.cpp.
References settings::SetLimits::EnableBuffers, and settings::USMSettings.
Referenced by piMemBufferCreate(), and piMemRelease().
operator<<()
std::ostream& operator<< (std::ostream & Os, const Slab & Slab)
Definition at line 544 of file usm_allocator.cpp.
References Slab::getBucket(), Slab::getEnd(), Slab::getPtr(), and Bucket::getSize().
operator==()
bool operator== (const Slab & Lhs, const Slab & Rhs)
Definition at line 540 of file usm_allocator.cpp.
References Slab::getPtr().
Referenced by cl::sycl::kernel::operator!=().
Variable Documentation
MemTypeNames
const char* MemTypeNames[SystemMemory::All] static
Initial value:
= {
    "Host", "Device", "Shared", "SharedReadOnly"}
Definition at line 302 of file usm_allocator.cpp.
Referenced by USMAllocContext::allocate(), and USMAllocContext::deallocate().